### ISSUE TITLE
Questions about parser

### ISSUE THREAD

**Issue by DevSide** [evanw/esbuild#1012]
I'm trying to help transpiling stuff in the parser:
- I get an `invalid symbol reference` error when i use a ref inside `EIdentifier` in a statement
- I'm not sure when we should use `recordUsage` on a ref

Here is pseudo code where a function returns a new statement `return a = 0`
```go
func (p *parser) test () js_ast.Stmt { 
  ref := p.generateTempRef(tempRefNoDeclare, "")

  assign := js_ast.Assign(
    js_ast.Expr{Data: &js_ast.EIdentifier{Ref: ref}},
    js_ast.Expr{Data: &js_ast.ENumber{Value: 0}},
  )

  return js_ast.Stmt{Loc: p.Lexer.Loc(), Data: &js_ast.SReturn{Value: &assign}}
}
```

**Comment by evanw** [comment]
The parser has two phases and `generateTempRef` only works in the second phase, but you are trying to use it in the first phase. That's why you get `invalid symbol reference`. The `recordUsage` function also only works in the second phase.

What are you trying to do? Can you describe the problem you're having with esbuild?

**Comment by DevSide** [comment]
I see, thanks. I'll make a PR.
