### ISSUE TITLE
Typescript parsing error when there is ">=>" in source code

### ISSUE THREAD

**Issue by Shenmin-Z** [evanw/esbuild#1016]
Source code: 
```typescript
():Array<number>=>{return [1]}
```

When using esbuild:
```bash
❯ esbuild a.ts
 > a.ts: error: Expected "=>" but found ":"
    1 │ ():Array<number>=>{return [1]}
      ╵   ^

1 error
```

Problem seems to be gone when a space is added between `>` and `=>`

New source code: 
```typescript
():Array<number> =>{return [1]}
//              ^ add space here!
```

Result:
```
❯ esbuild a.ts
() => {
  return [1];
};
```

Thanks!

**Comment by evanw** [comment]
Thanks for the report. This was tripping up esbuild's TypeScript parser because the `>=` token was split into a `>` token and a `=` token because the `>` token is needed to close the type parameter list, but the `=` token was not being combined with the following `>` token to form a `=>` token. To fix this, esbuild needs to expand the `=` token into the following characters if possible, which can result in a `=>`, `==`, or `===` token. The fix for this will go out with the next release.
