### ISSUE TITLE
Spec violations with Optional Chaning

### ISSUE THREAD

**Issue by jridgewell** [evanw/esbuild#1019]
In digging through the transforms you're doing, I've noticed 2 spec violations in Optional Chaining:

1. Forced call of an optional member expression should propagate the object to the method:
   - https://bugs.chromium.org/p/v8/issues/detail?id=10024
    ```js
    const o = { m() { return this; } };
    assert.strictEqual((o?.m)(), o, 'receiver is passed to method');
    ```

2. Optional call of `eval` must be an indirect eval:
   - https://bugs.chromium.org/p/v8/issues/detail?id=10630
    ```js
    var a = 'global';
    var b = (a => eval?.('a'))('local');
    assert.strictEqual(b, 'global', 'indirect eval cannot see local scope');
    ```

**Comment by evanw** [comment]
Thanks for pointing these out. I think what happened here is that I referenced V8 and TypeScript when implementing this, but V8 has since changed its behavior. It looks like TypeScript still has the old behavior, meaning these syntax forms are now hazards for TypeScript users. I will change esbuild to align with V8's new behavior.
