### ISSUE TITLE
Shared dependencies between builds

### ISSUE THREAD

**Issue by joelmoss** [evanw/esbuild#1025]
One of the things I love about esbuild (apart from it being fast as hell!), is that it's low level nature means I can choose how to use it.

Now generally bundlers are built with single page apps in mind. But SPA's are not the only use for bundling your frontend code. I'm trying to use esbuild to build and bundle my code, but with code that is used on multiple pages, different times, and by multiple modules. This means that I need to be able to share dependency between entry points.

Now of course I know I can pass multiple entry points to esbuild to have them bundled. However, I may not always know which entrypoints that a page needs to use.

For example, I have a page that imports javascript module A, which in turn has a dependency on, and imports module B. The same page may or may not import module C, which also has a dependency on module B.

The problem arises when I import both module A and C into the same page. Because they have both been bundled with esbuild, and they both have a dependency on module B, they both include module B. This results in duplicated code, as module B is now imported twice.

Hopefully I've explained myself well enough, but I essentially need to know if it is possible to share dependencies between multiple entrypoints, but without bundling all the entry points together.

thanks

**Comment by lukeed** [comment]
I am not sure what could be done here? 

You would have to know ahead of time that module B is shared (or is likely to be shared) and bundle it separately so that A and C can mark B as `external` during their builds.

I may be wrong, but I think your only option is this more manual approach since (if I understand correctly) you're saying you cannot define all entrypoints upfront, which would allow esbuild to determine shared chunks -- via `bundle: true` and `splitting: true`

**Comment by joelmoss** [comment]
Yeah that's all I've thought of too.

However, it would be more efficient if A bundled B along with itself, instead of marking it as external. Then when C is imported, and it imported B, it can use the instance of B that A already imported.

This way, only two files are loaded (A+B and C), instead of three (A, B and C).

Of course, this would require the ability for other code to read/import from an already loaded module that is part of an esbuild bundle or chunk.

**Comment by evanw** [comment]
If you want to do this ahead of time, then you should be able to use esbuild's code splitting feature for this. Passing A and C to esbuild with code splitting enabled will automatically generate three output files with the shared code (i.e. B) in a third file that is imported from the other two. You don't need to tell esbuild anything about B because it will automatically figure out which code is shared by itself. Adding A to a page and then adding C later should share the same copy of B since the URL for B is the same. You would need to pass all entry points to esbuild at the same time to do this though. And keep in mind that the code splitting feature is still a work in progress and has some caveats at the moment.

If you want to do this on the fly at run time, then it either sounds like you're asking for things to actually not be bundled (i.e. be left as individual modules) in which case you don't need a bundler, or you're asking for things to be bundled on the fly in which case you'll need support from the server to send down a minimal bundle including only what you don't have already. Both of these use cases aren't what esbuild is designed for.

I believe the upcoming [resource bundles](https://github.com/WICG/resource-bundles) proposal would give you the on-the-fly server-generated minimal bundle thing, although it doesn't really do bundling. It just sends down modules individually. And TBD on if/when that ever becomes a real thing.

You could also look into [module federation](https://webpack.js.org/concepts/module-federation/) with Webpack, although that feature might be more designed to solve structural issues with huge organizations instead of being optimized for a specific bundling use case. I'm very unfamiliar with module federation but I'm mentioning it because from the little I have read about it, it sounds sort of like what you might be asking for.

**Comment by evanw** [comment]
I'm going to close this for the reasons stated above. Either this is done at bundle-time, in which case this is the code splitting feature already tracked by #16, or this is done at run-time, in which case either you need to not bundle your code or this needs server-side support which is out of scope of esbuild.
