### ISSUE TITLE
unneeded renaming for bundling

### ISSUE THREAD

**Issue by bobzhang** [evanw/esbuild#1027]
see `get2`, `getUndefined2` here
https://github.com/bobzhang/rescript-repack-demo/blob/master/bundle/map.mjs#L77

The input is https://github.com/bobzhang/rescript-repack-demo/blob/master/src/map.mjs

esbuild version 9.0.2

**Comment by evanw** [comment]
These variables are renamed to avoid a name collision, since there are two separate variables with the same name.

The following code generates a new variable and exports that new variable. It means the second variable will need to be renamed to avoid colliding with the first variable. This is what's causing `getUndefined` to become `getUndefined2`:

```js
import * as Belt_internalMapInt from "./belt_internalMapInt.js";
var getUndefined = Belt_internalMapInt.getUndefined;
export {getUndefined};
```

The following code re-exports the original variable instead. This means there is only ever a single variable, so it doesn't end up being renamed since there is no collision:

```js
export {getUndefined} from "./belt_internalMapInt.js";
```

These two code snippets are not semantically equivalent. The first code snippet is a "dead" export in that the exported value is a copy of the original variable's value. The copy isn't updated if the original variable is mutated. The second code snippet is a "live" export in that the exported value will change if the original variable is mutated.

If you want to avoid bloating your output with these additional variables, you should use the `export {} from` syntax instead of the `var; export {}` syntax for re-exports.

Also this renaming only affects local variables, not exports, so it should not have any impact on the semantics of your program. It's important for correctness that the linker has the ability to rename things to avoid name collisions. Even if you use the `export {} from` syntax (a good idea in this case to reduce bundle bloat), the variable may still be renamed if some other top-level variable in some other unrelated file in the bundle happens to also have the name `getUndefined`.

If this renaming is affecting the value of the `.name` property and you are relying on that value, you can enable the `keepNames` option to preserve the value of the `.name` property: https://esbuild.github.io/api/#keep-names.

**Comment by bobzhang** [comment]
Thanks for the explanation, it is very helpful.

> The copy isn't updated if the original variable is mutated.

This seems to happen rarely in practice, for this particular case, if we treat `Belt_internalMapInt` as a black box as an ES6 module, is there any chance that `Belt_internalMapInt.getUndefined` gets modified? 
It is not very clear to me since `getUndefined` is also an exported symbol.
If not, could esbuild optimize such case?

**Comment by evanw** [comment]
> if we treat Belt_internalMapInt as a black box as an ES6 module, is there any chance that `Belt_internalMapInt.getUndefined` gets modified?

Yes there is. That's how ESM works. Imports are live bindings in ESM. No, I'm not planning on optimizing this. These are not semantically equivalent. Rollup also doesn't optimize this, for example. I encourage you to use `export {} from` instead. You are writing a compiler, right? The compiler could use the `export {} from` syntax for exports.

**Comment by evanw** [comment]
Closing as "won't fix" for the reasons above.
