### ISSUE TITLE
Watch mode behavior on failed first builds

### ISSUE THREAD

**Issue by padmaia** [evanw/esbuild#1037]
I've noticed that watch mode only works if the first build is successful. Is this intentional?

My use case is a large repository with many apps and a single development server that lazily builds these apps in watch mode as they are requested. The server also establishes a web socket connection so the apps reload on successful rebuilds or render an error overlay if the build failed. Ideally the server could rely on esbuild's watch mode completely to know when to send these web socket messages, but currently I would have to set up my own watcher and retry starting esbuild in watch mode in the case where the build fails on the first try.

**Comment by evanw** [comment]
Just got a chance to look into this. It looks like it works with the CLI and Go APIs but not with the JavaScript API because the JavaScript API is designed to throw an exception when there are build errors. I'll need to think about how to solve this from an API design perspective.

**Comment by zaydek** [comment]
Would it make sense to inspect the thrown stack frame / continue on idempotent errors for now, and then refactor later?

**Comment by ggoodman** [comment]
Some of the different challenges around handling the state transitions are described here: https://github.com/evanw/esbuild/issues/814#issuecomment-779834583.

**Comment by evanw** [comment]
There's an interesting problem with doing this: #1063. If the initial build fails due to a plugin throwing an error, esbuild doesn't necessarily have enough information to know what to watch. In that case allowing watch mode to progress if the initial build fails could potentially leave watch mode in a broken state. Just linking these two issues because they seem related.

**Comment by lydell** [comment]
I used `esbuild --watch ...` but noticed my use case was too advanced for the CLI, so I looked into using the JS API. But due to this issue, `esbuild.build({ watch: true, ... })` is almost useless (ok, that’s overreacting 😅 ). It’s not uncommon to start build tools with errors in your code, for example when you pick up where you left off the previous day. Would be awesome if this could be improved!
