### ISSUE TITLE
Empty file bundles as `{ default: {} }` when imported via `import *`

### ISSUE THREAD

**Issue by mjackson** [evanw/esbuild#1043]
I wasn't sure the best way to provide a repro for this issue since it involves multiple files, so I made a small repo with a minimal test case here: https://github.com/mjackson/esbuild-empty-file-test

The issue is that it appears esbuild interprets `import *` differently than node's (and probably the browser's, though I didn't test it) native ESM loader.

If `a.mjs` is an empty file, in node (v12+) you get the following result:

```js
import * as a from './a.mjs';
console.log(a); // [Module] { } 
```

But when esbuild bundles that file, it generates a `default` export with a value of `{}`. So you get the following:

```js
import * as a from './a.mjs';
console.log(a); // { default: {} }
```

Happy to provide the repro in a different format if you prefer. Thanks!

**Comment by evanw** [comment]
This is deliberate behavior, and was added because there are some libraries that need this to work (not empty files specifically, but files with no exports). One example is the `@sheerun/mutationobserver-shim` package that used to assign to `module.exports` but that now assigns to `window` instead, and `@testing-library/dom` still contains a default import for that file. So treating it as a module would cause an unnecessary compile error in this case.

The bundling algorithm currently doesn't contain any logic that requires flagging modules as CommonJS vs. ESM beforehand. Instead it handles a superset and then sort of decides later if the module should be treated as CommonJS vs. ESM based on whether the module uses the `module` or `exports` variables (although this may change soon to checking for the `exports` keyword).

This is necessary to handle many real-world packages on npm with ESM code that are not flagged as ESM in a way that node would understand (i.e. not `"type": "module"` or `.mjs`) so node won't load them. This happened because historically people used tools that ran Babel to convert these to CommonJS modules on the fly. So these modules must be treated as ESM even though node's algorithm would consider them to be CommonJS.

However, this is a case where it's ambiguous whether something is a CommonJS module or an ESM module. This same issue comes up in TypeScript code too, since TypeScript also parses a superset like esbuild does. TypeScript's solution is to require you to mark the file as an ESM file with an empty export clause: `export {}`.

Can you say more about your use case? What use case do you have that needs an empty file be interpreted one way or the other?

**Comment by mjackson** [comment]
Thanks for the detailed explanation. Having dealt with many JS module issues myself in the past, I was pretty sure there was a good reason for the current behavior :)

> Can you say more about your use case? What use case do you have that needs an empty file be interpreted one way or the other?

Sure! I'm building a dev server that watches the filesystem for new and/or deleted "route" files. Each route file may contain a `default` export which is a React component. When the developer first creates a new file, it'll be empty. But I restart my incremental esbuild so I can reflect the new route that is present. When I `import *` from that file, I'd like to know there are no exports in it. Then I can show a default component instead of the one they haven't written yet.

> TypeScript's solution is to require you to mark the file as an ESM file with an empty export clause: export {}.

That's interesting. One workaround that I've been using is to load the file myself in a plugin (onLoad) and use `export {}` as its contents if it's empty. That works for now, so we can go ahead and close this if you'd like to keep the current behavior. I do think there is some value in matching native module loaders' behavior as closely as possible, but if it's just not possible given all the legacy npm code you have to deal with then I fully understand.

**Comment by zaydek** [comment]
On a somewhat related note, completely empty files are actually considered Svelte components (in Svelte). It’s a nice feature because you don’t need to worry about ripping out code or commenting and then your project breaking. Some more context [here](https://www.codingwithjesse.com/blog/the-simplest-svelte-component-is-an-empty-file).
