### ISSUE TITLE
[Question] asynchronous Multiple times execute the transform

### ISSUE THREAD

**Issue by aelbore** [evanw/esbuild#105]
I want to asynchronous execute multiple times service.transform is there any slow performance if everytime done execute on each transform i will stop the service? 
by the way keep up the good work :)

**Comment by evanw** [comment]
I haven't done performance measurements, but yes I assume it will be slower to start and stop the service for each transform since that creates and destroys a new process every time. Although it'll still probably be pretty fast compared to other libraries. Keep in mind that process startup overhead may be different on different operating systems.

**Comment by aelbore** [comment]
@evanw thanks for the reply. keep up the nice work.
