### ISSUE TITLE
A moment of appreciation

### ISSUE THREAD

**Issue by immanuelfodor** [evanw/esbuild#1055]
I'd like to take a moment of appreciation to the work being done here, and the effort that goes into not only the improvement of the tool but also such long and descriptive release notes. I've just seen https://github.com/evanw/esbuild/releases/tag/v0.10.0 and I was like: WOW, man, this is extraordinary. And not just this release but all previous ones. 

Thank you @evanw and all the contributors!

**Comment by iamakulov** [comment]
Absolutely supporting this. Release notes, the documentation, and especially the cadence of updates are just exceptional. Thank you for your work!

**Comment by evanw** [comment]
It's good to hear how much the work that goes into esbuild is appreciated. I'm also really grateful for the positive tone and deep and useful feedback on the issue tracker. This is my first big open source project and I didn't expect such helpful feedback and guidance from the community. So thank you all too!

I'm going to close this since it's not an issue with esbuild, but thank you very much for posting.
