### ISSUE TITLE
Incremental build and file loader

### ISSUE THREAD

**Issue by Ventajou** [evanw/esbuild#1059]
Hi @evanw could you please clarify the behavior of the file loader during an incremental build? Does it check the source file date to see if it has changed?

Also, if a plugin load callback specifies the file loader, would it be possible for the plugin to also return a flag indicating the file hasn't changed? I have a plugin that optimizes images and it would probably save a lot of time to not rewrite the images that haven't changed.

**Comment by evanw** [comment]
> Hi @evanw could you please clarify the behavior of the file loader during an incremental build? Does it check the source file date to see if it has changed?

Yes. All loaders do this. If the file metadata is sufficiently old (currently older than 3 seconds) and the file metadata hasn't changed since the last build, the file contents will not be reloaded from the file system.

> Also, if a plugin load callback specifies the file loader, would it be possible for the plugin to also return a flag indicating the file hasn't changed? I have a plugin that optimizes images and it would probably save a lot of time to not rewrite the images that haven't changed.

No, this is not possible. Currently esbuild always rewrites all output files. Although if your plugin returns the same data for the same path as in the previous build, esbuild may skip doing some extra work internally. For example, returning the same JavaScript code as the previous build means esbuild will reuse the previous AST instead of parsing the JavaScript again.

**Comment by Ventajou** [comment]
Thanks for the explanation, makes sense
