### ISSUE TITLE
Passing objects or arrays for node globals to define produces invalid code

### ISSUE THREAD

**Issue by remorses** [evanw/esbuild#1080]
This is a regression happened in `0.11.0`

Compiling the following code
```js
console.log(module.x)
```

With 

```js
const { build } = require('esbuild')

build({
   entryPoints: ['entry.js'],
    define: {
        module: '{}',
    },
    format: 'esm',
    outdir: 'out',
})
```

Produces

```js
var __commonJS = (cb, mod) => () => (mod || cb((mod = {exports: {}}).exports, mod), mod.exports);
var require_entry = __commonJS((exports, module) => {
  init_define_module();
  console.log("ciao");
  console.log(module.x);
});
export default require_entry();
```

Which will give `init_define_module is not defined` when run

If you instead pass a primitive value to define (for example a string or number), `module.x` will remain `module.x` (no replacement)

**Comment by evanw** [comment]
Thanks very much for reporting this. The problem here is that the definition file is being removed from the bundle because it's unused, but the call to the absent wrapper function is still being generated. This wasn't a problem with CommonJS wrapper closures because they are always considered to have side effects and tree shaking is disabled for them, but the new ESM wrapper closures still support tree shaking and can actually be completely removed. The fix will be in the next release.
