### ISSUE TITLE
Module not initialised causing runtime issue

### ISSUE THREAD

**Issue by SamyPesse** [evanw/esbuild#1088]
I'm trying to upgrade from 0.8.53 to 0.10 / 0.11.2 and I'm encountering a blocking issue, without any changes to the code, I have a runtime issue (Node JS environment):

```
TypeError: Cannot read property 'something' of undefined
    at /.../dist/index.js:11740:57
    ...
```

While looking at the code basically

```typescript
import { webConfig } from '@company/app-config'

...
webConfig.something // this line is failing
...
```

in `@company/app-config`, we have the following structure (we want to import in priority `webConfig.functions.ts` using esbuild option `resolveExtensions: ['.functions.tsx', '.functions.ts', '.tsx', '.ts']`) :

```
index.ts
webConfig.functions.ts
webConfig.ts
```

Looking at the bundled code, it looks like:

<img width="521" alt="Screenshot 2021-03-30 at 14 52 39" src="https://user-images.githubusercontent.com/845425/112991587-9442d900-9167-11eb-9a59-67da225e62a4.png">

The issue is that `init_index_functions` is never called so `webConfig` stays `undefined`.

I'm going to try writing a minimal reproducible example. But looking at the bundled code, it looks like the issue is the same for all imports coming from a "prioritised" extension (ex `.web.ts` or `.functions.ts`), maybe there is a regression there?

**Comment by evanw** [comment]
Thanks for the report. It looks like this is related to packages that have `"sideEffects": false` in their `package.json` file. I'm currently working on a fix.

> I couldn't find any `require` in the modules using this package, to justify the wrapper.

An `import()` could also cause this. Both `require()` and `import()` are ways to dynamically import a module and therefore require a wrapper to ensure correct evaluation order.

**Comment by dalcib** [comment]
Yes, the react-native-web has `"sideEffects": false`.
I couldn't find any `import()` either.

**Comment by evanw** [comment]
I'm still working on fixing this and it looks like it's not a super quick fix. The bug is with some long-standing behavior (files without side effects containing only re-exports are not included) combined with some new behavior (lazy-ESM files need to call their wrapper closure as a side effect).

In the meantime you might be able to get this to work with [`--tree-shaking=ignore-annotations`](https://esbuild.github.io/api/#tree-shaking) if you need to. I would recommend not upgrading until this is fixed though since that would be less work on your part.
