### ISSUE TITLE
How do you use define?

### ISSUE THREAD

**Issue by ribrdb** [evanw/esbuild#1091]
I want to have a variable that is false when I don't use esbuild, but that I can change to true using esbuild --define.

I tried something like this:
```
const USE_FOO = false;
if (USE_FOO) {
...
}
```
with `esbuld --define:USE_FOO=true`, but my if statement doesn't get modified.
How do I define USE_FOO so that it works with `--define:`?

**Comment by zaydek** [comment]
It would help to know if you are programming for Node or the browser because that changes whether you can rely on environmental variables or `window`.

I suppose if you didn’t define `USE_FOO`, you could do `if ("USE_FOO" in process.env)` or `if ("USE_FOO" in window)`. (Again, this depends on your environment)

I recommend searching previous issues for `define` because I think this question has been asked previously with different nuances.

**Comment by ribrdb** [comment]
I'm using the browser.

**Comment by zaydek** [comment]
OK this is working for me:

```
zaydeks-MBP:retro-test-drive zaydek$ echo 'if (window.USE_FOO) console.log("Hello")' | esbuild --define:window.USE_FOO=false
if (false)
  console.log("Hello");
zaydeks-MBP:retro-test-drive zaydek$ echo 'if (window.USE_FOO) console.log("Hello")'
if (window.USE_FOO) console.log("Hello")
zaydeks-MBP:retro-test-drive zaydek$
```

It looks like you can’t do dynamic statements like `"USE_FOO" in window` but you can use `window.USE_FOO`.

There might be a better way to do this but that should get you started.

**Comment by zaydek** [comment]
You can refer to the documentation here for some more ideas: https://esbuild.github.io/api/#define.

**Comment by evanw** [comment]
That's a good recommendation. Another way to do it could be something like this:

```js
const USE_FOO = typeof BUNDLER_USE_FOO !== 'undefined' && BUNDLER_USE_FOO;
if (USE_FOO) {
...
}
```

and then you can define `BUNDLER_USE_FOO` (or not) however you'd like.

Closing this issue as this and the above comments seem like a sufficient answer to this question, and this isn't an issue with esbuild. Feel free to continue to ask follow-up questions about this here if you'd like.
