### ISSUE TITLE
FuseBox benchmark comparison

### ISSUE THREAD

**Issue by NN---** [evanw/esbuild#11]
https://fuse-box.org/

**Comment by joseluisq** [comment]
FuseBox user here. It would be interesting to incorporate such benchmark especially against latest v4.x (`fuse-box@next`).

**Comment by evanw** [comment]
I took a stab at this: 236194e5249f4c0fef6cde349de32d2029055474. I'm not familiar with FuseBox and it took a while to figure out how to get it to work. I'm reluctant to benchmark against `fuse-box@next` because I'd like to pin the benchmark to a specific version to make it reproducible. So I tested the version you get when you follow the setup instructions which is `fuse-box@3.7.1`.

I think I've set everything up right as far as I can tell, but FuseBox actually takes **_over 8 minutes_** on my benchmark. The generated file is 6.48mb which much bigger than the other bundlers (they are all around 5.9mb). The generated source map is also incorrect, so I'm not sure if it should actually count as a successful production build. I also had to raise the memory ceiling on `node` because FuseBox actually crashed with an out-of-memory error the first time it ran my benchmark.

I'm not adding these benchmark results to the readme yet because they are so far away from the other results that I'm concerned that I may be doing something wrong. Can someone who's familiar with FuseBox double-check my setup?

**Comment by evanw** [comment]
Never mind. I think I'll go with `fuse-box@next` after all because the current release of FuseBox has too many problems. It looks like `fuse-box@next` at least generates a correct source map, and does so in a faster amount of time. It's still the slowest bundler with a 3 minute build, but that's a lot better than 8 minutes. The output is still much bigger than it should be at 6.55mb but that's a problem with FuseBox, not with this benchmark. I'll add it to the benchmark.

**Comment by evanw** [comment]
Here's the result:

![](https://user-images.githubusercontent.com/406394/74712675-b7b4f980-51db-11ea-8ad3-ddb4e5f77ef8.png)

**Comment by joseluisq** [comment]
Cool!
It would be also interesting for the fuse-box folks. https://github.com/fuse-box/fuse-box/issues/1539
