### ISSUE TITLE
Remove unused export

### ISSUE THREAD

**Issue by egoist** [evanw/esbuild#110]
ESBuild removed the types but kept the export, which results in SyntaxError.

![](https://user-images.githubusercontent.com/8784712/81891944-736ba680-95dc-11ea-96ee-15b2ec159bf6.png)

`esbuild v0.3`

**Comment by evanw** [comment]
Good catch.

Hmm, this one's tricky. Matching the TypeScript compiler's code generation for this exactly seems to potentially depend on actually evaluating types, which esbuild's approach to TypeScript compilation doesn't permit (esbuild treats type annotations as whitespace). For example, you can technically do this and the TypeScript compiler won't remove the export:

```ts
declare let Foo: any;
export {Foo};
```

I'm not sure if this case is important or not, since doing this causes the TypeScript compiler to generate invalid code. I think it could potentially be sufficient for real-world code bases to just remove exports for things that aren't local symbols. That will certainly fix cases like this at least. I'm going to try that and see how it goes.
