### ISSUE TITLE
onResolve without file extension

### ISSUE THREAD

**Issue by tannerkrewson** [evanw/esbuild#1104]
My use case is to transform a set of imports like
- `foomodule/dist/a` -> `foomodule/src/a`
- `barmodule/dist/a` -> `barmodule/src/a`
etc.

Currently, I'm using the plugin API and `onResolve` to accomplish this, and it works great!

With `onResolve`, I have to explicitly append the file extension to the path, or it will fail. This would be fine, but my project is a mix of `.js` and `.ts` files. 😢 

So, I've resorted to using [`resolve` with the opts.extensions](https://github.com/browserify/resolve#resolveid-opts-cb) set to `['.ts', '.js']` and it works just fine. It slows the build down by about 20% though, and it's kind of a nasty looking chunk of code 😆. 

Is there any better way to achieve this with esbuild? 😄 

I could also potentially do this with aliases, but I would have to list out every `foomodule`, `barmodule`, etc. which would be too much.

**Comment by evanw** [comment]
The plugin API is the intended way to do custom stuff like this. A 20% slowdown doesn't sound bad to me especially since esbuild is still so much faster than alternatives. If you really need your plugin to go faster you could consider calling esbuild's API from Go instead.

If aliases potentially work in your case too but you don't want to write them out by hand, you could also consider writing code to programmatically generate the aliases.

**Comment by tannerkrewson** [comment]
That's what I figured; thank you! Mostly just wanted to get this down in Google to help anyone who has a similar problem of trying to migrate from webpack's [`externals.modules`](https://webpack.js.org/configuration/resolve/#resolvemodules). 😉 

Good call, I think using something like [esbuild-plugin-alias](https://www.npmjs.com/package/esbuild-plugin-alias) and programmatically generating them would be a cleaner solution.

And I was being dramatic by saying 20% increase... because that's only .2 seconds in our project 😆 . Sure beats the over two minutes it was before! 😬
