### ISSUE TITLE
Explore using tinygo to shrink browser wasm? 

### ISSUE THREAD

**Issue by Jarred-Sumner** [evanw/esbuild#1111]
[tinygo](https://tinygo.org/webassembly/webassembly/) is a go compiler for embedded & wasm environments

It sounds like it could be interesting to shrink the wasm size and also _maybe_ to improve runtime performance (but that is unclear, could be worse perf)

I spent about an hour trying to get esbuild to build & run via tinygo with little progress. I'm not very familiar with go's build system and I think its not correctly ignoring files that are supposed to be excluded by wasm (including when passing `--tags=js wasm`

Lots of standard library functions aren't implemented. It seems extremely tedious to get this to work. 

At one point, I got something to build and it produced a 110 KB esbuild.wasm file -- which is big enough to indicate it has stuff in it and small enough to show promise versus 6 MB. But `WebAssembly.instantiate` would error with `WebAssembly Instantiation: Import #0 module="module" error: module is not an object or function`

Feel free to close if doesn't seem worthwhile to explore

**Comment by evanw** [comment]
This has been brought up previously as well: https://github.com/evanw/esbuild/issues/836#issuecomment-781254520. I don't think it'll work. From the [TinyGo docs](https://tinygo.org/lang-support/):

> The `recover` builtin is not yet supported. Instead, a `panic` will always terminate a program and `recover` simply returns nil.

There are a few different places where esbuild relies on `recover` so TinyGo is not an option. They also say this:

> Also, they have not been optimized for performance and will cause linear lookup times in some cases.

So I suspect that even if you did get it working, performance would also be worse since esbuild relies a lot on map lookups. That said, I have not tried it myself, so feel free to try it if you'd like. Just saying that I have a strong suspicion that it's not a worthwhile exploration.

**Comment by Jarred-Sumner** [comment]
Makes sense

**Comment by aamironline** [comment]
Assumed, TinyGo won't support it due to the cost involved. However, instead of rejecting the TinyGo entirely, can't ESBuild use an alternate approach when the target compiler is TinyGo?
