### ISSUE TITLE
accept require() with non string literal input

### ISSUE THREAD

**Issue by wcastand** [evanw/esbuild#113]
I'm trying to build an CLI and i request a glob pattern to find all the files and then require them to exec the code.

when i try to build with esbuild, i get this error : 
`The argument to require() must be a string literal`

From other issues, I've seen that you want to analyze the dependencies and that's why esbuild requires string literal.

but in my case i need to require dynamically, is there a way to do this or esbuild won't work for CLI that use require to load files based on a pattern?

this is currently what i do: 
```
;(async () => {
  await new Promise((r) => {
    glob(
      resolve(cli.input[0] || './*.test.?(tsx|ts)'),
      {},
      async (err, files) => {
        if (err) throw err
        if (files.length === 0) console.log(`No files found.`)
        await Promise.all(
          files.map(async (f) => {
            const outfile = `.ttaped/${relative('.', f.replace('.ts', '.js'))}`
            const options: BuildOptions = {
              stdio: 'inherit',
              entryPoints: [f],
              outfile,
              minify: true,
              platform: 'node',
              bundle: true,
            }

            await build(options)
              .then(() => require(resolve(outfile)))
              .catch(() => process.exit(1))
          }),
        )
        fs.rmdirSync(resolve('.ttaped'), { recursive: true })
        r(true)
      },
    )
  })
})
```

**Comment by evanw** [comment]
Thanks for this issue. I agree that this is a good escape hatch to have, and that it would let more real-world code be bundled with esbuild. That code may crash at run time if the files aren't there or if the bundle is used in the browser, but at least the bundling process would succeed. This could be useful in cases like this or in cases where the crash may not matter (e.g. it's in code that is never called).

I'm not quite sure what the best way of adding this is yet. Rollup just passes this straight through without a warning, which seems somewhat dangerous. But it might be the simplest way to solve this. I'll have to think more about this.

**Comment by wcastand** [comment]
thank for taking the time to answer, let me know if I can help in any way :)

**Comment by kritzware** [comment]
This is the only issue preventing esbuild from being able to build our medium-large production codebase, due to a couple of dependencies using require in this way (which is out of our control). 

I would also be happy to help on this if needed 👍

**Comment by evanw** [comment]
As of version 0.5.3, using require() with non string literal input is now a warning instead of an error. Hopefully this unblocks some use cases for esbuild that were previously blocked.

**Comment by jawadwaseem-10p** [comment]
Has there been any workaround proposed for this?

**Comment by zaydek** [comment]
@jawadwaseem-10p I opened this issue recently: #661 because I ran into this problem myself. Dynamic imports may be a solved problem in the future, but for now I think we have to lean into the plugin API. At least, if you want synchronous imports like when using `require`.

I see two options: You can either generate temporary files that have static imports and then rerun esbuild on that or you can create a plugin that resolves some special identifier. Generating temporary files works for some use-cases but not all in my experience. Sometimes you really do want dynamic imports.

Here’s my current thinking, albeit a little fuzzy:

You create an onResolve plugin that resolves an identifier. This identifier is something like `%%SECRET_INTERNALS%%` or whatever. The thing is, your dynamic imports are generally for more than one file (like `require("./src/*")`. What an onResolve plugin can do is resolve to a different file on every pass. So your esbuild would have its own state, and every time it gets invoked, it simply rotates to the next item in a list, for example (e.g. `file-a.js`, `file-b.js`, ...).

I guess you could even simplify the identifier to be something like `./src/*` but then the filter for onResolve could intercept code you didn’t expect it to. That’s why I like the idea of some custom identifier only you’re supposed to know.
