### ISSUE TITLE
esbuild.exe is always seen as a virus or trojan tool by 360 Security Guard on Windows 10

### ISSUE THREAD

**Issue by fengnex** [evanw/esbuild#1149]
As the above topic says, I wonder whether esbuild.exe does have a certain detrimental effect on my computer. If it does not affect anything, what's the cause 360 Security Guard treats it like that?

360 Security Guard is a famous anti-virus software like Noton that is especially famous in China.

**Comment by evanw** [comment]
This is a problem with 360 Security Guard, not a problem with esbuild. So I'm going to close this issue.

Windows anti-virus software is well-known for causing trouble with software development due to false positives. If this software is preventing you from using the pre-built esbuild binary, you can either [submit the esbuild binary as a false positive to 360 Security Guard](https://www.360totalsecurity.com/help/360-total-security/#collapse-faq-3-2) yourself, [build esbuild from source yourself](https://esbuild.github.io/getting-started/#build-from-source), use the slower [WebAssembly version of esbuild](https://esbuild.github.io/getting-started/#install-the-wasm-version) which will likely bypass your faulty anti-virus scanner, or decide to use another tool instead of esbuild.
