### ISSUE TITLE
Checking for existence of require in if throws warning

### ISSUE THREAD

**Issue by k15a** [evanw/esbuild#1153]
Sentry checks for `require` inside an if to throw an if no `appName` is provided and it can't require Electron. Unfortunately, esbuild thinks that this is a dynamic `require` and throws a warning.

<img width="787" alt="Screen Shot 2021-04-14 at 14 40 35" src="https://user-images.githubusercontent.com/20357450/114712216-233b1e00-9d30-11eb-9c7c-8799ccd367fd.png">

Is it possible to not warn in case some code is just checking for the existence of require?

**Comment by evanw** [comment]
> Is it possible to not warn in case some code is just checking for the existence of require?

Well this code isn't checking for the existence of `require`. This code will crash if `require` is not defined. Checking for the existence of `require` would involve using `typeof require` instead.

I should probably just remove this warning since people keep giving me grief about it. The alternative is to silently generate potentially broken bundles. I'll change esbuild to do that instead.

**Comment by k15a** [comment]
> would involve using typeof require instead

Ohh yes, my bad. I would still expect esbuild to not warn there. Thank you very much!
