### ISSUE TITLE
[Help] Why esbuild seems bundling for node instead of browser?

### ISSUE THREAD

**Issue by Lcfvs** [evanw/esbuild#1162]
Hi,

Actually, I'm on the version **0.11.12**

Into my project's `package.json`, I'm trying to enforce an import replacement, depending on the `platform`

```
  "exports": {
    "@lcf.vs/dom-engine/lib/backend.js": {
      "browser": "@lcf.vs/dom-engine/lib/worker.js"
    }
  },
```

When I'm bundling for the browser, `esbuild --bundle --minify --platform=browser --outdir=./dist --watch test.js` , I have a lot of strange errors like this
```
Could not resolve "XXX" (set platform to "node" when building for node)
``` 

I maybe make a mistake... but I don't understand why esbuild tries to bundle like if I declared `--platform=node`

Any ideas, please?

**Comment by evanw** [comment]
This only happens when `XXX` is the same name as a module that's built in to node. For example, `XXX` might be `fs`, the file system library that comes with node: https://nodejs.org/api/fs.html. The error here is `Could not resolve "XXX"`.

If you're trying to bundle a package for the browser that is meant for node, then you might have trouble if that package tries to import node-specific libraries. You will need to find some way of either resolving the import path to a browser-friendly alternative, or marking the path as external (works if that `require` call never ends up being evaluated in the browser). See also https://esbuild.github.io/getting-started/#bundling-for-the-browser.

The part in parentheses after the error is a hint to tell you that if you're trying to bundle for node instead of the browser, you should set `--platform=node` instead. Feel free to ignore the hint if it doesn't apply to you.

**Comment by Lcfvs** [comment]
Hi @evanw,

Thanks for your answer but, in my case, I'm trying to build an isomorphic demo using my [dom-engine](https://github.com/Lcfvs/dom-engine).

Into my project, I use node by default but the goal is to use the same code to be able to run it into a `ServiceWorker`.

The node version is using https://github.com/Lcfvs/dom-engine/lib/backend.js, where I search a way to replace it, by esbuild, by the worker version https://github.com/Lcfvs/dom-engine/lib/worker.js (which doesn't import anything) 

Actually, the closest solution I found is to make something like this
`esbuild --bundle --minify --format=esm--outdir=./dist --watch test.js`
 ```js
const path = typeof process !== 'undefined' && process.versions?.node
  ? `@lcf.vs/dom-engine/lib/backend.js`
  : `/@lcf.vs/dom-engine/lib/worker.js`

const engine = await import(path)
```

But the bundle can't be used into a worker, because of the `import` and even if it worked, it creates an additional request, delaying the execution.

There is a better approach, please?

**Comment by Lcfvs** [comment]
The information is still interesting but don't be hurry, I found a solution with my `@etchedjs/dispatcher` :P

**Comment by evanw** [comment]
The fully general solution to path replacement in esbuild is to use a plugin: https://esbuild.github.io/plugins/#resolve-callbacks. You should be able to use a plugin to match on `@lcf.vs/dom-engine/lib/backend.js` and replace it with `@lcf.vs/dom-engine/lib/worker.js` at build time.

**Comment by Lcfvs** [comment]
Thanks a lot :)
