### ISSUE TITLE
What's up with (0, import_module.funcName)() in compiled output?

### ISSUE THREAD

**Issue by eloff** [evanw/esbuild#1163]
Hi Evan,

Since upgrading to the latest master code, I've noticed some code that was previously compiled as `import_module.funcName()` is now compiled as `(0, import_module.funcName)()`. Is that intentional? I looked up how the comma operator works in JavaScript, but that did not shed any light on it. It seems the code would be shorter and no different in functionality if compiled the same way it was previously. Am I missing something?

**Comment by evanw** [comment]
It's because of how `this` works in JavaScript. `(0, import_module.funcName)()` is equivalent to `funcName()` but not to `import_module.funcName()` because in the last case, the receiver is `import_module` instead of `undefined`. So `funcName()` must be transpiled to `(0, import_module.funcName)()` when `funcName` comes from `import {funcName}`. All ESM transpilers do this including Babel and more recently TypeScript.

See https://github.com/microsoft/TypeScript/issues/35420 for an example of why using `import_module.funcName()` instead of `(0, import_module.funcName)()` introduces bugs.

**Comment by eloff** [comment]
Subtle! Thanks for explaining that!
