### ISSUE TITLE
provide changedFiles, outputFiles, rebuildTime information on watch.onRebuild results 

### ISSUE THREAD

**Issue by rizkyramadhan** [evanw/esbuild#1165]
Currently esbuild `watch.onRebuild` `result` argument only provide these information: 
` 'warnings', 'metafile', 'rebuild', 'stop'` .

It would be nice if we can get: 
- `changedFiles` that triggers rebuild
-  resulting `outputFiles `
-  `rebuildTime`: how much time does it take to rebuild

 This is useful when implementing custom hot reload logic for my project.

**Comment by evanw** [comment]
> * `changedFiles` that triggers rebuild

For performance, the build is started immediately whenever a change is detected, so there is only ever a single "changed file." It doesn't wait to finish scanning all of the watched files first before building because doing that would be a pretty big performance hit. If you need that you may want to use your own file watching library instead of the built-in one.

> * resulting `outputFiles`

You should be able to get this with `metafile` and `write: false`. See https://esbuild.github.io/api/#metafile and https://esbuild.github.io/api/#write.

> * `rebuildTime`: how much time does it take to rebuild

This shouldn't be necessary to implement hot reloading, right?

**Comment by rizkyramadhan** [comment]
Well, yeah. Actually I did what you suggest and it works. And rebuild time, I need it to brag with my peers how fast esbuild is!

**Comment by dalcib** [comment]
You can use a plugin

```javascript
{
    name: 'perf',
    setup(build) {
      build.onStart(() => {
        console.log('build started')
        console.time('Esbuild Time:')
      })
      build.onEnd((result) => {
        console.log(`build ended with ${result.errors.length} errors`)
        console.timeEnd('Esbuild Time:')
      })
}
```
