### ISSUE TITLE
Using esbuild with a library that is not a module

### ISSUE THREAD

**Issue by Marvelanda** [evanw/esbuild#1168]
Hey everyone!

I've got the following issue:
We use an external library (janus gateway) that is not exported as a module and that expects another library (WebRTC Adapter) to be available as a global variable. This library does not use 'import' to access to the functionality of webrtc-adapter, instead it expects a global object called just 'adapter' for that.

In case of webpack we can do something like that:

```js
module.exports = {
  plugins: [
    new webpack.ProvidePlugin({ adapter: ['webrtc-adapter', 'default'] })
  ]
}
```

Also janus.js does not use 'export' to provide its functionality to others, instead it creates a global variable called 'Janus' and expects consumers to use it.

In case of webpack it is possible to do this:

```js
module.exports = {
  module: {
    rules: [
      {
        test: require.resolve('janus-gateway'),
        loader: 'exports-loader',
         options: {
           exports: 'Janus',
         },
      }
    ]
  }
}
```

Is it possible in case of esbuild?

Thanks in advance!

**Comment by evanw** [comment]
I might not understand what you're saying because it sounds like what you're trying to do doesn't need any plugins. If a library creates a global variable called `Janus` and you want to use the library, then I think you should be able to just import the library and reference the `Janus` variable from the global scope. And if you are using a library that expects a global object called `adapter` to exist, then it seems to me like you'd need to assign to the global variable called `adapter` before running the code for that library. Neither of these things should need any special support from a bundler to work.

If you want to "capture" imports for a given package such as `janus-gateway` and redirect that to an automatically-generated shim file that does something custom such as exporting a copy of a global variable, you can use esbuild's plugin API for that. Documentation is here: https://esbuild.github.io/plugins/#using-plugins.

If it's important to replace all references to the global variable `adapter` with a reference to something else without actually assigning to that global variable, you should be able to do this with the "inject" feature and a small shim file you write. Documentation is here: https://esbuild.github.io/api/#inject.

**Comment by Marvelanda** [comment]
Thanks for the answer. Actually this library expects a global dependency called adapter as well as this library creates globals which are needed to be exported, but it doesn't support imports and exports. For expample, jquery also expexts $ to be a global variable. If I understood you correctly it can be done only by creating a plugin, right?

**Comment by evanw** [comment]
If you want to import and use a library that assigns to a global variable called `Janus` without a needing plugin, I'd expect something like this to work:

```js
import 'the-library'
useTheLibrary(Janus)
```

If you want to import a library that needs information passed in via a global variable `adapter` without a needing plugin, I'd expect the following options to work:

1. 
    ```js
    window.adapter = something
    require('the-library')
    ```

2. 
    ```js
    window.adapter = something
    import('the-library')
    ```

3. 
    ```js
    import './assign-to-adapter'
    import 'the-library'
    ```

    where the file `assign-to-adapter.js` looks something like this:

    ```js
    window.adapter = something
    ```

Note that the following wouldn't work, because import statements are "hoisted" in JavaScript and run first before other statements:

```js
// This doesn't work because the "import" statement would run first, before the assignment
window.adapter = something
import 'the-library'
```

**Comment by Marvelanda** [comment]
> import 'the-library'
useTheLibrary(Janus)

Unfrotunately this won't work as the library doesn't provide any exports, it just defines the Janus object globally.
And that is the main difficulty.

**Comment by evanw** [comment]
Another way to write that would be this:

```js
import 'the-library'
useTheLibrary(window.Janus)
```

In JavaScript if you access a variable such as `Janus` that isn't defined in the module's scope, the access check will continue on to the global scope. This is why for example you can reference global variables such as `Object` without needing to import them first (e.g. `Object.keys()`). You can also use `window.Object` instead of using a bare `Object` reference since they are equivalent. Similarly, you can use `window.Janus` instead of `Janus` if you prefer. But both of those are ways to access a global variable.

**Comment by Marvelanda** [comment]
I tried your variant and unfortunately the following error occures " Cannot find name 'Janus' ". 
I don't know how it actually works inside the library, I only can rely on the documentation.
But in my case I need some functionality similar to the one that is provided by export-loader plugin in webpack:
```
  module: {
    rules: [
      {
        test: require.resolve('janus-gateway'),
        loader: 'exports-loader',
         options: {
           exports: 'Janus',
         },
      }
    ]
  }
```
In this code we add a rule that says to find a module called 'janus-gateway' and add an export of Janus to this module (as the library does not contain exports)

**Comment by evanw** [comment]
I took a look at the `janus-gateway` package and it looks like it doesn't export a global variable after all. It only contains a local variable without any exports. In that case, you could make it work by using a plugin to add `export {Janus}` to the file:

```js
const esbuild = require('esbuild')

esbuild.build({
  entryPoints: ['entry.js'],
  bundle: true,
  plugins: [{
    name: 'make-janus-gateway-work',
    setup(build) {
      build.onLoad({ filter: /janus-gateway/ }, async (args) => {
        let contents = await require('fs').promises.readFile(args.path, 'utf8')
        contents += 'export {Janus}'
        return { contents }
      })
    },
  }],
})
```

where `entry.js` looks like this:

```js
import { Janus } from 'janus-gateway'
console.log(Janus)
```

I assume this is something similar to what the webpack `exports-loader` plugin does.

**Comment by Marvelanda** [comment]
many thanks for your time and a provided plugin, but unfortunately this plugin still doesn't work as expected - because of it my laptop started to brake down and I had to restart it :)
will try to dig in into the plugin creation and solve the problem somehow

**Comment by evanw** [comment]
I'm going to close this since it's been a while and it sounds like this question has been answered.

**Comment by seb3s** [comment]
Just a note to other readers to say that the solution provided by evanw works for me
