### ISSUE TITLE
A report about output size difference compared to Webpack

### ISSUE THREAD

**Issue by rogemus** [evanw/esbuild#1171]
Hi, I'm tryining to migrate our current build setup to esbuild and in project, we are using Styled-Component, TS, and React. I found out that esbuild does not minify code same as webpack and the output file is bigger (around 100kb). 
My config
```
const esbuild = require('esbuild');

esbuild.build({
  entryPoints: ['src/packages/admin/index.tsx'],
  entryNames: '[dir]/admin.bundle',
  bundle: true,
  loader: {
    '.otf': 'file',
    '.svg': 'dataurl',
  },
  outdir: 'admin',
  logLevel: 'info',
  minify: true,
  define: {
    'process.env.NODE_ENV': '"production"',
    'process.env.DEBUG': 'false',
  },
}).catch(() => process.exit(1))
```

Minified code from esbuild
<img width="1027" alt="Screenshot 2021-04-20 at 14 52 00" src="https://user-images.githubusercontent.com/9271549/115399372-6a218b80-a1e8-11eb-8f10-33e6941a23dc.png">

Minified code from webpack

<img width="1027" alt="Screenshot 2021-04-20 at 14 51 49" src="https://user-images.githubusercontent.com/9271549/115399386-6d1c7c00-a1e8-11eb-9e11-7cc8668644b6.png">

Is there something that I'm doing incorrectly?

**Comment by evanw** [comment]
The section of code you've highlighted is actually smaller in esbuild due to newlines taking one byte instead of two, arrow functions not being converted to regular functions, and template literals not being converted to function calls.

If there is a difference that large, then it's likely due to either some additional files being included with esbuild that aren't included with webpack, or some package that has been tuned for webpack's specific flavor of tree shaking that esbuild doesn't tree shake.

You can use esbuild's metafile feature to see what input files ended up in your output file (https://esbuild.github.io/api/#metafile) and I believe you can use webpack's stats feature to see the same thing for webpack (https://webpack.js.org/configuration/stats/). That might give you more information about this problem.

**Comment by evanw** [comment]
I’m closing this since it’s unactionable and it’s been a week without a response. Potential next steps are described in the comment above.
