### ISSUE TITLE
Feature Request: leave `process.env.NODE_ENV` in place.

### ISSUE THREAD

**Issue by samouri** [evanw/esbuild#1187]
**summary**
👋 Hi @evanw. First off, thank you for creating esbuild! It is a joy to use.

I am currently trying to use `esbuild` solely as a `typescript` transpiler, but am running into an issue.  I haven't been able to figure out how to mark the variable `process.env.NODE_ENV` as an external. In fact, each instance is being automatically defined to either `false` or `true` (as the docs indicate will happen).

Is there any way to leave the variable untouched?

Thanks!

**Comment by evanw** [comment]
This happens because the output defaults to being for the browser, and React (and many other libraries that have copied React) have strangely decided to check `process.env.NODE_ENV` at run-time, even though browsers don't have a `process` global, so esbuild has to remove this or React code will crash. But this can be configured by setting the platform to something other than `browser`: https://esbuild.github.io/api/#platform.

**Comment by samouri** [comment]
That worked like a charm! Thank you 🥇
