### ISSUE TITLE
Missing plugin hooks

### ISSUE THREAD

**Issue by barak007** [evanw/esbuild#1188]
Hello,
Stylable is a css based solution to style components it's like css modules but with type safety in the css world.
My use case is to create a plugin for the Stylable framework and I'm missing some hooks to do so.
 
1. Hook to inspect the module/dependency graph (importers, dependencies). This will allow me to sort the css correctly when writing a css bundle file.
2. After the dependency graph is set a way to modify the assets/module. This will allow to perform optimizations for the entire application and in dev mode assign order to the individual modules.

I can expand on each if needed.

Is it possible to have those hooks? if not are there any workarounds that you can think of?

**Comment by evanw** [comment]
I'm planning to add a "build end" callback so plugins can inspect and/or change the build result object before it is returned. That hasn't been added yet though.

> if not are there any workarounds that you can think of?

I believe at the moment this may be possible by doing this after the build API returns instead of within a plugin. You would set `metafile: true` and then get the graph from the `metafile` property on the build result. You could modify any output files you want by just modifying the files on the file system, or by setting `write: false` and then writing the files yourselves. In the future when there is a "build end" callback for this, you could move that logic into a plugin.

**Comment by evanw** [comment]
The latest release includes `onEnd` callbacks. See the release notes for details: https://github.com/evanw/esbuild/releases/tag/v0.11.15. It would be interesting to hear if this plus `metafile` does what you need or not.

**Comment by barak007** [comment]
I will check soon thanks

**Comment by evanw** [comment]
Closing this as this should now be possible via `onEnd`. See https://esbuild.github.io/plugins/#end-callbacks for documentation.
