### ISSUE TITLE
is it possible to specify special characters in --define ?

### ISSUE THREAD

**Issue by mreinstein** [evanw/esbuild#120]
e.g.

```bash
npx esbuild --bundle input.js --define:__DATE__=2020-05-18 --define:__VER__=v0.4.2
```

throws this error:

```bash
error: Invalid define: --define:__DATE__=2020-05-18
```

I've tried wrapping `2020-05-18` in single and double quotes, but this doesn't seem to matter. Any advice?

**Comment by evanw** [comment]
The value for `--define` must be either a valid identifier or a JSON atom (null/boolean/number/string). So if it's a string, you'll need to quote it.

With standard unix shells you'll have to escape the quotes so that the shell doesn't strip them. There are a few different ways of escaping quotes for these shells:

```sh
$ echo "foo"
foo
$ echo \"foo\"
"foo"
$ echo '"foo"'
"foo"
```

I'd expect this to work assuming you're using one of these shells:

```sh
npx esbuild --bundle input.js --define:__DATE__=\"2020-05-18\" --define:__VER__=\"v0.4.2\"
```

Does that work for you?

Also if you need to run the same commands in different shells with incompatible quoting rules (e.g. on both macOS and Windows), then you should consider writing a [build script](https://github.com/evanw/esbuild#running-a-build) instead.

**Comment by mreinstein** [comment]
> Does that work for you?

yes that worked, thank you!
