### ISSUE TITLE
environment detection broken in esbuild 0.11.11

### ISSUE THREAD

**Issue by achingbrain** [evanw/esbuild#1202]
Hat tip to @rvagg for the [detective work](https://github.com/ipfs/js-ipfs-unixfs/pull/116#issuecomment-825646616) on this one but how esbuild transpiles code changed somewhere between `0.11.10` and `0.11.11` which broke the style of environment detection [dirty-chai](https://www.npmjs.com/package/dirty-chai) (and others, presumably) uses.

I've put a small repro case together here: https://github.com/achingbrain/esbuild-dirty-chai

It works with `0.11.10` but errors with `0.11.11`.

I'm not quite sure what would have caused this, there's nothing obvious to my eye in the release notes for `0.11.11`.

**Comment by evanw** [comment]
I believe it's this change in [0.11.11](https://github.com/evanw/esbuild/releases/tag/v0.11.11):

> Remove warnings about non-bundled use of `require` and `import`

From your investigation, it looks like this library is relying on `typeof require === 'function'` being replaced by true by the bundler, which esbuild is no longer doing. The code that does that was probably tied up with the `require` warning code that was removed.

**Comment by evanw** [comment]
Here's what other bundlers do for this:

| | Webpack | Parcel | Rollup |
|---|---|---|---|
| `typeof require` | `"function"` | `"function"` | `typeof require` |
| `typeof exports` | `"object"` | `"object"` | `"object"` |
| `typeof module` | `typeof module` | `typeof module` | `"object"` |
| `typeof require == 'function' && require` | (a function that throws) | `ReferenceError: require is not defined` | (a function that throws) |

Presumably esbuild should try to match Webpack since it's used more widely than the other two. Probably the simplest way to solve this would be to include a stub `require` function if the output format is `iife` or `esm` and replace all non-bundled references to `require` with that function. This should not be done if the output format is `cjs`.

**Comment by rvagg** [comment]
> stub require function if the output format is iife or esm and replace all non-bundled references to require with that function

+1 to that, the (semi formal) notion that CJS has this thing called `require` around is baggage that we can't really get beyond and no amount of trying to rewrite it is going to catch all of the use-cases here. Whether it throws or not, its existence is commonly used for CJS feature detection.

But having said that, this specific pattern is extremely common and special-casing it wouldn't be such a terrible thing. >=7 years ago this was in all of our code and this iteration came out of the push to make AMD a thing so it had maximal compatibility:

```
(function (dirtyChai) {
    if (typeof require === 'function' && typeof exports === 'object' && typeof module === 'object') {
      module.exports = dirtyChai;
    } else if (typeof define === 'function' && define.amd) {
      define(function () {
          return dirtyChai;
      });
    } else {
      chai.use(dirtyChai);
    }
}(function dirtyChai(chai, util) {
```

It was eventually whittled down to remove the AMD cruft once we realised that wasn't going to catch on as broadly as they hoped. Browserify and friends just piggy-back on this pattern, this was peak module-system-detection and it's everywhere still.
