### ISSUE TITLE
QUESTION : Comments about libraries included in the bundle

### ISSUE THREAD

**Issue by Tazeg** [evanw/esbuild#1210]
I can see in the non minified bundle that comments are added to tell where the code is from. Example : 

```js
  // node_modules/axios/lib/helpers/bind.js
  var require_bind = __commonJS((exports, module) => {...

  // node_modules/axios/lib/utils.js
  var require_utils = __commonJS((exports, module) => {...
```

I am really happy about this. But i coudn't find anything about this in the documentation.
1) I would like to know if it will always be or if it may disappear in future releases. I need it.
2) Is there a way to prepend or append some code to those comments, like this : 

```js
  // My included comment 
  // node_modules/axios/lib/helpers/bind.js
  var require_bind = __commonJS((exports, module) => {...
```
If it is not actually possible, I don't request a feature, I can code it by myself with a script.

The reason is that i will add `// javascript-obfuscator:enable` for my own code, and `disable` for third libraries.

Thanks you for this great tool.

**Comment by evanw** [comment]
There is no support for general-purpose comment handling in esbuild. I can think of some hacks that might sort of work but they probably wouldn't be that robust.

If you need to do per-file processing, I would recommend doing it on the files before they are bundled instead of afterward. This can be done with a plugin, which can then check for the `// javascript-obfuscator:enable` comment: https://esbuild.github.io/plugins/#load-callbacks.

**Comment by Tazeg** [comment]
So, let's write a plugin for https://github.com/javascript-obfuscator/javascript-obfuscator ;)

**Comment by evanw** [comment]
Closing since I consider comment preservation to be out of scope. Feel free to write a plugin for your use case if you would like to.
