### ISSUE TITLE
How to build a ui package

### ISSUE THREAD

**Issue by Dolov** [evanw/esbuild#1214]
I'm developing a ui package and use babel and tsc to build it, but slow
so i want to use esbuild to replace babel and tsc
Can you give me some advice on how to pack it with esm and cjs
thanks for your time

**Comment by evanw** [comment]
Docs are here: https://esbuild.github.io/getting-started/. See also https://esbuild.github.io/api/#format-commonjs and https://esbuild.github.io/api/#format-esm.

**Comment by Dolov** [comment]
> Docs are here: https://esbuild.github.io/getting-started/. See also https://esbuild.github.io/api/#format-commonjs and https://esbuild.github.io/api/#format-esm.

Is there has an api can transform a dir files like ./node_modules/.bin/babel src --out-dir lib

**Comment by evanw** [comment]
No, there is not. There is only an API for bundling and an API for transforming a single file at a time. You can use the single-file API to do this but you will have to derive the list of input files yourself (e.g. using `find` or a glob). There may also be some features of Babel that esbuild doesn't have because esbuild is not intended as a Babel replacement.
