### ISSUE TITLE
Feature request: support constant value for `jsxFragment` option (like in @babel/transform-react-jsx).

### ISSUE THREAD

**Issue by idlist** [evanw/esbuild#1217]
Hi, 

I'm experimenting using Mithril with jsx and esbuild for a while and found this issue.

The `jsxFragment` of Mithril is not a function, but a constant string `'['`. When using babel (and webpack), I can set the `@babel/transform-react-jsx` plugin as:

```javascript
"@babel/plugin-transform-react-jsx", {
  "pragma": "m",
  "pragmaFrag": "'['"
}
```

But with esbuild, I cannot set the config as
```javascript
{
  'jsxFactory': 'm' // this line works well
  'jsxFragment': '"["' // this line would cause error:
  // Invalid JSX fragment: "\"[\""
}
```
or
```javascript
{
  'jsxFactory': 'm' // this line works well
  'jsxFragment': "'['" // this line would cause error:
  // Invalid JSX fragment: "'['"
}
```
Instead, I need to define a variable in the entry file `index.js` as
```javascript
m.Fragment = '['
```
and set the config as 
```
{
  'jsxFactory': 'm'
  'jsxFragment': 'm.Fragment'
}
```

This `jsxFragment` syntax might not be in the standard of jsx, but it would be appreciated if the feature could be added as it may make the configuration more straightforward. Thanks.

**Comment by evanw** [comment]
The JSX support in esbuild was implemented by following TypeScript's implementation, and TypeScript doesn't allow you to do this:

> error TS18035: Invalid value for 'jsxFragmentFactory'. '"["' is not a valid identifier or qualified-name.

So that's why a string is not allowed here. However, this value is just passed to the factory function as an argument instead of being called so I don't see why a string couldn't be allowed. This seems like something esbuild can add support for.
