### ISSUE TITLE
Feature Request: `writeFiles` option or `returnBundle`

### ISSUE THREAD

**Issue by Arcath** [evanw/esbuild#1221]
Over at [mdx-bundler](https://github.com/kentcdodds/mdx-bundler) we use esbuild with `write: false` so that we can return the bundled mdx to users. With the latest release (3.3.1) users can now specify a `cwd` option to tell esbuild where the root of their bundle is, instead of relying on our `inMemory` plugin to inject strings as files.

This new feature has opened up a world of possibilities but in my testing I'm running into an issue with images.

Using the `dataurl` loader with the images is working fine but ideally I'd like to output my images as files in the `out` directory. Obviously setting `write: true` breaks mdx-bundler and leaving it `false` is causing it throw errors in Next.JS because the refrenced images don't exist.

I can see two options here, 

1. add a `writeFiles` option so that the files loader can be told to write files even when the bundler isnt.

or

2. add a `returnBundle` option so that we can use `write: true` and still get the bundled files. This does have the added step on our part of clearing out the written js but thats not too big an issue.

Hopefully this all makes sense.

**Comment by evanw** [comment]
I'm confused. If you do `write: false` and you want the files written as well, can't you just write them with e.g. `fs.writeFile`? Or if you're doing `write: true` and you want the file contents, can't you just get the contents with `fs.readFile`? Another option could be to use an on-load plugin instead of or in addition to the built-in `file` loader to do whatever custom stuff you need for your image files.

**Comment by Arcath** [comment]
Yeah the more I thought about it the more I turned to just reading in the file if we needed. I've got it working in this PR https://github.com/kentcdodds/mdx-bundler/pull/34 and its great!

Thanks again for making esbuild! It's the backbone of mdx-bundler and its letting us do some impressive stuff.
