### ISSUE TITLE
Bug: global this is optimized to void 0, which will lead to runtime errors.

### ISSUE THREAD

**Issue by cookiengineer** [evanw/esbuild#1225]
In the source code, I'm using a way to detect a global variable that's checking against `global`, `window` and then fallsback to `this`. In the bundled code of esbuild, the `this` part is optimized to `void 0` (which is `undefined`) and therefore will throw some errors in the fallback case of using the global scope as a definition scope.

Why is this important? "Sandboxing" in Browsers is the reason. I had to implement helper methods like `isString()`, `isArray()` etc in order to check against data types that are transferred across sandboxes (or iframes in the Web Browser case). In this scenario something like `instanceof` will fail as it's checking against a datatype that's defined as a unique Function template in the current sandbox.

So `window.Array` !== `other_window.Array` and in nodejs, the same applies when using separate Context instances in v8.

In order to fix this, I've built a little gluecode library that offers checks and exports of the same datatypes (along polyfills for Buffer etc). In my case however, this transpilation scenario seems to fail, as it would break in environments where only the `globalThis` is present (like it is the case in nodejs-compatible embedded runtimes like jerryscript, or when embedding `libnode.so` on an Android App).

## How to reproduce:

Source Code:

```javascript
export const Array = (typeof global !== 'undefined' ? global : (typeof window !== 'undefined' ? window : this)).Array;

if (typeof Array.isArray !== 'function') {

	Array.isArray = function(arr) {
		return Object.prototype.toString.call(arr) === '[object Array]';
	};

}

export const isArray = Array.isArray;
```

Transformed Outfile (target: `es2020` and format: `esm`):

```javascript
const Array = (typeof global !== "undefined" ? global : typeof window !== "undefined" ? window : void 0).Array;
if (typeof Array.isArray !== "function") {
  Array.isArray = function(arr) {
    return Object.prototype.toString.call(arr) === "[object Array]";
  };
}
const isArray = Array.isArray;
export {
  Array,
  isArray
};
```

**Comment by evanw** [comment]
I do not consider behavior you described to be a bug. The top-level value of `this` is `undefined` in ECMAScript modules, and the code you wrote is considered an ECMAScript module because of the `export` keyword. So replacing `this` with `undefined` is necessary to be faithful to ECMAScript module semantics. Although esbuild doesn't warn about this, other bundlers such as Rollup do warn about this (and will warn about your code above and also replace `this` with `undefined`).

I believe this is specifically because ECMAScript modules are always evaluated in strict mode ([section 10.2.1 of the ES6 specification](https://262.ecma-international.org/6.0/#sec-strict-mode-code)):

> Module code is always strict mode code.

and strict mode functions do not coerce `undefined` to the global object ([Annex C of the ES6 specification](https://262.ecma-international.org/6.0/#sec-strict-mode-of-ecmascript)):

> If <b>this</b> is evaluated within <a href="https://262.ecma-international.org/6.0/#sec-strict-mode-code">strict mode code</a>, then the <b>this</b> value is not coerced to an object. A <b>this</b> value of <b>null</b> or <b>undefined</b> is not converted to the global object and primitive values are not converted to wrapper objects. The <b>this</b> value passed via a function call (including calls made using <code><a href="https://262.ecma-international.org/6.0/#sec-function.prototype.apply">Function.prototype.apply</a></code> and <code><a href="https://262.ecma-international.org/6.0/#sec-function.prototype.call">Function.prototype.call</a></code>) do not coerce the passed this value to an object (<a href="https://262.ecma-international.org/6.0/#sec-ordinarycallbindthis">9.2.1.2</a>, <a href="https://262.ecma-international.org/6.0/#sec-function.prototype.apply">19.2.3.1</a>, <a href="https://262.ecma-international.org/6.0/#sec-function.prototype.call">19.2.3.3</a>).

The new [`globalThis`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) property is intended to be a portable way to reference the global object, and could be something to look into. Lack of support for `globalThis` in older browsers could be an issue but there is [a shim for `globalThis`](https://github.com/es-shims/globalThis). You could also consider escaping strict mode by evaluating code in the global scope. For example, you can use the `Function` constructor:

```js
let globalThisRef = new Function('return this')()
```

**Comment by cookiengineer** [comment]
I was actually also reading up on this, it seems that most of the embedded runtimes (jerryscript and others) are kind of spec-violating in this matter; as they have support for import/export but don't have support for globalThis (yet) and seem to execute most things in the same scope.

PS: Thanks much for the detailed reply. I was assuming this fallback behaviour would be the same across all Browsers, as back then when I was verifying it, I was testing it in an outdated Safari 10ish version where module support was pretty new.

So I guess in my case it's better to use `globalThis` instead, and shim it beforehand so that it's guaranteed to be the same across all potential environments.
