### ISSUE TITLE
Bug: exported constants in global scope "leak out" in bundled outfiles

### ISSUE THREAD

**Issue by cookiengineer** [evanw/esbuild#1226]
When transpiling a file that contains `const Datatype` in the "global scope", they are automatically transpiled to `var Datatype` statements, which will lead to memory leaks once they are included and used in legacy environments.

When using `target: [ 'es2020' ]`, all `let` statements in the code are untouched, so I would argue that this is a misoptimization. `const` is used across the code, too, but only in nested function scopes.

Optimized code where the `var Array2` would leak out if included in embedded environments, which was previously `export const Array = (...)`:

```javascript
var Array2 = (typeof global !== "undefined" ? global : typeof window !== "undefined" ? window : void 0).Array;
if (typeof Array2.isArray !== "function") {
  Array2.isArray = function(arr) {
    return Object2.prototype.toString.call(arr) === "[object Array]";
  };
}
```

**Comment by evanw** [comment]
Can you share the rest of your esbuild API call arguments? Is bundling enabled? And what output format are you using? AFAIK under no circumstances should bundled code ever be run in the global scope:

* For `format: 'iife'` the output should be wrapped in a closure by esbuild to isolate it from the global scope.
* For `format: 'cjs'` the run-time CommonJS wrapper should mean the code doesn't run in the global scope.
* For `format: 'esm'` the code should be run in module scope by the run-time, not in the global scope.

Note that the format may be implied by the platform setting, and the platform setting defaults to browser.

**Comment by cookiengineer** [comment]
@evanw I was using `format: 'esm'` for the buildSync() call.

**Comment by evanw** [comment]
If you are using `format: 'esm'` then you must run the output as an ECMAScript module in your JavaScript engine. This is usually something you have to do explicitly because the default is usually not to run as an ECMAScript module, since they are new. In node you would use the `.mjs` extension and in the browser you would add `type="module"` to your script tag.

If you do this, `var` should not create a global variable because it's declared in a module scope, not the global scope. It would be a bug in your JavaScript engine if using `var` inside a module created a global variable since the private variables inside unrelated modules would collide with each other.

Here's a simple example for node (the `.mjs` extension causes node to run the file as an ECMAScript module):

```
$ cat example.mjs
var test = 123
console.log(test)
console.log(global.test)

$ node example.mjs
123
undefined
```

If you are running code in the global scope then you should use `format: 'iife'` instead of using `format: 'esm'`.

Are you actually experiencing this issue? If so, what JavaScript engine are you using?

**Comment by evanw** [comment]
Closing since this is working as intended, and since there was no response.

From #1225 it sounds like you're using JerryScript. It looks like the way to trigger module-mode is to use `JERRY_PARSE_MODULE`. If local variables inside a module are exposed as global variables in that VM then that's a bug with JerryScript, not with esbuild.
