### ISSUE TITLE
Bug: Class object misses keys

### ISSUE THREAD

**Issue by molszews** [evanw/esbuild#1228]
Hi, after switching to esbuild following code behaves in a different way than before:
```
class ContactInfoDto {
    firstName; lastName;
}

const contactInfo = new ContactInfoDto();
Object.keys(contactInfo).forEach(k => console.log(k));
```
In esbuild for some reason `contactInfo` object has no keys, while in babel `firstName` and `lastName` are in place.

**Comment by evanw** [comment]
This should be correct as long as the code is JavaScript. It won't be correct if this code is TypeScript, but that's because that's the way the official TypeScript compiler works (esbuild is just matching the behavior of the official TypeScript compiler here). So I'm assuming you're compiling this code as TypeScript. Let me know if that's not the case and, if not, what target environment(s) you have configured.

TypeScript implemented class fields before they were standardized in JavaScript and then got stuck with the incorrect behavior for class fields when they were ultimately specified differently. The TypeScript compiler requires you to enable `"useDefineForClassFields": true` in your `tsconfig.json` file to disable the incorrect behavior, so esbuild does as well. TypeScript's documentation for this is here: https://www.typescriptlang.org/tsconfig#useDefineForClassFields.

**Comment by molszews** [comment]
you are correct, setting `useDefineForClassFields` fixed the case, thanks
