### ISSUE TITLE
Bug:I am using `minify:true` in the compress my code 

### ISSUE THREAD

**Issue by Hunterib** [evanw/esbuild#1231]
> Example:

```typescript
function is() {
  let userID = "1122";
  let id = userID === null ? 0 : userID;

  let mylist = [1, 2];
  let targetList = null != mylist ? mylist : [0, 0];
}
is();
```

> outfile.js

```javascript
function e(){let l="1122",i=l===null?0:l,t=[1,2],n=t??[0,0]}e();

```

> The correct result should be the output

```javascript
function e(){let l="1122",i=l==null?0:l,t = [1, 2],n = t != null ? t : [0, 0]}e();
```

**Comment by evanw** [comment]
The output looks correct to me. `t ?? []` is equivalent to `t != null ? t : []` but is shorter, which is why it's being used when minification is enabled. `??` is the [nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator). If you are running your code in an environment that doesn't support `??`, then you should be setting the target environment to tell esbuild about that: https://esbuild.github.io/api/#target.

**Comment by Hunterib** [comment]
Thanks for answering my question, my problem has been solved
