### ISSUE TITLE
How to use unit test runners on a React component? (jest / mocha / @web/test-runner / etc)?

### ISSUE THREAD

**Issue by gaggle** [evanw/esbuild#1237]
Hi, I've been really impressed with ESBuild, thanks for making it available!

I can't manage to make unit-testing work though, so I'm asking here to see if I am perhaps missing something. I'm looking to be able to test React components in a Typescript project, but despite pouring many hours into this I can't seem tie Typescript, React, ESBuild, and a test-runner together successfully!

I've no preference for runners, it can be Jest, or Mocha, or @web/test-runner, or any other runner, but at this point I feel I've tried 'em all without luck. As an example, here's the error that occurs I run with Jest and @testing-library/react:

```
  SyntaxError: Unexpected token '<'
    > 6 | import logo from './react.svg'
        |                  ^
```

That indicates I've not made Jest work correctly with ESBuild, because this works in runtime because ESBuild has an SVG loader specified. But I can't see what I need to do to make it all play together.

(FWIW this specific problem [can be seen in this branch](https://github.com/gaggle/exploring-the-monorepo/tree/jest-esbuild-error), it occurs when running `npm test`)

I don't mean to ask you to debug Jest, but I'm asking here to understand if you have examples or suggestions of ways that should allow test runners to work with ESBuild?

**Comment by evanw** [comment]
I have no idea how to configure Jest or how the `esbuild-jest` package works, but it looks like you may not have configured it correctly? This line here looks like it's only configured to transform `.ts` and `.tsx` files, not `.svg` files:

```js
  transform: {
    '^.+\\.tsx?$': [
      'esbuild-jest', { sourcemap: true, loader: { '.svg': 'file' } }]
  },
```

Maybe that's the issue? Also TypeScript code appears to still be transformed if I comment out those lines entirely, so maybe those lines don't have any effect at all? Sorry, I have no idea how this works. This seems more like a question for whoever wrote `esbuild-jest`. I see you've opened https://github.com/aelbore/esbuild-jest/issues/31 so I'll let the conversation continue over there.

I've used Mocha a bit, although not with esbuild, so I'm a little familiar with Mocha. Each test is just a call to the global `it` function. I imagine it should be pretty straightforward to just run something like Mocha on a bundled file from esbuild. You could create a single entry point that imports all of your tests, bundle that entry point with esbuild, then just run `mocha <your-bundled-file>.js`. Mocha would run your bundle after injecting `it` into the global scope so all of your tests should work. And presumably Mocha can use source maps to report errors in the original unbundled input files.

The benefit of something like this is that you'd be able to get started right away without too much debugging, you can reuse most of the esbuild settings from your main build, and you wouldn't have any package other than esbuild in between you and the test runner so the setup is simpler.

I'm going to close this since this isn't an issue with esbuild, but people should feel free to still comment here if they have relevant experience to share.
