### ISSUE TITLE
Can't use JS API on Windows

### ISSUE THREAD

**Issue by brundonsmith** [evanw/esbuild#1239]
I'm attempting to call out to esbuild (v0.11.17) via the NodeJS API, on Windows 10

Esbuild is working fine on my machine when I invoke it via CLI, both from the local node_modules and the global one

When I try and call `build()` from a NodeJS project:
```javascript
// compiler.js

import { build } from "esbuild";

build({
    entryPoints: [ "entry.js" ],
    outfile: "out.js",
})
```

I get:
```
node:events:342
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\brundolf\git\bagel\esbuild.exe ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)     
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)     
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {        
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:\\Users\\brundolf\\git\\bagel\\esbuild.exe',
  path: 'C:\\Users\\brundolf\\git\\bagel\\esbuild.exe',
  spawnargs: [ '--service=0.11.17', '--ping' ]
}
```

My directory structure is:
```
git/bagel/
  node_modules/
    [this is where esbuild lives]
  build/
    compiler.js [this is the node file calling the API]
```

I've tried:
- Deleting and rebuilding both node_modules and package-lock.json
- Moving compiler.js out of the build/ directory
- Installing esbuild globally

**Comment by evanw** [comment]
I haven't seen this particular error before. The code to find the path to `esbuild.exe` is [here](https://github.com/evanw/esbuild/blob/a9ccb35d083f2dbe7904411a2c7efcf22f06dea0/lib/npm/node.ts#L44-L46):

```js
   return [path.join(__dirname, '..', 'esbuild.exe'), []]; 
```

That JavaScript code should have ended up in the file `C:\Users\brundolf\git\bagel\node_modules\esbuild\lib\main.js` so `__dirname` should be `C:\Users\brundolf\git\bagel\node_modules\esbuild\lib` and `__dirname\..\esbuild.exe` should be `C:\Users\brundolf\git\bagel\node_modules\esbuild\esbuild.exe`. However, the error message sounds like it's looking in `C:\Users\brundolf\git\bagel\esbuild.exe` instead. Perhaps given that information, you can figure out on your end why it's looking in the wrong spot?

One guess: are you bundling esbuild into your code and then trying to run it? That won't work because then `__dirname` will be wrong (it will no longer be inside of the esbuild package). If you are bundling your code you will have to mark esbuild as external so that it's not included in the bundle. Then this should work.

**Comment by brundonsmith** [comment]
I am bundling it actually (using esbuild 🙂). I think that was the problem

It's a tricky case; I understand why it can't actually be bundled, because it calls out to a native binary, but it's also not hard to imagine people who use the esbuild API bundling their NodeJS apps. Not sure what the best solution is; maybe a note in the docs would be warranted?

**Comment by evanw** [comment]
Yes. I'll have the library throw an error in this case.

**Comment by brundonsmith** [comment]
Awesome. Thanks, and thank you for the great project!
