### ISSUE TITLE
How to show original file in stack trace?

### ISSUE THREAD

**Issue by vhadianto** [evanw/esbuild#1257]
I'm trying out esbuild (from Webpack) and have successfully migrated all the options that I have in Webpack to esbuild.

One thing that I can't figure out though is how to show the original file in in the stack trace when we have an Uncaught Exception?

In Webpack we can see the original files in the stack trace but in esbuild all I see is the single output file. To trace it back to the original file I have to open the bundled file and figure out where it is in the source. Not a big issue but it's just one more step to do during development.

Is this possible? I looked at the Simple and Advanced option and not seeing anything that may turn this on.

No minification at the moment.

**Comment by evanw** [comment]
It sounds like you need to enable source maps: https://esbuild.github.io/api/#sourcemap.

**Comment by evanw** [comment]
Closing since this question was answered and there was no response. Feel free to ask follow-up questions if you have any. Make sure not to miss https://esbuild.github.io/api/#using-source-maps.

**Comment by vhadianto** [comment]
Hi @evanw 

Sorry was working in our current release branch which was still in Webpack so haven't had a chance to have a look. I just switched back to master and I tried the following setting:

`sourcemap: "inline"`

This is for the dev cycle btw so there's no minification and I don't care (too much) about file size. For prod deployment I'm trying out terser.

So the output is still looking like this (I'm artificially creating a TypeError here): 

```
"TypeError: Cannot read property 'bar' of undefined",
        "    at RunControl.run (/var/task/index.js:819489:64)",
        "    at /var/task/index.js:821699:16",
        "    at /var/task/index.js:844124:16",
        "    at /var/task/index.js:844040:16",
        "    at /var/task/index.js:6883:13",
        "    at /var/task/index.js:844072:9",
        "    at /var/task/index.js:843385:16",
        "    at /var/task/index.js:843276:9",

<snip>
```

compared that with Webpack (no minification):

```
 "TypeError: Cannot read property 'bar' of undefined",
        "    at RunControl.run (webpack:///../events/lib/run/run-control.js?:182:61)",
        "    at eval (webpack:///../events/lib/handler/tick.js?:271:14)",
        "    at eval (webpack:///../rdb/index.js?:1439:14)",
        "    at eval (webpack:///../rdb/index.js?:1343:16)",
```

As you can see with Webpack I know exactly where the code is.

Can we do the same with esbuild?

**Comment by evanw** [comment]
What platform are you on? In node you need the `--enable-source-maps` flag to use source maps for example. You can also potentially try to use libraries such as [`source-map-support`](https://www.npmjs.com/package/source-map-support) to add support for source maps in stack traces to other V8-based environments. Otherwise you may be out of luck if your JS environment doesn't support source maps.

Webpack is using a different approach here. It puts your source code inside `eval` and probably uses a `//# sourceURL=<filename>.js` comment to specify the file name for the otherwise-anonymous source code snippet. This isn't something that esbuild supports natively, and it likely wouldn't be easy to add it using an esbuild plugin. The reason is that `eval` prevents the bundler from working by putting information necessary for bundling inside an opaque string, and esbuild wasn't designed with this specific use case in mind.

Debugging in esbuild is intended to be done via source maps. If you can't enable source maps in your JS environment for whatever reason, then the answer to your question "is it possible?" is likely no, it is not possible to do that with esbuild.

**Comment by vhadianto** [comment]
Ah that's the missing setting! We're using Node but on AWS Lambda so it needs this environment variable set:
```
NODE_OPTIONS=--enable-source-maps
```

https://serverless.pub/aws-lambda-node-sourcemaps/

It works automatically in Webpack so I didn't realise I have to do something to enable this. Now that I set the appropriate environment variable I get this:

```
"TypeError: Cannot read property 'bar' of undefined",
        "    at RunControl.run (/var/task/index.js:819568:59)",
        "        -> /events/lib/run/run-control.js:183:57",
        "    at /var/task/index.js:821778:16",
        "        -> /events/lib/handler/tick.js:271:14",

<snip>
```

Thank you for your help!
