### ISSUE TITLE
footer works as banner if the code isn't bundled

### ISSUE THREAD

**Issue by assapir** [evanw/esbuild#1272]
Steps to reproduce:
build config that looks like this:
```
esbuild
  .build({
    entryPoints: ['src/index.jsx'],
    outdir: 'public/js',
    sourcemap: 'inline',
    logLevel: 'info',
    target: ['esnext'],
    footer: { js: '(() => new EventSource("/esbuild").onmessage = () => location.reload())();' },
})
```
expected: the footer will be shown up at the end of the unified file.
actual: the footer show in the beggingn, which cause an error in the browser:
> Uncaught SyntaxError: import declarations may only appear at top level of a module index.js:1
This cause because the actual code insert it before all of the imports: 
```
 (() => new EventSource("/esbuild").onmessage = () => location.reload())();
import * as React from "react";
import * as React2 from "react";
```

**Comment by evanw** [comment]
I'm still unable to reproduce this on that branch. After following those instructions, the contents of http://0.0.0.0:3000/js/index.js look like this:

```js
import React from "react";
import ReactDOM from "react-dom";
import App from "./App";
ReactDOM.render(/* @__PURE__ */ React.createElement(App, null), document.getElementById("root"));
(() => new EventSource("/esbuild").onmessage = () => location.reload())();
//# sourceMappingURL=data:application/json;base64,ewogICJ2ZXJzaW9uIjogMywKICAic291cmNlcyI6IFsiLi4vLi4vc3JjL2luZGV4LmpzeCJdLAogICJzb3VyY2VzQ29udGVudCI6IFsiaW1wb3J0IFJlYWN0IGZyb20gJ3JlYWN0JztcbmltcG9ydCBSZWFjdERPTSBmcm9tICdyZWFjdC1kb20nO1xuaW1wb3J0IEFwcCBmcm9tICcuL0FwcCdcblxuUmVhY3RET00ucmVuZGVyKFxuICAgIDxBcHAgLz4sXG4gICAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ3Jvb3QnKVxuKTtcbiJdLAogICJtYXBwaW5ncyI6ICJBQUFBO0FBQ0E7QUFDQTtBQUVBLFNBQVMsT0FDTCxvQ0FBQyxLQUFELE9BQ0EsU0FBUyxlQUFlOyIsCiAgIm5hbWVzIjogW10KfQo=
```

Are you sure there isn't something else going on? You said the file looked like this when you experienced the error:

```js
 (() => new EventSource("/esbuild").onmessage = () => location.reload())();
import * as React from "react";
import * as React2 from "react";
```

Even if the code did look like that, that shouldn't have caused the error `import declarations may only appear at top level of a module` because these import statements _are_ at the top level (i.e. not nested inside another scope). So it sounds like there's something else required to reproduce this issue that isn't in the reproduction instructions you provided.

**Comment by evanw** [comment]
I'm closing this because it's unactionable and there has been no response. We can continue to debug if more information is provided later.
