### ISSUE TITLE
Esbuild transform dynamic import to require despite the browser platform

### ISSUE THREAD

**Issue by AlexandreBonaventure** [evanw/esbuild#1281]
Repro: https://github.com/AlexandreBonaventure/esbuild-dynamic-import-bug

Since esbuild@0.11.0 transforming a file with a browser target not supporting dynamic `import()` statements converts it to `require` (see in repro see https://github.com/AlexandreBonaventure/esbuild-dynamic-import-bug/blob/main/out.js#L19). In a `node` context this makes sense, but not when targetting a browser. For context, this causes issue when trying to use https://github.com/GoogleChromeLabs/dynamic-import-polyfill used in Vite for instance.

I'd rather keep it untransformed in browser context. Best case scenario would be to warn the user about the target not supporting the feature.

Thanks

For context: https://github.com/vitejs/vite/issues/3388

**Comment by ggoodman** [comment]
@AlexandreBonaventure I've found a (terrible) work-around for this if you happen to control the code that is being transformed like this.

What I've done is hide the dynamic import from `esbuild` so that it doesn't get converted to require during the build. This hack will affect your ability to use content security policies though,

```ts
      // Create an aliased function that will call dynamic import at runtime but won't be recognized
      // as such at build time.
      const i = new Function('spec', 'return im' + 'port(spec)');
      if (Array.isArray(ctx.serverData) && ctx.serverData.length) {
        const promises: Promise<unknown>[] = [];

        for (const chunkId of ctx.serverData) {
          const promise = ctx.state.preload(chunkId, () => i(chunkId));

          if (promise) {
            promises.push(promise);
          }
        }

        if (promises.length) {
          return Promise.all(promises);
        }
      }
```

**Comment by AlexandreBonaventure** [comment]
I've noticed there is another issue with Vite when it comes to deal with `import.meta` statements which Vite uses for the environment variables. They are converted to `import_meta` and Vite fails to replace it afterwards,
To a broader extend this sheds light to the fact that we cannot use esbuild anymore for transpiling to older targets when esbuild is used as a transformer (and bundled by rollup in this case). It is a shame because `esbuild` was doing the job perfectly before this change and removed a lot of burden on this front. I hope we can find a solution so we can continue using `esbuild` for this use-case

I wonder if an option like `preserveImports` could be a solution here ? 
Thanks

**Comment by ggoodman** [comment]
I wonder if, in both our cases, a `require` or `module` is sneaking into the context of the `build()` called by Vite, causing something like https://github.com/evanw/esbuild/issues/769#issuecomment-775334509 to cascade the whole thing into CJS compat mode and thus causing ESM things to be converted.

**Comment by ggoodman** [comment]
@evanw I wonder if it might be possible to have a feature conceptually similar to `loader`s that would allow both the caller of `build()` and plugins hook logic to indicate to `esbuild` that we want to opt out of certain syntax transforms like this.

**Comment by ramasilveyra** [comment]
I also need to be able to opt out of the import.meta transformation.

**Use case:** I'm using esbuild-loader with webpack 5 and native web workers (https://webpack.js.org/guides/web-workers/).

**Problem:** In order for webpack to detect web workers you need to use the syntax `new Worker(new URL('./worker.js', import.meta.url));`, which it fails at runtime with `Uncaught TypeError: Failed to construct 'URL': Invalid URL` because esbuild replaces `import.meta.url` with `import_meta.url`, and `import_meta.url` is undefined.

**Workaround/hack:** I'm using [string-replace-loader](https://github.com/Va1/string-replace-loader) to undo the import.meta transformation.

```js
    const stringReplacer = {
      loader: 'string-replace-loader',
      options: {
        search: /import_meta\.url/,
        replace: 'import.meta.url',
      },
    };
```

**Comment by harveyconnor** [comment]
@ramasilveyra Could you please show me your webpack config file? I'm having trouble using string replace loader

**Comment by ramasilveyra** [comment]
@harveyconnor probably is the order, this is the order of the loaders for JS/TS code:
```
rule.use = [stringReplacer, esbuildLoader, babelLoader];
```
(I still need babel loader for some syntax that only is supported by babel)

**Comment by evanw** [comment]
After this issue was reported, esbuild has since implemented a way to control this directly: https://esbuild.github.io/api/#supported. You can now do `--supported:dynamic-import=true` to override the configured browser target. Closing this issue as fixed.

**Comment by KTibow** [comment]
In case anybody else is in my same situation: `--format=esm` also works
