### ISSUE TITLE
TypeScript import-equals statements cause incorrect duplicate export errors

### ISSUE THREAD

**Issue by yayaluoya** [evanw/esbuild#1283]
sample code：
```ts
import a = A.a;
import b = A.b;
export module c {
    export class B extends b {
    }
}
```

error message
```
export module c {
Multiple exports with the same name "c"
```

So I'm not going to make an error
```ts
import b = A.b;
export module c {
    export class B extends b {
    }
}
```
or
```ts
import a = A.a;
const b = A.b;
export module c {
    export class B extends b {
    }
}
```
。。。

**Comment by hyrious** [comment]
I doubt whether `import a = A.a` is a valid typescript syntax.
Till now I only see one possible usage: `import a = require('a')`

**Comment by evanw** [comment]
Thanks for reporting this issue and for providing an easy-to-reproduce example. It looks like this is caused by the import-elimination code I added to distinguish type imports from value imports. Here is an example:

```ts
import a = foo.a
import b = a.b
import c = b.c

import x = foo.x
import y = x.y
import z = y.z

console.log(c)
export {}
```

The TypeScript compiler converts that into the following JavaScript code, so esbuild should too:

```js
var a = foo.a;
var b = a.b;
var c = b.c;
console.log(c);
export {};
```

The `x`, `y`, and `z` import statements are eliminated in esbuild by iterating over imports and exports multiple times and continuing to remove unused TypeScript import-equals statements until none are left. The first pass removes `z` and marks `y` as unused, the second pass removes `y` and marks `x` as unused, and the third pass removes `x`. The problem is that this has the side effect of making esbuild think that a single export is exported twice (because it's processed twice).

This is a bug in esbuild, and I will fix this. In the meantime you should be able to avoid this by using `type` or `const` instead of `import`. That tells esbuild whether the import is a type or a value without esbuild having to guess.

**Comment by yayaluoya** [comment]
OK,thank,you
