### ISSUE TITLE
Support for sourcemap `names`

### ISSUE THREAD

**Issue by connor4312** [evanw/esbuild#1296]
Chrome has some support for renamed identifiers in sourcemaps. Now, [VS Code's debugger](https://github.com/microsoft/vscode/issues/12066) does too. It looks like esbuild doesn't generate `names`, but if it did it would make debugging easier.

**Comment by evanw** [comment]
Cool! I originally hadn't implemented this because I couldn't find a case where it mattered. I'm glad to hear that tooling has finally caught up. In addition to esbuild generating these names itself, it will also have to map names forward from embedded source maps in input files.

**Comment by kzc** [comment]
`source-map-support` has been used in NodeJS CLI tooling for stack traces since the early days and it makes use of sourcemap "names".  I had a stack trace discrepancy with a node CLI tool that was built with esbuild which led me to this issue.

Example CLI program:
```
$ cat names.js
try {
    require("source-map-support").install();
} catch (err) {}
Error.stackTraceLimit = 3; // not needed - demo purposes only
function someReallyDescriptiveFunc(flag) {
    if (flag) secondTime(flag);
}
function secondTime(flag) {
    if (flag) lastCall(flag);
}
function lastCall(flag) {
    if (flag) console.log(new Error("sourcemap names demo").stack);
}
someReallyDescriptiveFunc(0);
someReallyDescriptiveFunc(1);
```
Expected output without a sourcemap:
```
$ node names.js 
Error: sourcemap names demo
    at lastCall (/testing/names.js:12:27)
    at secondTime (/testing/names.js:9:15)
    at someReallyDescriptiveFunc (/testing/names.js:6:15)
```
Output with esbuild:
```
$ esbuild names.js --bundle --minify-identifiers --minify-whitespace --sourcemap --platform=node --external:source-map-support --outfile=names.esbuild.js --log-level=warning && node names.esbuild.js
Error: sourcemap names demo
    at o (/testing/names.js:12:27)
    at c (/testing/names.js:9:15)
    at r (/testing/names.js:6:15)
```
[Output with rollup+terser](https://sokra.github.io/source-map-visualization/#base64,dHJ5e3JlcXVpcmUoInNvdXJjZS1tYXAtc3VwcG9ydCIpLmluc3RhbGwoKX1jYXRjaChyKXt9RXJyb3Iuc3RhY2tUcmFjZUxpbWl0PTM7ZnVuY3Rpb24gcihyKXtpZihyKW8ocil9ZnVuY3Rpb24gbyhyKXtpZihyKWMocil9ZnVuY3Rpb24gYyhyKXtpZihyKWNvbnNvbGUubG9nKG5ldyBFcnJvcigic291cmNlbWFwIG5hbWVzIGRlbW8iKS5zdGFjayl9cigwKTtyKDEpOwovLyMgc291cmNlTWFwcGluZ1VSTD1uYW1lcy5yb2xsdXAuanMubWFwCg==,eyJ2ZXJzaW9uIjozLCJmaWxlIjoibmFtZXMucm9sbHVwLmpzIiwic291cmNlcyI6WyJuYW1lcy5qcyJdLCJzb3VyY2VzQ29udGVudCI6WyJ0cnkge1xuICAgIHJlcXVpcmUoXCJzb3VyY2UtbWFwLXN1cHBvcnRcIikuaW5zdGFsbCgpO1xufSBjYXRjaCAoZXJyKSB7fVxuRXJyb3Iuc3RhY2tUcmFjZUxpbWl0ID0gMzsgLy8gbm90IG5lZWRlZCAtIGRlbW8gcHVycG9zZXMgb25seVxuZnVuY3Rpb24gc29tZVJlYWxseURlc2NyaXB0aXZlRnVuYyhmbGFnKSB7XG4gICAgaWYgKGZsYWcpIHNlY29uZFRpbWUoZmxhZyk7XG59XG5mdW5jdGlvbiBzZWNvbmRUaW1lKGZsYWcpIHtcbiAgICBpZiAoZmxhZykgbGFzdENhbGwoZmxhZyk7XG59XG5mdW5jdGlvbiBsYXN0Q2FsbChmbGFnKSB7XG4gICAgaWYgKGZsYWcpIGNvbnNvbGUubG9nKG5ldyBFcnJvcihcInNvdXJjZW1hcCBuYW1lcyBkZW1vXCIpLnN0YWNrKTtcbn1cbnNvbWVSZWFsbHlEZXNjcmlwdGl2ZUZ1bmMoMCk7XG5zb21lUmVhbGx5RGVzY3JpcHRpdmVGdW5jKDEpO1xuIl0sIm5hbWVzIjpbInJlcXVpcmUiLCJpbnN0YWxsIiwiZXJyIiwiRXJyb3IiLCJzdGFja1RyYWNlTGltaXQiLCJzb21lUmVhbGx5RGVzY3JpcHRpdmVGdW5jIiwiZmxhZyIsInNlY29uZFRpbWUiLCJsYXN0Q2FsbCIsImNvbnNvbGUiLCJsb2ciLCJzdGFjayJdLCJtYXBwaW5ncyI6IkFBQUEsSUFDSUEsUUFBUSxzQkFBc0JDLFVBQ2hDLE1BQU9DLElBQ1RDLE1BQU1DLGdCQUFrQixFQUN4QixTQUFTQyxFQUEwQkMsR0FDL0IsR0FBSUEsRUFBTUMsRUFBV0QsR0FFekIsU0FBU0MsRUFBV0QsR0FDaEIsR0FBSUEsRUFBTUUsRUFBU0YsR0FFdkIsU0FBU0UsRUFBU0YsR0FDZCxHQUFJQSxFQUFNRyxRQUFRQyxJQUFJLElBQUlQLE1BQU0sd0JBQXdCUSxPQUU1RE4sRUFBMEIsR0FDMUJBLEVBQTBCIn0=,dHJ5IHsKICAgIHJlcXVpcmUoInNvdXJjZS1tYXAtc3VwcG9ydCIpLmluc3RhbGwoKTsKfSBjYXRjaCAoZXJyKSB7fQpFcnJvci5zdGFja1RyYWNlTGltaXQgPSAzOyAvLyBub3QgbmVlZGVkIC0gZGVtbyBwdXJwb3NlcyBvbmx5CmZ1bmN0aW9uIHNvbWVSZWFsbHlEZXNjcmlwdGl2ZUZ1bmMoZmxhZykgewogICAgaWYgKGZsYWcpIHNlY29uZFRpbWUoZmxhZyk7Cn0KZnVuY3Rpb24gc2Vjb25kVGltZShmbGFnKSB7CiAgICBpZiAoZmxhZykgbGFzdENhbGwoZmxhZyk7Cn0KZnVuY3Rpb24gbGFzdENhbGwoZmxhZykgewogICAgaWYgKGZsYWcpIGNvbnNvbGUubG9nKG5ldyBFcnJvcigic291cmNlbWFwIG5hbWVzIGRlbW8iKS5zdGFjayk7Cn0Kc29tZVJlYWxseURlc2NyaXB0aXZlRnVuYygwKTsKc29tZVJlYWxseURlc2NyaXB0aXZlRnVuYygxKTsK):
```
$ rollup names.js --external=source-map-support --sourcemap -o names.rollup.js -p terser='{"compress":false}' --silent && node names.rollup.js
Error: sourcemap names demo
    at lastCall (/testing/names.js:12:27)
    at secondTime (/testing/names.js:9:15)
    at r (/testing/names.js:6:15)
```
[The same output using terser alone](https://sokra.github.io/source-map-visualization/#base64,dHJ5e3JlcXVpcmUoInNvdXJjZS1tYXAtc3VwcG9ydCIpLmluc3RhbGwoKX1jYXRjaChyKXt9RXJyb3Iuc3RhY2tUcmFjZUxpbWl0PTM7ZnVuY3Rpb24gcihyKXtpZihyKW8ocil9ZnVuY3Rpb24gbyhyKXtpZihyKWMocil9ZnVuY3Rpb24gYyhyKXtpZihyKWNvbnNvbGUubG9nKG5ldyBFcnJvcigic291cmNlbWFwIG5hbWVzIGRlbW8iKS5zdGFjayl9cigwKTtyKDEpOwovLyMgc291cmNlTWFwcGluZ1VSTD1uYW1lcy50ZXJzZXIuanMubWFw,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIm5hbWVzLmpzIl0sIm5hbWVzIjpbInJlcXVpcmUiLCJpbnN0YWxsIiwiZXJyIiwiRXJyb3IiLCJzdGFja1RyYWNlTGltaXQiLCJzb21lUmVhbGx5RGVzY3JpcHRpdmVGdW5jIiwiZmxhZyIsInNlY29uZFRpbWUiLCJsYXN0Q2FsbCIsImNvbnNvbGUiLCJsb2ciLCJzdGFjayJdLCJtYXBwaW5ncyI6IkFBQUEsSUFDSUEsUUFBUSxzQkFBc0JDLFVBQ2hDLE1BQU9DLElBQ1RDLE1BQU1DLGdCQUFrQixFQUN4QixTQUFTQyxFQUEwQkMsR0FDL0IsR0FBSUEsRUFBTUMsRUFBV0QsR0FFekIsU0FBU0MsRUFBV0QsR0FDaEIsR0FBSUEsRUFBTUUsRUFBU0YsR0FFdkIsU0FBU0UsRUFBU0YsR0FDZCxHQUFJQSxFQUFNRyxRQUFRQyxJQUFJLElBQUlQLE1BQU0sd0JBQXdCUSxPQUU1RE4sRUFBMEIsR0FDMUJBLEVBQTBCIiwic291cmNlUm9vdCI6Ii8iLCJzb3VyY2VzQ29udGVudCI6WyJ0cnkge1xuICAgIHJlcXVpcmUoXCJzb3VyY2UtbWFwLXN1cHBvcnRcIikuaW5zdGFsbCgpO1xufSBjYXRjaCAoZXJyKSB7fVxuRXJyb3Iuc3RhY2tUcmFjZUxpbWl0ID0gMzsgLy8gbm90IG5lZWRlZCAtIGRlbW8gcHVycG9zZXMgb25seVxuZnVuY3Rpb24gc29tZVJlYWxseURlc2NyaXB0aXZlRnVuYyhmbGFnKSB7XG4gICAgaWYgKGZsYWcpIHNlY29uZFRpbWUoZmxhZyk7XG59XG5mdW5jdGlvbiBzZWNvbmRUaW1lKGZsYWcpIHtcbiAgICBpZiAoZmxhZykgbGFzdENhbGwoZmxhZyk7XG59XG5mdW5jdGlvbiBsYXN0Q2FsbChmbGFnKSB7XG4gICAgaWYgKGZsYWcpIGNvbnNvbGUubG9nKG5ldyBFcnJvcihcInNvdXJjZW1hcCBuYW1lcyBkZW1vXCIpLnN0YWNrKTtcbn1cbnNvbWVSZWFsbHlEZXNjcmlwdGl2ZUZ1bmMoMCk7XG5zb21lUmVhbGx5RGVzY3JpcHRpdmVGdW5jKDEpO1xuIl0sImZpbGUiOiJleGFtcGxlLmpzIn0=,dHJ5IHsKICAgIHJlcXVpcmUoInNvdXJjZS1tYXAtc3VwcG9ydCIpLmluc3RhbGwoKTsKfSBjYXRjaCAoZXJyKSB7fQpFcnJvci5zdGFja1RyYWNlTGltaXQgPSAzOyAvLyBub3QgbmVlZGVkIC0gZGVtbyBwdXJwb3NlcyBvbmx5CmZ1bmN0aW9uIHNvbWVSZWFsbHlEZXNjcmlwdGl2ZUZ1bmMoZmxhZykgewogICAgaWYgKGZsYWcpIHNlY29uZFRpbWUoZmxhZyk7Cn0KZnVuY3Rpb24gc2Vjb25kVGltZShmbGFnKSB7CiAgICBpZiAoZmxhZykgbGFzdENhbGwoZmxhZyk7Cn0KZnVuY3Rpb24gbGFzdENhbGwoZmxhZykgewogICAgaWYgKGZsYWcpIGNvbnNvbGUubG9nKG5ldyBFcnJvcigic291cmNlbWFwIG5hbWVzIGRlbW8iKS5zdGFjayk7Cn0Kc29tZVJlYWxseURlc2NyaXB0aXZlRnVuYygwKTsKc29tZVJlYWxseURlc2NyaXB0aXZlRnVuYygxKTsK):
```
$ terser names.js --source-map "root='/',includeSources=true,url='names.terser.js.map'" --toplevel --mangle -o names.terser.js && node names.terser.js
Error: sourcemap names demo
    at lastCall (/names.js:12:27)
    at secondTime (/names.js:9:15)
    at r (/names.js:6:15)
```
`source-map-support` usually works quite well, but it appears to have a bug generating the name `someReallyDescriptiveFunc`.  This bug is not present in various online source map visualizers.

Mangling symbols is not common in bundling NodeJS CLI tools, it was just used to demonstrate the issue more clearly. The actual discrepancies in my case were seeing things renamed like `Identifer2` instead of `Identifer`.

**Comment by kzc** [comment]
Follow up... 

If the following line in the `names.js` example above is removed:
```
Error.stackTraceLimit = 3; // not needed - demo purposes only
```
then `source-map-support` will correctly emit the stack frame for `someReallyDescriptiveFunc` for both rollup+terser and terser alone. It was just a NodeJS stack frame edge case, and the sourcemap "names" generation was fine.

**Comment by rdrabik** [comment]
Hey @evanw, are there any plans to add support for the source map names in the near future?

**Comment by evanw** [comment]
I have implemented support for `names` generation and I believe that the implementation works as intended. You can see an example of esbuild's output [here](https://evanw.github.io/source-map-visualization/#MTA2MwAvLyBpbmRleC50c3gKaW1wb3J0IHsgaCBhcyB1LCBGcmFnbWVudCBhcyBsLCByZW5kZXIgYXMgYyB9IGZyb20gInByZWFjdCI7CgovLyBjb3VudGVyLnRzeAppbXBvcnQgeyBoIGFzIHQsIENvbXBvbmVudCBhcyBpIH0gZnJvbSAicHJlYWN0IjsKaW1wb3J0IHsgdXNlU3RhdGUgYXMgYSB9IGZyb20gInByZWFjdC9ob29rcyI7CnZhciBuID0gY2xhc3MgZXh0ZW5kcyBpIHsKICBjb25zdHJ1Y3RvcihlKSB7CiAgICBzdXBlcihlKTsKICAgIHRoaXMubiA9ICgpID0+IHRoaXMuc2V0U3RhdGUoeyB0OiB0aGlzLnN0YXRlLnQgKyAxIH0pOwogICAgdGhpcy5yID0gKCkgPT4gdGhpcy5zZXRTdGF0ZSh7IHQ6IHRoaXMuc3RhdGUudCAtIDEgfSk7CiAgICB0aGlzLnN0YXRlLnQgPSBlLmU7CiAgfQogIHJlbmRlcigpIHsKICAgIHJldHVybiB0KCJkaXYiLCB7CiAgICAgIGNsYXNzOiAiY291bnRlciIKICAgIH0sIHQoImgxIiwgbnVsbCwgdGhpcy5wcm9wcy5sYWJlbCksIHQoInAiLCBudWxsLCB0KCJidXR0b24iLCB7CiAgICAgIG9uQ2xpY2s6IHRoaXMucgogICAgfSwgIi0iKSwgIiAiLCB0aGlzLnN0YXRlLnQsICIgIiwgdCgiYnV0dG9uIiwgewogICAgICBvbkNsaWNrOiB0aGlzLm4KICAgIH0sICIrIikpKTsKICB9Cn0sIHMgPSAocikgPT4gewogIGxldCBbbywgZV0gPSBhKHIuZSk7CiAgcmV0dXJuIHQoImRpdiIsIHsKICAgIGNsYXNzOiAiY291bnRlciIKICB9LCB0KCJoMSIsIG51bGwsIHIubyksIHQoInAiLCBudWxsLCB0KCJidXR0b24iLCB7CiAgICBvbkNsaWNrOiAoKSA9PiBlKG8gLSAxKQogIH0sICItIiksICIgIiwgbywgIiAiLCB0KCJidXR0b24iLCB7CiAgICBvbkNsaWNrOiAoKSA9PiBlKG8gKyAxKQogIH0sICIrIikpKTsKfTsKCi8vIGluZGV4LnRzeApjKAogIHUobCwgbnVsbCwgdShuLCB7CiAgICBvOiAiQ291bnRlciAxIiwKICAgIGU6IDEwMAogIH0pLCB1KHMsIHsKICAgIG86ICJDb3VudGVyIDIiLAogICAgZTogMjAwCiAgfSkpLAogIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCJyb290IikKKTsKLy8jIHNvdXJjZU1hcHBpbmdVUkw9ZXhhbXBsZS5qcy5tYXAKMzAxOAB7CiAgInZlcnNpb24iOiAzLAogICJzb3VyY2VzIjogWyJpbmRleC50c3giLCAiY291bnRlci50c3giXSwKICAic291cmNlc0NvbnRlbnQiOiBbImltcG9ydCB7IGgsIEZyYWdtZW50LCByZW5kZXIgfSBmcm9tICdwcmVhY3QnXG5pbXBvcnQgeyBDb3VudGVyQ2xhc3MsIENvdW50ZXJGdW5jdGlvbiB9IGZyb20gJy4vY291bnRlcidcblxucmVuZGVyKFxuICA8PlxuICAgIDxDb3VudGVyQ2xhc3MgbGFiZWxfPVwiQ291bnRlciAxXCIgaW5pdGlhbFZhbHVlXz17MTAwfSAvPlxuICAgIDxDb3VudGVyRnVuY3Rpb24gbGFiZWxfPVwiQ291bnRlciAyXCIgaW5pdGlhbFZhbHVlXz17MjAwfSAvPlxuICA8Lz4sXG4gIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdyb290JykhLFxuKVxuIiwgImltcG9ydCB7IGgsIENvbXBvbmVudCB9IGZyb20gJ3ByZWFjdCdcbmltcG9ydCB7IHVzZVN0YXRlIH0gZnJvbSAncHJlYWN0L2hvb2tzJ1xuXG5pbnRlcmZhY2UgQ291bnRlclByb3BzIHtcbiAgbGFiZWxfOiBzdHJpbmdcbiAgaW5pdGlhbFZhbHVlXzogbnVtYmVyXG59XG5cbmludGVyZmFjZSBDb3VudGVyU3RhdGUge1xuICB2YWx1ZV86IG51bWJlclxufVxuXG5leHBvcnQgY2xhc3MgQ291bnRlckNsYXNzIGV4dGVuZHMgQ29tcG9uZW50PENvdW50ZXJQcm9wcywgQ291bnRlclN0YXRlPiB7XG4gIHN0YXRlOiBDb3VudGVyU3RhdGVcblxuICBjb25zdHJ1Y3Rvcihwcm9wczogQ291bnRlclByb3BzKSB7XG4gICAgc3VwZXIocHJvcHMpXG4gICAgdGhpcy5zdGF0ZS52YWx1ZV8gPSBwcm9wcy5pbml0aWFsVmFsdWVfXG4gIH1cblxuICBpbmNyZW1lbnRfID0gKCkgPT4gdGhpcy5zZXRTdGF0ZSh7IHZhbHVlXzogdGhpcy5zdGF0ZS52YWx1ZV8gKyAxIH0pXG4gIGRlY3JlbWVudF8gPSAoKSA9PiB0aGlzLnNldFN0YXRlKHsgdmFsdWVfOiB0aGlzLnN0YXRlLnZhbHVlXyAtIDEgfSlcblxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIDxkaXYgY2xhc3M9XCJjb3VudGVyXCI+XG4gICAgICA8aDE+e3RoaXMucHJvcHMubGFiZWx9PC9oMT5cbiAgICAgIDxwPlxuICAgICAgICA8YnV0dG9uIG9uQ2xpY2s9e3RoaXMuZGVjcmVtZW50X30+LTwvYnV0dG9uPlxuICAgICAgICB7JyAnfVxuICAgICAgICB7dGhpcy5zdGF0ZS52YWx1ZV99XG4gICAgICAgIHsnICd9XG4gICAgICAgIDxidXR0b24gb25DbGljaz17dGhpcy5pbmNyZW1lbnRffT4rPC9idXR0b24+XG4gICAgICA8L3A+XG4gICAgPC9kaXY+XG4gIH1cbn1cblxuZXhwb3J0IGxldCBDb3VudGVyRnVuY3Rpb24gPSAocHJvcHM6IENvdW50ZXJQcm9wcykgPT4ge1xuICBsZXQgW3ZhbHVlLCBzZXRWYWx1ZV0gPSB1c2VTdGF0ZShwcm9wcy5pbml0aWFsVmFsdWVfKVxuICByZXR1cm4gPGRpdiBjbGFzcz1cImNvdW50ZXJcIj5cbiAgICA8aDE+e3Byb3BzLmxhYmVsX308L2gxPlxuICAgIDxwPlxuICAgICAgPGJ1dHRvbiBvbkNsaWNrPXsoKSA9PiBzZXRWYWx1ZSh2YWx1ZSAtIDEpfT4tPC9idXR0b24+XG4gICAgICB7JyAnfVxuICAgICAge3ZhbHVlfVxuICAgICAgeycgJ31cbiAgICAgIDxidXR0b24gb25DbGljaz17KCkgPT4gc2V0VmFsdWUodmFsdWUgKyAxKX0+KzwvYnV0dG9uPlxuICAgIDwvcD5cbiAgPC9kaXY+XG59XG4iXSwKICAibWFwcGluZ3MiOiAiO0FBQUEsU0FBUyxLQUFBQSxHQUFHLFlBQUFDLEdBQVUsVUFBQUMsU0FBYzs7O0FDQXBDLFNBQVMsS0FBQUMsR0FBRyxhQUFBQyxTQUFpQjtBQUM3QixTQUFTLFlBQUFDLFNBQWdCO0FBV2xCLElBQU1DLElBQU4sY0FBMkJGLEVBQXNDO0FBQUEsRUFHdEUsWUFBWUcsR0FBcUI7QUFDL0IsVUFBTUEsQ0FBSztBQUliLFNBQUFDLElBQWEsTUFBTSxLQUFLLFNBQVMsRUFBRUMsR0FBUSxLQUFLLE1BQU1BLElBQVMsRUFBRSxDQUFDO0FBQ2xFLFNBQUFDLElBQWEsTUFBTSxLQUFLLFNBQVMsRUFBRUQsR0FBUSxLQUFLLE1BQU1BLElBQVMsRUFBRSxDQUFDO0FBSmhFLFNBQUssTUFBTUEsSUFBU0YsRUFBTUk7QUFBQSxFQUM1QjtBQUFBLEVBS0EsU0FBUztBQUNQLFdBQU9SLEVBQUM7QUFBQSxNQUFJLE9BQU07QUFBQSxPQUNoQkEsRUFBQyxZQUFJLEtBQUssTUFBTSxLQUFNLEdBQ3RCQSxFQUFDLFdBQ0NBLEVBQUM7QUFBQSxNQUFPLFNBQVMsS0FBS087QUFBQSxPQUFZLEdBQUMsR0FDbEMsS0FDQSxLQUFLLE1BQU1ELEdBQ1gsS0FDRE4sRUFBQztBQUFBLE1BQU8sU0FBUyxLQUFLSztBQUFBLE9BQVksR0FBQyxDQUNyQyxDQUNGO0FBQUEsRUFDRjtBQUNGLEdBRVdJLElBQWtCLENBQUNMLE1BQXdCO0FBQ3BELE1BQUksQ0FBQ00sR0FBT0MsQ0FBUSxJQUFJVCxFQUFTRSxFQUFNSSxDQUFhO0FBQ3BELFNBQU9SLEVBQUM7QUFBQSxJQUFJLE9BQU07QUFBQSxLQUNoQkEsRUFBQyxZQUFJSSxFQUFNUSxDQUFPLEdBQ2xCWixFQUFDLFdBQ0NBLEVBQUM7QUFBQSxJQUFPLFNBQVMsTUFBTVcsRUFBU0QsSUFBUSxDQUFDO0FBQUEsS0FBRyxHQUFDLEdBQzVDLEtBQ0FBLEdBQ0EsS0FDRFYsRUFBQztBQUFBLElBQU8sU0FBUyxNQUFNVyxFQUFTRCxJQUFRLENBQUM7QUFBQSxLQUFHLEdBQUMsQ0FDL0MsQ0FDRjtBQUNGOzs7QUQ5Q0FHO0FBQUEsRUFDRUMsRUFBQUMsR0FBQSxNQUNFRCxFQUFDRSxHQUFBO0FBQUEsSUFBYUMsR0FBTztBQUFBLElBQVlDLEdBQWU7QUFBQSxHQUFLLEdBQ3JESixFQUFDSyxHQUFBO0FBQUEsSUFBZ0JGLEdBQU87QUFBQSxJQUFZQyxHQUFlO0FBQUEsR0FBSyxDQUMxRDtBQUFBLEVBQ0EsU0FBUyxlQUFlLE1BQU07QUFDaEM7IiwKICAibmFtZXMiOiBbImgiLCAiRnJhZ21lbnQiLCAicmVuZGVyIiwgImgiLCAiQ29tcG9uZW50IiwgInVzZVN0YXRlIiwgIkNvdW50ZXJDbGFzcyIsICJwcm9wcyIsICJpbmNyZW1lbnRfIiwgInZhbHVlXyIsICJkZWNyZW1lbnRfIiwgImluaXRpYWxWYWx1ZV8iLCAiQ291bnRlckZ1bmN0aW9uIiwgInZhbHVlIiwgInNldFZhbHVlIiwgImxhYmVsXyIsICJyZW5kZXIiLCAiaCIsICJGcmFnbWVudCIsICJDb3VudGVyQ2xhc3MiLCAibGFiZWxfIiwgImluaXRpYWxWYWx1ZV8iLCAiQ291bnRlckZ1bmN0aW9uIl0KfQo=) (hover over identifiers on the right to see the original names).

However, I have not used the feature myself yet as I don't typically use debuggers. Please evaluate esbuild's implementation and let me know if there are any issues.

**Comment by bpasero** [comment]
I gave this a spin from a branch applying `esbuild@0.15.5` for VSCode ([commit](https://github.com/microsoft/vscode/commit/8bd968242f169d3c6a84c19bad1ac78d0b3441c4#diff-5cbd49595c6e47b7bb83f9866c6f60ec1aefd8f9bd25921ec26cc878d9d14b97)). We have a rather simple `esbuild` invocation: https://github.com/microsoft/vscode/blob/a13e5e1da6d87e4dac3bfd9e61145f67dec29a43/build/lib/optimize.ts#L291-L299

The resulting build is not allowing me to quick outline into the methods so I am not 100% sure if it is working or if something is missing.

An example source map with this change is: https://ticino.blob.core.windows.net/sourcemaps/8bd968242f169d3c6a84c19bad1ac78d0b3441c4/core/vs/workbench/workbench.desktop.main.js.map

An example VSCode exploration build from this branch is: https://az764295.vo.msecnd.net/exploration/8bd968242f169d3c6a84c19bad1ac78d0b3441c4/VSCode-darwin-universal.zip

**Comment by evanw** [comment]
I visualized that source map here and it looks like the names are attached correctly: https://evanw.github.io/source-map-visualization/.

**Comment by bpasero** [comment]
Hm, I am mainly referring to the resolution in https://bugs.chromium.org/p/chromium/issues/detail?id=1087763#c15 which states we have to update to latest `esbuild` to see variable names in devtools. Our VSCode devtools is on Chrome 102, which I would assume is good enough for this.

**Comment by evanw** [comment]
Ah. Chrome 102 through 104 has a bug with reading the source maps that esbuild generates: https://bugs.chromium.org/p/chromium/issues/detail?id=1329997. I hear this has been fixed in Chrome 105 which is being released today? According to https://github.com/evanw/esbuild/issues/2295#issuecomment-1228002212.

**Comment by bpasero** [comment]
@evanw oh wow thanks! I did an experiment with using devtools in the browser for the sources (Chrome 104) and in fact I do see a difference.

**Old**
<img width="1498" alt="image" src="https://user-images.githubusercontent.com/900690/187370448-8e81f35d-d8db-49bd-a173-6ba0b1fba406.png">

**New**
<img width="1544" alt="image" src="https://user-images.githubusercontent.com/900690/187370492-9569e894-2ba7-4af8-a279-778363e75638.png">
