### ISSUE TITLE
Ast operation

### ISSUE THREAD

**Issue by yisar** [evanw/esbuild#1297]
Do you have any ideas? Is it possible to provide an API to operate AST in JavaScript API?

**Comment by evanw** [comment]
This is out of scope for esbuild. It's listed as a non-goal [in the documentation](https://esbuild.github.io/faq/#upcoming-roadmap):

> * An API for custom AST manipulation

I haven't used [swc](https://swc.rs/) myself but I've heard that it's designed to be a Babel replacement and has an [AST API](https://swc.rs/rustdoc/swc_ecma_ast/index.html) that can be used to write plugins. I suggest checking out swc instead.

**Comment by lukeed** [comment]
@evanw  Is there any scenario where you'd consider exposing the AST? I think if it were opt-in and that signal is what incurred some performance loss, I bet 99% of users would accept that trade-off. Right now, the only reason to leave `esbuild` is if/when you need to do some AST operations.

 I know you've been directing users towards swc – which is a nice gesture – but it's still so far away from being production-ready. It's very much still a WIP and I have hope for it, but even with plain `transform`/`minify` operations (no AST visitors), it's not very reliable & has exceptionally cryptic error messages. I still think its future is bright, but today it's in a different ballpark than esbuild. Its `spack` component/integration (tbd?) is there – via the `bundle` method – and so while there are clearly plans for swc to be an esbuild alternative, right now `swc.bundle` will either omit 30-50% of my bundle's contents or include them but not make them accessible / break the reference links.

So, without leaving esbuild wholesale, this means the only other option is to embed another toolchain as an esbuild plugin. Of course, this feels kinda silly since we now have different tools doing roughly the same work, resulting in a webpack-like parse->AST->modify->stringify cyclical caterpillar. I think it's a safe bet that this would result in a much larger performance hit than whatever loss may come from a pure-esbuild option.

There's also the dependency size argument. Some people don't care about this – which I guess is fine 😆 – but  on macOS esbuild weighs in at `7.7MB` which is an insane power:size ratio. Here are some other comparisons, all of which would be viable, importable toolchain just to _begin_ thinking about accessing an AST:

* `@babel/core` :: 10MB
* `rollup` :: 4.5MB
* `@swc/core` :: 24MB
* `typescript` :: 60MB

And only two of these unlock TypeScript access.

I'm at a point where `esbuild` is all I need 90% of the time, which  includes the quick plugins I write to bridge a small gap. But the remaining 10% leaves me a bit stranded & I have to abandon the esbuild ethos & pick up the old bag of tools & configs.

So yeah, I've gone on for a little too long, but I think I understand your concern (and reluctance) for exposing the internals, fearing that they'd change often. I think they _can change_ since esbuild is still 0.x and that's the bet we're all making. I'm imaging a top-level configuration option that unlocks the extra AST abilities, which is already an opt-in, so you could name it `--experimental-ast` to excuse/shelter the AST bits from the same strict versioning system. It'd _clearly_ be experimental until some future 1.x date.

As always, thanks for your work and for instigating a tidal wave of change throughout the ecosystem

**Comment by lukeed** [comment]
Friendly ping @evanw :D understand if it’s a hard “no” still but wanted to check in as it’s been some time now

**Comment by evanw** [comment]
I'm still not planning on doing this. In addition to being a lot of extra work and maintenance burden for me, it's also a bad fit for esbuild's out-of-process plugin model (which is due to the implementation choice of using the Go language, which is unlikely to change).

**Comment by lukeed** [comment]
That’s fair! Thanks for clarifying :)
