### ISSUE TITLE
[Bug] high memory and cpu use for esbuild-wasm on browsers

### ISSUE THREAD

**Issue by okikio** [evanw/esbuild#1298]
As of right now bundling any heavy packages requires quite a lot of compute power and memory. For example, the typescript and babel packages both take `over 500 Mb` of ram to complete. If possible please add the ability to control thread count, reduce general memory usage and slow down esbuild, so as to enable esbuild to work well on lower spec devices. 

You can try it out here: [okikio.github.io/bundle](https://okikio.github.io/bundle)

Type this into the editor,

```ts
export * from "typescript";
// and
// export * from "@babel/core";
```

**Comment by evanw** [comment]
The WebAssembly version of esbuild isn't designed to be optimal. The intended way to use esbuild is via the native executable. I only published a WebAssembly version because it was possible to do so, and because you can use it to try esbuild out in a browser on small projects.

If you need an optimized WebAssembly-based bundler then I wouldn't use esbuild. Go is not the right language to use if your goal is a high-performance low-memory WebAssembly module.

**Comment by okikio** [comment]
Oh, that's unfortunate i was hoping to use it as an online bundler. Do you know of any tools that would be a better fit for my project, I tried rollup but I couldn't get it to work well on the browser?

**Comment by evanw** [comment]
Something like Rust would be a better target since there has been a lot more of an implementation focus on Rust+WASM vs. Go+WASM. The [swc](https://swc.rs/) project is written in Rust and is planning on implementing a bundler called "spack" but that isn't production-ready yet. It's also currently slower than esbuild (e.g. 6.3 seconds vs. 0.36 seconds on the primary esbuild benchmark) but they are planning on working on that too. Some day it may be a solid alternative to esbuild. The WebAssembly version may potentially already be faster and/or use less memory than esbuild given how inefficient esbuild's WebAssembly version is.

I have also heard of some other people working on similar things. For example, someone is working on an esbuild-derived bundler in Zig: https://twitter.com/jarredsumner/status/1390084458724741121. When it's compiled to WebAssembly, the result is much more optimal: https://twitter.com/jarredsumner/status/1390417951300354050. It's unclear if/when this will become production-ready since the source isn't even available yet but this could be another project to keep an eye on.

**Comment by okikio** [comment]
Thanks for these suggestions, I'll check them out. Also, may suggest that you add a `http` and virtual memory plugin to esbuild by default. I am kind of dreading having to create an `http` and virtual memory plugin for `swc`, and `esdev` (if jarredsummer is able to complete it soon), so, it would be awesome if things like this for supporting web browsers were just built in by default.

**Comment by evanw** [comment]
I'm closing this because esbuild was not designed with the browser in mind (even though it is now possible to use it there) so I do not consider this a bug.
