### ISSUE TITLE
[question] format: 'esm' generates var instead of let or const

### ISSUE THREAD

**Issue by BePo65** [evanw/esbuild#1301]
If I run esbuild to generate esm output with the following options:
```
  platform: 'browser',
  format: 'esm',
  bundle: true,
  target: 'es2020'
```

the created output contains `var xx = class ...` for every class defined in the source file in addition to the expected `export {...}`.

Question: is the use of `var` by intention (e.g. for use in "classical" html pages) or should it better be `const` to avoid cluttering the global context / window object?

**Comment by heyheyhello** [comment]
It's intentional because let/const introduces a "TDZ" Temporal Dead Zone which is fine in theory but in practice caused extreme performance issues in Safari. https://github.com/evanw/esbuild/issues/478. There was some talk with the WebKit team I think. Ultimately switched everything to var :)

ESM is for _modules_ so the code will run as an ESM import or as a `<script type=module ...` block, both of which _do not_ clutter the global context/window - you need to explicitly say `window.x = ` to do that.

If you're running the ESM output code in a normal `<script>` block and are worried about the global context then use format IIFE.

**Comment by BePo65** [comment]
oh, so much for my knowledge about using var in a browser environment ;-)

Thank you for your very detailed answer.
