### ISSUE TITLE
Styled components - component name in generated CSS class

### ISSUE THREAD

**Issue by snizemic** [evanw/esbuild#1320]
Hi, esbuild is amazing. I have no issue, just question. We moved from webpack in our team and the speed of build against to webpack is unbelievable! We also use styled-components in our toolchain and I just wondering if there is a way to display component name in generated CSS class?

**Comment by evanw** [comment]
Sorry, I don't understand what you're saying. Maybe some code could help?

**Comment by snizemic** [comment]
Thank you for the answer. Please look at [https://styled-components.com/docs/tooling#better-debugging](url) The `babel-plugin-styled-components` do the job with webpack.

**Comment by evanw** [comment]
This doesn't seem to me like something that should be included in esbuild itself. It's a very specific convention that doesn't apply to everyone and could actually lead to correctness issues due to name collisions.

However, it seems to me like it's pretty trivial to do this yourself without any help from esbuild by providing your own JSX factory. Here's a quick example of how to do this with esbuild's [inject](https://esbuild.github.io/api/#inject) and [JSX factory](https://esbuild.github.io/api/#jsx-factory) features:

```
$ npm i react esbuild

$ cat entry.jsx
import React from 'react'
var Component = () => <div />
console.log(<Component class="asdf123" />, <button class="asdf123" />)

$ cat custom-jsx-factory.js
import React from 'react'
export var customCreateElement = (tag, props, ...children) => {
  if (props && props.class)
    props.class = `${tag.name || tag}-${props.class} ${props.class}`
  return React.createElement(tag, props, ...children)
}

$ ./node_modules/.bin/esbuild --bundle entry.jsx --inject:custom-jsx-factory.js --jsx-factory=customCreateElement | node
{
  '$$typeof': Symbol(react.element),
  type: [Function: Component],
  key: null,
  ref: null,
  props: { class: 'Component-asdf123 asdf123' },
  _owner: null,
  _store: {}
} {
  '$$typeof': Symbol(react.element),
  type: 'button',
  key: null,
  ref: null,
  props: { class: 'button-asdf123 asdf123' },
  _owner: null,
  _store: {}
}
```

I'm closing this issue because I believe it to be out of scope for including in esbuild itself.

**Comment by snizemic** [comment]
Thanks for your time! ;-)
