### ISSUE TITLE
The future with webbundle?

### ISSUE THREAD

**Issue by uasan** [evanw/esbuild#1329]
Hello, your library is great!

I for a couple of days I have been testing the `web-bundle` is technology native the browser, I really like how it just works.
https://chromium.googlesource.com/chromium/src.git/+/refs/heads/main/content/browser/web_package/subresource_loading_origin_trial.md

Do you think this technology can integrate with `esbuild`?
Thanks.

**Comment by evanw** [comment]
This seems like a way to put some files in an archive? If you want to do that, you can do that yourself by running their archive generation tool without needing esbuild to do this for you. I'm going to close this issue because I believe it to be out of scope.

For example, other potential archive formats are a zip file or a tar archive. I don't think esbuild should have built-in support for generating those formats either, even though users might hypothetically want to bundle some code and then archive it right afterward. Tools already exist to generate these archives and I believe these concerns (bundling and archive generation) should stay separate.

**Comment by uasan** [comment]
> you can do that yourself by running their archive generation tool without needing esbuild to do this for you

No, it's not just an archive, it's an HTTP request-response bundle.
Its main point, **not to create one big JS file** (parse big JS file and execute this useless CPU and memory utilization)

Therefore, more than one file is stored in the web bundle, many files are stored there (HTTP responses) if you have 1k files in the project, this bundle will have 1k files.

The browser extract 1k answers in its HTTP cache, i.e. 1k unique URLs with ready-made responses appear in the browser cache.

This means that esbuild output should not merge all the code into one file, esbuild should save each file as an HTTP response in web bundle format. Each JS file should have ES imports of other JS files, so the browser will load and execute only the necessary files from the bundle.

The next stable version of Chrome 103 already supports this web bundle format, which means that ~70% of users will be able to use it.

**Comment by evanw** [comment]
Here's the [first Google result for `web bundle`](https://web.dev/web-bundles/#building-web-bundles):

> The [go/bundle](https://github.com/WICG/webpackage/tree/master/go/bundle) CLI is currently the easiest way to bundle a website. go/bundle is a reference implementation of the Web Bundles specification built in [Go](https://golang.org/).
>
> ...
>
> Use the `gen-bundle` command to build a `.wbn` file.
>
> ```
> gen-bundle -dir build -baseURL https://preact-todom.vc/ -primaryURL https://preact-todom.vc/ -o todomvc.wbn
> ```

You can do this yourself by running their archive generation tool without needing esbuild to do this for you.

**Comment by uasan** [comment]
yes, it's enough to TS emit to ESNext version, then launch a web bundler, it seems that this is a good future for web developers )
