### ISSUE TITLE
Perf improvement idea: setrlimit/getrlimit to monitor & increase file handle limit

### ISSUE THREAD

**Issue by Jarred-Sumner** [evanw/esbuild#1330]
[`setrlimit`](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/setrlimit.2.html) is a system call that lets you change the number of max open file handles

Processes have a default number of max open file handles, and then can request up to some max number without special privileges. `getrlimit` returns the current and max values.

macOS defaults to `256` and "unlimited" as the max which is actually 10,240.

In my build tool based on esbuild's source, the time spent on opening & closing files is significant. As a performance optimization, on launch, it maxes out the file handle limit, tracks the max file descriptor, stores the file descriptors, and then only bothers to close files when when the max file descriptor is > (limit / 2). On windows, this optimization is disabled because I'm worried about how how Windows locks files

This reduced time spent building Rome's codebase (your TypeScript benchmark) by about 5%. The gain won't be as high for esbuild because mine writes individual files instead of bundling into one file. But maybe you'll get +5ms or so out of it. You can rely on the OS to close file handles for you on exit.

The important part is not closing files unless within some threshold of the limit. Could probably also make the resolver faster by increasing the count on that semaphore for limiting file access

**Comment by evanw** [comment]
Thanks for the experience report. It's good to keep this in mind.

I'm actually currently limiting concurrent open files to 32:

https://github.com/evanw/esbuild/blob/00237e723893a99ee1819ee32d8f19dd8e315fbd/internal/fs/fs.go#L152-L153

This number was introduced due to non-deterministic failures from ulimit issues (#348). A low value was chosen because I haven't observed a difference over that amount. For example, changing it from 32 to 256 doesn't appear to change the result of the primary benchmark on my computer.

**Comment by evanw** [comment]
Closing this issue as I'm not planning on doing this.
