### ISSUE TITLE
Question about the --service option

### ISSUE THREAD

**Issue by hsiaosiyuan0** [evanw/esbuild#1336]
Hi, the option [--service](https://github.com/evanw/esbuild/blob/7a727e305e7cab9e13b8819aa87f1b0053729298/cmd/esbuild/main.go#L171) says that it uses stdin/stdout under the hood, could you please help me to understand why stdin/stdout is chosen here instead of [IPC](https://nodejs.org/api/net.html#net_ipc_support) or some other things  :)

**Comment by evanw** [comment]
I used stdin/stdout because it was both easy and straightforward. This is an internal implementation detail that is unstable and isn't meant to be used outside of the built-in language bindings, so it shouldn't matter how it's implemented.

I'm closing this issue since this issue does not represent a problem with esbuild.
