### ISSUE TITLE
Incorrectly transformed `require.cache` in esm format

### ISSUE THREAD

**Issue by egoist** [evanw/esbuild#1345]
Input:

```js
console.log(require.cache)
```

Output:

```js
var __require = (x) => {
  if (typeof require !== "undefined")
    return require(x);
  throw new Error('Dynamic require of "' + x + '" is not supported');
};

// foo.js
console.log(__require.cache);
```

Command:

```
esbuild input.js --outdir=out --bundle --format=esm
```

esbuild version: 0.12.5

**Comment by evanw** [comment]
This is intentional. The `require` function has special behavior because esbuild is a CommonJS-aware bundler. Previously esbuild only transformed `require()` calls and not other uses of `require`, but that led to strange issues where `require` behaved inconsistently (it was a function at compile-time but undefined at run-time). For example, this caused problems with code that called `require` indirectly or that checked for a `require` function before calling it.

That behavior has now been intentionally changed such that `require` is now substituted for `__require` in environments that lack a `require` function (e.g. the `esm` output format). This guarantees that `require` is a function both at compile-time and at run-time.

If you need to use `require.cache` then you should set esbuild's output format to `cjs`. Node doesn't expose `require` to ES modules. If the use of `require.cache` is optional and you want to avoid crashing if it's not supported, you can test to see if `require.cache` exists first before using it. And if you need to generate ES modules but have `require.cache` be emulated for you, then you'll need to use another bundler; esbuild doesn't implement `require.cache` emulation.

**Comment by egoist** [comment]
fair enough. 👌
