### ISSUE TITLE
Require a umd module as commonJS conflict with requirejs.

### ISSUE THREAD

**Issue by wmzy** [evanw/esbuild#1348]
Look at the out code below:

```js
  // node_modules/tslib/tslib.js
  var require_tslib = __commonJS({
  "node_modules/tslib/tslib.js"(exports, module) {
    // ...
    (function(factory) {
      var root = typeof global === "object" ? global : typeof self === "object" ? self : typeof this === "object" ? this : {};
      // note: If requirejs has been load before, this branch will be run. 
      // And the `require_tslib()` will return an empty `{}`.
      if (typeof define === "function" && define.amd) {
        define("tslib", ["exports"], function(exports2) {
          factory(createExporter(root, createExporter(exports2)));
        });
      } else if (typeof module === "object" && typeof module.exports === "object") {
        factory(createExporter(root, createExporter(module.exports)));
      } else {
        factory(createExporter(root));
      }
      function createExporter(exports2, previous) {
        // ...
      }
    })(function(exporter) {
      // ...
      exporter("__importStar", __importStar);
      exporter("__importDefault", __importDefault);
    });
    }
});
```
If `requirejs` has been load before, the `require_tslib()` will return an empty `{}`.
This will result an error like #746 .

To avoid this, can we wrrap the code like:
```js
var require_tslib = __commonJS({
  "node_modules/tslib/tslib.js"(exports, module, define /* to hide the global define */) {
   // ...
  }
});
```
?

**Comment by evanw** [comment]
It would be wrong for esbuild to shadow `define` with `undefined` in all code that it bundles. This would make it impossible to use code that legitimately needs to access `define`.

However, if you would like to do that yourself, you can use [esbuild's define feature](https://esbuild.github.io/api/#define) for this. An example would be `--define:define=undefined` to replace all references to the global variable `define` with references to the global variable `undefined`.

I'm closing this issue because you can already configure esbuild to do this by yourself and is not a default behavior that should be added to esbuild for everyone.

**Comment by wmzy** [comment]
Even if this is not a perfect solution, I think this is still a bug of esbuid.

To define the `define` as `undefined` is a more dangerous way . It will replace all `define` but not only top level `define`.

I think the best way is to [do like the rollup](https://github.com/rollup/plugins/blob/6867290ec8b983950ce20e58a34eaaee5e371517/packages/commonjs/src/transform-commonjs.js#L306).

**Comment by evanw** [comment]
> It will replace all `define` but not only top level `define`.

That's not true. The define feature in esbuild only replaces references to global variables. It does not replace references to local variables:

```
$ echo "define" | ./esbuild --define:define=foo
foo;

$ echo "var define" | ./esbuild --define:define=foo
var define;
```

**Comment by wmzy** [comment]
Yes, I got it wrong here.

But I still hope that you can consider removing the umd wrapper to reduce this weird issue and produce a smaller bundle.
