### ISSUE TITLE
Respect the default setting of the useDefineForClassFields tsconfig option

### ISSUE THREAD

**Issue by kfdf** [evanw/esbuild#1354]
Sometime between 0.11.20 and 0.12.6 esbuild stopped transpiling public class fields into assignments inside the constructor when the `target` tsconfig setting is set to `esnext` and `useDefineForClassFields` is not present. This breaks LitElement decorators that make properties reactive, as described [here](https://lit.dev/docs/components/decorators/#avoiding-issues-with-class-fields). It's mentioned there that `useDefineForClassFields` is set to `false` by default. Maybe the default value should be respected when transpiling typescript files?

**Comment by evanw** [comment]
The TypeScript language now works like this as of TypeScript 4.3.1, so esbuild has been changed to match. The issue https://github.com/microsoft/TypeScript/issues/34787 has some additional context. I'm not sure why the TypeScript team decided to release this as a silent breaking change without an announcement. But the documentation for LitElement is now incorrect. The default value is `false` except when the target is `"ESNext"` in which case the default is `true`.

Anyway specifying `"target": "ESNext"` in your `tsconfig.json` file without also setting a value for `"useDefineForClassFields"` is now error-prone because it means your code will now behave differently in different versions of TypeScript. I personally think the TypeScript compiler should warn when you do this and tell you to set `"useDefineForClassFields"` explicitly.

If you are using an old version of TypeScript you can either add `"useDefineForClassFields": false` in your `tsconfig.json` file or, if you really don't want to change `tsconfig.json`, you can also just use an old version of esbuild.

**Comment by kfdf** [comment]
Oh, I see.
