### ISSUE TITLE
File with 'import' statement still being treated as CJS module

### ISSUE THREAD

**Issue by fun4wut** [evanw/esbuild#1366]
**Environment**
- esbuild version: 0.12.8
- node.js version: 12.18.4

---

I've tried the example in `architecture.md` 

<table>
<tr><th>foo.js</th><th>bar.js</th><th>bundle.js</th></tr>
<tr><td>

```js
export const fn = () => 123
```

</td><td>

```js
import {fn} from './foo'
console.log(fn())
```

</td><td>

```js
// foo.js
const fn = () => 123;

// bar.js
console.log(fn());
```

</td></tr>
</table>

But when I ran the command `esbuild bar.js --bundle --format=esm`,
The expected ouput was
```js
// foo.js
const fn = () => 123;

// bar.js
console.log(fn());
```

however, I got
```js
var __esm = (fn2, res) => function __init() {
  return fn2 && (res = (0, fn2[Object.keys(fn2)[0]])(fn2 = 0)), res;
};
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[Object.keys(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};

// foo.js
var fn;
var init_foo = __esm({
  "foo.js"() {
    fn = () => 123;
  }
});

// bar.js
var require_bar = __commonJS({
  "bar.js"() {
    init_foo();
    console.log(fn());
  }
});
export default require_bar();
```
---
**It seems like `bar.js` is treated as CJS module, though this file contains `import` statement.**
And I found if I added `export` statement in `bar.js`, the file would be treated as ESM module.
<table>
<tr><th>foo.js</th><th>bar.js</th><th>bundle.js</th></tr>
<tr><td>

```js
export const fn = () => 123
```

</td><td>

```js
import {fn} from './foo'
export const rua = 233
console.log(fn())
```
</td><td>

```js
// foo.js
var fn = () => 123;

// bar.js
var rua = 233;
console.log(fn());
export {
  rua
};
```
</td></tr>
</table>

I also found that if I modified the `type` field to `module`  in `package.json`, the origin example could ran as expected.

```js
// package.json
{
  "type": "module",
  // ....
}
```
---

_So I'm wondering how esbuild distinguish the entry point is `esm` or `cjs` module_, the behavior above seems not making sense.

**Comment by evanw** [comment]
Doing what you describe doesn't reproduce this:

```
$ cat foo.js 
export const fn = () => 123

$ cat bar.js
import {fn} from './foo'
console.log(fn())

$ echo {} > package.json
$ npm i esbuild@0.12.8

$ ./node_modules/.bin/esbuild bar.js --bundle --format=esm
// foo.js
var fn = () => 123;

// bar.js
console.log(fn());
```

If I explicitly add `"type": "commonjs"` to `package.json`, then I do get the output you describe. So I'm assuming that this is what you did and that having `"type": "commonjs"` in `package.json` is part of the steps to reproduce the issue you're describing.

However, that annotation says that files ending in `.js` are in CommonJS format which is clearly not the case here. So either these `.js` files shouldn't have ESM syntax in them if they are supposed to be CommonJS, or the `package.json` file shouldn't have `"type": "commonjs"` in it if the `.js` files aren't actually CommonJS. **These two things are in conflict.**

If esbuild was being strict about this, the `import` statement would be a syntax error if you do this. That's what happens when you try to run this in node:

```
$ node bar.js 
(node:23220) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
./bar.js:1
import {fn} from './foo'
^^^^^^
```

But esbuild is less strict than node. It actually parses a superset of CommonJS and ESM and then uses heuristics to try to make it work anyway. The heuristics first check for ESM exports (the `export` keyword), and then check for CommonJS exports (the `exports` or `module` variables), and then finally fall back to checking the `type` entry of `package.json`. The reason why the `import` keyword doesn't cause the module to become CommonJS is because there is code in the wild that uses ESM imports but CommonJS exports, and esbuild needs to be able to support such code. Anyway I believe that's why this is happening.

**Comment by fun4wut** [comment]
@evanw Great explanation! Thanks
