### ISSUE TITLE
replacing process.env.UNDEFINED_VAR

### ISSUE THREAD

**Issue by cvlmtg** [evanw/esbuild#1374]
Hi, I'm trying esbuild and so far I'm impressed by the speed! However I have an issue with `process.env` substitutions.

I followed the examples provided and used the `define` option, and it works as long as a variable is actually defined, but if, e.g., `UNDEF` is not defined, `process.env.UNDEF` is left as is in the code. With browserify it is replaced with an empty string, and I'd like to replicate this functionality with esbuild.

Any idea on how to solve this? I'm still new to esbuild, so maybe I'm missing out something.

Thanks!

**Comment by evanw** [comment]
There isn't built-in support for this. But you could use a [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) object to do this without needing to change esbuild at all:

```js
// env-proxy.js
export var process = {
  env: new Proxy({}, {
    get: () => '',
  })
}
```

If you build using `esbuild --bundle --inject:env-proxy.js` with the file above, that will replace references to the global `process` variable with the export from that file, and then any property access off of `process.env` that isn't replaced at compile-time by esbuild will end up as an empty string at run-time.

You can read more about the inject feature here: https://esbuild.github.io/api/#inject. Other approaches are possible too such as only replacing `process.env` instead of `process`.

**Comment by cvlmtg** [comment]
it works, thanks!

**Comment by shhdgit** [comment]
But this will cause all env variables to become empty string.

**Comment by evanw** [comment]
That’s up to you. The proxy is custom code that you write so you can have it do whatever you want.

**Comment by thscott** [comment]
Would it be possible to look at supporting the initial feature requested in this issue (a mechanism that replaces undefined process.env properties with "" or undefined)?

The current workarounds of defining process.env to {} or using inject, both work fine for runtime, but break support for tree shaking what should be unreachable code.

I'm currently explicitly defining all possible properties of process.env in my codebase, but it'd be nice to not have to do this.
