### ISSUE TITLE
Support JSX annotation

### ISSUE THREAD

**Issue by sarsamurmu** [evanw/esbuild#138]
Can we support JSX annotations?

Input
```js
// @jsx h
<div />
```
Output
```js
h('div') // Expected
React.createElement('div') // Actual
```
I am using esbuild in a build tool, that's why I need it.

**Comment by evanw** [comment]
The way to do this is to pass the `--jsx-factory=h` flag to esbuild or, if you're using the API, enable the `jsxFactory: 'h'` option. See also the [Using with React](https://github.com/evanw/esbuild/blob/9bdc08dbe37f62be20002fe51fd036e212177aa9/README.md#using-with-react) section in the readme.

**Comment by evanw** [comment]
This is now supported as of version 0.6.3.

**Comment by sarsamurmu** [comment]
That's great, Thanks

**Comment by bluepnume** [comment]
Is there a plan to also support `@jsxFragment` pragma? e.g. `@jsxFragment MyCustomJSXFragment`

**Comment by evanw** [comment]
> Is there a plan to also support `@jsxFragment` pragma? e.g. `@jsxFragment MyCustomJSXFragment`

Here are the release notes for version 0.6.3 (from [the commit that closed this issue](https://github.com/evanw/esbuild/commit/5c6b3ab0e25d68f3495e0f20c0e591749dc74fae), linked above):

> * Add support for `@jsx` and `@jsxFrag` comments ([#138](https://github.com/evanw/esbuild/issues/138))
> 
>     You can now override the JSX factory and fragment values on a per-file basis using comments:
> 
>     ```jsx
>     // @jsx h
>     // @jsxFrag Fragment
>     import {h, Fragment} from 'preact'
>     console.log(<><a/></>)
>     ```
> 
>     This now generates the following code:
> 
>     ```js
>     import {h, Fragment} from "preact";
>     console.log(h(Fragment, null, h("a", null)));
>     ```

As you can see, esbuild uses `@jsxFrag` instead of `@jsxFragment`. I did that because that's what https://babeljs.io/docs/babel-plugin-transform-react-jsx does, so AFAIK that's what the community is used to. I have no plans to also support `@jsxFragment` in addition to `@jsxFrag`.

**Comment by bluepnume** [comment]
That's perfect, sorry, should have read the commit! Thanks so much!
