### ISSUE TITLE
Is `esbuild.serve` faster than a custom node sever proxy?

### ISSUE THREAD

**Issue by JounQin** [evanw/esbuild#1405]
Hi, recently I'm trying to implement a bundler all with `esbuild`, no `rollup` inside like `vite`, at https://github.com/rx-ts/esbuilder.

The prototype is just working, but I need some advice from you.

Should I use `esbuild.serve` instead of a custom node server proxy on development? In case `esbuild.serve` is written in go, so I imagine it will be much faster than a custom node server which running `esbuild.build` + `watch` inside.

But unfortunately, `esbuild.serve`'s API is lack. I want my plugin like `@esbuilder/html` compatible with `esbuild.serve` at the same time. So maybe a virtual file system for `serve` would help.

**Comment by evanw** [comment]
You should benchmark it and see for yourself.

**Comment by heyheyhello** [comment]
@JounQin It's not worth your time to debate webserver speeds. Especially for a dev-server that so far, no offense, isn't being used by anyone yet. Focus on building the featureset you need and consider performance optimizations later when you actually run into bottlenecks.

**Comment by evanw** [comment]
I think the reason why the performance is unlikely to matter too much in your situation is actually because a) serving a file with a node proxy mostly just involves moving a few buffers around, which mainly happens in C++ and is very fast and b) serving a page usually involves only serving a few requests (one HTML file and one or two CSS/JS files). So even if the speed difference is 2ms vs. 20ms you are unlikely to perceive a speed difference and the choice of node vs. Go doesn't matter. Go is probably slightly faster than JS but both will probably be sufficiently fast.

But you could be in some special case where you are serving thousands of files per page (I have no idea what your use case is), in which case raw network performance could matter. You would be able to tell if you are in this situation if you compare the speed of both approaches and one is significantly slower than the other instead of both being about the same speed. In that case technology choice could matter. Measuring is the only way to know for sure which situation you are in though.

If your use case is indeed extremely performance sensitive, you still don't need to use esbuild's serve API (especially if you find the API lacking). You can write your own web server in Go and call esbuild's build API instead. Or you could use write a proxy server in whatever other language you choose (Rust/C++/etc.) instead of JS. The technology choice and approach is up to you and likely just depends on what you find most comfortable to work with.

**Comment by JounQin** [comment]
Thanks guys for your suggestions!
