### ISSUE TITLE
Add dependency without importing

### ISSUE THREAD

**Issue by Mokshit06** [evanw/esbuild#1412]
For React Server Components, the client build should output the imported files as it normally would but rather than importing the Client components (`.client.js`) in the app, it uses a `useServerResponse` hook which returns the output chunk name, and a few other properties. The issue is that esbuild won't bundle the `.client.js` files unless they are imported in one of the files.

Would it be possible to do something like this in esbuild?

**Comment by evanw** [comment]
At a high level the bundling algorithm in esbuild just works the way JavaScript works. So if you are using a framework that doesn't work the way JavaScript works, then it may not be possible to get it to work with esbuild (or lots of other JavaScript tools for that matter).

Here's a random idea that might help you (I'm not sure because I don't know anything about the framework you're talking about): If you want importing a file to magically also import additional files, you could use a plugin to intercept the loading of a file and add an additional `import` statement to the end during bundling: https://esbuild.github.io/plugins/#load-callbacks.

So if you want importing `xyz.js` to also include `xyz.client.js` in the bundle without an explicit import, the plugin would intercept the loading of `xyz.js` and add `import "./xyz.client.js"` to the end of the file. The reason for adding it to the end is that this won't affect the source map offsets so debugging won't be affected. Although depending on what the import does, you may need to insert the import at the beginning instead (e.g. if it does something to global state that the file doing the importing depends on).

**Comment by Mokshit06** [comment]
Wouldn't adding an `import` to the file also load it in the browser immediately? I just want it to be included in the bundle as a seperate chunk. 

Similar to how in webpack there is `addDependency` and in rollup there is `emitFile`

**Comment by Mokshit06** [comment]
I think what might work is adding a dynamic import inside a function so that it is included in the bundle but not fetched unless required. I'll try this and see if it works. Thanks!
