### ISSUE TITLE
Interesting behavior of single and double quote

### ISSUE THREAD

**Issue by ZYinMD** [evanw/esbuild#1417]
I use single quotes in writing .ts files, then after I run esbuild, all single quotes are changed to double quotes.

It's a small inconvenience that when I want to compare the diffs between my .ts and .js, there are a ton of diffs due to quote changes.

Interestingly, if I run with --minify, all quotes become single quotes again.

**Comment by evanw** [comment]
The only hard constraints on the generated JavaScript output are deliberately semantic, not aesthetic, because esbuild is not a code formatting tool. Code is pretty-printed when `--minify` is not specified because the code is intended to be readable by humans, but fine control over specific code formatting decisions is out of scope. It would be a bug if `--minify` generates code that is longer than it could be, otherwise any output that is the same length is valid. In fact forcing the same kind of quotes everywhere may even result in a slightly smaller size after being gzipped which is desirable. And anyway you will likely see behavior similar to what you described with many other JavaScript tools that generate JavaScript based on an AST since the [ESTree AST specification](https://github.com/estree/estree/blob/a050afde7b9ce11394a1491e8763b35d78d0f7ea/es5.md#literal) doesn't include the type of quote (it's not semantically relevant). Closing as "out of scope."
