### ISSUE TITLE
Probably CSS loader transformation bug

### ISSUE THREAD

**Issue by anwerso** [evanw/esbuild#1421]
I'm not sure whats going on here, all good on this example :

```
echo div { --hs: 216,55%; --l: 50%; color: hsl(var(--hs), var(--l)) } | esbuild --loader=css --minify
div{--hs: 216,55%;--l: 50%;color:hsl(var(--hs),var(--l))}
```

But output is broken when I add some old browser target:
```
echo div { --hs: 216,55%; --l: 50%; color: hsl(var(--hs), var(--l)) } | esbuild --loader=css --minify --target=chrome65
div{--hs: 216,55%;--l: 50%;color:hsl(var(--hs),,,var(--l))}
```

**Comment by evanw** [comment]
Thanks for the report. I can reproduce the issue. What's going on is that esbuild is matching this code with the pattern `hsl(a b c)` which is for the new color syntax from [CSS Color Module Level 4](https://drafts.csswg.org/css-color/#the-hsl-notation). That is then being converted to old color syntax using `hsl(a b c)` → `hsl(a, b, c)` for older browsers. The problem is that this only works when `var()` is substituted for a single token, not when it's substituted for multiple tokens. So this conversion should be disabled when `var()` is present.
