### ISSUE TITLE
Failed to download binaries from private registry in CI environment without internet access and yarn v1 as package manager

### ISSUE THREAD

**Issue by SkReD** [evanw/esbuild#1422]
We use an internal nexus instance that contains all of the packages we we need to build and those machines don't have access to the internet. Currently when we try to use esbuild it fails in CI since the installer attempts to download the public registry. We are using `yarn v1` as package manager.

None of solutions below worked:

`export NPM_CONFIG_REGISTRY`
`export npm_config_registry`
`yarn config set registry`
`yarn config set registry -g`
`.yarnc`
`.npmrc`

Yarn issues yarnpkg/yarn#5854 and yarnpkg/yarn#5683

Only worked solution was pre-install packages via npm install with --registry option for cache warmup. Also in docker there seems to be problem with process.env.TMPDIR and that require('os').tmpdir() is returns cwd instead of temp directory path (npm/npm#4531).

Can install script be extended with support for custom env variable for registry and with `--unsafe-perm` flag for correct process.env.TMPDIR value?

**Comment by evanw** [comment]
The plan for fixing these kinds of things is to try using optional dependencies instead: #789. I would like to experiment with that approach instead of trying to add a ton of custom flags to the installer for everyone's unusual use cases. My assumption is that optional dependencies should naturally just work with existing package managers even when they have been heavily reconfigured, although that still needs to be validated.
