### ISSUE TITLE
Private methods will be overwritten

### ISSUE THREAD

**Issue by 2z6c** [evanw/esbuild#1424]
Building the class which has a static field and two or more private methods, private methods will be overwritten by the last one.
```javascript
class T {
  #a() { return 'a'; }
  #b() { return 'b'; }
  static c;
  d() { console.log(this.#a()); }
}
```
The `d()` is expected to return `'a'`, but it returns `'b'`.
Here is the output code
```javascript
...
  var _a, __create, _b, __create;
...
  _a = new WeakSet();
  __create = function() {
    return "a";
  };
  _b = new WeakSet();
  __create = function() {
    return "b";
  };
...
```
`__create` is declared twice, and the first `__create` is overwritten by the next one.

**Comment by evanw** [comment]
Note to self: This only happens when the target is something other than `esnext`. The presence of `__create` likely indicates an uninitialized symbol reference since this is the first symbol in the runtime file. A workaround for this bug is setting the target to something other than `esnext` such as `--target=es6`.
