### ISSUE TITLE
Question: Why cyclic import warning?

### ISSUE THREAD

**Issue by koenbok** [evanw/esbuild#1429]
I'm working on an enhanced http-plugin example that supports import maps and I ran into the following issue I don't understand. I'm trying to import `react` from the following url:

https://ga.jspm.io/npm:react@17.0.2/index.js

I'm getting an error back saying: 

> Detected cycle while resolving import "default"

With the following import stack (remember I rewrite `react` to `https://ga.jspm.io/npm:react@17.0.2/index.js`):

```
 > http-url:https://ga.jspm.io/npm:react@17.0.2/index.js:1:29: error: Detected cycle while resolving import "default"
    1 │ import"object-assign";import e from"./cjs/react.production.min.js";export{defa...
      ╵                              ^

 > http-url:https://ga.jspm.io/npm:react@17.0.2/index.js:1:74: error: Detected cycle while resolving import "default"
    1 │ ...s/react.production.min.js";export{default}from"./cjs/react.production.min.j...
      ╵                                      ~~~~~~~

 > src/web.js:2:7: error: Detected cycle while resolving import "default"
    2 │ import React from "react";
      ╵        ~~~~~
```

So the following snippet generates a cyclic import warning. But I'm not sure why?

```
import e from"./cjs/react.production.min.js";export{default}from"./cjs/react.production.min.js";
```

**Comment by evanw** [comment]
One guess is that your plugin is also mapping the import for `./cjs/react.production.min.js` to `https://ga.jspm.io/npm:react@17.0.2/index.js` so the file is trying to import its own export. If that's the case, the problem is with the plugin since the import should be mapped to a different file instead. The error message could be made even more clear here to say what the import resolved to (which isn't necessarily obvious if plugins are present).

If that's not the case then it could be a bug in esbuild. If so, it would be useful for me to be able to run a reduced test case myself that demonstrates the issue so I can fix it.

**Comment by koenbok** [comment]
Okay let me verify that and build a test case if it seems a bug.

**Comment by koenbok** [comment]
So this was definitely my bug. The regex I used for the import mappings was not setup to do a full exact match, re-mapping _every path_ with `react` in it, and creating cyclic imports 😞
