### ISSUE TITLE
Fails on "--" as "Invalid build flag"; instead it is deisired that it should gracefully ignore it.

### ISSUE THREAD

**Issue by adrian-grajdeanu** [evanw/esbuild#1431]
When using cdk NodejsFunction (from @aws-cdk/aws-lambda-nodejs) with PNPM package manager, this is the command line that is generated for _local_ bundling:

```
pnpm exec esbuild -- --bundle "[project-root]/[code-path]/handler.ts" --target=node14 --platform=node --outfile="[project-root]/cdk.out/bundling-temp-8b6ed390c45688293451e8952dff247026fe61f6e0615cf20e46df2b884014ec/index.js" --external:aws-sdk
```
Alas, esbuild does not like the -- particle and fails.

In the grand scheme of things, this should not be of any concern to esbuild, but conforming to other tools that are traditionally used is a necessity.

This issue is to suggest esbuild gracefully ignores the "--" flag if present.

**Comment by adrian-grajdeanu** [comment]
Xref https://github.com/aws/aws-cdk/issues/15460

**Comment by evanw** [comment]
I haven't seen this before but from Google apparently `--` usually means "the following arguments are not flags" (see [this page](https://unix.stackexchange.com/questions/11376/what-does-double-dash-mean) for example). In that case respecting the generally-understood meaning of `--` would break your code in a different way. It would try to parse a file named `--bundle` as JavaScript. 

> This issue is to suggest esbuild gracefully ignores the "--" flag if present.

I don't think just ignoring `--` is the right solution since that would go against how `--` works in other command-line interfaces.

So I think the problem here is with whatever code is adding `--` in the first place, not with esbuild.

**Comment by adrian-grajdeanu** [comment]
Indeed, you are right.
The folks working on cdk are fixing the problem on their end, which is the right place to do it.
Closing this.
