### ISSUE TITLE
Import or Inject renames global variable

### ISSUE THREAD

**Issue by socialhacker** [evanw/esbuild#1442]
Disclaimer: I don't know what I'm doing.  :)  I'm not usually a JavaScript programmer.

I'm trying to bundle a third party library into my application.  The library uses the following pattern:

```javascript
var Bar;

(function () {
    Bar = function() { this.bar = 4; }
})()
```

Which I assume means it expects you to include it as a script on your page and then access it using the global `Bar`.  But when I either import this using `import "./bar.js"` or inject it from the command line using `--inject:./bar.js` the result is the same, the variable `Bar` has been renamed to `Bar2`, which means my code can no longer access it.  `Bar2` seems to be picked because there is a perceived collision with my code that uses `Bar` as `new Bar()`, if I make that `new Bar2()` then the libraries `Bar` is no longer renamed.

Have I missed an obvious solution?  Or is the library in question just doing something that is incompatible with the way esbuild expects the world to work?  As I said, I don't really know all of the JavaScript patterns and expectations yet, so I'm not sure who's expecting what.

**Comment by evanw** [comment]
This happens because esbuild does not support files in "global code" format. Input files are assumed to either be in ECMAScript module (ESM) format or in CommonJS format. Both of those formats isolate top-level variables to that file's scope so they don't leak out into the global scope. `var Bar` is being renamed to `Bar2` to avoid a conflict with `new Bar` because `var Bar` is a local variable to that file while `new Bar` is a reference to the global variable named `Bar`.

The easiest way to fix this is to just add `export {Bar}` to the end of the file, which would turn it into a file in the ESM format. You can either do this manually or, if you don't want to modify the file itself (e.g. the file is controlled by a package manager) you can edit the file during the build with a simple esbuild plugin that loads the file as a string and adds `export {Bar}` to the end: https://esbuild.github.io/plugins/#load-callbacks.

**Comment by hyrious** [comment]
If you are bundling to IIFE format, you can just mark the module you imported external with [this plugin](https://github.com/yanm1ng/esbuild-plugin-external-global) and put it before your script.

Otherwise, you should convert that file to ESM/CJS as evan said.

**Comment by socialhacker** [comment]
That makes sense, thanks.  I think I had read somewhere that using ```import "./filename.js"``` was equivalent to concatenation, but obviously it's not.  I'll check out the plugin options, or possibly just find a more module compliant library to substitute.  Thanks again.
