### ISSUE TITLE
Function calls in between import statements are reordered

### ISSUE THREAD

**Issue by almeidx** [evanw/esbuild#1444]
I did not test anything else, but presumably, esbuild just keeps the imports all in a big chunk and moves all the code in between them to the bottom

***

Consider the following code:
```ts
import pnp from '../../../.pnp.js';
pnp.setup();
import './database/connection';
```

Which esbuild compiles into:
```js
var import_pnp = __toModule(require("../../../.pnp.js"));
var import_connection = __toModule(require("./database/connection"));
import_pnp.default.setup();
```
This does not work, since I need the `pnp.setup()` function to be run before importing anything else besides the first file.

For instance, here's how the TypeScript Compiler does it:
```js
const _pnp_js_1 = tslib_1.__importDefault(require("../../../.pnp.js"));
_pnp_js_1.default.setup();
require("./database/connection");
```

**Comment by evanw** [comment]
The conversion from ESM to CommonJS done by esbuild attempts to preserve the behavior of the original code as much as possible. What you are observing happens because in ESM, all imports are essentially "hoisted" to the top of the file since all dependencies of a given file must be evaluated before any code in that file is evaluated. This is just how the JavaScript language works. More information: https://github.com/evanw/esbuild/issues/1395#issuecomment-869026051.

The code you wrote happens to work due to a defect in the TypeScript compiler: https://github.com/microsoft/TypeScript/issues/16166#issuecomment-318782098. Writing such code is risky because your code will break as soon as it's run in a real ESM environment (such as esbuild, or node's ESM mode, or in a browser).

I recommend you change your code instead. You can get the effect you want by moving the first two statements into a separate file and importing that instead:

```js
import './pnp-setup';
import './database/connection';
```

where `pnp-setup.js` looks like this:

```js
import pnp from '../../../.pnp.js';
pnp.setup();
```

This will do what you want because dependencies of a file are evaluated before the file itself, and in the order they were imported.

**Comment by almeidx** [comment]
> The conversion from ESM to CommonJS done by esbuild attempts to preserve the behavior of the original code as much as possible. What you are observing happens because in ESM, all imports are essentially "hoisted" to the top of the file since all dependencies of a given file must be evaluated before any code in that file is evaluated. This is just how the JavaScript language works. More information: [#1395 (comment)](https://github.com/evanw/esbuild/issues/1395#issuecomment-869026051).

I guess I didn't search well enough before making this issue, thanks for the heads up

> The code you wrote happens to work due to a defect in the TypeScript compiler: [microsoft/TypeScript#16166 (comment)](https://github.com/microsoft/TypeScript/issues/16166#issuecomment-318782098). Writing such code is risky because your code will break as soon as it's run in a real ESM environment (such as esbuild, or node's ESM mode, or in a browser).

Makes sense, I didn't know that was the case

> I recommend you change your code instead. You can get the effect you want by moving the first two statements into a separate file and importing that instead:
> 
> ```js
> import './pnp-setup';
> import './database/connection';
> ```
> 
> where `pnp-setup.js` looks like this:
> 
> ```js
> import pnp from '../../../.pnp.js';
> pnp.setup();
> ```
> 
> This will do what you want because dependencies of a file are evaluated before the file itself, and in the order they were imported.

Thanks for the suggestion, will do!
