### ISSUE TITLE
Sourcemaps are missing closing braces

### ISSUE THREAD

**Issue by edoardocavazza** [evanw/esbuild#1448]
Hi! I noticed that closing braces are not correctly mapped in sourcemaps generated by esbuild. Am I missing some configuration detail or is it something esbuild currently does not handle?

![image](https://user-images.githubusercontent.com/3907295/125900688-35c5b613-9f33-42bb-a6ca-becccfb83207.png)

**Comment by evanw** [comment]
Source maps don’t remap every single thing, just the important parts. I think you shouldn’t ever hit an exception or a pause in execution in those spots when using a debugger.

**Comment by edoardocavazza** [comment]
Yeah this is true for the debugging process, but tools for coverage reporting use them :( I don't know if other tools rely on those informations.

**Comment by glromeo** [comment]
@evanw I would like to make a case for the closing brackets as well because indeed I ran into an issue trying to use v8-to-istanbul where because the end range is missing in the sourcemap an entire function is ignored and marked as covered.
From one side I am trying to see whether is possible for the code coverage tool to be more resilient but from another side I see how the mapping for the end range would make the code coverage more precise and if it's not too much of a trouble (or of a performance drag) I'd love to see the change to happen in esbuild.
Would that be something you would consider a PR for if you don't have time for it?
