### ISSUE TITLE
PluginAPI Option to resolve all files first after that load them

### ISSUE THREAD

**Issue by alexanderniebuhr** [evanw/esbuild#1453]
I know is question is causing some performance hits, but is there a way to run the `build.onResolve` for all files first, then do some magic stuff with the information taken from that, after that running `build.onLoad`

The use case of this, is that I would need to manipulate the files based on the `importer` file. So, if the file is imported at the entry point, it could be built directly. If it is imported by another file (so nested files) would firstly to move some code of the nested file into the parent file, and then build the whole stuff.

We could discuss this Option, or if someone has any idea how to make it possible with the current available Plugin API would be very appreciated.

**Comment by evanw** [comment]
This isn't really possible to do with the way esbuild works since all files are processed in parallel. The code inside `onLoad` can't know whether or not it will be imported by an entry point in the future. This information may even be impossible to provide even for a non-parallel algorithm due to import cycles. However, you could do this by doing two builds in succession where the second build uses information from the first build do something different.

**Comment by alexanderniebuhr** [comment]
Thank you for you answer, and I will try to run the two builds :)
