### ISSUE TITLE
When using esbuild with external react I get Dynamic require of “react” is not supported

### ISSUE THREAD

**Issue by yigalirani** [evanw/esbuild#1454]
cross post from stackoverflow: https://stackoverflow.com/questions/68423950/when-using-esbuild-with-external-react-i-get-dynamic-require-of-react-is-not-s

**Comment by hyrious** [comment]
You may try [this plugin](https://github.com/yanm1ng/esbuild-plugin-external-global) to import react from a global name if you are bundling to IIFE format.

**Comment by yanm1ng** [comment]
> 

add build config:
```js
esbuild({
   //....
   define: {
      'process.env.NODE_ENV': 'production',
    },
})
```

**Comment by mattwoberts** [comment]
Hi.

I'm having the same issues here, and wondering if this is my misunderstanding about how this works..

We have react pulling in via a separate script, so I don't want esbuild to include react, so I'm trying to use the `external` property.

I've got an entry file that looks like this:

```javascript
import React from 'react';
import ReactDOM from 'react-dom';
...
```

And I'm building that for the web like this:
```javascript
require('esbuild').build({
    entryPoints: ['Assets/react/ReactBook.jsx'],
    bundle: true,
    external:['react','react-dom'],
    outfile: 'wwwroot/js/dist/ReactBookEsbuild.js',
  }).catch(() => process.exit(1))
```

That results in code that gives the same error (Dynamic require of react is not supported). Looking at the generated code I can see this:

```javascript
  // Assets/react/ReactBook.jsx
  var import_react19 = __toModule(__require("react"));
  var import_react_dom4 = __toModule(__require("react-dom"));
```

And that's where it all goes wrong, since that `__require` method throws the error.

Can anyone shed any light on this?

**Comment by mattwoberts** [comment]
Update - swapping from using `external` to use that plug as suggested by @hyrious seems to have done the trick for me

**Comment by dizefurkan** [comment]
I am facing same error. I have two library. 1 library does not have any issue but the other (same config) throw this error. Can anyone have any idea?
![Screenshot 2023-01-11 at 02 06 21](https://user-images.githubusercontent.com/28892291/211743615-5387cb6b-0068-4e2d-88ac-17106efd0150.png)

I try to external,
Also try add `import React from "react"` to tsx files. but there error is still there.
When i comment inhouse-components it is work. but when i open it it crash... any idea?

![Screenshot 2023-01-11 at 02 14 15](https://user-images.githubusercontent.com/28892291/211744118-2eb6bf1f-aae1-47c1-9164-2f795d468ba1.png)
