### ISSUE TITLE
Expose Handler in go

### ISSUE THREAD

**Issue by chowey** [evanw/esbuild#1457]
I propose that esbuild exposes an [http.Handler](https://pkg.go.dev/net/http#Handler) in the go API.

The [Serve](https://pkg.go.dev/github.com/evanw/esbuild/pkg/api#Serve) function launches a web server. This is convenient and performant for development work. But it is tricky to incorporate into a larger go program.

It would be very useful if the go API could generate a plain http.Handler. Something like the following function signature:

```go
func Handler(serveOptions ServeOptions, buildOptions BuildOptions) (http.Handler, error)
```

It looks like this would be straightforward to implement. I would be willing to submit a pull request if this feature is acceptable.

**Comment by evanw** [comment]
The server API is only meant for lightweight development scenarios (both the Go and the JS versions, which are very similar). It intentionally isn't designed to be extremely customizable since the point of the esbuild project is to primarily be a bundler, not to be a server. If you want something like that, you should be able to build it yourself using either [the build API](https://esbuild.github.io/api/#build-api) or by [passing traffic through a proxy that you write](https://esbuild.github.io/api/#customizing-server-behavior).

**Comment by chowey** [comment]
Currently passing traffic through a proxy that I write is the option I have to take. It is just harder to work with, even in a development scenario.

As I said, this should be straightforward to implement, and I would be willing to submit a pull request. But if it is against your vision for esbuild then I will hold off.

**Comment by evanw** [comment]
I consider this to be out of scope, sorry. Closing.
