### ISSUE TITLE
Support range requests in "serve" mode

### ISSUE THREAD

**Issue by mixtur** [evanw/esbuild#1463]
Now when a browser makes a GET request with headers like

```
Range: 847528500-847595525
content-type: multipart/byteranges
```
esbuild's server returns the entire file. It should only return the byte span specified in `Range`.

That is the way Potree loads very large (> 10GB) point clouds. 

Here is an example of the code responsible for such requests if you are interested - https://github.com/potree/potree/blob/develop/src/modules/loader/2.0/OctreeLoader.js#L52

**Comment by evanw** [comment]
This should already work. Here's the code for handling range requests in esbuild's built-in server:

https://github.com/evanw/esbuild/blob/1d3c10301f5180a276fd191e9cca3a78dc0a4f9a/pkg/api/serve_other.go#L240-L247

According to [the specification for range requests](https://httpwg.org/specs/rfc7233.html#header.range), I believe a range request is only valid if it starts with `bytes=`. The example you pasted didn't start with `bytes=`:

```
Range: 847528500-847595525
content-type: multipart/byteranges
```

but [the code you linked to](https://github.com/potree/potree/blob/3a5aaac8c2f4314a7d09d026fc86ccbc23845dca/src/modules/loader/2.0/OctreeLoader.js#L52) does appear to specify `bytes=`. Can you confirm whether the actual request has units or not? If it doesn't have units, then I think it's an invalid request and the fix should be to add the units instead of to change esbuild to accept invalid range requests.

**Comment by mixtur** [comment]
Oh. I see. You are right. The request was actually wrong. But for whatever reason [http-server](https://www.npmjs.com/package/http-server) actually handled my malformed request.

**Comment by lukeed** [comment]
because `http-server` doesn't really care if `bytes=` [is there or not](https://github.com/http-party/http-server/blob/master/lib/core/index.js#L263) whereas esbuild's does an [explicit check](https://github.com/evanw/esbuild/blob/1d3c10301f5180a276fd191e9cca3a78dc0a4f9a/pkg/api/serve_other.go#L276)

**Comment by mixtur** [comment]
![image](https://user-images.githubusercontent.com/2968077/128693168-0320e01e-54e9-4254-ac50-edb94281ef9c.png)

I changed my request to `bytes=...` but still have a problem with one request.

It seems the problem occurs when end byte is exactly at the end of the file.
https://github.com/evanw/esbuild/blob/1d3c10301f5180a276fd191e9cca3a78dc0a4f9a/pkg/api/serve_other.go#L281 there should probably be `parseRangeInt(r[dash+1:], contentLength)` without "-1".

**Comment by mixtur** [comment]
Nope sorry. My bad again. The end position should be 1 less on the request.
