### ISSUE TITLE
Unable to do an `npm install` with node `v14.17.3` using snap

### ISSUE THREAD

**Issue by maarteNNNN** [evanw/esbuild#1464]
It seems I can't do an `npm install` with the Vite bundler using snap. When I used node that was installed via `apt-get` repo it worked without any problem.

Node version from the `apt-get` repo: `v12.21.0`
Node version from the `snap` repo: `v14.17.3`

```
Operating System: Ubuntu 21.04
Kernel: Linux 5.11.0-22-generic
Architecture: x86-64
```

```
359 verbose stack Error: command failed
359 verbose stack     at ChildProcess.<anonymous> (/home/maarten/.npm-packages/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
359 verbose stack     at ChildProcess.emit (events.js:375:28)
359 verbose stack     at maybeClose (internal/child_process.js:1055:16)
359 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
360 verbose pkgid esbuild@0.12.15
361 verbose cwd /home/maarten/code/freelance/philho
362 verbose Linux 5.11.0-22-generic
363 verbose argv "/snap/node/4933/bin/node" "/usr/local/bin/npm" "i"
364 verbose node v14.17.3
365 verbose npm  v7.19.1
```

It seems that the `install.js` isn't getting generated:
https://github.com/evanw/esbuild/blob/3431cc835b6dcf8f6172665a68b1d9c8b80fb147/scripts/esbuild.js#L30-L40

Any ideas as to why the `install.js` doesn't generate correctly using snap?
Can you guide me on how to use the populate this param correctly:
https://github.com/evanw/esbuild/blob/3431cc835b6dcf8f6172665a68b1d9c8b80fb147/scripts/esbuild.js#L291
And I'll gladly open a PR with a solution if I find one.

**Comment by maarteNNNN** [comment]
I have used node version `v12.22.3` in snap and that does seem to work.

**Comment by evanw** [comment]
I'm confused. The `esbuild/scripts/esbuild.js` file you pointed to is a helper script that is only used for generating builds for CI and publishing. It's not ever published to npm, so it's not relevant for `npm install`. The `install.js` postinstall script should already be present in every esbuild package that's published to npm (e.g. you can see `install.js` in https://unpkg.com/browse/esbuild@0.12.16/).

If `npm install` works with `apt-get` node but not `snap` node, then it seems to me like the problem is with the node version you're trying to use instead of with esbuild. Perhaps this is a question for someone who works on snap? I have no idea how snap works so I don't think I'll be able to help you.

**Comment by maarteNNNN** [comment]
I see. I will close this. I could make this work using another version so it seems like a specific case.
