### ISSUE TITLE
Bug w/ named exports

### ISSUE THREAD

**Issue by o-alexandrov** [evanw/esbuild#1469]
Please find a reproduction of this bug here:
- https://codesandbox.io/s/esbuild-bug-with-named-exports-f4g23

The complete code sample there is 2 files:
```js
// named-exports.js
export const a = "a";
export const b = "b";
```
```js
// index.js
import * as namedExports from "./named-exports";

console.log(namedExports);
console.log(namedExports.default);
```

There are two npm scripts: `nodejs` & `esbuild`.
When you run `npm run nodejs`, you'd see the following output in the console:
```
[Module] { a: 'a', b: 'b' }     // namedExports
undefined                           // namedExports.default
```
whereas when you run `npm run esbuild`, the CLI output is:
  - note there's the unexpected `default` value
```
{ default: { a: [Getter], b: [Getter] }, a: [Getter], b: [Getter] }
{ a: [Getter], b: [Getter] }
```

---

As you could see above, `esbuild` provides a different output than plain Node.js either with `esm` to transpile JS, or by running against `.mjs` files.

_Originally posted by @o-alexandrov in https://github.com/evanw/esbuild/issues/532#issuecomment-873762517_

**Comment by hyrious** [comment]
This is because your code is actually transformed to CJS format _independently_ by esbuild-register.
The `__toModule` helper method in the result makes the _unknown format_ named-exports.js have a `default` prop. You may ask esbuild-register to do something like esm register to transform your code to esm and load them.

You may [search](https://github.com/evanw/esbuild/search?q=WrapWithToModule) the source code to see why it happens.

In fact, if you can bundle them all and run instead of let esbuild-register transform each file, the result will be the same as `npm run nodejs`. I've written another [tool](https://github.com/hyrious/esbuild-dev) to do such thing.

**Comment by o-alexandrov** [comment]
@hyrious thank you, yes, you are correct; the problem is with esbuild-register.
- I should have checked the `esbuild --bundle` output, added an additional npm script to the reproduction

I tried the tool you created [@hyrious/esbuild-dev](https://github.com/hyrious/esbuild-dev) and it doesn't have this issue. I'll be using it, thank you very much!

On a side note, the only problem with the tool you created is it needs a predefined script to be used as a module for node.js preloading
  - `node -r ...otherPreloadedModules -r @hyrious/esbuild-dev src/example.js` would fail

**Comment by hyrious** [comment]
> On a side note, imho, the only missing feature in the tool you created is it needs a predefined script (with `--cjs` flag enabled) to be used as a module for node.js preloading

The `-r` usage is what registers (esbuild-register, esm, ...) expect. However, I don't want to use a [deprecated](https://nodejs.org/api/modules.html#modules_require_extensions) feature as esbuild-dev's readme said.

Maybe you will be interested in creating such register by yourself.

**Comment by hyrious** [comment]
@o-alexandrov I found another register loading esm, maybe you could give it a try: https://github.com/antfu/esbuild-node-loader

**Comment by o-alexandrov** [comment]
@hyrious thank you, I need the preloaded module to return `cjs`, so `esbuild-node-loader` doesn't work for me
