### ISSUE TITLE
Ignore/exclude files/dirs from watch

### ISSUE THREAD

**Issue by schickling** [evanw/esbuild#1478]
It would be great if it there was a way to exclude/ignore files and/or directory when using `watch: true` (e.g. `node_modules`).

Maybe this is already possible via plugins as well?

**Comment by evanw** [comment]
This isn't possible with esbuild's built-in watch mode but it's trivial to use whatever external watch mode library you prefer instead of esbuild's built-in watch mode. Just turn off esbuild's watch mode and use [incremental builds](https://esbuild.github.io/api/#incremental) instead, then call `rebuild()` whenever your watch mode library detects a change.

**Comment by gustavopch** [comment]
I'd like this too. My use case is that I'm writing some stuff to the file system in `onRebuild`, so it triggers an extra rebuild that's not necessary:
- Build runs
- `onRebuild` writes a file
- Build runs again but this time unnecessarily

**Comment by evanw** [comment]
Since this issue was filed, esbuild has improved its watch mode to reduce the cases where rebuilds happen due to file system changes that are unrelated to the build: https://github.com/evanw/esbuild/pull/1676. So I'm closing this issue both because you can bring your own watch mode if you choose, and because the situation has already been improved.
