### ISSUE TITLE
Install script uses wrong registry

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [evanw/esbuild#1485]
I tried a fresh vite project which has esbuild as dep. When I try to run `npm install` i see that the install script is trying to download something from a different registry than npm is configured with.
Is there a way to override the url from the install.js so it is asking the correct registry for the package?
```
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node install.js
npm ERR! Trying to install "esbuild-windows-64" using npm
npm ERR! Failed to install "esbuild-windows-64" using npm: Command failed: npm install --loglevel=error --prefer-offline --no-audit --progress=false esbuild-windows-64@0.12.17
npm ERR! npm ERR! code ETARGET
npm ERR! npm ERR! notarget No matching version found for esbuild-windows-64@0.12.17.
npm ERR! npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! npm ERR! notarget a package version that doesn't exist.
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     C:\Users\<user>\AppData\Local\npm-cache\_logs\2021-08-01T20_58_36_415Z-debug.log
npm ERR!
npm ERR! Trying to download "https://registry.npmjs.org/esbuild-windows-64/-/esbuild-windows-64-0.12.17.tgz"
npm ERR! Failed to download "https://registry.npmjs.org/esbuild-windows-64/-/esbuild-windows-64-0.12.17.tgz": connect ETIMEDOUT
```

**Comment by evanw** [comment]
It's supposed to pick up the registry setting from npm's configuration. See https://github.com/evanw/esbuild/issues/1193#issuecomment-826374405. It sounds like [Yarn has bugs with nested npm invocations](https://github.com/evanw/esbuild/issues/1193#issuecomment-827003081) picking up the correct configuration, [as does npm](https://github.com/npm/cli/issues/2284). But this isn't a problem with esbuild (esbuild is just running the `npm` command). This is a problem with npm (or whatever package manager you have substituted for npm if applicable).

In case you're wondering, the reason why you're seeing the download from `registry.npmjs.org` in the logs is that the `npm install` has already failed and the esbuild installer is trying again with `registry.npmjs.org` just in case that works. But the issue is with the failed `npm install`.

I'm working on an alternate installation strategy that doesn't use a `postinstall` script. Hopefully this approach would work around these issues. You can follow along here for updates: https://github.com/evanw/esbuild/issues/789.

**Comment by dan-nl** [comment]
@sschneider-ihre-pvs, `npm i -D esbuild@0.12.16 vite` took care of the issue for now

**Comment by sschneider-ihre-pvs** [comment]
that sounds promising

**Comment by michaelfaith** [comment]
This is affecting us now too.  Angular v12 application builds are failing corporate-wide because esbuild is trying to install something from the yarn registry instead of our internal artifact store.  If installing an older version of esbuild fixes it, then it seems like this is a regression issue and not just some bug with npm/yarn.

**Comment by woppa684** [comment]
A possible cause for this is mentioned in the linked issue above. I would also like to see a solution here indeed. Maybe not doing a cwd would already fix it?

**Comment by evanw** [comment]
Do you have a self-contained way to reproduce this issue? Then we could figure out if there's a configuration issue and/or which piece of software needs to be fixed.

**Comment by michaelfaith** [comment]
That's going to be tricky without being behind some kind of firewall.  We did find something that helped with this, in case it points towards a root cause.  Our build boxes didn't have yarnrc files on them, just npmrc, which has worked fine for us til now.  After also explicitly setting the registry in a yarnrc to our registry, the esbuild postinstall went through.

**Comment by michaelfaith** [comment]
That doesn't really help @woppa684's issue though, with project level npmrc files not being picked up

**Comment by michaelfaith** [comment]
That's going to be tricky without being behind some kind of firewall. We did find something that helped with this, in case it points towards a root cause. We were still having issues (but with a slightly different error) after rolling back to 0.12.6.  Our build boxes didn't have yarnrc files on them, just npmrc, which has worked fine for us til now, since yarn falls back on that. After also explicitly setting the registry in a yarnrc to our registry, the esbuild postinstall went through.  But still with the older version.  

But even that doesn't really help @woppa684's issue though, with project level npmrc files not being picked up

**Comment by michaelfaith** [comment]
I'll retry in the morning with the newer version and that setup.
