### ISSUE TITLE
import {version} from '../package.json'

### ISSUE THREAD

**Issue by binary64** [evanw/esbuild#1486]
Hi, in my TypeScript source, I wish to import the version from package.json as a variable that I can use within my app.

```typescript
import {version} from '../package.json'
console.log(`We're running ${version}!`)
```

However, I get this error:

```
> node --experimental-json-modules esbuild.cjs

(node:17268) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
file:///C:/p/dist/main.mjs:11
import { version } from "../package.json";
         ^^^^^^^
SyntaxError: The requested module '../package.json' does not provide an export named 'version'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:179:5)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
    at async handleMainPromise (node:internal/modules/run_main:63:12)
```

I found a workaround, which is `bundle: true`, but I'm not sure I want to bundle.

My esbuild.cjs is:
```javascript
require("esbuild")
  .build({
    entryPoints: ["src/main.ts"],
    format: "esm",
    platform: "node",
    outfile: "dist/main.mjs",
    sourcemap: true,
  })
  .catch(() => process.exit(1));
```

**Comment by hyrious** [comment]
Native JSON modules do not have (and will not have) named exports according to the [proposal](https://github.com/tc39/proposal-json-modules/blob/master/README.md#why-dont-json-modules-support-named-exports). The correct way to import a json file natively is:

```js
import pkg from "../package.json"
```

However, I do not recommend you to do this, since it requires `--experimental-json-modules` even in node16 and it prints warning message in console.

A better way for node.js can be found in [the doc](https://nodejs.org/api/esm.html#esm_no_json_module_loading).

If your target platform is browser, then bundling is maybe better.

Besides, if you want to emit d.ts files, see [this stackoverflow thread](https://stackoverflow.com/questions/55753163/package-json-is-not-under-rootdir).

**Comment by evanw** [comment]
The `import {version}` form is nice because the bundler will tree-shake everything else away. That’s an esbuild-specific extension, however, and can only be used when bundling. If you are running this in node directly instead of bundling with esbuild firet than you have to go by node’s rules, not esbuild’s rules. And this doesn’t work in node for the reasons mentioned above. 

Although I don’t think this is a fundamental limitation of node, just an implementation choice, so you could potentially try to get that changed in the proposal. The proposal gives the reason “not all object property keys are JavaScript identifiers that can be bound as named imports” which isn’t a valid reason anymore now that [arbitrary module namespace identifiers](https://github.com/bmeck/proposal-arbitrary-module-namespace-identifiers) exist.
