### ISSUE TITLE
[Feature] Output bundle analysis

### ISSUE THREAD

**Issue by tracker1** [evanw/esbuild#15]
Webpack (and via extension, Parcel) support outputting a bundle analysis which shows visually the relative size of the modules of the built package, which is very useful for isolating problem areas.

**Comment by evanw** [comment]
I agree this would be very helpful. It seems like something that people might need very different things from though. I wonder if the best way to approach this for now cost/benefit wise is to have a way to output structured metadata about the bundle to a file so that other tools can consume it. A proposal would be to write out each module's path, original size, bundled size, and dependencies. There may already be a standard format for this kind of thing out there.

**Comment by evanw** [comment]
Version 0.4.8 includes a `--metafile` flag where you can output information about the bundle in JSON format. This should make it possible to integrate that information into other tools for analysis and display. See #140 for an example of such an integration.
