### ISSUE TITLE
esbuild.exe blocked by Norton 360  Heur.AdvML.B

### ISSUE THREAD

**Issue by DaveSharman** [evanw/esbuild#1508]
When esbuild is installed in a project     npm i esbuild   norton blocks installation of exbuild.exe

"esbuild.exe contained threat Heur.AdvML.B"

this also happens when trying to build a new angular 12.2 project, that fails on the esbuild.exe
[2021-08-07T17_36_11_561Z-debug.log](https://github.com/evanw/esbuild/files/6949531/2021-08-07T17_36_11_561Z-debug.log)

to duplicate  
mkdir test
cd test
npm init
npm i esbuild      <-  fails on this step.

**Comment by DaveSharman** [comment]
Note:   with Angular/cli 12.2  it tries to install esbuild@0.12.17   explicitly installing 0.12.18 fails as well.

**Comment by evanw** [comment]
This is a problem with Norton, not with esbuild. It's well-known that antivirus software causes issues with legitimate software due to false positives. You are welcome to submit a false positive report to to your antivirus vendor about esbuild if you'd like. A Google search says the submission form is here: https://symsubmit.symantec.com/.

Closing since this isn't a problem with esbuild.

**Comment by DaveSharman** [comment]
Thanks for the info.    Much appreciated
