### ISSUE TITLE
Entry hashes changes between sourcemap mode false and external

### ISSUE THREAD

**Issue by stoivo** [evanw/esbuild#1514]
Thanks for creating esbuild, it is an amazing tool.

We want to build without sourcemaps for production but want to produce them and ship them to a third party error tracker.   
We planned to run esbuild twice, once for production use without sourcemaps and once with output to a different directory with sourcemaps in external mode. We thought the output files would be the same, with same hashes, but the hashes are not the same (content is). That's our problem, your issue ;) Is this an issue or wrong assumptions from us?

Attached an example here:
```
$ cat esbuild.ts
function hello(name: string){
  console.log(`hello, ${name}`);
}
$ ./node_modules/.bin/esbuild esbuild.ts --outdir=tmp --entry-names=hello-[name]-[hash]

  tmp/hello-esbuild-OD4SSJDG.js  58b 

⚡ Done in 5ms
$ ./node_modules/.bin/esbuild esbuild.ts --sourcemap=external --outdir=tmp --entry-names=hello-[name]-[hash]

  tmp/hello-esbuild-SMXKPHEQ.js       58b 
  tmp/hello-esbuild-SMXKPHEQ.js.map  219b 

⚡ Done in 4ms
$ md5sum tmp/hello-esbuild-OD4SSJDG.js tmp/hello-esbuild-SMXKPHEQ.js
92b916ef8e4d918be15c40868649fe3f  tmp/hello-esbuild-OD4SSJDG.js
92b916ef8e4d918be15c40868649fe3f  tmp/hello-esbuild-SMXKPHEQ.js
```

**Comment by evanw** [comment]
There are two ways to do source map hashing:

1. The hashes for the primary file name and the source map file name are the same.

    This way you can easily find one given the other one, just by adding or removing `.map`. In this case [the source map data has to be included in the hash](https://github.com/evanw/esbuild/blob/a9456dfbf08ab50607952eefb85f2418968c124c/internal/bundler/linker.go#L5204-L5222). If it wasn't included, then the source map contents might change while the hash stays the same, which violates the guarantee that the hash changes if the contents change. That's important because if your web server is configured to tell browsers to cache things forever (as it should be if you're using hashes), then browsers would be incorrectly downloading stale source maps.

2. The hashes for the primary file and the source map are different.

    In this case primary file name and the source map file name could be impossible to match up without some external mapping, especially if there's no `sourceMappingURL` comment linking the two together. But the source map data doesn't need to be included in the hash of the primary file because the source map can change without changing anything about the primary file.

I decided to go with option 1 because having the primary file name and the source map file name match makes them much easier to work with. But that has this consequence that you have noticed. I haven't thought of a way around this limitation.

I recommend just always building with external source maps enabled and then deleting them if you don't want them. That way both builds should line up exactly.

**Comment by stoivo** [comment]
Option 1 sound much better. I see the arguments for adding the content of the source maps in the hash.

We will build our assets with sourcemaps twice.

Thanks again

**Comment by evanw** [comment]
> We're doing this as a incremental rollout (with some performance metrics) as we've been burned before by changes to minifiers deoptimizing hot paths (ex: by inlining too much code and [overflowing a compiled function byte limit](https://source.chromium.org/chromium/chromium/src/+/main:v8/src/objects/shared-function-info-inl.h;l=246-248;drc=36c59c53be1d8852f5087008c45a95797bac9730)).

Luckily esbuild doesn't currently inline non-trivial functions, so I wouldn't expect this particular thing to happen with esbuild. There are some minifications that esbuild does to use newer JavaScript language features when they are shorter such as converting `a !== null && a !== undefined ? a.b : undefined` into `a?.b` that could hypothetically deoptimize a hot path if those newer JavaScript language features are unoptimized. But esbuild won't do this if the `target` setting is configured to an environment that doesn't support these features.

> Also, to achieve our rolllout strategy we currently run the build up until minification and then run both minifiers (generating two sets of bundles). The lack of inputSourceMaps also means that we'd need to write //# sourceMappingURL= lines for esbuild that we don't want in our non-esbuild version.

One idea for handling this during your rollout is to write an esbuild plugin with an `onLoad` hook that automatically adds the `//# sourceMappingURL=` comments on the fly at build time.

> Would love to hear your thoughts. Also, if you can think of an alternative/better way to achieve what we're trying to do please let me know!

From what I understand, both of your proposed solutions would still have the problem of how to associate the output files with their source maps. How were you planning on handling that with your proposed solutions?

Since you asked, here's another idea: `--sourcemap-hashes=separate` would break the constraint that the output file and source map hashes are the same. There could be a reference to the source map in the output file metadata in the metafile JSON that esbuild can generate, which you would then have to use to associate the output files with their source maps.

**Comment by issacgerges** [comment]
> One idea for handling this during your rollout is to write an esbuild plugin with an onLoad hook that automatically adds the //# sourceMappingURL= comments on the fly at build time.

This worked great to keep the annotations out of the final assets, still (obviously) have the inconsistent hashes between builds.

> How were you planning on handling that with your proposed solutions?

In the ideas I was proposing, you'd be able to optionally opt-out of using the sourcemap hash as part of the filename (for both the assets and the sourcemaps). By saying `assets/[name]-[hash]` vs `assets/[name]-[combinedhash]` you'd be explicitly asking esbuild to only use the content hash (not including sorucemap data) in both the asset and sourcemap filename. I definitely see how this could be counterintuitive and break API.

`--sourcemap-hashes=separate` would definitely work (with a rename step). If this is something you'd consider I can take a peek at implementing it. 

One naive idea we had was to generate the files with no hashes and  just grab the the last 8 of the base32 encoded content bytes to generate a hash ourselves. Since the build generates the same output the hashes would be the same between the two. I know internally `esbuild` generates the hash with a combination of the contents and the hashes of its dependencies. I'm guessing there's a good reason, and curious what we might be missing

Thanks!
