### ISSUE TITLE
type imports are not removed

### ISSUE THREAD

**Issue by swandir** [evanw/esbuild#1525]
In TypeScript modules type imports are not removed, unless `importsNotUsedAsValues` is `"remove"`.

**Given**

tsconfg.json
```json
{
  "compilerOptions": {
    "noEmit": true,
    "isolatedModules": true,
    "importsNotUsedAsValues": "error"
  }
}

```

module.ts
```typescript
export type Type = unknown;
export const runtimeValue = undefined;
```

main.ts
```typescript
import { Type, runtimeValue } from "./module";

export const value = runtimeValue as Type;
```

**ESBuild emits**
```js
import { Type, runtimeValue } from "./module";
export const value = runtimeValue;
```

Which is not correct, because valid TypeScript is transformed into invalid JavaScript.

Note that `tsc` _does not emit an error_ in that case despite what one might think `"importsNotUsedAsValues": "error"` means.

Basically, type imports should be removed always.

**Update:**
To clarify: import statements should be preserved, but _imported types_ should still be removed.
So this code
```ts
import { Type } from "./module";
```
woud be transformed into
```js
import "./module";
```
---
Related issue: vitejs/vite#4581
Repro: [esbuild-type-import-repro](https://github.com/swandir/esbuild-type-import-repro)

**Comment by hyrious** [comment]
I think this behavior is right, since the [TypeScript Docs](https://www.typescriptlang.org/tsconfig#importsNotUsedAsValues) said:
> `error`: This preserves all imports (the same as the preserve option) ...

As of vite, I think it can do a hack in [transforming](https://github.com/vitejs/vite/blob/main/packages/vite/src/node/plugins/esbuild.ts), since you always want valid javascript output.

**Comment by swandir** [comment]
> I think this behavior is right, since the [TypeScript Docs](https://www.typescriptlang.org/tsconfig#importsNotUsedAsValues) said:
> 
> > `error`: This preserves all imports (the same as the preserve option) ...
> 

It does preserve imports, but still removes types.

So this code
```ts
import { Type } from "./module";
```
will be transformed into
```js
import "./module";
```

**Comment by hyrious** [comment]
I get it. However I'm in doubt that esbuild could do this checking, since it only knows some names not _in use_, instead of knowing which of them are _types_.

So this code
```ts
import { a, Type } from "./module"
let x: Type = 1
```

will be transformed into

```js
import "./module"
```

Emm, it looks fine though.

**Comment by swandir** [comment]
ESBuild transforms this
```ts
import { T, v } from "./module";
let t: T;
```
into this
```js
let t;
```
when `importsNotUsedAsValues` is `remove`.
Which is inline with that tsc does (except tsc also adds `export {}`, should esbuild do it too?..)

So I guess with `"importsNotUsedAsValues": "remove"/"preserve"` esbuild could just transform the same code into this
```js
import "./module";
let t;
```
which would match what tsc does exactly.

**Comment by swandir** [comment]
> So this code
> 
> ```ts
> import { a, Type } from "./module"
> let x: Type = 1
> ```
> 
> will be transformed into (when `importsNotUsedAsValues` is `preserve` or `error`)
> 
> ```js
> import "./module"
> let x = 1
> ```
> 
> Emm, it looks fine though.

Yeah, that's what tsc does

**Comment by evanw** [comment]
TypeScript might be changing their behavior for this soon. See https://github.com/microsoft/TypeScript/issues/43393 and https://github.com/microsoft/TypeScript/pull/44619. I think the new behavior will be something like `--importsNotUsedAsValues=preserve` still does not preserve imports that aren't used as values, but you can additionally add `--preserveValueImports` to actually preserve unused imported values. We'll have to see what the behavior ends up being when the next version of TypeScript is released. When that happens, esbuild can be changed to do what that version of TypeScript does.

**Comment by dummdidumm** [comment]
The new behavior does not necessarily relate to what the expected existing behavior is. Essentially it comes down to what is inside the `tsconfig.json`.

- If `importsNotUsedAsValues` is `remove`: Remove all unused values (which includes types, because they are never used as a value). If no value is left, remove the import altogether
- If `importsNotUsedAsValues` is `preserve`: Remove all unused values (which includes types, because they are never used as a value). If no value is left, keep the import.
- If `importsNotUsedAsValues` is `error`: Remove all unused values (which includes types, because they are never used as a value). If no value is left, keep the import. If all imports are only used as a type, emit an error
- If `preserveValueImports` is turned on, keep all imports not prepended with `type` no matter if they are used or not.

For ESbuild this means:
- If `importsNotUsedAsValues` is `remove`: Current behavior is correct
- If `importsNotUsedAsValues` is `remove` / `error`: These cases are the same to ESBuild as it doesn't deal with type-checking. In both cases, ESBuild needs to remove all unused imports (which includes type imports) and keep the import no matter what. **this is not what ESBuild does currently so this is a bug in my eyes**
- If `preserveValueImports` is turned on, keep all imports not prepended with `type` no matter if they are used or not. **this is what ESBuild currently does for `importsNotUsedAsValues` is `remove` / `error`**

**Comment by evanw** [comment]
This has now been released: https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#preserve-value-imports. So I plan to implement support for `preserveValueImports`, which should be straightforward. However, now that this feature exists, this hack that was made so esbuild could be used for Svelte (see #604) can now be removed, which means esbuild's output for import statements can now match the TypeScript compiler (Svelte use cases will now have to enable `preserveValueImports`). Making esbuild align with TypeScript's behavior exactly is a breaking change, and should be done in a breaking change release. I'm adding this comment to remind myself to do this.

**Comment by abdedarghal111** [comment]
For newer people, I got empty types import like this one:
```mts
// in typescript (mts)
import { type CommandCoupleType } from "../commands/commands.mts";
```
```mts
// processed with esbuild (mjs)
import {} from "../commands/commands.mjs";
```
Setting `"verbatimModuleSyntax": false` in `tsconfig.json` worked for me.

**Comment by IanVS** [comment]
That is how tsc works as well.  You can also keep `verbatimModuleSyntax` enabled and write your imports as `import type  CommandCoupleType } from "../commands/commands.mts";` if you would like the whole import statement to be removed.
