### ISSUE TITLE
Memory consumption when serving many range request from one large file

### ISSUE THREAD

**Issue by mixtur** [evanw/esbuild#1536]
When esbuild is started in the serve mode it consumes around 40-50MB on my system.

But when I open a page in a browser and the page starts making many small range requests suddenly memory consumption jumps to around 6GB which is scarry.

The requested file is about 800Mb in size, and we are making 10 to 20 request on startup, each request has a Range header with a range usually less than 100kB in size.

esbuild version was 0.12.21
I was running it on Windows 10
Memory consumption was measured using Windows Task Manager

**Comment by evanw** [comment]
Thanks for pointing this out. This is because the implementation of range requests currently reads the whole file and then returns a subset. That makes sense for output files files served from memory but doesn't make sense from files that need to be read from the file system. It should be possible to fix this.
