### ISSUE TITLE
Request: Expose list of imports in onLoad/onResolve argument to allow custom tree-shaking

### ISSUE THREAD

**Issue by mitschabaude** [evanw/esbuild#1542]
I'm working on a [plugin](https://github.com/mitschabaude/esbuild-plugin-wat) that can import WebAssembly (`.wasm` or `.wat`) files. Next, I'd love to enable tree-shaking of WebAssembly.

To give an example, say I am processing the following import:

```js
import {someFunction} from './my-module.wasm'
```

My plugin (in a future iteration) will translate functions that are exported from the wasm file to ones that can be directly called from JavaScript.

Now, I would also like to use the information that only `someFunction` was imported to strip away functions and globals in the wasm file that are not needed to provide `someFunction`.

However (AFAIU) the list of imports present in the import statement is currently not exposed to plugins in any way.

Would it be possible to expose the list of imports as additional arguments to the onLoad and/or onResolve handlers?

I know that the plugin API is intentionally limited in scope, but I thought that possibly this information is available anyway when handing over imports to plugins and just needs to be exposed.

**Comment by hyrious** [comment]
Instead of waiting for new feature, I think this requirement can be achieved in a plugin:

It requires [parse-imports](https://github.com/TomerAberbach/parse-imports).
```js
let searchImportPlugin = {
    name: 'test',
    setup({ onResolve, onLoad }) {
        let fs = require("fs")
        let parse
        onResolve({ filter: /()/ }, async args => {
            parse = parse || (await import("parse-imports")).default
            if (args.importer && args.kind === 'import-statement') {
                let code = await fs.promises.readFile(args.importer, 'utf8')
                for (let a of await parse(code)) {
                    console.log(a.moduleSpecifier.value, a.importClause.named)
                }
                // TODO:
                // if code imports *.wasm, save the named imports to pluginData
                // then, in onLoad(/\.wasm$/), do what we want.
            }
        })
    }
}
```

**Comment by evanw** [comment]
> Would it be possible to expose the list of imports as additional arguments to the onLoad and/or onResolve handlers?

This isn't really possible to do with the way esbuild works since all files are processed in parallel. The code inside `onLoad` can't know whether or not it will be imported by an entry point in the future.

This information may even be impossible to provide even for a non-parallel algorithm due to import cycles. For example, consider two files A and B that each import each other. If the entry point is A, `onLoad` for A must be run to return the contents of A. Then given the contents of A we discover that A imports B, so `onLoad` for B is also run to return the contents of B. Then given the contents of B we discover that B imports A. But the `onLoad` for A was already run, so the list of imports to A was incorrect (and it's now impossible to make it correct).

However, you could do this by doing two builds in succession where the second build uses information from the first build do something different.

> A simple workaround is to bundle twice, the first we scan imports, the second do bundle.

Yes, exactly this.

**Comment by mitschabaude** [comment]
Thanks a lot, both of you!

I completely forgot that a file will be imported multiple times, with different lists of imports 😅

The idea of parsing imports myself is great, I'll do that, and yeah probably bundle twice just to get the merged list of imports.
