### ISSUE TITLE
[Feature Request] Add `--bundle-relative` flag

### ISSUE THREAD

**Issue by loynoir** [evanw/esbuild#1564]
### Feature Request
Add `--bundle-relative` flag, only bundle all `relative-alike` files.

### Scenario

Relative import may conflict, when using output extension `.mjs`.

https://github.com/evanw/esbuild/issues/1563

Maybe 
- add extension name to relative importId,
- or eliminate relative import doing a minimal bundling.

### Description

```ts
import foo from '{{importId}}'
```

| importId     | bundle | Description |
| ----------- | ----------- | ----------- |
| ./foo     | true     | relative import     |
| /{{packageRoot}}/foo   | true        | absolute import    |
| /{{outside}}/foo   | false        | absolute import     |
| #foo   | true        | subpath import     |
| foo   | false        | namespace import and all else   |

<details>
  <summary>#foo</summary>
  <p>
 
[https://nodejs.org/api/packages.html#packages_subpath_patterns](https://nodejs.org/api/packages.html#packages_subpath_patterns
)

  </p>
</details>

**Comment by hyrious** [comment]
You can write a plugin using `onResolve` to externalize paths outside of cwd.

**Comment by loynoir** [comment]
@hyrious 
It can. 

But `esbuild` is awesome for out-of-box experience for typescript. Maybe add an `external` preset or something?

Or any plan for issue#1563 ?

**Comment by evanw** [comment]
TypeScript's upcoming version 4.5 now has a way to do this. If you have a TypeScript file that needs to import another TypeScript file that will have a `.mjs` extension when compiled, you should use the `.mts` file extension for the TypeScript file and you should use `import "./deps.mjs"` in your TypeScript code to import `deps.mts`. This will be the official way to do it going forward and doesn't need any special support from esbuild. You can read the announcement here: https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/#new-file-extensions.

Closing this issue since this is being addressed outside of esbuild by the TypeScript team, and is possible to implement within esbuild via a plugin without needing to modify esbuild itself.
