### ISSUE TITLE
Convert an object key named "a・" to the invalid character during minify

### ISSUE THREAD

**Issue by hibikine** [evanw/esbuild#1599]
ESBuild converts object keys that contain katakana middle dot (U+30FB, ・) into incorrect syntax when minifying them.

## Environment

* Node.js 14.17.5
* npm 6.14.14
* ESBuild 0.12.27
* Ubuntu 20.04 (Windows Subsystem for Linux)

Reproduce: https://github.com/hibikine/esbuild-nakaguro

## Details

```js
const a = { 'a・': 'foo' };
console.log(a);
```

This code is minified into

```js
const a={a\u30FB:"foo"};console.log(b);
//       ^^^^^^^
// SyntaxError: Invalid or unexpected token
//    at wrapSafe (internal/modules/cjs/loader.js:988:16)
//    at Module._compile (internal/modules/cjs/loader.js:1036:27)       
//    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)     
//    at Module.load (internal/modules/cjs/loader.js:937:32)                
//    at Function.Module._load (internal/modules/cjs/loader.js:778:12) 
//    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)       
//    at internal/main/run_main_module.js:17:47
```

## Expects

Object key includes "・" should be wrapped with quotes.

```js
const a={"a\u30FB":"foo"};console.log(b);
```

**Comment by evanw** [comment]
How strange. That code point sequence appears to be a valid identifier in ES5 but not in ES6+. I had assumed (incorrectly) that all identifiers which are valid in ES5 are still valid in ES6+, since otherwise upgrading a VM to support ES6 would have caused previously-working code to stop working.

I guess this is what is meant by the ES6 specification calling out Unicode in IdentifierName in the [section on incompatibilities with prior editions](https://262.ecma-international.org/6.0/#sec-additions-and-changes-that-introduce-incompatibilities-with-prior-editions):

> 11.6: In ECMAScript 2015, the valid code points for an _IdentifierName_ are specified in terms of the Unicode properties “ID_Start” and “ID_Continue”. In previous editions, the valid _IdentifierName_ or _Identifier_ code points were specified by enumerating various Unicode code point categories.

I can modify esbuild to only do this for identifiers that are valid in both ES5 and ES6+. My research for what an identifier means in both ES5 and ES6+ is below:

## ES5

Here's what [the ES5 specification](https://262.ecma-international.org/5.1/#sec-7.6) says about identifiers:

```
IdentifierName ::
  IdentifierStart
  IdentifierName IdentifierPart

IdentifierStart ::
  UnicodeLetter
  $
  _
  \ UnicodeEscapeSequence

IdentifierPart ::
  IdentifierStart
  UnicodeCombiningMark
  UnicodeDigit
  UnicodeConnectorPunctuation
  <ZWNJ>
  <ZWJ>

UnicodeLetter ::
  any character in the Unicode categories
    “Uppercase letter (Lu)”,
    “Lowercase letter (Ll)”,
    “Titlecase letter (Lt)”,
    “Modifier letter (Lm)”,
    “Other letter (Lo)”, or
    “Letter number (Nl)”.

UnicodeCombiningMark ::
  any character in the Unicode categories
    “Non-spacing mark (Mn)” or
    “Combining spacing mark (Mc)”

UnicodeDigit ::
  any character in the Unicode category
    “Decimal number (Nd)”

UnicodeConnectorPunctuation ::
  any character in the Unicode category
    “Connector punctuation (Pc)”
```

In addition, it says to use Unicode 3.0.0:

> A conforming implementation of this Standard shall interpret characters in conformance with the Unicode Standard, Version 3.0 or later and ISO/IEC 10646-1 with either UCS-2 or UTF-16 as the adopted encoding form, implementation level 3. If the adopted ISO/IEC 10646-1 subset is not otherwise specified, it is presumed to be the BMP subset, collection 300. If the adopted encoding form is not otherwise specified, it presumed to be the UTF-16 encoding form.

The character U+30FB is `KATAKANA MIDDLE DOT` which is in the `Pc` category in [Unicode 3.0.0](https://www.unicode.org/Public/3.0-Update/UnicodeData-3.0.0.txt). So `a\u30FB` is a valid identifier in ES5:

```
30FB;KATAKANA MIDDLE DOT;Pc;0;ON;;;;;N;;;;;
```

## ES6

Here's what [the ES6 specification](https://262.ecma-international.org/5.1/#sec-7.6) says about identifiers:

```
IdentifierName ::
  IdentifierStart
  IdentifierName IdentifierPart

IdentifierStart ::
  UnicodeIDStart
  $
  _
  \ UnicodeEscapeSequence

IdentifierPart ::
  UnicodeIDContinue
  $
  _
  \ UnicodeEscapeSequence
  <ZWNJ>
  <ZWJ>

UnicodeIDStart ::
  any Unicode code point with the Unicode property “ID_Start”

UnicodeIDContinue ::
  any Unicode code point with the Unicode property “ID_Continue”
```

In addition, it says to use Unicode 5.1.0:

> A conforming implementation of ECMAScript must interpret source text input in conformance with the Unicode Standard, Version 5.1.0 or later and ISO/IEC 10646. If the adopted ISO/IEC 10646-1 subset is not otherwise specified, it is presumed to be the Unicode set, collection 10646.

The character U+30FB is `KATAKANA MIDDLE DOT` which is not in the `ID_Continue` category in [Unicode 5.1.0](https://www.unicode.org/Public/5.1.0/ucd/DerivedCoreProperties.txt). So `a\u30FB` is not a valid identifier in ES6+:

```
30A1..30FA    ; ID_Continue # Lo  [90] KATAKANA LETTER SMALL A..KATAKANA LETTER VO
30FC..30FE    ; ID_Continue # Lm   [3] KATAKANA-HIRAGANA PROLONGED SOUND MARK..KATAKANA VOICED ITERATION MARK
```

**Comment by evanw** [comment]
After some investigation, it looks like the only two characters this affects are U+30FB `KATAKANA MIDDLE DOT` and U+FF65 `HALFWIDTH KATAKANA MIDDLE DOT`.

**Comment by hibikine** [comment]
Thank you!
