### ISSUE TITLE
Transform API does not generate sourceMappingURL comment when sourcemap is set to true

### ISSUE THREAD

**Issue by zen0wu** [evanw/esbuild#1627]
Not sure if this is intentional, but the doc seems to suggest it should?

https://esbuild.github.io/api/#sourcemap

If this sourceMappingURL=x.js generation only applies to the build API, it would be great to clarify in the doc.

**Comment by evanw** [comment]
This is intentional. The transform API doesn't have the output file name, so it doesn't have enough information to fill in the comment. Since the caller of the transform API presumably has that information, the caller can easily just append a sourceMappingURL comment to the transform API output instead. Something like this:

```js
const { code, map } = await esbuild.transform(input, { sourcemap: true })
const outfile = 'out.js'
fs.writeFileSync(outfile, `${code}//# sourceMappingURL=${outfile}.map\n`)
fs.writeFileSync(outfile + '.map', map)
```

**Comment by evanw** [comment]
[Docs](https://esbuild.github.io/api/#sourcemap) have been updated. Closing.

**Comment by zen0wu** [comment]
woah that's so responsive, thanks! @evanw
