### ISSUE TITLE
How can I inline chunk.js

### ISSUE THREAD

**Issue by Livog** [evanw/esbuild#1629]
I'm getting this file at the top of my file no matter what I do:
`import "/public/scripts/polyfills/chunk.js";`

How can I inline this instead?

The current config looks like this:
```
const polyfillConfig = {
  ...baseConfig,
  entryPoints: {
    'scripts/polyfills': path.resolve(config.paths.src, 'scripts/polyfills.js')
  },
  platform: 'node',
  splitting: true,
  format: 'esm',
  chunkNames: 'scripts/polyfills/[name]'
}
```

My core problem is that I would ONLY want to code split my async imports, as my polyfills file handles if it should load any polyfills or not.
E.g
```
const fillFetch = () => !Object.prototype.hasOwnProperty.call(window, 'fetch') && import(
    '/public/scripts/polyfills/fetch.umd.js'
  );
Promise.all([
  fillFetch()
]);
```

Any way to have code-splitting only for async imports or just to inline the chunk.js?

**Comment by evanw** [comment]
It's not totally clear what's happening in your case because there isn't enough information. However, [code splitting](https://esbuild.github.io/api/#splitting) is both code sharing and async imports for correctness reasons. You cannot separate them in the general case because of module identity. You never want to get into a situation where a given module is loaded more than once per page because then there are multiple copies of the same objects in different states which can lead to subtle bugs.

**Comment by Livog** [comment]
@evanw All right I can understand the code-sharing part. But Safari gives me a javascript error when I have `import "/public/scripts/polyfills/chunk.js";` at the beginning of the file.

In other files, it gives: `import { __commonJS } from "/app/themes/absolut/public/scripts/polyfills/chunk.js";` at the beginning which is fine in Safari.

**Comment by evanw** [comment]
What does the error say?

**Comment by Livog** [comment]
@evanw `SyntaxError: Unexpected string literal "/public/scripts/polyfills/chunk.js". import call expects exactly one argument.`

**Comment by evanw** [comment]
I believe that error happens when you try to load ESM code in a `<script>` tag and you forget to add `type="module"`. Make sure you're using `<script type="module">` to load ESM code.

**Comment by Livog** [comment]
🤦 My bad, of course that works, thank you!
