### ISSUE TITLE
Add option to use hashes of resolved modules

### ISSUE THREAD

**Issue by RDIL** [evanw/esbuild#1640]
Hi,

This bundler is really cool, but there is one thing that my project needs before it can be used.  Right now, it does something like:
```
__commonJS({
  "node_modules/example-module/index.js"(exports2) {
```
but this leaks module names in source code.  What would be a lot more helpful is if the string part either used a hash of the file's name, or some other unique identifier which is not able to be reversed.  (e.g. terser does stuff like `$f` for variable names, which is checked to ensure it doesn't collide with other variables.)  I don't really mind if it is a hash, or just an integer constant, or something like that, but this would be greatly beneficial and nice to have.

Thanks!

**Comment by evanw** [comment]
Debug (i.e. non-minified) mode has file names to help with debugging and profiling. Otherwise stack traces are very hard to use. This is similar to Webpack's development-mode behavior. See PR #1244 which introduced this behavior. Release (i.e. minified) mode does not have file names. You can enable minification to remove these file names.
