### ISSUE TITLE
Esbuild can't change relative path of require keyword at bundled package

### ISSUE THREAD

**Issue by ali-furkan** [evanw/esbuild#1644]
I want to use uws with esbuild at nodejs. You know that uws is written in c++ so nodejs uses with binding and must import it as relative. I get "cannot find" error just for this reason. Because when i build it with esbuild it adds all the imported libs into the file (because of bundle mode ) and esbuild can't change require's relative path at imported libraries.

Error
![error-ss](https://user-images.githubusercontent.com/46776661/135400636-bfe14052-f9fb-4c38-9926-2f2ec19bafee.png)

Esbuild output
![output](https://user-images.githubusercontent.com/46776661/135400828-19fde752-77b6-49de-ba4e-4997747c1ee8.png)

node_modules/uWebsocket.js/uws.js
![uws-js](https://user-images.githubusercontent.com/46776661/135400991-fd2d1109-08e7-4f26-b75e-c090e8f6528c.png)

node_modules/uWebsocket.js
![uwebsocket-folder](https://user-images.githubusercontent.com/46776661/135401041-a28d46de-f273-4b0b-bb14-a5e08229df70.png)

How can i force esbuild to change it ? Is there another way to solve the problem. If there isn't any way i'd be happy to contribute

**Comment by hyrious** [comment]
Do you really need bundling the uWebsockets.js library into your work? You can put it into your `package.json`'s `dependencies`, then externalize this library with `--external:uWebsockets.js`, others will be able to use it when they do `npm install <your package>`, which will also install uWebsockets.js.

If you do need that, the problem here is because it uses `require()` indirectly, which prevents esbuild to find the dependent files. You'd better manually copy these `.node` files to relative paths of your build target.

**Comment by ali-furkan** [comment]
Thanks for your answer. I can use external but I think if `require()` has path indirectly, it would be better for esbuild to change it.

**Comment by evanw** [comment]
Marking this package as external is the correct way to work around this. That isn't done automatically since there are some cases where this shouldn't be done, since the problematic code is either not ever evaluated at run-time or is evaluated in a try/catch with a fallback path. And full file-system bundling and emulation is [out of scope](https://esbuild.github.io/api/#non-analyzable-imports).

Closing since `--external:` is the correct solution here.
