### ISSUE TITLE
installation is broken when using `--no-optional`

### ISSUE THREAD

**Issue by lovasoa** [evanw/esbuild#1647]
Hello,
  The latest version of esbuild does not work when installing with `--no-optional`. In my project, esbuild is a subdependency, and it's not realistic to run `npm install` without  `--no-optional` on the entire project, installing gigabytes of unneeded optional dependencies just to get esbuild to work.

  Could the old post-installation download script be added back as a fallback for when esbuild is installed with `--no-optional` ? Instead of throwing with `The package "esbuild-linux-64" could not be found ...`, it could just run `npm install esbuild-linux-64`...

**Comment by calebdwilliams** [comment]
Also running into this issue.

**Comment by evanw** [comment]
The old post-install script was removed for a reason: it never fully worked. People use all kinds of custom package manager configurations and the only truly reliable way of installing a package is to let the package manager do it, which is why esbuild now uses `optionalDependencies`.

I can try adding some of the old install script behavior back as a fallback but it'll still break in various edge cases, and you could very well still experience installation problems. If you do, you'll be on your own. The only way to install esbuild that's guaranteed to work is to not specify `--no-optional` and let the package manager do it.

**Comment by lovasoa** [comment]
Well, the current solutions also breaks in all kinds of edge cases: all the cases where for one reason or another, dependencies are installed with `--no-optional` :stuck_out_tongue_closed_eyes: 

I think adding back the old post-install script would help in many of these cases. The error message when the post-install script fails could say something like `It looks like dynamically installing dependencies does not work in your situation. You can try installing esbuild without --no-optional`

**Comment by beenotung** [comment]
my workaround is to explicitly run rebuild script (`pnpm rebuild` in my case)

**Comment by garmoshka-mo** [comment]
I didn't liked using `--no-optional` from the start in my project, so I replaced it to solution below to exclude poorly managed library's dependencies: 
```
    "resolutions": {
        "package-to-replace": "npm:empty-npm-package"
    }
```
