### ISSUE TITLE
Bundler fails on string_decoder for NodeJs

### ISSUE THREAD

**Issue by re-thc** [evanw/esbuild#1680]
Hi, `string_decoder` is a builtin NodeJs module, which should be handled by the `platform=node` option. However it is also an [npm module](https://www.npmjs.com/package/string_decoder).

Issue arises in using Esbuild with e.g. Fastify that uses the npm module. Esbuild does not bundle `string_decoder` but does not treat it as a proper external either, i.e.

The generated code contains `require('string_decoder/')` and the `/` at the end refers to a module that doesn't exist and crashes.

What can be do in these cases?

Thanks.

**Comment by evanw** [comment]
Node's module resolution algorithm (which esbuild implements) says [this about core modules](https://nodejs.org/api/modules.html#modules_core_modules):

> Core modules are always preferentially loaded if their identifier is passed to `require()`. For instance, `require('http')` will always return the built in HTTP module, even if there is a file by that name.

So esbuild just adds all node core modules to its list of external modules when you pass `--platform=node`. However, due to an old feature that was added in #186, marking a module as external also marks all child paths as external too. So since `string_decoder` is marked as external, `string_decoder/` is also considered to be external.

But it turns out that's not how node actually works. Node has a hard-coded list of core module identifiers and only substitutes the core module when the path matches the identifier verbatim. This list is ​accessible via `require('module').builtinModules`
​and doesn't include `'string_decoder/'`, so that's why node crashes when running `require('string_decoder/')`.

The fix for this will need to be for esbuild to change its checking for node's core modules to behave like node, which means it will now behave differently than esbuild's external feature. Specifically, `--external:string_decoder` and `--platform=node` will now have subtly different behavior here. But changing that will arguably make esbuild more correct and will fix this issue, so I think it's a good change to make.
