### ISSUE TITLE
[Question] Is the Javascript API watch mode slower than using it from the CLI ?

### ISSUE THREAD

**Issue by alex-drocks** [evanw/esbuild#1683]
I've been using esbuild CLI with watch mode enabled and had instantaneous builds.

Further, I needed to implement a custom workflow with the Javascript API so I'm now using Esbuild through a node.js script. So with this Node script, the builds are copied almost a second later than with my previous CLI setup.

Please, is there anything you could tell me about the difference between the Esbuild CLI and Esbuild JS API performance ?

EDIT: for reference, with the JS API I'm using the Node fs module to copy files. I removed the fs usage and it went back to fullspeed. I think problem is solved. It is much slower when I use the Node.js fs module to copy some files/folder after the build is processed than the outDir generated by Esbuild.

Thanks in advance

**Comment by evanw** [comment]
Assuming you aren't doing anything extra in JS besides just calling esbuild's API, the main bottlenecks with the JS API over the CLI API are:

1. **Startup overhead**

    Running the `node` command involves some internal overhead for loading all of node's core modules as well as the overhead of parsing and JITing any JS you are running, so there is unavoidable overhead with using JS over just calling esbuild. This overhead costs around 45ms on my machine:

    ```
    $ time node -p "require('esbuild').version"
    real	0m0.058s

    $ time ./node_modules/.bin/esbuild --version
    real	0m0.012s
    ```

2. **Transfer cost**

    This is the cost of transferring data over to the esbuild executable and back. Most of the time this is negligible because the information is just a few file names and flags, but using certain features such as `stdin`, `write: false`, or `metafile: true` may need to transfer large amounts of data over the IPC pipe between node and esbuild. Doing this is typically slower than going through the file system instead. I think this is because node's pipe implementation uses a fixed small buffer size so large amounts of data involve many individual copies.

The underlying esbuild executable is the same in both cases, so there should not really be any speed difference otherwise. Of course running additional code in JS while esbuild is working can slow things down since then esbuild has to share CPU time with node, but then it's not equivalent to the CLI scenario so it makes sense why it'd be slower.
