### ISSUE TITLE
`styled-components` complains of keyframe interpolation only when using `esbuild`

### ISSUE THREAD

**Issue by Jud** [evanw/esbuild#1693]
We're migrating our webpack setup over to `esbuild` (our proof of concept cut build times in half!) and we have a little `styled-components` loader that works as expected in our current webpack setup, but when we build using `esbuild`, `styled-components` complains of keyframe interpolation and throws an exception. Here is a small repro:

`index.jsx`
```jsx
import React from "react"
import ReactDOM from 'react-dom'
import { css, keyframes } from "styled-components"

const beat = keyframes`
  50% { transform: scale(0.75); opacity: 0.2; }
  100% { transform: scale(1); opacity: 1; }
`
const BeatLoader = (props) => {
  const style = css`
    animation: ${beat} 0.7s 0.35s infinite linear;
  `

  return <span css={style} />
}

ReactDOM.render(
  <BeatLoader />,
  document.getElementById('root')
);
```
`index.html`
```html
<html>
  <head>
  </head>
  <body>
    <div id="root"></div>
    <script src="index.js"></script>
  </body>
</html>
```
styled-components error, for reference:

<img width="1037" alt="Screen Shot 2021-10-18 at 3 26 22 PM" src="https://user-images.githubusercontent.com/12308/137801911-3c9369fb-de99-4f59-bd43-00021adfa69b.png">

Edit: Using esbuild v0.13.6, also confirmed this happens using `esbuild` standalone, minimized repro.

**Comment by hyrious** [comment]
What "styled-components loader" are you using? As I can see the `css={style}` is not a built-in prop in react-dom.

The error occurs because react-dom will force converting all props into string, like doing: `el.setAttribute("css", String(style))`, and the special object `style` does not want itself to be convert to string, it then throws such error in `toString()` function.

After reading the styled components' doc, the correct usage would be:

```jsx
const beat = keyframes`
  50% { transform: scale(0.75); opacity: 0.2; }
  100% { transform: scale(1); opacity: 1; }
`

const BeatLoader = styled.div`
  animation: ${beat} 0.7s 0.35s infinite linear;
`

ReactDOM.render(
  <BeatLoader>
    Hello, world!
  </BeatLoader>,
  document.getElementById('root')
);
```

Your current syntax works in webpack probably because of some webpack loader does this work for you. If you still want to write that, take a look at the [plugins](https://esbuild.github.io/plugins) usage of esbuild.

**Comment by Jud** [comment]
Thanks @hyrious - turns out, buried in our babel config is a `styled-components` loader. The `css` prop requires that babel plugin: https://styled-components.com/docs/api#css-prop

I think we use this infrequently enough that we can convert to `styled.div`, etc. Thanks again!
