### ISSUE TITLE
Barrel export library not tree-shakeable with ESM

### ISSUE THREAD

**Issue by PuruVJ** [evanw/esbuild#1698]
Hi!

I have a simple use case: import everything from a lot of libraries and export it out in a standardized way. This is how it is 👇

<details>
    <summary>Code</summary>

```ts
/** COLLECTIONS */
export { diff as collectionDiff } from 'just-diff';
export { diffApply as collectionDiffApply } from 'just-diff-apply';
export { default as collectionCompare } from 'just-compare';
export { default as collectionClone } from 'just-clone';
export { default as collectionPluck } from 'just-pluck-it';
export { default as collectionFlush } from 'just-flush';

/** OBJECTS */
export { default as objectsExtend } from 'just-extend';
export { default as objectsMerge } from 'just-merge';
export { values as objectsValues } from 'just-values';
export { default as objectsEntries } from 'just-entries';
export { default as objectsPick } from 'just-pick';
export { omit as objectsOmit } from 'just-omit';
export { default as objectsFilterObject } from 'just-filter-object';
export { default as objectsMapObject } from 'just-map-object';
export { default as objectsMapValues } from 'just-map-values';
export { default as objectsMapKeys } from 'just-map-keys';
export { default as objectsReduceObject } from 'just-reduce-object';
export { default as objectsIsEmpty } from 'just-is-empty';
export { default as objectsIsCircular } from 'just-is-circular';
export { default as objectsIsPrimitive } from 'just-is-primitive';
export { default as objectsSafeGet } from 'just-safe-get';
export { default as objectsSafeSet } from 'just-safe-set';
export { default as objectsTypeof } from 'just-typeof';
export { default as objectsFlipObject } from 'just-flip-object';

/** ARRAYS */
export { default as arraysCartesianProduct } from 'just-cartesian-product';
export { default as arraysUnique } from 'just-unique';
export { default as arraysFlattenIt } from 'just-flatten-it';
export { default as arraysIndex } from 'just-index';
export { default as arraysInsert } from 'just-insert';
export { default as arraysIntersect } from 'just-intersect';
export { default as arraysCompact } from 'just-compact';
export { default as arraysLast } from 'just-last';
export { default as arraysTail } from 'just-tail';
export { default as arraysRandom } from 'just-random';
export { default as arraysShuffle } from 'just-shuffle';
export { default as arraysSplit } from 'just-split';
export { default as arraysSplitAt } from 'just-split-at';
export { default as arraysSortBy } from 'just-sort-by';
export { default as arraysPartition } from 'just-partition';
export { default as arraysPermutations } from 'just-permutations';
export { default as arraysRange } from 'just-range';
export { default as arraysRemove } from 'just-remove';
export { default as arraysUnion } from 'just-union';
export { default as arraysZip } from 'just-zip-it';
export { default as arraysGroupBy } from 'just-group-by';

/** STATISTICS */
export { default as statisticsMean } from 'just-mean';
export { default as statisticsMedian } from 'just-median';
export { default as statisticsMode } from 'just-mode';
export { default as statisticsPercentile } from 'just-percentile';
export { default as statisticsVariance } from 'just-variance';
export { default as statisticsStdev } from 'just-stdev';
export { default as statisticsSkewness } from 'just-skewness';

/** STRINGS */
export { default as stringsTemplate } from 'just-template';
export { default as stringsTruncate } from 'just-truncate';
export { default as stringsPrune } from 'just-prune';
export { default as stringsSquash } from 'just-squash';
export { default as stringsLeftPad } from 'just-left-pad';
export { default as stringsRightPad } from 'just-right-pad';
export { default as stringsCamelCase } from 'just-camel-case';
export { default as stringsKebabCase } from 'just-kebab-case';
export { default as stringsSnakeCase } from 'just-snake-case';
export { default as stringsPascalCase } from 'just-pascal-case';
export { default as stringsCapitalize } from 'just-capitalize';
export { default as stringsReplaceAll } from 'just-replace-all';

/** NUMBERS */
export { default as numbersClamp } from 'just-clamp';
export { default as numbersPrime } from 'just-is-prime';
export { default as numbersModulo } from 'just-modulo';

/** FUNCTIONS */
export { default as functionsCompose } from 'just-compose';
export { default as functionsCurry } from 'just-curry-it';
export { default as functionsDemethodize } from 'just-demethodize';
export { default as functionsFlip } from 'just-flip';
export { default as functionsPartial } from 'just-partial-it';
export { default as functionsDebounce } from 'just-debounce-it';
export { default as functionsMemoize } from 'just-memoize';
export { default as functionsMemoizeLast } from 'just-memoize-last';
export { default as functionsRandom } from 'just-random';
export { default as functionsThrottle } from 'just-throttle';
export { once as functionsOnce } from 'just-once';

```
</details>

Now, I compile it using esbuild to both ESM and JS, and the script is more or less this 👇

```ts
const commonConfig: BuildOptions = {
  entryPoints: [
    '../src/index.ts',
    '../src/collection.ts',
    '../src/objects.ts',
    '../src/arrays.ts',
    '../src/statistics.ts',
    '../src/strings.ts',
    '../src/numbers.ts',
    '../src/functions.ts',
  ],
  platform: 'node',
  bundle: true,
  sourcemap: true,
  treeShaking: true,
  target: 'esnext',
  outdir: '../dist/',
  tsconfig: '../tsconfig.json',
};

await Promise.all([
    build({
      ...commonConfig,
      format: 'esm',
      outExtension: {
        '.js': '.js',
      },
    }),
    build({
      ...commonConfig,
      format: 'cjs',
      outExtension: {
        '.js': '.cjs',
      },
    }),
  ]);

```

The output for the esm can be found here https://gist.github.com/PuruVJ/079b89257f4ba5b60db6cea8db42ef9d

Problem is, whenever I import individual functions from this code, and compile it(In ViteJS), the whole library is included. Even though it export everything individually. 

Rich harris's https://github.com/Rich-Harris/agadoo tool also says the file isn't tree shakeable

Please help

Thanks

**Comment by PuruVJ** [comment]
I understand the problem. For now, I've moved to rollup and it works like a charm. Hoping I can move it back to esbuild someday. Thanks for the reply

**Comment by spaceemotion** [comment]
Sorry for posting on such an old thread, but I am encountering a Tree-Shake issue with barrel files in an ESM library: `@aws-sdk/client-dynamodb`. Even though I already have set up the right order (`module, main`) in my build config, the meta file still spits out the following cause (the code base never uses this command at all):

```
Imported file src/services/dynamoDbClient.ts contains:
  import "@aws-sdk/client-dynamodb";

Imported file ../../node_modules/.pnpm/@aws-sdk+client-dynamodb@3.749.0/node_modules/@aws-sdk/client-dynamodb/dist-es/index.js contains:
  import "./commands";

Imported file ../../node_modules/.pnpm/@aws-sdk+client-dynamodb@3.749.0/node_modules/@aws-sdk/client-dynamodb/dist-es/commands/index.js contains:
  import "./DescribeKinesisStreamingDestinationCommand";

So imported file ../../node_modules/.pnpm/@aws-sdk+client-dynamodb@3.749.0/node_modules/@aws-sdk/client-dynamodb/dist-es/commands/DescribeKinesisStreamingDestinationCommand.js is included in the bundle.
```

https://github.com/aws/aws-sdk-js-v3/blob/5f1be938f93fdb47c9c2673b4f8883a61f98aca8/clients/client-dynamodb/src/commands/index.ts

This is my current config:

```js
{
  bundle: true,
  treeShaking: true,
  minify: true,
  sourcemap: true,

  legalComments: "none",

  platform: "node",
  target: "es2020",
  mainFields: ['module', 'main'],

  conditions: [
    'wintercg',
    'import',
    'module',
    'node',
  ],

  define: {
    'process.env.NODE_ENV': '"production"',
  },

  loader: {
    ".node": "file",
  },

  alias: {
    'lodash': 'lodash-es',
  },
}
```

The dynamoDB service file in question looks like this:
```ts
import type { BatchGetItemCommandOutput, BatchGetItemInput, BatchWriteItemCommandOutput, BatchWriteItemInput, DynamoDBClient, QueryCommandInput, UpdateItemInput, WriteRequest } from "@aws-sdk/client-dynamodb";
import { BatchGetItemCommand, BatchWriteItemCommand, paginateQuery as paginateQueryBase, UpdateItemCommand } from "@aws-sdk/client-dynamodb";
// @ts-expect-error Types are missing for the specific import
import { DynamoDBClient as RawDynamoDBClient } from "@aws-sdk/client-dynamodb/dist-es/DynamoDBClient.js";


export const client: DynamoDBClient = new RawDynamoDBClient({
  region: process.env.APP_AWS_REGION,
});
```

For some reason, `esbuild` still imports the whole thing: 

![Image](https://github.com/user-attachments/assets/69f548ca-7651-4c36-9620-749b23d3a033)

Thanks in advance!

**Comment by evanw** [comment]
This is documented: https://esbuild.github.io/api/#tree-shaking-and-side-effects

An expression such as `new RawDynamoDBClient({ region: process.env.APP_AWS_REGION })` is not generally safe to remove as it may have side effects. Specifically `new RawDynamoDBClient` could potentially modify global state or `process.env.APP_AWS_REGION` could potentially throw an exception if `process.env` is undefined. The analysis to automatically figure all of that out for you is out of scope for esbuild. If you want to enable tree shaking for expressions like this, you should use an annotation to tell esbuild that it's safe to assume there are no side effects. The general way to annotate any JS expression as side-effect free is `/* @__PURE__ */ (() => expression)()`. This is a common convention among bundlers and isn't esbuild-specific.

Also for the same reason, giant libraries are not automatically tree-shakable even if they are ESM instead of CommonJS. Generally the only things that can be automatically tree-shaken are function declarations, constant variable initializations, and simple class declarations. Any more complex code (such as dynamically adding properties to an object in a loop) is not automatically analyzed as side-effect free. The library author would have to explicitly annotate the code to allow it to be tree-shaken by bundlers, which can be done as described above or using the Webpack `sideEffects` annotation.

**Comment by spaceemotion** [comment]
@evanw thanks for the reply!

I think I should have been a bit clearer in my comment, cause I think there was a misunderstanding here: The service file I was referring to above is our code, not library code. I used a work-around that worked for S3 when i import the "raw" client, instead of the aggregated version.

I do know of the side effect comments (pure, etc.), but your response made me think about the potential cause for the issue I am seeing that the AWS SDK has:

1. The SDK libraries always use the same layout, with commands, an aggregated client (so you can do `client.putItem()`), as well as the raw client.
2. The aggregated client is being exposed to the main index file via a `export * from './S3Client'` call.
3. Inside the `S3Client` file, there's a single method that adds all the available commands to the client: https://www.runpkg.com/?@aws-sdk/client-s3@3.749.0/dist-es/S3.js#203

Is my logic correct here? With that one single line, any kind of optimization across the whole package is no longer possible because the index file exposes everything?

Cheers!

**Comment by evanw** [comment]
Yes, that's correct. Complex code execution at import-time that can't be determined to be side-effect free is conservatively considered to be a side effect. That's the reason for the second paragraph in my reply. The `sideEffects` annotation only helps eliminate files at the file boundary granularity, which might not help here. The easiest solution here might be to avoid barrel imports and only import from the file you want to include. There is probably a way for the author of the SDK to get this to work if they wanted to with some amount of annotating and/or moving code between files, but they'd have to be the ones to do that. These kind of tree shaking optimizations are generally the responsibility of the library authors.

**Comment by spaceemotion** [comment]
Okay, thanks! I already tried importing the files directly, but TypeScript is nagging at me for not knowing what they are - which kind of sucks. I guess I can try to do a re-export in our DynamoDB and S3 services.

I also tried adding the following plugins, but it still imports all of the commands:

```ts
build.onLoad({ filter: /@aws-sdk\/client-s3\/dist-es\/index\.js$/ }, ({ path }) => {
  return {
    contents: readFileSync(path, 'utf-8').replace('export * from "./S3";', ''),
  };
});

build.onLoad({ filter: /@aws-sdk\/client-dynamodb\/dist-es\/index\.js$/ }, ({ path }) => {
  return {
    contents: readFileSync(path, 'utf-8').replace('export * from "./DynamoDB";', ''),
  };
});

build.onResolve({ filter: /@aws-sdk\/client-(dynamodb|s3)\/dist-es\// }, () => {
  return {
    sideEffects: false,
  };
});

build.onLoad({ filter: /@aws-sdk\/client-(dynamodb|s3)\/dist-es\/commands\/\w+Command.js$/ }, ({ path }) => {
  const contents = readFileSync(path, 'utf-8')
    .replace(/export class (\w+) extends/, 'export const $1 = /*@__PURE__*/ ')
    .replace(/\s*\{[^}]+\}$/, ';')
    .replace(`.build() {\n}`, '.build();')
    ;

  return {
    contents,
  };
});
```

**Comment by spaceemotion** [comment]
@evanw So AWS got back to the linked issue and there seems to be something about async imports that messes up the tree-shaking:

1. When I import the DynamoDB / S3 client stuff like normal, everything gets tree shaken properly. Even when the files call methods inside.
2. However, as soon as I async import a file - and that file itself only pulls in one specific method from those clients - the whole tree shaking gets broken, as it pulls everything in:

```ts
// test.ts
export const migrations = {
  'add-users': import('./migrations/20250101-add-users.ts'),
};
```

```ts
// 20250101-add-users.ts
import { QueryCommand } from '@aws-sdk/client-dynamodb';

export default function migrate() {
  new QueryCommand();
}
```

Is this expected behavior? Thanks in advance!
