### ISSUE TITLE
Trying to use "sourcemap: 'linked'" in build api results in error

### ISSUE THREAD

**Issue by dave-irvine** [evanw/esbuild#1722]
Error message is:

> Error: Invalid sourcemap: "linked" (valid: inline, external, both)

Example build script:

```js
esbuild
  .build({
    entryPoints: ['./src/index.js'],
    bundle: true,
    format: 'esm',
    sourcemap: 'linked',
    loader: {
      '.js': 'jsx',
    },
  })
  .catch((err) => {
    console.error(err);
    process.exit(1)
  });
```

Esbuild version:

```json
"esbuild": "^0.13.10",
```

I can see in the docs that:

>the transform API does not support the linked mode

but I don't *think* I'm using the transform API, so unless I'm confused then something is wrong :/

**Comment by rossjrw** [comment]
> Use `sourcemap: true` to get linked, as described in the documentation: https://esbuild.github.io/api/#sourcemap.

This isn't mentioned explicitly in the documentation, only implied by the `--sourcemap` in the code snippet rather than `--sourcemap=linked`. The title of that section is "`linked`", which implies that "linked" can be passed a string value just like every other option in that list. It would be clearer to write "linked" as plain text and also note its API usage explicitly.
