### ISSUE TITLE
async transform breaks way to get AsyncFunction constructor

### ISSUE THREAD

**Issue by jayjun** [evanw/esbuild#1743]
As documented on [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncFunction), the only way to get an `AsyncFunction` constructor is through the prototype of one.

```javascript
const AsyncFunction = Object.getPrototypeOf(async function(){}).constructor;
```

However because esbuild transforms `async function(){}` into a regular function, transpiled code returns a regular function constructor. This breaks libraries that expect the constructor to return a `Promise`.

For example, [Alpine.js calls `then` and `catch`](https://github.com/alpinejs/alpine/blob/9146daa567aece18e87f8a259445d54ce8e7341e/packages/alpinejs/src/evaluator.js#L102-L104) on the result.

Unfortunately that hideous way is the only way to dynamically create `async` functions. Wondering if esbuild can special case this by never transforming `async` functions inside `Object.getPrototypeOf(...)`.

### Steps to reproduce
1. Save this as `in.js`.
```javascript
const AsyncFunction = Object.getPrototypeOf(async function(){}).constructor;

let echo = new AsyncFunction(["message"], "return message");

console.log(echo);

echo("foo").then((value) => console.log(value));
```

2. Run these commands.
```
$ node in.js
[AsyncFunction: anonymous]
foo
$ ./esbuild --bundle in.js --outfile=out.js --target=es2015

  out.js  879b 

⚡ Done in 3ms
$ node out.js
[Function: anonymous]
out.js:30
  echo("foo").then((value) => console.log(value));
              ^

TypeError: echo(...).then is not a function
```

**Comment by hyrious** [comment]
`tsc` and `babel` can not handle this too.

**Comment by evanw** [comment]
The point of the async transform is to make the code run in an environment where `AsyncFunction` is not available. It doesn't make sense to transform async away and then expect `AsyncFunction` to be present. If `AsyncFunction` was present, you could just implement the async transform using `AsyncFunction` instead, which would be trivial (just use `new AsyncFunction`).

And `AsyncFunction` is not easy to polyfill because it lets you eval code with `await` in it, so polyfilling it would mean including a full JavaScript parser, transformer, and code generator with your bundled code at run-time. And if that's implemented using esbuild's JavaScript transformer, it would mean bundling in around 10mb of WebAssembly code (since esbuild's WASM code is not size-optimized at all), which is crazy. So there's no way esbuild is going to support this.

If your code relies on `AsyncFunction` you should use a `target` setting where it exists such as `es2017` and then only run your code in environments that support `AsyncFunction`. Closing this issue as out of scope.

**Comment by jayjun** [comment]
Thanks @evanw, great explanation. Passing `--target=es2017` to fix my project.
