### ISSUE TITLE
[Feature] Identifier blocklist

### ISSUE THREAD

**Issue by nfam** [evanw/esbuild#1748]
Hey,

Bundle, and minify will rename (or shorten), function, class, and variable names. Can we have blocklist for those new names?

My internal web app dynamically imports libraries (usually big) on demand, so our CI bundles, and minifies those separately (multiple entries). Unfortunately, LeafletJS for OpenStreetMap has a global `L` variable bound to `window`, thus, after dynamically imported at runtime, LeafletJS invalidates whatever function `L` in the main bundle, to which renamed (or shortened) by esbuild.

LeafletJS did try to move on to ES6 years ago, but they must hotfix and keep `window.L` to prevent a lot of plugins out there from being broken. For my case, I just wrote a small script modifying `node_modules/leaflet`, to remove `window.L = ...`  for my CI build because my project does not use any LeafletJS plugin. But popular libraries (with popular plugins) have their hands tied.

If esbuild has an identifier blocklist, the (renamed, shortened) function `L` will never appear in the main or other bundles. We can use legacy libraries without hacky scripts.

**Comment by evanw** [comment]
I don't understand the problem from your description. It should already be working that way. All global identifiers in the code will already be added to esbuild's "identifier blocklist" automatically before minification, so the minifier should already never generate a variable named `L` if the code accesses a global named `L`. And if the global named `L` is never accessed, then the name `L` is automatically free to be used without collisions.

This can be demonstrated with a quick example. The minifier uses a character frequency analysis to determine which characters to use for better gzip compression, so you can get esbuild to generate a variable with the name `L` pretty easily just by repeating it enough times somewhere in the code. This is shown for all three supported output formats below:

```
$ echo 'var x = 123; console.log("LLLL", x)' | esbuild --minify --bundle --format=esm
var L=123;console.log("LLLL",L);

$ echo 'var x = 123; console.log("LLLL", x)' | esbuild --minify --bundle --format=cjs
var L=123;console.log("LLLL",L);

$ echo 'var x = 123; console.log("LLLL", x)' | esbuild --minify --bundle --format=iife
(()=>{var L=123;console.log("LLLL",L);})();
```

The above output is not problematic because the original code never accesses the global variable named `L`, so the identifier `L` is free for use. And it's not possible for the top-level variable named `L` to collide with any global variable named `L` under the assumptions that esbuild makes during bundling, which are a) that all code in the bundle is passed to esbuild (e.g. no code is appended or prepended to the bundle after esbuild runs) and b) that the resulting code is being run as the provided format (e.g. with `--format=esm` you must use `<script type="module">` which runs the code in a module scope). If either of these assumptions are not correct for your use case then you are not using esbuild the way it's intended to be used, and things may indeed break, but that's not a problem with esbuild.

And here's an example where the original code _does_ reference the variable `L`, shown again in all three supported output formats:

```
$ echo 'var x = 123; console.log("LLLL", x, L)' | esbuild --minify --bundle --format=esm
var o=123;console.log("LLLL",o,L);

$ echo 'var x = 123; console.log("LLLL", x, L)' | esbuild --minify --bundle --format=cjs
var o=123;console.log("LLLL",o,L);

$ echo 'var x = 123; console.log("LLLL", x, L)' | esbuild --minify --bundle --format=iife
(()=>{var o=123;console.log("LLLL",o,L);})();
```

As you can see, esbuild now does not use the variable name `L` since that would collide with the access of the global named `L`. So what you are describing should happen automatically. Please let me know if I'm misunderstanding something.

**Comment by nfam** [comment]
Thank you for your reply,

> if the global named L is never accessed, then the name L is automatically free to be used without collisions.

Yes, my code never access `L`, and for years `Leaflet` has not contained any global `L` except for one line setting
```js
window.L = exports;
```
for backward compatibility. I guess esbuild does not see `window.L` is an access to a global `L`.

**Comment by evanw** [comment]
I still don't understand. You're saying code is never reading from or writing to the global `L` (only the property `window.L`). In that case, it should be fine for esbuild to create a local variable named `L` since it will have no observable difference than using any other name. So there's no problem here?

**Comment by hyrious** [comment]
I think you didn't get what's the problem with those leaflet plugins. It is just like jQuery. Some side effects (like defining `window.L`, right in the leaflet source code) must be run before some other code (the leaflet plugins). You have to make sure the code run in this order, and codes are written in valid commonjs/es modules (i.e. some form of UMD/AMD won't work well).

**Comment by nfam** [comment]
This is my esbuild option
```go
opt := api.BuildOptions{
	EntryPoints: strings.Split(entry, ","),
	Outdir:      out,
	Bundle:      true,
	Format:      api.FormatESModule,
	Write:       true,
	LogLevel:    api.LogLevelInfo,
}
if min {
	opt.MinifyIdentifiers = true
	opt.MinifySyntax = true
	opt.MinifyWhitespace = true
}
```

This is the orginal function `dataStatus` in `status.ts` file.
```ts
export type StatusOpt = 'update' | 'reviewable' | 'auditable';
export const statusOptNames: StatusOpt[] = ['update', 'reviewable', 'auditable'];
export const statusOptValues: { [key in StatusOpt]: string } = {
  update: 'icon:square_pencil',
  reviewable: 'icon:checkmark',
  auditable: 'icon:checkmark_seal',
};

export function dataStatus<
  T extends {
    completed?: boolean;
    reviewed?: boolean;
    suspended?: boolean;
    canceled?: boolean;
    audited?: boolean;
  },
>(o: T) {
  return o.suspended || o.canceled
    ? 'remove'
    : !o.completed
    ? 'update'
    : !o.reviewed
    ? 'review'
    : undefined;
}
```

And this is the first few line of generated `main` bundle without minify, so we can see `dataStatus` function in the bundle.

![Screen Shot 2021-11-07 at 18 19 03](https://user-images.githubusercontent.com/35899503/140642812-c8e0970d-2cea-43db-aecb-87153c16c3a6.png)

All variables, functions in the bundle are at the *global* level. If the bundle is minified, a certain function name will be shortened to `L`. Once the bundle `leaflet.js` is dynamically loaded, `window.L = exports` will invalidate that function. Calling the original function `L` will throw error `L is not a function`

**Comment by hyrious** [comment]
That's impossible in **es modules** context because they are isolated. I doubt you just concat some code with the bundled one.

**Comment by nfam** [comment]
> Or you didn't use the right way to execute it (you should use <script type="module"> and import()).

My bad, I put the `main` bundle in `<script type="module">`, and it works.

Thank @hyrious for emphasizing it. And sorry @evanw for wasting your time.

**Comment by evanw** [comment]
This seems to come up a lot (not running ESM correctly). I wonder if I should just always generate `export {};` at the end of ESM files to make running ESM incorrectly an instant syntax error instead of having it pollute the global scope.
