### ISSUE TITLE
tree-shaking sometimes prevents syntax minification

### ISSUE THREAD

**Issue by privatenumber** [evanw/esbuild#1749]
### Description
When enabling treeshaking, some parts of the code syntax that would previously be minified would no longer be minified.

### Reproduction
Using Vue v2.6.12

#### Minify identifiers & syntax

```sh
$ npx esbuild --minify-identifiers --minify-syntax "./node_modules/vue/dist/vue.runtime.common.dev.js" | pbcopy
```

#### Minify identifiers & syntax w/ tree-shaking enabled
```
$ npx esbuild --minify-identifiers --minify-syntax --tree-shaking=true "./node_modules/vue/dist/vue.runtime.common.dev.js" | pbcopy
```

### Output
Some parts that can be minified are no longer minified:
```js
Vue.config.mustUseProp = mustUseProp;
Vue.config.isReservedTag = isReservedTag;
Vue.config.isReservedAttr = isReservedAttr;
Vue.config.getTagNamespace = getTagNamespace;
Vue.config.isUnknownElement = isUnknownElement;
extend(Vue.options.directives, platformDirectives);
extend(Vue.options.components, platformComponents);
Vue.prototype.__patch__ = inBrowser ? patch : noop;
```

Expected to be:
```js
Vue.config.mustUseProp = mustUseProp, Vue.config.isReservedTag = isReservedTag, Vue.config.isReservedAttr = isReservedAttr, Vue.config.getTagNamespace = getTagNamespace, Vue.config.isUnknownElement = isUnknownElement, extend(Vue.options.directives, platformDirectives), extend(Vue.options.components, platformComponents), Vue.prototype.__patch__ = inBrowser ? patch : noop
```

Full diff:
https://www.diffchecker.com/jNL2B7XX

### Other info
I realize this isn't really a big deal, especially because there's probably no end-result difference between `,` vs `;`. But figured I report it incase it's an unexpected behavior.

**Comment by evanw** [comment]
I don't consider this to be a bug. Like you said there's no difference between `,` and `;` in terms of the resulting file size. This happens because with tree-shaking enabled, esbuild keeps statements separate so they can be dropped if they are side-effect free. Collapsing multiple consecutive expression statements into a single expression statement is useful when it allows for compaction inside nested statements. Here are some examples:

```js
for(;x;){y=1;z=2} // before
for(;x;)y=1,z=2;  // after

if(x){y=1;z=2} // before
x&&(y=1,z=2);  // after
```

Merging multiple expression statements lets you potentially drop the outer block, resulting in one less character. But there is no outer block for top-level statements so this doesn't seem as useful. And keeping top-level statements separate during tree-shaking is a big win for esbuild's performance since it simplifies tree-shaking a lot, so it's an intentional part of the implementation.

**Comment by privatenumber** [comment]
Gotcha! Thank you always for the kind and careful explanation.

No issue if it's expected behavior.
