### ISSUE TITLE
change the registry.npmjs.org in install.js

### ISSUE THREAD

**Issue by sinbargit** [evanw/esbuild#1762]
Hi since there is some network problem to visit registry.npmjs.org. any way can change it?

**Comment by evanw** [comment]
Since [version 0.13.0](https://github.com/evanw/esbuild/releases/tag/v0.13.0), the installer doesn't download anything by itself anymore. Instead, the package uses npm's `optionalDependencies` feature to install the correct sub-package. That way sub-package installation is no longer done by esbuild. Make sure you are using the latest version of esbuild to get this behavior.

The only case when this doesn't work is if you explicitly pass `--no-optional` to `npm install`. If you do this, then esbuild's installer may not work. Since [version 0.13.4](https://github.com/evanw/esbuild/releases/tag/v0.13.4) is a best-effort fallback that does try to download the sub-package in this case (first with `npm install`, then with a manual download from registry.npmjs.org if that fails) but it doesn't always work in all situations and I do not recommended using it. I recommend removing the `--no-optional` flag instead.
