### ISSUE TITLE
generate stable metafile 

### ISSUE THREAD

**Issue by hardfist** [evanw/esbuild#1766]
It seems that esbuild's metafile is not stable, It may change even the project is the same, it seems caused by plugin hooks run in parallel, is there an way to generate stable metafile

**Comment by hyrious** [comment]
You shouldn't depend on plugins run in some order, as they can be async. Instead make sure plugins always returning consist result for same input.

**Comment by hardfist** [comment]
I does not depend on plugin order, I depend on metafile imports order is stable

**Comment by hyrious** [comment]
Oh, maybe you can just write a plugin to record .css imports in `onLoad` callback, like [mine](https://github.com/hyrious/esbuild-plugin-style).

**Comment by hardfist** [comment]
I already did this and I need to manual extract css myself(other than rely on esbuild's extract logic), and I find the generated css order is not stable, it may be caused by unstable metafile(since i concat according to metafile's imports topological order

**Comment by hardfist** [comment]
related to https://github.com/evanw/esbuild/issues/1388

**Comment by evanw** [comment]
Can you provide a code example demonstrating the problem?

**Comment by hardfist** [comment]
It's a internal application, I will try to create an demo

**Comment by hardfist** [comment]
It seems my fault that accidentally change the import order, by the way is metafile guarantee to be stable between different builds in same project?

**Comment by evanw** [comment]
Yes, if everything about the build's inputs is the same (esbuild version, file contents, relative input paths, plugin return values) then the build output should also be the same every time. If build output differed, it would be a non-determinism bug in esbuild. The metafile format is not guaranteed to be stable across esbuild versions, since new versions may add new features and/or potentially change how file linking works (not that this happens often, and file linking changes would likely be marked as a breaking change). But given the same esbuild version everything should be completely deterministic.
