### ISSUE TITLE
[Question] Incremental Rebuild performance expectations

### ISSUE THREAD

**Issue by chrismcv** [evanw/esbuild#1770]
Hi, I've been implementing esbuild on a large build, and seeing impressive gains in the build times over webpack. So sincere thanks for all the work on this project to date.

My build is taking around 8-10s, and the incremental build is sitting at around 6s. The docs don't specify what the expected delta between incremental and full should be, and possibly my webpack flavoured expectations were that incremental would be more like sub second. (The 6s is after the watcher "polling" period, which is varying between 0.5-3s on my machine).

So my questions are:
1) Is what I'm seeing "normal" or does this point at something with my configuration that could be improved?
2) If not normal, is there a way of testing my plugins (alias/style) to measure their impact?

Thanks!

**Comment by evanw** [comment]
Rebuilds currently still do a full build, they just reuse ASTs for files that didn't change. Everything still has to be re-resolved and re-linked. So the speedup with incremental builds currently isn't very impressive.

If you are using plugins, it's possible that plugins are taking most of the time (both for the initial build and incremental builds). In that case it would be worth optimizing your plugins. The time taken to run a given plugin isn't necessarily straightforward because plugins are async so many plugins may be running at the same time. But you can still try.

A quick way to do this is to add some logs within the plugin at the start and end of the plugin callbacks (usually `onResolve` and/or `onLoad`). Something like this:

```js
build.onLoad(..., args => {
  const start = Date.now()
  ...
  const end = Date.now()
  console.log(`plugin took ${end - start}ms for ${args.path}`)
  return ...
})
```

I usually just temporarily edit the source code on the file system (i.e. inside `node_modules`) for something like this. Something like this should give you a general idea of which plugins are more expensive.

The main way to speed up plugins for incremental builds is to add caching. Unfortunately caching is inherently complicated, especially if the plugin isn't a pure function of the input file. There are some notes on how to implement caching here: https://esbuild.github.io/plugins/#caching-your-plugin.

**Comment by evanw** [comment]
Closing this issue because this question was answered.
