### ISSUE TITLE
[Feature request/question] Any way to time/benchmark plugins/different parts of the build process?

### ISSUE THREAD

**Issue by jjant** [evanw/esbuild#1778]
Yeah so basically the title, our builds uses a bunch of plugins, and build are relatively slow, I would like to be able to get timings for whatever different parts of the build process there are, and how much time plugins are adding.

Is this currently possible somehow?

**Comment by chrismcv** [comment]
see the answer to https://github.com/evanw/esbuild/issues/1770

**Comment by evanw** [comment]
If you don't want to modify the plugins themselves, you can wrap them instead. Here's an example wrapper:

<details>

<summary>Click to expand the code for the <code>logTimePlugin</code> wrapper plugin</summary><br>

```js
const logTimePlugin = plugin => ({
  name: plugin.name,
  async setup(build) {
    const makeTimer = name => ({
      name,
      total: 0,
      hit: false,
      addSince(start) { this.hit = true; this.total += Date.now() - start },
      toString() { return `${this.name}: ${this.total}ms` },
    })

    const start = makeTimer('start')
    const onStart = makeTimer('onStart')
    const onEnd = makeTimer('onEnd')
    const onResolve = makeTimer('onResolve')
    const onLoad = makeTimer('onLoad')
    const all = [start, onStart, onEnd, onResolve, onLoad]

    const buildShim = {
      ...build,

      async onStart(callback) {
        build.onStart(async () => {
          const start = Date.now()
          try { return await callback() }
          finally { onStart.addSince(start) }
        })
      },

      async onEnd(callback) {
        build.onEnd(async (...args) => {
          const start = Date.now()
          try { return await callback(...args) }
          finally { onEnd.addSince(start) }
        })
      },

      async onResolve(options, callback) {
        build.onResolve(options, async (...args) => {
          const start = Date.now()
          try { return await callback(...args) }
          finally { onResolve.addSince(start) }
        })
      },

      async onLoad(options, callback) {
        build.onLoad(options, async (...args) => {
          const start = Date.now()
          try { return await callback(...args) }
          finally { onLoad.addSince(start) }
        })
      },
    }

    const setupStart = Date.now()
    await plugin.setup(buildShim)
    start.addSince(setupStart)

    build.onEnd(() => {
      const parts = [
        `\x1b[1;33m[plugin: ${plugin.name}]\x1b[0m`,
        `  total: ${all.reduce((a, b) => a + b.total, 0)}ms`,
      ]
      const hit = all.filter(x => x.hit)
      for (let i = 0; i < hit.length; i++)
        parts.push(`   ${i + 1 < hit.length ? `├` : `└`} ${hit[i]}`)
      parts.push(``)
      console.log(parts.join('\n'))
    })
  },
})
```

</details>

Use it like this:

```js
esbuild.build({
  plugins: [
    // ... your plugins here ...
  ].map(logTimePlugin),
})
```

The major caveat to this approach is that the time elapsed from when a plugin begins to when a plugin ends (which is what this code measures) is not necessarily any indication of how much work that plugin is doing. This is because many plugins may be evaluated simultaneously and their evaluations may all overlap, so some may be blocked by others due to the event loop and their evaluations may be artificially elongated. To really understand the performance characteristics and what is keeping the CPU busy (if your plugin is CPU-bound instead of, say, network-bound), you'd need to actually use a profiler instead of doing something simple like this.

**Comment by evanw** [comment]
Closing since I believe the above answer is sufficient. Feel free to continue to add additional comments here if you’d like.

**Comment by jjant** [comment]
Thanks @chrismcv and @evanw that helps quite a bit!
