### ISSUE TITLE
"Ignoring this import because X was marked as having no side effects" on type imports

### ISSUE THREAD

**Issue by fregante** [evanw/esbuild#1785]
https://github.com/g-plane/typed-query-selector is a type-only package, it's normal for it to be ignored (related: https://github.com/evanw/esbuild/issues/1525), but it should not cause a warning.

## Repro

```sh
npm i -D typed-query-selector
```

```ts
// main.ts
import 'typed-query-selector'
document.querySelector('div#app')
```

```
esbuild main.ts --bundle
```

## Expected output

No error

```js
document.querySelector('div#app')
```

## Current output

```
 > file.ts:1:7: warning: Ignoring this import because "node_modules/typed-query-selector/shim.d.ts" was marked as having no side effects
     1 │ import 'typed-query-selector';
       ╵        ~~~~~~~~~~~~~~~~~~~~~~
   node_modules/typed-query-selector/package.json:13:2: note: "sideEffects" is false in the enclosing "package.json" file
    13 │   "sideEffects": false,
       ╵   ~~~~~~~~~~~~~
```

**Comment by hyrious** [comment]
I believe this warning is for preventing people from incorrectly marking a package as no side-effect when it actually has. Normally the `import "xxx"` statement is used for side effects, like importing from core-js. Esbuild can not ignore this statement like other `import type`s because when you write `import "xxx"`, you expect something happen globally (but this thing happens in types world, so esbuild don't know).

**Comment by fregante** [comment]
Thanks @evanw!
