### ISSUE TITLE
[Plugin] onEnd callbacks modify the build result

### ISSUE THREAD

**Issue by yanm1ng** [evanw/esbuild#1792]
I used end callback to modify the build result，it works，but I can't return the new result。

```ts
function myPlugin(): Plugin {
  return {
    name: 'my-plugin',
    setup(build: PluginBuild) {
      const options = build.initialOptions;
      options.write = false;

      build.onEnd(async ({ errors, outputFiles }) => {
        if (!errors.length && outputFiles?.length) {
          await Promise.all(outputFiles.map(async file => {
                // some logic to modify output contents...
          }));
        } else {
          console.error(errors);
        }
      });
    },
  };
}

const result = await esbuild({
      entryPoints: [ path.join(__dirname, './entry.js')],
      outdir: path.join(__dirname, 'dist'),
      plugins: [ myPlugin() ]
});

for (let out of result.outputFiles) {
     // still original build result
     console.log(out.path, out.text);
}
```

also onEnd function type only support `void` or `Promise<void>`

![image](https://user-images.githubusercontent.com/16443628/142827790-83315f69-9f62-42cf-874e-594b6188db6c.png)

**Comment by evanw** [comment]
Well `text` is a lazily-evaluated getter instead of a normal property so you have to use `Object.defineProperty(file, 'text', { value: 'something' })` instead of `file.text = 'something'` but changing it should work fine (I just tried it myself). You can also just mutate the `outputFiles` property on the `result` argument directly instead if you want. The `onEnd` callback doesn't have a return value because the `result` object is provided as an argument and you can fully modify any aspect of it before you return it.

**Comment by yanm1ng** [comment]
I also found `text` is a getter before you reply. I will try to modify the `result` object.
Thank you for your reply anyway ❤️

**Comment by eric-hemasystems** [comment]
FYI. For anybody that comes across this in the future.

I wasn't able to modify my build result by updating the `text` property (even using `Object.defineProperty(file, 'text', { value: 'something' })`). But I could do so by modifying the `contents` property (this also implicitly modifies `text` since it is a function that reads from `contents`). Example:

```js
build.onEnd((result) => {
  const js = result.outputFiles.find(f => f.path.match(/\.js$/))
  const modified = doSomething(js.text)
  js.contents = Buffer.from(modified)
})
```

To see a fuller example (where I use it to instrument for code coverage) see https://github.com/marvinhagemeister/karma-esbuild/issues/33#issuecomment-1093042415
