### ISSUE TITLE
Please support  loong64 ISA

### ISSUE THREAD

**Issue by cheungxi** [evanw/esbuild#1804]
I can `go build`  esbuild on loong64 computer successfully.
but esbuild need specify go/sys  https://github.com/loongson/sys

Considering the user experience, I hope that the main line of esbuild can support loong64 ISA.

Thanks

If you need any support for the new architecture, I am happy to provide support.

**Comment by evanw** [comment]
It looks like work is in progress to add this to Go itself, in which case integration with esbuild should be trivial: https://github.com/golang/go/issues/46229.

**Comment by evanw** [comment]
Marking as `unactionable` until https://github.com/golang/go/issues/46229 is fixed and shipped.

**Comment by evanw** [comment]
It looks like this might be shipped in Go 1.19 in August 2022: https://tip.golang.org/doc/go1.19.

**Comment by shipujin** [comment]
Hi, find npmjs existing "[npmjs/esbuild-linux-loong64 package](https://www.npmjs.com/package/esbuild-linux-loong64) "
After reading, I found that the author was "Cheungxi", the same name as you,
Because "esbuild-Loong64" exists on npmjs, Evanw needs to rethink the package name of "esbuild-linux-loong64", [Support Loongarch LE architecture](https://github.com/evanw/esbuild/pull/2373)
Could you help me with this? Thank you~

**Comment by cheungxi** [comment]
ok, i will delete this package.

**Comment by evanw** [comment]
This is unblocked now that [Go 1.19 has been released](https://go.dev/doc/go1.19#loong64).

**Comment by evanw** [comment]
Fixed by #2373
