### ISSUE TITLE
node child_process fork

### ISSUE THREAD

**Issue by rschoenbichler** [evanw/esbuild#1818]
Considering the following code,

```
// src/foo.ts
import { fork } from "child_process";
fork("./bar");
```

```
// src/bar.ts
console.log("bar");
```

when bundling via `esbuild src/foo.ts --bundle --platform=node --target=node16 --outfile=dist/app.js`, the expected result would be that running `node dist/app.js` results in a console log of "bar";

Instead, the following error is thrown when executing:

```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/path/to/base/bar'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

```

**Comment by evanw** [comment]
Sorry, I don't think your description has enough information to understand what the problem is. Are you saying you're calling esbuild's JS API and then your code has trouble forking? Are you calling esbuild's JS API from a fork? Are you trying to bundle code that forks? It would be most useful to provide a code sample that reproduces your problem.

**Comment by rschoenbichler** [comment]
I've updated the description accordingly, hope the issues is clear now.

**Comment by hyrious** [comment]
esbuild doesn't know which string in your code is a path to another file. So your foo.ts just look for the `./bar` file relative to itself. That's why it can not find it:

```
src/
	foo.ts
	bar.ts  <- actually want this
dist/
	app.js  <- I want to run the file "./bar"
	<- there's no "./bar" relative to app.js
```

You have to also build src/bar.ts to dist/bar.js to make it work. Simply: `esbuild src/bar.ts --bundle --platform=node --outfile=dist/bar.js`.

However, if both foo.ts and bar.ts import a shared module and are bundled separately, the module won't be shared (i.e. only one copy of it) in the output files. [See it live.](https://hyrious.me/esbuild-repl/?version=0.14.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJmb28udHMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwYSUyMGZyb20lMjAlNUMlMjIuJTJGYnV6ei50cyU1QyUyMiU1Q25hLnB1c2goMSklM0IlNUNuY29uc29sZS5sb2coJTVDJTIyZm9vJTVDJTIyKSUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmJhci50cyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjBhJTIwZnJvbSUyMCU1QyUyMi4lMkZidXp6LnRzJTVDJTIyJTVDbmEucHVzaCgyKSUzQiU1Q25jb25zb2xlLmxvZyglNUMlMjJiYXIlNUMlMjIpJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYnV6ei50cyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBkZWZhdWx0JTIwJTVCJTVEJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmJ1bmRsZSUyMiUzQXRydWUlMkMlMjJmb3JtYXQlMjIlM0ElMjJlc20lMjIlMkMlMjJzcGxpdHRpbmclMjIlM0FmYWxzZSUyQyUyMnBsYXRmb3JtJTIyJTNBJTIybm9kZSUyMiUyQyUyMnRhcmdldCUyMiUzQSU1QiUyMm5vZGUxNiUyMiU1RCU3RCU3RA%3D%3D)

The correct way to build multiple targets with shared modules, should be using esm and enable [code splitting](https://esbuild.github.io/api/#splitting), however that only works with esm format. [See it live.](https://hyrious.me/esbuild-repl/?version=0.14.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJmb28udHMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwYSUyMGZyb20lMjAlNUMlMjIuJTJGYnV6ei50cyU1QyUyMiU1Q25hLnB1c2goMSklM0IlNUNuY29uc29sZS5sb2coJTVDJTIyZm9vJTVDJTIyKSUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmJhci50cyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjBhJTIwZnJvbSUyMCU1QyUyMi4lMkZidXp6LnRzJTVDJTIyJTVDbmEucHVzaCgyKSUzQiU1Q25jb25zb2xlLmxvZyglNUMlMjJiYXIlNUMlMjIpJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYnV6ei50cyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBkZWZhdWx0JTIwJTVCJTVEJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmJ1bmRsZSUyMiUzQXRydWUlMkMlMjJmb3JtYXQlMjIlM0ElMjJlc20lMjIlMkMlMjJzcGxpdHRpbmclMjIlM0F0cnVlJTJDJTIycGxhdGZvcm0lMjIlM0ElMjJub2RlJTIyJTJDJTIydGFyZ2V0JTIyJTNBJTVCJTIybm9kZTE2JTIyJTVEJTdEJTdE)

**Comment by rschoenbichler** [comment]
Thank you for the clarification.
We don't mutate module scopes, so that is not an issue.

In fact, I tried including the file in the build process before but I didn't take into account that the import path is relative to the execution scope.
I was able to get this to run by executing `cd dist && node app.js`
Thank you for the pointers.
