### ISSUE TITLE
feature request: arrow function transformation

### ISSUE THREAD

**Issue by MathGeniusJodie** [evanw/esbuild#182]
it's the only thing preventing me from switching from babel really

**Comment by evanw** [comment]
The minimum language target for esbuild is set at ES6, which supports arrow functions. It's not possible to set the language target to ES5. I'm currently not intending for esbuild to be able to target below ES6, at least not while there's still a lot of remaining work to do for transforming syntax for ES6 and up.

You might want to look at other tools for this. I've heard that [swc](https://github.com/swc-project/swc) is trying to be a faster implementation of Babel, so it might be a good replacement for you.

**Comment by tooolbox** [comment]
Hm, could be worth doing a survey:
- How many people aren't using esbuild because it doesn't convert X feature of ES2019 down to ES6?
- How many people aren't using esbuild because it doesn't convert X feature of ES6 to ES5?

Personally I most need async/await lowering, but generally I would fall in the latter camp; I care more about supporting older browsers than things like async generators or bigints.

Aside from speed, what's most exciting about esbuild is its potential to centralize the entire build process into a single tool.  I think ditching Babel is less about the speed increase and more about the toolchain simplicity.

**Comment by MathGeniusJodie** [comment]
I'll just use rebuild for projects that don't need to support ie then, thanks ^^

**Comment by evanw** [comment]
> Personally I most need async/await lowering

FYI I just implemented this in version 0.5.8 (see also #137).

**Comment by evanw** [comment]
I'm going to close this in favor of #297 which is more general.

**Comment by tooolbox** [comment]
🤯 

(take note, @MathGeniusJodie)
