### ISSUE TITLE
Include entry function in bundle without exporting

### ISSUE THREAD

**Issue by sharing-tech** [evanw/esbuild#1832]
Is there an operation if I don't want to include only the entry file or entry function in the treeshaking target?
I'm currently bundling for CloudFront Functions (CF2), but I can't use export with CF2.
I want to include the handler function in the bundle without doing an export.

### config
```
format: 'esm',
bundle: true,
```

### source
**`sitedomain.ts`**
```typescript
import { CloudFrontFunctionsEvent } from 'aws-lambda'
import { addWWW } from '../common'
import { CloudFrontFunctionsResult } from '../types'

// If I include 'export' here, I get an error in CF2.
// If I remove the 'export' here, nothing will be output.
export function handler({
  request,
}: CloudFrontFunctionsEvent): CloudFrontFunctionsResult {
  // unify the presence or absence of www
  var redirectWWW = addWWW(request)
  if (redirectWWW) {
    return redirectWWW
  }

  return request
}
```

**`common.ts`**
```typescript
import {
  CloudFrontFunctionsRequest,
  CloudFrontFunctionsRedirect,
} from './types'

export const addWWW = (
  request: CloudFrontFunctionsRequest,
): CloudFrontFunctionsRedirect | false => {
  // pass
}

export const removeWWW = (
  request: CloudFrontFunctionsRequest,
): CloudFrontFunctionsRedirect | false => {
  // pass
}
```
common.ts contains addWWW and removeWWW, but I only use one and I don't want to include it in the bundle.

### output
```javascript
// src/functions/common.ts
var addWWW = (request) => {
  // pass
};

// src/functions/sites/sitedomain.ts
function handler({
  request
}) {
  var redirectWWW = addWWW(request);
  if (redirectWWW) {
    return redirectWWW;
  }
  return request;
}
export {
  handler
};
```

#### error part
```javascript
export {
  handler
};
```

#### error contents
```
The CloudFront function associated with the CloudFront distribution is invalid or could not run. SyntaxError: Illegal export statement in 46
```

P.S. Many thanks for esbuild

**Comment by evanw** [comment]
Setting the format to `esm` tells esbuild to assume the output will be run as an ES module, but you are then running it as something else, which is of course not going to work. You should never be setting the format to `esm` if CloudFront does not support ES modules.

I'm very unfamiliar with however CloudFront works but from your post I'm going to assume you need a top-level variable called `handler` somewhere in your code that holds a function object. This isn't a module format that esbuild supports directly (it only supports CommonJS modules, ES modules, and IIFE modules) but you should be able to hack this in by doing something like `handler = function` instead of `export function handler` and then changing the configuration to this:

```diff
-format: 'esm',
+format: 'iife',
+banner: { js: 'var handler;' },
 bundle: true,
```

This will basically make the output look something like this:

```js
var handler;
(() => {
  ...
  handler = function(request) {
    ...
  };
})();
```

The function definition was being removed because non-exported function definitions have no side effects and can't possibly be accessed in any of the output formats that esbuild supports. With this change, the function is no longer being removed because from esbuild's point of view `handler` is a global variable and assigning to a global variable is a side effect. The banner feature inserts arbitrary text into the output file but is used here to turn `handler` into a local variable again, which is what I'm assuming you need here.

I'm not sure what module format CloudFront uses or how it defines exports so if their module format is something other than "you need a local variable called `handler`", the solution here may look very different. But that's something you'll need to figure out for yourself given the esbuild settings at your disposal.

**Comment by sharing-tech** [comment]
I see, thank you for the detailed explanation!
Unfortunately it didn't work with that hack.
It was a little different from what I was looking for, but it worked with `treeshaking: false`.

**Comment by dsmrt** [comment]
Just in case anyone else finds this. I had this same issue with (transpiling CloudFront Functions with esbuild) and followed the above. Here's everything put together.

Here is my esbuild command:
```bash
esbuild function.ts \
  --outfile=function.js \
  --target=es5 \
  --tree-shaking=false \
  --format=iife \
  --banner:js='var handler;' \
  --bundle
```

My function looks like this:
```typescript
import { CloudFrontFunctionsEvent } from "aws-lambda"
// ts ignore since we are defining the `var handler;` in the banner.
// @ts-ignore 
handler = function (event: CloudFrontFunctionsEvent) {
  // ...
}
```

**Comment by doteric** [comment]
Hey 👋  
@evanw , I've done the following configuration and it seems to work well initially with some basic examples, but I'm wondering if I could reach some edge cases. Config:
```
{
        "format": "cjs",
        "target": "es5",
        "platform": "neutral",
        "treeShaking": false,
        "banner": {
          "js": "var module = {};"
        },
        "minifyIdentifiers": false,
        "supported": {
          "const-and-let": false,
          "exponent-operator": true,
          "template-literal": true,
          "arrow": true,
          "rest-argument": true,
          "regexp-named-capture-groups": true
        }
      }
```
I simply use the `cjs` format and declare a `var module = {}` which acts as a suppressor.
I can then safely:
```typescript
function handler(event: unknown) {
  ...
}
export default handler;
```
As I mentioned, initially it works, but I wonder if it's an "okeyish" idea.
The `module.exports` is actually unused inside the CloudFront function, but it doesn't harm it either 🤔

**Comment by johannes-idealayer** [comment]
Adding on to @doteric's comment:

If you use CloudFront Functions [runtime 2.0](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/functions-javascript-runtime-20.html) it supports a few more features, so you can turn on `arrow`, `async-await`, `const-and-let`, `exponent-operator`, `regexp-named-capture-groups`, `rest-argument`, `template-literal`, and `unicode-escapes`.

I've also been able to make it work with full minification. What I did was use `format: "esm"` and then simply regex-replace the `export{xxx as handler}` in the output with `var handler=xxx`.

**Comment by mihailthebuilder** [comment]
For those who got here when trying to bundle for Google Apps Script. The `tree-shaking` works, here's the full command:

```
esbuild src/index.ts --bundle --outfile=dist/server.js --minify=false --keep-names --format=esm --tree-shaking=false
```

**Comment by MauriceArikoglu** [comment]
I've setup my CloudFront 2.0 Function in TypeScript with the following esbuild config:

```
import { tsPathsPlugin } from '@awalgawe/esbuild-typescript-paths-plugin';
import { build } from 'esbuild';

build({
  entryPoints: ['./functions/index.ts'],
  bundle: true,
  treeShaking: true,
  outfile: 'out/function.js',
  platform: 'neutral',
  format: 'esm',
  target: 'es6',
  minify: false,
  plugins: [tsPathsPlugin()],
}).catch(() => process.exit(1));

```

This also handles absolute import paths and inlines everything according to CF spec in my case.
