### ISSUE TITLE
Generate code coverage instrumentation

### ISSUE THREAD

**Issue by LarsDenBakker** [evanw/esbuild#184]
I'm working on a [new test runner](https://github.com/modernweb-dev/web/tree/master/packages/test-runner) where I am evaluating `esbuild` to replace babel.

I can replace most things, but one final major part I need babel for is generating code coverage instrumentation for https://istanbul.js.org/ using https://github.com/istanbuljs/babel-plugin-istanbul.

Do you think that something like this could be added to `esbuild`?

**Comment by evanw** [comment]
I agree that this could be cool, but it's outside the intended scope of esbuild. And while esbuild is intending to add support for plugins in the future (#111), a plugin for this likely wouldn't have much of a speed advantage over other approaches since it'd have to re-parse the source code. So you'll have to stick to Babel for this unfortunately.

I could see maybe adding a code coverage transformation to esbuild if it's something super simple (e.g. "call this function with the line number before every statement"). But I'm guessing it's something more complicated, pretty custom to Istanbul, and not that useful for other code coverage tools, which seems more appropriate for a plugin.

**Comment by LarsDenBakker** [comment]
Thanks for your response. I do appreciate that you're looking to keep the project scope very focused.

**Comment by evanw** [comment]
I'm going to close this since I consider it out of scope for esbuild.

**Comment by rickmed** [comment]
@evanw 
>  a plugin for this likely wouldn't have much of a speed advantage over other approaches since it'd have to re-parse the source code.

why?

**Comment by evanw** [comment]
If you re-parse the source code, then that's going to be your bottleneck. It means that your build will be nearly as slow as a JavaScript-based bundler (assuming you use a JavaScript-based parser to implement this) since that's what a JavaScript-based bundler would be doing.

**Comment by cenfun** [comment]
There is no need to instrument the source code if using native V8 coverage data in 2024, here is the tool [monocart-coverage-reports](https://github.com/cenfun/monocart-coverage-reports)
