### ISSUE TITLE
Imports break depending on order of exports from index.ts

### ISSUE THREAD

**Issue by nozzlegear** [evanw/esbuild#1850]
Hey, I think I've discovered a bug with esbuild where imports will break depending on the order of exports from an `index.ts` file. I thought maybe I just didn't know about this limitation with JavaScript but using the typescript compiler produces code that works, and using esbuild produces code that breaks.

Here's a repo containing a reproduction of the bug: [nozzlegear/esbuild-export-bug](https://github.com/nozzlegear/esbuild-export-bug).

| Package    | Version |
|------------|---------|
| esbuild    | 0.14.3  |
| typescript | 4.5.4   |
| node       | 16.13.1 |

## Reproduction steps

First, create a new file named `run.ts` and add the following code to it:

```ts
import { startApp } from "./src";

startApp();
```

Next, create a folder named `src` and add add three files to it named `say.ts`, `app.ts` and `index.ts` with the following code:

```ts
// In say.ts

export function say(phrase: string) {
    console.log(phrase);
}
```

```ts
// In app.ts

import { say } from "./";

export function startApp() {
    say("hello world from app.ts")
}
```

```ts
// In index.ts

export * from "./app";
export * from "./say";
```

Now compile the four files with esbuild:

```sh
esbuild --outdir=esbuild-bin --platform=node --format=cjs run.ts src/*.ts
```

Finally, run the `run.js` file with node:

```sh
node esbuild-bin/run.js
```

If reproduced successfully, you'll get an error that looks something like this:

```
TypeError: (0 , import__.say) is not a function
    at startApp (/home/nozzlegear/repos/playgrounds/esbuild-bug-repro/esbuild-bin/src/broken/app.js:29:20)
    at Object.<anonymous> (/home/nozzlegear/repos/playgrounds/esbuild-bug-repro/esbuild-bin/run.js:24:28)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

## Workarounds

The bug seems to exist in the order of exports from `src/index.ts`. I've found several workarounds:

**Workaround 1:** Reorder the exports in `src/index.ts` to have `./say` exported before `./app`:

```
// In index.ts

export * from "./say";
export * from "./app";
```

**Workaround 2:** Export the `say` function explicitly:

```
// In index.ts

export * from "./app";
export { say } from "./say";
```

**Workaround 3:** Import the `say` function from its own file instead of from `index.ts`

```
// In app.ts
import { say } from "./say";

export function startApp() {
    say("hello world from app.ts")
}
```

**Workaround 4:** Don't use esbuild, just compile the code with typescript instead:

```sh
npx tsc && node typescript-bin/run.js
```

**Comment by indutny-signal** [comment]
See https://github.com/evanw/esbuild/issues/1894

**Comment by DavidZbarsky-at** [comment]
I actually think this is #1890 which has been fixed

**Comment by evanw** [comment]
I confirmed that this was fixed by #1894, in version 0.14.27.

**Comment by jhvissotto** [comment]
I have the same issue in 2023. Changing export error order breaks the application. It's unbelievable!!!

**Comment by DavidZbarsky-at** [comment]
@jhvissotto JS Modules are surprisingly complicated and where there is complexity, there are often latent bugs. If you take a bit of time to share a reduced testcase, I bet Evan would be interested in debugging/fixing it (at least based on my experience reporting a few issues)

**Comment by jhvissotto** [comment]
Ok, here we go.

I was trying to create a backend boilerplate. Simple, without DDD, but complete. With cache, Redis, Apollo, Swagger, Knex, Prisma, zod, jwt, etc, etc. Using the Nest.Js componentization pattern. Ready to scale to a large application.

For test purpose, I let only one controller imported and activated in the express router, the auth controller. That should return { success: true }. Simple.

![image](https://user-images.githubusercontent.com/19745638/215008576-53f6e399-e945-4474-b4b6-2a9cfe8606ca.png)

Then I created a template for express router called "createRoute", for unsure the correct inputs.

![image](https://user-images.githubusercontent.com/19745638/215008843-93a86dfd-17b9-46a5-87bf-456bfa0cffd8.png)

The inputs comes from the file called "defs".

![image](https://user-images.githubusercontent.com/19745638/215008987-bbd4c41b-9d64-4adf-9568-a947945395ea.png)

And here we have the problem: I developed the folder/files architecture so that I can access any function or atribute just browsing so: folder1.folder2.folder3.function() or folder2.const.

Example: 

![image](https://user-images.githubusercontent.com/19745638/215009904-cc646424-4574-4d40-8194-d8a73fede5d2.png)


So here we can see the problem happening:

![image](https://user-images.githubusercontent.com/19745638/215010436-6965f2c2-6e83-4131-93fd-02dbdb4c73ea.png)

So changing the order of exportation the createRoute function is able to receive the inputs of the defs.ts file and don't throw a error. The express server until works! However, the file routes is not able to read the defs inside of the createRoute and the props of component auth is all undefined.

![image](https://user-images.githubusercontent.com/19745638/215010988-757fd36d-e8db-44b9-9642-9cbe3c2093a0.png)


![image](https://user-images.githubusercontent.com/19745638/215011695-d8e737ca-93bf-4c69-a2b1-ee16b261f512.png)

So, as you can see, when I stress the feature [[ export * from '...' ]]  until the last consequences that error happens.

It's the first time I'm trying to create a backend boilerplate in Typescript. I never faced that before.

Maybe DDD arch could solve that problem. But I think DDD very non intuitive. I don't know what to do now. That project is stopped. You can copy the boiler here:  https://github.com/jhvissotto/backend
