### ISSUE TITLE
incorrectly handling of `this` on a module namespace object

### ISSUE THREAD

**Issue by bakkot** [evanw/esbuild#1891]
Input:
```js
// esbuild-a.mjs
export function f() {
  this.g();
}

export function g() {
  console.log(0);
}
```
```js
// esbuild-b.mjs
import * as a from './esbuild-a.mjs';
a.f();
```

If you run `node esbuild-b.mjs` it will print `0`. Same behavior in browsers. This is correct per spec.

However, running `esbuild esbuild-b.mjs --bundle --format=esm` produces

```js
// esbuild-a.mjs
function f() {
  this.g();
}

// esbuild-b.mjs
f();
```

which, when run, throws because `this` is undefined, and would also throw because `g` is missing.

This is another one of those "I went looking for dumb edge cases" bugs, not something which came up in real code, so prioritize accordingly.

**Comment by evanw** [comment]
I'm actually already aware of this. My current opinion is that deviating from the specification here is far more valuable than following it. If this were to be followed literally, then large amounts of real-world code would not be tree-shakeable. It would be a shame to effectively disable tree shaking for most people for what is an extremely obscure edge case (and arguably a terrible anti-pattern as well). Another data point is that [Rollup does this too](https://rollupjs.org/repl/?version=2.62.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMGElMjBmcm9tJTIwJy4lMkZlc2J1aWxkLWEubWpzJyUzQiU1Q25hLmYoKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmVzYnVpbGQtYS5tanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZnVuY3Rpb24lMjBmKCklMjAlN0IlNUNuJTIwJTIwdGhpcy5nKCklM0IlNUNuJTdEJTVDbiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMGcoKSUyMCU3QiU1Q24lMjAlMjBjb25zb2xlLmxvZygwKSUzQiU1Q24lN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==), so writing code that relies on this behavior is already non-portable.

I suppose I could try to add analysis for this, which would look something like "if a module namespace exotic object could possibly be referenced in the `this` position by a function containing `this` inside the body, then disable tree shaking for that whole module." But the analysis for this is very complicated and imprecise. I'd need to track whether each function uses `this` as well as if it is ever re-assigned. And calling any non-function export (i.e. a function stored in an exported variable) would always have to disable tree shaking for that whole module since the variable could hold anything. I still don't think it's worth doing given that no one should ever write code like that.

**Comment by evanw** [comment]
I’m going to close this as “won’t fix” for the reasons stated above.

**Comment by bakkot** [comment]
Makes sense, but maybe worth adding [a caveat to the docs](https://esbuild.github.io/content-types/#javascript-caveats)?

**Comment by evanw** [comment]
This has been documented here: https://esbuild.github.io/content-types/#module-namespace-this.
