### ISSUE TITLE
[bug] An unexpected sourcemap

### ISSUE THREAD

**Issue by bvanjoi** [evanw/esbuild#1920]
- version: `0.14.10`.

I had tried to convert the code to ESM and then to CJS, then sourcemap got lost, as figure showned.

This [demo](https://github.com/bvanjoi/ESBuild-Sourcemap-merge-bug-demo) describes more detailed information.

![error sourcemap](https://github.com/bvanjoi/ESBuild-Sourcemap-merge-bug-demo/raw/main/images/error.png)

**Comment by evanw** [comment]
That's not a bug. There's no executable code there, so there's nothing to map. The debugger will never stop there.

**Comment by bvanjoi** [comment]
But in some case we may encounter unexpected result. 

For example, we need statistics code coverage( [c8](https://github.com/bcoe/c8), a code coverage tools using [V8_NODE_COVERAGE](https://nodejs.org/api/cli.html#node_v8_coveragedir)), and if lack this sourcemap infos,  It will cause [mapping.generatedLine === needle.generatedLine](https://github.com/mozilla/source-map/blob/master/lib/source-map-consumer.js#L507) return `false`, so that we get wrong result.

![5wgk8e6YoO](https://user-images.githubusercontent.com/30187863/148548279-a3d7d646-6762-4051-b378-2a1452771af9.png)

**Comment by evanw** [comment]
I still don't understand. You're saying that a code coverage tool reports that some of your code is not covered by tests when that uncovered code is just blank lines with no code in them? That sounds like a bug with your code coverage tool to me. One idea for how to work around that bug is to use `--minify-whitespace` to make esbuild's output mostly on a single line.

**Comment by bvanjoi** [comment]
Emm, maybe I should submit some code for c8 to improve its ability to handle boundary cases.
