### ISSUE TITLE
transforming for await loop not supported for browser that supports it

### ISSUE THREAD

**Issue by thepassle** [evanw/esbuild#1930]
I noticed esbuild doesnt transform `for-await loops` for build target `safari11`:

```
✘ [ERROR] Transforming for-await loops to the configured target environment ("safari11") is not supported yet

    app.js:3:6:
      3 │   for await (const i of a) {
        ╵       ~~~~~
```

However, according to both [caniuse](https://caniuse.com/?search=for%20await) and [mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of#browser_compatibility), safari11 does support `for-await` loops.

It made me wonder if there is a particular reason esbuild doesnt currently handle it that I might be unaware of, or is this an oversight?

Reproduction:
https://stackblitz.com/edit/node-3gwvxg?file=index.js
![image](https://user-images.githubusercontent.com/17054057/149119794-080e8861-08d8-4f63-93e6-4a9f239f8c7b.png)

**Comment by evanw** [comment]
> It made me wonder if there is a particular reason esbuild doesnt currently handle it that I might be unaware of, or is this an oversight?

The reason is that it's a very obscure feature that almost no one uses and it's non-trivial to implement. I think you're the first person to ask about it. In all my time writing JavaScript professionally I've seen exactly one use of `for await` and it was easily replaced by a `for` loop containing an `await` inside it.

> However, according to both [caniuse](https://caniuse.com/?search=for%20await) and [mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of#browser_compatibility), safari11 does support `for-await` loops.

My [source for browser compatibility data](https://github.com/kangax/compat-table/blob/ae834ce301e4d4d2b6611833ce7ee0dcfc5a5b63/data-es2016plus.js#L3356) says that they are supported in Safari 12+. I just checked Safari 11.1 on BrowserStack and `for await` can't even be parsed, so my compatibility data appears to be correct and MDN/Caniuse appears to be wrong. Here's a screenshot:

<img width="522" alt="SyntaxError: Unexpected identifier 'await'. Expected '(' to start a for-loop header." src="https://user-images.githubusercontent.com/406394/149174918-ddae89b4-638d-4aeb-bf92-2d110b73f49e.png">

The simplest workaround for you is probably to just use a `for` loop with an `await` in it instead of using a `for await` loop.

**Comment by thepassle** [comment]
> The reason is that it's a very obscure feature that almost no one uses and it's non-trivial to implement. I think you're the first person to ask about it. In all my time writing JavaScript professionally I've seen exactly one use of for await and it was easily replaced by a for loop containing an await inside it.

Yeah, I definitely agree that the code that uses it could(/should) be refactored to not use a for-await loop, but unfortunately the code is not directly under our maintenance.

Interesting that both caniuse and mdn are off on this one, thanks for confirming that indeed safari11 does not support for await loops.

Thanks for the detailed and swift answer 🙂  I'll close this issue then

**Comment by LarsDenBakker** [comment]
@evanw would you consider adding an option to let these pass through uncompiled? Then at least the rest of the code could be compiled to a certain target or browser.

**Comment by evanw** [comment]
Why would you want to do that? Then the code still wouldn't work in the target browser. You could run another tool (e.g. Babel/TypeScript/SWC) after esbuild to post-process the code for the target browser, but then why not have that other tool transform other syntax too? If you want to use esbuild transform away the newest syntax that your other tools don't yet support, you can still use `--target=es2018` with esbuild and continue to use `for await`.
