### ISSUE TITLE
Watch option doesn't seem to work for Go API

### ISSUE THREAD

**Issue by aslilac** [evanw/esbuild#1948]
A minimal test program of...

```go
package main

import (
	"fmt"

	esbuild "github.com/evanw/esbuild/pkg/api"
)

func main() {
	esbuild.Build(esbuild.BuildOptions{
		EntryPoints: []string{"main.ts"},
		Outfile:     "out.js",
		Bundle:      true,
		Watch: &esbuild.WatchMode{
			OnRebuild: func(result esbuild.BuildResult) {
				if len(result.Errors) > 0 {
					fmt.Printf("watch build failed: %d errors\n", len(result.Errors))
				} else {
					fmt.Printf("watch build succeeded: %d warnings\n", len(result.Warnings))
				}
			},
		},
	})

	fmt.Printf("watching...\n")
}
```

...just exits immediately, even though it's basically a copy-paste of the [Go example given in the documentation](https://esbuild.github.io/api/#watch). Idk if I'm missing something, but I'm pretty sure that either the documentation is leaving something out, or there's a bug here

**Comment by evanw** [comment]
It exits immediately because you're exiting immediately. That's completely under your control. Watch mode runs on a separate thread. Unlike node, Go doesn't keep the process open if there are background threads. Once `main` returns the process exits. You could add something like `<-make(chan bool)` at the end of `main` to keep the process open. It's what esbuild does:

https://github.com/evanw/esbuild/blob/3449be558dad71b3d411ceea7ddfd0a45e2e374c/pkg/cli/cli_impl.go#L1008

You could also do something else like calling [`runtime.Goexit()`](https://pkg.go.dev/runtime#Goexit) if you want. But you need to avoid exiting immediately somehow.

You probably also want to set `Write: true` or you will only get the in-memory results back. I can add that to the example code. The default value for the JS API is `true` but the default value for the Go API is `false` because Go can't distinguish between `false` and `undefined` like JS can.

**Comment by aslilac** [comment]
I kind of figured it was something like that, I've just never used Go before and wasn't sure 😅 Thanks for the tip!

It might be worth adding `<-make(chan bool)` to the end of the Go snippet in the docs, with a brief comment explaining why it's useful/necessary

**Comment by evanw** [comment]
Just added it to the docs: https://esbuild.github.io/api/#watch. Closing this issue as it seems like it's resolved.
