### ISSUE TITLE
Results of imports not taken into account in file hashes

### ISSUE THREAD

**Issue by jacob-ebey** [evanw/esbuild#1957]
Esbuild does not seem to be taking into account the inlined values that results from importing a file.

## Actual Behavior

Given these two files:

index.js
```
import href from "./index.css";
console.log(href);
```
index.css
```
h1 { color: blue; }
```

Running a build may output:
- build/index-hash1.css
- build/index-hash1.js

Now making a change to index.css (`color: red;` or something) we get the same hash for the .js file, but a new hash for the .css file:
- build/index-hash2.css
- build/index-hash1.js

Here is a repository with the described behavior above: https://github.com/jacob-ebey/esbuild-hash-repro

## Expected Behavior

When index.css changes, the resulting contents of the bundled index.js also changes. I'd expect the hash for the ".js" output file to change along with the contents.

**Comment by kiliman** [comment]
When I was troubleshooting this issue, I copied the output of the first build, then ran the build again after changing the .css file. If you notice, the index.js file has the SAME hash in both builds, but the contents are DIFFERENT. I don't think that was the intended result.

![image](https://user-images.githubusercontent.com/47168/150875349-02b6521c-ba0f-46ee-bbad-2732e480dc92.png)

**Comment by evanw** [comment]
Thanks for the report. This is a bug and is not intentional. Injected file paths are only finalized at the end of the linking phase since they need to be calculated relative to other output file paths, and this graph can have cycles. The hash calculation was accounting for injected file paths in cross-chunk `import` statements but not injected file paths due to the `file` loader. I believe this simple to fix.

**Comment by jacob-ebey** [comment]
Thank you @evanw :)
