### ISSUE TITLE
Using --external:./node_modules/* results in relative import instead of bare import

### ISSUE THREAD

**Issue by supachailllpay** [evanw/esbuild#1958]
From `entry.js`:

```js
import React from 'react'
```

Run build:

```bash
esbuild entry.js --bundle --outfile=out.js --format=esm --external:"./node_modules/*"
```

Then `out.js`:

```js
import React from "./node_modules/react/index.js";
```

But if I just exclude `react` directly:

```bash
esbuild entry.js --bundle --outfile=out.js --format=esm --external:react
```

Then the result will be:

```js
import React from "react";
```

Or if I use the plugin below to manually exclude all packages from `node_modules`. The result will still be a bare import.

```js
let makeAllPackagesExternalPlugin = {
  name: 'make-all-packages-external',
  setup(build) {
    let filter = /^[^.\/]|^\.[^.\/]|^\.\.[^\/]/ // Must not start with "/" or "./" or "../"
    build.onResolve({ filter }, args => ({ path: args.path, external: true }))
  },
}
```

_Originally posted by @evanw in https://github.com/evanw/esbuild/issues/619#issuecomment-751995294_

So I'm not sure if this is the intended behavior or bug?. And if this is intended, how can I do this without using a plugin?

Thank you.

**Comment by matthiasg** [comment]
I just stumbled into this as well. This causes npx to be broken though as the node_modules folder is not created in the same location after 'install'.

**Comment by maximilianschmitt** [comment]
I've also encountered this issue while trying to use esbuild to bundle some TS code for an Electron application.  `import ejs from 'ejs'` becomes `require("../../node_modules/ejs/lib/ejs.js")` in the resulting bundle which then creates issues when run with Electron because when bundling the application, the node_modules move relative to the entry-file.

**Comment by StarpTech** [comment]
Hi, I run into this as well. This only happens for `require` imports. It would be great to have a continuation on this. As a workaround, I mark all packages in node_modules as external.

**Comment by ShravanSunder** [comment]
i'm also running into this with https://github.com/juliencrn/usehooks-ts/issues/97

**Comment by jakebailey** [comment]
Not sure if you've already considered it, but this would be a great breaking change to include in something like #2508.

I've personally worked around this by doing something like `const moduleName = "source-map-support"` and then `requiring` that, since I need to enable that if it works (but there's no guarantee that any particular version of that library has the final mapped path).

**Comment by jakebailey** [comment]
I think that this is the same bug, but one thing I've noticed is that if you set `--./node_modules/*` but are targeting the CJS format, you will end up with code like:

```js
chai = __toESM(require("../../node_modules/chai/index.mjs"));
```

Which will fail to work since that's not CJS code. If the code had not been external, this would have been fine since it'd be bundled and so the MJS-ness of the file would not matter.

Setting the conditions to be `require` fixes things.

**Comment by jakebailey** [comment]
After viewing some of the cross-linked PRs, I realized that I had completely glossed over the fact that you can just specify each package name as "external" directly, rather than using a wildcard. With that in mind, I've ended up going with using a plugin that enforces that "external" is fully configured:

```js
{
    name: "no-node-modules",
    setup: (build) => {
        build.onLoad({ filter: /[\\/]node_modules[\\/]/ }, () => {
            // See: https://github.com/evanw/esbuild/issues/1958
            return {
                errors: [{ text: 'Attempted to bundle from node_modules; ensure "external" is set correctly.' }]
            };
        });
    }
},
```

This gives me a handy error at bundle time:

![image](https://user-images.githubusercontent.com/5341706/195906067-2dedd5f8-ec64-43b2-8e07-3ee286f354f2.png)

This is plenty for my needs.
