### ISSUE TITLE
Should not eliminate dead code if `new Function(...)` exists

### ISSUE THREAD

**Issue by athyuttamre** [evanw/esbuild#196]
Hey Evan! I found an issue with dead code elimination in an edge case that involves declaring a function using `new Function(...)`. I'm using commit 25b92bfbb7278e1ce1f9005367eccaf3cf1d9d48 locally.

Context: In addition to the normal `function f() {...}` and `const f = () => {...}` syntax for declaring functions, JS also allows declaring functions via an eval-like format: `const f = new Function('return 1')` ([docs on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/Function)). Functions declared like this can only operate in the global scope.

Our test case:

```js
// demo/new-function.js
function foo() { return 1; }
const callFoo = new Function('return foo()');
console.log(callFoo());
```

Running `esbuild --bundle demo/new-function.js` has the effect of removing `foo()` altogether:

```shell
$ ./esbuild --bundle demo/new-function.js
(() => {
  // demo/new-function.js
  const callFoo = new Function("return foo()");
  console.log(callFoo());
})();
$
```

I think this is a logic error, and has to do with dead code elimination assuming that `foo()` is not used anywhere. Doing something like what we do with `eval` is likely to fix this (but only in the global scope, since these functions only operate there).

https://github.com/evanw/esbuild/blob/25b92bfbb7278e1ce1f9005367eccaf3cf1d9d48/internal/ast/ast.go#L1092-L1095

While I wasn't able to repro simply, the same issue might also show up via minification (imagine that we kept the function, but renamed it to `a()`; the code would still fail).

I'm happy to help fix this if I could get some pointers on where to start. Totally ok if you prefer to just fix it too.

Thanks for all the great work with esbuild!

---

One caveat is that the test case doesn't actually run in Node, but does run in the browser (at least in WebKit in Safari, where I tested).

Node.js:
```
$ node --version
v14.4.0
$ node demo/new-function.js
undefined:3
return foo()
^

ReferenceError: foo is not defined
    at eval (eval at <anonymous> (/Users/athyuttamre/Work/github/esbuild/demo/new-function.js:2:17), <anonymous>:3:1)
    at Object.<anonymous> (/Users/athyuttamre/Work/github/esbuild/demo/new-function.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
$
```

Webkit in Safari:
<img width="1112" alt="Screen Shot 2020-06-24 at 12 41 25 AM" src="https://user-images.githubusercontent.com/1485350/85516904-931ac500-b5b3-11ea-9681-36b63c3cae4d.png">

**Comment by evanw** [comment]
Thanks for taking the time to report an issue. However, I don't think the behavior you want is possible. It sounds like you'd like for the `esbuild --bundle demo/new-function.js` command to produce this output:

```js
(() => {
  // demo/new-function.js
  function foo() { return 1; }
  const callFoo = new Function("return foo()");
  console.log(callFoo());
})();
```

That output won't do what you want. It will always crash with `ReferenceError: foo is not defined`, even in the browser. The problem is that the code inside `new Function()` is always run under the global scope. It behaves like indirect eval, not direct eval.

The reason the code worked in your browser screenshot is because you were running the original unbundled source code and the function `foo` became stored on the global scope. Bundling your code moves it outside the global scope, so the `foo` function is no longer accessible and the dead code elimination is correct. If you want it to still be accessible in the global scope, you could always change it to `window.foo = function() { return 1 }` instead. That will also cause it to not be eliminated as dead code.

**Comment by athyuttamre** [comment]
Ah, that does make sense, thanks for responding!

(Not that this was a real use case; I was just reading through the code and wondered if there were any other eval-like features in JS and stumbled upon this. The detailed comments throughout really helped my comprehension!)
