### ISSUE TITLE
feature request: throw expressions

### ISSUE THREAD

**Issue by CheloXL** [evanw/esbuild#197]
I would like to propose a transform for [throw expressions](https://github.com/tc39/proposal-throw-expressions).
It's the only transform I'm missing right now to migrate from babel. Impressive speed boost!

**Comment by evanw** [comment]
Throw expressions are cool but they are currently only at stage 2. I will implement them if they ever get far enough along in the process (basically if they are implemented by a browser or by the TypeScript compiler).

I'm going to close this issue for now since it's not looking like there's currently any momentum for throw expressions. The proposal was last updated over two years ago and some of the issues point to a conflict with the "do" expression proposal.

I'm not planning to have esbuild implement tentative TC39 proposals like Babel does. Babel is an appropriate playground for new language ideas while esbuild will only be following the official JavaScript language specification.
