### ISSUE TITLE
Will `esbuild` take a collection of already transpiled JavaScript files together with an entry file name and return a bundle?

### ISSUE THREAD

**Issue by djalbat** [evanw/esbuild#198]
I have a tool that leverages Babel and Browserify to build bundles incrementally. However, although I can transpile only the JavaScript files that change, that is incrementally, I have to bundle the whole collection every time. Therefore a fast bundler would be extremely useful. I'd like to stick with transpiling with Babel, at least for the time being, but a fast bundler would be very welcome!

The tool is here:

https://github.com/djalbat/watchful-cli

The bit where I invoke Browserify is here:

https://github.com/djalbat/watchful-cli/blob/master/bin/utilities/bundle.js

So, ideally, I would like to swap in `esbuild` for Browserify here.

I understand that I need something like:

```
const { build } = require('esbuild')

build({
  entryPoints: ['...'],
  outfile: '...',
  minify: false,
  bundle: true,
}).catch(() => process.exit(1))
```
So my question is whether it transpiles by default (which I don't need) and if so, how to turn it off. Also, is there a way of configuring it to use source maps?

Many thanks in advance!

**Comment by evanw** [comment]
> So my question is whether it transpiles by default (which I don't need) and if so, how to turn it off. Also, is there a way of configuring it to use source maps?

This is documented in [the readme](https://github.com/evanw/esbuild/blob/b3dfb491e09c7fa79ef6b6a0eda0cf05205383b9/README.md#command-line-usage):

```
  --target=...          Language target (default esnext)
```

The latest version of JavaScript is called ESNext. Since the language target defaults to ESNext, esbuild will never transform syntax to older versions of JavaScript by default.

```
  --sourcemap           Emit a source map
```

Source map support is configured by enabling the `sourcemap` option.

The JavaScript APIs correspond directly to the command-line APIs. The type definitions for the JavaScript API are [here](https://github.com/evanw/esbuild/blob/b3dfb491e09c7fa79ef6b6a0eda0cf05205383b9/lib/api-types.ts) for reference.

**Comment by jecs-imperial** [comment]
Many thanks. I'll give it a try.

**Comment by evanw** [comment]
I'm going to close this because the question was answered. This should be possible, at the very least by building into a parallel directory hierarchy and running esbuild there. Depending on what you're asking you may want the nested source maps feature, but there is already another issue for this: #211.

**Comment by djalbat** [comment]
Thank you again and apologies for not replying earlier. I do intend to look at this the moment I have the time, but feel free to keep it closed. If I have further questions, I'll open it again.
