### ISSUE TITLE
Where is the code for option deserialization in js api?

### ISSUE THREAD

**Issue by rxliuli** [evanw/esbuild#1982]
Currently I'm trying to complete an out-of-the-box lib, cli build tool based on esbuild and golang, but have some simple questions to understand. When using js api, the build option passed to esbuild is lowercase camel case and does not use enumeration in golang, while in golang api it is uppercase camelcase and needs to use enumeration, where is the deserialization code, If it's in golang, is it possible for me to reuse it?

```json
{
  "entryPoint": ["src/index.ts"],
  "outfile": "dist/index.js"
}
```

```go
options := api.BuildOptions{
  EntryPoints: []string{"src/index.ts"},
  Outfile:     "dist/index.js",
}

```

> ref: [saki](https://github.com/rxliuli/saki)

Also, if the esbuild plugin for js needs to be loaded, is it possible to reuse something from esbuild or do I have to reparse the js code and implement the communication part with the js plugin?

**Comment by evanw** [comment]
The JavaScript API converts the JS options into command-line flags, then the Go API converts the command-line flags into Go options. You can read the code for the details. The JS code to convert JS options into command-line flags is not exposed, since this is not a supported use case. The Go code to convert commands-line flags into Go options is exposed in the `cli` package, although keep in mind that it may not cover 100% of the options exactly since there are some slight differences between the CLI API and the non-CLI APIs (e.g. `metafile`).

Running JS plugins from Go yourself is not a supported use case. I have primarily designed esbuild to be used with JavaScript. Go was originally an implementation detail but was exposed as an API at the request of the community. However, I think the JavaScript APIs are most natural to use when JavaScript is the host and since that is the primary use case, I plan to keep the JavaScript API the way it currently is. It’s technically possible to call JS from Go but you’d have to do everything yourself. You can write a Go plugin for esbuild that creates a node child process and then communicates with it using whatever communication method you prefer.

**Comment by rxliuli** [comment]
At present, the reason why I try to implement this cli with golang is that the nodejs cli based on the esbuild package will be slow, especially in a relatively large monorepo (we have about 90 modules in the production environment), which will become unbearable, but thank you For the response, I think it may be possible to support configuration files for the time being. We can implement all plugins using golang. Anyway, the esbuild plugin is so simple (*^_^*).
