### ISSUE TITLE
Feature request: minify function names as well

### ISSUE THREAD

**Issue by scottdotjs** [evanw/esbuild#1989]
Variable names are shortened when minification is performed, if function names got the same treatment that would be great.

**Comment by evanw** [comment]
That's not true. Both are minified.

I'm guessing you're talking about top-level symbols (both variables and functions) not being minified when no output format is configured. This is because esbuild doesn't know what you will be doing with the output, so for safety it doesn't make any assumptions about top-level variable names. For example, you might be injecting the output inside some other code template, which is what happens with people that use esbuild in combination with languages that embed JS/TS snippets like [Svelte](https://svelte.dev). Preserving top-level symbol names doesn't happen if you set an output format (with `--format=`) or if you enable bundling (with `--bundle`, which automatically picks an output format if none was explicitly set).

**Comment by scottdotjs** [comment]
Oh right. That isn't mentioned in the [`--minify` section](https://esbuild.github.io/api/#minify) of the API docs. It would be useful context for people using esbuild for the first time (like me). Thank you.

**Comment by evanw** [comment]
Makes sense. I added the following documentation here: https://esbuild.github.io/api/#minify-considerations

> By default esbuild won't minify the names of top-level declarations. This is because esbuild doesn't know what you will be doing with the output. You might be injecting the minified code into the middle of some other code, in which case minifying top-level declaration names would be unsafe. Setting an output [format](https://esbuild.github.io/api/#format) (or enabling [bundling](https://esbuild.github.io/api/#bundle), which picks an output format for you if you haven't set one) tells esbuild that the output will be run within its own scope, which means it's then safe to minify top-level declaration names.

Closing as fixed.
