### ISSUE TITLE
Can't successfully install esbuild or it's broken

### ISSUE THREAD

**Issue by michaelusantiago** [evanw/esbuild#1992]
![trans1](https://user-images.githubusercontent.com/4829195/152647235-e1b630cc-2d6b-46d3-a5e0-be8b73f1fa0d.png)
![trans2](https://user-images.githubusercontent.com/4829195/152647247-3e57e2a4-2786-4045-bbef-084207d96a7a.png)

Did I missed/messed something?

It runs this way
![trans3](https://user-images.githubusercontent.com/4829195/152647533-983fb1a4-b2bb-4c4b-9768-b2e377bf720f.png)

**Comment by evanw** [comment]
Installing esbuild puts it in a folder, but it doesn't put it in your path. That's not how installing an npm package works. You can see the instructions for running esbuild here: https://esbuild.github.io/getting-started/#install-esbuild. To run it you can run `.\node_modules\.bin\esbuild --version`. If you run esbuild using a build script (see https://esbuild.github.io/getting-started/#build-scripts) then you can use the `esbuild` command as npm puts esbuild in your path for you in that case. You would type `npm run build` and then npm would run the command you have in your `package.json` file.

Note that some people also use the `npx` command to run `npx esbuild --version` using https://docs.npmjs.com/cli/v7/commands/npx. I haven't listed that here because it's buggy, slow, and has security issues (see #823). So that can work too as long as you don't hit the bugs or security issues.

All of this is just generally how commands in npm packages work. This isn't an esbuild-specific limitation.

**Comment by michaelusantiago** [comment]
Yeah my bad. When I figured out later and I wanted to delete this issue immediately but I can't.

Anyway, great tool. It's actually simple to use and fast.

**Comment by evanw** [comment]
No worries. Closing this issue as it seems resolved.
