### ISSUE TITLE
Exclude specific module from minification

### ISSUE THREAD

**Issue by stonedMoose** [evanw/esbuild#1993]
Sorry If I have missed an issue or a part of the documentation referencing this matter, but I'd love to be able to exclude a given module from minification.

It seems that minification breaks mysql bundling on AWS Lambda environment, for now I have just disabled minification on my functions, but I would appreciate activating it and only disabling mysql minification.

Any answer will be appreciated. 

Thanks

**Comment by evanw** [comment]
One option is you could bundle your code once with minification enabled but with that library as external, then bundle again with that library not external but with minification disabled.

Another option is you could get the bug fixed in the library you want to use so that the library is able to be minified.

**Comment by evanw** [comment]
Closing because this question has been answered.
