### ISSUE TITLE
Import of type only used for type annotations breaks build

### ISSUE THREAD

**Issue by ErikSchierboom** [evanw/esbuild#2029]
I'm working on a project to integrate `yjs` with `codemirror` using the `y-codemirror.next` package. 
I ran their [demo](https://github.com/yjs/yjs-demos/tree/main/codemirror.next) locally and all worked fine, but when I tried to use it with esbuild, I got some compilation errors.

After some digging, it turned out that this was for a somewhat odd reason: the `y-codemirror.next` package was importing a type from some of the codemirror packages but only used them in a type annotation. When compiling this with esbuild, esbuild (rightfully) complains about not finding a matching export, as the imported type is just a compile-time thing, not an actual imported type. The accompanying `index.d.ts` file _does_ export the type, but esbuild ignores it.

Here are some links to the source:

- First, the file that imports the `DecorationSet` type: https://github.com/yjs/y-codemirror.next/blob/main/src/y-remote-selections.js#L2
- Then, the type annotation comment that uses the `DecorationSet` type: https://github.com/yjs/y-codemirror.next/blob/main/src/y-remote-selections.js#L129
- The imported package's code looks like this: https://unpkg.com/@codemirror/view@0.19.43/dist/index.js (scroll down to the last line to see the exports: no `DecorationSet` exported)
- The imported package's `d.ts` looks like this: https://unpkg.com/@codemirror/view@0.19.43/dist/index.d.ts (scroll down to the last line to see the exports: the `DecorationSet` is exported)

## Repro

Go to https://stackblitz.com/edit/node-jla3pz?file=package.json

In the console, do:

```shelll
> npm install
```

Then do:

```shell
> npm run build
```

You should then see the following errors:

```shell
❯ npm run build
$ esbuild index.js --bundle --outfile=out.js --external:vue --format=esm
✘ [ERROR] No matching export in "node_modules/@codemirror/view/dist/index.js" for import "DecorationSet"

    node_modules/y-codemirror.next/src/y-remote-selections.js:2:57:
      2 │ ..., EditorView, Decoration, DecorationSet, WidgetType } from '@cod...
        ╵                              ~~~~~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/@codemirror/state/dist/index.js" for import "StateCommand"

    node_modules/y-codemirror.next/src/y-undomanager.js:3:15:
      3 │   EditorState, StateCommand, Facet, Annotation, AnnotationType // e...
        ╵                ~~~~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/@codemirror/view/dist/index.js" for import "KeyBinding"

    node_modules/y-codemirror.next/src/y-undomanager.js:6:33:
      6 │ ... { ViewPlugin, ViewUpdate, KeyBinding, EditorView } from '@codem...
        ╵                               ~~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/@codemirror/state/dist/index.js" for import "Extension"

    node_modules/y-codemirror.next/src/index.js:4:9:
      4 │ import { Extension } from '@codemirror/state' // eslint-disable-line
        ╵          ~~~~~~~~~

4 errors
```

**Comment by evanw** [comment]
This is a problem with that library, not with esbuild. You need to file an issue with them. That file contains invalid JavaScript code. It doesn't run with node either:

```
$ node index.js
file://./node_modules/y-codemirror.next/src/y-remote-selections.js:2
import { ViewPlugin, ViewUpdate, EditorView, Decoration, DecorationSet, WidgetType } from '@codemirror/view' // eslint-disable-line
                                                         ^^^^^^^^^^^^^
SyntaxError: The requested module '@codemirror/view' does not provide an export named 'DecorationSet'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:181:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
```

Closing this issue as invalid.

**Comment by iHiD** [comment]
@evanw Thanks for the quick response!

As you say `node index.js` gives the error above, but running `npm start` in that repo works fine. Equally running up a demo that imports that package with webpack seems to work fine too (e.g. the demo at https://github.com/yjs/yjs-demos/tree/main/codemirror.next) but switching it to esbuild breaks. 

Is there something "magical" that npm and/or webpack are doing here that esbuild is not doing (either due to some limitation or to some incorrect config on our side?) As Erik said in the OP, it feels like webpack is "honouring" the types definitions but esbuild is ignoring them. As we've only just switched everything in Exercism to esbuild now (from webpack), we're a little green on how things differ. 

Any more pointers would be really appreciated, and sorry if we're just being dump.

**Comment by evanw** [comment]
> running `npm start` in that repo works fine

I get this when I run `npm start` because there's no script called `start` in https://stackblitz.com/edit/node-jla3pz?file=package.json:

```
$ npm start
npm ERR! Missing script: "start"
npm ERR! 
npm ERR! Did you mean one of these?
npm ERR!     npm star # Mark your favorite packages
npm ERR!     npm stars # View packages marked as favorites
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run
```

> Is there something "magical" that npm and/or webpack are doing here that esbuild is not doing

I don't know, sorry. One guess is that Webpack is converting ESM to CommonJS without validating exports and then the import of `DecorationSet` becomes essentially `require('@codemirror/view').DecorationSet` which is `undefined`.

But you should be debugging this with them, not with me, because this is a problem with their package. It's not a problem with esbuild.

**Comment by ErikSchierboom** [comment]
Thanks for the detailed reply. We'll take it up with the library authors.
