### ISSUE TITLE
Sources imported via text loader doesn't appears in source maps

### ISSUE THREAD

**Issue by tinovyatkin** [evanw/esbuild#2041]
I need to get source reference for original file imported via text loader (in may case it's `*.graphql` file), but unfortunately I don't see original source entry in the `sources` array of generated source map. Do I missing something or it's a bug?

Example of source:
```ts
import SiteQuery from '@common/graphql/queries/site/site.graphql';
console.log(SiteQuery);
```

Bundles as expected (with ` loader: { '.graphql': 'text' }` option) into (including comment that points to the file properly):
```js
// ../common/graphql/queries/site/site.graphql
var site_default = '#import "../../fragments/site.graphql"\n\nquery Site($input: SiteInput!) {\n  site(input: $input) {\n    ...SiteFragment\n  }\n}\n';
console.log(site_default)
```

but there is no `site.graphql` entries in souce map `sources` array.

**Comment by hyrious** [comment]
This is intentional behavior in esbuild because it only outputs sourcemaps which are helpful in showing logs (errors, warnings). Basically they (helpful debug points) are the places that could throw errors, like accessing a variable name, accessing a getter, calling a function, etc. That's why it will choose these <samp><a href=#>|</a></samp> places shown below.

<p align=center><samp><a href=#>|</a>console.<a href=#>|</a>log(<a href=#>|</a>42)</samp></p>

A string from text loader doesn't trigger any errors or warnings, so esbuild won't preserve it in the output.

<p align=center><samp>var a = <a href=#>|</a>"text" // useless</samp></p>

However, you're free to write a plugin that makes use of [on-end](https://esbuild.github.io/plugins/#on-end) callback to append the missing sourcemap.
