### ISSUE TITLE
Build times are no longer displayed 

### ISSUE THREAD

**Issue by sortofsleepy** [evanw/esbuild#205]
👋 

Just tried upgrading from 0.2.9 to 0.5.14 and I noticed that build times aren't getting output anymore. Is there a reason that was taken out? Is there a way to re-enable?

If it's gone no worries, not super important but it was still a nice to have, helped me figure out why it seemed like my code was taking a noticeable amount of time to build.

**Comment by evanw** [comment]
I removed build status information because people were complaining about it being there. There currently isn't a way to re-enable it.

If you're on Unix and calling esbuild from the command line, you can always prefix the esbuild command with `time` to measure the build time like this:

```
time esbuild --bundle ./entry.js
```

That's slightly more accurate than the old time information anyway because it also includes the time for Go to initialize, although it's not a big difference.

**Comment by sortofsleepy** [comment]
👍

**Comment by lolgesten** [comment]
@evanw if/when you do a watch mode, you might want to consider having a switch for it. we use chokidar to trigger esbuild externally, so i can totally do the `time` thing, but i'm also secretly hoping i can one day drop chokidar :)
