### ISSUE TITLE
globalName supported format

### ISSUE THREAD

**Issue by ilijapuaca** [evanw/esbuild#2054]
We are having issue making use of `globalName` while transitioning another one of our projects to `esbuild` from `webpack`. Namely build fails with `Expected identifier but found` when trying to specify a name such as `@foo/bar`, same case passes and works just well when bundling with webpack.

Presumably this has to do with the way global name is attached to the window object? eg. `window.@foo/bar = {}` would throw but `window['@foo/bar'] = {}` would not. I started digging through some of the code in order to verify if that's true and potentially contribute but got quickly lost.

Unfortunately the global name that we use needs to maintain this format as it represents a name of the published package, which is a hard requirement in one of our Jupyter use cases.

**Comment by evanw** [comment]
If you need `globalName` to be `window['@foo/bar']`, why not just set `globalName` to `window['@foo/bar']`? The documentation for `globalName` is here: https://esbuild.github.io/api/#global-name

**Comment by ilijapuaca** [comment]
Maybe I didn't word that well, the global name should be `@foo/bar` so that it can be retrieved from the window object like so `window['@foo/bar']`

**Comment by evanw** [comment]
If you try it, you'd see that it results in the following code:

```js
var window = window || {};
window["@foo/bar"] = (() => {
  // ...
})();
```

The `var window = window || {};` doesn't matter in this case because `window` is always truthy, so you're left with just `window["@foo/bar"] = ...`.

In case you're wondering why esbuild doesn't just store to `window[globalName]` for any value of `globalName`, the reason is because people may want to either assign to `foo.bar` in a way that automatically assigns `foo = {}` if `foo` is undefined, or to assign to `window['foo.bar']` (where the `.` is part of the property name), so esbuild needs to be able to distinguish the two. This is why `globalName` is parsed as a JavaScript expression instead of just being treated as a string that can contain anything (so you have the option of doing it either way). Specifying `foo.bar` as a `globalName` means the former, not the latter. All of this is why you're getting a syntax error when you specify `@foo/bar` as a global name—it's not a valid JavaScript expression.

**Comment by ilijapuaca** [comment]
Got it, thank you for elaborating. Trying this out in an actual production environment is a little bit tricky, but I could've put together a small snippet as you mentioned.

Closing as it works as intended.
