### ISSUE TITLE
`setImmediate` syntax not being transpiled when target is set

### ISSUE THREAD

**Issue by jordanmbell** [evanw/esbuild#2077]
My understanding of the `target` field is that it sets the standard for what the compiled code will turn into as a result of the esbuild run, but I am running into a situation where that does not seem to be working.

If I run: 
`echo "setImmediate(()=>console.log("HERE"))" | ./node_modules/.bin/esbuild --target=chrome98 --loader=js --minify`
It results in: `setImmediate(()=>console.log(HERE));`

However, according to [mozilla](https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate) `setImmediate` is a non standard feature and is not supported on many browsers, and indeed on chrome this code does not run. To work on chrome it would probably have to look like: `setTimeout(()=>console.log(HERE), 0);`

Is it possible to transpile the code in this way, and if not, is it possible to output an error? Otherwise in order to find issues like this and similar in my codebase I would have to try and manually look through the outputted bundle and look for any incompatible syntax.

**Comment by evanw** [comment]
Only JavaScript syntax features are transformed by esbuild. Those need to be handled by a compiler because they cannot be polyfilled. Browser APIs are left alone by esbuild because you can trivially polyfill them yourself. For example:

```js
window.setImmediate = x => setTimeout(x, 0);
```

Closing as out of scope.

> Is it possible to transpile the code in this way, and if not, is it possible to output an error? Otherwise in order to find issues like this and similar in my codebase I would have to try and manually look through the outputted bundle and look for any incompatible syntax.

No. Even if I wanted for esbuild to do this, JavaScript is a dynamic language so there's no way to know for sure which APIs some code will use without running it.
