### ISSUE TITLE
Source map for minified file not working in Safari

### ISSUE THREAD

**Issue by keroxp** [evanw/esbuild#209]
Source mapping for minified file may not be working in Safari.

- esbuild: 0.5.16
- typescript: 3.9.5

**index.ts**
```index.ts
import React from "react"
import { render } from "react-dom"
import { log } from  "./other"
const str = "esbuild"
log(str)
render(React.createElement("div"), document.body)
```

**other.ts**
```other.ts
export function log(a: any) {
  console.trace(a);
}
```

When building bare and minified version of `index.ts`, source mapping for minified version not working in Safari.
Those screenshots show how mapping is wrong (Above is bare, below is minified version).  

Correct line number is `other.ts:2`.  

**Safari**
<img width="749" alt="スクリーンショット 2020-07-01 10 42 51" src="https://user-images.githubusercontent.com/927286/86194188-d44d3f00-bb88-11ea-9043-a4925ff0f131.png">

**Chrome**
<img width="681" alt="スクリーンショット 2020-07-01 10 42 58" src="https://user-images.githubusercontent.com/927286/86194194-d6af9900-bb88-11ea-9f33-236cfc063ad4.png">

I don't understand what happened. Have any idea? 🤔

**Comment by keroxp** [comment]
I realized that rest stack traces are not correctly mapped (in all browsers).  I think source maps for minified file are (partially) incorrect, isn't it?

**Comment by evanw** [comment]
Thanks for bringing this to my attention. I'll try to figure out what's going on. I'm not sure it's as simple as the source maps being wrong because the source map locations all appear to be correct in the actual source map.

It's really weird. The source maps esbuild generates for your example work fine in Firefox, but they don't work in Safari and Chrome. I'm not yet sure if it's a bug in their source map implementations or a problem with how I'm generating source maps.

**Comment by evanw** [comment]
It also works fine for me in Chrome Canary, but not in Chrome, which seems to indicate to me that it's a bug in Chrome that has been fixed. It's unclear if this has been fixed in Safari or not because Safari's nightly builds don't run on my version of macOS.

Here's what I see:

![](https://user-images.githubusercontent.com/406394/86316914-e6f46200-bbe2-11ea-97ca-c2351cf367e5.png)

Can you confirm that this is what you observe too?

1. Wrong in Chrome
2. Correct in Chrome Canary
3. Correct in Firefox
4. Wrong in Safari

**Comment by evanw** [comment]
I did a `git bisect` on the Chrome developer tools code base and https://github.com/ChromeDevTools/devtools-frontend/commit/a10679ba4c5862bac9bb3ca30d2172c94417eafa appears to be the commit that fixed it. It was committed on April 2nd.

**Comment by evanw** [comment]
I'm going to close this because I'm sufficiently confident that this is a bug in Safari, not in esbuild. I have filed the bug with Apple instead: https://bugs.webkit.org/show_bug.cgi?id=213873.

**Comment by keroxp** [comment]
@evanw Thanks!
