### ISSUE TITLE
treeShaking: false don't work in transform api

### ISSUE THREAD

**Issue by Valexr** [evanw/esbuild#2090]
`"esbuild": "^0.14.25"`

`treeShaking: false`

[Repo](https://github.com/Valexr/Slidy/blob/e3e4e32ccd4b6d61665e2a46f819e494f3e03177/packages/svelte/esbuild.js#L120)

```js
import { transform } from "esbuild";

transform(content)
```
stdin
```
import { slidy } from "@slidy/core";
import { Arrow, Image, Pagination } from "./components";
import { clamp as clampValue } from "../helpers/utils";
import "./slidy.module.css";
```

stdout
```
import { clamp as clampValue } from "../helpers/utils";
import "./slidy.module.css";
```

Why removes imports when `treeShaking: false` ?
Or how i can prevent removes any imports in transform api?

**Comment by hyrious** [comment]
This is because `loader: ts` makes esbuild remove "type-like" imports. To preserve them, you have to pass additional tsconfig-raw option `preserveValueImports: true` to it. [see it live](https://hyrious.me/esbuild-repl/?version=0.14.25&mode=transform&input=import+%7B+slidy+%7D+from+%22%40slidy%2Fcore%22%3B%0Aimport+%7B+Arrow%2C+Image%2C+Pagination+%7D+from+%22.%2Fcomponents%22%3B%0Aimport+%7B+clamp+as+clampValue+%7D+from+%22..%2Fhelpers%2Futils%22%3B%0Aimport+%22.%2Fslidy.module.css%22%3B&options=--loader%3Dts+--tsconfig-raw%3D%27%7B%22compilerOptions%22%3A%7B%22preserveValueImports%22%3Atrue%7D%7D%27)

**Comment by Valexr** [comment]
> This is because `loader: ts` makes esbuild remove "type-like" imports. To preserve them, you have to pass additional tsconfig-raw option `preserveValueImports: true` to it. [see it live](https://hyrious.me/esbuild-repl/?version=0.14.25&mode=transform&input=import+%7B+slidy+%7D+from+%22%40slidy%2Fcore%22%3B%0Aimport+%7B+Arrow%2C+Image%2C+Pagination+%7D+from+%22.%2Fcomponents%22%3B%0Aimport+%7B+clamp+as+clampValue+%7D+from+%22..%2Fhelpers%2Futils%22%3B%0Aimport+%22.%2Fslidy.module.css%22%3B&options=--loader%3Dts+--tsconfig-raw%3D%27%7B%22compilerOptions%22%3A%7B%22preserveValueImports%22%3Atrue%7D%7D%27)

Great 👍🏻 @hyrious thanks 🤓
Pretty nice repl - i'm post it in ru-svelte community 👍🏻

**Comment by Valexr** [comment]
solved
