### ISSUE TITLE
Root dir for resources when using absolute paths

### ISSUE THREAD

**Issue by txigreman** [evanw/esbuild#2096]
I would like to set a root directory where the resources are located, and make all absolute path resolve against it. Is that possible?
The only way I've found to achieve this is by using a plugin with an on-resolve callback.

```js
// .esbuild/rootdir.js
const path = require('path');

module.exports = function(rootdir) {
    return {
        name: 'rootdir',
        setup(build) {
            build.onResolve({ filter: /^\// }, args => {
                return { path: path.join(path.resolve(rootdir), args.path) };
            });
        },
    };
}
```
```js
// usage:
const rootdirPlugin = require('./.esbuild/rootdir.js');

esbuild.build({
    // ...
    plugins: [ rootdirPlugin('resources/') ],
};
```

**Comment by evanw** [comment]
This is a good way to handle that, since you are in complete control of the behavior. You could also try a `tsconfig.json` file with a `paths` entry that remaps `/*` to `./resources/*`: https://www.typescriptlang.org/tsconfig#paths. That's another way of remapping paths that is supported by esbuild.

**Comment by txigreman** [comment]
Thanks a lot, I was worried I could be missing some core configuration. I think I'll go with the plugin by now.
