### ISSUE TITLE
Watch mode rebuilds cause touch/update to every output file

### ISSUE THREAD

**Issue by maranomynet** [evanw/esbuild#2104]
Hi. Is there a way to configure Esbuild in watch mode to only touch/rewrite the bundles (output files) that actually changed with the rebuild.

I'd even be willing to sacrifice a bit of speed.

Use case: I'm running a separate [watch task](https://www.npmjs.com/package/onchange) to monitor the contents of the outdir, and perform further actions on the files that changed.

The fact that every output file fires a change-event on every incremental rebuild is making things very busy+slow.

I've done my best to hunt for answers, but to no avail. Any suggestions?

**Comment by evanw** [comment]
This is intentional. After running esbuild, the build outputs should always be newer than the build inputs. Not doing this means build results could appear to be stale, which would be a bug in esbuild.

If you want to change this behavior, you could use [`write: false`](https://esbuild.github.io/api/#write) and then only write out the files that have changed.

**Comment by maranomynet** [comment]
This would be a nice feature, though and more in line with how e.g. Rollup does partial rebuild.

Working with `result.outputFiles` requires maintaining one's own in-memory cache of build results to compare against, and messing with `fs.exists`, `fs.mkdir`, etc.

**Comment by maranomynet** [comment]
I'm still thinking about your claim that all built files should at all times be newer than the source files.

I agree this makes perfect sense after a fresh build.

But I'm not sure I agree this holds in `watch` mode when incremental builds are pretty much the expected outcome — at least in the use-case outlined above.
