### ISSUE TITLE
Esbuild removes curly brackets `{` from files loaded from the file-loader

### ISSUE THREAD

**Issue by StarpTech** [evanw/esbuild#2125]
Hello,
as titled. This is only happening when we use the external pattern `"./node_modules/*"`.

```go
	options := api.BuildOptions{
		Outfile:     b.outFile,
		EntryPoints: []string{b.entryPoint},
		Bundle:      true,
		Incremental: true,
		Platform:    api.PlatformNode,
		fileLoaders:   []string{".handlebar"},
		Format:      api.FormatCommonJS,
		Color:       api.ColorAlways,
		External:    append(b.externalImports, "./node_modules/*"),
		Engines: []api.Engine{
			{Name: api.EngineNode, Version: "12"}, // Maintenance
			{Name: api.EngineNode, Version: "16"}, // LTS
		},
		Write:       true,
		TreeShaking: api.TreeShakingTrue,
	}
```

In typescript, we import the template as follows. This file is provided by an external node_module and used in the entrypoint.

```ts
import handlebar from "./test.handlebar"
const tmpl = Handlebars.compile(handlebar());
tmpl({
  test: "foo"
})
```

template
```
// test.handlebar
export type Role = {{ foo }};
```

esbuild will import the following string

```
export type Role = ;
```

**Comment by evanw** [comment]
I don't know anything about this templating language. But are you sure you didn't mean to do this instead?

```diff
 import handlebar from "./test.handlebar"
 const tmpl = Handlebars.compile(handlebar());
 tmpl({
-  test: "foo"
+  foo: "foo"
 })
```

I'm guessing your templating language replaces things inside `{{ ... }}` and replaces undefined references with the empty string.

**Comment by evanw** [comment]
After taking another look, the code sample in the post isn't even valid code. There's no option in esbuild's `api.BuildOptions` called `fileLoaders`.

I'm closing this issue because I'm assuming this is the result of using Handlebars incorrectly. My guess in my previous comment as to the behavior of Handlebars with undefined references appears to be correct: [(link)](https://handlebarsjs.com/playground.html#format=1&currentExample=%7B%22template%22%3A%22export%20type%20Role%20%3D%20%7B%7B%20foo%20%7D%7D%3B%22%2C%22partials%22%3A%5B%5D%2C%22input%22%3A%22%7B%5Cn%20%20test%3A%20%5C%22foo%5C%22%5Cn%7D%5Cn%22%2C%22output%22%3A%22export%20type%20Role%20%3D%20%3B%22%2C%22preparationScript%22%3A%22%22%2C%22handlebarsVersion%22%3A%224.7.7%22%7D). In that case there is nothing wrong with esbuild.
