### ISSUE TITLE
Trouble loading fonts from fontawesome

### ISSUE THREAD

**Issue by mwillema** [evanw/esbuild#2137]
Hi everyone,

Using Elixir Phoenix and esbuild, I installed fontawesome using NPM in the assets folder. I can properly load the SCSS files, but the fonts do not load. I get the following error: 

`no route found for GET /node_modules/@fortawesome/fontawesome-free/webfonts/fa-solid-900.ttf`

Any idea how could I fix this?

PS: My esbuild config is:
`config :esbuild,
  version: "0.14.0",
  default: [
    args:
      ~w(js/app.js --bundle --target=es2017 --outdir=../priv/static/assets --external:/fonts/* --external:/images/*),
    cd: Path.expand("../assets", __DIR__),
    env: %{"NODE_PATH" => Path.expand("../deps", __DIR__)}
  ]`

Thanks in advance for your help!

**Comment by evanw** [comment]
I have never used Elixir or Phoenix so I'm not going to be able to help you, sorry. You should probably ask them instead. If this was a normal esbuild command, it wouldn't even build in the first place because there's no default loader for `.ttf` files, so there must be some other magic in there that I'm unfamiliar with.

One quick observation: did you mean `@fontawesome` instead of `@fortawesome`?

**Comment by chowey** [comment]
No they use [`@fortawesome`](https://fontawesome.com/docs/web/setup/packages#the-free-package).

**Comment by evanw** [comment]
Oh, I see. It looked like a typo to me.

I'm going to mark this as `unactionable` since there's nothing I can do to help. I don't know anything about Elixir/Phoenix myself. This is probably a better question for them instead.

**Comment by evanw** [comment]
This forum post looks like a better place to debug this than this issue: https://elixirforum.com/t/trouble-loading-webfonts-from-fontawesome-using-esbuild/46851. So I'm going to close this thread in favor of that one. I believe there should be enough flexibility in esbuild's API for Phoenix to solve this without any changes to esbuild.
