### ISSUE TITLE
Using esbuild minifier breaks code 

### ISSUE THREAD

**Issue by surgicaI** [evanw/esbuild#2139]
We are using 1.8.38 version of [gojs](https://www.npmjs.com/package/gojs) library and the library(which is valid javascript code) breaks after minification with esbuild.

Here is repo that can be used to reproduce the issue. Instructions to build and run code can be found in the README file in the repo.
https://github.com/surgicaI/esbuild-gojs-minify-bug

In the above repo, rollup is used to generate javascript bundle from source code and rollup config can be found [here](https://github.com/surgicaI/esbuild-gojs-minify-bug/blob/main/rollup.config.js). Gojs library is used to create diagrams and notice that when the generated javascript bundle is minified using `minify` module from esbuild, the code breaks and no diagram is rendered in the app.

Please look into the issue

**Comment by hyrious** [comment]
This could be caused by [minify-syntax](https://esbuild.github.io/api/#minify). You can turn it off by adding options to the rollup plugin:

```js
minify({
  minifyWhitespace: true,
  minifyIdentifiers: true,
})
```

However it is hard to tell what's wrong in the minified code, `keepNames` does not work too. Searching the source code to see if it uses `eval` or `Function()` also does not give me any clue. We have to investigate it more deeply.

**Comment by evanw** [comment]
Thanks for the report. I've traced it down to this optimization:

https://github.com/evanw/esbuild/blob/2244c09f6abee489158240942871a10807e54800/internal/js_parser/js_parser.go#L9219-L9221

The issue is with if statements of the following form:

```js
if (a)
  b: {
    if (c) {
      break b
    }
  }
else if (d)
  e()
```

That code is incorrectly minified into this:

```js
if (a)
  b:
    if (c)
      break b;
else
  d && e();
```

The problem is that the AST printer doesn't add braces to avoid the inner `if` merging with the outer `else` when the inner `if` is the child of a label. I will change esbuild to print the AST this way instead:

```js
if (a) {
  b:
    if (c)
      break b;
} else
  d && e();
```
