### ISSUE TITLE
Semicolon parsing not consistent with Chrome/NodeJS

### ISSUE THREAD

**Issue by Maxou44** [evanw/esbuild#2143]
Hello

I discovered a bug on esbuild when I use a static array and loop on it using forEach, I got the following error: 
```TypeError: {(intermediate value)(intermediate value)(intermediate value)}[(\\"login\\" , \\"email\\" , \\"password\\")].forEach is not a function```

I use the following code:

![image](https://user-images.githubusercontent.com/8138585/160842092-1d4579e5-3625-4ef4-8bad-2599a2914817.png)

Based on @zloirock feedback, adding a semicolon fixed the issue, but the version without semicolon works on NodeJS runtime and on Chrome, any idea to fix/support it in esbuild?

Have a good day,
Maxime

**Comment by zloirock** [comment]
That's what happens when you don't use a semicolon, lol.

**Comment by Maxou44** [comment]
@zloirock Adding a semicolon fixed the issue, but the version without semicolon works on NodeJS runtime and in Chrome, any idea to fix/support it in esbuild?

**Comment by zloirock** [comment]
It can work only if you evaluate it line-by-line. This is how JavaScript work.

![image](https://user-images.githubusercontent.com/2213682/160847025-91bf077c-8952-4e96-bad2-c2dff55c86ca.png)

It's just an equal of

```js
const x = {}[].forEach
```
so I can't understand anyone who calls to use JS without semicolons - it's like write in English without dots - you will have similar problems.

**Comment by bathos** [comment]
@Maxou44 in case it’s still unclear what’s happening: each time you press enter in the console/REPL, that text is treated as though it were a “script” proper to evaluate. ASI is a kind of error correction algorithm that kicks in only when there _would be_ a syntax error if not for inserting the semicolon (under specific conditions). It can correct the syntax error in _this_ script:

```js
const x = {}
```

...because the token `}` is followed by [end-of-input] and in this position, that wouldn’t be allowed, but a semicolon would be. It “inserts” it hypothetically and everything’s fine.

But there is no syntax error in this next script:

```js
const x = {}
['z'].forEach;
```

The token following the `}` is `[`, which is a valid continuation of that expression. ASI cannot correct the error if it doesn’t exist. The TypeError is because this valid program happens to fail during evaluation. It cannot be determined that that would occur, either, e.g. maybe someone already evaluated this in a prior script: `Object.prototype.z = []`.

**Comment by Maxou44** [comment]
Thanks for your replies 😅
