### ISSUE TITLE
json-merger does not seem to work

### ISSUE THREAD

**Issue by trixobird** [evanw/esbuild#2152]
Hi, new to esbuild, apologies if this is a dump question.

I am trying to get json-merger to work with esbuild. I have created this gist: https://gist.github.com/trixobird/2986080a25da961506de90f57dcc625c

I have two scripts, build and build1. In both cases the error once I run the out.js or out.cjs is the same `Error: Cannot find module '../include/module.js'`

I am sure there are at least another thing that is missing. The settings.yml file in not on the build folder, I assume it has to be there.

**Comment by hyrious** [comment]
Running your build command will print useful warnings:

```js
▲ [WARNING] "esprima" should be marked as external for use with "require.resolve"

    node_modules/jsonpath/lib/aesprim.js:4:27:
      4 │ var file = require.resolve('esprima');
        ╵                            ~~~~~~~~~

▲ [WARNING] "../include/module.js" should be marked as external for use with "require.resolve"

    node_modules/jsonpath/lib/grammar.js:102:58:
      102 │   grammar.moduleInclude = fs.readFileSync(require.resolve("../include/module.js"));
          ╵                                                           ~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] "../include/action.js" should be marked as external for use with "require.resolve"

    node_modules/jsonpath/lib/grammar.js:103:58:
      103 │   grammar.actionInclude = fs.readFileSync(require.resolve("../include/action.js"));
          ╵
```

i.e. `require.resolve(path)` won't be bundled because the resolve function is aimed to be executed at runtime. Changing the semantic of that is wrong for a bundler like esbuild. This results in `../include/*.js` cannot be bundled to the output and the resolving failed because the file path changed.

Generally I'd just recommend you to not bundle dependencies when working on node.js. Simply `--external:json-merger`.

If you do want to bundle that library, you may have a look at the [plugin](https://esbuild.github.io/plugins/) api of esbuild to manually edit codes in the warnings to be bundle-able.

**Comment by trixobird** [comment]
You have been extremely helpful, thank you very much.
