### ISSUE TITLE
Make it possible to add formatting to logs

### ISSUE THREAD

**Issue by amcaplan** [evanw/esbuild#2153]
I have a situation where I'm running multiple simultaneous esbuilds through the JS API, and I'd like to output `info`-level logs with a preface indicating which build is the source of the logs. Something like:

```
[process1]: Starting build
[process2]: Starting build
[process1]: index.js  988.1kb
[process2]: main.js  673.4kb
[process2]: Build completed successfully!
[process1]: Build completed successfully!
```

However, this doesn't seem to be possible, because there's no hook given to format log lines to be printed to the terminal.

While this is actually [very doable](https://github.com/evanw/esbuild/issues/865) for errors and warnings by setting `logLevel` to `silent` and then logging myself, there doesn't seem to be a way to apply a prefix to all log lines on higher levels of logging.

I could of course shell out, but that means dealing with the complexity of turning my options object into CLI options, which would be unfortunate as the JS API already makes it a solved problem.

Is there some existing method I've missed?

If not, is it a feature that would be possible to add by proxying Go output through a customizable JS function?

**Comment by evanw** [comment]
There isn't a built-in way to do this. Even though log messages are always returned from the API, debug and verbose log messages are deliberately not generated when the `logLevel` doesn't cause them to be printed because generating them has non-trivial overhead and would normally slow builds down. I don't think it necessarily makes sense to add support for this to the API as it's a pretty niche and custom use case. Here are some other ideas for you in addition to shelling out:

* You could skip logging debug and verbose log messages. These are only really intended for debugging strange rare build issues and shouldn't normally be needed anyway. You could always manually enable logging them in the rare case that they are actually needed.

* You could use node's [`fork`](https://nodejs.org/api/child_process.html#child_processforkmodulepath-args-options) method to create a child process to run esbuild in, and then send your JS API options object over to the child process using [`send`](https://nodejs.org/api/child_process.html#subprocesssendmessage-sendhandle-options-callback). That should work as long as your options object is serializable.

* You could run each build in serial instead of running them in parallel. Then you could print `[process1]` before the first one and `[process2]` before the second one and the output wouldn't be mixed up in the terminal.

**Comment by evanw** [comment]
Closing this issue as I'm not planning on implementing this within esbuild itself.
