### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by uncle-ara** [evanw/esbuild#2160]
Hello. I'm getting an error: ReferenceError: regeneratorRuntime is not defined
when connecting mongodb. I do not use the babel-loader. 
How can I solve the problem? Thank you.

![image](https://user-images.githubusercontent.com/47677284/162040474-c254fdeb-e7d5-48d5-a0fb-da9e5dbd0ed6.png)

**Comment by evanw** [comment]
This error message is telling you that `regeneratorRuntime` is not defined. Presumably the fix is to define `regeneratorRuntime` before running your code. Note that [esbuild has nothing to do with this](https://github.com/evanw/esbuild/search?q=regeneratorRuntime). This is a problem in your code, not in esbuild. Closing this issue as "invalid" because it's not a problem with esbuild.
