### ISSUE TITLE
Minor suggestion for Serve API docs

### ISSUE THREAD

**Issue by scottdotjs** [evanw/esbuild#2169]
Looking at the Serve docs explaining a proxy, it would be helpful for learners if there were a couple of links to the Node docs. Not being very experienced with Node, on seeing the example my first reaction was to look for `http` on npm (very wrong). Then Node's documentation for `http` didn't make it clear that that HTTPS requires using `https` instead - I did find it, but only after a bit of poking around.

My suggestions:

Old: "Here's a simple example of a proxy server to get you started."
New: "Here's a simple example of a proxy server to get you started, using Node's [`http`](https://nodejs.org/docs/latest-v8.x/api/http.html)."

Old: "Adding support for HTTPS using your own self-signed certificates"
New: "Adding support for HTTPS using Node's [`https`](https://nodejs.org/docs/latest-v8.x/api/https.html) and your own self-signed certificates"

**Comment by evanw** [comment]
Thanks for the suggestion. I have updated the documentation: https://esbuild.github.io/api/#customizing-server-behavior. I decided to link to [node's instructions for setting up a HTTPS server](https://nodejs.org/en/knowledge/HTTP/servers/how-to-create-a-HTTPS-server/) instead of to the [`https`](https://nodejs.org/api/https.html) module because it seemed more concise and useful.

**Comment by scottdotjs** [comment]
Thank you!
