### ISSUE TITLE
Forking esbuild to build an AST plugin tool.

### ISSUE THREAD

**Issue by defensadev** [evanw/esbuild#2172]
Loving working with esbuild! Right now I'm using a parser after bundling to get an AST but I'd ideally like to understand the code to build my own version of esbuild with support for ASTs.

I've read through some of the issues and roadmap and understand that AST's are out of the scope of the project according to issue: [#1880](https://github.com/evanw/esbuild/issues/1880)

To overcome this issue, I've forked esbuild and I'm trying to get a grasp on how the internals of the go code work. I've read through the ["Architecture Markdown"](https://github.com/evanw/esbuild/blob/master/docs/architecture.md) but it didn't go into specifics on things, like how to use the interal js_parser and such. I'm ideally looking for a simple hint to build a modified ***api.Build*** that could take in a plugin like so:

```go
	var astPlugin = api.ASTPlugin{
		Name: "ast-plugin",
		Setup: func(build api.ASTPluginBuild) {
			build.OnResolve(api.OnASTResolveOptions{Filter: `in\.js`},
				func(args api.OnASTResolveArgs) (api.OnASTResolveResult, error) {
					return api.OnResolveResult{
						Path:      args.Path,
						Namespace: "ast-plugin-ns",
					}, nil
				})

			build.OnASTLoad(api.OnASTLoadOptions{Filter: `in\.js`, Namespace: "ast-plugin-ns"},
				func(args api.OnASTLoadArgs) (api.OnASTLoadResult, error) {
					// ast can be used here
				})
		},
	}
```

**Comment by defensadev** [comment]
Also how would I be able to generate an AST using the go modules under "internal", Ideally I can just pass in the source code, but it appears that the js parser takes a lot more complicated options like logger.Log, logger.Source, Options, etc. Is there any good explanations on these args...

**Comment by evanw** [comment]
You’ll have to figure out how to implement this yourself. The internal AST is not designed for this use case at all, and it’s not a use case that I’m going to spend time supporting (so I’m not going to spend time documenting exactly how to do it). I recommend using some other tool if you want to do AST-level stuff, especially because keeping a hack like this working over time as esbuild changes might be a big pain for you. 

If it really want to do this with esbuild, know that the AST is not cleanly abstracted and is only intended for use with esbuild (e.g. uses a lot of internal data structures, has implicit invariants regarding symbols and tree shaking, does some weird things for performance reasons). I’m not going to describe all of the arguments to the parser but you could probably figure them out if you study the code. Log is a message log, Source represents a source file, Options are the parser options, etc. 

Closing this issue because using the AST like this is not the intended use case and is deliberately out of scope.
