### ISSUE TITLE
"import" and WorkDir

### ISSUE THREAD

**Issue by Roffild** [evanw/esbuild#2180]
The file was not added to package.json "exports".
```js
import Swiper1 from "./node_modules/swiper/swiper-bundle.min.js"
```
```console
X [ERROR] Could not resolve "./node_modules/swiper/swiper-bundle.min.js"

    assets/externals0.js:1:20:
      1 │ import Swiper1 from "./node_modules/swiper/swiper-bundle.min.js"
        ╵                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Roffild** [comment]
```js
import Swiper1 from "swiper/swiper-bundle.min.js"
```
```console
X [ERROR] Could not resolve "swiper/swiper-bundle.min.js"

    assets/externals0.js:2:20:
      2 │ import Swiper1 from "swiper/swiper-bundle.min.js"
        ╵                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The path "./swiper-bundle.min.js" is not exported by package "swiper":

    node_modules/swiper/package.json:10:13:
      10 │   "exports": {
         ╵              ^
```

**Comment by evanw** [comment]
But that’s a problem with the package? The `exports` mechanism deliberately provides a way for package authors to prevent a file from being importable (by omission in the map) so esbuild’s behavior here is mandated by the specification of the `exports` field. 

Why did you file this issue with esbuild? Is what esbuild does here incorrect and, if so, how?

**Comment by Roffild** [comment]
> Warning: Introducing the "exports" field prevents consumers of a package from using any entry points that are not defined, including the package.json (e.g. require('your-package/package.json'). This will likely be a breaking change.

https://nodejs.org/api/packages.html

But in many projects, this field is forgotten or considered a recommendation, not a ban.

**Comment by hyrious** [comment]
It is a ban in node side.

**Comment by Roffild** [comment]
Okay, package.json "exports" works fine.

The problem is in determining the working directory for the import.

000.js
```js
import "./node_modules/swiper/swiper-bundle.min.js"
```
```bat
> esbuild --bundle .\assets\000.js --outdir=public
X [ERROR] Could not resolve "./node_modules/swiper/swiper-bundle.min.js"
    assets/000.js:1:7:
      1 │ import "./node_modules/swiper/swiper-bundle.min.js"
1 error
```
```bat
> esbuild --bundle .\000.js --outdir=public
  public\000.js  193.6kb
Done in 18ms
```

I received this error from Hugo, but now it is not reproduced...

**Comment by evanw** [comment]
In JavaScript, imports starting with `./` are relative paths that are relative to the directory containing the file with the import. So for the file `./assets/000.js`, all imports in that file will be relative to `./assets/`. Specifically, an import of `./node_modules/swiper/swiper-bundle.min.js` in `./assets/000.js` will be looking for the file `./assets/./node_modules/swiper/swiper-bundle.min.js`, which appears to not exist in your case.

I'm guessing it should work if you import from `../node_modules/swiper/swiper-bundle.min.js` in the file `./assets/000.js` because then it will be looking for the file `./assets/../node_modules/swiper/swiper-bundle.min.js` which ends up just being `./node_modules/swiper/swiper-bundle.min.js`.

File: **./assets/000.js**

```diff
-import "./node_modules/swiper/swiper-bundle.min.js"
+import "../node_modules/swiper/swiper-bundle.min.js"
```

**Comment by Roffild** [comment]
Now I understand: which of the 1000 and 1 variants was correct...

```bat
> hugo.exe
Error: Error building site: JSBUILD: failed to transform "000.js" (application/typescript):
   Could not resolve "../node_modules/swiper/swiper-bundle.min.js"
```
