### ISSUE TITLE
Is it possible to bundle esbuild in esbuild?

### ISSUE THREAD

**Issue by jeffmcaffer** [evanw/esbuild#2190]
I'm bundling up some tools, one of which is `esbuild`, for easy distribution in a particular environment. I had planned on using `esbuild` itself to do the bundling but am seeing issues where `esbuild` objects to being bundled. I'm happy to make platform specific JS bundles that have `esbuild` embedded somehow in them but am unsure how to make that happen.

To make things a little more complex, I am actually using `module-from-string` which in turn uses `esbuild` to transform and load code for my tools to run. That is, I don't have direct control over how `esbuild` is called/used.

Suggestions?

**Comment by evanw** [comment]
No it's not possible because esbuild is written in Go which compiles to native code, and that needs to be a separate file on the file system for the OS to be able to launch it. You could probably bundle the `esbuild-wasm` package but it would end up being much less efficient than just using the `esbuild` package. If you need a JS transformation tool written in JS, I recommend that you consider using another tool instead (e.g. [Babel](https://babeljs.io/)).

**Comment by jeffmcaffer** [comment]
Thanks for the quick response. I quite like `esbuild` (thanks for doing it) and was thinking about a way of bundling the binary and laying it out on disk when it comes time to run. Anyway, I'll figure out a way to package this all together.
