### ISSUE TITLE
The `build.resolve` API and it's parameters do not seem to have a TypeScript declaration

### ISSUE THREAD

**Issue by doberkofler** [evanw/esbuild#2197]
The `build.resolve` API and it's parameters do not seem to have a TypeScript declaration and Typescript reports an error when using it like in the following example from the esbuild documentation:

```javascript
let examplePlugin = {
  name: 'example',
  setup(build) {
    build.onResolve({ filter: /^example$/ }, async () => {
      const result = await build.resolve('./foo', { resolveDir: './bar' })
      if (result.errors.length > 0) {
        return { errors: result.errors }
      }
      return { path: result.path, external: true }
    })
  },
}

require('esbuild').build({
  entryPoints: ['app.js'],
  bundle: true,
  outfile: 'out.js',
  plugins: [examplePlugin],
}).catch(() => process.exit(1))
```

**Comment by evanw** [comment]
> The `build.resolve` API and it's parameters do not seem to have a TypeScript declaration

That's incorrect. There is a type declaration for `build.resolve`:

https://github.com/evanw/esbuild/blob/1d71dff0ad17522bf9f5fc3e142d41b40c57e525/lib/shared/types.ts#L276-L278

> Typescript reports an error when using it like in the following example from the esbuild documentation:

That's because that example is JavaScript, not TypeScript. If I try that code sample (and enable `"strict": true` in `tsconfig.json`), the TypeScript error I get is this:

```
example.ts:3:9 - error TS7006: Parameter 'build' implicitly has an 'any' type.

3   setup(build) {
          ~~~~~
```

I believe the problem is instead that you are using TypeScript incorrectly. TypeScript's type checker doesn't propagate types backward like that, so `examplePlugin` doesn't pick up any type information from esbuild's type definitions in the code snippet you posted. You can fix this problem in this example by either inlining the definition of `examplePlugin` into the use (in which case type definitions flow naturally from `require('esbuild')`), or by adding a type declaration (which tells TypeScript that `examplePlugin` is an esbuild plugin and not just some unrelated object literal):

```diff
-let examplePlugin = {
+let examplePlugin: import('esbuild').Plugin = {
```

Make sure you are also using a sufficiently new version of esbuild so that you have type definitions for `build.resolve`.

**Comment by doberkofler** [comment]
Thank you for your feedback and sorry for not noticing that the plugin i'm trying to enhance did actually use a old version of esbuild that simply did not yet contain the `build.resolve` api.
