### ISSUE TITLE
import { ReactComponent as LogoHeader } from "./header.svg";

### ISSUE THREAD

**Issue by rickevry** [evanw/esbuild#2217]
With the standard React toolchain we can do the following:

import { ReactComponent as LogoHeader } from "./header.svg";

Unfortunately, it does not work with esbuild.

**Comment by hyrious** [comment]
No, react does not come up with built-in svg component support. It is often provided by plugins. You may have to find out which plugin you've used before and then replicate that in esbuild's [plugin](https://esbuild.github.io/plugins) system.

**Comment by DBBrowne** [comment]
Don't know if there's a policy against recommending specific plugins, but `esbuild-plugin-svgr` solved this for me.

Also had to change the import:
```diff
- import { ReactComponent as Logo } from '../logo.svg';
+ import Logo from '../logo.svg';
```

**Comment by evanw** [comment]
I'm closing this issue as invalid. This is not a part of React: https://www.google.com/search?q=site%3Areactjs.org%20%22import%20ReactComponent%22. As mentioned in the previous comments, a plugin API is available if you want to do something custom like this.

**Comment by rickevry** [comment]
Hi, sorry for the late reply.

The standard React toolchain absolutely support svg. 

Run "npx create-react-app test1--template typescript" and checkout App.tsx:

import React from 'react';
**import logo from './logo.svg';**
import './App.css';

It is not custom, it is how the React starter kit recommends you writing code.

**Comment by hyrious** [comment]
CRA is made up with webpack(bundler) and a huge number of plugins. As you may know esbuild is the bundler, there's no such duty for esbuild to be a CRA-alternative.

IMHO, the "recommended" toolchain is in fact a lie. The react team made CRA to promise you to write react app without knowing anything about bundler or plugins. It may be true on the first sight. However it also forbids you to use other modern tools because they are not "knowing nothing".
