### ISSUE TITLE
Minify css and html tag function

### ISSUE THREAD

**Issue by njfamirm** [evanw/esbuild#2223]
Hello

When I use esbuild to bundle my [lit](lit.dev) component
that's don't minifi css and html tag function

![image](https://user-images.githubusercontent.com/83071310/166559322-37883c43-d82b-409b-9aa3-afcd6c432212.png)

example.ts
```typescript
import {html, css, LitElement} from 'lit';

@customElement('simple-greeting')
export class SimpleGreeting extends LitElement {
  static styles = css`p { color: blue }`;

  render() {
    return html`<p>Hello, ${this.name}!</p>`;
  }
}


```

esbuild.config.js
```javascript
const esbuild = require('esbuild');

const esbuildOptionTypescript = {
  entryPoints: ['sexample.ts'],
  outfile: 'example.js',
  bundle: true,
  minify: true,
  sourcemap: false,
};

esbuild.build(esbuildOptionTypescript);


```

**Comment by hyrious** [comment]
The minification is done by plugins, here's [the related section in lit's doc](https://lit.dev/docs/tools/production/#preparing-code-for-production). To do the same thing in esbuild, you have to replicate that plugin, and it turns out that someone has made one:

https://github.com/bennypowers/lit-css/tree/main/packages/esbuild-plugin-minify-html-literals
https://github.com/bennypowers/lit-css/tree/main/packages/esbuild-plugin-lit-css

**Comment by njfamirm** [comment]
But I don't like import component style from css file and I want write that in csz tag function

**Comment by hyrious** [comment]
Minfying css tag functions seems to be very [difficult](https://github.com/lit/lit-element/issues/696). If you've done this before in other bundlers (like webpack or rollup), you can try to find out how it works and replicate that in esbuild plugin system.

**Comment by njfamirm** [comment]
OK, thank you
