### ISSUE TITLE
Consecutive commands break build time

### ISSUE THREAD

**Issue by gabskoro** [evanw/esbuild#2225]
Couldn't find anyone talking about this weird scenario so I decided to open an issue.

I have the following `esbuild.js` file
```js
require('esbuild')
  .build({
    entryPoints: [
      // My lambdas here
    ],
    outdir: 'dist',
    sourcemap: 'inline',
    sourcesContent: false,
    external: ['dd-trace', 'pg-native'],
    target: 'es6',
    platform: 'node',
    logLevel: 'info',
    minify: true,
    bundle: true,
  })
  .catch(() => process.exit(1));
```

And for testing purposes, I added have two build scripts in my`package.json` file
```json
"script": {
  "build": "node ./esbuild"
  "build2": "node ./esbuild && yarn otherLongRunningScript"
}
```

If I run the first command `yarn build`, I will get something like
```
$ node ./esbuild

  dist/someFunction.js              10.8mb ⚠️

✨  Done in 1.12s.
```

But If I run the second command `yarn build2`, I will get something like
```
$ node ./esbuild && yarn otherLongRunningScript

  dist/someFunction.js              10.8mb ⚠️

Output from the other script
...

✨  Done in 23.12s.
```

And now the `Done in` shows the complete timeframe it took for the whole script to execute, not only for the esbuild process which is actually what I expected. Any idea how to avoid that? tnx :)

**Comment by davezuko** [comment]
That "Done in" is printed by yarn and returns the total time to execute the entire package.json script. So, this issue doesn't really concern esbuild itself. Nonetheless, there are a number of ways to get just the build time:

1. Time and log it yourself in `build.js`.
2. Run `yarn build && yarn otherLongRunningScript` directly without the wrapper `build2` script. Since these are two distinct and non-recursive yarn invocations you'll see the execution time for each.
3. Use the `time` script, e.g. `time node ./esbuild && yarn otherLongRunningScript`
4. etc.

You may want to refer to https://github.com/yarnpkg/yarn/issues/4423

**Comment by gabskoro** [comment]
Oh, didn't realize that. Tnx! ended up doing the following

```js
console.time('esbuild done in');
require('esbuild')
  .buildSync({
    entryPoints: [
      // My lambdas here
    ],
    outdir: 'dist',
    sourcemap: 'inline',
    sourcesContent: false,
    external: ['dd-trace', 'pg-native'],
    target: 'es6',
    platform: 'node',
    logLevel: 'info',
    minify: true,
    bundle: true,
  });
console.timeEnd('esbuild done in');
```

Works for me 👍🏻
