### ISSUE TITLE
Performance guidelines

### ISSUE THREAD

**Issue by rob-lattice** [evanw/esbuild#2228]
I'm interested in understanding if there's anything I can do in my code, or project organization, or `tsconfig.json` (as examples), to speed up compile times. I'm mostly interested in improving the development edit/compile/run cycle.

Does the esbuild project provide performance tips similar to [this Microsoft page](https://github.com/microsoft/TypeScript/wiki/Performance)? I've reviewed the esbuild FAQ, as well as the architecture document in this repo, but I'm not sure how to know whether my project could better leverage esbuild's capabilities.

**Comment by hyrious** [comment]
esbuild is much faster than rollup/webpack/babel, etc. I don't think you need worrying about performance at the most of the time.

There could be performance impact from process communications (go ↔ js) which is mostly seen in plugins. You'd better specify a good `filter` option to reduce that.

**Comment by evanw** [comment]
If an esbuild-based build system is slow, it's almost certainly due to JavaScript plugins and not due to esbuild itself. Generally the fewer times a JavaScript-based esbuild plugin runs, the faster your build will go. This is both due to the IPC overhead and because esbuild is multi-threaded while JavaScript is single-threaded. For example, if you can use esbuild's native `tsconfig.json` support for transforming paths instead of using a plugin, then your build will go much faster.

There are other things you can do to increase performance somewhat, but they typically won't be that big a win. For example, generating more output is slower than generating less output, so you can turn off source maps if you don't need them or turn on minification if you don't need to read the source so that less output is generated. You can also do some form of incremental builds (either watch mode, serve mode, or using the incremental build API) to get another modest speed improvement. This avoids re-parsing files whose contents haven't changed (but still always does all of the other steps).

Closing this issue as it's not a problem with esbuild.
