### ISSUE TITLE
Component reference in jsx

### ISSUE THREAD

**Issue by rmannibucau** [evanw/esbuild#2242]
Hi,

Not sure it is intended but using esbuild-jest (didn't test with plain esbuild but esbuild-jest does nothing about it) I didn't manage to get component reference working:

````
const MyComponent = ({value}) => (<div>{value}</div>);
const registry = { 'test': MyComponent };
const MyOtherComponent = ({componentName, componentConfiguration }) => {
  const component = registry[componentName];
  return <component {...componentConfiguration} />;
};

// i'm using preact but with react it would be the same
// render(<MyOtherComponent componentName="test" componentConfiguration={{value:"some value"}} />)
````

Expected behavior is that `<component/>` line behaves exactly as `jsxFactory(component, options, children)` - which is my workaround using preact `h` factory directly - but it actually renders as `<component/>`.

**Comment by evanw** [comment]
The React team has decided that JSX component names that start with a lowercase letter are considered strings while JSX component names that start with an uppercase letter are considered variable references. This is arbitrary but it's how they decided JSX should work. This is documented here, and is something you must be aware of when using JSX: https://reactjs.org/docs/jsx-in-depth.html#user-defined-components-must-be-capitalized.

Closing this issue as invalid because esbuild is behaving correctly here.

**Comment by rmannibucau** [comment]
For reference the same actual documentation for preact is there: https://preactjs.com/guide/v10/components/#functional-components.

Side note being I didn't find this reference in JSX spec itself - https://facebook.github.io/jsx/#prod-JSXIdentifier.

That said thanks for the answer, helped to see this particular issue.
