### ISSUE TITLE
Sourcemap extension for .jsx

### ISSUE THREAD

**Issue by joelmoss** [evanw/esbuild#2251]
Setting `sourcemap` to `linked` produces a sourcemap file ending with `.js.map` even if the entrypoint ends with `jsx`.

Surely the sourcemap file should end with `.jsx.map` instead of `.js.map`?

**Comment by hyrious** [comment]
Sourcemap is linked to the **output** file. i.e. a.jsx &rarr; a.js, a.js.map So that browsers can read the url to sourcemap from a.js and load that file. The filename actually does not matter because there is `sources` field in the sourcemap contents.

**Comment by evanw** [comment]
The above comment is accurate. The extension is meaningless anyway and is `.js.map` by convention, since the output file ends in `.js` and the source map goes with the output file.

In addition, you can change the output extension to `.jsx` instead of `.js` if you really need it to be that way: https://esbuild.github.io/api/#out-extension. Just use `--out-extension:.js=.jsx` or the equivalent JS API configuration. That may cause problems with other tools that are expecting the `.js` extension (such as a web server) but I suppose it could make sense to do this if you're also using [`--jsx=preserve`](https://esbuild.github.io/api/#jsx).

Closing this issue as invalid.

**Comment by evanw** [comment]
Well the more serious issue would be that your JavaScript output files would collide in that case, since the resulting JavaScript files would both be called `component.js`. This is prevented if you process both `component.js` and `component.jsx` with one esbuild command (esbuild should generate the error `Two output files share the same path but have different contents` and refuse to build) but this isn't prevented if you use separate esbuild commands for each file.

I recommend avoiding having both `component.js` and `component.jsx` in the same directory. It's confusing and asking for trouble, especially since `component.js` is the default output name of compiling `component.jsx`. But it should work if they are in separate input directories because esbuild will recreate the output hierarchy in the output directory. For example, if the input files are `a/component.js` and `b/component.jsx` then esbuild will generate `outdir/a/component.js` and `outdir/b/component.js` in the output directory. Then it doesn't matter that there are two files called `component.js` (and two files called `component.js.map` if source maps are enabled) because they are in separate directories.

**Comment by joelmoss** [comment]
I suppose it's a non-issue in real life. ;)

thx again!
