### ISSUE TITLE
"use strict" not being emitted automatically if needed breaks code

### ISSUE THREAD

**Issue by fabiospampinato** [evanw/esbuild#2264]
Long story short esbuild is not emitting `"use strict";` while Vite is, even if I point it to my "tsconfig.json" with "alwaysStrict" in it.

IMO this is a really bad default that breaks code in subtle ways.

For my sample project I'm basically getting this with esbuild:

```js
function self () {
  return this;
}

const bind = self.bind.bind ( self );
const value = bind ( '123' )();

console.log ( value );
console.log ( typeof value );
```

But this with Vite:

```js
'use strict';

function self () {
  return this;
}

const bind = self.bind.bind ( self );
const value = bind ( '123' )();

console.log ( value );
console.log ( typeof value );
```

And for whatever _insane_ reason outside of strict mode this code outputs a String object, while in strict mode it outputs a string primitive.

Outputting the strict mode directive IMO is just a much better default, nobody should be using sloppy mode anyway really.

Also it's unclear how well the banner workaround works, potentially I could be using multiple plugins each setting their own strict mode directive? Maybe some other plugin could override my plugin's request to use strict mode? It just doesn't make a lot of sense to me to use `banner` for this. If anything this should be opt-out not opt-in.

Sample project: 

[voby_bug.zip](https://github.com/evanw/esbuild/files/8766863/voby_bug.zip)

**Comment by evanw** [comment]
I think there are a few different things here:

* The `"use strict"` directive is duplicated twice in ESM output. This is just an oversight. I didn't think to test this because `"use strict"` is irrelevant in this case (since ESM always implies strict mode). Arguably it shouldn't ever be inserted at all for ESM output. It's easy to fix the duplicate one, so I can do that.

* There is a request for `"use strict"` to always be generated. I disagree that this is a good idea. Right now the presence of `"use strict"` in the output is determined by the presence of `"use strict"` in the entry point file. I think that's the most straightforward way to control this behavior, so I'm planning to keep it this way.

* There is a request for esbuild to respect `alwaysStrict` in `tsconfig.json`. It's not expected that this should work because esbuild only supports a subset of `tsconfig.json` options: https://esbuild.github.io/content-types/#tsconfig-json. But that's a reasonable request, and I can see it making sense for esbuild to support this option.

**Comment by curiousdannii** [comment]
"use strict" shouldn't be emitted if the format is ESM, because ES modules are always strict.

**Comment by fabiospampinato** [comment]
@curiousdannii Are you seeing a `"use strict"` being added to your build as a result of having the `"alwaysString"` option in tsconfig.json? 

The problem with reverting this change is that you as the library author are assuming that your code is running under strict mode, because you are outputting an ESM module, but once the user gets to actually execute your code that may no longer be the case, depending on the bundler used, I guess.

**Comment by curiousdannii** [comment]
Yes, `"use strict"` started to be added because my tsconfig.json has `"strict": true`.

If someone is doing additional bundling after esbuild, then it's their responsibility to ensure they're bundling it correctly. I don't see why esbuild should add an unnecessary pragma just in case someone bundles it incorrectly. If esbuild tried to protect against anything that could possibly be misconfigured then it would cease being a very efficient minifier!

**Comment by unilynx** [comment]
I'm running into an issue which seems to be related to this (or might not be?)

i'm switching from `tsc` to `esbuild` (actually, a fork of esbuild-runner to replace ts-node) and a test that worked under ts-node now fails because esbuild isn't emitting "use strict" - which causes frozen (Object.freeze) properties to no longer throw. 

I'm unclear as to whether adding strict/alwaysStrict to tsconfig should have fixed it. If it should, I'll investigate further.

For now the banner workaround in https://github.com/evanw/esbuild/issues/2264#issuecomment-1136957422 fixes this case for me, but it feels a bit ugly :)
