### ISSUE TITLE
output does not contain all imports

### ISSUE THREAD

**Issue by MoritzLoewenstein** [evanw/esbuild#2307]
I am pretty sure I am missing something, but heres my problem:
```js
// a.js
import "./b.js"
// b.js
function sum(a, b) {
  return a + b;
}
// build.js
import esbuild from "esbuild";
esbuild.buildSync({
  entryPoints: ["a.js"],
  treeShaking: false,
  minify: false,
  bundle: true,
  outfile: "out.js",
});
// out.js
(() => {
})();
```

I am just trying to achieve this: " To join a set of files together with esbuild, import them all into a single entry point file and bundle just that one file with esbuild.".
I tried to add sideEffects: ["*.js"] to package.json, but it didnt change anything.
If this is the expected behaviour, can I preserve the function from b.js in the output with other available options?

**Comment by evanw** [comment]
You have encountered "tree shaking" also known as "dead code removal." There is no observable difference between this code:

```js
(() => {
  function sum(a, b) {
    return a + b;
  }
}();
```

and this code:

```js
(() => {
})();
```

so during bundling, esbuild automatically omits the dead code for you. If you want `sum` to be present in the output, you'll have to use it somehow. You should either call it or export it so that some other code can call it.

Note that all three of [esbuild's output formats](https://esbuild.github.io/api/#format) (`iife`, `cjs`, `esm`) are some form of module that encapsulates local unexported state. There is no "global" output format that automatically exposes exports as properties on the global object. Which output format you choose depends on how the output file will be used.

**Comment by evanw** [comment]
Closing this issue as out of scope. It's deliberate that esbuild only supports non-global module-oriented output formats.
