### ISSUE TITLE
Feature Request: Minify/Mangle class properties with `private` keyword

### ISSUE THREAD

**Issue by muzuiget** [evanw/esbuild#2313]
Currently esbuild has a "annotation comment" feature, like `/* @__PURE__ */` for functions.

Can esbuild add a new annotation comment for class properties, mark the property it can be safe to minify/mangle?

```javascript
class {
    constructor() {
        this.initial();
    }
    /* @__PRIVATE__ */ initial() {
    }
}
```

An the Typescript access modifiers `private` keyword implies this meaning:

```typescript
class {
    public constructor() {
        this.initial();
    }
    private initial() {
    }
}
```

**Comment by hyrious** [comment]
IMHO, the `private` keyword does not always mean <q>mangle-able</q>, it is just a type annotation that does not want users to use it (which means you can still use it when you're for example debugging, in which case you may not want it to be mangled).

I'd suggest you to use the existing [mangle](https://esbuild.github.io/api/#mangle-props) api of esbuild to manually write these props in the form like `xxx_`.

**Comment by muzuiget** [comment]
> the private keyword does not always mean "mangle-able"

We can only mangle them in the "minifiy" step. Currently we already know minify/tree-shaking the code may breaking somethings, like the function's `this` and `toString()`.

**Comment by muzuiget** [comment]
So maybe `mangleProps` accept a object as configuration?

```
mangleProps: {
    modifiers: 'private',
}
```

So we can mark a property name is mangle-able inline, we don't need to do a globle including or excluding with regexp.

**Comment by evanw** [comment]
Name mangling has to be global, not on the property of a type, because TypeScript's type system is advisory only and fundamentally (and deliberately) unsound. Doing what you suggested is not safe.

Furthermore, esbuild only added support for `/* @__PURE__ */` annotations for compatibility with the existing conventions in the minifier ecosystem (which originated from Uglify). I don't think esbuild should be one to innovate in this space and diverge from the way the existing ecosystem works. So I'm not planning to do what you are suggesting.

**Comment by muzuiget** [comment]
All right, I understand.

**Comment by evanw** [comment]
I'm closing this issue since I do not plan to do this.
