### ISSUE TITLE
deno-esbuild: A request for WebAssembly support

### ISSUE THREAD

**Issue by johnspurlock** [evanw/esbuild#2323]
I'd like to be able to run esbuild transform in a Deno program, but using a loaded wasmModule (e.g. instantiated in Deno with `WebAssembly.compileStreaming` from a fetch response from `https://unpkg.com/esbuild-wasm@0.14.43/esbuild.wasm`).

tried:
```ts
await initialize({ wasmModule }); // does not throw
await transform(code, { target: 'es2019' }); // still requires run access to the esbuild binary in the deno cache, if denied, throws (does not use wasm)
```

It seems like this _should_ be able to work, given Deno has the wasmModule loaded.

Thanks!
\- John

**Comment by evanw** [comment]
The Deno API is not built to use WASM at all, so this isn't supposed to work anyway. The only reason doing this doesn't throw an error right now is that the `wasmModule` API option is a newer addition (#2155) and I forgot to add code to throw here when this option is passed. I'll fix this to make it throw.

Why do you want to use WebAssembly instead of native? It can easily be 10x slower.

**Comment by evanw** [comment]
I tried poking at this and it seems relatively straightforward. Caveats:

* It wouldn't have file system support just like esbuild's browser-based API. Getting file system support is possible of course but would be additional work.

* There are two options for loading WASM in Deno: reading it from the file system and downloading it from the internet. One needs `--allow-read` and one needs `--allow-net`. I assume I should be downloading it from the internet since that's how Deno does dependencies? Not sure because I don't use Deno myself.

* Deno appears to have a severe WebAssembly performance bug where it hangs for 15 seconds on exit, spinning at 100% CPU. I'm assuming that this is Deno blocking exit on finishing WASM compilation even though it's irrelevant, since node has the same bug and they both use V8. In that case using esbuild's WASM implementation in Deno for short operations will be extremely inefficient due to this Deno bug.

    Long story is that V8 has a two-tiered JIT for WASM. WASM can start running with the low tier, and may even finish running completely. The high tier is supposed to only be for long-running applications that need optimal performance. You can read more about this architecture here: https://v8.dev/docs/wasm-compilation-pipeline. IMO after the application has exited Deno shouldn't be waiting for the high tier to finish compiling.

    Node has the same bug: https://github.com/nodejs/node/issues/36616. My ugly hack to "fix" this in node for the CLI version of esbuild's WASM implementation is to load a native node extension on exit that invokes the [`_exit` syscall](https://man7.org/linux/man-pages/man2/_exit.2.html) directly, which bypasses node's lifecycle code:

    https://github.com/evanw/esbuild/blob/698898f86615a69f52d2e00681a13fe2b8635e88/npm/esbuild-wasm/bin/esbuild#L26-L63

    I'm guessing there's nothing like that for Deno, and even if there was that you may not want to use it since it's quite the hack. I assume this bug doesn't matter if you're using Deno in a long-lived context, since the WASM compilation should be finished by the time you want to exit.

**Comment by johnspurlock** [comment]
Re: loading interface - the [deno_emit](https://github.com/denoland/deno_emit) wasm module has a way to provide a [custom loader function](https://github.com/denoland/deno_emit/blob/84014a247fd9fd572860a5776b4015a5838f7f72/mod.ts#L83), which is basically: 

```ts

type Loader = (spec: string) => Promise<LoadResponseModule>;

interface LoadResponseModule {
    /** A module with code has been loaded. */
    kind: 'module';
    /** The string URL of the resource. If there were redirects, the final
     * specifier should be set here, otherwise the requested specifier. */
    specifier: string;
    /** For remote resources, a record of headers should be set, where the key's
     * have been normalized to be lower case values. */
    headers?: Record<string, string>;
    /** The string value of the loaded resources. */
    content: string;
}
```

I've been working on getting the emit wasm running on Deno Deploy (see [bundle.deno.dev](https://bundle.deno.dev/)), and it appears to be working, although a much smaller library than esbuild.

To me though, while running a future esbuild wasm on an edge platform would be cool, just being able to run it locally without needing the process permission would be very useful as well.
