### ISSUE TITLE
Not possible to reserve top-level identifiers during minification

### ISSUE THREAD

**Issue by knaccc** [evanw/esbuild#2338]
cache.json:
```json
{ "Apple": false, "banana": false }
```

test.js:
```js
class Apple {
  banana() {}
}
```

`esbuild --minify-identifiers --format=esm --mangle-props=".*" --mangle-cache=cache.json test.js` output:
```js
class p {
  banana() {
  }
}
```

Please could you consider making it possible to prevent `Apple` from being minified, either via `--mangle-cache` or via e.g. a `--reserve-identifiers=` flag?

**Comment by evanw** [comment]
Could you say more about your use case? Are you perhaps trying to use esbuild for some custom module format that doesn't work like standard JavaScript? That's not something that esbuild is intended to be used for.

**Comment by knaccc** [comment]
@evanw Sure, it's just a simple web app where the Javascript is a bunch of top-level classes and functions that do all sorts of complicated UI presentation of data. The web server loads some data from a database, and writes a <script> into the HTML that looks something like this:

```js
let data = new CustomObject({<data from database, perhaps with a tree of further class instantiations>});
init();
```

Therefore I use terser's `--top-level` option so that tha vast majority of class and function identifiers are minified, but a small number of identifiers such as the `CustomObject` class name will be reserved.

**Comment by evanw** [comment]
I'm not going to support this because I don't think it's a good idea. Probably the most insidious bug I've ever had to deal with was one where a minified variable in our code collided with the global `ga` Google analytics variable and caused a rare timing-dependent loading failure. Ensuring top-level variables were wrapped in their own scope removes this entire class of bugs.

**Comment by arcanis** [comment]
Fwiw I have a problem where Esbuild is mangling `Worker`, preventing it from being detected by subsequent Webpack invocations (required to turn the ESM code into traditional web bundles). Being able to disable mangling of some identifiers would be handy when static analysis is involved.

**Comment by bhuynhdev** [comment]
Sorry to resurrect the issue, but I'm trying to use `esbuild` to minify some legacy JavaScript code, where the file will be included via `<script src=...`> tags (not modules), and so function declarations would be merged into the global scope to be used anywhere.

Example function
```js
function honk(message, honkTimes) {
  alert("Honk", message, `for ${honkTimes}`)
}

// In HTML somewhere else
<script src="/js/honk.js">
<button onclick="honk('Hello',3)">HONK</button> 
```
As a result, I'd like to have the top-level function name `honk` unchanged, but the argument name inside the function to be minified. I have tried setting `minifyIdentifiers: false`, and while that leave `honk` as is, it didn't minify the argument names.

Is this use case not expected.

**Comment by evanw** [comment]
> As a result, I'd like to have the top-level function name `honk` unchanged, but the argument name inside the function to be minified. I have tried setting `minifyIdentifiers: false`, and while that leave `honk` as is, it didn't minify the argument names.

That seems to work for me: https://esbuild.github.io/try/#dAAwLjI1LjkAewogIG1pbmlmeUlkZW50aWZpZXJzOiB0cnVlLAp9AGZ1bmN0aW9uIGhvbmsobWVzc2FnZSwgaG9ua1RpbWVzKSB7CiAgYWxlcnQoIkhvbmsiLCBtZXNzYWdlLCBgZm9yICR7aG9ua1RpbWVzfWApCn0. That minifies to this:

```js
function honk(n, o) {
  alert("Honk", n, `for ${o}`);
}
```

Anything you're doing differently from that?

**Comment by bhuynhdev** [comment]
@evanw Wow thank you very much for the extremely fast response. You're right!! I was wrong. Yesterday, I tried different `format` configuration to achieve what I wanted and accidentally used `format: 'esm'` because I thought that was Esbuild's default value. Turns out if I just don't specify any format (and turn off bundling), esbuild won't try to do format conversion, and that's what I wanted. Thank you very much, my pain point is resolved. Lesson learned: I should have used the web version.
