### ISSUE TITLE
Bundling for Rhino?

### ISSUE THREAD

**Issue by gausie** [evanw/esbuild#2357]
I'd be very interested in using esbuild to build and bundle code for running with [Rhino](https://github.com/mozilla/rhino). In pursuing the same goal with babel in the past, we've got all the necessary information into compat-table. Obviously I am aware that it would serve only a very small minority of the userbase. Would you in theory accept a PR allowing rhino as a target?

**Comment by evanw** [comment]
You should be able to do this for yourself using the new `supports` feature. It was just released so the documentation hasn't been updated yet, but it's described in the release notes here: https://github.com/evanw/esbuild/releases/tag/v0.14.46. You can mark anything in that list which Rhino doesn't support with e.g. `--supported:bigint=false` and that will have the same effect as what you're asking for, but without any changes to esbuild.

**Comment by evanw** [comment]
> it's not so simple for usage as adding a Rhino target.

I'm not sure what you're saying, sorry. Are you saying that disabling esbuild features that aren't supported in Rhino is too hard and not something that you think users of esbuild should be doing? Or are you warning me that having esbuild support Rhino isn't as simple as trusting the data in compat-table for Rhino (potentially because the data is incomplete and/or incorrect)?

**Comment by zloirock** [comment]
I just said that for a simple user to form a list of features that Rhino supports is much harder than just to write `target: ['rhino1.7.14']`. The compat table data for Rhino were added to make the same thing for Babel, so it's OK.

**Comment by gausie** [comment]
Amazing, thanks both!
