### ISSUE TITLE
Unused Node built-in modules tree-shaken despite tree-shaking disabled

### ISSUE THREAD

**Issue by privatenumber** [evanw/esbuild#2367]
## Description
When setting the loader to `ts`, unused built-in Node.js modules get tree-shaken. Even with `--tree-shaking` force disabled.

[Reproduction](https://hyrious.me/esbuild-repl/?version=0.14.48&mode=transform&input=import+a+from+%27fs%27%3B%0Aimport+a+from+%27path%27%3B&options=--loader%3Dts+--tree-shaking%3Dfalse)

[(Doesn't tree-shake with `js` loader.)](https://hyrious.me/esbuild-repl/?version=0.14.48&mode=transform&input=import+a+from+%27fs%27%3B%0Aimport+b+from+%27path%27%3B&options=--loader%3Djs+--tree-shaking%3Dfalse)

## Expected behavior
For it to be left untouched. If minification and tree-shaking are both disabled, unused code should be left intact.

## Use-case
For the TS Repl in [tsx](https://github.com/esbuild-kit/tsx), when passing in `import fs from 'fs'` (invalid input), it doesn't error because esbuild removes it.

**Comment by hyrious** [comment]
The removal is because esbuild strips maybe-type-names in ts context to prevent it become a runtime error. The behavior is [the same as typescript](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAQTgMyhEcBEBDTAoIA). To preserve that import, you have to enable `preserveValueImports` in tsconfig: [repl](https://hyrious.me/esbuild-repl/?version=0.14.48&mode=transform&input=import+a+from+%27A%27%3B&options=--loader%3Dts+--tsconfig-raw%3D%27%7B%22compilerOptions%22%3A%7B%22preserveValueImports%22%3Atrue%7D%7D%27).

**Comment by privatenumber** [comment]
Ahh, glad it wasn't a bug. Thank you very much @hyrious for the quick & careful explanation and solution!
