### ISSUE TITLE
How to remove wrapper function in IIFE

### ISSUE THREAD

**Issue by Yash-Singh1** [evanw/esbuild#2368]
I am compiling to the AppScript environment and they require that all functions be declared in the top-level:

```js
function onInstall() {
    console.log('Addon installed!');
}
```

Currently if I try to import something and bundle with the `--bundle` flag, esbuild will give me something along the following:

**INPUT**

```ts
import logger from './helpers/logger.ts';

function onInstall() {
    logger('Hello World');
}
```

**OUTPUT**

```ts
"use strict";
(() => {
  // helpers/logger.ts
  function logger(...args) {
      // log...
  }

  // Code.ts
  function onInstall() {
    logger('Hello World');
  }
  
})();
```

What I want is something like this:

```js
// helpers/logger.ts
function logger(...args) {
    // log...
}

// Code.ts
function onInstall() {
  logger('Hello World');
}
```

Is this currently possible with bundling all the code into a single file in esbuild?

**Comment by hyrious** [comment]
I don't know what kind of top-level functions that AppScript could recognize, for example, can it find out these special names from re-assignment?

```js
var MyModule = (() => {
	function onInstall() {}
	return { onInstall }
})();
var onInstall = MyModule.onInstall // <--
```

If it can, then you can use the [globalName](https://esbuild.github.io/api/#global-name) option to do so. You can use [esm-module-lexer](https://github.com/guybedford/es-module-lexer) to get exported names from a single file. (hint: use the transform api first to convert ts into js)

If it cannot, which means it must see a top-level `function xxx()`, you can try use `format: "esm"` with `treeShaking: false`: [repl](https://hyrious.me/esbuild-repl/?version=0.14.48&mode=build&modules=%5B%5B%22main.js%22%2C%22import+%7Blog%7D+from+%27.%2Flogger%27%5Cn%5Cnfunction+onInstall%28%29+%7B%5Cn%5Ctlog%281%29%5Cn%7D%22%2C1%5D%2C%5B%22logger.js%22%2C%22export+function+log%28%29+%7B%7D%5Cn%5Cnexport+function+onInstall%28%29+%7B%5Cn%5Ct%5C%22name+conflict%21%5C%22%5Cn%7D%22%2C0%5D%5D&buildOptions=%7B%22bundle%22%3Atrue%2C%22format%22%3A%22esm%22%2C%22treeShaking%22%3Afalse%7D), but be careful that esbuild can rename any name since the environment is ESM and all names not exported are seen as safe to rename.

**Comment by Yash-Singh1** [comment]
> I don't know what kind of top-level functions that AppScript could recognize, for example, can it find out these special names from re-assignment?
> 
> ```js
> var MyModule = (() => {
> 	function onInstall() {}
> 	return { onInstall }
> })();
> var onInstall = MyModule.onInstall // <--
> ```
> 
> If it can, then you can use the [globalName](https://esbuild.github.io/api/#global-name) option to do so. You can use [esm-module-lexer](https://github.com/guybedford/es-module-lexer) to get exported names from a single file. (hint: use the transform api first to convert ts into js)
> 
> If it cannot, which means it must see a top-level `function xxx()`, you can try use `format: "esm"` with `treeShaking: false`: [repl](https://hyrious.me/esbuild-repl/?version=0.14.48&mode=build&modules=%5B%5B%22main.js%22%2C%22import+%7Blog%7D+from+%27.%2Flogger%27%5Cn%5Cnfunction+onInstall%28%29+%7B%5Cn%5Ctlog%281%29%5Cn%7D%22%2C1%5D%2C%5B%22logger.js%22%2C%22export+function+log%28%29+%7B%7D%5Cn%5Cnexport+function+onInstall%28%29+%7B%5Cn%5Ct%5C%22name+conflict%21%5C%22%5Cn%7D%22%2C0%5D%5D&buildOptions=%7B%22bundle%22%3Atrue%2C%22format%22%3A%22esm%22%2C%22treeShaking%22%3Afalse%7D), but be careful that esbuild can rename any name since the environment is ESM and all names not exported are seen as safe to rename.

That sounds like a good idea and it seems to work in the AppScript Editor! I'll try implementing that.

**Comment by magic-akari** [comment]
Awesome esbuild playground!
I have played with it.

It's easy to export a gloabal name.

[playground link](https://hyrious.me/esbuild-repl/?version=0.14.48&mode=build&modules=%5B%5B%22main.ts%22%2C%22import+logger+from+%27.%2Flogger.ts%27%3B%5Cn%5Cnexport+%3D+function+%28%29+%7B%5Cn++++logger%28%27Hello+World%27%29%3B%5Cn%7D%22%2C1%5D%2C%5B%22logger.ts%22%2C%22export+default+function+onInstall%28%29+%7B%5Cn++++console.log%28%27Addon+installed%21%27%29%3B%5Cn%7D%22%2C0%5D%5D&buildOptions=%7B%22bundle%22%3Atrue%2C%22globalName%22%3A%22onInstall%22%2C%22format%22%3A%22iife%22%2C%22treeShaking%22%3Afalse%7D)

**Comment by evanw** [comment]
I'm going to close this issue because I consider it to be out of scope. Restricting JavaScript to only top-level functions means it's no longer JavaScript (i.e. it doesn't follow the JavaScript specification) and so is not something esbuild will have built-in support for.

I agree that setting the output format to `esm` and disabling tree shaking is as close as you'll be able to get with esbuild. It's not a general-purpose solution because setting the output format to `esm` tells esbuild that it can assume that the output will be running as an ES module, which it sounds like isn't actually true in your case. So esbuild will assume that renaming non-exported functions is safe (since it's safe when the output is run as an ES module) and may rename some functions if they have the same name as other identifiers. The workaround in that case would be to just not reuse the names of important top-level functions for other unrelated identifiers.
