### ISSUE TITLE
write:false with multiple entry points

### ISSUE THREAD

**Issue by mehulkar** [evanw/esbuild#2378]
I'm trying to setup esbuild to bundle JS entry points in an 11ty project. The idea is to use an 11ty template to "render" built JS from entry points. This approach is described in https://www.raresportan.com/eleventy-part-five/.

This is the config used to build the JS:

```js
const result = await esbuild.build({
  entryPoints: ['src/js/foo.js', 'src/js/bar.js'],
  format: "iife",
  bundle: true,
  minify: true,
  write: false, // returns output in result, instead of printing to stdout
});
```

The `write: false` is important here because we don't want esbuild to write to a file, we just want to get the output, so 11ty can "render" it into a file as part of its template compilation.

Anyway, it seems that esbuild requires an `outDir` when there are multiple entry points. 

```
✘ [ERROR] Must use "outdir" when there are multiple input files
```

Why is that? With a single entry point, I see the resulting file in `result.outputFiles[0].contents`, so presumably, `outputFiles` is setup to hold the compiled output of each entry point?

**Comment by hyrious** [comment]
Because when there's only one entry point, esbuild set the outfile name (`result.outputFiles[0].path`) as `"<stdout>"`. This behavior cannot be applied to multiple entries where the output path must be calculated from entry names and outdir.

It is safe to set `outdir` with `write: false`, esbuild won't actually write things out, it is used to generate the paths of output files.

**Comment by evanw** [comment]
Closing as this question has been answered.

**Comment by 1SAURABHKUMAR1** [comment]
@hyrious  I am trying same thing . How can i combine multiple output files . I am trying to build a online ide.
