### ISSUE TITLE
TypeError thrown from bundle encountering an mjs module

### ISSUE THREAD

**Issue by harrygr** [evanw/esbuild#2384]
I'm trying to bundle a React Application of mine (that previously was being bundled using Vite) using esbuild. 

Despite esbuild successfully creating the bundle, at runtime I'm getting a TypeError seemingly coming from a dependency that contains mjs modules. Here's the stack trace in my browser.

<img width="655" alt="Screenshot 2022-07-13 at 10 14 00" src="https://user-images.githubusercontent.com/5128200/178697333-b91b2ced-4715-4eac-904a-7e373701c133.png">

Looking at `parser.mjs` it shows me this:

<img width="322" alt="Screenshot 2022-07-13 at 10 23 41" src="https://user-images.githubusercontent.com/5128200/178699672-92403f6e-9db3-435d-80a5-2d30c053090b.png">

I'm running esbuild as follows:

```
esbuild ts/index.tsx --bundle --target=es2016  --loader:.png=file --loader:.svg=file --outdir=../priv/static/assets
```

The dependency in question seems be the `graphql` package; specifically the `parser.mjs`. module. The error is:

```
Uncaught TypeError: import_defineToJSON.default is not a function
```

I'm struggling to get to the bottom of this by following the stacktrace. Any ideas on how to solve it or debug the issue?

**Comment by hyrious** [comment]
Can you try with `--resolve-extensions=.tsx,.ts,.mjs,.js,.css,.json`?

**Comment by hyrious** [comment]
That's good news. If I'm not guessing wrong, this was because the 
graphql module uses .mjs extension to identify es modules. But esbuild does not resolve .mjs by default [as said in the docs](https://esbuild.github.io/api/#resolve-extensions). So if esbuild sees:

```js
import defineToJSON from './defineToJSON'
defineToJSON({ ... })
```

..and there be ./defineToJSON.js (in CJS format) and ./defineToJSON.mjs (in ESM format), esbuild will choose the CJS one by default. Then some error would likely to happen in CJS-ESM interop.

Vite works because they write their own resolver, which may have covered this case.

**Comment by harrygr** [comment]
Yeah, that is most likely the cause. There is indeed both types of module in the graphql package.
