### ISSUE TITLE
React: "legalComments": "linked" error

### ISSUE THREAD

**Issue by gkiely** [evanw/esbuild#2385]
When building an application that contains React using `"legalComments": "linked"` I get the following error. 
"Cannot transform with linked or external legal comments".

As far as I can tell there are no linked/external legal comments.  Is this something that can be fixed or is it intended and I am reading this incorrectly?

Example repo:
https://github.com/gkiely/vite-react-starter

Steps:
```
> Uncomment esbuild section in vite.config.ts, line 65-67
npm i
npm run build
```

**Comment by evanw** [comment]
This is an error because you are not supposed to do this. Passing `linked` tells esbuild to generate an additional `.LEGAL.txt` output file, but transform mode (unlike build mode) returns a string and doesn't support returning additional generated files. So `linked` is incompatible with transform mode.

**Comment by danielo515** [comment]
Why? Why can not the legal comments be processed and generated in a separate pipeline while the transform gets the code with the comments removed?
