### ISSUE TITLE
Typo in esbuild-linux-mips64le manifest?

### ISSUE THREAD

**Issue by cristiano-belloni** [evanw/esbuild#2400]
https://github.com/evanw/esbuild/blob/f5f5b57733865cf0968f05a5ef38b3604c997950/npm/esbuild-linux-mips64le/package.json#L15

Should it be `mips64le` instead of `mips64el`?

**Comment by evanw** [comment]
I can't check for sure because I don't have one of these machines myself. But I'm guessing it's correct because:

* Someone who actually has one of these machines told me that it's supposed to be `mips64el`: https://github.com/evanw/esbuild/issues/523#issuecomment-727753422.
* https://nodejs.org/api/process.html#processarch mentions `mipsel` as an official supported architecture.
* `mips64le` has only [38,700 search results](https://www.google.com/search?hl=en&q=%22mips64le%22) while `mips64el` has [180,000 search results](https://www.google.com/search?hl=en&q=%22mips64el%22).
* No one has written in about it not working in the almost two years since it has shipped.

Please describe in more detail how you know that it's not correct.

**Comment by cristiano-belloni** [comment]
It just seemed a typo that `esbuild-linux-mips64le` had `mips64el` as arch. Happy it's not a bug, closing, thanks!
