### ISSUE TITLE
--mangle-quoted skips mangling of properties used in "long strings with 'property' inside it" (like in Angular's HTML templates)

### ISSUE THREAD

**Issue by sachingarg05** [evanw/esbuild#2402]
Example of Angular's HTML template after it gets compiled into plain JS:
```
g=>{g.exports=`
  <div *ngIf="obj1.prop1.someProp" [style.bottom]="(obj1.prop1.anotherProp_ * 100) + '%'">
  </div>
`}}]);

```

In above example, esbuild doesn't mangle 'anotherProp_'. Even when--mangle-props is used to mangle all properties ending with _ and --mangle-quoted is also used.

This is expected behavior as described in esbuild's current documentation, but this means any properties used in Angular's HTML templates can't be mangled or minified.

Can we add another option like --mangle-quoted-substrings to include this? Or something like 
--mangle-quoted=none (default, when --mangle-quoted is not used)
--mangle-quoted=props-only (current behavior)
--mangle-quoted=substrings (to cover this new use-case)

**Comment by sachingarg05** [comment]
If this can be added, this example (with more _ at end of every property inside the sub-sub-strings):

```
g=>{g.exports=`
  <div *ngIf="obj1_.prop1_.someProp_" [style.bottom]="(obj1_.prop1_.anotherProp_ * 100) + '%'">
  </div>
`}}]);
```

Can be minified to something like this:
```
g=>{g.exports=`
  <div *ngIf="a.b.c" [style.bottom]="(a.b.d * 100) + '%'">
  </div>
`}}]);

```

**Comment by evanw** [comment]
Sorry but stuff like this is out of scope because it’s outside of normal JavaScript semantics. I do not intend for esbuild to be a compiler for Angular. You could potentially write code to do this yourself by getting the property mangling results from esbuild’s mangle cache, but it would be up to you to do that. You could also disable property mangling to get things like this to work. 

Closing as out of scope.
