### ISSUE TITLE
for window-latest CI, what is optimal way to call esbuld cli with directory of files?

### ISSUE THREAD

**Issue by iambumblehead** [evanw/esbuild#2414]
Please excuse me if this ticket is noise and feel free to close it.

I searching for a way of calling esbuild on a directory of files, from github's windows-latest CI pipeline. Currently, I'm [using this line][0] (below) which calls esbuild separately for each specific file. It does work, but is a little clunky,
```console
forfiles /m \"*.js\" /c \"cmd /c npx esbuild @file --minify --allow-overwrite --outfile=@file\"
```
Is there a known way, from windows-latest, to process all files with one call to esbuild?

[0]: https://github.com/iambumblehead/esmock/blob/master/tests/package.json#L21

**Comment by hyrious** [comment]
If you're meant to pass multiple entries to esbuild (like esbuild *.js ..., it cannot work on windows because CMD.exe does not expand asterisks), then there's no easy way. I'd recommend you to write some script to help doing this, which is easy:

```js
var p = require('path')
var entryPoints = require('fs').readdirSync('src')
	.filter(f => f.endsWith('.js'))
	.map(f => p.join('src', f))
require('esbuild').build({
	entryPoints,
	minify: true,
	allowOverwrite: true,
	outdir: 'src'
}).catch(() => process.exit(1))
```

**Comment by iambumblehead** [comment]
do you think something like following could work? --use an npm package to list the folder contents inside the esbuild command? 

here's a psuedo-code using https://www.npmjs.com/package/windows-ls. I don't think it would work as-is with windows CMD. Is it possible to use a method like this, embedding a call to another tool to return the list?
```console
esbuild `npx windows-ls ./src/*` --minify --allow-overwrite --outdir=src
```

**Comment by hyrious** [comment]
As I said, <q>there's no easy way</q>. But I'll still post some CMD.exe tricks here:

Assume we have these files:

```js
// a.mjs (test argv)
console.log(process.argv)

// ls.mjs (print out filenames)
import fs from "fs";
// **Warn**: incorrect output! need further shell escape
console.log(fs.readdirSync(".").join(" "));
```

You can use this command in CMD to pass the result of `ls.mjs` to `a.mjs`:

```cmd
for /f "delims=" %i in ('node ls.mjs') do node a.mjs %i
```

If you put this code to a shell script (a.cmd/a.bat), you have to escape `%` with `%%`:

```cmd
:: a.cmd
for /f "delims=" %%i in ('node ls.mjs') do node a.mjs %%i
```

Explanation: The `for-in` command iterates **each line** of a file-set/string-set/command-output then do something on it. The default delimiter is any whitespace characters, we set it to nothing so that one-line output will be captured entirely to one variable (%i).

If you cannot get an one-line output (which is not easy because of escaping CMD special characters), then to concat lines, more code is needed:

```cmd
:: a.cmd
@echo off
:: Enable !VAR! to be expanded lazily
setlocal EnableDelayedExpansion

set ARGS=
for /f %%i in ('dir /b *.js') do set "ARGS=!ARGS! ^"%%i^""
echo node a.mjs%ARGS%
node a.mjs%ARGS%
```

Again, I'm not suggesting doing this. It is easier and cross-platform to call esbuild in Node.js.

**Comment by hustcer** [comment]
If I were you, I will use [nushell](https://github.com/nushell/nushell) by [setup-nu](https://github.com/hustcer/setup-nu), Nushell has cross-platform support. You will love it.

**Comment by evanw** [comment]
Closing this issue because this has to do with how to use Windows, not esbuild. For what it’s worth, the [official recommendation in the docs](https://esbuild.github.io/getting-started/#build-scripts) is to use the JS API instead of the CLI for complex scenarios:

> However, using the command-line interface can become unwieldy if you need to pass many options to esbuild. For more sophisticated uses you will likely want to write a build script in JavaScript using esbuild's JavaScript API.
