### ISSUE TITLE
Bundle issue with esbuild 0.14.51, 0.14.50 works

### ISSUE THREAD

**Issue by deleonio** [evanw/esbuild#2425]
**Describe the bug**

Webpack build break.

<img width="527" alt="image" src="https://user-images.githubusercontent.com/6279703/182008247-69d7b6cc-20b6-43d0-a96c-1c22fdf40d06.png">

**To Reproduce**

- https://github.com/deleonio/eslint-preact-issue
- `pnpm i` or `npm i`
- `npm start` -> `BREAK`
- change `esbuild` version in `package.json` to fix version "`0.14.50`"
- `pnpm update` or `npm update`
- `npm start` -> `WORKS`

**Comment by deleonio** [comment]
https://github.com/preactjs/preact/issues/3641

**Comment by hyrious** [comment]
This was caused by passing `jsx: 'preserve'` to esbuild transform options (in your tsconfig.json). See reproduction below:

```jsx
let a = <div />
```

[with esbuild 0.14.51, --tsconfig-raw=...jsx: 'preserve'...](https://hyrious.me/esbuild-repl/?version=0.14.51&mode=transform&input=let+a+%3D+%3Cdiv+%2F%3E&options=--loader%3Dtsx+--tsconfig-raw%3D%27%7B%22compilerOptions%22%3A%7B%22jsx%22%3A%22preserve%22%7D%7D%27)

```jsx
let a = <div />;
```

[with esbuild 0.14.50, --tsconfig-raw=...jsx: 'preserve'...](https://hyrious.me/esbuild-repl/?version=0.14.50&mode=transform&input=let+a+%3D+%3Cdiv+%2F%3E&options=--loader%3Dtsx+--tsconfig-raw%3D%27%7B%22compilerOptions%22%3A%7B%22jsx%22%3A%22preserve%22%7D%7D%27), esbuild doesn't preserve jsx:

```js
let a = /* @__PURE__ */ React.createElement("div", null);
```

**Comment by deleonio** [comment]
Thanks
