### ISSUE TITLE
[Bug] Spread syntax does not merge falsey `""` (empty strings)

### ISSUE THREAD

**Issue by tresabhi** [evanw/esbuild#2447]
A bundled Javascript file that displays this error may look like:
```js
const a = { suffix: '' };
const b = { scale: [1, 8, 12, 0] };

const c = { ...a, ...b };
// Unbundled vanilla JavaScript: { suffix: '', scale: [1, 8, 12, 0] };
// esbuild bundled JavaScript: { scale: [1, 8, 12, 0] };
```

The build script (from the project I found the issue in):
```js
await build({
  entryPoints: ['src/index.ts'],
  outdir: BUILD_DIR, // const BUILD_DIR = 'dist';

  platform: 'neutral',
  bundle: true,
  minify: true, // disable this to see esbuild's spread syntax implementation
  sourcemap: true,
});
```

What I am having to do now:
```js
const a = { suffix: '' };
const b = { suffix: '', scale: [1, 8, 12, 0] }; //  temporary esbuild fix

const c = { ...a, ...b };
// esbuild bundled JavaScript: { suffix: '', scale: [1, 8, 12, 0] };
```

**Comment by evanw** [comment]
This is esbuild's output from the above code sample and build command (I added `console.log(c)`):

```js
var c={suffix:""},o={scale:[1,8,12,0]},s={...c,...o};console.log(s);
//# sourceMappingURL=index.js.map
```

You get this output to the console when you run that code:

```js
{ suffix: '', scale: [ 1, 8, 12, 0 ] }
```

Which is not surprising because esbuild hasn't changed anything about the code. So either esbuild is working as intended and you have a problem with some other tool you're using, or your code sample and/or build command are incorrect.

Please either update your code sample and build command so they demonstrate the problem (and provide the problematic output) or close this issue if it's not a problem with esbuild.

**Comment by tresabhi** [comment]
I will look into isolating the issue further.

**Comment by tresabhi** [comment]
This does not seem to be the case, closing. Sorry for the inconvenience.
