### ISSUE TITLE
[Feature] TypeScript 4.0 support

### ISSUE THREAD

**Issue by photonstorm** [evanw/esbuild#245]
Nothing stands still for long: https://devblogs.microsoft.com/typescript/announcing-typescript-4-0-beta/

TS4 features keep landing in VSCode with every version, so I'd say we're getting closer and closer to release now.

Will esbuild work with TS4 as is? Or will you need to implement support for the new features (such as variadic tuples, `&&=`, etc)

Equally, with a few breaking changes between 4.0 and 3.x, how will you handle backward compatibility?

**Comment by evanw** [comment]
I believe esbuild should fully support TypeScript 4. If you run into any issues, please report them.

I have already implemented these TypeScript 4 features:

* [x] Variadic Tuple Types (this has always been supported)
* [x] Short-Circuiting Assignment Operators (supported since esbuild version 0.5.5)
* [x] Labeled Tuple Elements (supported since esbuild version 0.5.13)
* [x] Custom JSX Factories (supported since esbuild version 0.5.15)

See the [release notes](https://github.com/evanw/esbuild/blob/master/CHANGELOG.md) for more details.

These TypeScript 4 features are part of the type system, which is irrelevant for esbuild since esbuild doesn't do type checking (you still need to run the TypeScript compiler for type checking when using esbuild):

* [ ] Class Property Inference from Constructors
* [ ] `unknown` on `catch` Clause Bindings
* [ ] `lib.d.ts` Changes
* [ ] Properties Overridding Accessors (and vice versa) is an Error
* [ ] Operands for `delete` must be optional.

As far as I'm aware all breaking changes are type system changes, so there are no backwards compatibility concerns with esbuild and TypeScript.

**Comment by photonstorm** [comment]
Perfect, thanks. I'll swap to the latest beta and open any issues if I find them.
