### ISSUE TITLE
Transform uses 5% of CPU, build takes 30s

### ISSUE THREAD

**Issue by ysageev** [evanw/esbuild#2454]
Hi,

I'm using Vite.js 3.0 for my React SPA of ~2000 transformed modules.  The project itself has ~490 files.   When I build the project, CPU utilization rarely goes above 5% during the transform phase, and the project takes about 30s to build.

My machine is a Ryzen 9 3950x (16 cores), and it doesn't seem that esbuild is using more than one core.

My question is, what can I do to improve build speeds.  I am certainly not getting anything close to what the benchmarks show.

**Comment by lukeed** [comment]
Try using esbuild directly. Vite is a combination of rollup and esbuild

**Comment by evanw** [comment]
This sounds like a Vite problem, not an esbuild problem. The benchmarks on esbuild's website show esbuild running by itself. Vite uses esbuild's API instead and it sounds like it's not feeding files to esbuild fast enough to be able to take advantage of esbuild's parallelism.

The easy way to speed up your build would be to use esbuild by itself (which of course only works if you aren't using Vite-specific features that don't work in esbuild). The hard way would be for you to debug Vite and figure out what is preventing parallelism in your case.

I'm closing this issue because it's not a problem with esbuild.
