### ISSUE TITLE
React displayName on anonymous functional components

### ISSUE THREAD

**Issue by patrickjm** [evanw/esbuild#2475]
Say I have the following code,

```jsx
const Image = () => (
  <img src="test.jpg" alt="image" />
)
```

There are a few [babel plugins out there](https://github.com/zendesk/babel-plugin-react-displayname) that support transforming the above code into something like this:

```jsx
const Image = () => (
  <img src="test.jpg" alt="image" />
)
Image.displayName = "Image";
```

That way, `<Image>` will be properly named in React Devtools.

I'm using Vite, and Vite only uses esbuild's transform api, so I'm assuming plugins are out of the question based on https://github.com/evanw/esbuild/issues/790, and they've expressed as much in https://github.com/vitejs/vite/issues/2325#issuecomment-789014352.

Are there any options here?

Thanks

**Comment by evanw** [comment]
Plugins are not supported for the transform API because it doesn't make any sense. All a plugin would do is change the input string that goes into the transform call. But you don't need a plugin to do that. Just change the input string before you call transform.

**Comment by patrickjm** [comment]
Will look into that, thank you

**Comment by ccreusat** [comment]
Issue is closed but maybe will be useful for anyone else.. 

You should write `displayName` directly in your component file because it is mainly use in Dev mode..

But there is some issue with tree-shaking. With Vite (or any bundler I guess), you should prefix it with `if (import.meta.env.DEV)` (in Vite's case) so that it doesn't add up in your final bundle or tree-shaking will not work correctly when using your components.
