### ISSUE TITLE
Feature request: deep analysed annotations for cjs -> esm

### ISSUE THREAD

**Issue by simon300000** [evanw/esbuild#2486]
Currently esbuild generate annotations for nodejs' cjs to esm lexer, which works well.

But if the input js file contains something like `export * from 'package-x'`,
The exports of package-x is not in the annotation.

will it be possible for esbuild to read the exports of package-x and "re-emit" in the annotation of output file?

**Comment by hyrious** [comment]
FYI, nodejs uses [cjs-module-lexer](https://github.com/nodejs/cjs-module-lexer) to lexically analyze source code to find exports. So we have several choices:

1. Let esbuild annotate more names by analyzing other packages like you said. This would require esbuild to implement something like cjs-module-lexer.
2. Let cjs-module-lexer support parsing esbuild's code pattern of re-exports, [they have already intentionally supported babel & typescript](https://github.com/nodejs/cjs-module-lexer#transpiler-re-exports). So I just raised an issue there.

**Comment by evanw** [comment]
It's probably possible to do this without modifying `cjs-module-lexer` (and also without reading the exports of the re-exported package). Modifying `cjs-module-lexer` to match esbuild's generated output based on identifiers would also not be robust because esbuild's generated identifiers can be renamed (to avoid collisions, or during minification). Instead, esbuild would have to emit something that matches [what `cjs-module-lexer` is expecting](https://github.com/nodejs/cjs-module-lexer#moduleexports-reexport-assignment). Maybe something like this:

```js
module.exports = {
  ...require('package-x'),
  /* other exports */
};
```

**Comment by simon300000** [comment]
This seems to me a far better approach, will you make this extra annotation in esbuild?
