### ISSUE TITLE
`export type` in typescript file generates export of empty objects at build

### ISSUE THREAD

**Issue by JoCat** [evanw/esbuild#2490]
Hello, ran into this problem.

When I create a variable and export its type from a ts file, an extra boilerplate code is created when building the file, which causes an error when working with electron

for example:
```ts
import { contextBridge, ipcRenderer } from 'electron';

import Game from './components/Game';
import ServerList from './components/ServerList';

const API = {
    ipc: { // temp
        on: ipcRenderer.on,
        send: ipcRenderer.send,
        invoke: ipcRenderer.invoke,
    },
    game: {
        start: Game.start,
    },
    api: {
        getStatus: async (): Promise<'connected' | 'failure' | 'connecting'> =>
            await ipcRenderer.invoke('getStatus'),
        getServers: ServerList.getServers,
    },
};

contextBridge.exposeInMainWorld('launcherAPI', API);

export type API = typeof API;
```

This generates an unused empty export with redundant code in this case:
![image](https://user-images.githubusercontent.com/13483132/186071298-abbe8f9a-20f2-46bb-a50e-f04603cc582a.png)

Which causes an error in the preload script with sandbox mode enabled, because the module does not exist in this case.
![image](https://user-images.githubusercontent.com/13483132/186071562-56ad73ab-a48f-45d2-aacf-5762a9ca8efa.png)

Everything works when sandbox mode is turned off, but I'm wondering if there's a way to fix this behavior?

Because I don't really want to pull extra code + lose more security by not being able to use sandbox mode.

**Comment by hyrious** [comment]
The problem is not with `export type`, but with the output format you chosen. When you set `format: 'cjs'`, it tells esbuild that this code: `module.exports = {}` is safe to be put in the output.

The preload script in electron does not run in a runtime that supports commonjs (like node.js), it is actually a weird context that having `require` and [some other globals](https://www.electronjs.org/zh/docs/latest/tutorial/sandbox#preload-scripts), but runs in normal browser context (thinking of it be loaded through `<script src="preload.js"></script>`, it's pretty much like that).

So the correct output format for preload.js should at least be [`iife`](https://esbuild.github.io/api/#format-iife), where a top-level `require` will still work fine.

**Comment by JoCat** [comment]
Right, I didn't think of that this morning. Thank you for your reply.
