### ISSUE TITLE
Idea: Try to sync up with the swc project

### ISSUE THREAD

**Issue by DanielRamosAcosta** [evanw/esbuild#25]
There's already a tool there called [swc](https://github.com/swc-project/swc) which I think it covers some part of this project. Maybe it's valuable to sync up with them as they might have already covered some part of this project.

I would like to hear your opinion! Thanks!

**Comment by evanw** [comment]
The author of SWC is already aware of esbuild, and I am already aware of SWC. I already worked with the author about a bug in SWC related to my benchmark, for example (see #2).

I am going to keep esbuild completely separate from SWC. SWC is slower than esbuild so integrating with SWC goes against the performance goals of this project. To give you an idea of the speed difference, on my machine esbuild can build my benchmark in ~0.5 seconds while SWC takes ~3.2 seconds (6.4x slower) to process everything and it doesn't even do bundling yet. The author said they are working on adding bundling support, but even if they get that working I think it still valuable for esbuild to exist independently because it's still so much faster.
