### ISSUE TITLE
wasm version much slower than swc

### ISSUE THREAD

**Issue by troy351** [evanw/esbuild#2503]
Both compile `lodash` source code inside web worker, `swc` was almost 2x faster than `esbuild` 

https://stackblitz.com/edit/vitejs-vite-wy5me8?file=main.js,worker.js&termial=dev

See console log

Maybe support `transformSync` when `worker: false`?

**Comment by evanw** [comment]
That's ok. The main point of esbuild is the native version. The WebAssembly version only exists because it was possible to publish it. I never originally intended for esbuild to run via WebAssembly and esbuild has not been designed for this use case at all. The WebAssembly output is not optimal in terms of memory usage, code size, or performance and it's not possible to achieve optimal WebAssembly output without completely rewriting esbuild in a language other than Go, which is not going to happen. If you want to use a bundler via WebAssembly that is more optimized than esbuild, then I recommend that you use another bundler instead.

**Comment by troy351** [comment]
Fair enough, so the main limitation was cause by `Go` not `esbuild`
