### ISSUE TITLE
support package.json type script

### ISSUE THREAD

**Issue by wenerme** [evanw/esbuild#2506]
esbuild bundle systemjs

```
The "type" field must be set to either "commonjs" or "module".
```

xref https://github.com/systemjs/systemjs/issues/2420

**Comment by evanw** [comment]
The `type` field must be set to either `commonjs` or `module` for npm packages: https://nodejs.org/api/packages.html#type. The value `script` is not one of the valid values for that field. In addition, both esbuild and node only support those two module formats as input.

**Comment by sapphi-red** [comment]
esbuild seems to load a file as JSON when `sourcemap: true` is set.

Here's the reproduction: https://stackblitz.com/edit/esbuild-template-3mtzn8?file=build.js

**Comment by sapphi-red** [comment]
No, it wasn't. systemjs's file was incorrect.

`system.min.js` includes the following code...
```js
//# sourceMappingURL=system.min.js
```

**Comment by guybedford** [comment]
@evanw JSPM supports a `"type": "script"` field to enable distinguishing scripts from modules in ESM CDN workflows, which turned out to be important when ESM is being optimized under different constraints (scripts and modules minify differently). I don't expect it to be supported elsewhere anytime soon, and a warning is no problem though.
