### ISSUE TITLE
import could not resolve

### ISSUE THREAD

**Issue by wang1212** [evanw/esbuild#2518]
When I use esbuild to package a dependency with three.js, issue an import statement and report an error.

E.g:

```ts
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls';
```

but the error disappeared when i added the file extension:

```js
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
```

Why is this?

---
esbuild (0.15.6)

**Comment by hyrious** [comment]
This is because `three`'s package.json has this config:

```json
"exports": {
  "./examples/jsm/*": "./examples/jsm/*"
}
```

When a package defined `exports`, it means that it can **fully control** what paths users can use and [resolve extensions](https://esbuild.github.io/api/#resolve-extensions) won't be applied here. So when esbuild see this code:

```js
import 'three/examples/jsm/controls/OrbitControls'
```

The exports map above tells esbuild to just load the file `path/to/three/examples/jsm/controls/OrbitControls` and an error will occur.

**Comment by wang1212** [comment]
> This is because `three`'s package.json has this config:
> 
> ```json
> "exports": {
>   "./examples/jsm/*": "./examples/jsm/*"
> }
> ```
> 
> When a package defined `exports`, it means that it can **fully control** what paths users can use and [resolve extensions](https://esbuild.github.io/api/#resolve-extensions) won't be applied here. So when esbuild see this code:
> 
> ```js
> import 'three/examples/jsm/controls/OrbitControls'
> ```
> 
> The exports map above tells esbuild to just load the file `path/to/three/examples/jsm/controls/OrbitControls` and an error will occur.

Actually, I took a look at the `exports` configuration in the package.json file of `three`, but node itself supports the implicit file extension parsing algorithm, doesn't it?
