### ISSUE TITLE
Import a file and copy to output directory without actually using it in code

### ISSUE THREAD

**Issue by SaphireLattice** [evanw/esbuild#2520]
Been struggling a bit with figuring out how to have this done without an unholy plugin that will just... copy it manually. Sure, I can do that, but I do want to see it being output and have this controlled from source code more or less easily

Basically I have a `json` file that I need to copy into the output directory, but it is not actually needed in the code, but rather where this code will be used (it's a metadata for JS that loads the code to look at). So uh, using `file` loader failed, as it just told me there's "no side effects" in the.. import? No clue how to define that.

So yeah, not sure what to do as I can't use `copy` loader because it WILL insert a damn import statement that will cause the code to fail to work at all.

**Comment by evanw** [comment]
I'm confused. You don't need esbuild to copy a file. You could just do this after running esbuild:

```
cp file.json dist/file.json
```

or if you're using JavaScript:

```js
fs.copyFileSync('file.json', 'dist/file.json')
```

That's just one line of code. If you really wanted to use esbuild to copy the file, I suppose you could make a dummy entry point that isn't actually used and then have that import the JSON file via the `copy` loader. But that's not what the `copy` loader is intended to be used for and has other drawbacks (such as all JSON files would use `copy` instead of `json`, and you'd have to disable hashes for asset files which could cause collisions).

**Comment by SaphireLattice** [comment]
Well, I wanted to do it with minimal extra code and thought that hey, I could use an `import`, as I wanted esbuild to specifically be the thing that copies that file over. 

Entry point is a typescript file, and I just wanted to have it "import" a metadata file into the output directory along with it, but turns out that `copy` loader leaves an import in the generated file which fails to get resolved by the target runtime. And `file` loader gets eaten by side effect check.

Anyways, `const sideEffect = require("metadata.json")` worked as it does not *actually* import the file in the output, but only a dummy string (whereas `copy` gives me just... bare import of the file itself), and yeah still had to mess with the asset file hashes/names to preserve the name, though in this case it's alright as it's the only asset file.

**Comment by evanw** [comment]
Ok. It sounds like you found a solution so I'm going to close this issue.
