### ISSUE TITLE
npm install esbuild fail on x64

### ISSUE THREAD

**Issue by npup** [evanw/esbuild#2521]
Hi.

I looked at some of the existing (closed) tickets for similar problems, but could not make much out of it I am afraid.
Installing works on my windows machine at home, but not at work.  It seems to be the postprocessing of the install (binary?) that has a problem (thinking of the line `220 error     at validateBinaryVersion (C:\Users\envalpet\test\node_modules\esbuild\install.js:89:32)`).  Is the postinstall not allowed to reach the needed resources for some reason?

Thankful for any pointers.  Providing the full npm debug log file.

[2022-09-05T08_24_47_084Z-debug.log](https://github.com/evanw/esbuild/files/9488224/2022-09-05T08_24_47_084Z-debug.log)

**Comment by evanw** [comment]
Took a look at the log. Maybe the relevant line is this one?

```
220 error <ref *1> Error: spawnSync C:\Users\envalpet\test\node_modules\esbuild-windows-64\esbuild.exe UNKNOWN
```

Looks like invoking the binary executable failed. I’ve heard of this happening sometimes on Windows due to either antivirus or some corporate policy about not being able to run unsigned binary executables. You might check to see if it’s either of those cases. If so, you could try adding a policy exception. Or you could try using the WebAssembly version instead (which likely won’t have this problem) and take the performance hit. Anyway this is likely a problem with your environment instead of a problem with esbuild.

**Comment by evanw** [comment]
The link you posted already [links to a solution](https://github.com/vitejs/vite/issues/9993#issuecomment-1237370039): You can potentially configure your package manager to do this. How you do that depends on the package manager. 

I’m closing this issue since it sounds like it’s not a problem with esbuild. Installing esbuild should work on a normal OS install. It’s of course possible to configure your OS such that esbuild doesn’t run, but this isn’t a problem with esbuild.
