### ISSUE TITLE
Do not hard-code `node_module` as cache directory

### ISSUE THREAD

**Issue by marvinruder** [evanw/esbuild#2523]
In https://github.com/evanw/esbuild/pull/2457, it was introduced to write to the hard-coded folder `node_modules/.cache/esbuild` in certain cases when using `yarn`. However modern `yarn` workflows (https://yarnpkg.com/features/pnp) no longer use `node_modules` folder, e.g. in favor of `.yarn/cache`. So there is no `node_modules` folder in those projects, and also no reason to create one with that name. It would be great to be able to choose a different folder for storing the cached binary in those cases, possibly inside `.yarn` or something like `.esbuild`.

**Comment by bapmrl** [comment]
Hello,

Why has this been closed? I'd also love to be able to configure the directory where the esbuild binary gets copied (as I'm using Yarn's Plug'n'Play feature and don't have any `node_modules` directories).

Thank you,

**Comment by davidkarlsson** [comment]
I'm also not very fond of esbuild creating a `node_modules/.cache/esbuild` folder. Thanks to the wonders of Yarn PnP I hadn't seen a `node_modules` folder for a long time until today when it was suddenly back after having updated esbuild to 0.15.10.

Isn't esbuild unplugged implictly anyway because it contains a postinstall script as https://yarnpkg.com/advanced/lexicon#unplugged-package says it should be? I can see both esbuild and esbuild-windows-64 in my .yarn/unplugged folder so I think it is?
