### ISSUE TITLE
feature request: drop console.assert only

### ISSUE THREAD

**Issue by mixtur** [evanw/esbuild#2530]
There are cases when we want to drop only console.assert calls, not all console.* calls.

Can you please make it possible?

There are a lot of sanity checking via `console.assert` in our code. The assertions are sometimes slow so we would like to remove them on production.
At the same time there are also some `console.log`s which we don't want to remove.

There currently is a babel plugin that we use that allows us to do exactly that https://babeljs.io/docs/en/babel-plugin-transform-remove-console/ But we would be happy to get rid of that.

**Comment by evanw** [comment]
You can do this easily without needing any changes to esbuild itself:

```js
ASSERT && console.assert(somethingExpensive())
console.log('keep this')
```

then use `--define:ASSERT=false` to remove the asserts. You can also do this:

```js
const consoleKeep = console
console.assert(somethingExpensive())
consoleKeep.log('keep this')
```

then use `--drop:console` to remove the asserts. 

The `drop` API is not intended to be a general-purpose code transformation tool like you are proposing. But this is ok because there are other straightforward ways of having unwanted code be removed with esbuild.
