### ISSUE TITLE
Change log is too large. Split it to separate files?

### ISSUE THREAD

**Issue by mixtur** [evanw/esbuild#2541]
Here is what I see when I go to the changelog page now.

![image](https://user-images.githubusercontent.com/2968077/189626848-e38cc14c-a870-4ff6-9869-9dc9e743bf22.png)

Maybe move 0.14.*, 0.13.* etc to their own separate files, only keep the links to them in the CHANGELOG.md. And in CHANGELOG.md keep the part of the changelog related to the most recent major version (0.15 now)?

**Comment by evanw** [comment]
Node had the same problem and ended up splitting things by year instead (https://github.com/nodejs/node/issues/5533 / https://github.com/nodejs/node/pull/6337). I think I like that a little better because division by version numbers is pretty arbitrary (some only have a few releases while others have dozens).
