### ISSUE TITLE
`this` inside `React.createElement` outputs an warning

### ISSUE THREAD

**Issue by sapphi-red** [evanw/esbuild#2557]
When a code transpiled from JSX by babel like
```js
const Foo = () => _jsxDEV(
  "div",
  {},
  void 0,
  false,
  { fileName: "Foo.tsx", lineNumber: 1, columnNumber: 23 },
  this
);
```
is passed to esbuild, it does not output any warnings. (0905d851eca6666bc606ff719450336ab868c547)

But when
```js
const Foo = () => {
  return /*#__PURE__*/ _createElement('div', {
    key: null,
    __self: this,
    __source: {
      fileName: _jsxFileName,
      lineNumber: 2,
      columnNumber: 10,
    },
  });
};
```
is passed (this is generated in the same situation with #2534), it outputs a warning (`this-is-undefined-in-esm`).
[stackblitz reproduction](https://stackblitz.com/edit/esbuild-template-1aqzjd?file=src%2Fmain.jsx)

I expect this warning to be omitted, since the `_jsxDEV` one is already omitted.

related: https://github.com/vitejs/vite/issues/10098

**Comment by bathos** [comment]
I’m not sure if it merits a warning or not (would lean towards no), but “since the _jsxDEV one is already omitted” seems unrelated? `_jsxDEV` is a binding identifier and could have any value / may or may not have been declared in the global obj env or the global lexical env. `this` is a keyword which is statically known to be `undefined` in this context.

**Comment by evanw** [comment]
Ok. I will remove the warning.

**Comment by sapphi-red** [comment]
Thanks!
