### ISSUE TITLE
How to directly use esbuild with Yarn 3 PnP?

### ISSUE THREAD

**Issue by thekarel** [evanw/esbuild#2567]
When installing esbuild to a Yarn 3 PnP project it's only possible to invoke it via yarn:

```sh
yarn esbuild .
```

But this is a "slow" way to run the tool, as mentioned [in the documentation](https://esbuild.github.io/getting-started/#yarn-pnp):

> For maximum esbuild performance, you may want to consider running esbuild without using Yarn's CLI (i.e. not using yarn esbuild). This can result in esbuild running 10x faster.

Is there a way to have the best of both worlds, i.e. use PnP and invoke esbuild directly? 

(I know the binary is extracted to `node_modules/.cache/...` but only after the 1st invocation.)

**Comment by evanw** [comment]
It's up to you. There's no recommended way to do this because it's a bit of a weird situation. It means you would be deciding to use Yarn for package management while simultaneously trying to avoid using Yarn to skip the performance penalty that using Yarn brings. I assume isn't a workflow that the Yarn maintainers would encourage.

The documentation calls this out for two reasons. First of all, it lets you know that you can do this if you want to. For example, if the decision to use Yarn is not in your control but you don't want to wait many seconds before your code will run, you can bundle your code with esbuild and run that directly with node to avoid Yarn's performance penalty. Second of all, it lets people who are trying to benchmark esbuild's Yarn PnP implementation that most of the performance cost is just invoking Yarn, which isn't anything that esbuild has control over.

> Is there a way to have the best of both worlds, i.e. use PnP and invoke esbuild directly?

Yes, there are ways. For example, you could install esbuild using npm in another folder, and then use that to run esbuild on your Yarn PnP project. It's up to you whether you want to do that or not though. I could see people feeling weird about that if they wanted to only use Yarn. Or you could have a separate folder with Yarn not in PnP mode and install esbuild there.

**Comment by thekarel** [comment]
Thanks @evanw. Installing into a subfolder sounds like a good starting point.
