### ISSUE TITLE
Wildcard to include all subfolders when compiling doesn't work

### ISSUE THREAD

**Issue by charklewis** [evanw/esbuild#2570]
I am finding I have to list all of the sub folders in order to get them to compile.

For example:
```
esbuild server/*.ts server/**/*.ts server/**/**/*.ts --bundle --platform=node --outdir=dist
```

I am building a fastify app with the [@fastify/autoload plugin](https://github.com/fastify/fastify-autoload) so not all of my files are imported and hence, can not all be located via imports from the main entry point.

How can I tell esbuild to look in every subfolder in server and compile all of the .ts files it finds? Is this possible using the CLI?

**Comment by evanw** [comment]
Wildcards like that are expanded into a list of files by your shell before esbuild even starts running. So this seems like a question for elsewhere (Stack Overflow?) about how to use your shell correctly instead of a question for the esbuild repo.

Note that the command as you have written it will create N independent bundles, one for each of the N files listed on the command line. That may or may not be what you want depending on what you intend for those output files to be used for. If you just want to strip TypeScript types from the `.ts` files then you probably don't want to use `--bundle`. But keep in mind that esbuild is primarily a bundler and isn't intended for the use case of emulating what `tsc` does regarding `.ts`-to -`.js` conversion, so certain things may not work as expected (such as things that require type system knowledge across files).

**Comment by charklewis** [comment]
@evanw ah I see this is why I may be getting confused. I am new to this area and was a little confused about covering TS into JS and bundling. 

I have set up my app using `ts-node` and it is working great now. I do find the `ts-node` is incredibly slow compared to `esbuild`. 

Thanks for the spending the time to respond!
