### ISSUE TITLE
esbuild-darwin-arm64

### ISSUE THREAD

**Issue by vsakaria** [evanw/esbuild#2575]
Hi there

I am on a M1 MBP 

Went to do an `npm i` and got the following 

`npm ERR! notsup Unsupported platform for esbuild-darwin-arm64@0.14.39: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})`

Searching around I think this is a OS issue can't seem to find any resources to fix it. 

Working on node `v14.18.1` and macOs Monterey 12.5.1

Any idea's

**Comment by evanw** [comment]
People often get into this situation by installing esbuild with npm running inside of Rosetta 2 and then trying to use it with node running outside of Rosetta 2, or vice versa (Rosetta 2 is Apple's on-the-fly x86_64-to-arm64 translation service).

If you are installing with npm, you can try ensuring that both npm and node are not running under Rosetta 2 and then reinstalling esbuild. This likely involves changing how you installed npm and/or node. For example, installing node with the universal installer here should work: https://nodejs.org/en/download/. Or you could consider using yarn instead of npm which has built-in support for installing a package on multiple platforms simultaneously.

If you are installing with yarn, you can try listing both "arm64" and "x64" in your ".yarnrc.yml" file using the "supportedArchitectures" feature: https://yarnpkg.com/configuration/yarnrc/#supportedArchitectures Keep in mind that this means multiple copies of esbuild will be present.

**Comment by evanw** [comment]
Were you able to get this working?

**Comment by evanw** [comment]
Closing due to lack of a reply. No code changes are needed for this because the text in https://github.com/evanw/esbuild/issues/2575#issuecomment-1259518895 is already printed in the error message for this case as of the latest esbuild version.

**Comment by vsakaria** [comment]
Sorry @evanw I haven't been able to get around to this but I will do over the next few days. Thanks for the reply I'll update you.
