### ISSUE TITLE
Write successful output to `stdout`, not `stderr`

### ISSUE THREAD

**Issue by AlexWayfer** [evanw/esbuild#2579]
Partially related to #2466, I guess.

I have tests with `esbuild` runs, and everything is OK, but there are a lot of extra output! It's from `stderr`, yes.

I guess you believe that 2nd output is not necessary is `stderr`, but as I know in UNIX world it is.

Please, write "okay" lines into `stdout`, it's regular, the 1st.

### Output

```
> pnpm esbuild assets/scripts/main.js assets/scripts/sentry.js --outdir=public/scripts/compiled/ --bundle --sourcemap
  public/scripts/compiled/sentry.js      148.1kb
  public/scripts/compiled/main.js          2.5kb
  public/scripts/compiled/sentry.js.map  364.4kb
  public/scripts/compiled/main.js.map      4.7kb

⚡ Done in 16ms

> pnpm esbuild assets/scripts/main.js assets/scripts/sentry.js --outdir=public/scripts/compiled/ --bundle --sourcemap 2>/dev/null

```

**Comment by evanw** [comment]
If you don't want to see the output file summary, you should just turn it off with [`--log-level=warning`](https://esbuild.github.io/api/#log-level). If you want stderr to end up on stdout you can do that yourself with [`2>&1`](https://linuxize.com/post/bash-redirect-stderr-stdout/#redirecting-stderr-to-stdout). You can also do `2>/dev/null` if you'd like as you demonstrated yourself.

Closing this issue because this was a deliberate design decision, and is a normal part of how Unix tools work.

**Comment by AlexWayfer** [comment]
> and is a normal part of how Unix tools work

Can you provide proofs or examples please?

I know work-arounds with redirecting output, I just don't understand why do you need a literally info log level into `stderr` (literally `err`, not even `warn`, but warnings are pretty common there) pipeline.

**Comment by AlexWayfer** [comment]
@evanw can you?
