### ISSUE TITLE
React exception when using esbuild and mui with package.json type=module

### ISSUE THREAD

**Issue by doberkofler** [evanw/esbuild#2581]
When combining the latest versions of react, mui and esbuild and using `type: "module` in the `package.json` file, using mui icon components results in a runtime error: `Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`

[example.zip](https://github.com/evanw/esbuild/files/9679369/example.zip)

```json
{
  "name": "esbuild-mui",
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "build": "esbuild index.jsx --bundle --outfile=dist/index.js"
  },
  "dependencies": {
    "@emotion/styled": "^11.10.4",
    "@mui/icons-material": "^5.10.6",
    "esbuild": "^0.15.10",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  }
}
```

```html
<!DOCTYPE html>
<html lang="en">
<head>
 <title>esbuild-mui</title>
</head>
<body>
 <div id="root"></div>
</body>
<script src="dist/index.js"></script>
</html>
```

```jsx
import * as React from 'react';
import ReactDOM from 'react-dom/client';
import MenuIcon from '@mui/icons-material/Menu';

ReactDOM.createRoot(document.querySelector("#root")).render(<MenuIcon />);
```

**Comment by hyrious** [comment]
This is because you have `"type": "module"` when you're importing a CJS module's "default export" (MenuIcon), esbuild will wrap that module with `__toESM(require_lib(), 1)` which in turn the `MenuIcon` variable becomes the whole CJS module `{ default: MenuIcon }`.

Read the doc:
https://esbuild.github.io/content-types/#default-interop

`@mui/icons-material` does provide ESM modules, I'd suggest you to write this instead:

```js
import { Menu as MenuIcon } from '@mui/icons-material'
```

**Comment by doberkofler** [comment]
Thank you very much.
