### ISSUE TITLE
Allow platform specific installs when `--platform` and `--arch` are specified

### ISSUE THREAD

**Issue by Josh-a-e** [evanw/esbuild#2597]
It would be great if this worked:

`npm install --platform=linux --arch=arm64 esbuild-linux-arm64`

But it results in this error message

```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for esbuild-linux-arm64@0.15.10: wanted {"os":"linux","arch":"arm64"} (current: {"os":"darwin","arch":"arm64"})
```

As pointed out in the very helpful error message, getting esbuild running in docker containers can present some challenges around architecture-specific builds. Typically, installing all the relevant builds during development is a good solution (similar issues are experienced working with [sharp](https://sharp.pixelplumbing.com/install#apple-m1) and [prisma](https://www.prisma.io/docs/concepts/components/prisma-schema/generators#prisma-client-prisma-client-js)) - it would be great if this was also possible with esbuild.

**Comment by evanw** [comment]
This is documented here: https://esbuild.github.io/getting-started/#simultaneous-platforms. The way to do this is to either a) run `npm install` on the target platform instead of copying the installation files over from another platform or b) use `yarn` instead of `npm` which has a feature that allows for installing multiple platforms at once (see the docs for details). It's up to you which of those options you want to go with.

When you install esbuild from the npm package registry, the installation process deliberately uses npm's available features for platform-specific packages. As far as I know `npm` doesn't have a feature that allows for installing multiple platforms at once. So if you want `npm` to be able to do this, you should send this feature request to them instead.

The reason why `esbuild-linux-arm64` is locked to a specific platform like this is that the installation process for esbuild must work without install scripts enabled since many people install their stuff with `--ignore-scripts`. Currently the only way to achieve this with npm's `package.json` format is to use `optionalDependencies` in the primary package and the `os` and `cpu` fields in the platform-specific packages.

**Comment by Josh-a-e** [comment]
Thanks. This is both helpful and annoying.
