### ISSUE TITLE
ESbuild bundling the whole lodash lib instead of importing only the used function

### ISSUE THREAD

**Issue by zerubeus** [evanw/esbuild#2602]
I use esbuild to bundle ts code used in lambda, it was working perfectly fine the bundled output was pretty small, until a few days ago, the generated file goes from few kilobytes to 5MB I inspected the generated file, and it looks like everything from the dependencies are imported even not used functions.

This is my config:

```
// eslint-disable-next-line @typescript-eslint/no-var-requires
const esbuild = require('esbuild');

const config = {
  entryPoints: ['./src/lambda.ts'],
  outdir: 'dist',
  external: ['aws-sdk'],
  bundle: true,
  format: 'cjs',
  platform: 'node',
  sourcemap: true,
  target: 'node12',
};

esbuild.build(config).catch(() => process.exit(1));
```

The lambda.ts file is really a few functions receiving an event from s3 and sending a message to SQS, I can't find out why the bundle is 5mb, thank you for the help.

**Comment by hyrious** [comment]
This is because esbuld's tree-shaking only happens in ESM context. The lodash library is written in CJS so the whole library is bundled. You may want to use `lodash-es` instead, or import functions from the sub entries like:

```js
import defaults from "lodash/defaults.js"
```

Note that esbuild does not support many optimizations involving heavy works, such as tracking a key of an object.

You can also run other optimizers such as terser or rollup after esbuild finishes its bundling.

**Comment by geoffharcourt** [comment]
There's also an ESM version of lodash you can use to help here: https://www.npmjs.com/package/lodash-es

Note that if you have dependencies that themselves use lodash, you need to make sure they import from `lodash-es` as well:

```json
# package.json
  "browser": {
    "lodash": "lodash-es"
  },
```

**Comment by evanw** [comment]
Yes `lodash-es` sounds like the best solution here. From what I understand, the main point of `lodash-es` is to enable tree-shaking of `lodash` so that's what you're supposed to use if tree-shaking is important. I'm closing this issue as "won't fix".
