### ISSUE TITLE
esbuild esm node issue

### ISSUE THREAD

**Issue by mshamasa** [evanw/esbuild#2626]
I am trying to use esbuild to build a node application, but I keep encountering this issue.

node: v16.18

I can build the project and everything looks good with one minor issue, esbuild keeps using the ESM files from 1 library, even though I'm setting everything to be commonjs.

I have an example repo to reproduce error here: https://github.com/mshamasa/esbuild_gql

You can replicate error by:
yarn install
yarn build
yarn prod

<img width="1444" alt="Screen Shot 2022-10-22 at 8 29 48 PM" src="https://user-images.githubusercontent.com/6489276/197372274-679525b9-e956-4ab3-af02-fc9def63497b.png">
<img width="878" alt="Screen Shot 2022-10-22 at 8 30 06 PM" src="https://user-images.githubusercontent.com/6489276/197372275-cee3c4a9-a35a-429c-83bc-5c2630884b84.png">

**Comment by evanw** [comment]
This is a known issue with the approach of using `--external:./node_modules/*` (it's because esbuild currently rewrites external paths that were specified using a relative file system path). One workaround is to manually specify each dependency as external using `--external:@graphql-tools/merge` instead. This is easier to do with the JavaScript API instead of the CLI since you can use JavaScript to generate the array of external dependency names from your `package.json` file.

**Comment by mshamasa** [comment]
I see, thank you!

I updated the code base I have above with both options, with CLI and a JS API and that resolve it.
Is there some place you want me to update the docs to reflect this known issue?
