### ISSUE TITLE
jsxFactory should be aliased for better minification

### ISSUE THREAD

**Issue by Vendicated** [evanw/esbuild#2633]
Like the name suggests, custom jsxFactories are not minified when building with minification enabled

What this means is that if you use a very long factory (mine is 42 chars!), this factory will be embedded in the output for each jsx element, this is about 300 times in mine. After changing my factory to a single letter, my bundle size shrank by 10%.

Why doesn't esbuild alias the factory (and fragment factory) to a shorter variable (or wrapper function if you're worried about losing `this`) ?

**Comment by Vendicated** [comment]
```jsx
function Component() {
  return (
    <div>
      <h1>Title</h1>
      <p>Hi!</p>;
    </div>
  );
}
```

```sh
$ esbuild code.jsx --jsx-factory="Some.Super.Long.Factory" --minify
function Component(){return Some.Super.Long.Factory("div",null,Some.Super.Long.Factory("h1",null,"Title"),Some.Super.Long.Factory("p",null,"Hi!"),";")}
```

**Comment by evanw** [comment]
For compatibility with the rest of the JSX ecosystem, the JSX factory must be substituted inline as if you had written it manually. This matters in the case where the JSX factory is not part of the bundle (which is the case in your example). Aliasing it in a variable would be incorrect because there's no guarantee that the value will remain the same over time. There is also no guarantee about when the value will be initialized. Automatically aliasing the value as you suggested will silently introduce bugs in certain projects. I think what esbuild is doing here is correct.

If your JSX factory is external to the bundle like this and you know that the factory is going to already be initialized when the bundle is loaded, then esbuild already gives you the tools to opt-in to generating better output. For example:

```
$ cat example.tsx 
function Component() {
  return (
    <div>
      <h1>Title</h1>
      <p>Hi!</p>;
    </div>
  );
}

$ cat injected.js 
export let jsxAlias = Some.Super.Long.Factory

$ esbuild example.tsx --minify --inject:injected.js --jsx-factory=jsxAlias
var e=Some.Super.Long.Factory;function t(){return e("div",null,e("h1",null,"Title"),e("p",null,"Hi!"),";")}
```

**Comment by Vendicated** [comment]
That's a really good point, but wouldn't a wrapper function solve those cases?
esbuild could generate something along the lines of the below code. I can just inject it manually now (thanks for the tip!), but it woud probably be useful for many people to have this out of the box, unless you see any more potential problems with this?
```js
var e = function() { return Some.Super.Long.Factory.apply(Some.Super.Long, arguments) }
e("div", {}, e("p", {}, "hi"));
```

**Comment by evanw** [comment]
Forwarding a function generically like that introduces additional performance overhead, so it still doesn't seem like something that esbuild should be doing automatically.
