### ISSUE TITLE
esbuild keeps wholeheartedly ignoring `--define`

### ISSUE THREAD

**Issue by markusbkk** [evanw/esbuild#2644]
Maybe I came in here with faulty expectations because I thought esbuild was finally the holy grail of JS build systems (let's not kid ourselves. The JS ecosystem is an absolute mess. It's such a mess, I occasionally take a break and write some C++ code, read a book on Java or debug some Perl code to calm myself 😉 ) but I'm really running into some frustrating issues while attempting to set up preact-compat for a small app (while also wondering why so many things have to be put into a single line inside **package.json** rather than a config file).

My main issue is that, no matter what I do or what docs I follow, esbuild keeps warning about a missing env define.
Then, inside the browser, there's naturally nothing but a white page and a "helpful" red error message floating atop the console window telling me that `process` is not defined.

My **package.json** has the following `start` script:

```sh
"node esbuild.config.js --define:process.env.NODE_ENV=\\\"development\\\" -w --loader:.js=jsx"
```

**esbuild.config.js**:

```js
#!/usr/bin/env node

import esbuildServe from "esbuild-serve";

esbuildServe(
  {
    logLevel: "info",
    entryPoints: ["src/index.js"],
    bundle: true,
    outfile: "www/main.js",
  },
  { root: "www" }
);
```
**tsconfig.json**:

```json
{
    "include": ["src"],
    "compilerOptions": {
      "target": "ES6",
      "module": "commonjs",
      "jsx": "react-jsx",
      "jsxImportSource": "preact",
      "jsxFactory": "h",
      "jsxFragmentFactory": "Fragment",
      "outDir": "./dist",
      "strict": true,
      "baseUrl": "./",
      "esModuleInterop": true,
      "skipLibCheck": true
    }
  }
```

My **index.tsx** to test preact-compat interoperability:

```tsx
import React, { Fragment } from "preact/compat";
import { render, h, Component } from "preact";

import { Planet } from "react-kawaii";

const Example = () => <Planet size={200} mood="blissful" color="#FDA7DC" />;

class Clock extends Component {
  state = { time: Date.now() };
  timer = Date.now();

  // Called whenever our component is created
  componentDidMount() {
    // update time every second
    this.timer = setInterval(() => {
      this.setState({ time: Date.now() });
    }, 1000);
  }

  // Called just before our component will be destroyed
  componentWillUnmount() {
    // stop when not renderable
    clearInterval(this.timer);
  }

  render() {
    let time = new Date(this.state.time).toLocaleTimeString();
    return (
      <>
        <Example />
        <span>{time}</span>
      </>
    );
  }
}

render(<Clock />, document.getElementById("app"));
```

Is there anything I'm missing?

I tried putting `define: { "process.env.NODE_ENV": "development" }` inside `esbuildServe(
  {` in **esbuild.config.js**, but that just raises another error in the browser console.

VSCode also tells me that `"jsx": "react-jsx"` won't play well with `"jsxFactory": "h"` and `"jsxFragmentFactory": "Fragment"`, even though I definitely saw those documented together somewhere and they actually make two error messages inside **index.tsx** disappear.

**Comment by evanw** [comment]
> My **package.json** has the following `start` script:
> 
> ```shell
> "node esbuild.config.js --define:process.env.NODE_ENV=\\\"development\\\" -w --loader:.js=jsx"
> ```
> 
> **esbuild.config.js**:
> 
> ```js
> #!/usr/bin/env node
> 
> import esbuildServe from "esbuild-serve";
> 
> esbuildServe(
>   {
>     logLevel: "info",
>     entryPoints: ["src/index.js"],
>     bundle: true,
>     outfile: "www/main.js",
>   },
>   { root: "www" }
> );
> ```

First of all, I have no idea what code is being run when you import the `esbuild-serve` package because that package isn't a part of this repo. So you may need to reach out to the author of the package you are using if you are still encountering trouble.

That said, it looks like you are passing command-line arguments to some code you wrote that doesn't check command-line arguments. So I'm not surprised that command-line arguments are being ignored because I don't see any code that reads them. There's nothing that magical about esbuild's JavaScript API. It's just a function that you call. You'll need to pass your API options to esbuild using JavaScript (assuming that `esbuild-serve` is mostly a pass-through package on top of esbuild's JavaScript API and doesn't do anything magical like converting command-line options into options for esbuild's JavaScript API).

> I tried putting `define: { "process.env.NODE_ENV": "development" }` inside `esbuildServe( {` in **esbuild.config.js**, but that just raises another error in the browser console.

I'm guessing the error is because you are substituting `process.env.NODE_ENV` for `development` (the identifier) not `"development"` (the string). This exact situation and what to do about it is already described in the documentation: https://esbuild.github.io/api/#define.

> VSCode also tells me that `"jsx": "react-jsx"` won't play well with `"jsxFactory": "h"` and `"jsxFragmentFactory": "Fragment"`, even though I definitely saw those documented together somewhere and they actually make two error messages inside **index.tsx** disappear.

That error sounds right. `jsxFactory`/`jsxFragmentFactory` is for the normal JSX transform while `react-jsx` is for something else that works entirely differently. `react-jsx` has six separate identifiers instead of two and the names are non-configurable. Instead, you are supposed to configure the `jsxImportSource` setting. This is documented here: https://esbuild.github.io/api/#jsx-import-source.

**Comment by markusbkk** [comment]
> ```js
> esbuild-serve"
> ```

Thanks for the quick response time.

[esbuild-serve](https://github.com/nativew/esbuild-serve) is basically just a thin wrapper around esbuild and [serve](https://github.com/nativew/serve) that provides live-reloading.
I added it to my test project last night because I couldn't find a built-in way to do a live reload.

As for 
> it looks like you are passing command-line arguments to some code you wrote that doesn't check command-line arguments

I'm trying to build a project that uses React components and preact-compat under the hood.
React (and thus preact-compat) expect node environment variables when bundling for the browser.

After changing the define inside **esbuild.config.js** to a proper string, there's no more warnings but the browser console now reports another, more cryptic error.

```
Uncaught TypeError: Cannot add property __, object is not extensible
    at w (main.js:2658:19)
    at j (main.js:2777:267)
    at w (main.js:2668:9)
    at j (main.js:2777:267)
    at w (main.js:2668:9)
    at j (main.js:2777:267)
    at w (main.js:2668:9)
    at j (main.js:2777:267)
    at P (main.js:2856:105)
    at main.js:3448:3
```

A cursory google search returned https://github.com/storybookjs/storybook/issues/12853 so I guess this is an aliasing issue that will require me to get more thoroughly accustomed to esbuild's plugin system.

**Comment by evanw** [comment]
Closing as this was a problem with the code that was calling esbuild, not a problem with esbuild itself.
