### ISSUE TITLE
External package doesn't get imported

### ISSUE THREAD

**Issue by Alexandre-Fernandez** [evanw/esbuild#2650]
I specified `@proload/core` as an external package, but for some reason it doesn't work. 
When running `dist/index.js` it is `undefined`.

Reproduction : 
- `git clone https://github.com/Alexandre-Fernandez/esbuild-proload &&`
- `cd esbuild-proload &&`
- `npm i &&`
- `npm run debug`

```js
require("esbuild").build({
	entryPoints: ["index.ts"],
	bundle: true,
	outdir: "dist",
	external: ["@proload/core", "@proload/plugin-typescript", "@swc/core"],
	platform: "node",
})
```

**Comment by hyrious** [comment]
This is because the CJS wrapper in [`@proload/core`](https://github.com/natemoo-re/proload/blob/main/packages/core/lib/cjs/index.cjs) does not re-export the same object (the load function) in ESM module.

```js
// @proload/core/lib/cjs/index.cjs
function load(...args) {
    return import('../esm/index.mjs').then(({ default: loader }) => loader(...args));
    //                                                 ^ the real load function in ESM
}
```

The real one (in ESM module) does have the `load.use()` method, while the CJS one does not implement corresponding wrapper.

You can compile your script to ESM format with `format: 'esm'`, which should work. (Don't forget to change the extension to `.mjs` for node.js to run correctly).

As for the package author, they can implement such wrapper instead,

```js
// @proload/core/lib/cjs/index.cjs
let _use_plugins
async function load(...args) {
  const mod = await import('../esm/index.mjs')
  if (_use_plugins) {
    mod.default.use(_use_plugins)
    _use_plugins = undefined
  }
  return mod.load(...args)
}
load.use = function use(plugins) {
  (_use_plugins ||= []).push(...plugins)
  load.plugins.push(...plugins) // XXX not the same array in ESM!
}
// caveat: cannot wrap `load.plugins` correctly because it is sync
load.plugins = []
```

**Comment by Alexandre-Fernandez** [comment]
I guess this issue is closable, unless there's a way to detect this kind of issue and create the wrapper inside the bundle

**Comment by evanw** [comment]
I see. The ESM version is a synchronous API while the CommonJS version is an asynchronous API. I'm going to close this because it's a problem with the package, not with esbuild.
