### ISSUE TITLE
ESBuild tree-shakes imports of code that is emitted

### ISSUE THREAD

**Issue by DerGernTod** [evanw/esbuild#2665]
## Problem
ESBuild generates invalid code when creating unreachable blocks via define replacements. It tree-shakes imports of functions that are still used in the unreachable code parts, making other code inspectors (like Google closure compiler) break upon reaching it during analysis.

## Expectation
ESBuild shouldn't tree-shake imports of code that is still used in the result, even if unreachable.

## Example

```ts
import { log } from "./lib";

declare const IS_DEBUG: boolean;

function foo() {
    if (IS_DEBUG) {
        log("foo");
    }
}

foo();
```

Using the `define` config, we can replace the `IS_DEBUG` constant with `false` to create an unreachable code block. ESBuild afterwards removes the `import` statement, but keeps the unreachable block, resulting in this:

```js
function foo() {
  if (false) {
    log("foo");
  }
}
foo();
```

However, running this through other analyzers such as Google closure compiler will result in an error:

> ERROR - [JSC_UNDEFINED_VARIABLE] variable log is undeclared

you can find a reproducer repo here:
https://github.com/DerGernTod/esbuild-define-tree-shaking

**Comment by evanw** [comment]
This code isn't what esbuild would consider invalid. Invalid to esbuild means code with a syntax error or a module instantiation error. This code is valid JavaScript. If you run it in a JavaScript environment, this change that esbuild made won't ever cause any behavior changes vs. the original code. If you are running code analyses such as linting, I recommend running them on the source code instead of on the generated output. If you want esbuild to "compact" the syntax tree you can use `minifySyntax: true`, which should remove this if statement.

Google Closure Compiler's advanced mode has its own "language" that looks like JavaScript but that has its own type system layered on top and that comes with a lot of extra rules for what JavaScript syntax should be used. It's an evolutionary divergence from the rest of the community, which went with TypeScript instead. This language is not something that esbuild supports.

**Comment by DerGernTod** [comment]
fair enough. thanks for the hint about `minifySyntax`, that's what did the trick. i couldn't wrap my head around why esbuild would know what to remove, but keep the code that was responsible for that removed import. didn't think about a flag that would resolve it.

i agree, closure, as powerful as it is, is hardly compatible with the modern js world (i see lots of warnings because it doesn't understand optional properties properly after ts transpiled them to es5)... unfortunately it's still the most feasible optimizer for my project, so i have to stick with it... i would just hope it wouldn't throw errors for code that is never executed 😅
