### ISSUE TITLE
browser developer tools step through does not work properly with sourcemaps generated by esbuild

### ISSUE THREAD

**Issue by skarning** [evanw/esbuild#2667]
We have been using esbuild for bundling for a while but we have issues when stepping through code in dev tools.

Code we know have been executed will be skipped and breakpoints will not be hit.
Sometimes breakpoints will be hit for one run but not the next etc.

Our configuration:

```javascript
esbuild.build({
entryPoints: Object.fromEntries(getComponents().map((file) => [path.parse(file).name, file])),
bundle: true,
        sourcemap: true,
        minify: false,
        minifyWhitespace: true,
        minifySyntax: true,
        outdir: WIDGETS_OUTPUT_DIR,
        outbase: WIDGETS_INPUT_DIR,
        sourcesContent: true,
        watch: watch,
        plugins: [litcss.litCssPlugin()]
    })
    .catch(() => process.exit(1));
```

Is this a bug with sourcemaps? Or are we missing some configurations

**Comment by evanw** [comment]
This could be a bug with your browser, or a bug with esbuild. It would only be a bug with esbuild if it happens when you use esbuild to bundle your code but not when you use another bundler to bundle your code. Is that the case here? If not, then you'd want to report this bug to your browser vendor instead.

> Sometimes breakpoints will be hit for one run but not the next etc.

Non-determinism with how the browser handles breakpoints isn't anything that esbuild has any control over. Maybe the source map hasn't been loaded by the browser in time on some runs? This sounds like a browser bug.

**Comment by skarning** [comment]
Thank you for your answer. This bug only happens when bundling with esbuild. With rollup it works fine, but we want to use esbuild for performance reasons. The inconsistency in breakpoints happens long after inital load, so timing should not be the issue.

**Comment by evanw** [comment]
I'm going to add `unactionable` since issue this needs more information to be able to do anything here. It sounds like it could be due to the difference between the source maps generated by esbuild and by Rollup, in which case esbuild's source map generation could be changed to fix this. But I'd need an example that demonstrates the problem to be able to fix it.

**Comment by evanw** [comment]
Closing since this is unactionable and hasn't gotten a follow-up post with more details. We can reopen it later if more details are provided.
