### ISSUE TITLE
Compiling untrusted code

### ISSUE THREAD

**Issue by spg** [evanw/esbuild#2680]
Webpack [should not be used](https://stackoverflow.com/questions/64515844/why-does-webpack-warn-not-to-compile-untrusted-code) to compile untrusted code. 

Is esbuild safe to compile untrusted code? Could not find any information on Google about esbuild specifically.

**Comment by evanw** [comment]
First of all, doing this requires a lot of caution. Even installing untrusted code in order to download it to your file system isn't safe because your package manager may try to run it (e.g. post-install scripts). That's just a problem with the JavaScript ecosystem, and isn't anything specific to esbuild.

Once you get the files safely on your file system, if you only use the esbuild binary executable or esbuild's Go API, don't use esbuild's JavaScript API, and don't run any plugins, then the bundling operation should be reasonably safe. Running esbuild won't evaluate any JavaScript (it can't as it doesn't contain a JavaScript interpreter), and esbuild doesn't create any subprocesses so it won't try to run any commands or anything like that.

Whether that's means safety or not depends on your threat model. For example, there's no guarantee of termination. Arbitrary untrusted inputs could still cause esbuild to crash, hang, or use up all of the memory and/or file system space on the machine and brick the machine. This goes for almost any program that you might run on your computer. Also Unix systems have lots of things on the file system that look like files but aren't and esbuild might access them if JavaScript code references them. For example, nothing stops esbuild from reading from `/dev/random` forever if JavaScript contains `import '/dev/random'`. There could be other special paths on the file system that do even worse things when esbuild accesses them (e.g. hypothetically writing to a file system path that turns out to be a socket that sends important data somewhere bad). That's just a problem with the Unix ecosystem, and isn't anything specific to esbuild.

There isn't currently anything esbuild does that explicitly accesses the network (other than the dev server obviously, but you have to explicitly run that) so at least right now, bundling with esbuild shouldn't leak anything over the network. For example, esbuild doesn't currently try to fetch imported `https://` URLs like [Deno](https://deno.land/) does. I could see people asking for this feature in the future, and I'm not going to commit to esbuild never doing that. So if you're concerned about the possibility of that happening in a future esbuild update, you could consider running this in an environment without network access. Although I have no plans to add a feature like that to esbuild at the moment.

So I'm not going to say it's totally safe, but it's pretty safe.

**Comment by spg** [comment]
Thanks for your detailed answer @evanw 🙏

**Comment by evanw** [comment]
Closing this as it has been answered.
