### ISSUE TITLE
How to compile node_modules for the first time, and no longer compile node_modules dependent packages in rebuild

### ISSUE THREAD

**Issue by gitfei1231** [evanw/esbuild#2689]
Currently using https://dependency-packager.fly.dev/echarts@5.0.0 to obtain the node_modules dependency package, I want to use esbuild-wasm for browser compilation, I have written it, and the compilation is normal, but every time Rebuild will recompile the node_modules dependency package, resulting in a longer rebuild time. How can rebuild not need to compile the compiled node_modules dependency package?

**Comment by gitfei1231** [comment]
@evanw Can you help me

**Comment by evanw** [comment]
I’m not totally sure what you’re saying, sorry. 

If you have added a plugin that pulls external dependencies from the internet and it’s slow: It’s up to plugin authors to add caching to their plugin. There are some notes for how to do that here: https://esbuild.github.io/plugins/#caching-your-plugin. 

If you are asking for faster incremental builds that don’t rebuild the whole module graph: Unfortunately that’s not how esbuild currently works, and it’s not straightforward to change it. Every build rebuilds the whole module graph. There are certain aspects of how esbuild does bundling such as scope hosting that requires all modules to be re-bundled. Incremental builds are a way to skip parsing all of the unchanged modules again. This is a speed-up but does not make bundling an order of magnitude faster (maybe 2x faster?).

**Comment by gitfei1231** [comment]
> 我不太确定你在说什么，抱歉。
> 
> 如果您添加了一个从互联网上提取外部依赖项的插件并且它很慢：插件作者需要向他们的插件添加缓存。这里有一些关于如何做到这一点的说明：[https](https://esbuild.github.io/plugins/#caching-your-plugin) ://esbuild.github.io/plugins/#caching-your-plugin 。
> 
> 如果您要求更快的增量构建而不重建整个模块图：不幸的是，这不是 esbuild 当前的工作方式，并且更改它并不简单。每次构建都会重建整个模块图。esbuild 如何进行捆绑的某些方面，例如需要重新捆绑所有模块的范围托管。增量构建是一种跳过再次解析所有未更改模块的方法。这是一种加速，但不会使捆绑速度提高一个数量级（也许快 2 倍？）。

thankyou,My purpose is to make the increment faster. Can I ask you another question, if I want to develop a browser-based online multi-file dependency compilation preview editor, is using esbuild-wasm the best choice? Can you give me an idea or suggestion.

**Comment by gitfei1231** [comment]
@evanw thankyou, my purpose is to make the increment faster. Can I ask you another question, if I want to develop a browser-based online multi-file dependency compilation preview editor, is using esbuild-wasm the best choice? Can you give me an idea or suggestion.

**Comment by evanw** [comment]
It’s not necessarily the best choice, no. I added a WASM build to esbuild because people asked for it and it was possible to do. But esbuild wasn’t designed for the WASM use case at all and there are some drawbacks. The WASM GC proposal is still being worked on so GC languages like Go are at a disadvantage with WASM. Go also hasn’t enabled threads for WASM so esbuild is single-threaded on WASM (unlike native esbuild, which is multithreaded). Also the WASM byte code format is not a good fit for Go’s coroutine-style execution model, which leads to inefficient code generation. These things mean WASM esbuild can be around 10x slower than native esbuild. 

I’m not sure what the best tool out there is for doing this, sorry.

**Comment by gitfei1231** [comment]
@evanw I see. Thank you for your answer
