### ISSUE TITLE
Export all available options from esbuild

### ISSUE THREAD

**Issue by 1aron** [evanw/esbuild#2703]
<img width="971" alt="Screenshot 2022-11-27 at 11 58 27 PM" src="https://user-images.githubusercontent.com/33840671/204144876-fae6a925-d0e0-4480-b431-59de4d774aab.png">

I'm basing my CLI on top of esbuild, which provides its own options, and I'd like to inherit from esbuild as well, is there a way to export options that already exist inside esbuild `esbuild --help`?

<img width="682" alt="Screenshot 2022-11-28 at 12 09 17 AM" src="https://user-images.githubusercontent.com/33840671/204145185-1ef878e6-ec77-47e5-af4d-af0ad30b2c2a.png">

It could look like this:

```ts
import { options } from 'esbuild'
```
`console.log(options)`
```json
[
    { "name": "bundle", "description": "Bundle all dependencies into the output files", "type": "boolean" },
]
```

**Comment by hyrious** [comment]
Well, I have [one tool](https://github.com/hyrious/esbuild-dev) that passes through some esbuild options too. Because it's basically calling esbuild through the JS api, I need to also parse the cli args to JS values. In the end, I manaully extracted [flags](https://github.com/hyrious/esbuild-dev/blob/main/src/args.ts) from [scanning](https://github.com/hyrious/esbuild-dev/blob/main/scripts/flags.ts) the esbuild source code (it's just some string manipulations).

The esbuild cli options are not as common as other cli tools. I mean a simple JSON may not enough to be what you want. For example:

- There are not only `string` typed options like `--global-name`, but also options that need you to
  - transform to RegExp like `--mangle-props`
  - transform to contents of a file like `--mangle-cache`
- There are single typed options like `--bundle`, but also options that having multiple types, like `--sourcemap=true`, `--sourcemap=inline`

Such uncommon options may be more in the future, I hope you could find the proper way to solve your problem.

**Comment by 1aron** [comment]
@hyrious Thank you for your explanation and tools, I think it makes sense! 🥰
