### ISSUE TITLE
enum tree shaking failing in real-life scenario

### ISSUE THREAD

**Issue by NPellet** [evanw/esbuild#2705]
I've gone through https://github.com/evanw/esbuild/issues/128 but I'm still getting an issue with tree-shaking:
Steps to reproduce:

```
npm i esbuild
npm i @aws-cdk/aws-dynamodb
```

main.ts
```typescript
import { AttributeType } from '@aws-cdk/aws-dynamodb';

export const config = {
  A: AttributeType.BINARY,
};
```

esbuild.js
```javascript
const path = require('path');

require('esbuild')
  .build({
    entryPoints: ['./main.ts'],
    bundle: true,
    platform: 'node',
    outdir: 'build',
    target: 'node14',
    allowOverwrite: true,
    minify: false,
    sourcemap: false,
  })
  .catch(() => process.exit(1));
```

## Expected output
Just the inlined enum.

## Actual output
The whole module is not shaken away.

Declaration of the enum:
```typescript
/**
 * Data types for attributes within a table
 *
 * @see https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html#HowItWorks.DataTypes
 */
export declare enum AttributeType {
    /** Up to 400KiB of binary data (which must be encoded as base64 before sending to DynamoDB) */
    BINARY = "B",
    /** Numeric values made of up to 38 digits (positive, negative or zero) */
    NUMBER = "N",
    /** Up to 400KiB of UTF-8 encoded text */
    STRING = "S"
}
```

Is it because the `@aws-cdk/aws-dynamodb` module was transpiled to CJS ?

**Comment by evanw** [comment]
> Is it because the `@aws-cdk/aws-dynamodb` module was transpiled to CJS ?

Yes. Importing `@aws-cdk/aws-dynamodb` imports [this file](https://unpkg.com/@aws-cdk/aws-dynamodb@1.181.1/lib/index.js) which is just JavaScript. TypeScript enum inlining is only done by esbuild if you use the original TypeScript source code. That's not the case here.

Also even if esbuild were to process the TypeScript type declaration file, all TypeScript type annotations are treated as comments by esbuild and are ignored so this wouldn't actually do anything. Specifically everything in a `.d.ts` file is a type annotation as well as everything inside a TypeScript `declare` statement. This behavior is documented here: https://esbuild.github.io/content-types/#no-type-system. It's because esbuild does not attempt to replicate TypeScript's type system.

This is not a bug with esbuild. This is just a limitation due to esbuild not processing TypeScript types, which is a non-goal.

**Comment by NPellet** [comment]
Thanks !
I perfectly understand why the enum is not inlined, makes complete sense.
But I'm also trying to figure out why dead-code elimination is not performed. 

In `@aws-cdk/aws-dynamodb/lib/table`, where the symbol is located, the definition of the enum is 

```javascript
/**
 * Data types for attributes within a table
 *
 * @see https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html#HowItWorks.DataTypes
 */
var AttributeType;
(function (AttributeType) {
    /** Up to 400KiB of binary data (which must be encoded as base64 before sending to DynamoDB) */
    AttributeType["BINARY"] = "B";
    /** Numeric values made of up to 38 digits (positive, negative or zero) */
    AttributeType["NUMBER"] = "N";
    /** Up to 400KiB of UTF-8 encoded text */
    AttributeType["STRING"] = "S";
})(AttributeType = exports.AttributeType || (exports.AttributeType = {}));
``` 

Even if I include this file directly, I don't see any dead code elimination
Is it one of those expression with any side effect ?

**Comment by hyrious** [comment]
Yes, the tree-shaking rules in esbuild is much simpler than rollup. It does not track side effects inside objects (which means it only has var-level DCE). Examples:

```js
let BINARY = "B" // pure
let AttributeType = { BINARY } // pure

AttributeType["BINARY"] = "B" // Not pure, because there might be a { set BINARY() {} } which triggers side effects

let B = AttributeType.BINARY // Not pure, because there might be a { get BINARY() {} } which triggers side effects
```

There's also pure annotations (`/* @__PURE__ */`) that can help bundlers shaking codes. You can read more info in my gist: https://gist.github.com/hyrious/3040183d0b966f9696dca20ec9bdfb2d

**Comment by NPellet** [comment]
Alright ! Thanks ! That's good to know, I understand
