### ISSUE TITLE
How can I bundle transpilled CSS & JS in variable format?

### ISSUE THREAD

**Issue by SuperPauly** [evanw/esbuild#2709]
So I have compiled some Svelte code and I now have the CSS and JS in variables.
So far I can write it out to a file and call:

```
require("esbuild")
  .build({
    entryPoints: ["js.code"]
```

To build it but what if I don't have a file and its just a long string of text? How can I pass in CSS and JS for it to be bundled/minified?

I have tried a few different ways like using 'stdin' and 'sourcefile' but that didnt work.

How can I do this without creating a file?

**Comment by evanw** [comment]
The documentation provides a working example for how to do this: https://esbuild.github.io/api/#stdin. It's not possible to say what's wrong here since you didn't provide a working example of the problem. Note that you may need to specify `resolveDir` to say which directory to use when resolving import paths (since bundling is enabled).

**Comment by SuperPauly** [comment]
> The documentation provides a working example for how to do this: https://esbuild.github.io/api/#stdin. It's not possible to say what's wrong here since you didn't provide a working example of the problem. Note that you may need to specify `resolveDir` to say which directory to use when resolving import paths (since bundling is enabled).

Thanks for the reply :)

I solved it in the end, right at the bottom of the page was a Svelte example I missed under 'Example Plugins' https://esbuild.github.io/plugins/#svelte-plugin
