### ISSUE TITLE
define `process.env.NODE_ENV` works differently

### ISSUE THREAD

**Issue by sapphi-red** [evanw/esbuild#2719]
```js
process.env.NODE_ENV = 'test'
const foo = process.env.NODE_ENV

foo.bar = 'foo bar'
const bar = foo.bar
```
is transformed to
```js
"node_env" = "test"; // process.env.NODE_ENV is replaced even if it's a lvalue
const foo = "node_env";
foo.bar = "foo bar"; // foo.bar is not replaced
const bar = foo.bar;
```
with `--define:process.env.NODE_ENV=\"node_env\" --define:foo.bar=\"foo_bar\"` ([repl](https://hyrious.me/esbuild-repl/?version=0.16.1&mode=transform&input=process.env.NODE_ENV+%3D+%27test%27%0Aconst+foo+%3D+process.env.NODE_ENV%0A%0Afoo.bar+%3D+%27foo+bar%27%0Aconst+bar+%3D+foo.bar&options=--define%3Aprocess.env.NODE_ENV%3D%5C%22node_env%5C%22+--define%3Afoo.bar%3D%5C%22foo_bar%5C%22)).

The generated code is not a valid code. A string cannot be a lvalue.

This happens with 0.11.23, 0.12.29, 0.13.15, 0.14.54, 0.15.18, 0.16.1.

**Comment by evanw** [comment]
I just looked into this. There isn't anything special about `process.env.NODE_ENV` here. In your example the define for `foo.bar` doesn't apply because the define feature only replaces global variable references and `foo` is a local variable in this case. If you add `let process` to the code then `process.env.NODE_ENV` won't be replaced either, since then `process` will also be a local variable.

**Comment by sapphi-red** [comment]
Oh, you are right. There aren't anything special with `process.env.NODE_ENV`. It's special when it includes a `.`.

```js
foo_bar = 'foo bar'
const bar = foo_bar
```
is transformed to
```js
foo_bar = "foo bar";
const bar = "foo_bar";
```

**Comment by evanw** [comment]
I discovered that Webpack's DefinePlugin has the same behavior here (being able to replace an assignment target with a non-identifier). I can change esbuild to avoid generating code with a syntax error by avoiding replacements for assignment targets, but the result still won't make much sense since it means the load will be substituted but the store won't be.
