### ISSUE TITLE
Ability to output pure cjs for node from TS

### ISSUE THREAD

**Issue by ArnaudBarre** [evanw/esbuild#2733]
Hi and thanks for all the work you've already done on interop.

I've read the documentation and various issues and I understand the current behaviour and I also think that the best one for esbuild adoption and helping people move to a faster bundler.

I also think that we should stop using default export. But alas, for compatibly with the existing vite-react plugin, I published the vite-react-swc plugin with default export using esbuild to output [both esm and cjs](https://github.com/vitejs/vite-plugin-react-swc/blob/5e2a30862ce5143e9d1942db01df74b2812a89ce/scripts/bundle.ts).

In this configuration, I would like to be able to generate cjs code that would never be imported in ESM and follows node convention for default export.

**Comment by hyrious** [comment]
I guess what you're expecting is to let esbuild output `module.export = X` when the source code is `export default X`? This can cause problems when there's not only one export name. Rollup will give you a warning in this case and it also provides an [option](https://rollupjs.org/guide/en/#outputexports) to tweak that. esbuild on the other hand only provides one way to convert esm to cjs.

Instead of waiting for esbuild to introduce more options, I think the best way to solve your current issue is writing a cjs wrapper that re-exports esm source like:

```js
import react from './src'
module.exports = react
```

..and bundle the wrapper into the cjs dist file.

Note that you may also use the [stdin](https://esbuild.github.io/api/#stdin) option to create the wrapper in your build script.

**Comment by ArnaudBarre** [comment]
This hurts my eyes to use `import` and `module.exports` together, but this works really well.

**Comment by ArnaudBarre** [comment]
Thanks for the hack, I think this should be the minimum price to pay to continue using default export in library, otherwise people won't stop to do it 😄
