### ISSUE TITLE
Unexpected identifier 'production'  when using process.env.NODE_ENV in define

### ISSUE THREAD

**Issue by bosheski** [evanw/esbuild#2737]
I'm trying to make my own bundler for a codesandbox clone that I'm making but I've come accross this bug where I'm doing the following:
![image](https://user-images.githubusercontent.com/30408073/206948425-9046c68b-32f5-4b7f-986d-50de6c986290.png)

Upon bundling my code I get this error: 
![image](https://user-images.githubusercontent.com/30408073/206948495-268ae17e-fda8-4659-8359-dd68c4065f51.png)

For some reason process.env.NODE_ENV keeps getting added as a string instead of a value
![image](https://user-images.githubusercontent.com/30408073/206948566-ae956cd6-5a77-498e-88a9-8326cd8589ea.png)
I've tried doing export NODE_ENV=production as I'm on OS X but it just doesn't want to work.

Any ideas how I could solve this issue?

**Comment by evanw** [comment]
Sorry, I'm not sure exactly what you're saying. You said this:

> For some reason process.env.NODE_ENV keeps getting added as a string instead of a value

But then you pasted an error that looks like it's getting added as a value instead of a string. Then you also posted a picture of a syntax error that is neither a string replacement nor a value replacement.

Please post a self-contained code sample that reproduces the problem along with the esbuild command used.

**Comment by bosheski** [comment]
It ended up being a local Issue, upon creating a code-sandbox environment the code worked.
Sorry for raising the issue this can be closed.
