### ISSUE TITLE
Bundling esbuild with esbuild (deno)

### ISSUE THREAD

**Issue by danielr1996** [evanw/esbuild#2739]
I'm trying to bundle a cli application with esbuild that uses esbuild internally to dynamically load modules. Now when i `deno run` tobundle the cli prints 
```
Usage:
  esbuild [options] [entry points]

Documentation:
  https://esbuild.github.io/

Repository:
  https://github.com/evanw/esbuild
....
```

Which seems to be the same as when running esbuild itself in cli mode, could there be a scoping problem when bundling files with esbuild that themself consume esbuild as a library? Not however that bundling the same file with `deno bundle` or running the unbundled file with `deno run` executes my cli and works as expected. 

I've provided a repo explaining the behaviour at https://github.com/danielr1996/esbuild-issue-2739

**Comment by evanw** [comment]
The problem appears to be that esbuild believes it's the main module because of [the following code](https://github.com/esbuild/deno-esbuild/blob/3667bedb577025c305d284b7f1c1fa44ee33c93d/mod.js#L1948-L1958):

```js
if (import.meta.main) {
  Deno.run({
    cmd: [await install()].concat(Deno.args),
    cwd: defaultWD,
    stdin: "inherit",
    stdout: "inherit",
    stderr: "inherit"
  }).status().then(({ code }) => {
    Deno.exit(code);
  });
}
```

You could work around that with something like this in your initial build: `define: { 'import.meta.main': 'false' }`.

The next problem you will hit is that the plugin you're using does not use the `js` loader for anything served via https://raw.githubusercontent.com/ because that server always uses the content type `text/plain` instead of `application/javascript`. You will probably need to either use a different plugin or a different server to fix that, but you'll have to figure out what to do there.

**Comment by evanw** [comment]
I'm closing this issue because it's possible to bundle esbuild like this (with the adjustment mentioned above), and the remaining problem is a problem with a plugin, not with esbuild.
