### ISSUE TITLE
format=iife and target=es5

### ISSUE THREAD

**Issue by vforsh** [evanw/esbuild#275]
When I use this arguments combination `--format=iife --target=es5` the resulting file contains `(() => {})()` instead of good ol' `(function() {})()`. I suppose that is an issue since arrow functions were introduced in **ES6** and not ES5.

**Comment by photonstorm** [comment]
ES5 isn’t a valid target: https://github.com/evanw/esbuild#javascript-syntax-support

**Comment by evanw** [comment]
This is actually already fixed on master. I realized this late last night and fixed it but I haven't done a new release yet. The fix should be out sometime today.

> ES5 isn’t a valid target: https://github.com/evanw/esbuild#javascript-syntax-support

It is actually. I added it recently so you can tell esbuild to not introduce ES6 syntax even though there isn't any in the input. For example, without this flag esbuild will replace string literals containing newlines with template literals because they are shorter.

**Comment by vforsh** [comment]
Thanks a lot for a quick fix

**Comment by photonstorm** [comment]
@evanw probably worth updating the README too, then, as it still says ES6 is as low as it will go. Although from what you said, it doesn't sound like a transpile target (in the traditional Babel sense), more a "hands-off" flag?
