### ISSUE TITLE
Minify obvious results

### ISSUE THREAD

**Issue by rentalhost** [evanw/esbuild#2756]
Real case:

```
const cacheEnabled = () => true

if (cacheEnabled()) {
    console.log("cache is enabled")
}
```

Since `cacheEnabled` is just a function that returns `true` in 100% of cases, then you could replace it directly:

```
// Step 1:
if (true) {
    console.log("cache is enabled")
}

// Step 2: (same as Terser result)
console.log("cache is enabled")
```

I use this methodology to "mock" this function during testing to disable caching. However, when compiling for production, this function is no longer needed, as the cache is always enabled.

**Comment by evanw** [comment]
I recommend using the `define` feature with esbuild instead: https://esbuild.github.io/api/#define

**Comment by rentalhost** [comment]
I believe `define` can help in my case. But wouldn't this type of optimization be interesting for other cases?

```ts
const john = { isLogged() {return true } }

const isLogged = (user) => {
    return user.isLogged();
}

console.log(isLogged(john)) // ==> console.log(john.isLogged())
```

**Comment by evanw** [comment]
What you are suggesting can be quite complicated to implement correctly, especially when bundling cross-module code that can potentially access variables before they are declared using hoisted exported functions. Depending on the declaration, those variables are then either supposed to have a value of `undefined` or throw an error due to the temporal dead zone. Compared to that, the implementation of `define` is trivial and quite robust.
