### ISSUE TITLE
Transform produces invalid code for sources containing direct eval

### ISSUE THREAD

**Issue by micschro** [evanw/esbuild#2761]
When this code 
```
// source
if (true) { 
  function foo () {};
  eval(''); 
}
```
is transformed with default settings in esbuild 0.16.10, esbuild produces the following invalid output

```
// transformed
if (true) {
  let foo = function() {
  };
  var foo = foo;
  ;
  eval("");
}
```

=> Identifier 'foo' has already been declared

To reproduce, just call the transform API like this: 

```
// index.js
console.log(require('esbuild').transformSync(`if (true) { function foo () {}; eval(''); }`).code)
```

I'm aware that [direct eval should be avoided](https://esbuild.github.io/content-types/#direct-eval), but esbuild still should be able to produce valid output when it is used in the sources.

**Comment by evanw** [comment]
The reason why esbuild does this is because function hoisting semantics depends on strict mode. If this code is followed by `console.log(foo)` and evaluated, it will print `foo` in non-strict mode but it will throw an error in strict mode. The transformation that esbuild does here is intended to preserve the original semantics of the input (which was in non-strict mode) even when the output is evaluated in strict mode.

It might be impossible to preserve the original semantics of the input like this while also preserving the names of these symbols for direct `eval`. So perhaps the answer here is to not do this transformation when direct `eval` is present. This means that direct `eval` will be able to reference `foo` but the final code may end up behaving differently from the original code since the original function hoisting semantics were not preserved.
