### ISSUE TITLE
Support Haiku as target platform/OS

### ISSUE THREAD

**Issue by aldipower** [evanw/esbuild#2772]
Nowadays a lot of packages are using esbuild, which is a great achievement.
But I am starting to love the Haiku OS (an open source successor of BeOS).
Node and even Yarn are running just fine on Haiku, but unfortunately 'esbuild' isn't. The 'haiku' target platform is not supported is esbuild telling me.
This effectively means, because esbuild is getting more and more attention, I cannot use the Node ecosystem on Haiku. :(

Is there a way to bring esbuild to Haiku? 
Not sure how I can help with this?

**Comment by evanw** [comment]
As far as the native esbuild executable: It looks like the Go compiler doesn't officially support Haiku OS (it's not in `go tool dist list`), in which case this isn't going to be something that esbuild can officially support. I see that there's a fork of the Go compiler for Haiku OS. You are welcome to try to use it build esbuild yourself, but you'll be on your own.

Depending on your requirements, a simpler approach could be to use the WebAssembly version of esbuild instead: https://esbuild.github.io/getting-started/#wasm. It's much slower than the native esbuild executable and certain features aren't supported, but many people still use esbuild this way. It should just work without any effort on your part assuming node and yarn are already working.

I'm closing this issue because Go not supporting Haiku OS is not something that esbuild can do anything about.
