### ISSUE TITLE
[plugin api] Side effect import kind?

### ISSUE THREAD

**Issue by joelmoss** [evanw/esbuild#2777]
In the plugin API, a [side effect import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#import_a_module_for_its_side_effects_only) (`import "module-name"`) currently has a `kind` of `import-statement`, which is obviously correct.

However, it would be really useful to be able to know if the import is a side effect import. Perhaps with a kind of `side-effect-import-statement`.

**Comment by evanw** [comment]
These are considered to be the same import kind because both esbuild itself and the JavaScript language consider these to be the same thing (i.e. there is no concept of a “side effect import” in the JavaScript specification). Having these behave differently would be a deviation from how JavaScript works, which isn’t something that I think esbuild should encourage. 

Also it would be incorrect for plugins to try to use this information to change how the imported module behaves based on whether the import has names or not because a code base could contain both imports with names and without names, which makes doing this ambiguous and error-prone. What would likely happen in practice is that the build behavior would become non-deterministic as esbuild’s multithreaded architecture would cause the plugin to encounter these import statements in different orders for different build runs.

**Comment by joelmoss** [comment]
Fair enough. thx for the fast response 👏
