### ISSUE TITLE
Support NPM Specifiers

### ISSUE THREAD

**Issue by codesculpture** [evanw/esbuild#2782]
Its nice to support npm specifiers in Deno. Since NPM specifiers is a good feature in Deno. Thank You

**Comment by evanw** [comment]
I don’t use Deno myself but I think this is basically a request for replicating all of `npm install` in esbuild? I consider that to be out of scope for esbuild since that would be a very complex feature. You are welcome to attempt to do this yourself in an esbuild plugin if you’d like. You can also use `--external:npm:*` to leave these paths in the bundle for Deno to interpret if that would be helpful.

**Comment by codesculpture** [comment]
Yeah it may complex. Im thinking about to create plugin. So it would be great. Since esbuild is not for Deno particularly. And thanks for reply!
