### ISSUE TITLE
esbuild 0.16.14 failing to install

### ISSUE THREAD

**Issue by almazgaliev** [evanw/esbuild#2796]
i tried

```sh
npm install -g esbuild
```
and it outputs:
```
npm ERR! code 1
npm ERR! path /home/user/.node/lib/node_modules/esbuild
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! /home/user/.node/lib/node_modules/esbuild/install.js:130
npm ERR!     throw new Error(`Expected ${JSON.stringify("0.16.14")} but got ${JSON.stringify(stdout)}`);
npm ERR!           ^
npm ERR! 
npm ERR! Error: Expected "0.16.14" but got "0.16.13"
npm ERR!     at validateBinaryVersion (/home/user/.node/lib/node_modules/esbuild/install.js:130:11)
npm ERR!     at /home/user/.node/lib/node_modules/esbuild/install.js:277:5

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2023-01-05T16_58_48_918Z-debug-0.log

```

its similar to #1851 and #1852

**Comment by evanw** [comment]
Installing version 0.16.14 works fine for me, so I don’t think this is similar to #1851 and #1852. 

I noticed you are trying to install esbuild globally. This isn’t typically how esbuild is installed. I assume you previously installed version 0.16.13 this way. Perhaps npm has bugs when packages that require specific versions of dependencies like esbuild are installed globally?

In that case you can either a) install esbuild locally within a project instead of installing it globally or b) uninstall the old globally-installed version of esbuild before installing the new version. You may also want to consider updating your version of npm if it’s old because whatever bug that’s causing this may have been fixed.

**Comment by almazgaliev** [comment]
@evanw  im sorry, i actually tried `npm i -g vite@latest` first, but it installs esbuild as dependency so after that i tried to install esbuild only , in both cases output was the same. it might be that vite causes this error.

i use:
* npm 8.19.2
* node 16.19.0

**Comment by almazgaliev** [comment]
.

**Comment by almazgaliev** [comment]
i tried on other pc, it works, i dont know what could cause this

**Comment by unitythemaker** [comment]
> i tried on other pc, it works, i dont know what could cause this

I got the same problem on Arch Linux. I am not using esbuild directly but via dependency. I had installed esbuild package as a system command. It had a later version of esbuild and I had an older version in the project. I removed the system package but I am getting a way more complicated message now. I hope I will fix that one soon too.

**Comment by unitythemaker** [comment]
Fixed! I had [this issue](https://github.com/evanw/esbuild/issues/2812) and solved it via the [comment by evanw](https://github.com/evanw/esbuild/issues/2812#issuecomment-1377505836)
