### ISSUE TITLE
Are you considering writing tsserver in golang?

### ISSUE THREAD

**Issue by pie6k** [evanw/esbuild#280]
Currently, the biggest issue in terms of performance with TS is not related to build time, but with ide typescript support (autocomplete, autoimports etc).

Are you considering giving it a try? That would be amazing to have 10x faster developer experience when working with TS code :)

**Comment by evanw** [comment]
No, I am not considering that since doing that would be a massive ongoing maintenance burden. That's basically signing up to manually port every single commit to the TypeScript project going forwards, forever. I agree that it'd be great for the TypeScript compiler itself to be faster but realistically that decision has to be made by the TypeScript compiler team itself. I have some more thoughts here: https://github.com/evanw/esbuild/issues/101#issuecomment-626424174.
