### ISSUE TITLE
Bug: ES2016 with async arrow function creates unexpected `export default`

### ISSUE THREAD

**Issue by Ayc0** [evanw/esbuild#2807]
When using the`async` keyword with the target `es2016`, it adds an `export default`, causing a crash with a `Uncaught SyntaxError: Unexpected token 'export'`

**version:** 0.16.16 (but I also noticed that on all version down to [0.11.13](https://hyrious.me/esbuild-repl/?version=0.11.13&mode=build&modules=%5B%5B%22a.js%22%2C%22const+a+%3D+async+%28%29+%3D%3E+%7B%7D%3B%5Cn%5Cna%28%29%3B%22%2C1%5D%5D&buildOptions=%7B%22bundle%22%3Atrue%2C%22format%22%3A%22esm%22%2C%22splitting%22%3Afalse%2C%22target%22%3A%22es2016%22%2C%22platform%22%3A%22browser%22%2C%22sourcemap%22%3Afalse%7D) (before the REPL I'm using crashes, so I couldn't check))

## Reproduction 

With the target `esnext`, everything behaves properly ([link to REPL](https://hyrious.me/esbuild-repl/?version=0.16.16&mode=build&modules=%5B%5B%22a.js%22%2C%22const+a+%3D+async+%28%29+%3D%3E+%7B%7D%3B%5Cn%5Cna%28%29%3B%22%2C1%5D%5D&buildOptions=%7B%22bundle%22%3Atrue%2C%22format%22%3A%22esm%22%2C%22splitting%22%3Afalse%2C%22target%22%3A%22esnext%22%2C%22platform%22%3A%22browser%22%2C%22sourcemap%22%3Afalse%7D)):

<img width="1502" alt="image" src="https://user-images.githubusercontent.com/22725671/211293188-9ab11587-78a3-4a85-9a7f-480e09d5cb4b.png">

Note: [es2017](https://hyrious.me/esbuild-repl/?version=0.16.16&mode=build&modules=%5B%5B%22a.js%22%2C%22const+a+%3D+async+%28%29+%3D%3E+%7B%7D%3B%5Cn%5Cna%28%29%3B%22%2C1%5D%5D&buildOptions=%7B%22bundle%22%3Atrue%2C%22format%22%3A%22esm%22%2C%22splitting%22%3Afalse%2C%22target%22%3A%22es2017%22%2C%22platform%22%3A%22browser%22%2C%22sourcemap%22%3Afalse%7D), [es2018](https://hyrious.me/esbuild-repl/?version=0.16.16&mode=build&modules=%5B%5B%22a.js%22%2C%22const+a+%3D+async+%28%29+%3D%3E+%7B%7D%3B%5Cn%5Cna%28%29%3B%22%2C1%5D%5D&buildOptions=%7B%22bundle%22%3Atrue%2C%22format%22%3A%22esm%22%2C%22splitting%22%3Afalse%2C%22target%22%3A%22es2018%22%2C%22platform%22%3A%22browser%22%2C%22sourcemap%22%3Afalse%7D) work fine

But with the target `es2016`, we can see that it adds an `export default` ([link to REPL](https://hyrious.me/esbuild-repl/?version=0.16.16&mode=build&modules=%5B%5B%22a.js%22%2C%22const+a+%3D+async+%28%29+%3D%3E+%7B%7D%3B%5Cn%5Cna%28%29%3B%22%2C1%5D%5D&buildOptions=%7B%22bundle%22%3Atrue%2C%22format%22%3A%22esm%22%2C%22splitting%22%3Afalse%2C%22target%22%3A%22es2016%22%2C%22platform%22%3A%22browser%22%2C%22sourcemap%22%3Afalse%7D)):
<img width="1490" alt="image" src="https://user-images.githubusercontent.com/22725671/211293311-0ed63464-52fc-4410-af4b-6c4349243950.png">

Here is the full bundle config:

```json
{
  "bundle": true,
  "format": "esm",
  "splitting": false,
  "target": "es2016",
  "platform": "browser",
  "sourcemap": false
}
```

Note: [es2015](https://hyrious.me/esbuild-repl/?version=0.16.16&mode=build&modules=%5B%5B%22a.js%22%2C%22const+a+%3D+async+%28%29+%3D%3E+%7B%7D%3B%5Cn%5Cna%28%29%3B%22%2C1%5D%5D&buildOptions=%7B%22bundle%22%3Atrue%2C%22format%22%3A%22esm%22%2C%22splitting%22%3Afalse%2C%22target%22%3A%22es2015%22%2C%22platform%22%3A%22browser%22%2C%22sourcemap%22%3Afalse%7D) crashes too

**Comment by evanw** [comment]
> causing a crash with a `Uncaught SyntaxError: Unexpected token 'export'`
>
> ...
>
> Here is the full bundle config:
> 
> ```json
> {
>   "format": "esm",
> }
> ```

If you're getting a crash like this, then you're using esbuild incorrectly. You have told esbuild to generate ESM output but you are then not running esbuild's output as ESM. That is not a problem with esbuild. You need to either run the output as ESM (e.g. with `<script type=module>`) or you need to set the output format to something other than ESM (e.g. `iife`).

**Comment by hyrious** [comment]
Despite of runtime issue, the `export default` also present in transform mode with [`--supported:async-await=false --format=esm`](https://hyrious.me/esbuild-repl/?version=0.16.16&mode=transform&input=async+e%3D%3Ee&options=--format%3Desm+--supported%3Aasync-await%3Dfalse).

This is because:

1. The lowering process converts `async () => {}` to an expression that references to top-level `this`:

   ```js
   () => __async(this, null, function* () {
   });
   ```

   Note that `async function() {}` doesn't get affected because it wraps `this` into a function body.

2. esbuild then try to guess the file format by content, and it sees a top-level `this`, it assumes the file is in CJS.

3. Transforming CJS to ESM format (`--format=esm`) needs a wrapper function `__commonJS` and is assigned to the es module's default export, this is because in which case we can convert `this.a = 1` to something like `export default { a: 1 }`. [repl](https://hyrious.me/esbuild-repl/?version=0.16.16&mode=transform&input=this&options=--format%3Desm)

That's why there's an `export default`.

**Comment by Ayc0** [comment]
I see, thanks for the explanation!
