### ISSUE TITLE
Allow to customize output extension

### ISSUE THREAD

**Issue by egoist** [evanw/esbuild#281]
To have both ES module and CommonJS module co-exist in a Node.js package, we need to use different extensions, https://nodejs.org/api/esm.html#esm_enabling

**Comment by evanw** [comment]
I added a new flag for this: `--out-extension:.js=.mjs` (as well as JavaScript and Go APIs). It's a mapping instead of a single value because I plan to have more file types in the future such as CSS and HTML, and you may want to customize those output extensions too. This was published in esbuild version 0.6.6.

**Comment by tonyxiao** [comment]
Is it possible to transform the file extension in `require` statement too? Otherwise when I try to transform esm into cjs the require statement still says `require('*.js')` which would of course fail if the out extension has been changed to `*.cjs`
