### ISSUE TITLE
Put download directly from NPM behind flag?

### ISSUE THREAD

**Issue by ph08n1x** [evanw/esbuild#2820]
Hey there!

Currently I am trying to get `esbuild` to work in a certain environment where it is seen as unsecure to "directly download from NPM".

However in this environment I can use the NPM command line which then in turn will safely use the proxy.

The issue is in the [`checkAndPreparePackage`](https://github.com/evanw/esbuild/blob/main/lib/npm/node-install.ts#L232) method. The method will safely attempt to find the binary package via the NPM but if this fails to find the package, the install script goes ahead and [contacts NPM directly](https://github.com/evanw/esbuild/blob/main/lib/npm/node-install.ts#L281) which in my case I can't allow.

I was wondering is there any chance we could put that `downloadDirectlyFromNPM` behind some kind of flag (that by default is set to `true`)?

Loving this tool btw, thank you so much for it's creation!

**Comment by hyrious** [comment]
You can use `--ignore-scripts` during `npm add esbuild` or `pnpm add esbuild` to prevent its `postinstall` script being executed.

Further more, you can add `--no-optional` to skip downloading optional dependencies (`@esbuild/*`) too if you want to totally control the assets in your node_modules.

**Comment by ph08n1x** [comment]
Thanks for the reply! Sadly none of those options are available to my environment.

I cannot add arguments to my install command

I.e. I need people to be able to run `npm i esbuild' from a private NPM registry.

I did see however there is a 'ESBUILD_BINARY_PATH' so I could use this but then I would have to write my own script that essentially does the same as the `esbuild` install script i.e. find out your platform & arch to install the correct npm binary package.

The only viable option I have got close to is replacing the install script with my own custom one that removes this line of code... which I then replace in the `postinstall` npm script.

**Comment by evanw** [comment]
> Currently I am trying to get `esbuild` to work in a certain environment where it is seen as unsecure to "directly download from NPM".

Can you say why this is? I'm curious about your threat model. You're talking about a package that's originally hosted on npm. Mirroring it doesn't make the contents of the package any safer, so if downloading the original is dangerous then wouldn't downloading the mirrored copy be dangerous too? I assume you aren't manually auditing the contents of the esbuild package when you mirror it because it's a 9mb binary blob, which means you're probably already blindly trusting that the package contents are benign? If you have concerns about the contents of the esbuild package, then the safest thing to do would probably be to build it from source yourself instead of trusting the contents on npm.

**Comment by evanw** [comment]
Marking as unactionable due to lack of a reply.

**Comment by evanw** [comment]
Closing due to being `unactionable` without a follow-up reply.
