### ISSUE TITLE
esbuild + linaria + jest = ❌ -- Plugins and the Transform API

### ISSUE THREAD

**Issue by dfrkp** [evanw/esbuild#2821]
We are using esbuild, preact, and linaria for our website. We've used cypress for e2e testing, but we would like to add jest. To do that, I looked at this project:
https://github.com/hannoeru/jest-esbuild

Unfortunately, it breaks as soon as linaria style `css` statements are encountered because it isn't aware of the required plugin.

I know that the Transform API is not supporting plugins by design, but I need more ideas on how to get this to work.

Here's the build config we use for more context.
```javascript
const linaria = require("@linaria/esbuild");
const prod = process.env.NODE_ENV === "production";

module.exports = {
  entryPoints: ["./src/index.tsx"],
  loader: { ".svg": "dataurl", ".webp": "file" },
  assetNames: "assets/[name]-[hash]",
  outdir: "dist",
  jsxFactory: "h",
  jsxFragment: "Fragment",
  bundle: true,
  plugins: [
    linaria.default({
      sourceMap: prod,
    }),
  ],
};
```

Any chance the discussion around supporting plugins in the transform API can be re-opened?

**Comment by hyrious** [comment]
I'm afraid that it's not about transform api to support plugins, but about jest does not support async transformers. As you can see in [jest-esbuild](https://github.com/hannoeru/jest-esbuild/blob/main/src/index.ts#L66), you can only use sync apis in jest context. Plugins are not supposed to run in sync mode since they can have async callbacks.

**Comment by dfrkp** [comment]
> I'm afraid that it's not about transform api to support plugins, but about jest does not support async transformers. As you can see in [jest-esbuild](https://github.com/hannoeru/jest-esbuild/blob/main/src/index.ts#L66), you can only use sync apis in jest context. Plugins are not supposed to run in sync mode since they can have async callbacks.

Actually, jest has support for async transformers (only in esm mode though). I already forked [jest-esbuild](https://github.com/hannoeru/jest-esbuild/blob/main/src/index.ts#L66) and made the necessary changes locally, but then I ran into the issue with the transform API...

**Comment by evanw** [comment]
The `transform` API is basically a very limited special case of the `build` API. It's nicer to use if your use case fits within the limits, but if it doesn't then you'll want to use the `build` API instead.

Plugins aren't enabled for the transform API because they'd be pretty useless. The transform API doesn't support loading files from the file system so the `onResolve` and `onLoad` plugin callbacks wouldn't ever be called. That leaves the other two plugin APIs: `onStart` and `onEnd`. But you don't need plugins for those two things either. If you want to run code before and/or after your call to `transform`, you can just put your code before and/or after your call to `transform`.

**Comment by evanw** [comment]
I'm closing this issue because I'm not planning on adding plugins to the transform API. Plugins are intended to be used with the build API, which is more general. You can use the [stdin](https://esbuild.github.io/api/#stdin) feature of the build API to pass it a string similar to the transform API if that helps.

**Comment by robwierzbowski** [comment]
@dfrkp, Did you resolve your issue? I've been hacking on the esbuild-transformer-jest repo and am not sure I can consistently trigger the async transform when needed.
