### ISSUE TITLE
[suggestion] allow onLoad to return a promise

### ISSUE THREAD

**Issue by eng-dibo** [evanw/esbuild#2825]
in your examples, particularly in the http example,  you use async & await to download the content like this
![image](https://user-images.githubusercontent.com/57308531/212502516-d26ccd70-1c3d-428a-8eb8-9290f1df6304.png)

I suggest that you allow the content to be of type `string | Promise<string>`, if it is a promise just wait until it resolves.
so, the snippt would be like this 
```
// we don't need to use async
 build.onLoad({ filter: /.*/, namespace: 'http-url' }, (args) => {
      let contents =  new Promise((resolve, reject) => {
      ...
      }
}
```

**Comment by evanw** [comment]
I'm confused. That code is already returning a promise because every `async` function in JavaScript [automatically returns a promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function#return_value). I recommend reading more about how asynchronous code in JavaScript works. TL;DR: Instead of changing the API to `return { contents: somethingAsync() }` you use the current API and either do `return somethingAsync().then(x => ({ contents: x }))` in a non-`async` function or `return { contents: await somethingAsync() }` in an `async` function. They are equivalent, and mean the same thing. I'm closing this issue because there's nothing to do (`onLoad` is already allowed to return a promise, as is demonstrated by the example code in your post).

**Comment by eng-dibo** [comment]
no, I mean if `content` is Promise, esbuild have to wait until it resolved

**Comment by evanw** [comment]
Ah, I see. Your request was to "allow onLoad to return a promise" which is why I responded that onLoad is already allowed to return a promise. I see you're saying that you're asking for esbuild to additionally support `content` being a promise too.

In that case: thank you for the suggestion, but I don't think this is necessary so I'm not planning to do this. Instead of doing `return { content: promise }` you can either do `return { content: await promise }` or `return promise.then(x => ({ content: x }))`. This is sufficiently similar that I don't think it needs to be built in to the API itself.

**Comment by eng-dibo** [comment]
> return promise.then(x => ({ content: x }))

this one is awesome, and will do the trick.
