### ISSUE TITLE
Allow Serve to use http.Handler

### ISSUE THREAD

**Issue by shyim** [evanw/esbuild#2831]
The context API looks cool with Serve, but I would need in my own Go app 2 HTTP Servers to serve the files.

So It would be nice if Serve would support the default `http.Handler` so I can bind ESBuild directly to my already existing server and not block a second port.

**Comment by evanw** [comment]
The interface for the Go API is deliberately as identical as possible to the JS API. Nothing will be added to the Go API that doesn't also make sense for the JS API, since the JS API is the primary use case and the Go API is the secondary use case. So I won't be adding the `http.Handler` interface.

The way to customize the server is to use a proxy, as is described in the documentation: https://esbuild.github.io/api/#serve-proxy.
