### ISSUE TITLE
Multiple dependencies bundled with esbuild in watch mode doesn't cascade

### ISSUE THREAD

**Issue by baptisteArno** [evanw/esbuild#2834]
I have a library that imports another library.

When both are running esbuild watch mode, I would expect that this library re-bundle when the imported library is re-bundled. But that doesn't happen.

Is there anything I can do to make it work?

**Comment by evanw** [comment]
Can you provide a way to reproduce the issue?

**Comment by baptisteArno** [comment]
I'll try to reproduce with a minimal example.

But that can be easily understood => Because the `node_modules` folder is ignored, the freshly bundled imported library wouldn't trigger the build of its consumer.

Is there any way to say to esbuild: "Also watch the `dist` folder of this specific library to trigger the bundle again"

**Comment by evanw** [comment]
> But that can be easily understood

I'm asking for a way to reproduce the issue because I don't understand what you're saying. Watch mode is supposed to check all of the inputs to the build. If one of those has changed, then the build needs to be redone, otherwise it doesn't. So I'm not sure if you're saying that esbuild's watch mode has a bug that's failing to pick up a change to an input to the build, or if you're using some buggy esbuild plugin that's not specifying dependencies correctly, or something else. I don't know why you're talking about `node_modules` because esbuild's watch mode doesn't discriminate between thing inside of `node_modules` vs. outside. I'm not really sure what you're saying at all, sorry.
