### ISSUE TITLE
The built-in server responds to `HEAD` requests with 404

### ISSUE THREAD

**Issue by arnog** [evanw/esbuild#2851]
I don't have a simple test case to share, however, the `ServeHTTP()` function in `pkg/api/serve_other.go` file does indeed seem to only handle `GET` (line 129). Instead it should probably handle `HEAD` and `GET` similarly, but avoid doing a rebuild or returning a body for `HEAD`.

**Comment by evanw** [comment]
I can add support for `HEAD`. I think it would have to trigger a build though since you can't know whether the path in the URL is valid or not without doing a build.

What are you using `HEAD` for? It could be good for me to know why you need this in case it's relevant when I'm working on the dev server.

**Comment by arnog** [comment]
Yes, I see your point about the rebuild. It probably won't be required in most cases, but I guess it doesn't really hurt.

My use case is as follow: I need to determine the URL of a file located next to the library file (it's some ancillary assets (fonts) that I need to load dynamically). In order to do that I need to resolve the URL of the library file, as in some cases (when using CDNs) the actual URL can be behind some redirects. Using a `GET` would work, but it's inefficient since I don't need the payload, just the resolved URL. `HEAD` satisfies this by return the resolved URL, which I can then use as a base to locate the ancillary files.

Those assets have been manually copied into the `servedir` during a build step prior to invoking esbuild.

**Comment by lukeed** [comment]
HEAD is also used purely for "is X still the latest?" requests via etag and/or content-length lookups (oof)

Haven't had a moment to try out 0.17.x yet, but if there's still work being done in this space, it'd be great if `serve` send down assets with weak `W/"file-hash"` etag header and then tracked/persisted that for the `serve` lifetime. Most frontend build systems that rely on ESM for development (vite, svelte kit, astro, etc) are heavily relying on this `304` pattern already. While they're not HEADs, it's related. Plus a number of backend frameworks route all HEAD requests to the GET for that route since they're identical, sans body

**Comment by arnog** [comment]
Excellent! Thanks.
