### ISSUE TITLE
Feature request: can config the registry url

### ISSUE THREAD

**Issue by lolychee** [evanw/esbuild#286]
https://github.com/evanw/esbuild/blob/2abe0243556294a5862c8c43c455e78f85d8a633/npm/esbuild/install.js#L20

idea：
config the `https://registry.npmjs.org` from `yarn config get registry` or `ENV`.

**Comment by evanw** [comment]
Can you say why you would want to do this? Is this causing esbuild to be broken for you? The install script downloads the packages from the npm registry because the packages are only ever published to the npm registry.

**Comment by LanceZhu** [comment]
In China, can not download this package from the npmjs registry or the speed is very slow. If can config the registry url, we can download from [cnpm](https://cnpmjs.org/) or similar mirror site.

**Comment by Benoit-Vasseur** [comment]
Kind of related, I am behind a proxy and the request seems not to take my HTTPS_PROXY export into account.

**Comment by evanw** [comment]
Version 0.6.6 should now respect the configured npm registry. Read [the release notes](https://github.com/evanw/esbuild/blob/2b48759a923209dcb67542df254ed68dcfa09317/CHANGELOG.md#066) for more details.

Note that I haven't fully tested this so it'd be great to get independent confirmation that it works as expected. I only verified that the configuration setting causes the download to be redirected to the new domain instead of going to the npm registry.
