### ISSUE TITLE
Default import getting renamed when bundling

### ISSUE THREAD

**Issue by mayank99** [evanw/esbuild#2867]
consider these files:
```js
// index.mjs
import Foo from './foo.mjs';
const hello = 'hello';
console.log(hello, Foo.world);
```
```js
// foo.mjs
export default { world: 'world' };
```

running `esbuild index.mjs --bundle --format=esm` leads to this output:
```js
// foo.mjs
var foo_default = { world: "world" };

// index.mjs
var hello = "hello";
console.log(hello, foo_default.world);
```

Is there a way to preserve the original import name? so instead of `foo_default`, i want `Foo`.

I tried the `--keep-names` option, but it didn't have any effect. when used together with `---minify`, it also doesn't keep the name of the other variable (`hello`).
```js
var o={world:"world"};var l="hello";console.log(l,o.world);
```

**Comment by evanw** [comment]
No, there is no way to preserve the original name. Why are you asking this?

**Comment by mayank99** [comment]
I'm trying to use esbuild to "resolve all imports" in a file before executing parts of a file. It is much easier to execute parts from the original, untransformed file if esbuild leaves the names unchanged. For example:
```
import A from './A'; // esbuild will resolve this
import B from './B'; // esbuild will resolve this

export const a = `${A}`; // this will be executed first
export const b = `${B}`; // this will be executed separately
```

But since the names get changed, I would need to figure out how to parse the source maps produced by esbuild and use those find `a` and `b` in the bundled file and execute those.

**Comment by evanw** [comment]
There isn't enough information in your comment for me to understand what you mean, sorry. But if you are doing partial evaluation of files, I'm guessing you would probably be better off using a library more meant for that purpose (e.g. one that provides access to an AST).

The reason why esbuild doesn't provide control over variable names like this is that it shouldn't matter. The way you are supposed to use esbuild is you're supposed to bundle your code into a file in one of the three output formats: `iife`, `esm`, or `cjs`, and then run the bundled output file that esbuild generates as that output format. If you do that, then all three of esbuild's output formats run in a local scope where local variables are inaccessible to all other code. IIFE has a local scope because it uses a function closure, ESM has a local scope because JavaScript runtimes provide one for ESM code (e.g. using `<script type=module>` in the browser or `.mjs` in node), and CommonJS has a local scope because node wraps CommonJS modules in a function body. If what you're trying to do doesn't involve bundling some code and then running it as-is, then your needs could be outside of esbuild's scope as a bundler.

**Comment by mayank99** [comment]
I am already using a different library for AST parsing, but it won't help me resolve imports.

Ideally, I would just ask Node to resolve the imports when executing inside [`vm`](https://nodejs.org/api/vm.html), but this doesn't currently support ESM without a [flag](https://nodejs.org/api/vm.html#class-vmmodule), so I thought of using esbuild for inlining the imports.

I understand this is a very niche use case outside of esbuild's scope, so I will close this. I might be able to make something work using esbuild's sourcemaps. Thanks for the response.
