### ISSUE TITLE
No matching export for `import {A,B}`  when `export default {A,B}`

### ISSUE THREAD

**Issue by zxj5470** [evanw/esbuild#2880]
esbuild version: 0.17.5

files:
- clazz.js
- main.js
- esbuild.js

```js
// clazz.js
class A {}
class B {}

export default {
    A,
    B
}
```

```js
// main.js
import { A, B } from "./clazz";
console.log({A,B});
```

```js
// esbuild.js
var esbuild = require("esbuild");

let t1 = new Date();

esbuild.build({
    entryPoints: ["main.js"], 
    outfile: "build.js", 
    bundle: true, 
    minify: true, 
})
    .then(() => {
        let t2 = new Date();
        let t = (t2 - t1);
        console.log(`⚡ build ${t} ms`);
    })
    .catch(() => process.exit(1));
```

```
X [ERROR] No matching export in "clazz.js" for import "A"

    main.js:1:9:
      1 │ import { A, B } from "./clazz";
        ╵          ^

X [ERROR] No matching export in "clazz.js" for import "B"

    main.js:1:12:
      1 │ import { A, B } from "./clazz";
```

Is there something wrong in ES6 configuration?

If I use legacy js module export usage
```js
module.exports = {
    A, B
}
```
instead of `export default`, It's OK.

Here's permutation table for clazz.js and main.js

| clazz export file | main import file | result |
|---|---|---|
| `module.exports` | `import {A,B} from "./clazz"` | OK |
| `export default {A,B}` | `import {A,B} from "./clazz"` | × |
| `export default {A,B}` | `import Clazz from "./clazz"; const {A,B} = Clazz;` | OK |

So is there a way to use `export default` to make the second one correct?

**Comment by evanw** [comment]
> So is there a way to use `export default` to make the second one correct?

No there isn't, but there isn't supposed to be. I'm closing this issue because this isn't how JavaScript works so this also shouldn't be how esbuild works. You'll have to use correct JavaScript syntax when using esbuild to bundle your JavaScript.

One option that's missing from your table is `export default {A,B}; export {A,B}`. That would work. But that's not "using `export default` to make the second one correct."
