### ISSUE TITLE
Error handlers URL for `context.serve` / support SPA

### ISSUE THREAD

**Issue by tinovyatkin** [evanw/esbuild#2904]
Thank you for great enhancements for esbuild server on 0.17.x!

It would be fantastical if we can specify URL for error handler for `context.serve` and open a way to support SPA / routing, like:

```js
const server = await context.serve({
  port: PORT,
  servedir: config.outdir,
  errorUrls: {
    404: '/index.html',
  },
  onRequest({ method, path, status, timeInMS }) {
    console.log(`%s %s: %d in %d ms`, method, path, status, timeInMS);
  },
});
```

alternatively (but probably way more complex to implement) would be an addition of a hook for `context.serve` like

```js
const server = await context.serve({
  port: PORT,
  servedir: config.outdir,
  onResolve({ method, pathname, servedir }) {
    if (!fs.existSync(path.resolve(servedir, pathname.slice(1))))
      return './index.html';
  },
  onRequest({ method, path, status, timeInMS }) {
    console.log(`%s %s: %d in %d ms`, method, path, status, timeInMS);
  },
});
```

**Comment by jsteuer** [comment]
That would be very helpful!

My usecase: I am developing a SPA with client-side routing.  If the developer access the application using an arbitrary URL, the frontends fixed html needs to be loaded - then client-side routing will work. Using esbuild I can't accomplish this task, since it returns "404" on routes, that are not pointing to an existing file.

Because of that I am using the watch mode in combination with [live-server](https://github.com/tapio/live-server)  and the `--entry-file` option.  This is not perfect. 

It would be great if esbuild had an option to serve a fixed file instead of returning "404".

**Comment by mbrevda** [comment]
Yes, this would be great. Especially considering the extremely popular use case of a SPA, it would be great if this could be handled without needing a proxy

**Comment by marlun** [comment]
I'm also having "problems" with this, it's so close to being a very simple solution covering my needs, all I need is the client side routing ability.

@mbrevda do you have a working repo for this example? I can't get it to work.

**Comment by mbrevda** [comment]
I don't

**Comment by evanw** [comment]
My proposed solution for this is a new `--serve-fallback=<./some-file.html>` flag. This file would be served by esbuild's dev server if a file at the requested path doesn't exist.

It seems like this would be a better fit for the desired SPA use case than the proposed solution. If the proposed `errorUrls` solution were to be implemented, then (I assume) it would only be used when esbuild would otherwise serve a 404 error. But that wouldn't happen when esbuild [serves an automatically-generated directory listing](https://github.com/evanw/esbuild/blob/bf3acc146f4d5481fd5828bbbf09aa7aecad6985/pkg/api/serve_other.go#L557-L630). For a SPA it seems like it would be better to serve a fallback page instead of a directory listing in that case.

**Comment by mbrevda** [comment]
That would be great @evanw, and should address the issue elegantly!

**Comment by mbrevda** [comment]
thanks so much!
