### ISSUE TITLE
expose hash in plugin API 

### ISSUE THREAD

**Issue by reinholdk** [evanw/esbuild#2908]
For plugins handling output on their own, it would be beneficial to expose the hash in the plugin API.
With that information, the plugin could easily detect in watch mode whether it needs to write a certain file or not.

Stripping the hash from the path could be used as a workaround, but requires manipulating source mapping URLs in case the hash shall not be included in the output path.

The hash could be exposed to the `onEnd` callback via a new property `OutputFile.hash` received as part of the `BuildResult` which should be available independently from the `entyNames`, or `assetNames` config.

**Comment by evanw** [comment]
> With that information, the plugin could easily detect in watch mode whether it needs to write a certain file or not.

I believe you want the content hash for that, not the hash in the file name, since the hash in the file name also changes when dependencies are changed even when the file content stays the same. As a plugin you are able to hash the content yourself without esbuild's help: https://nodejs.org/api/crypto.html#class-hash.

**Comment by reinholdk** [comment]
Thanks that works. Did expect a bigger performance overhead by calculating the hash again.
