### ISSUE TITLE
jsx: preserve removes jsx comments

### ISSUE THREAD

**Issue by maor-benami** [evanw/esbuild#2909]
```tsx
console.log(
  esbuild.transformSync(`const x = <h1>{/*comment*/}</h1>`, {
    format: 'esm',
    charset: 'utf8',
    jsx: 'preserve',
    loader: 'tsx',
  }).code,
)
```

Output is:

```tsx
const x = <h1 />;
```

<img width="1372" alt="image" src="https://user-images.githubusercontent.com/85426848/218279003-ac209ddb-4356-4a6d-81ff-a95c59582278.png">

**Comment by evanw** [comment]
It's not expected that running code through esbuild preserves all comments. You're not supposed to use esbuild as a code formatter because it's not meant for that. If you want to see your original code while debugging, you should be using [source maps](https://esbuild.github.io/api/#sourcemap). And if you want to format your code, you should be using a tool intended for that purpose.

**Comment by maor-benami** [comment]
I am not using it as "code formatter".
I use it to turn tsx into jsx and then parsing it with `meriyah` and `astring`

Output should be:

```tsx
const x = <h1>{/*comment*/}</h1>
```

**Comment by evanw** [comment]
> Output should be:

Why is that?

**Comment by maor-benami** [comment]
`jsx: preserve`

**Comment by maor-benami** [comment]
maybe you should consider removing this comment too

```tsx
esbuild.transformSync(`const x = "<h1><!--comment--></h1>"`)
```

**Comment by evanw** [comment]
Comments are not part of [the JSX grammar](https://facebook.github.io/jsx/#sec-jsx-elements). I'm trying to ask you why you need this, but you still haven't said why.

**Comment by maor-benami** [comment]
I did not know that

Any way, i wish to render jsx comments as html comments

**Comment by evanw** [comment]
> i wish to render jsx comments as html comments

And why is that?

**Comment by maor-benami** [comment]
because this is not valid jsx either

```tsx
const x = <h1><!--comment--></h1>
```

leaving the jsx comments as an alternative

**Comment by maor-benami** [comment]
lets settle on

```tsx
const x = <h1>{/*<!--comment-->*/}</h1>
```

**Comment by evanw** [comment]
> because this is not valid jsx either
> 
> ```tsx
> const x = <h1></h1>
> ```

I know that. But you still haven't said why you need this. Why are you wanting to author HTML comments using JSX syntax? Maybe think of it like this: what is broken by HTML comments not being there?

**Comment by maor-benami** [comment]
Because html comments are a think and are being used in rendering frameworks.
JSX is HTML mirrored inside JS... i don't think we need more then that.

Taking your approach means deviating from HTML standards for no seeable reason.

**Comment by maor-benami** [comment]
Maybe the solution is this being valid

```tsx
const x = <h1><!--comment--></h1>
```

but i think esbuild could give a hand here and at least offer a flag

**Comment by evanw** [comment]
> html comments are a thing and are being used in rendering frameworks

Can you say more about this? Which rendering frameworks do this? What are you trying to do that needs HTML comments authored by JSX syntax?

Sorry for all the questions but I'd like to actually understand why you need this, both because I want esbuild's features to be motivated by real use cases and because I need to understand how esbuild's features are being used for esbuild's ongoing maintenance (e.g. so I can write the appropriate test coverage and so I don't accidentally break them).

> Maybe the solution is this being valid
> 
> ```tsx
> const x = <h1></h1>
> ```

That's not valid JSX syntax unfortunately, so it would be invalid for esbuild's JSX parser to accept it.

**Comment by maor-benami** [comment]
I just want the option to render html comments from jsx...

i think i'd make the renderer treat `<h1>{'<!--comment-->'}</h1>` as a comment node instead

**Comment by maor-benami** [comment]
I now see that esbuild offer some escape options for legal comments with "!",
maybe they could be applied in this case (and other) no matter the use-case
