### ISSUE TITLE
Version 0.6.6 break the install with custom npm registry (e.g. cnpm)

### ISSUE THREAD

**Issue by sorrycc** [evanw/esbuild#291]
0.6.6 support custom npm registry, but the `package/-/package-version.tgz` format is not support on [the cnpm registry](https://cnpmjs.org/).

* https://registry.npmjs.org/esbuild-linux-64/-/esbuild-linux-64-0.6.7.tgz (ok)
* https://r.cnpmjs.org/esbuild-linux-64/-/esbuild-linux-64-0.6.7.tgz (not found)

![image](https://user-images.githubusercontent.com/35128/88497908-4aac5800-cff4-11ea-9d74-512dfd9d5a2b.png)

**Comment by ngbinh** [comment]
@sorrycc `0.6.7` should fix the issue

**Comment by sorrycc** [comment]
![image](https://user-images.githubusercontent.com/35128/88499823-98778f00-cff9-11ea-8df6-33a9c2732fbb.png)
@ngbinh I tested 0.6.7, don't work.

**Comment by evanw** [comment]
Sorry about that. I'm going to push another version to try to fix this. I can't guarantee that it'll work though because there appears to be a problem with cnpm itself. For example, [version 0.6.5](http://registry.npm.taobao.org/esbuild-darwin-64/0.6.5) is present but [version 0.6.6](http://registry.npm.taobao.org/esbuild-darwin-64/0.6.6) is absent (I get a 404). I have no idea why this is because I don't know anything about cnpm. To work around issues like this, I'm going to try falling back to the official npm registry if the custom one fails.

**Comment by evanw** [comment]
@sorrycc Can you try again with version 0.6.8?

**Comment by tiyunchen** [comment]
same issue
![image](https://user-images.githubusercontent.com/24793416/88748633-14054780-d184-11ea-9839-c700bbe31212.png)

**Comment by ngbinh** [comment]
@tiyunchen looks like you tried `0.6.5` instead of `0.6.8`

**Comment by tiyunchen** [comment]
`0.6.8` is ok, is the problem with esbuild-webpack-plugin

**Comment by tiyunchen** [comment]
![image](https://user-images.githubusercontent.com/24793416/88749383-bf62cc00-d185-11ea-9a67-5316c3118882.png)
