### ISSUE TITLE
Preserve IE hacks (\9) in CSS bundles

### ISSUE THREAD

**Issue by gomorizsolt** [evanw/esbuild#2925]
Please see https://github.com/vitejs/vite/issues/12065 for further details.

# TL;DR

[**Playground**](https://esbuild.egoist.dev/#W1siaW5kZXgudHMiLHsiY29udGVudCI6ImltcG9ydCAnLi90ZXN0LmNzcycifV0sWyJlc2J1aWxkLmNvbmZpZy5qc29uIix7ImNvbnRlbnQiOiJ7XG4gIFwiZm9ybWF0XCI6IFwiZXNtXCIsXG4gIFwiY2RuVXJsXCI6IFwiaHR0cHM6Ly9jZG4uc2t5cGFjay5kZXZcIlxufSJ9XSxbInRlc3QuY3NzIix7ImNvbnRlbnQiOiIuZm9vIHtcbiAgZGlzcGxheTogbm9uZVxcOTtcbn0ifV1d)

CSS:

```css
display: ~'none \9';
```

Bundle:

```css
 display: none\;
```

Is anyone aware of a workaround to preserve `\9` as-is in the final bundle?

**Comment by gomorizsolt** [comment]
@evanw you are right. interestingly enough, the strange output is reproducible only if it is piped through vite. i suspect it has to do with their default esbuild config?! will contact them, thanks for your help!

**Comment by gomorizsolt** [comment]
@evanw on second thoughts, ...

```css
a {
  display: ~'none \9';
}
```

the tilde (`~`) in LESS outputs the string literal as-is and so eventually what gets processed by esbuild is...

```css
a {
  display: none \9;
}
```

which outputs

```css
a {
  display: none \	;
}
```

consequently, maybe it rather falls under esbuild's radar?

**Comment by evanw** [comment]
Again, I believe esbuild is functioning according to the specification. The CSS parsing algorithm is here: https://www.w3.org/TR/css-syntax-3/#tokenizer-algorithms. The byte sequence `\9` is parsed as an `<ident-token>` consisting only of the tab character:

> **U+005C REVERSE SOLIDUS (\\)**
> If the input stream [starts with a valid escape](https://www.w3.org/TR/css-syntax-3/#check-if-two-code-points-are-a-valid-escape), [reconsume the current input code point](https://www.w3.org/TR/css-syntax-3/#reconsume-the-current-input-code-point), [consume an ident-like token](https://www.w3.org/TR/css-syntax-3/#consume-an-ident-like-token), and return it.

Then, when printing this token, esbuild escapes the tab character so that the output still forms a valid identifier token. So both the input and the output are valid CSS syntax, and are equivalent (and equally meaningless).

I don't think esbuild needs to do anything different here. There is no syntax error in the code either before or after esbuild processes it, and Internet Explorer is pretty irrelevant nowadays so I don't think esbuild should be explicitly adding special extra code for it.
