### ISSUE TITLE
Use more compact binary runtime for buffers under 112kb

### ISSUE THREAD

**Issue by jed** [evanw/esbuild#2931]
Currently esbuild ships the following runtime decoder for binary embeds:

```js
var __toBinary = /* @__PURE__ */ (() => {
  var table = new Uint8Array(128);
  for (var i2 = 0; i2 < 64; i2++)
    table[i2 < 26 ? i2 + 65 : i2 < 52 ? i2 + 71 : i2 < 62 ? i2 - 4 : i2 * 4 - 205] = i2;
  return (base64) => {
    var n = base64.length, bytes = new Uint8Array((n - (base64[n - 1] == "=") - (base64[n - 2] == "=")) * 3 / 4 | 0);
    for (var i3 = 0, j = 0; i3 < n; ) {
      var c0 = table[base64.charCodeAt(i3++)], c1 = table[base64.charCodeAt(i3++)];
      var c2 = table[base64.charCodeAt(i3++)], c3 = table[base64.charCodeAt(i3++)];
      bytes[j++] = c0 << 2 | c1 >> 4;
      bytes[j++] = c1 << 4 | c2 >> 2;
      bytes[j++] = c2 << 6 | c3;
    }
    return bytes;
  };
})();
```

For payloads of 111.977kb or fewer (possibly depending on platform, larger payloads exceed the maximum call stack), the following would also work:

```js
var __toBinary = base64 => Uint8Array.from(atob(base64), x => x.charCodeAt())
```

Would esbuild consider shipping the latter by default for smaller embeds? It's small enough to be embedded in the call site and makes for cleaner code (though perhaps a performance tradeoff, but given decoding happens once per file, seems acceptable).

**Comment by evanw** [comment]
Your suggested code runs over 20x slower in V8. That seems like a pretty significant performance overhead for esbuild to introduce, which would be a startup penalty imposed on all code that uses the `binary` loader. In addition, the fact that it could potentially fail in limited environments either due to limited call stack (as you described) or due to running out of memory (what I experienced during testing) makes this seem like not a good idea to me. I'm assuming the 112kb limit you mentioned is something specific to your setup (e.g. which JS VM you're using, which version of that VM, how much memory your machine has, whether it's 32bit or 64bit, etc.). Encoding specific limits of a single implementation into esbuild to avoid crashing also doesn't seem like a good idea. For example, people run the code that esbuild generates in all kinds of environments including on embedded systems.

**Comment by jed** [comment]
I totally agree and understand these points. I'm not personally dealing with files large enough to hit performance issues, and still think there's a certain size threshold at which this makes sense; it just may be much lower than the theoretical limits of memory and call stack. for example, if I'm just embedding one 32-byte buffer to be used for `importKey`, 600 bytes of additional runtime start to make less sense.  But I suppose those use cases are infrequent enough that it's not worth branching the code to optimize.

**Comment by evanw** [comment]
If you want to optimize for very small binary files, you can already do that yourself with esbuild's [`base64` loader](https://esbuild.github.io/content-types/#base64) and the code that you suggested.
