### ISSUE TITLE
sourcemap doesn't have entrypoint source when use bundle option

### ISSUE THREAD

**Issue by zeakd** [evanw/esbuild#2938]
Hi. there is no source of entrypoint inside sourcemap when use bundle option. Is it intended?

``` ts
// hello.ts
export function hello() { console.log('hello') };

// hi.ts
export function hi() { console.log('hi') }

// index.ts
export * from './hello';
export * from './hi';
```

run `esbuild index.ts --outfile=out.js --sourcemap --bundle` 

``` json
// out.js.map (with bundle)
{
  "version": 3,
  "sources": ["hello.ts", "hi.ts"],
  "sourcesContent": ["export function hello() {\n  console.log('hello');\n}\n", "export function hi() {\n  console.log('hi');\n}\n"],
  ...
}

```

I think there should be "index.ts" in "sources" but there are only its dependencies. 

Without `--bundle`, there is "index.ts"

``` json
// out.js.map (without bundle)
{
  "version": 3,
  "sources": ["index.ts"],
  "sourcesContent": ["export * from './hello';\nexport * from './hi';\n"],
  ....
}
```

Thanks!

**Comment by evanw** [comment]
This is intentional. Tree shaking means files that don't contribute anything to the bundle are omitted from the source map. If you want the entry point to be present in the source map, then you'll have to put some code in it that contributes to the bundle.

**Comment by zeakd** [comment]
Sorry. I didn't fully understand. Why treeshaking is related this issue?

I have another example in case format=esm
``` js
// hello.ts
export function hello() { console.log('hello') };

// hi.ts
export function hi() { console.log('hi') }

// index.ts
export { hello as greeting } from './hello';
export { hi } from './hi';
```

and run `esbuild index.ts --sourcemap --outfile=out.js --bundle --format=esm` create **out.js.map** below
``` json
{
  "version": 3,
  "sources": ["hi.ts", "hello.ts"],
  "sourcesContent": ["export function hi() {\n  console.log('hi');\n}\n", "export function hello() {\n  console.log('hello');\n}\n"],
  "mappings": ";AAAO,SAAS,KAAK;AACnB,UAAQ,IAAI,IAAI;AAClB;;;ACFO,SAAS,QAAQ;AACtB,UAAQ,IAAI,OAAO;AACrB;",
  "names": []
}
```

In this case, this sourcemap has lost information about `greeting`. Shouldn't the sourcemap have information about it?

**Comment by evanw** [comment]
The code `export { hello as greeting } from './hello'` says "the export called `greeting` comes from the file `./hello`". So that doesn't prevent `index.ts` from being tree-shaken because `index.ts` still doesn't contribute any code to the bundle. If for example `index.ts` looked like this instead:

```ts
// index.ts
export * from './hello';
export * from './hi';
console.log('hello from index.ts');
```

then `index.ts` will be present in the source map because it contributes the code `console.log('hello from index.ts')` to the bundle.

**Comment by zeakd** [comment]
I see. Just re-exporting (or renaming) doesn't contribute to the bundle, so there's no need to source-mapping. Then why sourcemap include "index.ts" without bundle option?

**Comment by evanw** [comment]
> Then why sourcemap include "index.ts" without bundle option? I'm not sure about this difference.

If bundling is disabled then the `export * from './hello';` code from `index.ts` ends up in the output, so then `index.ts` is included in the source map.

This can also happen when bundling. For example, if you use `--bundle "--external:*"`, then the `export * from './hello';` code will appear in the resulting bundle, so `index.ts` will appear in the source map.

So it's not caused by whether bundling is enabled or not. It's caused by whether something from `index.ts` appears in the output or not.

**Comment by zeakd** [comment]
Thank you so much for your answer. It helped me understand. 
Taking this opportunity, I've been your fan since I saw "WebGL Water" 8 years ago. Thank you for all the great works!
