### ISSUE TITLE
context.watch resolves before the output directory is available on disk

### ISSUE THREAD

**Issue by ArnaudBarre** [evanw/esbuild#2941]
Repro:
```js
import { rmSync, writeFileSync } from "fs";
import { context } from "esbuild";

rmSync("dist", { force: true, recursive: true });
const c = await context({
  outdir: "dist",
  stdin: { contents: "console.log('Hello world');" },
});
await c.watch();
writeFileSync("dist/test.txt", "Hello world");
```

Error: `ENOENT: no such file or directory, open 'dist/test.txt'`

Mac Intel, node 19.3, esbuild 0.17.10

**Comment by evanw** [comment]
This is because `watch()` just enables watching and then returns immediately. If you want to wait for a build, you should call `rebuild()` after `watch()`. This also gives you the opportunity to handle build failure if you so choose (since `rebuild()` will throw an error in that case).

**Comment by ArnaudBarre** [comment]
Ok thanks for the answer. Is there any information contains in this watch promise? If it returns immediately I think this should not return a promise

**Comment by evanw** [comment]
My rationale: Enabling watch mode can fail if the context has already been disposed or if it has already been enabled. These failure checks exist on the Go side and communicating with the Go side is asynchronous. Also watch mode takes an optional set of arguments. These arguments are currently empty but some may be added in the future. If so, validation of those arguments may also be done synchronously in which case failure would be asynchronous. Having the API be asynchronous from the start means that additional arguments can be added in the future in a natural way that will work with existing code instead of potentially requiring another breaking API change where people have to rewrite their build scripts again. You are welcome to ignore the returned promise if you don’t like it.

**Comment by ArnaudBarre** [comment]
Thanks for explaining your rationale. I will just add `.rebuild` to my scripts, this is fine for me.

I just try to illustrate what make me uncomfortable with this initial build that you need to await via another call that starts with "re":
```ts
import { rmSync } from "fs";
import { context } from "esbuild";

rmSync("dist", { force: true, recursive: true });
const c = await context({
  outdir: "dist",
  stdin: { contents: "console.log('Hello world');" },
  plugins: [
    {
      name: "test",
      setup(build) {
        build.onStart(() => console.log("Starting..."))
      },
    },
  ],
});
await c.watch()
console.log("watching...");
// Commenting out this line doesn't give the same number of logs
// await new Promise((resolve) => setTimeout(resolve, 1000));
await c.rebuild();
console.log("rebuilt");
await c.rebuild();
console.log("rebuilt2");
```

**Comment by glromeo** [comment]
@evanw thank you for the clarification but I had to search the issues to find this out!

The examples in the [documentation](https://esbuild.github.io/api/#watch) doesn't mention
that `ctx.watch()` wouldn't wait for the initial build to finish and I was induced to think so 
given it's used with `await`.

I also share the  perplexity of @ArnaudBarre in seeing that a timeout would lead anyway to an initial
build to happen after some time so why not waiting on that before resolving watch's promise?

**Comment by eakl** [comment]
> @evanw thank you for the clarification but I had to search the issues to find this out!
> 
> The examples in the [documentation](https://esbuild.github.io/api/#watch) doesn't mention that `ctx.watch()` wouldn't wait for the initial build to finish and I was induced to think so given it's used with `await`.

Same for me. Calling rebuild() after watch solve my issue
