### ISSUE TITLE
Bundle react/jsx-runtime even if react is listed as external

### ISSUE THREAD

**Issue by tim-hilt** [evanw/esbuild#2947]
I have the following build-function in my project (irrelevant stuff removed):

``` js
  build({
    entryPoints: inputFiles,
    outfile: "dist/index_ext.js",
    define: {
      global: "window",
    },
    external: ["react", "react-dom"],
    plugins: [globalExternals(globals)],
  }).catch(() => process.exit(1));
};
```

react and react-dom are provided via another javascript file, which adds the relevant code to `window`. However, there are two libraries (namely [react-tiny-popover](https://www.npmjs.com/package/react-tiny-popover) and [react-dnd](https://www.npmjs.com/package/react-dnd), that do something like this in their code:

``` js
import { jsx } from "react/jsx-runtime.js";
```

which is then added to my bundle as such. When I try to run the website I see the following two error-messages when I try to access different areas of my application:

```
Module not found: Error: Can't resolve 'react/jsx-runtime'

Uncaught Error: Dynamic require of "react/jsx-runtime" is not supported
```

Rollup somehow doesn't have this problem, so I assume Rollup bundles `"react/jsx-runtime"`, even though `react` is specified as external.

Is there some known workaround to bundle `react/jsx-runtime`, even if `react` is listed as an external module?

**Comment by evanw** [comment]
> Is there some known workaround to bundle `react/jsx-runtime`, even if `react` is listed as an external module?

No. If you mark something as `external` then it's not included in the bundle (that's the purpose of the `external` feature). If you want something to be included in the bundle, then it shouldn't be marked as `external`. If you want to do something custom (e.g. only certain subpaths in a module are not external) then you'll have to write a plugin instead of using the built-in `external` feature. The documentation for the plugin API is here: https://esbuild.github.io/plugins/.

**Comment by tim-hilt** [comment]
Thanks for the fast response. I'll close this, since it doesn't seem to be in scope for esbuild-core
