### ISSUE TITLE
class rename with suffix when using static inside scope

### ISSUE THREAD

**Issue by djmisterjon** [evanw/esbuild#2956]
how i can avoid this issue ? 
```ts
class A {
    static a = '';
    onupdate() {
        const { a } = A;
    }
}
console.log( 'A:', [A]);
```
this will rename the class "A" to "_A"
if i remove static
```ts
class A {
    //static a = '';
    onupdate() {
        const { name } = A;
    }
}
console.log( 'A:', [A]);
```
Now it fine, class "A" is keep named "A"

i tried this setting , but seem not related, not work at all !
```
    optimizeDeps: {
        esbuildOptions: {
            keepNames: true,
        },
    },
```
thanks for your time.
![image](https://user-images.githubusercontent.com/24865815/222005898-fc6e0a6d-efde-4c53-b23e-8bcbc920db28.png)

if someone confirm for me that it are normal behavior or not? it may just be a bad typescript config on my side?
or i missing something ?

it important for me because i have a ui thats depend of class name
![image](https://user-images.githubusercontent.com/24865815/222006046-a1bbf8c3-c874-46b4-a8b6-7c8200526c6d.png)

**Comment by evanw** [comment]
It's not possible to preserve the specific textual identifier in the source code with esbuild. One reason this is impossible is because esbuild does "scope hoisting" which merges multiple files into the same scope, so esbuild sometimes needs to rename identifiers to avoid collisions.

The "keep names" setting preserves the runtime value of the `.name` property on the object. So if you care about preserving the runtime value of the `.name` property, you should enable the `--keep-names` setting. But if you care about preserving the specific textual identifier in the source code, then you should use another tool instead of esbuild (and perhaps not bundle your code at all).

> i tried this setting , but seem not related, not work at all !
> 
> ```
>     optimizeDeps: {
>         esbuildOptions: {
>             keepNames: true,
>         },
>     },
> ```

I can't reproduce this. Here's what I tried:

```
$ cat example.js
class A {
  static a = '';
  onupdate() {
    const { a } = A;
  }
}
console.log('A:', [A]);

$ esbuild --bundle example.js | node
A: [ [class _A] { a: '' } ]

$ esbuild --bundle example.js --keep-names | node
A: [ [class A] { a: '' } ]
```

Notice how the name is preserved with `--keep-names`. Specifically `class _A` becomes `class A`. So esbuild's `--keep-names` feature appears to work fine given the input you have provided.

**Comment by djmisterjon** [comment]
> It's not possible to preserve the specific textual identifier in the source code with esbuild. One reason this is impossible is because esbuild does "scope hoisting" which merges multiple files into the same scope, so esbuild sometimes needs to rename identifiers to avoid collisions.
> 
> The "keep names" setting preserves the runtime value of the `.name` property on the object. So if you care about preserving the runtime value of the `.name` property, you should enable the `--keep-names` setting. But if you care about preserving the specific textual identifier in the source code, then you should use another tool instead of esbuild (and perhaps not bundle your code at all).
> 
> > i tried this setting , but seem not related, not work at all !
> > ```
> >     optimizeDeps: {
> >         esbuildOptions: {
> >             keepNames: true,
> >         },
> >     },
> > ```
> 
> I can't reproduce this. Here's what I tried:
> 
> ```
> $ cat example.js
> class A {
>   static a = '';
>   onupdate() {
>     const { a } = A;
>   }
> }
> console.log('A:', [A]);
> 
> $ esbuild --bundle example.js | node
> A: [ [class _A] { a: '' } ]
> 
> $ esbuild --bundle example.js --keep-names | node
> A: [ [class A] { a: '' } ]
> ```
> 
> Notice how the name is preserved with `--keep-names`. Specifically `class _A` becomes `class A`. So esbuild's `--keep-names` feature appears to work fine given the input you have provided.

thank for clear explantation  :)
