### ISSUE TITLE
Treeshaking appears to only work at the top-level

### ISSUE THREAD

**Issue by thebanjomatic** [evanw/esbuild#2967]
When variables are un-used at the top-level of a module, tree-shaking kicks in unused code is properly dropped from the output. For example, the code below correctly results in empty output (with `--tree-shaking`) because foo is not referenced. If you uncomment the `console.log(foo)` at the bottom, or add `export {foo}` etc, then all of the associated code persists.
```js
function getFoo() {
  window.alert('getting foo...');
  return 5;
}
const foo = /*#__PURE__*/ getFoo();
// console.log(foo)
```

All of the above works great, but if you take the exact same code and wrap it in a function, no code is eliminated from the body of the function.

```js
(function () {
  function getFoo() {
    window.alert('getting foo...');
    return 5;
  }
  const foo = /*#__PURE__*/ getFoo();
})();
```

Would it be difficult to apply the same analysis to function bodies that applies at the top-level and drop any side-effect-free expressions that are not visible to a return value?

**Comment by evanw** [comment]
> Would it be difficult to apply the same analysis to function bodies that applies at the top-level and drop any side-effect-free expressions that are not visible to a return value?

Yes. The data structure that esbuild uses for tree-shaking makes a graph of top-level statements and is not recursive. It's designed to run quickly and give good results when bundling from source (since esbuild is primarily a bundler), but that means it's not designed to be optimal for all use cases. There is more discussion in this issue (which is the same request as yours): https://github.com/evanw/esbuild/issues/639.

**Comment by thebanjomatic** [comment]
Closing in favor of #639
