### ISSUE TITLE
No loader configured for '.node' files?

### ISSUE THREAD

**Issue by dawesydev** [evanw/esbuild#2972]
I'm using Vue 3 with Vite and I'm running into the following error:

No loader is configured for ".node" files: node_modules/fsevents/fsevents.node

Am I able to configure this manually in the vite.config.js for .node file types?

Or is this a deeper issue with how Vite has setup esbuild behind the scenes?

Any help would be much appreciated, thanks.

**Comment by evanw** [comment]
> Am I able to configure this manually in the vite.config.js for .node file types?
>
> Or is this a deeper issue with how Vite has setup esbuild behind the scenes?

This is a question for Vite. I know nothing about Vite. Their issue tracker is here: https://github.com/vitejs/vite/issues.

That said, I suspect you don't want to add a loader for `.node`. If you're using Vite to build for the web, it doesn't make sense to attempt to run `.node` files in the browser because they are extensions for node written in native code. You likely instead want to avoid bundling that whole package since that package is not web-compatible.

I'm closing this issue because this is not the Vite repo, and is not an appropriate place for Vite support requests.

**Comment by dawesydev** [comment]
Apologies, the error triggered originates from node_modules/esbuild/lib/main.js  so I assumed is was an esbuild issue. Perhaps the [loader](https://esbuild.github.io/api/#loader) is not configured for ".node" files? It's an error that has popped up completely out of the blue, I don't touch node_modules during development so I can't understand/fix the issue.

**Comment by dawesydev** [comment]
Thanks for your help 🙏🏻
