### ISSUE TITLE
Still in beta?

### ISSUE THREAD

**Issue by danielehrhardt** [evanw/esbuild#2988]
I really want to use esbuild. 
But as written in the docs it is still in beta. 
https://esbuild.github.io/faq/#production-readiness

Is this still the case?

**Comment by evanw** [comment]
I think this part of the documentation is still accurate:

> For some early-adopters that means it's good enough to use for real things. Some other people think this means esbuild isn't ready yet. This section doesn't try to convince you either way. It just tries to give you enough information so you can decide for yourself whether you want to use esbuild as your bundler.

Many people are currently using esbuild for production workflows. For example, the TypeScript 5.0 compiler that will be released soon is bundled with esbuild. However, some of esbuild's features such as [code splitting](https://esbuild.github.io/api/#splitting) are not where they need to be for production use cases. That doesn't matter for some people since they aren't using esbuild for code splitting. But if you need that, then you may want to use another tool instead.
