### ISSUE TITLE
Minify multiple js files into one

### ISSUE THREAD

**Issue by quinncomendant** [evanw/esbuild#300]
I have a legacy project using uglifyjs that I'd like to replace with esbuild. It will need to take a list of input files, and minify them into one output file. Currently, I'm doing this:

    uglifyjs js/jquery.js js/modernizr.js js/app.js --output html/build/app.min.js --mangle --compress

Is there a way to do this with esbuild? I'm confused what the esbuild docs refer to as "entry points", i.e., *one bundle file per entry point*, I guess "entry point" doesn't refer to "input file" so I have hope this is possible.

Thanks for your work on this project!

**Comment by evanw** [comment]
The bundling process takes a single input file and produces a single output file containing that input file and all of its dependencies. The single input file to the bundling process is called the entry point.

To improve performance, esbuild lets you specify multiple entry points to tell it to perform the bundling operation multiple times, once for each entry point. This improves performance because any dependency that is shared between multiple entry points is only parsed once. Other than the performance improvement, this is equivalent to invoking esbuild separately for every entry point.

If you want to bundle all of these files into a single bundle with esbuild, you can reference them all from a single file:

```js
// entry.js
import "./js/jquery.js"
import "./js/modernizr.js"
import "./js/app.js"
```

and pass that file as the entry point to esbuild:

```
esbuild entry.js --bundle --outfile=html/build/app.min.js --minify
```

**Comment by quinncomendant** [comment]
Oh, that's so easy. 😎

Thanks for the prompt reply!

**Comment by evanw** [comment]
Cool! Glad it worked. I'm going to close this since it sounds like the problem was resolved.
