### ISSUE TITLE
Config options `target` and `supported` are not working

### ISSUE THREAD

**Issue by georgolden** [evanw/esbuild#3002]
**Bug**:

Config: https://github.com/oldbros/shiftjs/blob/main/scripts/build.mjs

After compilation: https://github.com/oldbros/shiftjs/blob/main/dist/shift.cjs

It is clear, that both `target` and `supported` options are ignored completely during build. Code is es2015 no matter what

**Comment by evanw** [comment]
I haven't investigated this yet but I'm guessing this is done for internal esbuild-specific reasons and is not related to `target` and `supported` at all (for more information see #2416 and #2889). The `target` and `supported` settings tell esbuild that it can assume a feature is supported, but that's different from forcing esbuild to not transform syntax. There is no API for forcing esbuild to not transform syntax. I would ideally like to improve the output here but that's tricky due to the current design of esbuild's class transformation code. I'm labeling this `suboptimal-output` because this is intentional behavior and is not a bug.
