### ISSUE TITLE
Using node:process breaks variable substitution

### ISSUE THREAD

**Issue by ben-eb** [evanw/esbuild#3015]
Hello, many thanks for this project 🙂 

I ran into an issue recently where refactoring some code to use the module form of `process` broke the substitution in esbuild. 

Given the following `build.js`:

```javascript
import * as esbuild from 'esbuild'

await buildFile('a.js')
await buildFile('b.js')

async function buildFile (entryPoint) {
    return esbuild.build({
        entryPoints: [entryPoint],
        bundle: true,
        outfile: `dist/${entryPoint}`,
        define: {
            'process.env.FOO': 'true'
        },
        platform: 'node',
        format: 'esm'
    })
}
```

`a.js`:

```javascript
console.log(`foo: ${process.env.FOO}`)
```

and `b.js`:

```javascript
import process from 'node:process'

console.log(`foo: ${process.env.FOO}`)
```

I get the following `dist/a.js`:

```javascript
// a.js
console.log(`foo: ${true}`);
```

and `dist/b.js`:

```javascript
// b.js
import process from "node:process";
console.log(`foo: ${process.env.FOO}`);
```

As you can see, adding the import statement turns off the substitution which changes the behaviour of the compiled application.

I fixed the issue in my application by reading the `process.env` directly rather than inlining it into the bundle (as it is available in my target environment), but I thought that you should be aware of this. Thanks!

**Comment by evanw** [comment]
This is by design. The `define` feature deliberately only affects references to global variables. References to local variables are not replaced. This is mentioned in the first line of [the documentation for `define`](https://esbuild.github.io/api/#define):

> This feature provides a way to replace _**global identifiers**_ with constant expressions.

As you have already discovered, you can remove the import statement to get this to work:

```diff
-import process from "node:process";
 console.log(`foo: ${process.env.FOO}`);
```

**Comment by fantua** [comment]
hey @evanw, any chance you can revisit this one?

I'm experiencing the same issue with external lib https://github.com/vadimdemedes/ink/issues/571. Basically I would like to set `define: { 'process.env.DEV': 'false' }` to remove ink devtools from production bundle. But it doesn't work because process is imported from `node:process`.

Lib maintainers expect this to be addressed on bundler (esbuild) side https://github.com/vadimdemedes/ink/issues/571#issuecomment-1485756890. 

Node.js recommends to import process now: https://nodejs.org/dist/latest-v16.x/docs/api/process.html#process_process

Also this works fine with webpack.
