### ISSUE TITLE
cant support tsconfig.compilerOptions.paths ?

### ISSUE THREAD

**Issue by takegine** [evanw/esbuild#3017]
![image](https://user-images.githubusercontent.com/64788603/227206923-f0e7324e-79f5-4eff-ae0f-e0193a33597c.png)

**Comment by hyrious** [comment]
esbuild does support `paths`, it seems rollup-plugin-esbuild is using the [transform](https://github.com/egoist/rollup-plugin-esbuild/blob/dev/src/index.ts#L158) mode of esbuild which does not resolve tsconfig paths since it only transform the syntax instead of doing the resolving like in build mode.

You can use other plugins to resolve tsconfig paths, try them:

- https://github.com/simonhaenisch/rollup-plugin-typescript-paths
- https://github.com/lightyen/typescript-paths

Or you can hack esbuild to abuse its build mode as a resolver [like this](https://github.com/hyrious/esbuild-dev/blob/main/src/build.ts#L183).
