### ISSUE TITLE
build cjs module but require an esm module

### ISSUE THREAD

**Issue by MageMaize** [evanw/esbuild#3024]
when i use puppeteer module in my project.
```typescript
import puppeteer from "puppeteer";
```
use esbuild to build project:
```typescript
await build({
    bundle: true,
    target: "node18",
    platform: "node",
    format: "cjs",
    sourcemap: "external",
    external:["/node_modules/*"],
    entryPoints: ["./src/index.ts"],
    outfile: "./dist/index.js",
    plugins: []
});
```
run build and open dist/index.js file. can find this code:
```javascript
var import_puppeteer = __toESM(require("../node_modules/puppeteer/lib/esm/puppeteer/puppeteer.js"));
```
This line of code is wrong, the correct one should be like the following
```javascript
var import_puppeteer = __toESM(require("../node_modules/puppeteer/lib/cjs/puppeteer/puppeteer.js"));
```
esbuild incorrectly referenced the esm module in the cjs module.
Can someone help me solve this problem? Thank you so much.
nodejs version: 18.14.0
esbuild version: 0.17.14
puppeteer version: 19.2.2
os: Windows 11 Professional 22H2 22621.1344

**Comment by evanw** [comment]
A straightforward way to solve this is to make the `puppeteer` package external. I suspect your `external` setting isn't doing anything since your `node_modules` folder isn't mounted at the file system root (and on Windows the file system root is `C:\` not `/` anyway).

You can use the `packages` setting to mark all packages as external: https://esbuild.github.io/api/#packages. Or if you want to be more selective, you can use the `external` setting with absolute paths, relative paths, or individual package names: https://esbuild.github.io/api/#external.

**Comment by MageMaize** [comment]
Okay, the external configuration wasn't changed before and there was no problem, but it only appeared recently. The problem was solved by setting the puppeteer package as an external package. Thank you very much!
