### ISSUE TITLE
Build error occurs

### ISSUE THREAD

**Issue by qertis** [evanw/esbuild#3044]
The build crashes with an unclear error message.

**How to reproduce?**

1. Open the project https://github.com/qertis/solid-client
2. Switch to the solid-client branch
3. Execute the following commands:
```
npm install
npm run pwa
```
4. Observe the error:
![](https://user-images.githubusercontent.com/3893228/230395368-b0f49a1a-d2f4-418a-9dec-6c46d318725e.png)

**Additional context**
It seems more likely to be a problem with the behavior of esbuild. When I change the esbuild target to es2022, I still see this error. [^1]

This has nothing to do with Quasar CLI itself. [^2]

[^1]: [solid-client-js/issues/1924](https://github.com/inrupt/solid-client-js/issues/1924#issuecomment-1500078241)
[^2]: [quasar/issues/15686](https://github.com/quasarframework/quasar/issues/15686#issuecomment-1499990898)

**Comment by hyrious** [comment]
I didn't see the issue about BigInt, but I did see the first issue you discovered in inrupt/solid-client-js#1924:

```
TypeError: Class extends value undefined is not a constructor or null
    at duplexify.js:41:25
```

(Hint: enable `build.sourcemap: 'inline'` in quasar.config.js for better debugging)

The problem here is circular dependencies in `readable-stream` not being transformed well in `@rollup/plugin-commonjs@21` which is bundled in `vite@2` which is a dependency of `@quasar/app-vite`. This was fixed in `@rollup/plugin-commonjs@22` (the latest is 24 though).

`readable-stream` is a dependency of `n3`, which is a dependency of `@inrupt/solid-client` which is the direct dependency of your project.

So this is actually not an issue in esbuild. If you want a reproduction using rollup here it is:

```js
// package.json
{
  "devDependencies": {
    "@rollup/plugin-commonjs": "^21",
    "@rollup/plugin-node-resolve": "*",
    "readable-stream": "^4.3.0",
    "rollup": "^2"
  }
}

// main.js
const { Readable } = require("readable-stream");
console.log(Readable);
```

```bash
$ npx rollup main.js -f cjs -p commonjs,node-resolve -o out.js
$ node out.js
class Duplexify extends Duplex$4 {
                        ^

TypeError: Class extends value undefined is not a constructor or null
```

**Comment by hyrious** [comment]
I did see the BigInt error in `target-esnext` branch, but I don't think this is an error -- it is somewhere else setting the [target](https://esbuild.github.io/api/#target) option of esbuild to `["chrome87", "edge88", "es2019", "firefox78", "safari13.1"]`, I guess it is [vite@2](https://github.com/vitejs/vite/blob/v2.9.15/packages/vite/src/node/build.ts#L277) too. esbuild doesn't know how to lowering bigints (in the 'buffer' package, which is a dependency of 'n3'), so that's it.

**Comment by qertis** [comment]
Thanks. I'll try to reopen https://github.com/quasarframework/quasar/issues/15686
