### ISSUE TITLE
esbuild does not support method decorators in class expressions

### ISSUE THREAD

**Issue by Diggsey** [evanw/esbuild#3045]
The following has been supported in Typescript for a long time:

```ts
function example(...args: unknown[]) {}

const Foo = class Foo {
  @example
  changed() {}
}
```

But is rejected by esbuild with the error `Decorators can only be used with class declarations in TypeScript`

This would be useful to support as class expressions are commonly used to implement mixins in Typescript, and it's not clear why class expressions should differ from class declarations in this way.

**Comment by evanw** [comment]
[TypeScript's experimental decorators do not support this.](https://www.typescriptlang.org/play?experimentalDecorators=true#code/GYVwdgxgLglg9mABAUwB4EMC2AHANsgCgDoT0AnAcwGcAuRcAazDgHcwBtAXQEpEBvAL4AoIRARUoiAGJw4iALyIIudFSrTZ-IYkQABNFjzJtSgBbowFZABMCvQUOFA) This is the error you get when you compile the code you provided with TypeScript's experimental decorators enabled:

```
example.ts:4:3 - error TS1206: Decorators are not valid here.

4   @example
    ~
```

I'm closing this issue as invalid, as esbuild appears to be working correctly here.

Side note: JavaScript is planning to add a feature that's also called "decorators" but that works differently from TypeScript's experimental decorators. Notably JavaScript decorators would allow the code you want to write to work. Currently esbuild only supports TypeScript's experimental decorators because JavaScript's decorator feature is still a work in progress. Supporting JavaScript decorators is tracked by #104.

**Comment by Diggsey** [comment]
@evanw I guess I'm a bit confused because when the "experimental decorators" TS config is *disabled* the TypeScript compiler does successfully translate the TypeScript into Javascript code that does not use decorators at all.

Why is this feature calls "JavaScript decorators" if it's the Typescript compiler which is doing the transformation? And given that esbuild is serving as a replacement for the Typescript compiler (sans type checking) I would expect any mismatch between what the Typescript compiler does and what esbuild does to be considered a bug (at least when I haven't explicitly opted into any experimental features...)

**Comment by evanw** [comment]
I'm calling it "JavaScript decorators" because it comes from a proposal to add decorators to JavaScript: https://github.com/tc39/proposal-decorators. It's still being actively worked on, as you can see here: https://github.com/tc39/proposal-decorators/issues/499. The esbuild issue about implementing this is #104 if you want to subscribe for updates about esbuild's implementation of this feature.

As far as I understand, some people at Microsoft are working on the JavaScript decorators proposal with the JavaScript language committee and shipped a WIP implementation in TypeScript compiler to get feedback on the specification. They are using that feedback to evolve the specification before it's finalized and becomes a part of JavaScript. I'm waiting until the specification is more final so that I can implement it without having to continually change esbuild's implementation to follow along with the specification changes.

**Comment by Diggsey** [comment]
Thanks for the context. It's not great that the Typescript maintainers added this experimental feature without requiring an opt-in then... ☹️

**Comment by mmmmmmmgo** [comment]
This error message is quite rare, and currently, only this issue can be found through searches. Although unrelated to this specific problem, I'll also provide my scenario to help future developers save time in troubleshooting.

In my case, I was using `vite` and `@vitejs/plugin-react` to compile the project. However, the project used decorators, and to avoid errors with the `babel` inside `@vitejs/plugin-react`, I additionally added the `@babel/plugin-proposal-decorators` and `@babel/plugin-proposal-class-properties` plugins to `@vitejs/plugin-react`:

```javascript
viteReact({
  jsxRuntime: 'classic',
  babel: {
    plugins: [/* '@babel/plugin-proposal-class-properties', '@babel/plugin-proposal-decorators' */],
  },
})
```
This caused Babel to transform:
```
@myDecorator
class MyClass
```

into:

```
let MyClass = (_dec = injectable(), _dec(_class = class MyClass
Finally, when esbuild compiled the code, it reported the error: Decorators can only be used with class declarations in TypeScript.
```

my solution is change to `@babel/plugin-syntax-decorators` and `@babel/plugin-syntax-class-properties`
