### ISSUE TITLE
Esbuild throws errors on generic arrow functions in certain cases

### ISSUE THREAD

**Issue by charliematters** [evanw/esbuild#3049]
### Bug description

We have upgraded esbuild-loader to avoid the node 18 bug in webpack, and suddenly we are getting syntax errors which are not being reported by tsc.

It seems that it can no longer parse this line:
```typescript
const foo = async <T>(bar:T): Promise<T> => bar
```

The error thrown is `Expected ")" but found ":"`

I've added a repo which shows that when that file is consumed from stdin it fails, but passing the filename as an argument works as expected

### Minimal reproduction link

https://github.com/charliematters/esbuild-issue

**Comment by evanw** [comment]
Data from stdin is a raw string without any file extension attached, so esbuild has no information about what type of file it is. In that case, esbuild defaults to assuming the input is JavaScript. You need to specify a different [loader](https://esbuild.github.io/api/#loader) if that's not the case (e.g. `--loader=ts`).

I'm closing this issue because esbuild is working as expected.
