### ISSUE TITLE
ESBuild fails on linked workspaces

### ISSUE THREAD

**Issue by James-Mnemosyne** [evanw/esbuild#3060]
Consider a workspace setup with an app and a package. In this case, we'll call them app and package, and say that they're positioned in the apps/app and packages/package directories, and that app relies upon package. E.g.

app <- package

In a typical yarn workspaces setup, dependencies between workspaces are generally tracked by adding the a dependency line to the dependent package.json. E.g. app's package.json would contain the line

```
"dependencies": {
...
"@packages/package": "workspace:*", // This line, and running yarn, causes the issue.
...
}
```

And running yarn.

However, esbuild stops respecting path aliases and changes when this is done, leading to an error.

To clarify, running esbuild without the line above, or even without yarn installing the line above, succeeds. @packages/packages successfully transpiles/everything is bundled together nicely. But with the line above, and after running yarn, the something like

```
import package from '@packages/packages';
```

Keeps the term @packages/packages through the build phase and in the output.

This causes the expected errors when running, namely:

```
Error: Cannot find module '@packages/package'
```

Curious if this is a known issue, and if not, whether it's an easy fix?

**Comment by hyrious** [comment]
esbuild doesn't read the dependencies of package.json, it's resolver works almost the same as native Node.js', which means it will goto node_modules to search the folder '@packages/package'.

You may go check if yarn doesn't put the linked folder there, in which case esbuild cannot resolve correctly. Since yarn >= 2 seems to take over the node modules loading process completely.

On the other hand, you said <q>running esbuild without the line above, or even without yarn installing the line above, succeeds</q>. It sounds like you have some other esbuild-wrapper or plugin that marks dependencies as [externalized](https://esbuild.github.io/api/#external). This is often correct for building libraries, but not for websites.

**Comment by James-Mnemosyne** [comment]
Yeah. Sorry. False flag. It's actually the node external modules plugin that strips items out of the bundle automatically if they're named deps in the package json.

Put out a request [here](https://github.com/pradel/esbuild-node-externals/pull/41) for that lib. Closing here. Sorry about that.

**Comment by kevireilly** [comment]
For any future travelers potentially finding this as a regression: I was able to backtrack this to the workspace module that cannot be found receiving a major version revision to `@swc`
```diff
-        "@swc/cli": "0.1.62",
-        "@swc/core": "1.3.70",
+        "@swc/cli": "0.3.5",
+        "@swc/core": "1.3.107",
```
