### ISSUE TITLE
Rebuild for CI / persistent cache

### ISSUE THREAD

**Issue by marionebl** [evanw/esbuild#3063]
I'm interested in leveraging the newly introduced `rebuild` functionality for speed ups in continuous integration. 

The way I imagine this could work from a user's perspective:

1. CI environment provides a pre-populated `outdir` and `esbuild.cache` file
2. CI environment ensures timestamps of inputs and outputs reflect last edit
3. `esbuild` uses the populated outdir and `esbuild.cache` file to decide if an input needs to be processed
4. A new `esbuild.cache` file is written on successful build

--- 

I'm fuzzy on what would go into the said `esbuild.cache`, I suspect it would be at least 

* a `Map<sourcePath, mtime>`
* a `Map<outputFilePath, mtime>`
* a `Map<outFilePath, sourcePath[]>`

Let me know what you think.

**Comment by evanw** [comment]
You're free to create caching logic around esbuild if you'd like. Keep in mind that it's very easy to introduce subtle consistency bugs when doing this. One example: mtime granularity differs between file systems and may sometimes be on the order of seconds, which doesn't catch rapid changes. To get around this, esbuild's watch mode [avoids using mtime if it's too recent](https://github.com/evanw/esbuild/blob/f22c5132e3116288ce2782759f4cbb039ef6a136/internal/fs/fs.go#L231-L236). Another example: for correctness, you also need to invalidate the cache when any of the source code involved in generating cache entries changes (esbuild avoids this problem by not persisting its cache to the file system). There is some additional advice here in case it helps: https://esbuild.github.io/plugins/#caching-your-plugin. Good luck!

**Comment by marionebl** [comment]
Playing back what I understood:

* You would prefer persistent caching to be solved outside esbuild
* It is a very hard problem to solve well

Is that a fair summary?

I agree with both statements in principle. 

Reading through the API docs I can't see the caching primitives exposed to the build or plugin APIs. 
Unfortunately I can't see how a plugin or wrapper would be able to implement effective caching with that. 

Could you give me a hint as to how you'd expect a persistent and granular cache to be wrapped around esbuild?

**Comment by evanw** [comment]
Typically by far the slowest part of running esbuild is the plugins (otherwise esbuild almost always completes builds very fast). Plugins are also something that esbuild doesn't have enough information to cache correctly in a persistent fashion, so it's impossible for esbuild to cache their output on the file system given the current API.

For example, there would need to be some way for esbuild to traverse all code used by that plugin (including its transitive dependencies) to verify that the code hasn't changed, but all esbuild's API gets is a JavaScript function object. There is also the problem of any dependency being able to open any file at any time and include it in the build. One way for esbuild to automatically implement caching correctly would be for esbuild to be the JavaScript runtime that plugins run in (i.e. for esbuild to include a JavaScript interpreter) so it can intercept all file system operations (including the loading of code), as well as all other sources of non-determinism. But that would be a very different, invasive API change and would make esbuild much harder to integrate into existing workflows.

So instead, esbuild leaves caching decisions up to each plugin. The plugin is the thing that should be able to have enough information to know when its output does not need to be recomputed. In that case it can just return its previous output instead of recomputing it. In this model, you'd still have to run esbuild's build API every time, but the build should complete more quickly than a full build if all plugins just load their content from a cache.

If you want to skip the build altogether, then you'd need to add some additional logic (that you write) around the call to esbuild's build API so that you don't call it if it's not needed. The exact conditions for when a build doesn't need to be recomputed is case-specific, and so must be implemented by you. For example, there may be a plugin that injects the current day into the build as a string. There's no way for esbuild to automatically know that the build is invalidated when the current day changes. These are rules that you have to write yourself.

**Comment by marionebl** [comment]
Thank for the thorough explanation. I'll explore some of the options you outlined.

**Comment by espoal** [comment]
I'm working on a similar thing. I made it work in two different ways:

- Using [CRIU](https://criu.org/Main_Page). I freeze the container with esbuild running in watch mode. When CI runs again I unfreeze it, do a git pull, and then I freeze it again
- Using a merkle tree. I'm still working on this.

Let me know if you want to hear more about this.

**Comment by marionebl** [comment]
> I'm working on a similar thing. I made it work in two different ways:
> 
> * Using [CRIU](https://criu.org/Main_Page). I freeze the container with esbuild running in watch mode. When CI runs again I unfreeze it, do a git pull, and then I freeze it again
> * Using a merkle tree. I'm still working on this.
> 
> Let me know if you want to hear more about this.

I'm very interested!
