### ISSUE TITLE
Minify converting string to template string

### ISSUE THREAD

**Issue by privatenumber** [evanw/esbuild#307]
## Description
`minify` is converting strings that use `.concat()` to template strings. I'm not sure if this is a bug, but this was definitely unexpected for me because of how it spans multiple lines in the Chrome Dev Sources tab.

If it's expected behavior, I'm curious why?

## Reproduction
Minify input:
```js
'\n\t\t\t\thello'.concat(' world');
```

Output:
```js
`\n\t\t\t\thello`.concat(" world");
```

**Comment by evanw** [comment]
This is deliberate, and only happens when minifying. The escape sequence `\n` takes two bytes in the output file while a newline character only takes one byte. But a newline character can only appear inside a template literal, not a string literal. So the string literal is converted to a template literal which allows newlines to be printed using shorter newline characters instead of the longer `\n` sequence.

**Comment by privatenumber** [comment]
Ahh I see. Great explanation! Thank you @evanw
