### ISSUE TITLE
[feat] treat typescript namespace like `import * as foo from 'foo'` which refer to `ImportNamespaceSpecifier` in AST

### ISSUE THREAD

**Issue by loynoir** [evanw/esbuild#3077]
### Reproduce

```sh
$ npm exec -- esbuild --format=esm --bundle ./entry.mts
```

```ts
==> entry.mts <==
import TypeRegistry from './lib.mjs'

TypeRegistry.Clear()

==> lib.mts <==
const map = new Map<string, unknown>()

function Entries() {
  return new Map(map)
}

function Clear() {
  return map.clear()
}

export default /* @__PURE__ */{ Entries, Clear }
```

### Actual
```js
// lib.mts
var map = /* @__PURE__ */ new Map();
function Entries() {
  return new Map(map);
}
function Clear() {
  return map.clear();
}
var lib_default = { Entries, Clear };

// entry.mts
lib_default.Clear();
```

### Expected
```js
// lib.mts
var map = /* @__PURE__ */ new Map();
function Clear() {
  return map.clear();
}
var lib_default = { Clear };

// entry.mts
lib_default.Clear();
```

### Related
https://github.com/sinclairzx81/typebox/issues/401

**Comment by evanw** [comment]
You also filed #3076 about a similar thing. But regardless of how you generate a JavaScript object, it's still a huge increase in complexity to tree-shake JavaScript objects in the way you are asking for, so this is not something that esbuild does.

The problem is that JavaScript objects are not namespaces, and they do not work like real namespaces do in languages which have that feature. One source of complexity is that you can still access all other properties via `this`. So in JavaScript it's not safe to assume that `Entries` can be removed if it's not referenced explicitly. And even if `this` isn't present in the source code, you can still later mutate the JavaScript object by overwriting one of the properties on the object with a function that uses `this` to get to any other property on the object.

It looks like Rollup and Parcel don't do this transformation either, which is presumably due to the same complexity issues. I recommend that you use normal ESM exports the way they are intended to be used if you are interested in enabling tree shaking of your code:

```diff
 ==> entry.mts <==
-import TypeRegistry from './lib.mjs'
+import * as TypeRegistry from './lib.mjs'
 
 TypeRegistry.Clear()
 
 ==> lib.mts <==
 const map = new Map<string, unknown>()
 
-function Entries() {
+export function Entries() {
   return new Map(map)
 }
 
-function Clear() {
+export function Clear() {
   return map.clear()
 }
 
 export default /* @__PURE__ */{ Entries, Clear }
```

**Comment by loynoir** [comment]
@evanw 

Awesome!

```js
// lib.mts
var map = /* @__PURE__ */ new Map();
function Clear() {
  return map.clear();
}

// entry.mts
Clear();
```

**Comment by loynoir** [comment]
What about treat namespace like this behavior too?

https://astexplorer.net/

```
import * as x from 'foo'
```

Ast parse it as `ImportNamespaceSpecifier`

**Comment by loynoir** [comment]
Close in favor of https://github.com/evanw/esbuild/issues/3077

**Comment by evanw** [comment]
Sorry, I don't understand what you're saying. I don't know what you mean by "namespace" or "ImportNamespaceSpecifier".

**Comment by loynoir** [comment]
typescript have namespace

https://github.com/sinclairzx81/typebox/blob/376e482737bd915460f122c95c66482b77fa9416/src/typebox.ts#L781

And babel parse `import * as foo from 'foo'` as `ImportDeclaration` with specifiers `ImportNamespaceSpecifier` with identifier with name foo

**Comment by evanw** [comment]
TypeScript's namespaces are just syntax sugar for constructing a mutable JavaScript object, which has all of the same issues. It would be equally unsafe for esbuild to do this for TypeScript namespaces.

One important difference between normal JavaScript objects and the objects that you get when you import a namespace (called [module namespace exotic objects](https://tc39.es/ecma262/#sec-module-namespace-exotic-objects) in the JavaScript specification) is that module objects don't allow you to mutate their properties. That means esbuild doesn't have to account for the possibilty of them being mutated.

It's the opinion of the TypeScript team that if you are already using ESM syntax, then you should probably shouldn't be using TypeScript namespaces for code organization: https://github.com/microsoft/TypeScript/issues/30994#issuecomment-492017219. Instead you should be using ES modules. They are standardized across the JavaScript ecosystem, they have better support from existing tooling (e.g. you get tree shaking), they generate smaller code when minifying (since export names can be minified), and they even make your code run faster at run-time (since you avoid property access overhead). The TypeScript code base itself even [moved away from TypeScript namespaces to ES modules](https://github.com/microsoft/TypeScript/issues/39247) because ES modules are better.

I don't think it's worth it for esbuild to add additional complexity to support these unusual and non-recommended workflows. Instead, I recommend that you do code organization using normal ESM exports the way they are intended to be used.

**Comment by loynoir** [comment]
@evanw 

Thanks for your very professional and very detailed explaination!

Close in favor of https://github.com/sinclairzx81/typebox/issues/408
