### ISSUE TITLE
Multiple callbacks vs multiple plugins?

### ISSUE THREAD

**Issue by joelmoss** [evanw/esbuild#3078]
From a performance - or indeed any other - point of view, is it better to have fewer plugins with multiple onResolve/onLoad callbacks, or more plugins with fewer callbacks?

**Comment by evanw** [comment]
For performance, it's better to have no callbacks than to have some callbacks. This is why the `filter` property exists, and is mandatory. If any plugin's `filter` matches then esbuild has to send an expensive IPC from the Go process over to the JavaScript process, but if no plugins have a matching `filter` then esbuild can skip that part. Once esbuild has to run a given JavaScript callback for a single plugin, running it for another plugin isn't much of an additional performance cost (outside of the cost of running the callback itself of course). Also note that any plugin that uses a match-all filter (e.g. `{ filter: /.*/ }`) will cause the maximum performance penalty for that callback type as it means esbuild will always have to do an IPC. Also note that running `onResolve` callbacks is more expensive than running `onLoad` callbacks because they run more times, which means more overhead.

So the answer to your question is that it doesn't matter which plugin the callbacks come from because all callbacks for a given type basically become a flat array.

**Comment by joelmoss** [comment]
Ah but what if the plugins are all written in Go?

**Comment by evanw** [comment]
There should be virtually no performance impact for Go plugins outside of the code within the plugin itself.

**Comment by joelmoss** [comment]
Great! So makes no difference if I stuff everything into multiple callbacks in one plugin then?

**Comment by evanw** [comment]
No, I wouldn't expect it to make any observable difference.

**Comment by joelmoss** [comment]
Thanks bud, and thx for an amazing piece of software. You've also helped introduce me to the joys and speed of Go :)
