### ISSUE TITLE
Feature request: Entry point should contain information whether it has changed

### ISSUE THREAD

**Issue by esseswann** [evanw/esbuild#3084]
Currently if code changed in one of the entry points, all of them are being rebuilt or at least all of them are present in `outputFiles`. For our case it would be convenient to either provide only changed outputFiles or add a flag that describes whether it was changed since the last build

**Comment by evanw** [comment]
I'm thinking that providing the output file content hash (see #3293) would be a better way to do this. Providing only changed output files or providing a flag doesn't necessarily work for what you're trying to do because different builds can have different numbers of output files (i.e. sometimes an output file may be _removed_) and this information wouldn't be communicated in that case.
