### ISSUE TITLE
esbuild gets stuck for 15 minutes during ng build

### ISSUE THREAD

**Issue by infyklohar** [evanw/esbuild#3103]
Hi there..!!

We are experiencing issues with esbuild, where it gets stuck for 15 minutes like a timer.. while ng build is in progress.
ng build process doesn't get any timeout.. but gets successfully completed after 15 minutes.
Below are the build agent, code-base versions.. we tried with many combinations.. but still same issue.
All versions are consuming 20 mins to build defeating the purpose of ESBUILD which is to reduce the overall build time.
Could you please look into this and advise..? adding screen print for your reference.
![esbuild-stuck-state-0504](https://user-images.githubusercontent.com/19195472/236372021-73411864-91e3-4ac9-9b30-e42ad39ce9b7.jpg)
Appreciate your help.
Thanks.

Build-agent OS: RHEL-7.9, RHEL-8.7
code-base: Angular-14, node-14
code compilation utility tried: node-14.20.1, 14.21.3
different esbuild versions tried: 0.15.5 (default with Angular), 0.15.10, 0.15.12, 0.15.18, 0.16.2, 0.16.17, 0.17.2, 0.17.12, 0.17.18

**Comment by evanw** [comment]
I'm not sure what's going on, sorry. You'll have to investigate on your end. One random idea is that perhaps you are running out of memory. In that case increasing available memory or reducing the number of parallel requests to esbuild could fix this issue.

I'm closing this issue because I'm not the right person to investigate this (I don't know anything about Angular), and because the issue likely relates to whatever Angular is doing with esbuild. This repo that you created your issue in has nothing to do with Angular, and is not an appropriate place for Angular support requests. You'll have to find help with this issue elsewhere.
