### ISSUE TITLE
export the xxhash functions

### ISSUE THREAD

**Issue by ComLock** [evanw/esbuild#3113]
I tried to reimplement:
https://github.com/evanw/esbuild/blob/7d11ef1e24a3f0981e45e37200957268c4e22619/internal/xxhash/xxhash.go#L104C4-L117

In js:
https://github.com/enonic/starter-tsup/blob/70bfe36bc86e38a7e43978da0b0db23ad3f82833/tsup/static.ts#L44-L55

Yes, I have no idea what I'm doing :), but it works.

I would be great if all the xxhash api inside esbuild were exposed to js.

Something like:

```
import {xxhash} from 'esbuild'
```

I was thinking of making or extending a esbuild pluing to copy static files from node_modules and adding a hash to them, and in addition generate a manifest.json file for them.

Then I can serve immuteable assets (permalink, endless cache) instead of just etag.

(In the example above I do this with react and react-dom.)

**Comment by ComLock** [comment]
Made a plugin, will improve it
https://github.com/enonic-playground/esbuild-plugin-copy-with-hash

**Comment by evanw** [comment]
I'm closing this issue because I'm not planning on doing this. This is an internal implementation detail of esbuild that isn't meant to be a part of esbuild's API. For example, I may change the hash function that esbuild uses in the future if there's another one that makes more sense to use.

You can use Google to find a JavaScript xxhash implementation by yourself: https://www.google.com/search?q=xxhash+js. You can also use esbuild's built-in [copy loader](https://esbuild.github.io/content-types/#copy) to copy files and add a hash to them if you want to.
