### ISSUE TITLE
[BUG] Comments not being removed in latest esbuild

### ISSUE THREAD

**Issue by knaccc** [evanw/esbuild#3117]
esbuild is not removing all comments. Simple test case:

input file (in.js) contents:

```javascript
class MyClass {
  // first comment
  /* second comment */
}
// third comment
/* fourth comment */

```

```bash
esbuild --version
0.17.18
esbuild --outfile=out.js in.js
```

out.js contents:

```javascript
class MyClass {
  // first comment
  /* second comment */
}
```

esbuild is removing the third and fourth comments, but not the first and second comments.

Curiously, using `--minify` does remove all 4 comments, but using `--minify-identifiers` leaves in the first and second comments.

**Comment by evanw** [comment]
Comments are removed when minifying: https://esbuild.github.io/api/#minify. Specifically with `--minify-whitespace`, since comments are a form of whitespace.

**Comment by knaccc** [comment]
@evanw thanks for your quick reply - perhaps it should be more of a feature request, then, for esbuild to always remove all comments? It caught me by surprise, because at first it seemed to be removing all of the comments when I used it in `--minify-identifiers` mode.

Then, luckily, I checked again and found that it was removing **most** of the comments instead of **all** of the comments.

It seems inconsistent to remove most rather than all, and it's also very useful to be able to use esbuild as a lightning-fast comment stripper instead of using a second tool for that. Thanks again for the incredible work you do.

**Comment by evanw** [comment]
> It seems inconsistent to remove most rather than all

Some comments have been preserved because particular tools have particular semantics associated with them (e.g. #2721). All comments have not been preserved because doing so is a lot of work and it's not currently needed by any third-party tools that I have decided to commit to supporting.

> it's also very useful to be able to use esbuild as a lightning-fast comment stripper instead of using a second tool for that

Sorry, esbuild is not a comment stripper. Code formatting is not an intended use case for esbuild. Other tools exist for that.

I'm closing this issue because I do not consider it to be a bug with esbuild.
