### ISSUE TITLE
Facing vulnerability issue CVE-2022-29526 due to esbuild-wasm

### ISSUE THREAD

**Issue by harshint** [evanw/esbuild#3120]
This vulnerability (https://avd.aquasec.com/nvd/2022/cve-2022-29526/) seems to be originating from esbuild-wasm in my node modules because of using outdated go version.
Even the latest version of the package seems to be using older version of go that has this vulnerability.

**Comment by evanw** [comment]
The last time esbuild used Go 1.18.1 was [a year ago](https://github.com/evanw/esbuild/commit/3967668fca7594e9637fd7859682fbd54a932d60), and esbuild is currently [using Go 1.20.4](https://github.com/evanw/esbuild/blob/2f2b90a99d626921d25fe6d7d0ca50bd48caa427/Makefile#L23). You are welcome to build esbuild with Go 1.20.4 yourself to verify that the resulting binary is bitwise identical to the published version.

Either you are using a really old esbuild version or you are using a buggy security product. So you either need to update to a recent version of esbuild or report a false-positive to your security product vendor. You can read more about this problem here: https://esbuild.github.io/faq/#anti-virus-software.

I'm closing this issue because it's a problem on your end. There's nothing esbuild can do about this.

**Comment by sgurenkov** [comment]
these are the version affected: `< 1.19.10, 1.20.0-0 ≤ Version < 1.20.5`

is it possible to update go to at lease `1.20.5`?

here is the vulnerability report: https://pkg.go.dev/vuln/GO-2023-1840
