### ISSUE TITLE
AG Grid bundled as cjs in esm project

### ISSUE THREAD

**Issue by tim-hilt** [evanw/esbuild#3124]
I'm bundling an application that also includes AG Grid. Although I have set `format: "esm"` in my `esbuild.config.mjs`, I still see AG Grid show up as cjs module, when running the metafile through esbuild analyzer:

<img width="1007" alt="image" src="https://github.com/evanw/esbuild/assets/16037579/0dec6d90-a2ab-409b-95b3-8f1bee425a23">

Here is my `esbuild.config.mjs`:

``` js
export default () =>
  build({
    entryPoints: ["index.ts"],
    outdir: "dist",
    splitting: true,
    bundle: true,
    minify: true,
    format: "esm",
    allowOverwrite: true,
    plugins, // copy-plugin and sass-plugin - shouldn't be relevant
    metafile: true,
  }).then((res) => {
    fs.writeFileSync("meta.json", JSON.stringify(res.metafile));
  });
```

**Comment by tim-hilt** [comment]
I guess a more general title for this question could be: "How can I force esbuild to always bundle the esm-version of a dependency?"

**Comment by evanw** [comment]
You may find `logLevel: 'verbose'` informative. It makes esbuild explain what it's doing during path resolution: https://esbuild.github.io/api/#log-level.

> How can I force esbuild to always bundle the esm-version of a dependency?

This is typically controlled by the package author via `exports` in `package.json`, in which case esbuild respects what the package says to do. If a package doesn't set `exports` but does set `module` (typically ESM) and `main` (typically CommonJS), then esbuild may pick `main` over `module` if you use `require` instead of `import`. If that's happening then you can either use `import` instead of `require` (not always possible if it's 3rd-party code) or control this with something like `mainFields: ['module', 'main']` to explicitly prioritize `module` over `main`: https://esbuild.github.io/api/#main-fields. Keep in mind that messing with `mainFields` can sometimes introduce issues with certain packages (which is why esbuild's default behavior is the way it is). And regardless of this specific situation, you can always override esbuild by writing a plugin that redirects import paths to wherever you want them to go: https://esbuild.github.io/plugins/#on-resolve.

**Comment by tim-hilt** [comment]
Adding `mainFields: ['module', 'main']` brought down the cjs ratio in my bundle significantly. Thanks for that! I'll have to investigate if it leads to any issues though. Thanks so far!
