### ISSUE TITLE
[css-minifier] Support `layer` for `@import`

### ISSUE THREAD

**Issue by binyamin** [evanw/esbuild#3137]
CSS allows authors to assign a cascade layer to an imported file, like so:
```css
@import 'theme.css' layer(core);
```
This is equivalent to having enclosed the contents of the imported file in a cascade layer.

**Expected Behavior**: Output the import statement with the layer-name. The only relevant optimization I can think of is minification.
**Actual Behavior**: Esbuild thinks it's a conditional import, and throws an error, because it can't bundle conditional imports.

---
- [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/@import#importing_css_rules_into_a_cascade_layer)
- Related: https://github.com/evanw/esbuild/issues/2437

**Comment by evanw** [comment]
This isn't trivial to implement because currently importing a file twice doesn't actually bundle it twice (i.e. imports are deduplicated by their file path). I think this would mean that different layers should essentially count as different files. Which should be possible to implement, but I'll have to integrate this information into esbuild's internal file cache key.
