### ISSUE TITLE
Access pluginData after final output

### ISSUE THREAD

**Issue by caramboleyo** [evanw/esbuild#3143]
I wonder if there is a way to access pluginData collected during onLoad in the final result?

 final result looks like this:
 ```
{
  errors: [],
  warnings: [],
  outputFiles: [
    {
      path: "<stdout>",
      contents: Uint8Array(2828) [
         47,  42,  32, 104, 116, 116, 112,  45, 117, 114, 108,  58, 104, 116,
        116, 112, 115,  58,  47,  47,  99, 100, 110,  46, 119, 111, 114, 108,
        100,  97, 112, 105,  46, 111, 114, 103,  47,  99, 115, 115,  47, 102,
        111, 110, 116, 115,  47, 115, 101, 103, 111, 101,  47,  99,  97,  99,
        104, 101,  46,  99, 115, 115,  32,  42,  47,  10,  64, 102, 111, 110,
        116,  45, 102,  97,  99, 101,  32, 123,  10,  32,  32, 102, 111, 110,
        116,  45, 102,  97, 109, 105, 108, 121,  58,  32,  83, 101, 103, 111,
        101,  85,
        ... 2728 more items
      ],
      text: [Getter]
    }
  ],
  metafile: undefined,
  mangleCache: undefined
}
```
i do not see the pluginData anywhere.
How can i return data i collected in my custom onLoad function to the final result?

**Comment by evanw** [comment]
`onLoad` is called for input files but the result returns output files. There is not necessarily a 1-to-1 mapping of input files to output files because esbuild is a bundler. So it’s not clear what you’re asking for. 

You can already store a mapping of input file to metadata in your plugin if you want to, which you could mutate within your `onLoad` callback. Your plugin could even mutate the build result to include the metadata you desire in an `onEnd` callback if you wanted to.

**Comment by evanw** [comment]
I'm closing this issue because this doesn't seem to be a problem with esbuild. You should already be able to store this information for yourself if you need it, as described above.
