### ISSUE TITLE
`jsx` loader tree shaking behavior is different from `tsx` loader

### ISSUE THREAD

**Issue by ArrayZoneYour** [evanw/esbuild#3146]
`index.jsx`
```jsx
console.log(1);

class Component {}

class CenterToast extends Component {

  static toast = {};
  static info = {};

  componentDidMount() {
  }

  render() {
    const { message, isVisible, icon, color, eventsPassThrough } = this.state;
    return null;
  }
}

```

tree shaking result is clean

[esbuild repl](https://hyrious.me/esbuild-repl/?version=0.17.19&mode=transform&input=console.log%281%29%3B%0A%0Aclass+Component+%7B%7D%0A%0Aclass+CenterToast+extends+Component+%7B%0A%0A++static+toast+%3D+%7B%7D%3B%0A++static+info+%3D+%7B%7D%3B%0A%0A++componentDidMount%28%29+%7B%0A++%7D%0A++render%28%29+%7B%0A++++const+%7B+message%2C+isVisible%2C+icon%2C+color%2C+eventsPassThrough+%7D+%3D+this.state%3B%0A++++return+null%3B%0A++%7D%0A%7D%0A&options=--loader%3Djsx+--tree-shaking%3Dtrue)

`index.tsx`
```tsx
console.log(1);

class Component {}

class CenterToast extends Component {

  static toast = {};
  static info = {};

  componentDidMount() {
  }

  render() {
    const { message, isVisible, icon, color, eventsPassThrough } = this.state;
    return null;
  }
}
```

class declaration & its static member declaration is kept after tree shaking

[esbuild repl](https://hyrious.me/esbuild-repl/?version=0.17.19&mode=transform&input=console.log%281%29%3B%0A%0Aclass+Component+%7B%7D%0A%0Aclass+CenterToast+extends+Component+%7B%0A%0A++static+toast+%3D+%7B%7D%3B%0A++static+info+%3D+%7B%7D%3B%0A%0A++componentDidMount%28%29+%7B%0A++%7D%0A++render%28%29+%7B%0A++++const+%7B+message%2C+isVisible%2C+icon%2C+color%2C+eventsPassThrough+%7D+%3D+this.state%3B%0A++++return+null%3B%0A++%7D%0A%7D%0A&options=--loader%3Dtsx+--tree-shaking%3Dtrue)

**Comment by hyrious** [comment]
This is because by default the ts/tsx loader will use `useDefineForClassFields: false` in aligning with the official TypeScript compiler. It generates `CenterToast.toast = {}` at the end, which is considered having side effect and is not tree-shakeable.

You can enable that in tsconfig ([repl link](https://hyrious.me/esbuild-repl/?version=0.17.19&mode=transform&input=console.log%281%29%3B%0A%0Aclass+Component+%7B%7D%0A%0Aclass+CenterToast+extends+Component+%7B%0A%0A++static+toast+%3D+%7B%7D%3B%0A++static+info+%3D+%7B%7D%3B%0A%0A++componentDidMount%28%29+%7B%0A++%7D%0A++render%28%29+%7B%0A++++const+%7B+message%2C+isVisible%2C+icon%2C+color%2C+eventsPassThrough+%7D+%3D+this.state%3B%0A++++return+null%3B%0A++%7D%0A%7D%0A&options=--loader%3Dtsx+--tree-shaking%3Dtrue+--tsconfig-raw%3D%27%7B%22compilerOptions%22%3A%7B%22useDefineForClassFields%22%3Atrue%7D%7D%27)), or use `--target=esnext` which is shorter.
