### ISSUE TITLE
Support `#__NO_SIDE_EFFECTS__` comment from Rollup

### ISSUE THREAD

**Issue by antfu** [evanw/esbuild#3149]
With a similar reasoning:
- https://github.com/evanw/esbuild/issues/1883

We recently shipped `#__NO_SIDE_EFFECTS__` in Rollup (https://github.com/rollup/rollup/pull/5024). We wish to push this convention to be supported in other build tools and to benefit library authors to make more portable and flexible libraries.

Would love the hear the thoughts from `esbuild` side. Thanks!

**Comment by antfu** [comment]
Currently, when using `rollup-plugin-esbuild`, the comments are not preserved, and `__NO_SIDE_EFFECTS__` is not recognized by esbuild. We need to use `/*!` to preserve them.

- https://github.com/rollup/rollup/pull/5024#issuecomment-1580285756

It would be great to esbuild been able to preserve it, or even provide tree-shaking capability with that convention.

**Comment by paulmillr** [comment]
Why is it `#__NO_SIDE_EFFECTS__`, but `/* @__PURE__ */`? Does `@__NO_SIDE_EFFECTS__` also work?

**Comment by evanw** [comment]
I can look into preserving comments containing `/* #__NO_SIDE_EFFECTS__ */`. I don't think it's possible to actually implement this feature in esbuild with esbuild's current tree shaking code as side effect detection is currently done locally for each file.

**Comment by evanw** [comment]
I looked into this. A few questions:

* Is there any documentation about how this is supposed to work? I found [this](https://rollupjs.org/configuration-options/#no-side-effects) but it isn't a specification (e.g. it doesn't say exactly where you can use these comments). So I'm trying to reverse-engineer the expected behavior from the Rollup REPL.

* It looks like the annotation sort of works with variable declarations, but only for the first declaration and only for `const`. Is that right?

* Is there a reason why this annotation doesn't work with `async` functions? It seems to work with regular functions and generator functions.

* It doesn't appear to work for object methods, class methods, or class fields. So it shouldn't work in these places when using esbuild either then, right?

**Comment by antfu** [comment]
Thanks a lot for the prompt support!

We were discussing with @lukastaegert that we should have a repo hosting the spec for `__PURE__` as well as `__NO_SIDE_EFFECTS__`, as where were never a proper doc/spec for them. We will see!

As for the async function and generator, that's a good point and actually was my mistake to miss them. I will send a PR to fix it on Rollup soon. I guess that makes sense for esbuild to still present the comments for them as well.
