### ISSUE TITLE
Provide example in docs on how to run esbuild without Yarn's CLI when using P'n'P

### ISSUE THREAD

**Issue by MatsG23** [evanw/esbuild#3157]
The documentation says that the [Yarn's CLI adds a performance overheap](https://esbuild.github.io/getting-started/#yarn-pnp) to every command, including esbuild. How am I meant to run esbuild without Yarn's CLI when using the Yarn Plug'n'Play feature? All that works for me seems to be `yarn esbuild`, which the documentation does not recommend. Because of P'n'P, there is no `node_modules`folder, so I cannot use the typical command `./node_modules/.bin/esbuild`. It would probably work using [pnpify](https://yarnpkg.com/package/@yarnpkg/pnpify) but this workaround may even add a greater performance overheap to the esbuild command than Yarn's CLI.

**Comment by evanw** [comment]
How to install esbuild without Yarn is already the topic of the section immediately following this one: https://esbuild.github.io/getting-started/#other-ways-to-install. For example, the first option in that section would work: https://esbuild.github.io/getting-started/#download-a-build.

I assume if you’re using Yarn that Yarn’s unique behavior regarding how dependencies are stored on the file system is more important to you than performance, because it comes at a heavy performance cost. So I assume that running esbuild with `yarn esbuild` (instead of installing esbuild without Yarn) will make the most sense for you. 

I’m mainly documenting Yarn’s performance overhead here for people who are wondering why it’s so slow (i.e. that it’s not esbuild’s fault). If performance was more important to you than Yarn’s unique dependency storage mechanism, then I believe the simplest way to improve performance would be to not use Yarn.
