### ISSUE TITLE
The module imported with the path alias specified in paths in tsconfig.json is not being bundled

### ISSUE THREAD

**Issue by mattp0123** [evanw/esbuild#3160]
https://esbuild.github.io/try/#YgAwLjE4LjIALS1idW5kbGUgLS1wbGF0Zm9ybT1uZXV0cmFsIC0tcGFja2FnZXM9ZXh0ZXJuYWwAZQBzcmMvaW5kZXgudHMAaW1wb3J0IHsgZm9vIH0gZnJvbSAnfi9mb28nCgpjb25zb2xlLmxvZyhmb28pAABzcmMvZm9vLnRzAGV4cG9ydCBjb25zdCBmb28gPSAnZm9vJwAAdHNjb25maWcuanNvbgB7CiAgImNvbXBpbGVyT3B0aW9ucyI6IHsKICAgICJzdHJpY3QiOiB0cnVlLAogICAgIm1vZHVsZVJlc29sdXRpb24iOiAiYnVuZGxlciIsCiAgICAibW9kdWxlIjogIkVTTmV4dCIsCiAgICAidGFyZ2V0IjogIkVTTmV4dCIsCiAgICAiYmFzZVVybCI6ICJzcmMiLAogICAgInBhdGhzIjogewogICAgICAifi8qIjogWyIqIl0KICAgIH0KICB9LAogICJpbmNsdWRlIjogWyJzcmMvKiovKiJdLAogICJleGNsdWRlIjogWyJub2RlX21vZHVsZXMiXQp9

Expect the output to be:
```javascript=
var foo = 'foo'
console.log(foo) 
```

**Comment by hyrious** [comment]
I guess this is because `--packages=external` marks every path not starting with `[./]` as external before the bundle resolution works. [repl link without that option](https://esbuild.github.io/try/#YgAwLjE4LjIALS1idW5kbGUgLS1wbGF0Zm9ybT1uZXV0cmFsAGUAc3JjL2luZGV4LnRzAGltcG9ydCB7IGZvbyB9IGZyb20gJ34vZm9vJwpjb25zb2xlLmxvZyhmb28pAABzcmMvZm9vLnRzAGV4cG9ydCBjb25zdCBmb28gPSAnZm9vJwAAdHNjb25maWcuanNvbgB7CiAgImNvbXBpbGVyT3B0aW9ucyI6IHsKICAgICJzdHJpY3QiOiB0cnVlLAogICAgIm1vZHVsZVJlc29sdXRpb24iOiAiYnVuZGxlciIsCiAgICAibW9kdWxlIjogIkVTTmV4dCIsCiAgICAidGFyZ2V0IjogIkVTTmV4dCIsCiAgICAicGF0aHMiOiB7CiAgICAgICJ+LyoiOiBbIi9zcmMvKiJdCiAgICB9CiAgfSwKICAiaW5jbHVkZSI6IFsic3JjLyoqLyoiXSwKICAiZXhjbHVkZSI6IFsibm9kZV9tb2R1bGVzIl0KfQ)

Note that `baseUrl` is prepended to the aliased path, so you should avoid duplicate segments between them.

**Comment by mattp0123** [comment]
@hyrious thank you for the reply, I trying to bundle my node app to esm syntax output (mjs), any suggestion?

**Comment by hyrious** [comment]
One possible way is to use `--external:pkgname` to manually exclude dependencies instead of using packages=external. In 99% of the cases, you only have to exclude the keys from your package.json/dependencies so:

```js
let pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'))
esbuild.build({ ...options, external: Object.keys(pkg.dependencies) })
```

**Comment by mattp0123** [comment]
@hyrious Thank you, I also add a `banner` option to avoid this [issue](https://github.com/evanw/esbuild/pull/2067)
```
{
  ...options,
  banner: {
    js: "import { createRequire } from 'module';const require = createRequire(import.meta.url);",
  },
}
```
