### ISSUE TITLE
How do I bundle each package separately?

### ISSUE THREAD

**Issue by newtack** [evanw/esbuild#317]
Our use case is that we want to create an esm bundle for each of our npm dependencies so we can use esm in the browser during development. Somewhat similar to pika/vite, but we want to use esbuild for it.

We could use the external flag but it becomes really unwieldy if we have 20 externals that we need to exclude. 

1) Is it possible to have the options read from a json config file instead of only passing it in the command line? Similar to how the Typescript compiler allows passing options via either the command line or via a tsconfig.json, it would be great if we could have such a json config file for esbuild.
2) Is it possible to indicate "exclude all other dependencies" rather than listing each dependency we want to exclude?

**Comment by evanw** [comment]
You'll want to try esbuild's [JavaScript API](https://github.com/evanw/esbuild/blob/df265cd66c625e20704738312f85acdfd256f4d1/docs/js-api.md#running-a-build) to automate tasks like this. It's sort of like having a config file but even better because you can include JavaScript code too (e.g. do a loop over all of your externals in your case). It should have enough power that you can do the custom stuff you need it to. For example, you could programmatically list all packages you depend on and convert them to externals.
