### ISSUE TITLE
Minified line lengths

### ISSUE THREAD

**Issue by jawj** [evanw/esbuild#3170]
I bundle a library using esbuild with `--minify`. Most of the minified code is in lines of >30,000 characters.

When the library throws an Error, the stack trace includes a code excerpt, which I think must be defined as a specific number of lines. This means that users have to scroll back up a **very** long way to find the error message.

I'd like to keep minifying the library, but it would be great if there was an option to emit shorter lines. Two possibilities that come to mind:

* Always emit `\n` instead of `;` when the effect is the same (keeps output size constant)
* Emit a `\n` after a `;` if there hasn't been one for the last N characters (potentially simpler to implement)

Is either of these (or something else) a possibility?

**Comment by evanw** [comment]
I’m looking at what other tools do. Terser and UglifyJS seem to have a `max_line_len` setting. Google Closure Compiler says it [adds like breaks approximately every 500 characters](https://developers.google.com/closure/compiler/faq?csw=1#linefeeds) as a holdover from a time when buggy routers corrupted JavaScript files with long lines. 

It would be nice to not have the size be any bigger, in which case this could happen automatically. Computing whether it’s safe to omit a semicolon is somewhat complicated both because the printer doesn’t necessarily know what will be printed next, and because going back and changing a semicolon to a newline messes up source map generation. 

Note to self: I’ll try to think of a way of doing this. Maybe `printSemicolonIfNeeded` can set a flag and later code can rewrite the semicolon into a newline. It shouldn’t be too complicated regarding source maps if it’s at the end of the current code string.

**Comment by jawj** [comment]
Many thanks for the quick reply @evanw (and many thanks for esbuild too, of course)! I look forward to seeing what you come up with.

**Comment by evanw** [comment]
I looked into this a bit. Relying on ASI is possible but hurts gzip size, so it's probably not something that would be turned on by default.
