### ISSUE TITLE
Not able to add default export option in esbuild

### ISSUE THREAD

**Issue by Ajadli** [evanw/esbuild#3175]
When using webpack we can give libraryExport and library
```
output: {
        path: path.join(__dirname, '/dist'),
        filename: 'reddis.bundle.js',
        publicPath: "/",
        libraryTarget: 'var',
        libraryExport: 'default',
        library: 'reddisCacheBundle',
        sourceMapFilename: "[file].tsx.map"
    },
```

![image](https://github.com/evanw/esbuild/assets/108657556/8026073f-fbda-4357-98af-06d821aaf563)

How can i give that in esbuild ?

**Comment by Ajadli** [comment]
Curreent Settings : 

// esbuild.config.js
```
const res = require('esbuild').buildSync({
    entryPoints: ['src/index.tsx'],
    bundle: true,
    minify: false,
    format: 'iife',
    sourcemap: false,
    
    mainFields: ["browser", "main"],
    platform: "browser",
    loader :{
        '.png' : 'binary'
    },
    
    outfile: 'dist/output.js',
  })
```

**Comment by hyrious** [comment]
I guess you're looking for [--global-name=reddisCacheBundle](https://esbuild.github.io/api/#global-name).

**Comment by Ajadli** [comment]
@hyrious can i bundle .css file and .js into 1 file only ?

**Comment by hyrious** [comment]
If you want to replicate the style-loader (which creates `<style>` tags at runtime) behavior from webpack in esbuild, you can write a simple plugin to do so. [This repo](https://github.com/hyrious/esbuild-plugin-style/blob/main/index.ts) may give you some inspirations.

**Comment by evanw** [comment]
Yes, https://esbuild.github.io/api/#global-name is the way to do this (specifically to export the entry point as a property on the global object when using the `iife` format). So I'm closing this issue as esbuild can already do this.

For the comment about CSS: Note that CSS-in-JS may be less efficient than using separate .css and .js files, since using separate files allows the browser to download (and also cache) both files in parallel. That is one of the reasons why esbuild doesn't have a built-in way to do this.
