### ISSUE TITLE
Suggestion: Regular Expression minification

### ISSUE THREAD

**Issue by Conaclos** [evanw/esbuild#3181]
I found a missed opportunity of minification: Regular Expression minification.

For instance the following regex

```js
/[A-Za-z0-9_]{0,}[0-9]{1,}/
```

could be minified to:

```js
/\w*\d+/
```

**Comment by hiteshbedre** [comment]
Need to change the middle forward slash to backward.

```php

/\w*\d+/

**Comment by Conaclos** [comment]
Thanks! I edited the post.

**Comment by evanw** [comment]
Thanks for the suggestion. However, this seems very low-priority to me since a) parsing and optimizing regular expressions is a decent amount of effort, b) regular expressions are typically a very small part of your source code, and b) I don't think any existing JavaScript minifiers do this transformation. At least [Terser](https://terser.org/), [Uglify](https://github.com/mishoo/UglifyJS), [SWC](https://swc.rs/), and [Google Closure Compiler](https://developers.google.com/closure/compiler/) all don't do this. So I'm closing this issue as I'm not planning on doing this.

**Comment by Conaclos** [comment]
Thanks for the detailed explanation! Have a nice day :)
