### ISSUE TITLE
Stupid question about async/promises in bundles and esbuild's threading structure

### ISSUE THREAD

**Issue by joshbrew** [evanw/esbuild#3187]
Two questions:

1. Can plugins return content asynchronously? E.g. for parallel compilation with workers.
2. Is esbuild multithreaded anyway to the point this would be redundant?

For science :-)

**Comment by evanw** [comment]
1. Yes. Plugins are allowed to return a promise, which will be awaited. You can see that in [the type definitions here](https://github.com/evanw/esbuild/blob/7d5df1004c34e04050d2ddc19be3114d5c258bd5/lib/shared/types.ts#L303-L309). 

2. Well esbuild is multithreaded but JavaScript is single-threaded. So regardless of whether your plugin is sync or async, esbuild can do other work in the meantime while your plugin is running. But only one plugin can ever be running at a time (for JavaScript-based plugins, obviously Go-based plugins can run in parallel). Returning a promise from your plugin is a way to yield control to another plugin in the meantime. For example, this is useful when your plugin is waiting on a network request.

**Comment by joshbrew** [comment]
I'm just thinking about possibly compiling fat node_modules imports in workers in parallel. Does esbuild decide when to split compilation into threads automatically? I.e. would that be redundant? Or if I, say, setup promises in the onLoad for each import path to have those run independent build commands, would that parallelize the build step more? I'm guessing this is taken care of under the hood since that makes the most sense for a lower level to handle.

**Comment by joshbrew** [comment]
I'll add, that right now I am doing something close to this having workers bundled in their own build step in an async onLoad function, however they still resolve the content synchronously

**Comment by evanw** [comment]
JavaScript is a single-threaded language. Promises in JavaScript are concurrency, not parallelism. Concurrency means that task evaluation may overlap but only one task is ever being worked on at a time. If you want to introduce parallelism, you’ll have to do it yourself by spawning other JavaScript VMs (e.g. with a worker API). This is not something that esbuild does for you. Of course if you’re using Go to write esbuild plugins then they do run in parallel, but that’s because the Go runtime has parallelism built in.

**Comment by joshbrew** [comment]
I'm aware of JS being single threaded by default, and I'm good with the worker-fu otherwise, so I'm mainly wondering if the "contents" resolved in a plugin onLoad can be done in parallel so I can then implement dependencies compiling in threads, or if that's redundant based on what's under the hood for esbuild.

**Comment by evanw** [comment]
I think you're asking whether esbuild's API calls can run in parallel (i.e. when you call `build` in your code). The answer is basically yes.

Calling esbuild's `build` function from JavaScript sends the serialized build options to esbuild (which is running in a separate process) and then runs other JavaScript while it waits for the esbuild process's reply. When the esbuild process gets an incoming serialized build API call, it spawns a new Go thread to handle it, so any work that esbuild does regarding that build API call runs in parallel with all other work esbuild is doing for other API calls that are already in progress. Then when esbuild has finished the work for a build API call, it will send the serialized build result back to JavaScript which will schedule an event on the JavaScript event loop to resolve the promise returned by `build`. The serialization and deserialization that happens in JavaScript isn't parallel because it's JavaScript, but everything that happens within the esbuild process is parallel.

So if you're calling esbuild's build API concurrently, it's likely better for that to be done in the same JavaScript VM than in different JavaScript VMs because esbuild's JavaScript API creates one esbuild process per VM you call it in. Since each esbuild process already spawns as many threads as you have CPU cores, multiple esbuild processes would unnecessarily compete for resources. So you probably shouldn't create a nested JavaScript worker VMs just to call esbuild's build API from. Instead you should probably just call esbuild's API from the main thread since esbuild's API naturally parallelizes all esbuild-specific work under the hood. The simplest way of using esbuild's API is also usually the fastest.

The only reason that it might make sense to call esbuild's API concurrently from separate JavaScript workers is if your build time is dominated by JavaScript plugin execution and you're trying to parallelize that. However, that still might be better served by calling esbuild's API only from the main thread and then calling out to JavaScript workers from within your plugin instead of using a separate esbuild instance per JavaScript worker.

Hopefully that helps.

**Comment by joshbrew** [comment]
Interesting, so sounds mostly redundant for what I can add, I can think of a way to make this work to parallelize a plugin while respecting the serialization though but might be more effort than it's worth. Thank you!
