### ISSUE TITLE
Improving the filesystem watcher

### ISSUE THREAD

**Issue by fabiospampinato** [evanw/esbuild#3209]
I've just [implemented](https://github.com/fabiospampinato/pollex) a TS version of esbuild's filesystem watcher, as I understand it at least, because I find it cute in its simplicity while still being surprisingly decent for some use cases.

While writing it I thought of a couple of potential improvements, that I haven't implemented yet though, that might be useful for esbuild too.

As I understand it currently there are two tiers, a hot one for changed files and a cold one for unchanged files, but:

- It can happen that a new file is added to the watched directory, that file is probably more likely to be edited soon than cold files, but if every added file is added to the hot tier immediately it may be a problem if a big-ish folder containing files that won't actually be edited soon is added to the watched folder, and likewise if added files are added to the cold tier we lose a bit of information that we could have potentially used to speed things up. Maybe a better solution would be to have a "warm" tier that's refreshed more frequently than the cold tier but less frequently than the hot tier?
- Alternatively, though I guess it could be a complimentary idea also, it may be interesting to cool hot files down over time, otherwise for long-running filesystem watching sessions the hot tier might just grow without bounds. And cooling hot files down seems more precisely what should happen compared to having an lru for hot files for example. 
- Maybe tiers should be deleted entirely, and the probability of each file to get refreshed soon should just be higher the hotter it is. And editing a file makes it boiling hot, while every file gets gradually colder over time if not edited.

Maybe they could make sense? Just some random ideas.

**Comment by evanw** [comment]
Thank you for your ideas. However, I believe that esbuild's watch mode as it's currently implemented is already sufficient. These optimizations are mainly tuned for rapidly editing a handful of files, in which case all files being actively edited should always be hot (since esbuild tracks up to 16 hot items). So I'm not planning on doing any of these ideas. We can look at these ideas if it turns out later on that esbuild's watch mode behavior is insufficient for these goals.
