### ISSUE TITLE
Support `budgets` config option

### ISSUE THREAD

**Issue by DrewMcArthur** [evanw/esbuild#3221]
in my `angular.json` config, i have a `budgets` option that specifies maximum file sizes for different types of files.  when running `ng build` with this builder enabled, i get the warning:

```
The 'budgets' option is not yet supported by this builder.
```

here's an example config snippet:
```json
          "configurations": {
            "development": {
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "50kb",
                  "maximumError": "100kb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "2kb",
                  "maximumError": "10kb"
                },
              ],
            },
```

**Comment by ghiscoding** [comment]
this seems totally unrelated to esbuild, it seems more of something that the Angular team will have to address eventually, they probably did not investigate how to deal with it yet because like it says esbuild with Angular is still experimental and I'm pretty sure they will eventually add this budget option in the future.

**Comment by DrewMcArthur** [comment]
ah okay, my bad. i assumed it was esbuild-related since that was the only thing i changed, plus the language around "supported by this builder".  feel free to close if this isn't the right place to track @ghiscoding

**Comment by evanw** [comment]
Yes this isn't the right place, sorry. This repo has nothing to do with Angular.
