### ISSUE TITLE
Install failure on node 18 and m1 mac

### ISSUE THREAD

**Issue by LukkaAustin** [evanw/esbuild#3224]
Hello! I am working on an m1 mac and using node 18.16.1. Node was installed via nvm. If I cd into an empty directory and run `npm i esbuild`, node throws an error and fails to install.

The error message is:
```npm ERR! code 1
npm ERR! path /Users/<my username>/p/esbuild-test/node_modules/esbuild
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! node:internal/errors:867
npm ERR!   const err = new Error(message);
npm ERR!               ^
npm ERR! 
npm ERR! Error: Command failed: /Users/<my username>/p/esbuild-test/node_modules/esbuild/bin/esbuild --version
npm ERR!     at checkExecSyncError (node:child_process:885:11)
npm ERR!     at Object.execFileSync (node:child_process:921:15)
npm ERR!     at validateBinaryVersion (/Users/<my username>/p/esbuild-test/node_modules/esbuild/install.js:98:28)
npm ERR!     at /Users/<my username>/p/esbuild-test/node_modules/esbuild/install.js:285:5 {
npm ERR!   status: null,
npm ERR!   signal: 'SIGKILL',
npm ERR!   output: [ null, Buffer(0) [Uint8Array] [], Buffer(0) [Uint8Array] [] ],
npm ERR!   pid: 64503,
npm ERR!   stdout: Buffer(0) [Uint8Array] [],
npm ERR!   stderr: Buffer(0) [Uint8Array] []
npm ERR! }
npm ERR! 
npm ERR! Node.js v18.16.1

**Comment by evanw** [comment]
I assume `SIGKILL` means something on your computer is killing esbuild. This is not a problem with esbuild, but is instead a problem with your computer. It could be that you have some other process that isn't letting esbuild run such as an anti-virus program or a system security policy against unexpected binary executables. If you do want to use esbuild then you'll have to configure it to allow esbuild to run. Or you can use the WebAssembly version of esbuild to bypass the problematic security policy, or you can use another tool instead of esbuild. See also https://esbuild.github.io/faq/#anti-virus-software.

**Comment by JWo1F** [comment]
Hi guys, I have a node **v18**.16.1 and m1 mac and have successfully installed esbuild.

**Comment by LukkaAustin** [comment]
This is exactly what it was. Thank you so much for the help!
