### ISSUE TITLE
Regression in 0.18.4 when using static class properties inside of decorators

### ISSUE THREAD

**Issue by mattlewis92** [evanw/esbuild#3230]
First off I just wanted to say thank you for esbuild and all the work you do maintaining it, it's made such an enormous improvement to our developer productivity ❤️ 

When upgrading to 0.18.x we found a bug introduced by https://github.com/evanw/esbuild/pull/3167 where using static class properties inside of decorators causes errors to be thrown at runtime. Playground link [here](https://esbuild.github.io/try/#dAAwLjE4LjQAewogIGxvYWRlcjogJ3RzJywKICB0YXJnZXQ6IFsnbm9kZTE2J10sCiAgdHNjb25maWdSYXc6ICd7ImNvbXBpbGVyT3B0aW9ucyI6IHsiZXhwZXJpbWVudGFsRGVjb3JhdG9ycyI6IHRydWUsfSx9Jwp9AGV4cG9ydCBjbGFzcyBEb2N1bWVudFNlYXJjaE9wdGlvbnMgewogICAgcHJpdmF0ZSBzdGF0aWMgcmVhZG9ubHkgRGVmYXVsdExpbWl0U2l6ZSA9IDE1OwoKICAgIHByaXZhdGUgc3RhdGljIHJlYWRvbmx5IE1heEZpbHRlcnNTaXplID0gMjA7CgogICAgbGltaXQgPSBEb2N1bWVudFNlYXJjaE9wdGlvbnMuRGVmYXVsdExpbWl0U2l6ZTsKCiAgICAvLyB3aWxsIHRocm93ICJUeXBlRXJyb3I6IENhbm5vdCByZWFkIHByb3BlcnRpZXMgb2YgdW5kZWZpbmVkIChyZWFkaW5nICdNYXhGaWx0ZXJzU2l6ZScpIiArCiAgICBAQXJyYXlNYXhTaXplKERvY3VtZW50U2VhcmNoT3B0aW9ucy5NYXhGaWx0ZXJzU2l6ZSkgCiAgICBmaWx0ZXJzOiBEb2N1bWVudFNlYXJjaEF2YWlsYWJsZUZpbHRlcltdOwp9). 

Due to `export let DocumentSearchOptions = _DocumentSearchOptions;` being set _after_ the call to `__decorateClass`, it means that `DocumentSearchOptions.MaxFiltersSize` will throw an error at runtime.

Please let me know if you need any more info!

**Comment by evanw** [comment]
Hmm. It looks like this is a difference between legacy TypeScript decorators and standard JavaScript decorators. Accessing the class name before its declaration is finished works with legacy TypeScript decorators but will no longer work with standard JavaScript decorators (compare [this](https://www.typescriptlang.org/play?experimentalDecorators=true&ts=5.1.6#code/C4TwDgpgBAIg9gYwK4FsIDtgGUIEMBOCAFgIIBuuAlgDa4BG1EAYjcBPlALxTqp3sBuAFBCEcdAGdgUEvny4QAWVwAPLJQBe0bgAoVALh592ASi4A+KAG8hUO1HwRgSfOig7chpOgAmEAGaU6BA+ADRQdIYAwrQSEiwQ1D4wEGLywHD4UeJsKsBmnJZ6hvDIaJg4BMTkVLQMzKzsANoAugWWKsIAvsKisRKwiKgY2HiERADyYMCU4gM29lBg+JQUbFBSuDMIDng+4tQgsAG4SNTAADKUKJTYmtpQAIwArL2Ly6tb0Jvbu7j76EOUGUKhY53YEnUWi4UAATAAGN72ajXW4w0rDCpjYhTGZzAB0KX8p3OVxudy0SLsAHpqVAAO40ahQYBEfBwelQABEABVwBAAKJyTLRXDodBwaSOf5LdmQfAzCADOD+KDePyBYI+dzSnxBADmUAA5CCwWx8JD7kaTFyoABqWz2AACsnkSlUUIgOgx5VGVUm01mknxpsaFs9ZkddkC4ItJSGvsq4xqNHojDNzRaMNa3SEQA) to [this](https://www.typescriptlang.org/play?ts=5.1.6#code/C4TwDgpgBAIg9gYwK4FsIDtgGUIEMBOCAFgIIBuuAlgDa4BG1EAYjcBPlALxTqp3sBuAFBCEcdAGdgUEvny4QAWVwAPLJQBe0bgAoVALh592ASi4A+KAG8hUO1HwRgSfOig7chpOgAmEAGaU6BA+ADRQdIYAwrQSEiwQ1D4wEGLywHD4UeJsKsBmnJZ6hvDIaJg4BMTkVLQMzKzsANoAugWWKsIAvsKisRKwiKgY2HiERADyYMCU4gM29lBg+JQUbFBSuDMIDng+4tQgsAG4SNTAADKUKJTYmtpQAIwArL2Ly6tb0Jvbu7j76EOUGUKhY53YEnUWi4UAATAAGN72ajXW4w0rDCpjYhTGZzAB0KX8p3OVxudy0SLsAHpqVAAO40ahQYBEfBwelQABEABVwBAAKJyTLRXDodBwaSOf5LdmQfAzCADOD+KDePyBYI+dzSnxBADmUAA5CCwWx8JD7kaTFyoABqWz2AACsnkSlUUIgOgx5VGVUm01mknxpsaFs9ZkddkC4ItJSGvsq4xqNHojDNzRaMNa3SEQA)). Running this code using standard JavaScript decorators will throw this error, which is effectively what esbuild is doing here:

```
Uncaught ReferenceError: can't access lexical declaration 'DocumentSearchOptions' before initialization
```

So it looks like what esbuild is doing here is correct for standard JavaScript decorators. Perhaps esbuild's parser needs to mess with scope only when parsing legacy TypeScript decorators to allow them to access the class object before it has been declared.

**Comment by evanw** [comment]
This is confusing. I'm trying to figure out whether the evaluation of decorators is supposed to happen inside or outside the class body. It seems like the answer is "it depends on the code being compiled" and I'm not sure what is a bug and what is intended behavior.

You are allowed to [call `await` inside a decorator](https://www.typescriptlang.org/play?experimentalDecorators=true&target=99#code/IYZwngdgxgBAZgV2gFwJYHsL3egFAShgG8AoGGKTEdAGwFMA6G9Ac1wHIAjOudAJzrt8ZCjVAgYAMRzER5AAK5gAd2CpkMCHWUwACn3QBbVCDoAefegAOdPsjAAROpT7Bk-AHy4+MALweYU2QAFVRDOnQEZFwCPwC+GMJ-YgBffAAaGABGAAY8-AK5QOQ3VFhedD8Ydgr2ERSRSghqeiZWDmA4ZFshEgaKghIgA) if the class is declared in an `async` context, which implies that decorators are evaluated _outside_ the class body:

```ts
async function foo() {
  console.log('before')
  class Foo {
    @(await new Promise<PropertyDecorator>(r => setTimeout(() => r(() => {}), 1000)))
    static foo = 'foo'
  }
  console.log('after')
}
foo()
```

You are also allowed to [use a private name inside a decorator](https://www.typescriptlang.org/play?experimentalDecorators=true&target=99#code/MYGwhgzhAEBiD29oG8BQ1oQC5iwS2GgGIAjMAJ2gF5oByUi29aAAQAoOBKagPhWmDwAdhHggApgDoQ8AOZsE8SQ3LcAvt0jQACuXgAHceSwBPACLjB5XPFXNsuAtABmianVfwma1EA), which implies that decorators are evaluated _inside_ the class body:

```ts
class Foo {
  static #bar = '#bar'
  @((() => { console.log(Foo.#bar) }) as PropertyDecorator)
  static foo = 'foo'
}
```

The use of private names appears to have been broken until TypeScript 4.8+ since TypeScript 4.7 and earlier generate nonsense code that references private names outside of the class body. Then TypeScript 4.8+ moved decorator evaluation into the class body, which makes this work.

But [attempting to do both of these things](https://www.typescriptlang.org/play?experimentalDecorators=true&target=99#code/IYZwngdgxgBAZgV2gFwJYHsL3egFAShgG8AoGGKTEdAGwFMA6G9Ac1wHIAjOudAJzrt8ZCjVAgYAMRzER5EMmBpYAYk7A+MALwx2ajezkwAArjOEtAPmIUqtRszbT0DfX0IBfQqBgAFPugADnR8yGAAInSUfEr8wuTkpsAA7sCoyDAQdMl+AQC2qCB0ADz+QSFhkdGxfJa4mlYwRcgAKqh5dOgIyOba1ny9jUReADQwAIwADNP4s0YKSqiwvOjauiuG5B4ilBDU9EysHMBwyCFCJNsrBCRAA) causes TypeScript to generate nonsense code even with the latest release, because of course `await` is not allowed in a class body:

```ts
async function foo() {
  console.log('before')
  class Foo {
    static #bar = '#bar'
    @((() => { console.log(Foo.#bar) }) as PropertyDecorator)
    @(await new Promise<PropertyDecorator>(r => setTimeout(() => r(() => {}), 1000)))
    static foo = 'foo'
  }
  console.log('after')
}
foo()
```

It seems like TypeScript wants decorators to be evaluated both _inside_ and _outside_ the class body. So I guess TypeScript decorators don't really have well-defined semantics? Or at least I can't figure them out.

**Comment by evanw** [comment]
This PR is relevant: https://github.com/microsoft/TypeScript/pull/50074. It introduced the behavior of sometimes putting decorator evaluation inside a static block in the class body. TypeScript's condition for doing this is currently whenever a class member has either a decorator or a parameter decorator that contains an private name (even if the private name is unrelated to the class with the decorator).
