### ISSUE TITLE
how to modify the module names imported in “import” or “require”

### ISSUE THREAD

**Issue by lidenggao** [evanw/esbuild#3232]
#3228
I want to modify the module names imported in “import” or “require” statements through plugins, but I couldn't find a way to do it. Can support for modifying imported module names be added in onResolve?

I'm afraid I didn't explain it clearly earlier. The path doesn't actually contain any usable information, as I failed to point out originally. Please allow me to update the example as follows:

```
import vue, { inject, ref, reactive } from "vue";
import moment from 'moment'
```
Modify to:
```
import vue_default as vue, { vue_inject as inject, vue_ref as ref, vue_reactive as reactive } from "vendor";
import { moment_default as moment } from 'vendor'
```

**Comment by lidenggao** [comment]
The interface provided is already quite good, but it still doesn't fully meet my needs - specifically getting and modifying this snippet in the example.
```
vue, { inject, ref, reactive }
```

**Comment by hyrious** [comment]
Where do the name `vue_inject`, `vue_ref` come from? Are they exported by hand or by another script?

**Comment by lidenggao** [comment]
> Where do the name `vue_inject`, `vue_ref` come from? Are they exported by hand or by another script?

I plan to merge dependencies into vendor. When merging, I will use the full path hash as the prefix, then concatenate the exported name of the module to form the new name.

**Comment by evanw** [comment]
There is no plugin API for accessing the AST. See https://esbuild.github.io/plugins/#plugin-api-limitations. 

Depending on what you're doing you could potentially still do something like this without access to the AST if you are just trying to bundle up some libraries into a `vendor` thing. When bundling `vendor` if it's possible to analyze the exports of the libraries you are bundling, then you could bundle `vendor` using an entry point like this:

```js
export { default as vue_default, ref as vue_ref, ... } from 'vue'
export { default as moment_default } from 'moment'
```

and then have your plugin replace `vue` with something like this:

```js
export { vue_default as default, vue_ref as ref, ... } from 'vendor'
```

and replace `moment` with something like this:

```js
export { moment_default as default } from 'vendor'
```

The list of exports would be the list of all possible exports from those libraries instead of only the used ones. That could be obtained at bundle-time using esbuild's [`metafile`](https://esbuild.github.io/api/#metafile) for example. Then that same list could be passed to the plugin somehow so it could know what replacement file to generate to import the correct thing from `vendor`. Just an idea.

**Comment by lidenggao** [comment]
Thank you so much for bringing us such an excellent tool. Just like you mentioned about IDEA, I do have some approaches to achieve this now, such as:
1. Complete the replacement before using ESBUILD, but this approach will affect third-party plugins reading files, so I need to modify the third-party plugins used. 
2. Replace the result in onEnd, this should be a relatively reliable approach, but I need to pay attention to the impact of file compression on the replacement logic. 

I was just hoping it would be better to provide name replacement in onResolve, like other string replacement APIs. But if it's not suitable to open the API here, then I will continue with the current approach and close this issue. Thank you.
