### ISSUE TITLE
Is watch mode really incremental?

### ISSUE THREAD

**Issue by mdorda** [evanw/esbuild#3233]
Sorry if I missed anything, but I was not able to find any issue or readme regarding my problem.

We use esbuild to bundle approximately 100 entryFiles. They have like 30 common chunks, but otherwise they are completely independent. When watch mode is turned on, changing any file - or even calling `rebuild` without changing anything - causes complete rebuild of all entry files. According to documentation, I thought watch mode should be incremental.

To be more specific, here is our setup.

Build options:
```typescript
const buildOptions: esbuild.BuildOptions = {
        entryPoints: entryFiles,
        bundle: true,
        format: 'esm',
        target: 'es6',
        platform: 'browser',
        treeShaking: true,
        minify: false,
        splitting: true,
        outdir: path.join(isProductionBuild ? cfg.destProd : cfg.destDev, 'plugins'),
        chunkNames: 'chunks/[name]-[hash]',
        entryNames: '[name]',
        write: false,
        plugins: [
            glsl({ minify: isProductionBuild }),
            capacitorPlugin(),
            preprocessPlugin(),
            sveltePlugin(prog, cfg),
            polyfillCoreImportsPlugin(),
        ],
};
```

Then it is used like:
```typescript
const context = await esbuild.context(buildOptions);
await context.watch();
```

When a single file is changed, without any import and used just and only in one of all entry points (yes, I am sure, I checked metafile as well), it triggers rebuild correctly, but it rebuilds all entry points.

Same for calling rebuild manually without changing anything:
```typescript
const context = await esbuild.context(buildOptions);
setInterval(() => {
    context.rebuild();
}, 10000);
```
It rebuilds everything over and over again, even if nothing is changed in source files meanwhile.

Is that correct? Or am I doing anything wrong? Thank you!

**Comment by evanw** [comment]
Yes, watch mode should be incremental. However it's probably not incremental in the way that you had hoped. The build is still done over again from scratch except that some internal work that esbuild does to parse ASTs should be skipped if the file contents haven't changed (since the ASTs from the previous build are already in memory). 

It's not generally safe to cache the output of plugins as they could depend on arbitrary external sources of data, so the build is done over again each time for correctness. This is documented here: https://esbuild.github.io/api/#rebuild. 

If you have a plugin that's doing some expensive work that shouldn't be re-done every build, then that plugin will have to be altered to cache that work in between builds. How the cache should work depends on how the plugin works. Some thoughts about how to do that are here: https://esbuild.github.io/plugins/#caching-your-plugin.

**Comment by mdorda** [comment]
I see. Thanks for the explanation. The slowest part is obviously Svelte. All entrypoints are built in 2s, but `sveltePlugin` took 12s. And 14s + 1s of polling file changes is pretty much on "hot reload" :-)

But https://esbuild.github.io/plugins/#caching-your-plugin is exactly what I am looking for. I apologize for the blindness. and thank you for all the great work!
