### ISSUE TITLE
Should be able to configure esbuild to source `react-native` entrypoints from dependencies' package.json when `"exports"` section is present

### ISSUE THREAD

**Issue by steveluscher** [evanw/esbuild#3261]
Imagine you're bundling a project. That project has dependencies.

```ts
import { usefulFunction } from '@my/dependency';
```

That dependency has a package.json that specifies a bunch of entrypoints. In particular, it uses the `"exports"` field:

```json
{
  "name": "@my/dependency",
  "exports": {
    "browser": "./dist/index.browser.js",
    "react-native": "./dist/index.react-native.js"
  },
  "main": "./dist/index.js",
  "browser": "./dist/index.browser.js",
  "react-native": "./dist/index.react-native.js"
}
```

When you configure esbuild with:

1. `platform=browser` it will bundle `./dist/index.browser.js` from `@my/dependency`;
2. `platform=node` it will bundle `./dist/index.js` from `@my/dependency`;

Setting `mainFields` to `["react-native"]` does not work unless you _delete_ the `"exports"` section.

[Repro link](https://esbuild.github.io/try/#YgAwLjE3LjQALS1idW5kbGUgLS1tYWluLWZpZWxkcz1yZWFjdC1uYXRpdmUAZQBlbnRyeS5qcwBpbXBvcnQgeyB1c2VmdWxGdW5jdGlvbiB9IGZyb20gJ0BteS9kZXBlbmRlbmN5JzsKdXNlZnVsRnVuY3Rpb24oKTsAAG5vZGVfbW9kdWxlcy9AbXkvZGVwZW5kZW5jeS9wYWNrYWdlLmpzb24AewogICJuYW1lIjogIkBteS9kZXBlbmRlbmN5IiwKICAiZXhwb3J0cyI6IHsKICAgICJicm93c2VyIjogIi4vZGlzdC9pbmRleC5icm93c2VyLmpzIiwKICAgICJyZWFjdC1uYXRpdmUiOiAiLi9kaXN0L2luZGV4LnJlYWN0LW5hdGl2ZS5qcyIKICB9LAogICJtYWluIjogIi4vZGlzdC9pbmRleC5qcyIsCiAgImJyb3dzZXIiOiAiLi9kaXN0L2luZGV4LmJyb3dzZXIuanMiLAogICJyZWFjdC1uYXRpdmUiOiAiLi9kaXN0L2luZGV4LnJlYWN0LW5hdGl2ZS5qcyIKfQAAbm9kZV9tb2R1bGVzL0BteS9kZXBlbmRlbmN5L2Rpc3QvaW5kZXguYnJvd3Nlci5qcwBleHBvcnQgZnVuY3Rpb24gdXNlZnVsRnVuY3Rpb24oKSB7CiAgY29uc29sZS5sb2coJ0hlbGxvIGJyb3dzZXInKTsKfQAAbm9kZV9tb2R1bGVzL0BteS9kZXBlbmRlbmN5L2Rpc3QvaW5kZXgucmVhY3QtbmF0aXZlLmpzAGV4cG9ydCBmdW5jdGlvbiB1c2VmdWxGdW5jdGlvbigpIHsKICBjb25zb2xlLmxvZygnSGVsbG8gUmVhY3QgTmF0aXZlJyk7Cn0)

**Comment by evanw** [comment]
It seems to work fine with `mainFields`: [link](https://esbuild.github.io/try/#YgAwLjE4LjE1AC0tYnVuZGxlIC0tbWFpbi1maWVsZHM9cmVhY3QtbmF0aXZlAGUAZW50cnkuanMAaW1wb3J0IHsgdXNlZnVsRnVuY3Rpb24gfSBmcm9tICdAbXkvZGVwZW5kZW5jeSc7CnVzZWZ1bEZ1bmN0aW9uKCk7AABub2RlX21vZHVsZXMvQG15L2RlcGVuZGVuY3kvcGFja2FnZS5qc29uAHsKICAibmFtZSI6ICJAbXkvZGVwZW5kZW5jeSIsCiAgIm1haW4iOiAiLi9kaXN0L2luZGV4LmpzIiwKICAiYnJvd3NlciI6ICIuL2Rpc3QvaW5kZXguYnJvd3Nlci5qcyIsCiAgInJlYWN0LW5hdGl2ZSI6ICIuL2Rpc3QvaW5kZXgucmVhY3QtbmF0aXZlLmpzIgp9AABub2RlX21vZHVsZXMvQG15L2RlcGVuZGVuY3kvZGlzdC9pbmRleC5yZWFjdC1uYXRpdmUuanMAZXhwb3J0IGZ1bmN0aW9uIHVzZWZ1bEZ1bmN0aW9uKCkgewp9). Making this as `unactionable` as you did not provide a way to reproduce the issue.

**Comment by steveluscher** [comment]
Oh wow. My esbuild REPL-fu was nowhere near as good as yours. I tried but didn't know you could do what you did.

I've attached a repro now. It's the `"exports"` field that's the problem.

**Comment by evanw** [comment]
You can use [`--conditions=react-native --platform=neutral`](https://esbuild.github.io/try/#YgAwLjE3LjQALS1idW5kbGUgLS1jb25kaXRpb25zPXJlYWN0LW5hdGl2ZSAtLXBsYXRmb3JtPW5ldXRyYWwAZQBlbnRyeS5qcwBpbXBvcnQgeyB1c2VmdWxGdW5jdGlvbiB9IGZyb20gJ0BteS9kZXBlbmRlbmN5JzsKdXNlZnVsRnVuY3Rpb24oKTsAAG5vZGVfbW9kdWxlcy9AbXkvZGVwZW5kZW5jeS9wYWNrYWdlLmpzb24AewogICJuYW1lIjogIkBteS9kZXBlbmRlbmN5IiwKICAiZXhwb3J0cyI6IHsKICAgICJicm93c2VyIjogIi4vZGlzdC9pbmRleC5icm93c2VyLmpzIiwKICAgICJyZWFjdC1uYXRpdmUiOiAiLi9kaXN0L2luZGV4LnJlYWN0LW5hdGl2ZS5qcyIKICB9LAogICJtYWluIjogIi4vZGlzdC9pbmRleC5qcyIsCiAgImJyb3dzZXIiOiAiLi9kaXN0L2luZGV4LmJyb3dzZXIuanMiLAogICJyZWFjdC1uYXRpdmUiOiAiLi9kaXN0L2luZGV4LnJlYWN0LW5hdGl2ZS5qcyIKfQAAbm9kZV9tb2R1bGVzL0BteS9kZXBlbmRlbmN5L2Rpc3QvaW5kZXguYnJvd3Nlci5qcwBleHBvcnQgZnVuY3Rpb24gdXNlZnVsRnVuY3Rpb24oKSB7CiAgY29uc29sZS5sb2coJ0hlbGxvIGJyb3dzZXInKTsKfQAAbm9kZV9tb2R1bGVzL0BteS9kZXBlbmRlbmN5L2Rpc3QvaW5kZXgucmVhY3QtbmF0aXZlLmpzAGV4cG9ydCBmdW5jdGlvbiB1c2VmdWxGdW5jdGlvbigpIHsKICBjb25zb2xlLmxvZygnSGVsbG8gUmVhY3QgTmF0aXZlJyk7Cn0) for this. The `--platform=neutral` turns off browser-specific behavior (because `platform` defaults to `browser`) and the `--conditions=react-native` selects the `react-native` entry in `exports` (`mainFields` doesn't apply when `exports` is present).

**Comment by steveluscher** [comment]
Oh, awesome. Thanks for the esbuild tech support; I would have never, ever, figured out that combination on my own.
