### ISSUE TITLE
Support parsed JSON for CommonOptions.define

### ISSUE THREAD

**Issue by dr-vortex** [evanw/esbuild#3263]
Currently, `define` only supports JSON values as strings. It would be nice to be able to pass in objects without `JSON.stringify`.

Currently:
```ts
const esbuildConfig = {
    // ...
    define: {
        $example: '{ "this_is": "a string" }'
    }
}
```
or
```ts
const esbuildConfig = {
    // ...
    define: {
        $example: JSON.stringify({
            this_is: 'an object'
        })
    }
}
```

With support:
```ts
const esbuildConfig = {
    // ...
    define: {
        $example: {
            this_is: 'an object'
        }
    }
}
```

**Comment by evanw** [comment]
Thank you for the suggestion but I am not going to do this. You should be using either one of the first two approaches you posted. The `define` field deliberately maps definitions to strings of code. I previously had implicit conversions to strings as you are suggesting, but people found it really confusing because it implied that passing a string was a way to get a string literal instead of an identifier. IMO it's less confusing if you always have to pass a string of code without any exceptions, which is why I changed it away from what you are suggesting. I'm closing this issue as I won't be taking this suggestion.

**Comment by dr-vortex** [comment]
That does make sense.
