### ISSUE TITLE
[bundle] use-before-define error when using re-exports

### ISSUE THREAD

**Issue by lukeed** [evanw/esbuild#3270]
Likely to do with the circular reference, but when an index-like file exports re-named helpers from its siblings, anything the siblings referenced from the index/parent is out of order. In this case, everything within a module is to share the same rate limiter. So all siblings import the `rlimit` singleton & the main entry re-exports the throttled helpers. Error only occurs when the outside consumer references the re-exports.

[REPL](https://esbuild.github.io/try/#YgAwLjE4LjE2AHsKICBidW5kbGU6IHRydWUsCiAgZm9ybWF0OiAnZXNtJywKICBleHRlcm5hbDogWwogICAgJ3AtdGhyb3R0bGUnCiAgXQp9AGUAZW50cnkudHMAaW1wb3J0ICogYXMgbGliIGZyb20gJy4vbGliJwoKYXdhaXQgbGliLml0ZW0oMTIzKQAAbGliL2luZGV4LnRzAGltcG9ydCB0aHJvdHRsZSBmcm9tICdwLXRocm90dGxlJzsKCmV4cG9ydCBjb25zdCBybGltaXQgPSB0aHJvdHRsZSh7CiAgLy8gLi4uCn0pOwoKZXhwb3J0IHsgZGV0YWlscyBhcyBpdGVtIH0gZnJvbSAnLi9pdGVtJzsKAABsaWIvaXRlbS50cwBpbXBvcnQgeyBybGltaXQgfSBmcm9tICcuL2luZGV4JzsKCmV4cG9ydCBjb25zdCBkZXRhaWxzID0gcmxpbWl0KGFzeW5jIGZ1bmN0aW9uIChpZDogc3RyaW5nKSB7CiAgLy8gLi4uCn0pOwo)

**Comment by evanw** [comment]
I'm confused. This is happening because that's how JavaScript works. Here's the same thing without esbuild involved at all:

* `entry.mjs`

    ```js
    import * as lib from './lib/index.mjs'

    await lib.item(123)
    ```

* `lib/index.mjs`

    ```js
    import throttle from 'p-throttle';

    export const rlimit = throttle({
      // ...
    });

    export { details as item } from './item.mjs';
    ```

* `lib/item.mjs`

    ```js
    import { rlimit } from './index.mjs';

    export const details = rlimit(async function (id) {
      // ...
    });
    ```

* `node_modules/p-throttle/index.js`

    ```js
    module.exports = x => x
    ```

Running `node entry.mjs` gives you this:

```
file://./lib/item.mjs:3
export const details = rlimit(async function (id) {
                       ^

ReferenceError: Cannot access 'rlimit' before initialization
    at file://./lib/item.mjs:3:24
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.16.1
```

So esbuild seems to be doing what it's supposed to do?

Can you explain in more detail why you think esbuild should be behaving differently? The JavaScript specification is here: https://tc39.es/ecma262/. If esbuild's bundler deviates from the specification somewhere, then maybe you can point out where?

**Comment by lukeed** [comment]
Ah, ok sorry. I expected esbuild (or any bundler) to shuffle this for me thru insights. I thought I used this pattern in the past with Rollup, but I verified that they also do the same thing you (and native imports) do.
