### ISSUE TITLE
When using yarn --modules-folder some_nonstandard_modules_folder, esbuild cannot be found

### ISSUE THREAD

**Issue by doctorpangloss** [evanw/esbuild#3273]
Reproduction:
 1. Use `yarn` 1.22.
 2. Run `yarn install --modules-folder some_nonstandard_npm_modules` on a project which contains `esbuild`. You can use my `package.json` from https://github.com/hiddenswitch/Spellsource/blob/typescript/spellsource-web/package.json.
 3. Observe `esbuild` errors.
 4. Remove `--modules-folder`
 5. Observe no `esbuild` errors.
 6. Observe running again with `--modules-folder` succeeds, because `esbuild` finds what it needs in `node_modules/`.
 7. Delete `node_modules` and run again with `--modules-folder`
 8. Observe everything succeeds.

Critically, this machine has never had `esbuild` installed on it using the provided node toolchain in the "right place."

**Comment by evanw** [comment]
TIL about `yarn --modules-folder`. I'm not going to install all of those packages to reproduce this. Here's what I tried:

1. Use `yarn` 1.22.
2. Run `yarn init -y`
3. Run `yarn add esbuild --ignore-scripts --modules-folder some_nonstandard_npm_modules`
4. Run `yarn --modules-folder some_nonstandard_npm_modules run esbuild --version`

That seems to reproduce the problem in that this crashes with `Error: Cannot find module 'esbuild'`. But the problem seems to be that esbuild is running `require.resolve('esbuild')` from within its own package and that is crashing. This seems like a Yarn problem, not an esbuild problem. Maybe the problem is that [`yarn run` doesn't support `--modules-folder`](https://github.com/yarnpkg/yarn/issues/8957)? I'm very unfamiliar with Yarn (I don't use it at all myself) but FWIW you can get it to work by avoiding Yarn and using node's deprecated `NODE_PATH` setting like this:

```
NODE_PATH=./some_nonstandard_npm_modules node ./some_nonstandard_npm_modules/.bin/esbuild --version
```

I'm going to say that this isn't something esbuild should attempt to fix. It looks like Yarn's `--modules-folder` isn't correctly shimming `require.resolve`, and I believe it's reasonable for esbuild to expect `require.resolve` to work under Yarn as it works under node. If you want to use esbuild with Yarn you can either a) not use `--modules-folder` or b) possibly use `NODE_PATH` hacks or c) get Yarn to fix this issue.

**Comment by doctorpangloss** [comment]
Thanks for investigating this and telling me about `NODE_PATH`. I am trying to run something under GraalVM which is why this is complex.
