### ISSUE TITLE
Plugin `onResolve` is not called when bundling is disabled

### ISSUE THREAD

**Issue by Akalanka47000** [evanw/esbuild#3277]
Hi, I'm not sure if this is an issue or a misunderstanding on my part, though I've tried for quite a while to find a solution both from the docs and external sources. I'm trying to configure path aliases for my imports. Example imports with aliases are as follows:-

```js
import connectDB  from '@/database';
import { errorHandler, queryMapper, responseInterceptor } from '@/middleware';
```

I've tried using a couple of plugins for managing path aliases which are already out there but nothing seemed to happen so I tried writing a plugin of my own to see if I could get something done however I seemed to notice that the callback inside `onResolve` is never called. The regex inside filter works as I tried matching it by hand. This seemed to be fixed as soon as I set the `bundle` option to `true` in the config. I couldn't find any mention in the docs as to whether this is the expected behavior once bundling is disabled. I'm guessing this could be the issue as to why the other plugins didn't work as well. 

I'm trying to get this done without bundling the code, please let me know if there is an alternative to get around this if someone finds the time. I've included both a simplified version of the build script with the options being used as well as the complete script if it is helpful by any chance. The issue's present in both.

## SImplified

```js
const path = require('path');

const alias = {
  name: 'alias',
  setup(build) {
    build.onResolve({ filter: /^@\/.*/ }, args => {
      console.log('Entered onResolve');
      return {
        path: path.resolve(__dirname, './src', args.path.replace(/^@\//, '')),
      }
    })
  },
}

require('esbuild')
  .build({
    entryPoints: [`./src/app.js`],
    bundle: false,
    outdir: './dist',
    format: 'cjs',
    plugins: [
      alias,
    ],
  })
  .catch(() => process.exit(1));
```

## Full Script

```js
const path = require('path');
const execSync = require('child_process').execSync;
const { globPlugin } = require('esbuild-plugin-glob');

execSync('npx rimraf ./dist && mkdir dist');

const copy = ['json', 'html', 'png']

const alias = {
  name: 'alias',
  setup(build) {
    build.onResolve({ filter: /^@\/.*/ }, args => {
      console.log('Entered onResolve');
      return {
        path: path.resolve(__dirname, './src', args.path.replace(/^@\//, '')),
      }
    })
  },
}

require('esbuild')
  .build({
    entryPoints: [`./src/**/*.{js,${copy.join(',')}}`],
    bundle: false,
    outdir: './dist',
    outbase: './src',
    platform: 'node',
    target: 'node16.0',
    format: 'cjs',
    minify: false,
    sourcemap: true,
    keepNames: true,
    loader: copy.reduce((acc, ext) => ({ ...acc, [`.${ext}`]: 'copy' }), {}),
    plugins: [
      alias,
      globPlugin(),
    ],
  })
  .catch(() => process.exit(1));
```

**Comment by hyrious** [comment]
I guess you want to achieve [unbundled](https://github.com/evanw/esbuild/issues/708) behavior like rollup's <samp>preserveModules</samp>. As you can see through the link this is not supported now.

When you set `bundle: false` in esbuild, it means to transform each file _individually_, which may produce some results you don't want. It is meaningless to let plugin's handle `resolve` and `load` processes because there's none.

One way to make something similar to happen is enabling the [splitting](https://esbuild.github.io/api/#splitting) option, which means do bundle everything but try to split out files as configured in `entryPoints`. This is still not "unbundled", see [this example](https://esbuild.github.io/try/#YgAwLjE4LjE3AC0tYnVuZGxlIC0tc3BsaXR0aW5nIC0tZm9ybWF0PWVzbSAtLW91dGRpcj0vAGUAZm9vLmpzAGltcG9ydCB7YmFyfSBmcm9tICcuL2JhcicKCmV4cG9ydCB2YXIgZm9vID0gMQoKZXhwb3J0IHtiYXJ9AGUAYmFyLmpzAGltcG9ydCB7Zm9vfSBmcm9tICcuL2ZvbycKCmV4cG9ydCB2YXIgYmFyID0gMgoKZXhwb3J0IHtmb299) in playground.

Currently only 2 bundlers supports the unbundled behavior, both of them have some drawbacks: one is rollup, another is [mkdist](https://github.com/unjs/mkdist). Use with caution.

Nowadays some library authors do not want bundling nor helper functions (like tslib) when providing their libraries, for example, Svelte. They choose to write plain JavaScript files with jsdoc comments and d.ts files manually.

**Comment by Akalanka47000** [comment]
Thanks for the clarification, I'll go ahead and close this issue
