### ISSUE TITLE
require call is used to load an ES module file,require().default

### ISSUE THREAD

**Issue by where-picturesque** [evanw/esbuild#3282]
how to use require,not require.default;
like babel with plugin `babel-plugin-add-module-exports`

environment: node
```
//main.js
const tools = require('./tools-esm.js')
console.log(tools)
console.log(tools.default)
//-------out---------
{ default: [Getter] }
{ fn1:()=>{},count:1 }

//tools-esm.js
const MyTools= {
  fn1:()=>{},
  count:1
}

export default MyTools
```

**Comment by evanw** [comment]
This is deliberately how esbuild's ESM import works. If `require()` returned the `default` export then there would be no way to access other exports. This is why `require()` returns an object with a property called `default`. If you want `require()` to return the object `MyTools` then you can do `module.exports = MyTools` (i.e. use CommonJS instead of ESM).

**Comment by evanw** [comment]
I’m closing this issue because esbuild’s behavior here is deliberate, as described above.

**Comment by where-picturesque** [comment]
thanks @evanw 

I have some old code using `require(esm)` compiled in webpack with babel@7, and  using babel's plugin `babel-plugin-add-module-exports` solved this problem ;
Migrating to esbuild, I am looking for similar plugins or other methods to solve this problem quickly.

Not found yet, maybe I'll just modify hundreds of files then use `import`
