### ISSUE TITLE
Plans for WASI Support?

### ISSUE THREAD

**Issue by william-stacken** [evanw/esbuild#3300]
Since go version 1.21.0, there is support to target WASI using `GOOS=wasip1`. I tried in `scripts/esbuild.js` to change GOOS in the buildWasmTarget function from `js` to `wasip1`, followed by a `make platform-wasm`. It worked and esbuild ran in wasmtime just fine.

Are there any plans to, for example, extend the `esbuild-wasm` package to include a esbuild WASI binary in addition to the JS one?

**Comment by evanw** [comment]
I don't have any plans at the moment (it was just released!). It's good to hear that it works. I think it makes sense to use a separate package for this so that people don't have to download both. However, adding this isn't super straightforward because Go 1.21.0 also dropped support for quite a few platforms, which I'm not keen on dropping for esbuild. So I'll probably stick to Go 1.20.x for at least a while.

**Comment by d3lm** [comment]
Go now has [official WASI support](https://go.dev/blog/wasi) and I wanted to ask if there are plans to look into WASI for esbuild now?

**Comment by d3lm** [comment]
Thanks a ton @evanw for implementing this!
