### ISSUE TITLE
Build fails for types in @types library

### ISSUE THREAD

**Issue by ffMathy** [evanw/esbuild#3312]
I am getting the following errors:

```
 >  NX   Build failed with 9 errors:

   node_modules/.pnpm/@types+uuid@9.0.2/node_modules/@types/uuid/index.d.ts:77:13: ERROR: The constant "NIL" must be initialized
   node_modules/.pnpm/@types+uuid@9.0.2/node_modules/@types/uuid/index.d.ts:78:13: ERROR: The constant "parse" must be initialized
   node_modules/.pnpm/@types+uuid@9.0.2/node_modules/@types/uuid/index.d.ts:79:13: ERROR: The constant "stringify" must be initialized
   node_modules/.pnpm/@types+uuid@9.0.2/node_modules/@types/uuid/index.d.ts:80:13: ERROR: The constant "v1" must be initialized
   node_modules/.pnpm/@types+uuid@9.0.2/node_modules/@types/uuid/index.d.ts:81:13: ERROR: The constant "v3" must be initialized
```

But these files are not mine. They are installed via PNPM and represent typings.

**Comment by hyrious** [comment]
The error seems not come from esbuild. Could you provide a more detailed reproduction?

**Comment by ffMathy** [comment]
Alright. Where do you think it is coming from? Pnpm? Nx?

I can't make a detailed repro because the code is under NDA.

**Comment by callmeberzerker** [comment]
> Alright. Where do you think it is coming from? Pnpm? Nx?
> 
> I can't make a detailed repro because the code is under NDA. 

You can create a repro. Start a new NX project, add the same library and their corresponding @types and see if it works. 

Your attitude needs a bug report as well.

**Comment by evanw** [comment]
This is due to a configuration error. You are never supposed to end up in a situation where you are bundling a `.d.ts` file since that doesn't make sense. So the problem is whatever is causing esbuild to attempt to traverse into a `.d.ts` file in the first place.

**Comment by ffMathy** [comment]
Wow, I am sorry if my attitude seemed off? Maybe it's unclear through text. That was not my intention.

I'm an open source maintainer myself, and I love NX.

The repro would take too much time to make because there is an insane amount of configuration that could be the cause, and I am not sure that would be justified to spend company time on.

That's why I wanted help to get in the right direction, or to help searching for the right things in the right areas.

**Comment by ffMathy** [comment]
I switched to SWC now and that seems to have worked.

TSC itself also works, but is very slow. Closed the issue to avoid wasting more of your previous time.

**Comment by evanw** [comment]
Hey, really sorry about @callmeberzerker's comment. I'm not sure who they are or why they commented on this issue. That was unnecessary and unfortunate.

Anyway I totally understand about not being able to provide a repro. I'm happy to try to help point you in the right direction if you're still interested in pursuing this.

I can also attempt to make esbuild not generate an error in this particular edge case. Even though importing a `.d.ts` file is a configuration error, I have done some work in the past to help make esbuild try to able to parse `.d.ts` syntax anyway. Typically these files should parse to an empty file because they only contain type declarations. Although allowing this file to parse may not fix your problem here because whatever is importing this file may not be expecting to import an empty file. Your code probably expects to be importing another file instead.

**Comment by ffMathy** [comment]
Thank you for that. That comment actually made me a bit sad.

I think I'll give it another shot tomorrow based on the info you've provided.

I wanted to become a sponsor on GitHub Sponsors as a thanks, but couldn't find your sponsor page. Can you send a link to it? Perhaps it's because I'm using the GitHub mobile app.
