### ISSUE TITLE
Decorator as static class member fails with runtime error

### ISSUE THREAD

**Issue by danielrentz** [evanw/esbuild#3326]
After upgrading Vite from 4.3.9 (esbuild 0.17.19) to Vite 4.4.9 (esbuild 0.18.20), decorators that are static class members stop working when the decorated static method instantiates the class.

In this case, the class will be created as temporary variable (e.g. `_Test`), and will be decorated using the original class name (`Test`) before that variable will be defined (`let Test = _Test`). 

Original test code (`Test1` works as expected, `Test2` fails with esbuild 0.18):
```ts
export class Test1 {
    static deco(): void { }
    @Test1.deco static test(): void { }
}
export class Test2 {
    static deco(): void { }
    @Test2.deco static test(): Test2 { return new Test2(); }
}
```

esbuild 0.17.19
```js
export class Test1 {
    static deco() {}
    static test() {}
}
__decorateClass([Test1.deco], Test1, "test", 1);
const _Test2 = class {
    static deco() {}
    static test() {
        return new _Test2();
    }
}
;
export let Test2 = _Test2;
__decorateClass([Test2.deco], Test2, "test", 1); // <============ works
```

esbuild 0.18.20
```js
export class Test1 {
    static deco() {}
    static test() {}
}
__decorateClass([Test1.deco], Test1, "test", 1);
const _Test2 = class _Test2 {
    static deco() {}
    static test() {
        return new _Test2();
    }
}
;
__decorateClass([Test2.deco], _Test2, "test", 1); // <============= uses "Test2" instead of "_Test2"
export let Test2 = _Test2;
```

Importing the module immediately fails with
```
ReferenceError: Cannot access 'Test2' before initialization
```

**Comment by dlmartens** [comment]
I am having this issue as well. It looks like it occurs in any class with static members (which cause an underscore prefix rename on the class). It seems the problem is just that the renamed class is not used in the call to `__decorateClass`.

[Here is a basic example.](https://esbuild.github.io/try/#dAAwLjE5LjIAewogIGxvYWRlcjogJ3RzJywKICB0c2NvbmZpZ1JhdzogewogICAgY29tcGlsZXJPcHRpb25zOiB7CiAgICAgIGV4cGVyaW1lbnRhbERlY29yYXRvcnM6IHRydWUsCiAgICB9LAogIH0sCn0AZXhwb3J0IGNsYXNzIEZvbyB7CiAgc3RhdGljIG1lc3NhZ2UgPSAnSGVsbG8gd29ybGQhJzsKICBzdGF0aWMgbXNnTGVuZ3RoID0gRm9vLm1lc3NhZ2UubGVuZ3RoOwoKICBARm9vLmV4YW1wbGUoKQogIGZvbygpIHt9CgogIHN0YXRpYyBleGFtcGxlKCkgewogICByZXR1cm4gZnVuY3Rpb24gKAogICAgICB0YXJnZXQ6IHVua25vd24sCiAgICAgIHByb3BlcnR5S2V5OiBzdHJpbmcsCiAgICAgIGRlc2NyaXB0b3I6IFByb3BlcnR5RGVzY3JpcHRvciwKICAgICkge307CiAgfQp9)

**Comment by viceice** [comment]
Seeing same error while trying to transition from jest (ts-jest) to vitest. For us esbuild v0.17 and v0.19 are failing too. 😕
