### ISSUE TITLE
Allowing other platforms to communicate with esbuild (Like nodejs does)

### ISSUE THREAD

**Issue by ia3andy** [evanw/esbuild#3327]
Hello @evanw,

I am one of the maintainers of the new https://github.com/mvnpm/esbuild-java, which is key to the https://github.com/quarkiverse/quarkus-web-bundler.

Currently we are using the esbuild CLI binary under the hood, it is already very fast and reliable, but:
- For scss, we have to do a very brittle pre-processing using a java scss compiler
- We can't use any esbuild plugins
- we can't use the Rebuild command which would be nice for our dev mode

This is why I am looking at ways we could do something similar as the NodeJs implementation to communicate, so I had a look at the sources to find out how the communication is done from the nodejs to the process through IPC (and also found this issue https://github.com/evanw/esbuild/issues/306).

What's your opinion on this? is this something you considered (allowing to communicate with the process from external clients/platforms)? is there plan to document the communication protocol?

**Comment by ia3andy** [comment]
@evanw any udpate on this?

**Comment by evanw** [comment]
You are welcome to build on esbuild's internal implementation details to make something like this work. The protocol is pretty simple (see [this](https://github.com/evanw/esbuild/blob/c8d1c4ea7db68e7a07392e7139cc91bebf267854/lib/shared/stdio_protocol.ts#L248-L347) and [this](https://github.com/evanw/esbuild/blob/c8d1c4ea7db68e7a07392e7139cc91bebf267854/cmd/esbuild/stdio_protocol.go#L36-L205)) and hasn't changed for quite some time. Just keep in mind that it's an internal implementation detail of esbuild and could hypothetically be changed at some point in the future. In any case, I'm closing this issue because I consider this to be an internal implementation detail of esbuild, and not a public API to be documented.
