### ISSUE TITLE
Name clash with `top` when bundling a PureScript application

### ISSUE THREAD

**Issue by Soupstraw** [evanw/esbuild#3340]
After building and bundling [my PureScript project](https://github.com/Soupstraw/orders-of-magnitude/tree/5f8841ea09a4633492f24291f04c03c43290aab0), I get a runtime error:
```
Uncaught TypeError: top is not a function
```

This error does not appear when I use the generated JavaScript files as modules.

`esbuild` version is `0.14.24`

**Comment by evanw** [comment]
I haven't run your code, but from your description it sounds like you're running esbuild's output in the global scope. If that's the case, then this is a usage error and not a bug with esbuild. You are not supposed to do that. 

If you are using `--format=esm` then you are telling esbuild that it can assume the output will be run as ESM, which means you must also use `type=module` in your script tag. Otherwise if you do not want to run the output as ESM, then you should not tell esbuild to use the ESM output format. Instead you should use the IIFE output format (which is the default). This is documented here: https://esbuild.github.io/api/#format.

**Comment by Soupstraw** [comment]
Oh, thanks! That indeed fixes the issue.
