### ISSUE TITLE
[Feature Request] Try resolve const enum from .d.ts

### ISSUE THREAD

**Issue by yangmingshan** [evanw/esbuild#3359]
# Problem
I have a project base on `@vue/reactivity`, and `@vue/reactivity` contains const enum. I want to use `esbuild` to build my project, but I can't, because `esbuild` can't resolve const enum from `@vue/reactivity`. I'm guessing this is because the const enum only exist in the type file and not source file.

# Request
So, is it possible to resolve package's const enum from the package's type file?

**Comment by yangmingshan** [comment]
Related issue: https://github.com/vitest-dev/vitest/issues/1650

**Comment by evanw** [comment]
> I'm guessing this is because the const enum only exist in the type file and not source file.

Yes, this is the problem. Here's Vite's documentation about this from [the link you pasted](https://github.com/vitest-dev/vitest/issues/1650#issuecomment-1186146956):

> ### TypeScript Compiler Options
> 
> Some configuration fields under `compilerOptions` in `tsconfig.json` require special attention.
> 
> #### `isolatedModules`
> 
> Should be set to `true`.
> 
> It is because `esbuild` only performs transpilation without type information, it doesn't support certain features like const enum and implicit type-only imports.
> 
> You must set `"isolatedModules": true` in your `tsconfig.json` under `compilerOptions`, so that TS will warn you against the features that do not work with isolated transpilation.

If you set `isolatedModules` to `true` and attempt to use a `declare const enum` from `@vue/reactivity`, TypeScript should give you a compile error. This is telling you that the library you are using is incompatible with tools such as esbuild that compile each module in isolation. This issue needs to be fixed in the library you are trying to use (I see you have already found https://github.com/vuejs/core/issues/1228 about fixing this for Vue).

I'm closing this issue because I don't plan on implementing this in esbuild. While it's sort of possible to make this work in some simple cases, emulating this correctly breaks down in more complex cases without esbuild replicating TypeScript's type system, which [I'm not going to do](https://esbuild.github.io/content-types/#no-type-system). I have to draw a "line in the sand" somewhere and I have decided that for esbuild, the line is that esbuild does not attempt to interpret type annotations (and everything in a `.d.ts` file is a type annotation).

**Comment by yangmingshan** [comment]
Thank you for your response, it makes perfect sense.
