### ISSUE TITLE
Enable built-in minifier replacement via plugin

### ISSUE THREAD

**Issue by hinell** [evanw/esbuild#3380]
I request to provide specific config & callbacks for plugins API to make it possible to replace built-in minifier by some other tool or tools. I.e. some config property to disable internal minifier inside plugin setup.

Thanks.

**Comment by evanw** [comment]
You can disable the minifier here: https://esbuild.github.io/api/#minify (but it's not enabled by default, so you don't need to do that). I'm closing this issue because I don't believe it makes sense to have an API for this. If you want to use another minifier on esbuild's output, you can just run the minifier on esbuild's output. No API change is needed for that.
