### ISSUE TITLE
ESBuild is not bundling the `ws` package for my VS Code extension

### ISSUE THREAD

**Issue by mrakgr** [evanw/esbuild#3386]
Link: https://github.com/microsoft/vscode/issues/193129

I am trying to bundle the [Spiral VS Code plugin](https://github.com/mrakgr/The-Spiral-Language/tree/c7d20ebff6d7e288ee388558f8b57495ec48937b/VS%20Code%20Plugin) and it is giving me trouble. For some reason it is not bundling correctly.

The way to reproduce this issue would be to clone the Spiral repo, and inside it, `npm install` the packages, run `npm esbuild`, delete the `node_modules` folder and then run the extension host. At that point you'll see that the `ws` package is missing.

**Comment by evanw** [comment]
This is a problem with the library you are using: https://github.com/dotnet/aspnetcore/issues/47674. The library you are using (at least that specific version) is deliberately not bundler-friendly because it contains anti-bundler code to hide imports from bundlers. That's not esbuild's problem, so I'm closing this issue as it's irrelevant to this project. This problem with that library has also already been fixed: https://github.com/dotnet/aspnetcore/pull/48154. It looks like the fix hasn't really been released yet. There is a release candidate available that you can install, or you can wait for the real release. I'll leave that decision up to you.

**Comment by mrakgr** [comment]
Ok, sorry for blaming ESBuild unfairly, and thanks. Who could have imagined the library authors would have put in hacks like those? I'll stick to not bundling the packages until this gets fixed.
