### ISSUE TITLE
Static block when using dynamic properties on a class

### ISSUE THREAD

**Issue by Nemikolh** [evanw/esbuild#3389]
Hello! :wave:

I've noticed that `esbuild` produces different code than `tsc` for the following code:

```ts
const k = 'a';

export class Foo {
  private [k]?: string;
  private foobar: string = 'test';
}
```

With `tsc` you get:

```js
const k = 'a';
class Foo {
    constructor() {
        this.foobar = 'test';
    }
}
```

While with `esbuild` you get:

```js
var k = "a";
var Foo = class {
  constructor() {
    this.foobar = "test";
  }
  static {
    k;
  }
};
```

In particular, I'm wondering whether or not it's a bug for `esbuild` to emit this static block.

Here is a playground on stackblitz for the issue: https://stackblitz.com/edit/node-9crmal

_ps: thanks for the amazing project btw! :heart:_

**Comment by evanw** [comment]
Evaluating an identifier could potentially have a side effect, and esbuild tries not to remove code with potential side effects. For example, this code could potentially throw a ReferenceError if `k` is not defined:

```ts
export class Foo {
  private [k]?: string;
  private foobar: string = 'test';
}
```

This code also could throw a ReferenceError for a different reason:

```ts
export class Foo {
  private [k]?: string;
  private foobar: string = 'test';
}

const k = 'a';
```

The `k` is present because esbuild doesn't do the (potentially very) complicated analysis to determine if a ReferenceError will be thrown or not. It just leaves the `k` there and lets the JavaScript VM apply any side effect that it has.

**Comment by Nemikolh** [comment]
Makes total sense! Thanks a lot for the detailed response 😃
