### ISSUE TITLE
unsupported export namespace？

### ISSUE THREAD

**Issue by ikilobyte** [evanw/esbuild#3406]
>  sample code

https://esbuild.github.io/try/#dAAwLjE5LjMAAGV4cG9ydCBuYW1lc3BhY2UgQ21kcyB7CiAgICBleHBvcnQgaW50ZXJmYWNlIFVzZXIgewoKICAgIH0KfQ

I use namespaces to distinguish the same interface，However, it is not supported.

**Comment by hyrious** [comment]
`namespace` is a TypeScript feature, you have to enable `--loader=ts` to tell esbuild to treat your input is TypeScript.

**Comment by ikilobyte** [comment]
Thank. 
But there's still a problem.

> src/contract/player.ts

```ts
export namespace Player {
    export interface Info {
        id: number,
    }
}
```

> src/main.ts

```ts
import {Player} from "./contract/player";
import Info = Player.Info;

const data: Info = {
    id: 1,
}

console.log(data);
```

> esbuild.mjs
```js
import esbuild from 'esbuild'

await esbuild.build({
	entryPoints: ['src/main.ts'],
	logLevel: 'info',
	bundle: true,
	outfile: 'bundle.cjs',
	format: 'cjs',
	platform: 'node',
	sourcemap: 'inline',
	tsconfig: 'tsconfig.json',
	target: 'ES2020',
	loader: {
		'.ts': 'ts'
	},
});
```

> node esbuild.mjs
```bash
✘ [ERROR] No matching export in "src/contract/player.ts" for import "Player"

    src/main.ts:1:8:
      1 │ import {Player} from "@/contract/player";
        ╵         ~~~~~~

```

**Comment by hyrious** [comment]
This was because of 2 behaviors of how esbuild is detecting types:

1. [Empty namespaces are compiled to nothing](https://esbuild.github.io/try/#dAAwLjE5LjMALS1sb2FkZXI9dHMAZXhwb3J0IG5hbWVzcGFjZSBQbGF5ZXIgewogIGV4cG9ydCBpbnRlcmZhY2UgSW5mbyB7fQp9) since they do not exist in JavaScript, they are just types.
2. `import A = B.C` implies `B` could potentially exist (because this line can become `const A = B.C`), so esbuild must keep the `import {B}` statement. [playground](https://esbuild.github.io/try/#dAAwLjE5LjMALS1sb2FkZXI9dHMAaW1wb3J0IHtQbGF5ZXJ9IGZyb20gJ2V4dGVybmFsJwppbXBvcnQgSW5mbyA9IFBsYXllci5JbmZvCnZhciBhOiBJbmZvID0ge30)

In the end esbuild said it cannot find the name `Player` in that file, which is true because that file is exporting nothing.

The culprit here is the statement `import Info = Player.Info`, this kind of code is hard to tell whether the `Info` is a type or entity. I would recommend you to write this instead:

```ts
type Info = Player.Info
```

[see it on playground](https://esbuild.github.io/try/#YgAwLjE5LjMALS1idW5kbGUgLS1mb3JtYXQ9Y2pzAGUAc3JjL21haW4udHMAaW1wb3J0IHtQbGF5ZXJ9IGZyb20gIi4vY29udHJhY3QvcGxheWVyIjsKdHlwZSBJbmZvID0gUGxheWVyLkluZm87Cgpjb25zdCBkYXRhOiBJbmZvID0gewogICAgaWQ6IDEsCn0KCmNvbnNvbGUubG9nKGRhdGEpOwAAc3JjL2NvbnRyYWN0L3BsYXllci50cwBleHBvcnQgbmFtZXNwYWNlIFBsYXllciB7CiAgICBleHBvcnQgaW50ZXJmYWNlIEluZm8gewogICAgICAgIGlkOiBudW1iZXIsCiAgICB9Cn0)

**Comment by ikilobyte** [comment]
Thank.

**Comment by ikilobyte** [comment]
How does watch mode show compilation time?

```js
import esbuild from 'esbuild'

const context =  await esbuild.context({
	entryPoints: ['src/main.ts'],
	logLevel: 'info',
	bundle: true,
	outfile: 'bundle.cjs',
	format: 'cjs',
	platform: 'node',
	sourcemap: 'inline',
	tsconfig: 'tsconfig.json',
	target: 'ES2020',
	loader: {
		'.ts': 'ts'
	},
});

await context.watch();
```

>  output 

```
[watch] build started (change: "src/main.ts")
[watch] build finished
```

>  Can the time-consuming be displayed? For example, as follows

```
[watch] build started (change: "src/main.ts")
[watch] build finished (10ms)
```

**Comment by hyrious** [comment]
_That's another question, though_

The builtin watch mode logger does not provide a build time, however you can invent the wheel in the onEnd callback:

```js
esbuild.context({
  plugins: [{
    name: 'rebuild-log',
    setup({ onStart, onEnd }) {
      var t
      onStart(() => {
        t = Date.now()
      })
      onEnd(() => {
        console.log('build finished', Date.now() - t, 'ms')
      })
    }
  }]
})
```

**Comment by ikilobyte** [comment]
Thank you.
