### ISSUE TITLE
Watch monorepos

### ISSUE THREAD

**Issue by hitsthings** [evanw/esbuild#3417]
This might be a PEBKAC but I am noticing that esbuild's watch doesn't rebuild when a dependency changes. This happens in my monorepo. One package `@monorepo/a` depends on `@monorepo/b` which is in a sibling folder:

```
- packages
  - a
    - scripts/watch.js
  - b
```

If I run `npm run -w packages/a watch` which executes `scripts/watch.js`, everything is built fine. But if I change a file in `packages/b`, esbuild does not rebuild anything. I assume that anything that looks like a package from node_modules (e.g. `@monorepo/b`) is ignored for watching purposes. Is there any way to include files from other packages, especially monorepo siblings, in the watch?

The only setting that seems relevant is `entryPoint` which doesn't seem to be enough to work around this (presumably very useful) optimization in esbuild. It would be nice if there were a way to specify dependencies to watch like `@monorepo/*` or it would be nice if esbuild could detect a monorepo and watch the whole thing, or have some kind of "G2" level of checking for changes that occasionally checks for updates in dependencies.

**Comment by evanw** [comment]
I'm guessing the reason why this isn't working would depend on at least what `scripts/watch.js` is doing. This should already be working because there is no code in esbuild's watcher to detect specific file structures and not watch them. Everything in the watcher is very general purpose. All file system accesses during the build are tracked and sent over to the watcher, which then treats all file accesses equally. It's impossible to say what's actually going on here because you have not provided enough information to reproduce the problem. Typically when watch mode doesn't work it's because of extra code outside of esbuild that isn't doing something correctly (e.g. an esbuild plugin or a pre/post build script). The only thing I could think of here that might be related would be symlinks. Maybe you have some monorepo tooling that makes symlinks, and maybe esbuild's watch mode has some problem with symlinks? Could be something else to investigate on your end in any case.

**Comment by hitsthings** [comment]
Thanks for the info!

> The only thing I could think of here that might be related would be symlinks. Maybe you have some monorepo tooling that makes symlinks, and maybe esbuild's watch mode has some problem with symlinks?

Yup that's almost certainly it. It's not any bespoke tooling - that is how NPM workspaces work. It symlinks each package into the root node_modules so you require them in that way.

I'll look into it a bit more and see if I can set up a simple reproduction and create a better issue if I can reproduce it. Thanks!

**Comment by paulbrzeski** [comment]
I have three folders - one contains my web application, another contains shared code and the third is a server application.

Watch is working for changes in the web application, but if I change shared code it doesn't rebuild.

The web application uses an import on the shared code which works fine for build, but watch doesn't seem to be observing changes in the shared code. Even after a few minutes nothing is fed back. There are no symlinks or remote mounts on this project, just local folders in the same monorepo.

My guess is that watch is only observing the current working directory and nothing above it? Will post an update if I find an answer.
