### ISSUE TITLE
Esbuild not throwing error when imports are missing during build and compilation

### ISSUE THREAD

**Issue by ashiqrasool7** [evanw/esbuild#3420]
![image](https://github.com/evanw/esbuild/assets/138850735/1d2c5233-b680-45fd-821b-86d71a719e18)
I am trying to adopt esbuild and move away from webpack.
One of the stages in our CI pipeline is to build/compile the code. 
When i removed the import statement for the Button, the code successfully builds for esbuild, however, webpack correctly throws an error and stops the build.

I am expecting a similar behaviour to webpack on this, to throw errors where applicable for react code. 

Is this possible?

**Comment by hyrious** [comment]
> webpack correctly throws an error and stops the build

I'm not sure which part of your webpack config did this. Does it come from the babel-loader, or from the ts-loader?

I'm asking this because it is allowed to referencing any global variables' names (thinking that `Button` exists on `window.Button`, which is undeniably possible). The bundler should not stop users from doing that. In fact, you are already doing that when you're using React:

```jsx
createRoot(<App />).render(document.getElementById('app')) // <-- what is 'document'?
```

If your error comes from TypeScript, then you can simply run `tsc --noEmit` in parallel with the esbuild building process.

**Comment by evanw** [comment]
You did not follow instructions because you did not provide a way to reproduce your issue. Marking this issue as `unactionable`. It will be closed soon if no way to reproduce the issue is provided. 

That said, make sure you read https://esbuild.github.io/content-types/#typescript before using esbuild. It looks like you took a screenshot of red underlines your IDE. That doesn’t make sense because esbuild is not a linter or a type checker and has nothing to do with IDE tooling.

**Comment by ashiqrasool7** [comment]
> You did not follow instructions because you did not provide a way to reproduce your issue. Marking this issue as `unactionable`. It will be closed soon if no way to reproduce the issue is provided.
> 
> That said, make sure you read https://esbuild.github.io/content-types/#typescript before using esbuild. It looks like you took a screenshot of red underlines your IDE. That doesn’t make sense because esbuild is not a linter or a type checker and has nothing to do with IDE tooling.

Thanks for your reply and sorry for not being clear. 
What I am looking for is for the build tool to throw an error if a particular component is used without importing.

An example of steps to reproduce:
Using Pagination from antd without importing it.
**Missing Code: import { Pagination } from 'antd';**
`import React from 'react';

const App: React.FC = () => <Pagination defaultCurrent={6} total={500} />;

export default App;`


This kind of error is not picked up by esbuild, but webpack flags it during build.
A screenshot of the error. 
This error was produced by removing the import statement for the component Button.
<img width="543" alt="image" src="https://github.com/evanw/esbuild/assets/138850735/5c4207fb-7efd-4879-ac02-c86194bc6b3e">

**Comment by hyrious** [comment]
> That doesn’t make sense because esbuild is not a linter or a type checker and has nothing to do with IDE tooling.

Your error seems come from [eslint](https://eslint.org/), which is a linter, and esbuild is not a linter.

You can simply run `npx eslint .` to get the error without the help of esbuild.

**Comment by ashiqrasool7** [comment]
> > That doesn’t make sense because esbuild is not a linter or a type checker and has nothing to do with IDE tooling.
> 
> Your error seems come from [eslint](https://eslint.org/), which is a linter, and esbuild is not a linter.
> 
> You can simply run `npx eslint .` to get the error without the help of esbuild.

Understood, thank you!

**Comment by ashiqrasool7** [comment]
not related to esbuild, add eslint plugin to check for lint errors during build
