### ISSUE TITLE
Build output contains altered variable names even without minify identifiers option

### ISSUE THREAD

**Issue by alessbelli** [evanw/esbuild#3427]
I am observing quite a few cases in which code produced by esbuild contains extra numeric suffixes (among other things) appended to variable names.
eg: `Buffer3` as opposed to `Buffer`, `foobar2` as opposed to `foobar`.

This makes it harder to reason about stack traces, so I wondered why this was happening (given that the original names should work unaltered, in a context where files are scoped independently) and how to disable this behavior - I would expect that identifiers remain unaltered by the build process when we don't specify to alter them.

Thank you in advance!

**Comment by evanw** [comment]
This is happening for internal esbuild reasons, such as avoiding a name collision with another symbol that may or may not end up in the final bundle (I’m not being specific about why it happens because you weren’t specific about the details of your problem). 

> I would expect that identifiers remain unaltered by the build process when we don't specify to alter them.

There is no guarantee that esbuild will preserve all of the original identifiers in the program. That is not an invariant that esbuild upholds. Indeed it’s sometimes impossible to do that without paying a run-time cost, which is not a transformation that esbuild does for you. If you require all identifiers to keep their original names after bundling then esbuild is not the bundler for you.

**Comment by alessbelli** [comment]
Good to know - any idea how to set up a transformation that would help us preserve symbols?
Esbuild has been working great for us, and this extra feature is more of a QoL extra, but I'd love it if we could preserve identifiers.

**Comment by evanw** [comment]
I'm closing this because this is not something that esbuild attempts to solve, so it's out of scope. I can't tell you how to set up a transformation that would help us preserve symbols with esbuild because esbuild doesn't do that.
