### ISSUE TITLE
19.x only - Could not resolve require("./src/build/**/*/DTraceProviderBindings"

### ISSUE THREAD

**Issue by vitaliytv** [evanw/esbuild#3434]
Exception when using module like [dtrace-provider](https://www.npmjs.com/package/dtrace-provider)
```
 > [build-env  6/10] RUN npx esbuild@0.19.4 src/index.js     --sourcemap=inline     --bundle     --platform=node     --outfile=app.cjs:
4.413 npm WARN exec The following package was not found and will be installed: esbuild@0.19.4
10.09 ✘ [ERROR] Could not resolve require("./src/build/**/*/DTraceProviderBindings")
10.09 
10.09     node_modules/dtrace-provider/dtrace-provider.js:18:30:
10.09       18 │ ...= require('./src/build/' + builds[i] + '/DTraceProviderBindings');
10.09          ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
10.09 
10.38 1 error

```

18.x work perfect

**Comment by evanw** [comment]
Thanks for the report. This is probably because the glob pattern in that file doesn't contain a file extension and esbuild's glob pattern implementation currently requires an exact match on the file name (i.e. it doesn't replicate node's implicit file extension magic during glob pattern expansion).

One way to work around this is to exclude the `dtrace-provider` package from your bundle. This can be done with esbuild's [external](https://esbuild.github.io/api/#external) feature.

**Comment by vitaliytv** [comment]
thank you @evanw 
this code help:

```bash
npx esbuild src/index.js \
    --sourcemap=inline \
    --bundle \
    --platform=node \
    --external:dtrace-provider \
    --outfile=app.cjs
```
