### ISSUE TITLE
Speed comparison with rollup

### ISSUE THREAD

**Issue by dilyanpalauzov** [evanw/esbuild#3436]
https://esbuild.github.io at the top compares the speeds of `esbuild` and `rollup+terser`.  Rollup 4 changed from using acorn to swc, thus its speed also changed.  Please clarify at https://esbuild.github.io whether “rollup+terser” refers to rollup 3 or rollup 4 and in the former case, update the comparison to rollup 4.

**Comment by dilyanpalauzov** [comment]
Or keep one line for rollup 3+terser and one line for rollup 4 + terser.

**Comment by Szymon-Wrzos** [comment]
Besides, you can use esbuild and swc in webpack and in rollup

It'd be fair to compare esbuild with swc for es6+ since swc can transpile to es5 and lower

**Comment by evanw** [comment]
It's definitely not Rollup 4. That just came out a week ago :)

PR #3441 updates the versions of the tools in esbuild's benchmark. I'm closing this issue in favor of that PR.

> It'd be fair to compare esbuild with swc for es6+ since swc can transpile to es5 and lower

This is a bundler benchmark. SWC has a bundler but last time I checked it didn't work. I was keeping some code around for a while that runs it in my benchmark but I eventually [removed it](https://github.com/evanw/esbuild/commit/8e0580dc64b56b93142ff6e6a466e0423ac9080c) because the bugs were never fixed. I just checked [their documentation](https://swc.rs/docs/usage/bundling) again and there's a warning about it not being actively developed, so it still doesn't seem like a good candidate for my benchmark:

> 🚧 This feature is still under construction. Also, the main author of SWC works for Turbopack by Vercel, so this feature is not a something that will be actively developed.
