### ISSUE TITLE
Async generator generator polyfill causes crashes in older browsers

### ISSUE THREAD

**Issue by tido64** [evanw/esbuild#3453]
The async generator generator polyfill introduced 0.18.8 causes crashes in "older" browsers (such as [Hermes](https://github.com/facebook/hermes)) because it assumes that `Symbol.asyncIterator` exists:

https://github.com/evanw/esbuild/blob/a7fcc43fdb6b6edc58f781fe96328f4867f4b33e/internal/runtime/runtime.go#L392-L393

We've worked around the crash by polyfilling the symbol, but it feels like I'm missing something. It works for now, but I don't know if this causes other issues or whether there's a proper solution.

**Comment by evanw** [comment]
I think this behavior with `Symbol` was originally from TypeScript's implementation of the `using` statement. There it makes sense that people would have to polyfill `Symbol.dispose` since any use of the `using` statement needs to use `Symbol.dispose` when constructing the object. But async generators are different because it's possible (and even likely) to use them without your code ever using `Symbol.asyncIterator` at all. So I think it makes sense for esbuild to polyfill `Symbol.asyncIterator` in this case.

**Comment by tido64** [comment]
Do you have a preference for how this should be done? I'd like to give it a shot if I have some time.

**Comment by zikaeroh** [comment]
FWIW it was intentional on the TypeScript side to not use `Symbol.for`: https://github.com/microsoft/TypeScript/pull/54505#discussion_r1237795863

Babel uses a different symbol name for this (some `@@` prefix), so I think code generated by Babel won't work with the new helper as it will try to use a different name, which is roughly the hazard mentioned in the linked comment.

**Comment by jakebailey** [comment]
FWIW it was intentional on the TypeScript side to not use `Symbol.for`: https://github.com/microsoft/TypeScript/pull/54505#discussion_r1237795863

Babel uses a different symbol name for this (some `@@` prefix), so I think code generated by Babel won't work with the new helper as it will try to use a different name (and vice versa), which is roughly the hazard mentioned in the linked comment. Seemingly the most compatible option is to polyfill the real global.

**Comment by jakebailey** [comment]
I misspoke; Babel uses the same string you have here. I guess this is only a hazard for compat with typescript code.
