### ISSUE TITLE
Allow using JSX before calling super when using --jsx-dev

### ISSUE THREAD

**Issue by skovhus** [evanw/esbuild#3454]
esbuild does not support using JSX inside a constructor before calling super when using the `--jsx-dev` flag . This seems like a bug. Note that [Babel supports this](https://github.com/babel/babel/pull/14271/files?w=1#diff-9126e794347775e905997bc502b918855652468b2c3293bfb2275de6bc7ef7a1R315).

When `--jsx-dev` the compiled version includes `this` as the last argument of the JSX function, which is problematic if you have some JSX defined inside a class constructor before calling super because you cannot access this before that point.

```typescript
  // Compiled code from the reproduction link
class ChildComponent extends ParentComponent {
  constructor() {
    super(/* @__PURE__ */ jsxDEV("div", { children: "Content" }, void 0, false, {
      fileName: "<stdin>",
      lineNumber: 22,
      columnNumber: 11
    }, this));
  }
}
```

### Reproduction
- [esbuild.github.io/try using --loader=jsx](https://esbuild.github.io/try/#dAAwLjE5LjUALS1qc3g9YXV0b21hdGljIC0tbG9hZGVyPWpzeABpbXBvcnQgKiBhcyBSZWFjdCBmcm9tICdyZWFjdCc7CmltcG9ydCAnLi9BcHAuY3NzJzsKCmNsYXNzIFBhcmVudENvbXBvbmVudCBleHRlbmRzIFJlYWN0LkNvbXBvbmVudCB7CiAgY29uc3RydWN0b3IoY29udGVudCkgewogICAgc3VwZXIoKTsKICAgIHRoaXMuY29udGVudCA9IGNvbnRlbnQ7CiAgfQoKICByZW5kZXIoKSB7CiAgICByZXR1cm4gPGRpdj57dGhpcy5jb250ZW50fTwvZGl2PjsKICB9Cn0KCmNsYXNzIENoaWxkQ29tcG9uZW50IGV4dGVuZHMgUGFyZW50Q29tcG9uZW50IHsKICBjb25zdHJ1Y3RvcigpIHsKICAgIC8vIFRoZSBmb2xsb3dpbmcgbGluZSB3b3JrcyBmaW5lCiAgICAvLyBzdXBlcignQ29udGVudCcpOwoKICAgIC8vIFRoaXMgb25lIHdpbGwgY3Jhc2ggYXQgcnVudGltZSB3aXRoCiAgICAvLyBVbmNhdWdodCBSZWZlcmVuY2VFcnJvcjogTXVzdCBjYWxsIHN1cGVyIGNvbnN0cnVjdG9yIGluIGRlcml2ZWQgY2xhc3MgYmVmb3JlIGFjY2Vzc2luZyAndGhpcycgb3IgcmV0dXJuaW5nIGZyb20gZGVyaXZlZCBjb25zdHJ1Y3RvcgogICAgc3VwZXIoPGRpdj5Db250ZW50PC9kaXY+KTsKICB9Cn0KCmZ1bmN0aW9uIEFwcCgpIHsKICByZXR1cm4gPENoaWxkQ29tcG9uZW50IC8+Owp9CgpleHBvcnQgZGVmYXVsdCBBcHA7Cg) (works as expected)
- [esbuild.github.io/try using --jsx-dev](https://esbuild.github.io/try/#dAAwLjE5LjUALS1qc3g9YXV0b21hdGljIC0tbG9hZGVyPWpzeCAtLWpzeC1kZXYAaW1wb3J0ICogYXMgUmVhY3QgZnJvbSAncmVhY3QnOwppbXBvcnQgJy4vQXBwLmNzcyc7CgpjbGFzcyBQYXJlbnRDb21wb25lbnQgZXh0ZW5kcyBSZWFjdC5Db21wb25lbnQgewogIGNvbnN0cnVjdG9yKGNvbnRlbnQpIHsKICAgIHN1cGVyKCk7CiAgICB0aGlzLmNvbnRlbnQgPSBjb250ZW50OwogIH0KCiAgcmVuZGVyKCkgewogICAgcmV0dXJuIDxkaXY+e3RoaXMuY29udGVudH08L2Rpdj47CiAgfQp9CgpjbGFzcyBDaGlsZENvbXBvbmVudCBleHRlbmRzIFBhcmVudENvbXBvbmVudCB7CiAgY29uc3RydWN0b3IoKSB7CiAgICAvLyBUaGUgZm9sbG93aW5nIGxpbmUgd29ya3MgZmluZQogICAgLy8gc3VwZXIoJ0NvbnRlbnQnKTsKCiAgICAvLyBUaGlzIG9uZSB3aWxsIGNyYXNoIGF0IHJ1bnRpbWUgd2l0aAogICAgLy8gVW5jYXVnaHQgUmVmZXJlbmNlRXJyb3I6IE11c3QgY2FsbCBzdXBlciBjb25zdHJ1Y3RvciBpbiBkZXJpdmVkIGNsYXNzIGJlZm9yZSBhY2Nlc3NpbmcgJ3RoaXMnIG9yIHJldHVybmluZyBmcm9tIGRlcml2ZWQgY29uc3RydWN0b3IKICAgIHN1cGVyKDxkaXY+Q29udGVudDwvZGl2Pik7CiAgfQp9CgpmdW5jdGlvbiBBcHAoKSB7CiAgcmV0dXJuIDxDaGlsZENvbXBvbmVudCAvPjsKfQoKZXhwb3J0IGRlZmF1bHQgQXBwOwo) (fails)

### Related

https://github.com/vitejs/vite-plugin-react/issues/231
https://github.com/babel/babel/pull/14271

**Comment by skovhus** [comment]
@evanw is this something you would want esbuild to support? I might be able to help implementing this if I get a few pointers.

**Comment by evanw** [comment]
FWIW TypeScript [doesn't seem to handle this case either](https://www.typescriptlang.org/play?jsx=5#code/MYGwhgzhAEBiD29oFMAeAXZA7AJjA8gEYBWyw60A3gFDR3TDxYToBOArufKwBQCUVWvWER2AB2S8APDgCWANwD0APj5C6AX2pasyAO5xE-akA). It's too bad that there doesn't seem to be a specification for the new React JSX transform, or at least not one that adequately describes it. I can only find [this](https://legacy.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) which links to [this](https://github.com/reactjs/rfcs/blob/createlement-rfc/text/0000-create-element-changes.md) which doesn't describe what `__self` is at all. Given how loose Babel is with this (just omit it within the entire constructor), I'm taking it that the value of `__self` doesn't really matter that much. It sounds like maybe the React team was using this for a migration warning at some point in the past, but now the value is perhaps irrelevant? I can have esbuild do what Babel does to fix this case. Hopefully I'm not breaking anything since I don't understand how it's supposed to be used.

**Comment by skovhus** [comment]
Thanks for fixing this and adding the detailed explanation and changelog entry! 

Frustrating that there isn’t a specification for this.
