### ISSUE TITLE
[Question] Conversion to CommonJS and Global Modules.

### ISSUE THREAD

**Issue by cemalgnlts** [evanw/esbuild#3457]
Hi,

I have a library like this:
```js
import fetch from "node-fetch";

class MyLib {}

export default MyLib;
```

This is how I translate it into CommonJS:
```js
build({
    entryPoints: ["src/index.ts"],
    allowOverwrite: true,
    format: "cjs",
    platform: "node",
    packages: "external",
    outfile: "dist/mail.cjs",
    target: "node14"
},
```

This is what I expect from build:
```diff
- import fetch from "node-fetch";
+ const fetch = require("node-fetch");

class MyLib {}

- export default MyLib;
+ module.exports = MyLib;
```

Instead I get a very long result:
```js
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var src_exports = {};
__export(src_exports, {
  default: () => src_default
});
module.exports = __toCommonJS(src_exports);
var import_node_fetch = __toESM(require("node-fetch"), 1);
class Mailjs {

// ...
```

Also, I don't need the `node-fetch` module for the browser, can I move all modules to the global area for the browser?

**Comment by evanw** [comment]
Part of the extra code is because ESM has read-only exports (i.e. they are non-locally immutable but locally mutable). That is why esbuild generates a shim object with getters for named exports. It would be incorrect for esbuild to not generate the shim object because then the exports would incorrectly be mutable from other modules. Also the CommonJS equivalent of `export default` is `exports.default = MyLib` not `module.exports = MyLib` (ignoring getters at the moment for simplicity). This is because ESM supports many export names of which `default` is just one. If esbuild generated `module.exports` instead of `exports.default` then it would potentially overwrite other named exports and/or cause the shape of the export object to be unpredictable if an export named something other than `default` is added later.

Part of the extra code is because the way the JavaScript ecosystem has evolved, there are two different possibilities for what a default `import` means. One interpretation is that `import fetch from 'node-fetch'` should behave like `const fetch = require('node-fetch')` and another interpretation is that it should behave like `const fetch = require('node-fetch').default`. Which interpretation esbuild uses depends on a few things including the presence of the `__esModule` property on the object returned by `require()`. You can read more about this mess here: https://esbuild.github.io/content-types/#default-interop. Just know that this isn't esbuild's mess. This is the result of node diverging in behavior from the rest of the JavaScript community. If you use a named import instead of a default import, esbuild won't generate the extra code to check for `__esModule`.

> can I move all modules to the global area for the browser?

Yes, you can do that. But you have to do that yourself using conditional compilation. That isn't something that esbuild does for you. There are a few ways to do this including the `browser` field in `package.json`, the `browser` condition in `package.json`, or a `define` that causes the execution of your code to behave differently when targeting the browser.

**Comment by cemalgnlts** [comment]
Thanks for the explanation.
