### ISSUE TITLE
Missing space before nested elements on a new line when building jsx 

### ISSUE THREAD

**Issue by ArnaudPare-Vogt** [evanw/esbuild#3469]
When writing jsx it can be usefull to split element content across multiple lines for readability. When doing this, a space is added between the lines. E.g. `<p>Very long content\n      some more content<\p>` will become `<p>Very long content some more content<\p>`.

However, this does not always work. When the new line start with a new nested element, esbuild does not add an extra space, even though it should. This jsx:
`<p>Very long content\n      <a>some<\a> more content<\p>` 
currently becomes:  (Notice there is a missing space between the "content" and the anchor element.)
`<p>Very long content<a>some<\a> more content<\p>`
but should become:
`<p>Very long content <a>some<\a> more content<\p>`

This can be seen in the playground:
https://esbuild.github.io/try/#YgAwLjE5LjUAAGUAZW50cnkuanN4AGZ1bmN0aW9uIGJyb2tlbigpIHsKICAgIHJldHVybiA8ZGl2PgogICAgICAgIDxwPlNlZSBob3cgb24gdGhlIG5leHQgbGluZSwgdGhlcmUgaXMgYSBtaXNzaW5nIHNwYWNlCiAgICAgICAgPGE+UmlnaHQgYmVmb3JlIHRoaXMgZWxlbWVudDwvYT4uIEJ1dCB0aGlzIGlzIG9ubHkgdGhlCiAgICAgICAgY2FzZSBpZiBhIG5lc3RlZCBlbGVtZW50IHN0YXJ0cyB0aGUgbGluZS48L3A+CiAgICA8L2Rpdj47Cn0

**Comment by evanw** [comment]
I'm confused because esbuild seems to generate the exact same JavaScript as both [TypeScript](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAIwE5wNYFMwAoCUiA3gFCLmKpZQipIA8AJjAG4B8ZFX9ADmwMpYsiABZwA7ogSIoI4WCwAPKIgA2MBQBoZcqohgBnRAENEAW0MGNAc0QGexiFk5dy9Y2wBKMayJXIsYDg9WUNELFUsMxwoegB6DwA6RAAhEBVQozCEVQBPHWdXCghjA2EYYBNEBQMoLEZwyOiwFVrjVCgjWWF1BUT4vhdEeOZ2AG4SAF8gA) and [Babel](https://babel.dev/repl#?browsers=chrome%20111&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAIwE5wNYFMwAoCUiA3gFCLmKpZQipIA8AJjAG4B8ZFX9ADmwMpYsiABZwA7ogSIoI4WCwAPKIgA2MBQBoZcqohgBnRAENEAW0MGNAc0QGexiFk5dy9Y2wBKMayJXIsYDg9WUNELFUsMxwoegB6DwA6RAAhEBVQozCEVQBPHWdXCghjA2EYYBNEBQMoLEZwyOiwFVrjVCgjWWF1BUT4vhdEeOZ2AG4SAF8gA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-3%2Ctypescript&prettier=false&targets=&version=7.23.2&externalPlugins=%40babel%2Fplugin-syntax-explicit-resource-management%407.20.0&assumptions=%7B%7D) for this JSX. What are you basing your expectation on? It would be very bad if esbuild's JSX transform behaved differently than both TypeScript and Babel.

Note that JSX is not HTML, so if you are basing your expectation on HTML then you will be in for surprises. My understanding is that it's common practice when working with JSX to manually insert spaces using `{' '}` to get around whitespace differences like this between JSX and HTML.

**Comment by ArnaudPare-Vogt** [comment]
You are completely right, I was basing my expectation on HTML, I expected JSX to treat strings the same way HTML treats text nodes. I still think this is strange, but it is definitely not an issue with esbuild, and I agree that consistency between tools is much more important than this.

In any case, the workaround using `{' '}` is a bit clunky, but it does work, and I will use that going forward.

A big thanks for the fast reply :heart:
