### ISSUE TITLE
install.js should support HTTPS_PROXY environment variable

### ISSUE THREAD

**Issue by silverwind** [evanw/esbuild#347]
The [esbuild](https://www.npmjs.com/package/esbuild) module has below rudimentary `fetch` implementation that does not support fetching via HTTPS proxies which means the script will run for over 4 minutes waiting for the HTTPS request to timeout in environments without direct Internet connectivity.

I'd suggest switching to [make-fetch-happen](https://github.com/npm/make-fetch-happen) for this download which is a `fetch`-compatible module that `npm` itself uses and it has full proxy support.

````js
function fetch(url2) {
  return new Promise((resolve, reject) => {
    https.get(url2, (res) => {
      if ((res.statusCode === 301 || res.statusCode === 302) && res.headers.location)
        return fetch(res.headers.location).then(resolve, reject);
      if (res.statusCode !== 200)
        return reject(new Error(`Server responded with ${res.statusCode}`));
      let chunks = [];
      res.on("data", (chunk) => chunks.push(chunk));
      res.on("end", () => resolve(Buffer.concat(chunks)));
    }).on("error", reject);
  });
}
````

Related: https://github.com/evanw/esbuild/issues/319

I could probably send you a pull request but I could not find the source for this script in the repo.

**Comment by evanw** [comment]
I don't want the install script to depend on additional packages. I'm going to try moving `npm install` before the direct download. That should handle this case while still supporting the case where npm isn't installed, since the npm command should fail instantly if it doesn't exist.

**Comment by silverwind** [comment]
What's the downside of doing `npm install`? Does it require golang on the system?

I guess if you don't want additional dependencies, you could replicate what these two modules are doing to support downloads via proxies:

https://github.com/Rob--W/proxy-from-env
https://github.com/np-maintain/global-tunnel

**Comment by evanw** [comment]
The downside is that `npm install` is slower and more complicated than just doing a HTTP request because npm itself is slow and complicated. Running npm recursively is not exactly a supported use case (e.g. it deadlocks when doing a global install without a specific workaround). People may also have overridden the `npm` command with something else so it's impossible to know if it'll actually do what is intended or not. That's why I'm going to keep the HTTP request fallback path. I totally agree with you about node not having proxy support :(
