### ISSUE TITLE
Built-in dev server triggers rebuild twice on single page reload

### ISSUE THREAD

**Issue by stupid-genius** [evanw/esbuild#3475]
I have a vanilla, bare-bones setup while troubleshooting issues.  Running just the esbuild dev server and then refreshing my browser triggers 2 rebuilds.  The docs say:
> With esbuild's web server, **each incoming request** starts a rebuild if one is not already in progress, and then waits for the current rebuild to complete before serving the file.

but my browser is sending 5 requests.  5 requests are sent to the esbuild server, but it rebuilds only twice.  I'm not editing anything, so there are no changes.

1. I don't understand why there are 2 rebuilds and not 5.
2. How can I have only 1 rebuild, or no rebuilds?

My setup:
```
const onBuild = {
	name: 'onBuild',
	setup(build){
		build.onEnd(result => {
			console.log(result); // I see this twice
		});
	}
};

const context = await esbuild.context({
	entryPoints: ['app/public/scripts/index.js'],
	// entryNames: '[dir]/[name]-[hash]',
	loader: { '.png': 'dataurl' },
	bundle: true,
	minify: !devMode,
	sourcemap: devMode,
	outbase: 'app/public',
	outdir: 'dist/public',
	plugins: [onBuild]
});

console.log(await context.serve({
	servedir: 'dist/public',
	port: 3000
}));
```

**Comment by hyrious** [comment]
I guess the document has already answered your question:

> &hellip;if one is not already in progress, &hellip;

That is to say, although there're 5 requests, some of them are triggered too fast that they are scheduled in one build.

**Comment by evanw** [comment]
The current behavior of esbuild is to consider any request that comes in either during a build in progress or ≤ 250ms after the build finishes to be associated with that build. Otherwise esbuild will consider the latest build to be stale and start a new build. So if you have a slow web app that loads more things more than 250ms after page load, you will likely see multiple rebuilds. This should be harmless as the build results for the second build should be identical if nothing has changed since the first build.

**Comment by evanw** [comment]
I'm closing this issue because this is a question, not a problem with esbuild, and the question has been answered.
