### ISSUE TITLE
Error when transforming import.meta

### ISSUE THREAD

**Issue by LarsDenBakker** [evanw/esbuild#349]
When doing a single file transform using `es2019` or below, esbuild throws a warning: `"import.meta" is not available in the configured target environment and will be empty` and makes the import.meta empty. import.meta is supported by the browser, so it shouldn't be changed.

See a reproduction here: https://repl.it/repls/ObviousRespectfulDatawarehouse

**Comment by LarsDenBakker** [comment]
This looks like an intentional change in https://github.com/evanw/esbuild/blob/master/CHANGELOG.md#0517

However browsers have been supporting `import.meta` before 2019: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import.meta#Browser_compatibility. We rely on this a lot when developing without bundling.

**Comment by rtsao** [comment]
I think `es2020` refers to the [11th edition of the ECMAScript language spec](https://www.ecma-international.org/ecma-262/11.0/index.html#title), also known as ECMAScript 2020. My understanding is that this edition of the spec introduces `import.meta` for the first time.

So it seems `esXXXX` in target options correspond to contents of the published language specifications (rather than browser support in calendar years).

**Comment by LarsDenBakker** [comment]
Yeah, that make sense. Unfortunately unlike other transforms, this one breaks the code :( You can't really compile import.meta.url away, unless you use a different module system like system js.

**Comment by evanw** [comment]
If you are targeting specific browsers, you should be using those browser versions as the target instead of `es2020`. For example, to support the browsers on [the page you pointed to](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import.meta#Browser_compatibility) you could use `--target=chrome64,edge79,firefox62,safari11.1`. Does that work for you?

**Comment by LarsDenBakker** [comment]
I didn't realize this is now supported by esbuild. That looks like what I need here, thanks!

**Comment by yamafaktory** [comment]
@evanw Hi and thanks a ton for this awesome project!

Sorry to dig into this closed issue but I have a specific use case indirectly involving esbuild (via https://github.com/privatenumber/esbuild-loader) and Webpack 5 + this new worker feature https://github.com/webpack/webpack/pull/11439.

The issue is that if you are not targeting a recent enough browser - as you mentioned here https://github.com/evanw/esbuild/issues/349#issuecomment-680272791 - or something below `es2020`, `import.meta.url` is `undefined`. As a consequence, the Webpack 5 worker feature will not work (no extra chunk is generated).

I might be missing something but do you think that an additional option to keep the `import.meta` data would be something that esbuild could eventually provide?

**Comment by JiangWeixian** [comment]
> 

I meet a similar issue, in my project, I use `import.meta.webpackContext` with `esbuild-loader`, but `import.meta` is emty if `target: es2017`

I hack this issue by moving `import.meta.webpackContext` to `js` files, like

```js
// utils/webpack-env
// refs: https://webpack.js.org/api/module-variables/#importmetawebpackcontext
export const contextRequire = import.meta.webpackContext('..', {
  recursive: true,
  regExp: /.tsx/,
  mode: 'sync',
})
```

then use it in `App.tsx`

```tsx
import { contextRequire } from '@/utils/webpack-env'

console.log(contextRequire('./pages/index.tsx'))
```

**Comment by evanw** [comment]
In case it helps: A feature was just added to let you preserve `import.meta` even when targeting environments that don't support it: https://github.com/evanw/esbuild/releases/tag/v0.14.46. If you can pass `supports: { 'import-meta': true }` to esbuild, then it should override that part of the `target: 'es2017'` setting.

**Comment by douglasg14b** [comment]
@evanw Can you provide a config example where this option is used? I am struggling to find one.

**Comment by douglasg14b** [comment]
Ah, found it:

```
    supported: {
        'import-meta': true,
    },
```

However, to other readers, this does not clear the:
> ▲ [WARNING] "import.meta" is not available with the "cjs" output format and will be empty [empty-import-meta]

Error that kills the build....

**Comment by masonembry** [comment]
Found ya, @douglasg14b.
