### ISSUE TITLE
Transforming JavaScript decorators to the configured target environment ("nodeXX.Y.Z") is not supported yet

### ISSUE THREAD

**Issue by darcyrush** [evanw/esbuild#3496]
I already checked [3482](https://github.com/evanw/esbuild/issues/3482) and filed an issue with [tsx](https://github.com/privatenumber/tsx/issues/393) (which uses esbuild under the hood), who in turn requested to file the issue here.

I am using the `nestjs` framework's decorators along with `tsx` and a `tsconfig.json` with `"experimentalDecorators": true` but the issue persists.

I am using `node` `21.2.0` and `tsx` `4.1.2` on linux.

Here is a [minimal reproduction repository](https://github.com/darcyrush/tsx-min-repo)

**Comment by evanw** [comment]
If you run your code through esbuild without tsx involved then it works fine: https://esbuild.github.io/try/#dAAwLjE5LjUAewogIGxvYWRlcjogJ3RzJywKICB0YXJnZXQ6IFsnbm9kZTIxLjIuMCddLAogIHRzY29uZmlnUmF3OiB7CiAgICBjb21waWxlck9wdGlvbnM6IHsKICAgICAgZXhwZXJpbWVudGFsRGVjb3JhdG9yczogdHJ1ZSwKICAgIH0sCiAgfSwKfQBpbXBvcnQgeyBDb250cm9sbGVyLCBHZXQgfSBmcm9tICJAbmVzdGpzL2NvbW1vbiIKCkBDb250cm9sbGVyKCkKZXhwb3J0IGNsYXNzIEhlYWx0aENvbnRyb2xsZXIgewogIEBHZXQoJ2hlYWx0aC9yZWFkaW5lc3MnKQogIGFzeW5jIHJlYWRpbmVzcygpOiBQcm9taXNlPHZvaWQ+IHsgfQp9. I only get that error if I set `experimentalDecorators: false`. So the problem appears to be with tsx, not with esbuild. Perhaps something about your `tsconfig.json` file isn't making it through tsx to esbuild? That would need to be fixed by tsx.

**Comment by privatenumber** [comment]
Confirming it's an issue with tsx. Sorry about the oversight.

**Comment by evanw** [comment]
No problem!

**Comment by RobertAKARobin** [comment]
@privatenumber How did you end up resolving this?
