### ISSUE TITLE
[Question] Why treat required module with ExportKind::None as commonjs.

### ISSUE THREAD

**Issue by underfin** [evanw/esbuild#3498]
Here has file `foo`, code is like 

``` .ts
// foo.js
console.log()
```

If a entry `import` it, 
```.ts
// entry.js
import "./foo"
```
The result is 
```
// file.js
console.log(1);
```
Here is a playground linked https://esbuild.github.io/try/#YgAwLjE5LjYALS1idW5kbGUgLS1vdXRkaXI9Ii8iIC0tZm9ybWF0PWVzbSAtLXNwbGl0dGluZwBlAGVudHJ5LmpzAGltcG9ydCAnLi9maWxlJwAAZmlsZS5qcwBjb25zb2xlLmxvZygxKQ

But if I changed the entry `require` it, like this 
``` .ts
require('./foo')
```
The result will wrapped the `foo` to `__commonJs`.

The result is below.
```.ts
var require_file = __commonJS({
  "file.js"() {
    console.log(1);
  }
});

// entry.js
require_file();
```

Here has a playground for this question, see https://esbuild.github.io/try/#YgAwLjE5LjYALS1idW5kbGUgLS1vdXRkaXI9Ii8iIC0tZm9ybWF0PWVzbSAtLXNwbGl0dGluZwBlAGVudHJ5LmpzAHJlcXVpcmUoJy4vZmlsZScpAABmaWxlLmpzAGNvbnNvbGUubG9nKDEp

I'm not sure why wrapped the `foo` to `__commonJs` if someone `require` it, look like it shouldn't be wrapped for best performance. I just have question with it, hope someone can me out, thanks a lot.

**Comment by evanw** [comment]
One reason to do this is that `import` means the file is initialized at module instantiation time while `require` means the file is initialized dynamically at run-time. For example, this prints `1` and then `before`:

```js
// entry.js
console.log('before')
import './file'
```

While this prints `before` and then `1`:

```js
// entry.js
console.log('before')
require('./file')
```

The evaluation of `require` can even be non-deterministic such as with `if (Math.random() < 0.5) require('./file')`, which is not the case for `import` since `import` is syntactically forbidden from being inside a conditional branch.

I recognize that there is a special case where if there is one `require('./file')` at the top level of a module and the return value of `require()` is not used, then the module contents could be inlined into that special `require()` call (well, except for certain situations such as if the module contains a top-level return). Perhaps that is what you are asking about here. But esbuild doesn't currently implement that special case.

**Comment by underfin** [comment]
Thanks for detail description.
