### ISSUE TITLE
High Vulnerability in Go v1.20.10

### ISSUE THREAD

**Issue by pdutchnz** [evanw/esbuild#3543]
Can esbuild be rebuilt using v1.20.12? This will address recently publish vulnerabilities in go v1.20.10:
CVE-2023-45285 - https://nvd.nist.gov/vuln/detail/CVE-2023-45285
CVE-2023-39326 - https://nvd.nist.gov/vuln/detail/CVE-2023-39326

Mostly an issue for us because next.js packages esbuild into runtime containers for some reason.

Ref: https://go.dev/doc/devel/release#go1.20.minor:~:text=tracker%20for%20details.-,go1.20.12,-(released%202023%2D12

**Comment by pdutchnz** [comment]
Thanks mate, very quick!

**Comment by brian-swantide** [comment]
@evanw Is this change available in a published version of esbuild? Trying to fix this vulnerability, but it looks like 0.19.9 (latest) does not contain this fix?

**Comment by evanw** [comment]
There hasn't been a new esbuild version published since this change landed. I will publish a new esbuild version at some point.

Luckily esbuild is not a security-sensitive application and neither of these issues indicate a security vulnerability with esbuild, so whatever warnings you're getting about this are just noise and can be ignored. Specifically:

* CVE-2023-45285 has to do with using `go get` to fetch dependencies, which doesn't happen when you install esbuild on npm (the Go compiler doesn't even run at all).

* CVE-2023-39326 is about a HTTP server accepting a lot of data, but esbuild's dev server is not [intended to be run in production](https://esbuild.github.io/api/#serve:~:text=Do%20not%20use%20this%20in,%23) so you shouldn't be encountering this issue in a production environment the first place.

**Comment by chrisbjr** [comment]
Hi @evanw this is also being flagged as well by JFrog Xray when scanning our containers with esbuild inside. We can defend the vulnerabilities found with what you mentioned in your previous comment, but we have several projects with esbuild and it would be hard to defend all of it.

Would really appreciate if a build was published with Go v1.20.12 😃

Thanks @evanw!
