### ISSUE TITLE
Feature request: treeshaking of enums when declaration merging is present

### ISSUE THREAD

**Issue by jahorton** [evanw/esbuild#3555]
Referring to https://www.typescriptlang.org/docs/handbook/declaration-merging.html#merging-namespaces-with-classes-functions-and-enums, the following is perfectly legal TypeScript.

```
export enum Fruits {
  apples = 'apples',
  oranges = 'oranges',
  grapefruit = 'grapefruit'
}

export namespace Fruits {
  export function taste(item: Fruits) {
    switch(item) {
      case 'apples':
        return 'sweet';
      case 'oranges':
        return 'sour';
      case 'grapefruit':
        return 'bitter';
    }
  }
}
```

As far as I can tell, if this exists within the top-level project and `esbuild` treeshaking is enabled... all is fine, and this will fully treeshake out.

_**However**_ - add the following complications:

1. Create a separate project to act as a code library hosting this code.
    - Define an npm package, etc.
2. `export { Fruits } from './fruits.js'` in the "entry point" for the project in step 1.
3. Provide another export - say, a simple one-liner function.
4. Import the new library from the main top-level project.
5. Do not import `Fruits`, but do import that "one-liner function" from the library.
6. Run `esbuild` with bundling and treeshaking activated on the top-level project.

Result:  the code above fails to treeshake out despite being unused.  

----

To facilitate a simple repro:   [esbuild-import-treeshake-repro.zip](https://github.com/evanw/esbuild/files/13700570/esbuild-import-treeshake-repro.zip)

When unzipped...

1. In the base folder, run `npm install`.
2. `cd main`
3. `node build`
4. Inspect `main/build/index.js` and note that all code for `Fruits` is in the build product despite being 100% unreferenced.

Fun variations:
- Go into `dependency/src/merged-enum-namespace.ts` and comment out the `export namespace Fruits` section.  Treeshaking will then work.
- Comment out the `enum`, but not the `namespace`.  This will not treeshake out.  So, it's _probably_ something to do with `namespace`s.

If `merged-enum-namespace.ts` is ripped out of the `dependency` project and transplanted into `main`, but `Fruits` goes unused, `Fruits` will then fully tree-shake out.  (Try adding an unrelated small import to `merged-enum-namespace.ts` and import _only_ that from it within the `main/src/index.ts` entry-point, then rebuild.)

---

In case it matters, the "dependency's" export map setup - where a direct link to a `*.ts` file is provided - is based upon this comment:  https://github.com/evanw/esbuild/issues/1250#issuecomment-1463826174.  My actual project does use incremental `tsc -b` builds; we've got a monorepo setup.

**Comment by evanw** [comment]
Here is a link to a repro: [(link)](https://esbuild.github.io/try/#YgAwLjE5LjkALS1idW5kbGUAZQBtYWluL3NyYy9pbmRleC50cwBpbXBvcnQgeyBoZWxsbyB9IGZyb20gIm15LXJlcHJvLWRlcGVuZGVuY3kiOwpoZWxsbygpOwAAbm9kZV9tb2R1bGVzL215LXJlcHJvLWRlcGVuZGVuY3kvcGFja2FnZS5qc29uAHsKICAibWFpbiI6ICJidWlsZC9pbmRleC5qcyIsCiAgImV4cG9ydHMiOiB7CiAgICAiLiI6IHsKICAgICAgImltcG9ydCI6ICIuL3NyYy9pbmRleC50cyIsCiAgICAgICJkZWZhdWx0IjogIi4vYnVpbGQvaW5kZXguanMiCiAgICB9CiAgfQp9AABub2RlX21vZHVsZXMvbXktcmVwcm8tZGVwZW5kZW5jeS9zcmMvaW5kZXgudHMAZXhwb3J0IHsgaGVsbG8gfSBmcm9tICcuL3NpbXBsZS1mdW5jdGlvbi5qcyc7CmltcG9ydCB7IEZvbyB9IGZyb20gJy4vc3RhdGljLWlubmVyLWNsYXNzLmpzJzsKZXhwb3J0IHsgRnJ1aXRzIH0gZnJvbSAnLi9tZXJnZWQtZW51bS1uYW1lc3BhY2UuanMnOwoKZXhwb3J0IHsgRm9vIH07Ci8vIGxldCBhID0gbmV3IEZvbygpLnRlc3QoKTsKCi8vIGltcG9ydCB7IEZydWl0cyBhcyBGcnVpdCB9IGZyb20gJy4vbWVyZ2VkLWVudW0tbmFtZXNwYWNlLmpzJzsKLy8gRnJ1aXQudGFzdGUoRnJ1aXQuYXBwbGVzKTsAAG5vZGVfbW9kdWxlcy9teS1yZXByby1kZXBlbmRlbmN5L3NyYy9zaW1wbGUtZnVuY3Rpb24udHMAZXhwb3J0IGZ1bmN0aW9uIGhlbGxvKCkgewogIGNvbnNvbGUubG9nKCJIZWxsbyB3b3JsZCIpOwp9AABub2RlX21vZHVsZXMvbXktcmVwcm8tZGVwZW5kZW5jeS9zcmMvc3RhdGljLWlubmVyLWNsYXNzLnRzAC8vIC4uLiBoYXZlIG5vdCB5ZXQgZmlndXJlZCBvdXQgZXhhY3RseSB3aGVyZS93aHkvaG93IHRoZSBjYXNlIEkgc2F3IGluIG91ciBtYWluIHByb2R1Y3QgZGlkbid0IHRyZWVzaGFrZS4KLy8gU2VlbXMgdG8gaGF2ZSBoYWQgY29tcGxpY2F0aW5nLCBjbGFzcy1leHRlcm5hbCBmYWN0b3JzLgpleHBvcnQgY2xhc3MgRm9vIHsKICBwcml2YXRlIHN0YXRpYyBCYXIgPSBjbGFzcyBCYXIgewogICAgcHVibGljIHZhbHVlOiBTdHJpbmc7CgogICAgY29uc3RydWN0b3IodmFsdWU6IFN0cmluZykgewogICAgICB0aGlzLnZhbHVlID0gdmFsdWU7CiAgICB9CgogICAgdG9TdHJpbmcoKSB7CiAgICAgIHJldHVybiAiZm9vYmFyIjsKICAgIH0KCiAgICAqbGV0dGVycygpIHsKICAgICAgY29uc3QgYmFyID0gWydiJywgJ2EnLCAnciddOwogICAgICBmb3IobGV0IGxldHRlciBvZiBiYXIpIHsKICAgICAgICB5aWVsZCBiYXI7CiAgICAgIH0KICAgIH0KICB9CgogIHB1YmxpYyB0ZXN0KCkgewogICAgcmV0dXJuIG5ldyBGb28uQmFyKCJmb29iYXIiKTsKICB9Cn0AAG5vZGVfbW9kdWxlcy9teS1yZXByby1kZXBlbmRlbmN5L3NyYy9tZXJnZWQtZW51bS1uYW1lc3BhY2UudHMALy8gQWhhISAgTGltaXRhdGlvbiAxOgovLyBodHRwczovL3d3dy50eXBlc2NyaXB0bGFuZy5vcmcvZG9jcy9oYW5kYm9vay9kZWNsYXJhdGlvbi1tZXJnaW5nLmh0bWwjbWVyZ2luZy1uYW1lc3BhY2VzLXdpdGgtY2xhc3Nlcy1mdW5jdGlvbnMtYW5kLWVudW1zCi8vIGVzYnVpbGQgZmFsbHMgb3ZlciB3aGVuIGhhbmRsaW5nIHN1Y2ggbWVyZ2VyczsgaXQgYWJhbmRvbnMgYW55IGF0dGVtcHQgdG8gdHJlZXNoYWtlIGhlcmUuCmV4cG9ydCBlbnVtIEZydWl0cyB7CiAgYXBwbGVzID0gJ2FwcGxlcycsCiAgb3JhbmdlcyA9ICdvcmFuZ2VzJywKICBncmFwZWZydWl0ID0gJ2dyYXBlZnJ1aXQnCn0KCmV4cG9ydCBuYW1lc3BhY2UgRnJ1aXRzIHsKICBleHBvcnQgZnVuY3Rpb24gdGFzdGUoaXRlbTogRnJ1aXRzKSB7CiAgICBzd2l0Y2goaXRlbSkgewogICAgICBjYXNlICdhcHBsZXMnOgogICAgICAgIHJldHVybiAnc3dlZXQnOwogICAgICBjYXNlICdvcmFuZ2VzJzoKICAgICAgICByZXR1cm4gJ3NvdXInOwogICAgICBjYXNlICdncmFwZWZydWl0JzoKICAgICAgICByZXR1cm4gJ2JpdHRlcic7CiAgICB9CiAgfQp9)

This doesn't seem like a bug to me. Declaration merging involves mutating JavaScript objects at run-time, which crosses the threshold past which esbuild's tree-shaking analysis is attempted. Attempting to predict the run-time behavior of code that mutates JavaScript objects is outside of esbuild's scope. You will also observe the same result if you do something like this, which is essentially the same code:

```js
var Fruits = {
  apples: 'apples',
  oranges: 'oranges',
  grapefruit: 'grapefruit'
}

Fruits.taste = function(item: Fruits) {
  switch(item) {
    case 'apples':
      return 'sweet';
    case 'oranges':
      return 'sour';
    case 'grapefruit':
      return 'bitter';
  }
}
```

I recommend using normal functions instead of enum declaration merging if you want tree-shaking to work.

**Comment by evanw** [comment]
I'm closing this issue as I don't plan to do this. This seems out of scope to me.
