### ISSUE TITLE
After the build is completed, the esbuild process does not exit

### ISSUE THREAD

**Issue by peakchen90** [evanw/esbuild#3558]
When I use `esbuild.build` api to build, the node process does not exit, but esbuild cannot exit either.

**The reproduce code**:
```js
const esbuild = require('esbuild');

(async () => {
  await esbuild.build({
    entryPoints: ['./src'],
  });

  console.log(' >>> done');
})();

setTimeout(() => {
  // keep running...
}, 10000000);

```

**The terminal output screenshot**:
<img width="330" alt="image" src="https://github.com/evanw/esbuild/assets/17677589/4993b5f5-36e0-4851-8aa5-4cc874462114">

**The MacOS monitor screenshot**:
<img width="736" alt="image" src="https://github.com/evanw/esbuild/assets/17677589/c96b741a-7a50-4705-90c9-ff44a6deee12">

I discovered this problem because my team member reported that running esbuild watch mode used 54G of memory on his computer.
![image](https://github.com/evanw/esbuild/assets/17677589/6631471c-b6ad-4391-a73f-3423cbfd22da)

**Comment by evanw** [comment]
> ```js
> setTimeout(() => {
>   // keep running...
> }, 10000000);
> ```

This is why your node process keeps running. That is not surprising.

Once activated, the esbuild process stays around until node exits (for performance reasons), but should not keep node open due to how node's child process reference counting works.

If you have a way to reproduce either the problem of esbuild keeping node open, or of esbuild using >50gb of memory, then please provide it here. In the meantime I'm marking this issue as `unactionable` because there's nothing I can do with it.

**Comment by anatoliyarkhipov** [comment]
I have a similar problem: after building I start `express` to host the built files (it's a production script):

```
  await esbuild.build(config)
  express().use("/media", express.static("media")).listen(3002)
```

And the process consumes a bunch of memory:

![image](https://github.com/evanw/esbuild/assets/1934180/19151b7d-4c0d-4b94-9c0e-849a1be215ed)

The more entry-points I had the more memory is consumed.

I tried to start only express, just in case, and it takes around 30mb.

**Comment by peakchen90** [comment]
@evanw  Is it possible to implement an api that can manually exit the esbuild child process, because I will only run `esbuild.build` once, and then never run it again, and it keeps using memory?

**Comment by evanw** [comment]
Yes. There used to be an API for this but it was removed after #656 was implemented as it was not necessary (see [version 0.9.0](https://github.com/evanw/esbuild/releases/v0.9.0)). However, the Deno API for esbuild currently does have a `stop()` function because Deno (at least at the time) didn't have a way to allow child processes to exit automatically when the parent process exits. So I can consider putting `stop()` back for the node API as well.

However, it would still be good to have a way to reproduce esbuild using >50gb of memory. That sounds like a bug unless you're doing something unusual with esbuild.

**Comment by peakchen90** [comment]
@evanw OK, thanks a lot.

I use esbuild to pre-build the node_modules code, and then compile the source code (src) with webpack. The usage code in watch mode is as following:

```ts
const ctx = await esbuild.context(buildOptions);
await ctx.watch(); 
```

And I cannot reproduce  esbuild useing more than 50G of memory (in my computer), so I want to avoid this problem by exiting esbuild manually.

**Comment by caramboleyo** [comment]
on deno the stop function does nothing
weird subprocesses remain forever (i also only need it once at startup)
