### ISSUE TITLE
Reserved functions name

### ISSUE THREAD

**Issue by krishneup** [evanw/esbuild#3572]
Hi, I am trying to switch from webpack to esbuild. First of all, this looks really good tooling project and thanks for creating this wonderful piece.

This may be a lot of ask for in a open source support, but would like to know if I can tell esbuild about my reserve functions and ask esbuild not to modify those function names:

`new TerserPlugin({
  terserOptions: {
    mangle: {
      reserved: ['__', '_n', '_nx', '_x'],
    },
})`

Thanks in advance.

**Comment by evanw** [comment]
There is no such feature. It can be impossible to make such a guarantee with all of esbuild's behavior (bundling, syntax lowering, optimizing, etc.) due to certain edge cases involving name collisions and/or syntax transformations.

However, you may use https://esbuild.github.io/api/#keep-names if you want to preserve the value of the `.name` property on the function. That is a guarantee that esbuild does offer.

**Comment by krishneup** [comment]
Thank you for response.
