### ISSUE TITLE
Esbuild.transform within Next.js Server Action

### ISSUE THREAD

**Issue by kaimou1357** [evanw/esbuild#3573]
I'm currently trying to use esbuild to transform JSX code -> Javascript code. The pattern I am using is to have some React client component use onClick -> hit the next.js server component/function with input: JSX and output: JS.

actions.tsx (file)
```
'use server'
import * as esbuild from 'esbuild'
import { TransformResult, TransformOptions} from 'esbuild';
export async function convertCode<T extends TransformOptions>(code: string): Promise<TransformResult<T>> {
  return await esbuild.transform(`export default ${code}`, {
    loader: "jsx",
    target: "es2015",
    format: "iife",
    globalName: "MyApp",
  });
}
```

(Please excuse my types - the code above does not build due to the return of the types not being correct ( I am new to Typescript).

However, the problem throws from the server side:

```
 node_modules/esbuild/lib/main.js (1982:10) @ esbuildCommandAndArgs
 ⨯ Error: The esbuild JavaScript API cannot be bundled. Please mark the "esbuild" package as external so it's not included in the bundle.

More information: The file containing the code for esbuild's JavaScript API (/Users/kaimou/Code/IterativeNext/.next/server/vendor-chunks/esbuild.js) does not appear to be inside the esbuild package on the file system, which usually means that the esbuild package was bundled into another file. This is problematic because the API needs to run a binary executable inside the esbuild package which is located using a relative path from the API code to the executable. If the esbuild package is bundled, the relative path will be incorrect and the executable won't be found.
    at convertCode (./src/app/tool/actions.tsx:15:55)
```

When I check my node_modules folder itself, the esbuild directory is definitely already in there. I did see some documentation on marking esbuild as external but I only saw it from the command line options. How do I mark this as external for the NextJS server runtime? (which I assume is NodeJS)?

Are there any examples of esbuild running within NextJS?

**Comment by kaimou1357** [comment]
The interesting thing is here that running a console.log(esbuild.version) does seem to run properly so it seems like it's a problem of Next.JS not recognizing the binary within Node Modules?

**Comment by kaimou1357** [comment]
Is a possible way to "bundle" the executable to move the executable to a public static directory and have the server reference it that way? Is there a way to set where the executable is being fetched from?

**Comment by evanw** [comment]
I have no idea how Next.js works, sorry. You may need to ask them how to do this instead. The only environments that esbuild's API supports are Node, Deno, Go, and the browser: https://esbuild.github.io/getting-started/. Perhaps the way to ask them for help is here? https://github.com/vercel/next.js/issues

If Next.js is some Node-like environment then it may be possible to do this, but if Next.js somehow bundles your code before running it (which it sounds like it does from the error message) then you'll need to figure out how to disable that to be able to use esbuild's API. This is because esbuild's API doesn't work when bundled (since it uses relative file paths to find the executable). There is an undocumented way to override esbuild's executable path by setting the `ESBUILD_BINARY_PATH` environment variable. Perhaps that might work in your situation as well.

**Comment by kaimou1357** [comment]
Got it - yeah in my case - I couldn't find a workaround here so I had to use a node.js serverless endpoint to actually do the transform()
