### ISSUE TITLE
Dynamic method names prevent tree shaking

### ISSUE THREAD

**Issue by quentinadam** [evanw/esbuild#3589]
Using dynamic class method names prevents the class to be discarded by tree shaking when it is not used.

Example:

```js
// input.js

const method = 'name';

class A {
  greet() {
    console.log('hello from A');
  }
  
  [method]() {
    return 'A';
  }
}

class B {
  greet() {
    console.log('hello from B');
  }
}

new B().greet();
```

I have tried to add various `/* @__PURE__ */` annotations, but the class A does not get tree shaken.
The above example is deliberately simple to demonstrate the issue, but the context where it came from is that any class that declares a custom inspect function like below prevents treeshaking:

```js
[Symbol.for('nodejs.util.inspect.custom')]() {
  return '...';
}
```

Here is a link to the playground to reproduce the issue.
https://esbuild.github.io/try/#dAAwLjE5LjExAC0tdHJlZS1zaGFraW5nPXRydWUAY29uc3QgbWV0aG9kID0gJ21ldGhvZCc7CgpjbGFzcyBBIHsKICBncmVldCgpIHsKICAgIGNvbnNvbGUubG9nKCdoZWxsbyBmcm9tIEEnKTsKICB9CiAgCiAgW21ldGhvZF0oKSB7CiAgICByZXR1cm4gJ0EnOwogIH0KfQoKY2xhc3MgQiB7CiAgZ3JlZXQoKSB7CiAgICBjb25zb2xlLmxvZygnaGVsbG8gZnJvbSBCJyk7CiAgfQp9CgpuZXcgQigpLmdyZWV0KCk7

**Comment by evanw** [comment]
> I have tried to add various `/* @__PURE__ */` annotations, but the class A does not get tree shaken.

The way to add a `@__PURE__` annotation for the class `A` is as follows:

https://esbuild.github.io/try/#dAAwLjE5LjExAC0tdHJlZS1zaGFraW5nPXRydWUAY29uc3QgbWV0aG9kID0gJ21ldGhvZCc7CgpsZXQgQSA9IC8qIEBfX1BVUkVfXyAqLyAoKCkgPT4gY2xhc3MgewogIGdyZWV0KCkgewogICAgY29uc29sZS5sb2coJ2hlbGxvIGZyb20gQScpOwogIH0KICAKICBbbWV0aG9kXSgpIHsKICAgIHJldHVybiAnQSc7CiAgfQp9KSgpCgpjbGFzcyBCIHsKICBncmVldCgpIHsKICAgIGNvbnNvbGUubG9nKCdoZWxsbyBmcm9tIEInKTsKICB9Cn0KCm5ldyBCKCkuZ3JlZXQoKTs

You cannot add the pure annotation to the `method` variable reference like [this](https://esbuild.github.io/try/#dAAwLjE5LjExAC0tdHJlZS1zaGFraW5nPXRydWUAY29uc3QgbWV0aG9kID0gJ21ldGhvZCc7CgpjbGFzcyBBIHsKICBncmVldCgpIHsKICAgIGNvbnNvbGUubG9nKCdoZWxsbyBmcm9tIEEnKTsKICB9CiAgCiAgWy8qQF9fUFVSRV9fKi8gKCgpID0+IG1ldGhvZCkoKV0oKSB7CiAgICByZXR1cm4gJ0EnOwogIH0KfQoKY2xhc3MgQiB7CiAgZ3JlZXQoKSB7CiAgICBjb25zb2xlLmxvZygnaGVsbG8gZnJvbSBCJyk7CiAgfQp9CgpuZXcgQigpLmdyZWV0KCk7) because that's annotating the wrong thing. The `@__PURE__` annotation says the result can be removed if it's not used. Except it is being used (as the name of the method) so the annotation doesn't have any effect. That's why it has to go around the whole class declaration. Another way to think about it: Just because the evaluation of the expression `method` has no side effects doesn't necessarily mean the evaluation of the ToString operation on that value also has no side effects.

> The above example is deliberately simple to demonstrate the issue, but the context where it came from is that any class that declares a custom inspect function like below prevents treeshaking:
> 
> ```js
> [Symbol.for('nodejs.util.inspect.custom')]() {
>   return '...';
> }
> ```

I appreciate you mentioning the actual use case. It's possible that esbuild could special-case this syntax to still allow tree shaking in this case.

**Comment by quentinadam** [comment]
Thank you ! I appreciate you taking the time to explain the correct way to place the /* @__PURE__ */ annotation !

**Comment by quentinadam** [comment]
Would there be any plans to allow ESBuild to special-case this syntax (when using custom inspect functions like `[Symbol.for('nodejs.util.inspect.custom')]()` or `[Symbol.for('Deno.customInspect')]()`) to still allow tree shaking in this case?

```ts
export class A {

  greet() {
    console.log('hello from A');
  }

  static hello(): void {
     console.log("static hello");
  } 

  [Symbol.for("nodejs.util.inspect.custom")]() {
    return 'A';
  }
}
```

I appreciate that the the IIFE syntax below is a workaround.

```ts
export const A = /* @__PURE__ */ (() => class {

  greet() {
    console.log('hello from A');
  }

  static hello(): void {
    console.log("static hello");
  } 

  [Symbol.for("nodejs.util.inspect.custom")]() {
    return 'A';
  }
})()
```

However this syntax is causing other unrelated problems. I am authoring a TS package for the [JSR registery](https://jsr.io/), which requires all exported symbols to have explicit types. When using the IIFE definition of the class, and in order to explicitly define all exported types, you would need to add explicit interface definitions which ends up being quite verbose compared to the initial class definition:

```ts
export interface A {
  greet(): void;
}

export type AConstructor = {
  new(): A;
  hello(): void;
};

export const A: AConstructor = /* @__PURE__ */ (() =>
  class implements A {
    greet(): void {
      console.log("hello from A");
    }

    static hello(): void {
      console.log("static hello");
    } 

    [Symbol.for("nodejs.util.inspect.custom")](): string {
      return "A";
    }
  }
)()
```
