### ISSUE TITLE
jsx set to "preserve" still applies transforms to JSX 

### ISSUE THREAD

**Issue by martypdx** [evanw/esbuild#3605]
[Working reproduction](https://esbuild.github.io/try/#dAAwLjE5LjExAHsKICBsb2FkZXI6ICdqc3gnLAogIGpzeDogJ3ByZXNlcnZlJywKfQA8bGk+SGVsbG8geyd3b3JsZCd9Pz88L2xpPg)

Esbuild with these inputs:

- option: `jsx: 'preserve, loader: 'tsx'`
- transform jsx that contains JsxText AST Nodes:
    ```jsx
    <li className={"item"}>Hello {world}??</li>
    ```

Expected output is that jsx is "preserved" as-is:

```jsx
    <li className={"item"}>Hello {'world'}??</li>
```

Actual output transforms JSXText to JSXExpressionContainer (and removes JSXExpressionContainer from literal attirbute. Also introducing additional formatring which has downstream effect of introducing additional text nodes:

```jsx
<li className="item">
  {"Hello "}
  {world}
  {"??"}
</li>;
```

(LMK if I am just missing another setting!)

AFAICT, [here is where the transform is applied](https://github.com/evanw/esbuild/blob/a652e730ff07b9081470ef6965f3d54daa7b2aab/internal/js_printer/js_printer.go#L2214-L2251).

IMO `jsx: 'preserve'` should not make any JSX transforms that would result in a different JSX AST being produced from the output what was produced for the jsx from the source. 

Happy to help with test/PR if needed.

**Comment by martypdx** [comment]
I created the [same jsx transform in tsc compiler with jsx preserve](https://www.typescriptlang.org/play?noImplicitAny=false&target=99&jsx=1#code/DwGwlgBAxiCGDO8BysC2BTAvAbwERgBd1VcBfAPgAl0QQB7CPAdzoCcQATMgfm+AHpw5IA). 

tsc does seem to be [significant whitespace aware](https://www.typescriptlang.org/play?noImplicitAny=false&target=99&jsx=1#code/MYewdgzgLgBAVhAHjAvDAPAGwJYwFAyEzCYCGEEAcqQLYCmKA3gETZR03MC+AfAUQAk6mTCBgsA7iABOmACbcA-PyKq161ctXoA9Dh5A). They probably take the approach of outputting the raw value from the AST for JSXText nodes.

Is there an opportunity to skip JSX generation entirely for preserve mode and somehow splice in the jsx segments into the output from the AST locations?

**Comment by evanw** [comment]
> IMO `jsx: 'preserve'` should not make any JSX transforms that would result in a different JSX AST being produced from the output what was produced for the jsx from the source.

The reason this is happening is because esbuild is parsing JSX into an AST and then printing it back out. In other words, the ASTs that esbuild makes for both the input and the output are exactly the same, just printed differently. You can see here that both the input and the output are equivalent when transformed into JS: [(link)](https://esbuild.github.io/try/#dAAwLjE5LjExAHsKICBsb2FkZXI6ICdqc3gnLAogIGpzeDogJ3RyYW5zZm9ybScsCn0AYSA9IDxsaSBjbGFzc05hbWU9eyJpdGVtIn0+SGVsbG8ge3dvcmxkfT8/PC9saT4KYiA9IDxsaSBjbGFzc05hbWU9Iml0ZW0iPgogIHsiSGVsbG8gIn0KICB7d29ybGR9CiAgeyI/PyJ9CjwvbGk+)

You haven't described an actual problem you are having. Why is this a problem for you?

**Comment by martypdx** [comment]
Sure thing! I am applying an ahead-of-time compile transformation to JSX directly after the esbuild step in vite. It's not a vdom-based architecture and so the factory generation pattern doesn't fit. So my problem is I need accurate jsx so I can can do the correct generation.

It works great to have esbuild handle the typescript to jsx conversion, then I use acorn+jsx parser to get the ast and handle the custom generation, hmr, etc. It would be great to have a hook directly into esbuild JSX AST --> js generation, but this is the next best thing for a fast compilation pipeline.

After I filled this issue, I somehow got the configuration such that it started outputting correct jsx, but then something changed and I couldn't reproduce it. Honestly, I thought I somehow missed this but now I feel it might be a recent change to config. I'll see if I can reliably reproduce. Are there configurations in which the jsx would be fully preserved?

**Comment by evanw** [comment]
I see. My intuition as a developer is that those two cases would be equivalent since I'd expect any relevant optimizations to be applied regardless of how the source code was written (e.g. `<a href={foo}/>` may become `<a href={"inline string"}/>` after an optimizer inlines it which I'd expect to be just as optimized as `<a href="inline string"/>`).

But I can still see an argument for changing esbuild's behavior here. The intent behind the word "preserve" is "doesn't change" and if someone wants to make `<a href="inline string"/>` mean something different than `<a href={"inline string"}/>`, esbuild shouldn't get in your way. The [JSX specification](https://facebook.github.io/jsx/) deliberately doesn't specify how JSX is to be interpreted so pretty much anything goes. I'll make this change to esbuild.

One random caveat with this is that the [`charset`](https://esbuild.github.io/api/#charset) setting will no longer affect the content of JSX text if JSX text is now reproduced verbatim. This seems fine though since the purpose of the `charset` setting is to work around with servers not setting the encoding correctly and JSX needs another transform before being served anyway, so the responsibility of the encoding workaround lies with that additional tool instead of with esbuild.

**Comment by martypdx** [comment]
> My intuition as a developer is that those two cases would be equivalent since I'd expect any relevant optimizations to be applied regardless of how the source code was written (e.g. <a href={foo}/> may become <a href={"inline string"}/> after an optimizer inlines it which I'd expect to be just as optimized as <a href="inline string"/>).

Intuition shaped by vdom architecture. 😁  For a render-once architecture you want to offload as much into the static initial html because then it is processed by the browser at not the library/fw. `<div>some text here</div>` to `<div>{'some text here'}</div>` is vastly different because the former is inlined into html that the browser handles whereas the later has to be managed via javascript by the library/framework. The attribute example you gave _would_ be a good optimization because it would make the attribute part of the clonable structure of the html template.

I was really impressed with how well esbuild does static optimization and inlining. It was hard to make a test case to "fool" it into outputting variables instead of static text. Even module boundaries are no obstacle! I am going to look at using that capability to try and "bundle" trees of components into equivalent single components.
