### ISSUE TITLE
Are we implementing node esm/cjs interop correctly

### ISSUE THREAD

**Issue by robert-melonn** [evanw/esbuild#3654]
After diging in node documentation, about cjs/esm interop and also facing issue when isNodeMode === 1 (__toESM is wrapping up the required module with a default property, even this module is a ESM transpiled to cjs with a export default statement). I realise that could be something wrong with the implementation of this wrapper.
Because [in this section from node esm modules](https://nodejs.org/api/esm.html#commonjs-namespaces) explains that when there is a 
`import cjs from "cjs"
 console.log(cjs) // this value will be equals to module.exports
`
and ONLY when the code is
`import * as cjs from cjs
console.log(cjs)// value will be {default: <module.exports>}
` 

it should be wrapped in a default property.

But as I notice in esbuild outputs if I use default import the require is wrapped with __toESM() along with isNodeMode = 1, when according to above examples and node docs, this condition ONLY should be applied when we are using import start or import namespace form.

I would like to get any response about this thought, because I need to find a right way to handle esm/cjs interop. Let me know if I m wrong . Thank you

**Comment by hyrious** [comment]
> But as I notice in esbuild outputs if I use default import the require is wrapped with __toESM() along with isNodeMode = 1

[That is not true.](https://esbuild.github.io/try/#YgAwLjIwLjAALS1idW5kbGUgLS1mb3JtYXQ9ZXNtAGUAZW50cnkuanMAaW1wb3J0IGNqcyBmcm9tICcuL2Nqcy5qcycAAGNqcy5qcwBleHBvcnRzLmEgPSAx)

In fact `isNodeMode` is not related to the style of import statement. This value is determined by these contexts:

- [Whether the ESM file ends with `.mjs`.](https://esbuild.github.io/try/#YgAwLjIwLjAALS1idW5kbGUgLS1mb3JtYXQ9ZXNtAGUAZW50cnkubWpzAGltcG9ydCB7YX0gZnJvbSAnLi9janMuanMnCmYoYSkAAGNqcy5qcwBleHBvcnRzLmEgPSAx) Because the extension was implemented by Node.js to distinguish different module syntaxes. So if the author write this extension, he has the expectation to run this code with Node.js style ESM behavior.
- [Whether the package.json has `"type": "module"`](https://esbuild.github.io/try/#YgAwLjIwLjAALS1idW5kbGUgLS1mb3JtYXQ9ZXNtAGUAZW50cnkuanMAaW1wb3J0IHthfSBmcm9tICcuL2Nqcy5janMnCmYoYSkAAGNqcy5janMAZXhwb3J0cy5hID0gMQAAcGFja2FnZS5qc29uAHsidHlwZSI6Im1vZHVsZSJ9). The reason is the same as above.

**Comment by robert-melonn** [comment]
Ok yes you right, if i set type module or use a .mjs file I m gonna get isNodeMode, [that s true](https://esbuild.github.io/try/#YgAwLjIwLjAALS1idW5kbGUgLS1mb3JtYXQ9ZXNtAGUAZW50cnkubWpzAGltcG9ydCBjanMgZnJvbSAnLi9janMuanMnCmNvbnNvbGUubG9nKGNqcykAAGNqcy5qcwBleHBvcnRzLmEgPSAxCmV4cG9ydHMuZGVmYXVsdCA9IDIgLy8gaW1hZ2luZSB0aGlzIGlzIGEgdHJhbnNwaWxlZCBlc20). But my point here is even isNodeMode be = 1, currently the behavior its the same for import default style and import namespace style. And that's incorrect. If I use import x from "x", I shouldnt get {default: module.exports}, I should get  module.exports

**Comment by evanw** [comment]
> But as I notice in esbuild outputs if I use default import the require is wrapped with __toESM() along with isNodeMode = 1, when according to above examples and node docs, this condition ONLY should be applied when we are using import start or import namespace form.

Different import forms are not supposed to result in different behavior. The following three import statements should all do exactly the same thing:

```js
import foo_default1 from 'foo'
import { default as foo_default2 } from 'foo'
import * as foo from 'foo'

console.log(
  foo_default1,
  foo_default2,
  foo.default
)
```

These are just three different syntaxes for doing the same import operation (importing the export named `default` from the module `foo`). They shouldn't behave differently from each other.
