### ISSUE TITLE
esbuild fails to bundle MUI (Material UI)

### ISSUE THREAD

**Issue by nelsonjr** [evanw/esbuild#3655]
I am moving from Webpack to Esbuild. I have a library that exports a component that uses Material UI.

I created a repro library and project to demonstrate. The bundle works without MUI but fails with MUI. The repro demonstrates both.

https://github.com/nelsonjr/repro-esbuild-mui-crash

Any help is much appreciated. Thanks for a fantastic (and fast!) bundler.

PS: The same problem seems to happen with React Bootstrap as well.

**Comment by hyrious** [comment]
That was because you have 2 copies of `react` in your local dependencies tree:

```
~>: resolves to

app/index.tsx
	import 'react' ~> node_modules/.pnpm/react@18.2.0/node_modules/react/index.js
	import 'my-lib/button1' ~> ../lib/dist/button1/index.js

../lib/dist/button1/index.js
	import 'react' ~> ../lib/node_modules/.pnpm/react@18.2.0/node_modules/react/index.js
```

It happens because `pnpm link` creates a symlink (instead of a hard link) to the source of the package. See https://pnpm.io/cli/link#whats-the-difference-between-pnpm-link-and-using-the-file-protocol. When esbuild saw a symlink, it follows the link to the real file and performs further resolving there.

Just like the link above said, you can use the `file:` protocol to create a hard link:

```json
"my-lib": "file:../lib/dist",
```

In which case the `app/node_modules/my-lib/*` are normal files (in the view of bundlers), so that esbuild can resolve to the same `react` in `app/node_modules`.

One downside (and that's why pnpm does not by default create hard links) of `file:` is that, hard links does not always reflect the distination's status. When there's file creates/removed, it cannot automatically update itself, where you have to run `pnpm i` again.

**Comment by nelsonjr** [comment]
Thanks, @hyrious! That resolved the problem in the repro. I will try in the actual code now.

Do you mind sharing what command you used to produce the output dependencies? I tried with `pnpm ls --long`, but they did not render that critical information.

**Comment by hyrious** [comment]
> Do you mind sharing what command you used to produce the output dependencies?

You can enable the [metafile](https://esbuild.github.io/api/#metafile) option in esbuild and drop that file at [Bundler Size Analyzer](https://esbuild.github.io/analyze/), from which you may find possible duplicate dependencies:

<img width="630" alt="image" src="https://github.com/evanw/esbuild/assets/8097890/7dcce263-f479-4c9a-8f83-01855e93f62b">

However, in fact I wrote the above comment without looking at the metafile. I just looked at the build/index.js and searched for `/react@` in the bundled code. esbuild writes `// path/to/source.js` comments in un-minified build results, so it was very fast and easy for me to find the duplicate problem (which is also a common issue in dealing with react related things).
