### ISSUE TITLE
Swagger won't load after building the app

### ISSUE THREAD

**Issue by ezeamin** [evanw/esbuild#3660]
Swagger is configured in an Express server project. During development (script `pnpm dev`) runs fine, but when building the app, it fails to load with the following errors: 

![image](https://github.com/evanw/esbuild/assets/82628932/7be08554-b1d0-405d-9416-94482adb2ddc)

A minimal reproduction can be found here: https://github.com/ezeamin/esbuild-swagger-test

Swagger URL can be found on the console logs when app is run, either with `pnpm dev` or `pnpm start`. Same behaviour with npm or other package managers.

Environment:
Windows 11
Chrome 121.0.6167.185
Node 21.2.0

**Comment by evanw** [comment]
Hello! I'm not sure why this happens as I have not debugged your code for you. But if I follow esbuild's [getting started instructions for node](https://esbuild.github.io/getting-started/#bundling-for-node) and add `--packages=external` then it seems to run correctly. Does that work for you?

**Comment by ezeamin** [comment]
Hi @evanw! Thanks for your quick response. It did indeed work setting `--packages=external`, but I wanted to bundle all my dependencies in the same file. I can work like this though, not something urgent. Thanks again!

**Comment by evanw** [comment]
If you add `--log-level=debug` then you'll see the following log messages:

```
● [DEBUG] This call to "require" will not be bundled because the argument is not a string literal [unsupported-require-call]

    node_modules/.pnpm/swagger-jsdoc@6.2.8_openapi-types@12.1.3/node_modules/swagger-jsdoc/src/utils.js:112:24:
      112 │   const loadCjs = () => require(resolvedPath);
          ╵                         ~~~~~~~

● [DEBUG] This call to "require" will not be bundled because the argument is not a string literal [unsupported-require-call]

    node_modules/.pnpm/express@4.18.2/node_modules/express/lib/view.js:81:13:
      81 │     var fn = require(mod).__express
         ╵              ~~~~~~~
```

These are likely the reason why the `express` and/or `swagger-jsdoc` packages are not bundler-friendly. Unfortunately it's generally not possible to bundle packages that are not bundler-friendly. So I'm closing this issue as esbuild is working as expected.

In case you are wondering: These are debug messages instead of warning messages because esbuild tries to reserve warnings for things that are very likely to be real issues, and enough packages use `require` like this for optional/non-essential things that there are too many false-positives for this to be a warning by default.
