### ISSUE TITLE
Transform resolving always true/always false expressions

### ISSUE THREAD

**Issue by shyguy1412** [evanw/esbuild#3661]
The transform function esbuild provides resolves expressions that are guranteed to be a certain value into that value. 
so
```js
!"string"
```
will always be transformed into 
```js
false
```

I recognize that this is expected behaviour, I just couldnt find anything about this optimization in the documentation.
I currently have a project where I actually prefer if this doesnt happen. Is there any way to prevent this or do I have to look into a different transformer for this?

**Comment by evanw** [comment]
> I actually prefer if this doesnt happen

Why is that?

> Is there any way to prevent this or do I have to look into a different transformer for this?

No, there currently isn't. You'd have to look into a different transformer for this.

**Comment by shyguy1412** [comment]
Its not actually a serious project, so I dont expect any more support on this.
I created a plugin for esbuild that implements operator overloading by adding symbols to an object. The Idea is that you can have a piece of code like this 
```js
import OperatorSymbols from "OperatorSymbols";
String.prototype[OperatorSymbols['!']] = (v) => v.toLocaleUpperCase();

console.log(!"hello world!")
```
Which would capitilize the string and print `HELLO WORLD!`.

Since I want this plugin to accept js, ts, jsx and tsx I use esbuilds transform before parsing the code to AST and doing all the magic that actually makes this work. Unfortunately, this has the side effect of not working well with literals due to this optimization.

This is obviously just for fun and not meant to be used in any real codebase, so I dont expect esbuild to accomodate my needs here. Still would have been fun if it was possible!

**Comment by evanw** [comment]
FWIW this is straightforward to do without language changes. Something like this perhaps:

```js
const up = (...x) => String.raw(...x).toLocaleUpperCase()
console.log(up`hello world!`)
```

Although maybe that's not fun anymore. In any case, your original request is for a language that esbuild doesn't support (i.e. one that doesn't behave like JavaScript), so I don't plan to support this. If you are doing AST transformations that don't follow [the JavaScript specification](https://tc39.es/ecma262/) then esbuild is almost certainly not the best tool to be using, as it wasn't designed for that.

In case you're curious: The limited constant folding that esbuild does do when minification is disabled is intentional, and is important for correctly handling certain libraries. In particular, React has a strange entry point that a) expects bundlers to substitute `process.env.NODE_ENV` and b) expects bundlers to do some limited constant folding to determine which sub-entry point to load. The slightly more general way to do that instead of special-casing things exactly for React is to do what esbuild does now, which is to do limited constant folding within expressions. This is a practical thing to allow esbuild to determine dead paths earlier on in the bundling process to avoid needing to unnecessarily process both paths of statically-determined if statements, which can be quite expensive if they contain `require()` calls that don't need to be followed.

**Comment by shyguy1412** [comment]
I realise there are many ways to achieve what I want in my example, but it was more specifically about the actual operator overloading.  
Either way, it is exactly as you said. This is something outside of the scope of what esbuild is supposed to be capable of.  
Thanks for taking the time to explain to me the exact reason too, that is genuinly good to know. esbuild is a great tool and you (+contributors) do great work!
