### ISSUE TITLE
Tree shaking or minifier issue - noop functions

### ISSUE THREAD

**Issue by nikitaeverywhere** [evanw/esbuild#3676]
Hello! Thanks for the great lib.

It's not enough in my case to just cut out `console.log`s from the built script (I build a few versions of script, depending on the environment). Let's say, I have a more sophisticated logger function, and the only way to "cut its usages" from the production bundle, to my understanding, is using `define`.

`index.js`

```ts
const CONST_1 = 'ok';
const CONST_UNUSED = 'well';

const log = (data: string) => {
  if (DEBUG) {
    console.log(data);
  }
};

log(CONST_1);
```

`build.js`

```js
import { build } from 'esbuild';

await build({
  logLevel: 'info',
  entryPoints: ['src/index.ts'],
  outfile: './lib/index.js',
  bundle: true,
  sourcemap: true,
  treeShaking: true,
  minify: false,
  format: 'iife',
  define: {
    DEBUG: 'false',
  },
});
```

`node build.js` output:

![image](https://github.com/evanw/esbuild/assets/4989256/c6a751cf-52f1-40af-9d95-6ecf08ba3161)

Expectation: no dead code

Reality: dead code

Indeed, if I use `minify: true`, the result is a bit better

```js
"use strict";(()=>{var o="ok";var t=l=>{};t(o);})();
```

But then there's an issue with minifier: it doesn't understand that the function is noop and should be removed.

Is there any way to achieve removing dead code in my case?

I understand there's an alternative: to write if statements all across my source code in this way:

```ts
import { log } from './module';

if (DEBUG) {
  log(...);
}
```

But this doesn't look nice; for instance, on a large codebase, someone can forget to wrap logging with `if`.

P.S. I understand if the library is mostly designed to be "simple", but due to this fact I need to use it in conjunction with other JS compilers like Closure Compiler, or switch away from it completely.

**Comment by evanw** [comment]
The result with `function` instead of an arrow function does work: [(link)](https://esbuild.github.io/try/#YgAwLjIwLjEAewogIGxvZ0xldmVsOiAnaW5mbycsCiAgZW50cnlQb2ludHM6IFsnc3JjL2luZGV4LnRzJ10sCiAgb3V0ZmlsZTogJy4vbGliL2luZGV4LmpzJywKICBidW5kbGU6IHRydWUsCiAgc291cmNlbWFwOiB0cnVlLAogIHRyZWVTaGFraW5nOiB0cnVlLAogIG1pbmlmeTogdHJ1ZSwKICBmb3JtYXQ6ICdpaWZlJywKICBkZWZpbmU6IHsKICAgIERFQlVHOiAnZmFsc2UnLAogIH0sCn0AAHNyYy9pbmRleC50cwBjb25zdCBDT05TVF8xID0gJ29rJzsKY29uc3QgQ09OU1RfVU5VU0VEID0gJ3dlbGwnOwoKZnVuY3Rpb24gbG9nKGRhdGE6IHN0cmluZykgewogIGlmIChERUJVRykgewogICAgY29uc29sZS5sb2coZGF0YSk7CiAgfQp9Cgpsb2coQ09OU1RfMSk7). Inlining of no-op functions currently only happens for `function` because initialization of function declarations is hoisted, which avoids [TDZ issues](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#temporal_dead_zone_tdz), while `const` initialization happens inline, which introduces TDZ issues that could make it incorrect to always inline calls to that function.

**Comment by nikitaeverywhere** [comment]
> The result with function instead of an arrow function does work: [(link)](https://esbuild.github.io/try/#YgAwLjIwLjEAewogIGxvZ0xldmVsOiAnaW5mbycsCiAgZW50cnlQb2ludHM6IFsnc3JjL2luZGV4LnRzJ10sCiAgb3V0ZmlsZTogJy4vbGliL2luZGV4LmpzJywKICBidW5kbGU6IHRydWUsCiAgc291cmNlbWFwOiB0cnVlLAogIHRyZWVTaGFraW5nOiB0cnVlLAogIG1pbmlmeTogdHJ1ZSwKICBmb3JtYXQ6ICdpaWZlJywKICBkZWZpbmU6IHsKICAgIERFQlVHOiAnZmFsc2UnLAogIH0sCn0AAHNyYy9pbmRleC50cwBjb25zdCBDT05TVF8xID0gJ29rJzsKY29uc3QgQ09OU1RfVU5VU0VEID0gJ3dlbGwnOwoKZnVuY3Rpb24gbG9nKGRhdGE6IHN0cmluZykgewogIGlmIChERUJVRykgewogICAgY29uc29sZS5sb2coZGF0YSk7CiAgfQp9Cgpsb2coQ09OU1RfMSk7).

Interestingly enough, in that example it keeps unused "ok" then.

<img width="293" alt="image" src="https://github.com/evanw/esbuild/assets/4989256/06041483-16df-4c91-9e8a-3e09e748988d">

Anyways I'm probably expecting too much from esbuild, feel free to close the issue.

In my use case, I started to post-process esbuild's output JS with Closure Compiler with [advanced optimizations](https://developers.google.com/closure/compiler/docs/compilation_levels) enabled. It removes all dead code, including chained dead code & vars that become unreferenced when the function is cut.

**Comment by Inqnuam** [comment]
Hello @nikitaeverywhere, 
maybe esbuild "dropLabels" option is more suitable for your use case.
[example link](https://esbuild.github.io/try/#YgAwLjIwLjEAewogIGxvZ0xldmVsOiAnaW5mbycsCiAgZW50cnlQb2ludHM6IFsnc3JjL2luZGV4LnRzJ10sCiAgb3V0ZmlsZTogJy4vbGliL2luZGV4LmpzJywKICBidW5kbGU6IHRydWUsCiAgc291cmNlbWFwOiB0cnVlLAogIHRyZWVTaGFraW5nOiB0cnVlLAogIG1pbmlmeTogdHJ1ZSwKICBmb3JtYXQ6ICdpaWZlJywKICBkcm9wTGFiZWxzOiBbIkRFQlVHIl0KfQAAc3JjL2luZGV4LnRzAGNvbnN0IENPTlNUXzEgPSAnb2snOwpjb25zdCBDT05TVF9VTlVTRUQgPSAnd2VsbCc7CgpmdW5jdGlvbiBsb2coZGF0YTogc3RyaW5nKSB7CiAgREVCVUc6IGNvbnNvbGUubG9nKGRhdGEpOwp9Cgpsb2coQ09OU1RfMSk7)

**Comment by nikitaeverywhere** [comment]
Thanks @Inqnuam, indeed an interesting workaround.

**Comment by evanw** [comment]
Closing this issue as it is possible after all (just using an alternate, more optimizable syntax form). Using Google Closure Compiler in advanced mode is fine too (it's probably the most advanced optimizer out there!) but be careful because it requires you to write in a very particular subset of JavaScript to avoid bugs.

**Comment by nikitaeverywhere** [comment]
Thank you Evan. Keep up the good work!
