### ISSUE TITLE
[again] esbuild does not properly resolve extends field in tsconfig.json

### ISSUE THREAD

**Issue by neves** [evanw/esbuild#368]
Following https://github.com/evanw/esbuild/issues/279

Now I'm having the opposite problem: 
https://gist.github.com/neves/05b17fce65cdc3c92010537a162b3c25 
`"extends": "@tsconfig/recommended"` works!
but
`"extends": "@tsconfig/recommended/tsconfig.json"` doesn't.

Implemented [here](https://github.com/evanw/esbuild/commit/fb363859e193ea35287ea1d08c793365b98528d8#diff-d0908e240a12dd95b95e7c4ca0b13e9cR428) and broked [here](https://github.com/evanw/esbuild/commit/b2ae71009ec2dc7f3621a5640c530544d4c4a0e6#diff-d0908e240a12dd95b95e7c4ca0b13e9cR432)
the order was changed.

**Comment by evanw** [comment]
I'm guessing you're on Windows. Is that right? I can reproduce the problem on Windows using esbuild version 0.6.28. This problem has already been fixed in version 0.6.29. I believe this is the issue you are experiencing: #359. Can you try again with the latest version of esbuild to see if the problem has already been fixed?

**Comment by evanw** [comment]
Closing this for now. As I said above, I believe this has already been fixed.
