### ISSUE TITLE
Compile to ES6? [Feature request]

### ISSUE THREAD

**Issue by s1nistr4** [evanw/esbuild#3708]
It would be nice if you can minify your code to es6 instead of es5. That way code can be minified but truly depend on the latest js features. Setting target: es6 in the config does not do it, it still uses es5 features regardless

**Comment by evanw** [comment]
I'm adding `unactionable` because there's nothing I can do with this issue report as there isn't enough information. You didn't follow the [issue reporting instructions](https://raw.githubusercontent.com/evanw/esbuild/main/.github/ISSUE_TEMPLATE/new-issue.md) that you deleted when posting this issue.

**Comment by evanw** [comment]
Closing due to lack of information. Note that ES6 is (perhaps except for some very obscure edge cases) a superset of ES5 so ES5 features also work in ES6. You may also be referring to https://esbuild.github.io/faq/#top-level-var, in which case you can read why this is done in that FAQ entry.
