### ISSUE TITLE
Error resolving an external transitive dependency when using pnpm

### ISSUE THREAD

**Issue by ryanwilsonperkin** [evanw/esbuild#3710]
Minimal reproduction at https://github.com/ryanwilsonperkin/esbuild-pnpm-transitive-external

When building with `esbuild` and using `pnpm` for package management, I've found that any transitive dependencies that are marked as "external" cannot be found when running the bundled script.

Take for example a file importing an imaginary package `a` which in turn has a dependency on `b`.

```js
// index.js
import a from 'a';
```

Under pnpm, the node_modules directory structure will look like:
```
node_modules/
  a -> .pnpm/a@1.0.0/node_modules/a
  .pnpm/
    a@1.0.0/node_modules/
      a/
      b -> ../../b@1.0.0/node_modules/b
    b@1.0.0/node_modules/b
```

If we now build this and specify that `b` is external, then we'll get an error when running the produced script that `b` cannot be found. The reason appears to be that when bundling `a`, esbuild doesn't include the context of the resolved path of `a` when doing module resolution for `b`, so Node's resolution falls back to only looking within `node_modules/`

I believe this is a bug in esbuild, and that it should be ensuring that `module.paths` is updated within the context of the bundled package `a` when doing a `require` on its transitive dependencies.

**Comment by evanw** [comment]
You're requesting for esbuild to handle something that is outside of esbuild's scope. If you tell esbuild that the package `is-odd` is external, then you are telling esbuild that you are guaranteeing that you will make it available at run-time. Your code is broken because you are not upholding the guarantees you have made to esbuild, not because of a bug with esbuild.

If you don't want to have to deal with this, you should be able to use `--packages=external` to bundle just your code and not any of the top-level packages you depend on. You can read more about this in esbuild's [getting started instructions for node](https://esbuild.github.io/getting-started/#bundling-for-node).

**Comment by ryanwilsonperkin** [comment]
Shouldn't Node's path resolution remain consistent even when marking as external? We can tell Esbuild that a package is external, but it should still be resolved using the same path resolution approach that it would have if it was resolved at compile-time when bundling it.

For example, the docs call out:
>  It can also be used to import code in node at run time from a package that cannot be bundled.

If we aim to externalize a transitive dependency because it cannot be bundled, does that mean that we must also explicitly install that transitive dependency (and ensure that the versions always match) so that it can be resolved?

**Comment by evanw** [comment]
> If we aim to externalize a transitive dependency because it cannot be bundled, does that mean that we must also explicitly install that transitive dependency (and ensure that the versions always match) so that it can be resolved?

Yes. For example, you may be running it in a completely separate environment that only has that transitive dependency installed and nothing else, which is what you might want to do to minimize system resources in production. The easy way to handle this is to use `--packages=external` and let your package manager deal with managing packages. I recommend doing that if you want things to "just work" automatically. But if you decide to customize package management by only making certain packages external, then you are also taking on the extra responsibility of making sure those packages are available at run-time as appropriate.

I'm not keen on having esbuild be able do this automatically for you because esbuild is used in a huge set of very different environments (e.g. node, deno, bun, pnpm, yarn + pnp, import maps, custom plugins, partially bundling with a chain of different bundlers, etc.), and replicating how to bypass the package manager's isolation to get at the original nested package in all of those environments would be a lot of added complexity and ongoing work since everyone's use case is different. It's more straightforward for esbuild to leave it up to the user to ensure that external paths are present, so that's the approach that I've chosen for esbuild.

**Comment by ryanwilsonperkin** [comment]
Understood, thank you
