### ISSUE TITLE
Inside docker, esbuild quietly exits with 0 when --serve is enabled

### ISSUE THREAD

**Issue by halaxa** [evanw/esbuild#3712]
Hi there and thanks a lot for this brilliant piece of sw.

*The problem:* Inside docker, esbuild quietly exits with `0` when --serve is enabled (and from what I've found probably with --watch as well) and stdin is not available. My Dockerfile line concerning esbuild is `ENTRYPOINT ["esbuild"]`. It probably behaves the same in a similar non-docker environment without stdin as well.

*The proposed solution:* Exit with a non-zero code with a meaningful message when stdin is needed but not present instead of quietly quitting with exit code 0.

Only thanks to this answer https://stackoverflow.com/a/71898595/1919090 I was able to fix it by opening stdin inside docker. When knowing this is the issue there are other workarounds as well.

I tried to search for a similar issue here but with no luck. Thank you for investing your time into an OSS project ;)

**Comment by hyrious** [comment]
There's an option `--watch=forever` to keep process alive regardless of stdin closed.

**Comment by evanw** [comment]
Thanks for this issue. I agree that esbuild should print something out in this scenario, so I'll add that. It's not great that it's exiting silently. Watch mode currently prints something out but in I haven't yet given serve mode the same treatment.

What I'm doing for watch mode is to exit with a zero exit code if stdin is closed cleanly (i.e. reading returns EOF), and only exit with an error code otherwise. I'm inclined to not change the exit code behavior for this since a) it's currently consistent between serve mode and watch mode, b) changing it might break something at this point so any change might want to wait until a breaking change release, c) exiting cleanly is not necessarily an error condition, and d) I'd expect the message printed to the console to be sufficient to debug things in this case.

FWIW the reason that this stdin-specific behavior exists is that (as far as I understand) the Erlang ecosystem doesn't have a way to terminate a child process other than closing stdin. There is also similar behavior in Webpack (see [this](https://github.com/webpack/webpack/issues/1308) and [this](https://github.com/webpack/webpack/pull/1311)).

**Comment by halaxa** [comment]
Thank you. You're right. Changing the exit code is not a good idea and probably not even necessary to introduce in the future. What would greatly help is the message with the cause for both modes. Good job 👍

**Comment by evanw** [comment]
I'm closing this issue as a log message has been added (see the above commit). It will go out with the next esbuild release.
