### ISSUE TITLE
ENV Secrets accessible from js code in a React + Rails APP.

### ISSUE THREAD

**Issue by devsheva** [evanw/esbuild#3732]
Context:
- Rails 7 + React APP with esbuild as bundler

It's not really an issue, but I have this concern. 
Context

I noticed that, obviously, variables declared in **define** block of esbuild config are plain, so you can see them by inspecting source code from the browser.

I have to use some secrets in the react code, like AWS access keys, so definitely defining them with esbuild is not the way.
My question is, how can I achieve this behaviour ?

This is my config

```js

// esbuild.config.js
const railsEnv = process.env.RAILS_ENV || 'development'
const optimize = railsEnv !== 'development'

const path = require('path')

const fs = require('fs')

const envPath = path.join(process.cwd(), 'app/javascript/react/src/.env')
const envFileExists = fs.existsSync(envPath)

envFileExists && require('dotenv').config({ path: envPath })

require('esbuild').build({
  entryPoints: ['application.js'],
  bundle: true,
  outdir: path.join(process.cwd(), 'app/assets/builds'),
  absWorkingDir: path.join(process.cwd(), 'app/javascript'),
  color: true,
  watch: process.argv.includes('--watch'),
  minify: optimize,
  sourcemap: true,
  define: {
    'process.env': JSON.stringify(process.env),
    'process.env.RAILS_ENV': JSON.stringify(railsEnv),
  },
})


```

**Comment by hyrious** [comment]
The answer is _not_ leaking the whole `process.env` to browser. For example, [Vite by default requires env variables to start with `VITE_` to allow to expose](https://vitejs.dev/guide/env-and-mode.html). You can implement the same idea in your build scripts.

**Comment by devsheva** [comment]
Sorry, what do you mean exactly? As I said I can see that variables like AWS_ACCESS_KEY are leaked in the browser. I need to access this variable from my code though, so if I don't put it in _define_  block, it won't be available

**Comment by devsheva** [comment]
Yes, I agree that is my responsibility to not expose the variables, but as I said I didn't find another way to achieve the same behaviour.

> Where your code will be executed ? in a browser ? in a backend JS runtime like NodeJS ?
As I said I have a React + Rails APP, so the backend is Rails -> code will be run in a browser

**Comment by hyrious** [comment]
Let's be clear at these facts:
- Code running in the browser is transparent to users. Any person can access the JS code you shipped on the website.
- Depending on the usage of a secret, it can be safe or danger to leak it to client. For those secrets having high privileges, it is better to only store it on the server side and let the client ask the server to get functions.

For example, AWS has a STS token which is often used to implement uploading logic in the client side (so that the server does not have to pay the cost of huge data from files). The STS token is made up by a specific OSS path, a policy string indicating the token's privileges, a signature and _the AK_. The token only works on limited resources and it will expire in a few time. In this situation, the AK is leaked to the client. But it is totally safe to do so.

As a developer, you need to know each secret's correct usage and decide whether to leak it to the client, or leave it at server side.

**Comment by devsheva** [comment]
I definitely agree with what you said, perfect explain. 

Never thought  about the STS solution, that can really help to solve my concern about AWS secrets. 
But what about f.e. Google Maps API Key ? We all know that you can't delegate the maps render to the server cause it's impossible, and the Google SDK is for js is client-side

**Comment by evanw** [comment]
I'm closing this issue because this is a general question about web development, and is not appropriate for esbuild's issue tracker.

Generally secrets that must not be exposed on the client have to be kept on the server and proxied to the client. The Google Maps API has a lot of documentation about this: https://developers.google.com/maps/api-security-best-practices.
