### ISSUE TITLE
Is there a problem here? does this make sense?

### ISSUE THREAD

**Issue by mikoloism** [evanw/esbuild#3738]
I haven't installed the [`esbuild`](https://github.com/evanw/esbuild) package (maybe [`tsup`](https://github.com/egoist/tsup) does it as a peer), but I haven't called or run any related commands?!
Why does it run automatically?

![image](https://github.com/evanw/esbuild/assets/64307152/f0f412cc-a085-4973-ba3b-542e175194fe)

> cross issues to [evanw/esbuild](https://github.com/evanw/esbuild/issues/3738) and [egoist/tsup](https://github.com/egoist/tsup/issues/1113) and [microsoft/vscode](https://github.com/microsoft/vscode/issues/211525)

**Comment by evanw** [comment]
This is due to a decision that I made because esbuild is written in native code and uses a platform-specific binary executable that comes from a separate package (one package per OS+CPU combination). This setup that uses separate platform-specific packages is complex and can sometimes break in unusual situations such as when people mess with their package manager’s settings. 

So when you install esbuild, esbuild’s install script [runs esbuild with the `--version` flag](https://github.com/evanw/esbuild/blob/b9adc0124d41d18110934d4da1b58c9462c16796/lib/npm/node-install.ts#L18) once as a sanity check which prints the version number and then exits. This catches situations where something is wrong with the installation so that you know something is wrong at install time instead of at some point later when you try to use esbuild. It has caught real issues in the past, such as people using a faulty npm proxy that caches packages for the wrong architecture, or people running esbuild on an old version of macOS that the Go compiler no longer supports.

This behavior is intentional. Nothing looks wrong here to me.

**Comment by evanw** [comment]
Ah, I see. It was unclear from your initial post what was happening. If it's still running then your problem is likely unrelated to any code in this repo, and something else on your end is causing esbuild to run. You'll have to investigate this on your end. Just posting a picture that says `code > node > esbuild` does not convey anywhere nearly enough information for me to be able to diagnose your problem.

**Comment by mikoloism** [comment]
That's a good point, I don't know what's going on here for me to explain it either :smiley:
