### ISSUE TITLE
Using define for code replacement

### ISSUE THREAD

**Issue by LXSMNSYC** [evanw/esbuild#374]
Is there a way to use `define` to generate code snippet? I have a `__DEV__` keyword which I want to be replaced with `process.env.NODE_ENV !== 'production'` for ESM builds, but it seems that `define` only allows valid JSON values for replacment.

**Comment by evanw** [comment]
If you want to replace `__DEV__` with `true` or `false` depending on the value of `process.env.NODE_ENV !== 'production'` then you could create a build script that looks something like this:

```js
const { build } = require('esbuild')

build({
  entryPoints: ['./src/main.ts'],
  outfile: './dist/main.js',
  minify: true,
  bundle: true,
  define: {
    '__DEV__': process.env.NODE_ENV !== 'production',
  },
}).catch(() => process.exit(1))
```

If you want to replace `__DEV__` with the literal code `process.env.NODE_ENV !== 'production'`, that is not currently possible. It's not necessarily clear how this should work to me. Replacing the code inline could be undesirable because it could cause heavy code expansion, which could make the bundle much bigger. But replacing it with a variable that is referenced once for each usage would change evaluation order.

A workaround could be to create another module that defines `export let __DEV__ = process.env.NODE_ENV !== 'production'` and then import that where you access the `__DEV__` variable.

**Comment by LXSMNSYC** [comment]
Thanks for the response.

Honestly, I wanted to do something similar to what TSDX delivers: https://tsdx.io/optimization#code-dev-code and so I cannot really do a constant export.

If there is no current workarounds then I am afraid I have to omit from implementing this feature.
