### ISSUE TITLE
Cross-Platform Development Problem 

### ISSUE THREAD

**Issue by andre-beeclever** [evanw/esbuild#3747]
Hello,
we experience the following problem:
node projects, set up on an M1 mac can't be used on an Intel based mac, github action or linux server, as it puts the darwin-arm64 version of esbuild into the dev dependencies of the package.json & package-lock.json.

When starting on an Intel Mac it works fine as the M1 can emulate the x64 binaries. 

Is there a proper way use esbuild cross platform (x64/arm)?

**Comment by evanw** [comment]
Please read the “getting started” instructions: https://esbuild.github.io/getting-started/#simultaneous-platforms

**Comment by evanw** [comment]
You cannot install esbuild on one OS, copy the `node_modules` directory to another OS without reinstalling, and then run esbuild on that other OS. This won't work because esbuild is written with native code and needs to install a platform-specific binary executable. Normally this isn't an issue because you typically check your `package.json` file into version control, not your `node_modules` directory, and then everyone runs `npm install` on their local machine after cloning the repository.

However, people sometimes get into this situation by installing esbuild on Windows or macOS and copying their `node_modules` directory into a [Docker](https://www.docker.com/) image that runs Linux, or by copying their `node_modules` directory between Windows and [WSL](https://docs.microsoft.com/en-us/windows/wsl/) environments. The way to get this to work depends on your package manager:

- **npm/pnpm:** If you are installing with npm or pnpm, you can try not copying the `node_modules` directory when you copy the files over, and running `npm ci` or `npm install` on the destination platform after the copy. Or you could consider using [Yarn](https://yarnpkg.com/) instead which has built-in support for installing a package on multiple platforms simultaneously.

- **Yarn:** If you are installing with Yarn, you can try listing both this platform and the other platform in your `.yarnrc.yml` file using [the `supportedArchitectures` feature](https://yarnpkg.com/configuration/yarnrc/#supportedArchitectures). Keep in mind that this means multiple copies of esbuild will be present on the file system.

You can also get into this situation on a macOS computer with an ARM processor if you install esbuild using the ARM version of npm but then try to run esbuild with the x86-64 version of node running inside of [Rosetta](https://en.wikipedia.org/wiki/Rosetta_(software)). In that case, an easy fix is to run your code using the ARM version of node instead, which can be downloaded here: [https://nodejs.org/en/download/](https://nodejs.org/en/download/).

Another alternative is to [use the `esbuild-wasm` package instead](#wasm), which works the same way on all platforms. But it comes with a heavy performance cost and can sometimes be 10x slower than the `esbuild` package, so you may also not want to do that.

**Comment by andre-beeclever** [comment]
Yeah sure, we are not copying the the node modules. We use git, and the node modules are ignored. But as soon as one ran `npm i `on an arm mac, the `esbuild-darwin-arm64` package appears in the dev dependencies of the package json. This can't be intended, as it causes an error when trying to install the project on another platform. Shouldn't esbuild be added to to the dev dependencies, so it can install the right binary on each system? There should not be platform specific modules in the package.json.

Sorry for bothering you with this.

**Comment by hyrious** [comment]
> Shouldn't esbuild be added to to the dev dependencies,

Yes it should be `esbuild` in `devDependencies`. Maybe there's some custom install script that adds platform specific esbuild variant to your package.json. You need to debug that for yourself.

**Comment by andre-beeclever** [comment]
Ok thanks.
