### ISSUE TITLE
Missing `es2023` target

### ISSUE THREAD

**Issue by garysassano** [evanw/esbuild#3762]
Although Microsoft added `es2023` target in TypeScript last month (see [this PR](https://github.com/microsoft/TypeScript/pull/58140)), esbuild still doesn't recognize it. Attempting to use `es2023` with esbuild results in the following error:

```sh
Error: Invalid target "es2023" in "--target=es2023"
```

**Comment by evanw** [comment]
Sure, I can add that. I don't think it will do anything different than `es2022` because all of the additions in ES2023 are APIs instead of syntax and `target` only cares about syntax changes. But I agree that it's weird that esbuild doesn't have an ES2023 target yet. You should be able to use `es2022` instead of `es2023` in the meantime.
