### ISSUE TITLE
Is there a way to preserve string delimiters?

### ISSUE THREAD

**Issue by Pomax** [evanw/esbuild#3804]
I noticed that esbuild produces a bundle where all my backticks are replaced by single quotes, so that this:

```js
        const descClass = `graphics-element-description`;
```

turns into this

```js
m = 'graphics-element-description';
```

And I understand the variable rename, that saves a bunch of bytes, but replacing one string delimiter for another does not help make the code smaller (they're all one byte), nor does it make the resulting code execute any faster. However, it _does_ make it needlessly more work to search for bits of erroneous code involving strings.

Is there a way to tell esbuild to not touch string delimiters?

**Comment by evanw** [comment]
No, there isn't a way to preserve string delimiters.

String literals behave exactly the same as no-substitution template literals at run-time, so esbuild treats them as equivalent and may turn either one into the other one depending on the situation. For example, esbuild may turn `"\'\""` into `` `'"` `` and ``` `\`` ``` into ``"`"`` because it's shorter, just like esbuild may transform `'\''` into `"'"` and `"\""` into `'"'`. Furthermore, even when it doesn't result the output using fewer characters, consistently using the same quote character whenever possible may help the resulting code compress to a smaller size after minification.

Can you say more about why you consider string literals to be not equivalent to no-substitution template literals?

**Comment by merceyz** [comment]
> nor does it make the resulting code execute any faster

However it can make compiling it faster https://github.com/nodejs/node/issues/41448.

**Comment by Pomax** [comment]
> An excellent explanation

That makes a lot of sense. However, it would still be nice if that was something I could configure to not happen.

> Can you say more about why you consider string literals to be not equivalent to no-substitution template literals?

It mostly matters during the process: if I'm debugging in the browser, and there's an error, the fastest way to find it in the source is to just copy a stretch of text and find-in-file with that. Selecting that stretch _with_ quotation marks is a decided faster action than having to carefully select the text_inside_ the quotation marks, and so this is really only a problem when something unexpected goes wrong in staging or as a review app, but when it _does_ go wrong, those quotes make an already unexpected time sink take that tiny bit longer.

**Comment by evanw** [comment]
It sounds like when you're debugging, you're saying that you prefer code that's more optimized for human readability than for machine consumption.

The good news is that esbuild already does have the ability to preserve `` ` `` in no-substitution template literals, and in fact does so by default. You're only seeing esbuild convert `` ` `` to `"` because you have minification enabled (specifically the [`--minify-syntax`](https://esbuild.github.io/api/#minify) setting tells esbuild to try to change your syntax to equivalent syntax that's more optimized for running in production, which is what esbuild is doing here). When debugging, I recommend not passing `--minify-syntax` to esbuild so that the generated code easier to debug. You can compare [this](https://esbuild.github.io/try/#dAAwLjIxLjUAAGNvbnN0IGRlc2NDbGFzcyA9IGBncmFwaGljcy1lbGVtZW50LWRlc2NyaXB0aW9uYDs) vs. [this](https://esbuild.github.io/try/#dAAwLjIxLjUALS1taW5pZnktc3ludGF4AGNvbnN0IGRlc2NDbGFzcyA9IGBncmFwaGljcy1lbGVtZW50LWRlc2NyaXB0aW9uYDs) to see the difference for yourself.

**Comment by Pomax** [comment]
that's fair, cheers!
