### ISSUE TITLE
Support decorators in `.vue` files.

### ISSUE THREAD

**Issue by ruojianll** [evanw/esbuild#3842]
In newest `npm create vue@latest` project, we could use decorators after set ` "experimentalDecorators": true` in standalone `.ts` files. But it couldn't be transformed in `.vue` files in `<script lang="ts"></script>`.

I don't know if it's an esbuld issue, could you give me some advices?

https://github.com/vitejs/vite-plugin-vue/issues/430

**Comment by evanw** [comment]
Sorry, esbuild has nothing to do with Vue. The content types that esbuild supports are here: https://esbuild.github.io/content-types/. You'll notice that the Vue language is not listed. Decorators are supported in JavaScript and TypeScript, so if Vue uses esbuild to transform JavaScript and/or TypeScript then decorators should work (assuming the target has been configured correctly). But that's up to Vue to make use of. That's not a problem with esbuild.

I'm closing this issue because it's out of scope.
