### ISSUE TITLE
esbuild "comment" to strip the next line during bundling?

### ISSUE THREAD

**Issue by Pomax** [evanw/esbuild#3849]
I was reading through https://github.com/evanw/esbuild/issues/2006 because I have a bunch of code in a single file along the line of 

```
const DEBUG = true;

...

if (DEBUG) console.log('lemon cake deserves real cream');
```

and was hoping to treeshake those out of existence (without minification) when DEBUG is `false` as any code path conditional on `false` is dead code and can be safely "shaken out". However, that's not really what happens, and if I read into issue 2006 and use a pattern `DEBUG && console.log(....)` instead, then the bundle ends up with a bunch of spurious `DEBUG && void 0;` rather than just "nothing.

For cases like these, it would be super nice to have something like `// @esbuild strip next-line` or something combined with `--allow-strip` as CLI argument so that esbuild knows to just gobble input until it's passed the next line of code. e.g.:

```
// @esbuild strip next-line
const DEBUG = true;

...

// @esbuild strip next-line
if (DEBUG) console.log('lemon cake deserves real cream');
runSomeThing();
```

would essentially pass the input as if it was:

```
...

runSomeThing();
```

Which would make for a much nicer bundle. 

(And because it would control the parser, it doesn't even need to know "what" it's stripping. If the resulting bundle is broken, that's on the person adding the strip comment, not esbuild)

**Comment by evanw** [comment]
I recommend that you use labels instead of comments: https://esbuild.github.io/api/#drop-labels. It's an existing feature and it uses real syntax instead of magic comments so it's more robust to code transformations than magic comments would be. It also has the benefit that you can toggle different names on and off independently for finer control. Here's an example (the label names are arbitrary and is up to you):

https://esbuild.github.io/try/#dAAwLjIzLjAALS1kcm9wLWxhYmVscz1lc2J1aWxkX3N0cmlwX3RoaXMAZXNidWlsZF9zdHJpcF90aGlzOgpjb25zb2xlLmxvZygnbGVtb24gY2FrZSBkZXNlcnZlcyByZWFsIGNyZWFtJyk7CnJ1blNvbWVUaGluZygpOw

**Comment by Pomax** [comment]
completely missed that part of the docs, thank you!
