### ISSUE TITLE
JSON files as entry points and JSON files imported from TS/JS

### ISSUE THREAD

**Issue by james-pre** [evanw/esbuild#3860]
I'm currently working on a project where I use JSON files in two ways. In the first way, I `import` from `package.json`. In the second, I `fetch` JSON files at runtime, which are used to store locale data. I just started experiencing a problem where all of the JSON files are converted to JS files, so the `fetch` fails because `example.json` doesn't exist (It is now `example.js`). When `import`ing a JSON file this makes sense, but I'm trying to copy it to the output. Note `bundle` is `true` and `format` is `esm`.

Basically:

example.ts
```ts
export { version } from '../package.json';
```
Gets transformed to
```ts
var version, author;
var init_package = __esm({
  "package.json"() {
    version = "example";
  }
});
```
This is correct. 

locales.ts
```ts
// ...
await fetch('locales/en.json');
// ...
```

This fetch call will stay the same after being transformed, though `locales/en.json` is transformed to `locales/en.js`, which causes the `fetch` to fail. This behavior is incorrect, at least for my use case.

Please note: The files in `locales` are entry points, and the JSON files `import`ed are not.

I can't fix this issue using Esbuild's configuration options, since I cannot specify a different loader for different paths for JSON files.

**Comment by hyrious** [comment]
First of all, to make esbuild understand the string 'locales/en.json' is actually a file referenced in the bundle's entry points, it should not be put in the `fetch()` call. The only way to indicate that is using `require('<path>')`/`import '<path>'`/`import('<path>')`. So the correct usage is:

```js
const en = await import('./locales/en.json')
someI18nLibrary.locales.set({ en })
```

Note that this way, esbuild **knows** you're dynamically importing a file. It will [split](https://esbuild.github.io/api/#splitting) that file out as a chunk so that it gets lazily loaded. Therefore you do not have to mark this file as entry point. [Playground Link](https://esbuild.github.io/try/#YgAwLjIzLjAALS1idW5kbGUgLS1mb3JtYXQ9ZXNtIC0tc3BsaXR0aW5nIC0tb3V0ZGlyPS4AZQBlbnRyeS5qcwBpbXBvcnQgZW4gZnJvbSAnLi9sb2NhbGVzL2VuLmpzb24nCmkxOG4uc2V0KHsgZW4gfSkKCmltcG9ydCgnLi9sb2NhbGVzL3poLUNOLmpzb24nKS50aGVuKCh6aENOKSA9PiB7CiAgaTE4bi5zZXQoeyAnemgtQ04nOiB6aENOIH0pCn0pAABsb2NhbGVzL2VuLmpzb24AeyJoZWxsbyI6ImhlbGxvIn0AAGxvY2FsZXMvemgtQ04uanNvbgB7ImhlbGxvIjoiXHU0RjYwXHU1OTdEIn0)

On the other hand, if you want to keep the `.json` extension and still use `fetch()` calls to load them. These json files should be considered static assets and be copied to the public folder. In which case you just stop feeding them as entry points, and write extra scripts to do the copy work.

**Comment by james-pre** [comment]
I've decided it is a lot easier to just copy the locales instead of trying to use Esbuild
