### ISSUE TITLE
Esbuild Won't Drop Unused Functions Created by Other Functions 

### ISSUE THREAD

**Issue by ghost** [evanw/esbuild#3863]
Example

```ts
export const mirror = function mirror(str)
{
    return str;
};

let createCounterFunction = function createCounterFunction()
{
    let i = 0;
    let counter = function counter()
    {
        i += 1;
        return i;
    };
    return counter;
};
export const funcCount = createCounterFunction();
```

Expected the "mirror" to be dropped

**Comment by evanw** [comment]
I'm confused because that already happens: [(here is an example)](https://esbuild.github.io/try/#YgAwLjIzLjAALS1idW5kbGUgLS1mb3JtYXQ9ZXNtAGUAZW50cnkuanMAaW1wb3J0ICcuL2ZpbGUuanMnAABmaWxlLmpzAGV4cG9ydCBjb25zdCBtaXJyb3IgPSBmdW5jdGlvbiBtaXJyb3Ioc3RyKQp7CiAgICByZXR1cm4gc3RyOwp9OwoKbGV0IGNyZWF0ZUNvdW50ZXJGdW5jdGlvbiA9IGZ1bmN0aW9uIGNyZWF0ZUNvdW50ZXJGdW5jdGlvbigpCnsKICAgIGxldCBpID0gMDsKICAgIGxldCBjb3VudGVyID0gZnVuY3Rpb24gY291bnRlcigpCiAgICB7CiAgICAgICAgaSArPSAxOwogICAgICAgIHJldHVybiBpOwogICAgfTsKICAgIHJldHVybiBjb3VudGVyOwp9OwpleHBvcnQgY29uc3QgZnVuY0NvdW50ID0gY3JlYXRlQ291bnRlckZ1bmN0aW9uKCk7). Note that `mirror` isn't removed if the root file is an entry point because the exports of an entry point are not unused: [(here is an example)](https://esbuild.github.io/try/#YgAwLjIzLjAALS1idW5kbGUgLS1mb3JtYXQ9ZXNtAGUAZW50cnkuanMAZXhwb3J0IGNvbnN0IG1pcnJvciA9IGZ1bmN0aW9uIG1pcnJvcihzdHIpCnsKICAgIHJldHVybiBzdHI7Cn07CgpsZXQgY3JlYXRlQ291bnRlckZ1bmN0aW9uID0gZnVuY3Rpb24gY3JlYXRlQ291bnRlckZ1bmN0aW9uKCkKewogICAgbGV0IGkgPSAwOwogICAgbGV0IGNvdW50ZXIgPSBmdW5jdGlvbiBjb3VudGVyKCkKICAgIHsKICAgICAgICBpICs9IDE7CiAgICAgICAgcmV0dXJuIGk7CiAgICB9OwogICAgcmV0dXJuIGNvdW50ZXI7Cn07CmV4cG9ydCBjb25zdCBmdW5jQ291bnQgPSBjcmVhdGVDb3VudGVyRnVuY3Rpb24oKTs).

**Comment by evanw** [comment]
I'm closing this issue as the user account that reported it has been deleted.
