### ISSUE TITLE
Drop Unused Imports

### ISSUE THREAD

**Issue by ghost** [evanw/esbuild#3864]
```'ts
import unused from "abc";
export const A = "hello"
```

**Comment by evanw** [comment]
I'm confused because that already works: [(here is an example)](https://esbuild.github.io/try/#dAAwLjIzLjAALS1taW5pZnktc3ludGF4AGltcG9ydCB1bnVzZWQgZnJvbSAiYWJjIjsKZXhwb3J0IGNvbnN0IEEgPSAiaGVsbG8i). Unless you mean that esbuild should remove the `import "abc"` itself. That would be incorrect, as that import could have important side effects.

**Comment by rkarthick15** [comment]
@evanw Could you please elaborate how removing a unused import have side effects?

**Comment by evanw** [comment]
Sure: [(link)](https://esbuild.github.io/try/#YgAwLjIzLjAALS1idW5kbGUgLS1mb3JtYXQ9ZXNtAGUAZW50cnkuanMAaW1wb3J0IHVudXNlZCBmcm9tICJhYmMiOwpleHBvcnQgY29uc3QgQSA9ICJoZWxsbyIAAG5vZGVfbW9kdWxlcy9hYmMvaW5kZXguanMAZXhwb3J0IGRlZmF1bHQgMTIzCmltcG9ydGFudFNpZGVFZmZlY3RzKCk). If you remove `import "abc"` then `importantSideEffects()` never gets called.

**Comment by evanw** [comment]
I'm closing this issue as the user account that reported it has been deleted.
