### ISSUE TITLE
broken build since 0.7 due to browser field in package.json

### ISSUE THREAD

**Issue by daaku** [evanw/esbuild#387]
I was using 0.6 successfully, but the recent support for `module` / `browser` in `package.json` seems to have broken the previously working ability to import the `nanoid` (version `3.1.12`) package.

Until 0.6, this command worked:
```
esbuild --bundle --sourcemap --define:process.env.NODE_ENV=\"production\" --outdir=dist/bundle test/tests.ts
```

Now it fails. It works again if I pass these flags:

```
--main-fields=module,main
```

Seems like the `browser` definition in the `package.json` for `nanoid` isn't what `esbuild` expects?

--

PS: Thanks for furthering the goal of removing the frustration of slow builds in my life.

**Comment by evanw** [comment]
It appears to work for me, both for the browser and for node, using the example from their readme:

```js
import { nanoid } from 'nanoid'
model.id = nanoid() //=> "V1StGXR8_Z5jdHi6B-myT"
```

It only works with `import`, however, not with `require`. It produces an error about not being able to import the `crypto` package when using `require`. So I'm guessing you're using `require`?

It looks like the `nanoid` package is configured incorrectly in `package.json`. The `"browser"` field contains an override for `"module"` but not for `"main"`, meaning bundlers that respect the `"browser"` field but that pick `"main"` over `"module"` won't get the browser-based build:

```json
"browser": {
  "./index.js": "./index.browser.js"
},
"main": "index.cjs",
"module": "index.js",
```

The library is missing the case for CommonJS code for the browser. I'd expect it to look like this instead:

```json
"browser": {
  "./index.cjs": "./index.browser.cjs",
  "./index.js": "./index.browser.js"
},
"main": "index.cjs",
"module": "index.js",
```

I can think of several workarounds:

* Use `--main-fields=module,main` like you said
* Use `import 'nanoid'` instead of `require('nanoid')`
* Use `require('nanoid/index.js')`

**Comment by daaku** [comment]
Thanks for taking a look. I'm using the `--main-fields` workaround. FWIW I was importing it using `import { customAlphabet } from 'nanoid';` (in TypeScript if it matters).

Closing it since you've opened a more appropriate issue on their side.

**Comment by ai** [comment]
I fixed `package.browser` in NanoID 3.1.23 https://github.com/ai/nanoid/commit/b7d116c685204f5c9763b0bec96176b8b428bf3c
