### ISSUE TITLE
Why "for the web"?

### ISSUE THREAD

**Issue by ericmorand** [evanw/esbuild#3873]
I'm sorry to open an issue for such a dumb question that would definitely be better suited as a discussion, but this is bugging me out: why is the documentation of esbuild saying that it is a _bundler for the web_.

I'm planning on moving from rollup to esbuild to bundle the npm packages that I maintain, and this simple "for the web" mention makes me wonder is this is a good or a wrong idea.

Specifically:

* Does it mean that esbuild makes some asumption that what we bundle is expected to be executed by an DOM-compliant JS runtime (typically, where `window` is an exposed global symbol)?
* Does it mean that, would I encounter an issue with a bundle executed by Node.js or deno or bum, I won't get any support from the maintainers?

**Comment by hyrious** [comment]
It simply means esbuild doesn't need too much configuration when [bundling for the browser](https://esbuild.github.io/getting-started/#bundling-for-the-browser). Docs for [`platform`](https://esbuild.github.io/api/#platform) has more detailed explanation about the behavior when choosing different platforms.

- > Does it mean that esbuild makes some asumption that what we bundle is expected to be executed by an DOM-compliant JS runtime (typically, where `window` is an exposed global symbol)?

  It does, for example [esbuild will mark these global API names as PURE](https://github.com/evanw/esbuild/blob/main/internal/config/globals.go#L255) so that it can do more minification works. In fact [rollup does the same](https://github.com/rollup/rollup/blob/master/src/ast/nodes/shared/knownGlobals.ts#L549) and even has more asumptions. (I guess rollup has the most strongest asumptions since it can fold functions and track object props. That's why it can tree-shake the most of the code).

- > Does it mean that, would I encounter an issue with a bundle executed by Node.js or deno or bun, I won't get any support from the maintainers?

  esbuild has `--platform=node` which sets many behavior to be Node.js compatible like how it resolve dependencies and adds `module.exports = {}` annotation to let Node.js' cjs-module-lexer find export names. On the other hand, [`target`](https://esbuild.github.io/api/#target) holds more detailed config for whether a language feature is supported at some runtime. So the maintainer is supporting them already.

**Comment by ericmorand** [comment]
Thanks for the explanation. The "for the web" mention is confusing but reading the rest of the documentation makes it clear that esbuild is appropriate for other targets too.
