### ISSUE TITLE
Keep number literals in their original form

### ISSUE THREAD

**Issue by wrnrlr** [evanw/esbuild#3886]
Is it possible to keep number literals in their original form? Currently esbuild will turn `1e1` into `10`, which is correct of course but in the ganja dialect of javascript this syntax is used as a shorthand for writing [multivectors](https://enkimute.github.io/ganja.js/examples/coffeeshop.html#pga3d_points_and_lines). For example `1e123` is the geometric product of the base vectors `1e1`, `1e2` and `1e3`.

This is also the behaviour of the `toString()` of a function:

```
let f = a => a*1e1
f.toString()
// "(a)=>a * 1e1"
```

**Comment by neehhaa06** [comment]
Hello!! @wrnrlr :)

> 
```
Use a Babel plugin to preserve number literals in their original form, like `1e1`. The plugin checks if a number is in exponential form and retains its raw representation. Integrate this plugin into your build process by adding it to your Babel configuration. This approach ensures that literals like `1e123` remain unchanged during code transformation.
```

**Comment by evanw** [comment]
That's a very creative abuse of JavaScript syntax. But at that point that's no longer JavaScript. Sorry, but esbuild only supports real JavaScript not other languages that happen to look like JavaScript but that behave differently. Technically you could say that esbuild doesn't support this because [esbuild explicitly doesn't support preserving `toString()` on functions](https://esbuild.github.io/content-types/#function-tostring). But even if that wasn't the problem, you're asking for esbuild to support an obscure programming language that looks like JavaScript but that doesn't behave like it, and that is outside of esbuild's scope. I'm closing this issue as out of scope.
