### ISSUE TITLE
Possible regression for fe92ecf (fix #363: require => "main" and import => "module")

### ISSUE THREAD

**Issue by wader** [evanw/esbuild#391]
Hello!

I just updated esbuild to 0.7.1 an got some strange runtime error messages from my bundled app when running in a browser:
```
NodeWidget.tsx:61 Uncaught TypeError: a.default is not a constructor
    at l.componentDidMount (NodeWidget.tsx:61)
    at commitLifeCycles (react-dom.development.js:19814)
    ... lots more ...
    at test.tsx:30
    at test.tsx:30
```

After some fiddling I managed to bisect it down to commit fe92ecf being the commit when it starts happening. I suspect it has to do with how react-diagrams and react-canvas-core are packaged using both main and module. Example https://github.com/projectstorm/react-diagrams/blob/master/packages/react-canvas-core/package.json

I tried to use the `require` once workaround that was mentioned in the release notes but it does not seems to make a difference.

Not sure if this is bug in esbuild, issue with my dependencies or if i'm doing something wrong. Happy to help digg further. 

Thanks for esbuild by the way! also thanks for the technical documentation, interesting read.

Here is the smallest reproduction case I can produce:
```tsx
// require once does not seems to help
// require('@projectstorm/react-diagrams');
// require('@projectstorm/react-canvas-core');

import * as React from 'react'
import * as ReactDOM from 'react-dom'

import createEngine, {
  DefaultNodeModel,
  DiagramModel,
} from '@projectstorm/react-diagrams';

import {
  CanvasWidget
} from '@projectstorm/react-canvas-core';

class App extends React.Component {
  render() {
    const node1 = new DefaultNodeModel();
    const model = new DiagramModel();
    const engine = createEngine();
    model.addAll(node1);
    engine.setModel(model);
    return <div>
      <CanvasWidget engine={engine} />
    </div>
  }
}

ReactDOM.render(<App />, document.getElementById('root'));
```

```json
{
  "name": "esbuildtest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "@projectstorm/react-diagrams": "^6.2.0",
    "@types/react": "^16.9.43",
    "@types/react-dom": "^16.9.8",
    "lodash": "^4.17.19",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "resize-observer-polyfill": "^1.5.1"
  },
  "devDependencies": {
    "@types/node": "^14.0.22",
    "esbuild": "0.7.1",
    "typescript": "^3.9.6"
  },
  "author": "",
  "license": "ISC"
}
```

```sh
esbuild \
        app/test.tsx \
        --bundle \
        --target=es6 \
        '--define:process.env.NODE_ENV="development"' \
        --define:global=window \
        --outfile=dist/out.js \
        --sourcemap
```

Diff of output from fe92ecf~1 and fe92ecf:

[out.js-b4a0662-fe92ecf.log](https://github.com/evanw/esbuild/files/5235328/out.js-b4a0662-fe92ecf.log)

**Comment by evanw** [comment]
It looks like this is a problem with one of the libraries you are using. That commit introduced greater compatibility with node's module resolution algorithm to esbuild. However, the `@projectstorm/react-diagrams-core` library you are using is not compatible with node's module resolution algorithm. You can verify this by running the following code unmodified in node without bundling with esbuild (i.e. it's a problem completely unrelated to esbuild):

```js
// Patches to avoid a crash in "@projectstorm/react-diagrams" and "matches-selector"
global.window = {};
global.Element = { prototype: { matchesSelector() {} } };
 
const React = require('react');
const { default: createEngine, DefaultNodeModel, DiagramModel } = require('@projectstorm/react-diagrams');
const { CanvasWidget } = require('@projectstorm/react-canvas-core');
const renderer = require('react-test-renderer');
 
class App extends React.Component {
  render() {
    const node1 = new DefaultNodeModel();
    const model = new DiagramModel();
    const engine = createEngine();
    model.addAll(node1);
    engine.setModel(model);
    return React.createElement("div", null, React.createElement(CanvasWidget, { engine }));
  }
}
 
const component = renderer.create(React.createElement(App, null));
console.log(component);
```

This crashes in node with `TypeError: a.default is not a constructor`. The problem is essentially this:

```js
// First, the code imports the resize-observer-polyfill library and exports it as module 22
e.exports = require("resize-observer-polyfill")

// Then, the code imports module 22 using a minified require() stub
const a = i(22);

// Finally, the code tries to access the "default" property on the exported object
componentDidMount() {
  this.ob = new a.default()
}
```

It crashes because the `resize-observer-polyfill` package exports a function directly using `module.exports = function() {}`. It does not export an object with a property called `default` with a function as a value, which is what `@projectstorm/react-diagrams-core` is expecting.

A possible workaround for this issue could be to use `--main-fields=browser,module,main` to force esbuild to use the `"module"` field in `package.json` before the `"main"` field. However, that may break other packages that use `require()` and expect to get a function object instead of an object with a `default` property (see #363 for an example).

**Comment by wader** [comment]
Thanks for the very detailed explanation. Think i have to read up on different module standards to fully understand. But there seems to be other people with similar issues with that library.

The `--main-fields` workaround seems to work fine! sorry it was unrelated to esbuild but hopefully this issue can be useful for others with similar issues.
