### ISSUE TITLE
Transforms `async: async` in objects to shorthand `async` for old platforms

### ISSUE THREAD

**Issue by jorenbroekema** [evanw/esbuild#3910]
```js
function foo(async) {
  const obj = { async: async };
  return obj;
}
foo(5);
```
The above pattern should not be transformed at all.

Actual behavior:
```js
function foo(async) {
  const obj = { async };
  return obj;
}
foo(5);
```

Reproduce (after creating a `foo.js` file locally): `npx esbuild foo.js --outfile=_foo.js --target=es6`

Real world use case: https://github.com/microsoft/tslib/blob/main/tslib.js#L359 
TS helper that gets injected in many many bundles, so when transpiling it with ESBuild this should remain intact, else it does not work in old JavaScript sandboxes such as the one that is used by [Figma](https://www.figma.com/) Plugins.

This issue is very specific to the "async" keyword, which isn't technically a reserved keyword in the same way that "await" is, because its meaning (async) can always be determined by its context to whether it's a variable or keyword. It's a bit "special" in that sense, and I'm guessing this is why in old JS engines it creates the error:
<img width="572" alt="Screenshot 2024-09-12 at 14 09 34" src="https://github.com/user-attachments/assets/3035c683-9a54-4739-8494-c4be5e23bbbc">

**Comment by evanw** [comment]
It looks like this is because Figma is running the code through https://esprima.org/ (specifically https://static.figma.com/scripts/esprima-4.0.1.min.js), which is an outdated/abandoned JavaScript parser that hasn't had a new release in many years. So Figma can't update their version of esprima to fix this bug because it's an abandoned project. If Figma wanted to fix this, they could use a modern and maintained JavaScript parser instead (e.g. Babel).

I'm closing this issue because I'm not going to add a special compiler target to esbuild for esprima. I recommend the `object-extensions` workaround for now.

**Comment by jorenbroekema** [comment]
Understandable! thanks for checking things out and explaining :)
