### ISSUE TITLE
Incorrect polyfill __knownSymbol lookups for Symbol.dispose (and probably others)

### ISSUE THREAD

**Issue by thodnev** [evanw/esbuild#3920]
### Problem statement
Esbuild uses `__knownSymbol` in generated code for `Symbol` lookups, that relies on [`Symbol.for()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/for)
https://github.com/evanw/esbuild/blob/d34e79e2a998c21bb71d57b92b0017ca11756912/internal/runtime/runtime.go#L78
However, the property `dispose` does not get set on [global `Symbol`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) by the generated code.
This results in `Symbol.dispose` resolving to `undefined` in the generated code, thus making the objects non-disposable.
Which further causes the `TypeError: Object not disposable` runtime error (Firefox 131.0b9 & Chromium 129.0.6668.58 tested, but sure the others will fail as well). Error is produced by this fragment:
https://github.com/evanw/esbuild/blob/d34e79e2a998c21bb71d57b92b0017ca11756912/internal/runtime/runtime.go#L510-L514

### Temporary (and hackish) solutions right now
One possible solution will be to polyfill the `Symbol.dispose` in TS ourselves, like the following:
```TS
Symbol.dispose ??= Symbol.for('Symbol.dispose')
```
But:
- It does not correspond to the polyfill [provided in the official](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-2.html) TS documentation:
  ```TS
  Symbol.dispose ??= Symbol("Symbol.dispose");
  ```
  (the one provided there simply won't work, as per [Symbol spec](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol), the `Symbol(key)` is guaranteed to return a **distinct** object every time, even for the same key
- It is very obscure to find a correct solution, as it requires digging inside toolchain internals
- Why does the user have to polyfill it himself everywhere, yet more, in his source files

### Proper fix proposal
Add to the generated code a procedure to test&set `dispose` property on `Symbol` object, something like:
```JS
if (Symbol.dispose === undefined) {
    Object.defineProperty(Symbol, 'dispose', {value: Symbol.for('Symbol.dispose')})
}
```

### Examples
Generated code (as of now):
- Test TS fragment:
  ```TS
   class TestCls implements Disposable {
       [Symbol.dispose]() {
           console.log('I was disposed')
       }
   }
   ```
- Output JS fragment built with `esbuild dispose.ts --target=es2022 --outfile=dispose.js`
   ```JS
   class TestCls {
     [Symbol.dispose]() {
       console.log("I was disposed");
     }
   }
   ```
Please find the TS input and the corresponding Esbuild JS output attached
(built with `esbuild dispose.ts --target=es2022 --outfile=dispose.out.js`) :
[dispose.ts.txt](https://github.com/user-attachments/files/17091230/dispose.ts.txt)
[dispose.out.js.txt](https://github.com/user-attachments/files/17091231/dispose.out.js.txt)

**Comment by evanw** [comment]
Sorry, I don't understand. You need to polyfill `Symbol.dispose` before you use it with esbuild, just like all other new APIs. This is because esbuild transforms newer syntax to older syntax for you but does not polyfill APIs for you. And polyfilling `Symbol.dispose` should already work fine. You can do it however you like. For example, you can do it exactly as TypeScript's documentation tells you to do it (as you pointed out):

```js
Symbol.dispose ??= Symbol("Symbol.dispose");

function demo() {
  class Foo {
    constructor() { console.log('constructor') }
    [Symbol.dispose]() { console.log('dispose') }
  }

  using foo = new Foo
}

demo()
```

If you [build this with esbuild](https://esbuild.github.io/try/#dAAwLjI0LjAALS1zdXBwb3J0ZWQ6dXNpbmc9ZmFsc2UAU3ltYm9sLmRpc3Bvc2UgPz89IFN5bWJvbCgiU3ltYm9sLmRpc3Bvc2UiKTsKCmZ1bmN0aW9uIGRlbW8oKSB7CiAgY2xhc3MgRm9vIHsKICAgIGNvbnN0cnVjdG9yKCkgeyBjb25zb2xlLmxvZygnY29uc3RydWN0b3InKSB9CiAgICBbU3ltYm9sLmRpc3Bvc2VdKCkgeyBjb25zb2xlLmxvZygnZGlzcG9zZScpIH0KICB9CgogIHVzaW5nIGZvbyA9IG5ldyBGb28KfQoKZGVtbygp) and run it, it will output the following:

```
constructor
dispose
```

So everything already appears to be working correctly. This happens because `__knownSymbol` just returns the value of `Symbol[name]` if it's present. If you polyfill `Symbol.dispose` before using it, then `Symbol['dispose']` will be your polyfill. The stuff with `Symbol.for` is irrelevant for your use case. It's only there for obscure compatibility reasons with code generated by Babel.

You have to polyfill `Symbol.dispose` with esbuild just like you have to do with TypeScript. This is already [in esbuild's documentation](https://esbuild.github.io/api/#target):

> Note that this is only concerned with syntax features, not APIs. It does not automatically add [polyfills](https://developer.mozilla.org/en-US/docs/Glossary/Polyfill) for new APIs that are not used by these environments. You will have to explicitly import polyfills for the APIs you need (e.g. by importing [core-js](https://www.npmjs.com/package/core-js)). Automatic polyfill injection is outside of esbuild's scope.

**Comment by thodnev** [comment]
@evanw Thank you for the clarification.
In the case the user has not provided his own polyfill, maybe there should be a hint in the error message itself. This would largely  reduce uncertainty for the user.
Now the error message states `TypeError: Object not disposable`. Which leads to doubts that probably there is something wrong with the object itself.
What about `TypeError: Object not disposable or Symbols.dispose not provided`?
