### ISSUE TITLE
Mark all external except the source directory possible?

### ISSUE THREAD

**Issue by mschering** [evanw/esbuild#3936]
Hi,

Thank you for this great bundler! 

If I have a folder structure like this

-modulea
 - a1
   - src
       - index.ts
       - classa.ts
   - package.json
-moduleb
 - b1
-modulec
 - c1 
- etc. more separate modules with separate package.json here

I want to be able to import from other modules without compling them with typescript. There can be an inifinite number of modules. So I would like to mark all as external:

esbuild src/index.ts --external:../../* 

But when I do this then classa.ts is also not bundled.

So is there something like this possible:

esbuild src/index.ts --external:../../* --external=!./src

exclude all parents except the "src" directory?

PS: I also tried to do --external=@groupoffice/* because I use tsconfig.paths to map those. This works but then it doesn't transform @groupoffice/modulea to the real js path. It does do this when you mark them external with a file path. Is there a reason for that behaviour?

Thanks for an answer in advance!

Best regards,
Merijn

**Comment by hyrious** [comment]
There's no negative glob pattern support for now. You can write a plugin to carefully pick modules to be externalized:

```js
{
  name: 'externalize-everything-except-src',
  setup(build) {
    let src = path.resolve('src')
    // TODO: filter less
    build.onResolve({ filter: /(.*)/ }, async (args) => {
      if (!args.pluginData?.resolving) {
        let params = {...args}
        delete params.path
        params.pluginData = { resolving: true }
        let result = await build.resolve(args.path, params)
        // TODO: use a more robust way to test parent path
        if (result.path.startsWith(src)) {
          // include this module
        } else {
          // TODO: modify args.path here, e.g. resolve tsconfig paths
          return { path: args.path, external: true }
        }
      }
    });
  },
}
```

> &hellip;it doesn't transform @groupoffice/modulea to the real js path. &hellip;Is there a reason for that behaviour?

This is just because the externalize happens in different phases: If you mark the import path as external literally, like matching `@mod/name`, esbuild won't try to resolve this module and it just leaves it as is. If you specify the file path, like saying `--external=path/to/the/file`, esbuild will firstly resolves the module name, and finds that this file is configured as externalized, so it leaves the resolved path in the final bundle.

**Comment by mschering** [comment]
Thanks for your helpful answer! I went that route and it works fine now!
A negative glob pattern would still be nice as it would have been much simpler to accomplish my and perhaps other people's goal.
