### ISSUE TITLE
How to dynamically add the existing ast syntax tree in esbuild like 'babel-import-plugin'

### ISSUE THREAD

**Issue by zhusjfaker** [evanw/esbuild#398]
In Babel, there is a babel-import-plugin that can dynamically add additional import dependencies to the file according to the existing import statements,

```
import { Button } from '@bytedesign/web-react'
import  '@bytedesign/web-react/Button/lib/index.css'
```
api_impl.go line 635
```

if !log.HasErrors() {
	// add import 
	bundle.AddNewImport()
        results = bundle.Compile(log, options)
}

```

```
func (b *Bundle) AddNewImport() {
	newpath := &ast.Path{Text: "@bytedesign/web-react/es/Select/style/index.css", IsAbsolute: false}
	newimport := &ast.ImportRecord{Path: *newpath}
	b.files[1].ast.ImportRecords = append(b.files[1].ast.ImportRecords, *newimport)
}

```

How to implement the above code

**Comment by evanw** [comment]
When the plugin API is released (see issue #111), this will trivially be possible by writing an esbuild loader plugin that inserts those lines of JavaScript at the start of the source code before the original file contents using string concatenation. You should already be able to do this with the current work-in-progress plugin API on the `plugins` branch.

However, that isn't ideal if you are using source maps because it will throw off line count. I am planning to add an additional API to allow for inserting optional lines before and after the original file contents without altering the line count. That API has not been implemented yet.

Note that this does not involve doing any AST manipulation. I am not planning for AST manipulation to be part of the esbuild plugin API.

**Comment by zhusjfaker** [comment]
```
	// Stop now if there were errors
	if !log.HasErrors() {
		// Scan over the bundle
		mockFS := fs.MockFS(make(map[string]string))
		resolver := resolver.NewResolver(mockFS, log, options)
		bundle := bundler.ScanBundle(log, mockFS, resolver, nil, options)

		// Stop now if there were errors
		if !log.HasErrors() {
			// Compile the bundle
                         // i can design to use nodejs to transfer the location of the golang *. so plugin-file
			// handleAst(bundle.ast) // import golang 1.5 plugin funtion  and exec it 
			results = bundle.Compile(log, options)
		}
	}
```

Can't use the golang 1.5 plugin method to extend the result of AST execution directly and then assemble it?

In this way, the code compilation can be executed efficiently in golang, and the content of JS can not be transmitted in the process. I plan to propose a pull request in this way

**Comment by zhusjfaker** [comment]
After reviewing the issue discussion, I personally think that we only need to ensure that the plug-in and the main framework language structure are consistent, and do not need to be responsible for any integrated plug-in file *.so. This allows more people to enrich the functions of esbuild through plug-ins and reduce one's development burden.

**Comment by zheyaoa** [comment]
How did you solve it in the end?

**Comment by zhusjfaker** [comment]
> How did you solve it in the end?

https://esbuild.github.io/plugins/#http-plugin 

transform code with babel through the transform in the plugin provided by esbuild

**Comment by unphased** [comment]
Is babel still the standard for js/ts code AST manipulation? I'm doing some of that for my app but really want to move away from having babel as my core "linker". I would be much more comfortable if i can only leverage babel for its AST transformation and use esbuild instead. Thanks
