### ISSUE TITLE
Minifier: `#__PURE__` marked optional chain expression with side-effect in arguments

### ISSUE THREAD

**Issue by KermanX** [evanw/esbuild#3991]
### **Current behavior**:

```js
/*#__PURE__*/ unknown?.(effect()) // =====> effect();
```

If `unknown` is nullish, in the original code, `effect()` won't be called, but in the output code, it will.

[Playground link](https://esbuild.github.io/try/#dAAwLjI0LjAALS1taW5pZnkALyojX19QVVJFX18qLyB1bmtub3duPy4oZWZmZWN0KCkp)

### **Expected behavior**:

The output should be either:

- Preserve the original code
- `unknown !== null && unknown !== undefined && effect()`

**Comment by evanw** [comment]
The behavior of esbuild matches the behavior of Terser (https://try.terser.org/) and UglifyJS (https://skalman.github.io/UglifyJS-online/). These annotations don't have a formal specification but are instead derived by converging on the behavior of other tools. So I think esbuild should behave this way since these other tools behave this way too, even though I see your point that the annotation seems to be meaningless. IMO it's important for all tools in the JavaScript ecosystem to treat these annotations the same way to simplify the ecosystem and avoid divergence in behavior. If you don't want this to happen when using esbuild, then you should remove the annotation from the code.
