### ISSUE TITLE
[QUESTION] - JSX components minification

### ISSUE THREAD

**Issue by gc-victor** [evanw/esbuild#3996]
Is there a naming convention for JSX components minified under preserve mode? I have seen that there is an option to avoid using `minify-identifiers` that could work for my use case 🤔

**Comment by evanw** [comment]
The typical JSX naming convention is preserved under minification. Specifically the minifier doesn't minify JSX names starting with a lowercase letter (which typically represent HTML elements) and ensures that JSX names starting with an uppercase letter are minified to a name that starts with an upper case letter (so other tools won't mistake them for HTML elements).

**Comment by gc-victor** [comment]
@evanw I thought that was the pattern, but I have cases where the minification converts it to an underscore and a dollar sign.

**Comment by evanw** [comment]
Underscore and dollar sign are both not considered to start HTML element names by all common JSX tooling (e.g. [Babel](https://babel.dev/repl#?browsers=safari%2016&build=&builtIns=false&corejs=3.21&spec=false&loose=true&code_lz=B4AgvCA8AmCWBuB6AfAKAJ7igEQSjWkA-rkmphJACSn5A&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3%2Ctypescript&prettier=false&targets=&version=7.26.2&externalPlugins=%40babel%2Fplugin-syntax-explicit-resource-management%407.20.0&assumptions=%7B%7D), [esbuild](https://esbuild.github.io/try/#dAAwLjI0LjAALS1sb2FkZXI9anN4AHggPSA8ZGl2Lz4KeSA9IDxEaXYvPgp5ID0gPF9EaXYvPgp5ID0gPCREaXYvPgo), [TypeScript](https://www.typescriptlang.org/play/?#code/B4AgvCA8AmCWBuB6AfAKAJ7igEQSjWkA+rkmphJACSn5A)), so this shouldn't be a problem. Please describe why this is a problem for you.

**Comment by gc-victor** [comment]
Oh, great! It is not a problem per se. I'm creating a JSX transform for server-side rendering in Rust that consumes the output of esbuild. The problem was not having that information. Could you point me to any documentation or code to check if there are other cases?

**Comment by evanw** [comment]
Documentation is here: https://legacy.reactjs.org/docs/jsx-in-depth.html#user-defined-components-must-be-capitalized

Here's what various libraries do:
* Babel: https://github.com/babel/babel/blob/e66517c1765cf6fb2c39ea0525b1a5d2141ab421/packages/babel-types/src/validators/react/isCompatTag.ts
* esbuild: https://github.com/evanw/esbuild/blob/9eca46464ed5615cb36a3beb3f7a7b9a8ffbe7cf/internal/js_parser/js_parser.go#L4990-L4993
* TypeScript: https://github.com/microsoft/TypeScript/blob/b263cc4b2ef12ae013526a3d8808b6716146586a/src/compiler/utilities.ts#L6183-L6186

The rule is basically that names are only for HTML elements if they start with a character from `a` to `z` (inclusive) or if they contain `-` or `:` anywhere in the string. All other names are for JavaScript variables instead of HTML elements.

**Comment by gc-victor** [comment]
Thanks!

**Comment by gc-victor** [comment]
Thank you for your support and the outstanding work on esbuild!
