### ISSUE TITLE
Use relative paths when setting the baseUrl and paths properties in compilerOptions when using tsconfigRaw

### ISSUE THREAD

**Issue by giangm9** [evanw/esbuild#4014]
I have 2 questions related to using tsconfigRaw in esbuild:

- According to the official TypeScript documentation, when setting the two properties baseUrl and paths, the paths within them will be relative to the location of the tsconfig.json file. In esbuild, when setting these two properties, which directory will the paths be relative to?
- How can I make VSCode Intellisense resolve modules according to the settings in tsconfigRaw instead of tsconfig.json?

**Comment by evanw** [comment]
I believe esbuild behaves as if `tsconfigRaw` is contained in a file in the current working directory:

https://github.com/evanw/esbuild/blob/199a0d38e4e4191e970f2a0a25e50e5c7ae36464/internal/resolver/resolver.go#L337

But if you are using it for path-specific settings, I recommend creating a `tsconfig.json` file and passing the path to `tsconfig` instead of using `tsconfigRaw`. That will make this easier to reason about and also make this automatically work with VSCode.
