### ISSUE TITLE
wasm filetype loader

### ISSUE THREAD

**Issue by tonyhb** [evanw/esbuild#408]
Adding a quick request to support .wasm filetypes being bundled, similar to how webpack works.  The specific use case:

1. Compile a package using wasm-bindgen or [wasm-pack with `--target bundler`](https://rustwasm.github.io/docs/wasm-bindgen/reference/deployment.html#bundlers)
2. Use this package within an esbuild project.

The alternative right now is to use wasm-bindgen with a target of web and load the wasm file via fetch.

**Comment by evanw** [comment]
It seems to me like it would be best to experiment with doing this as a plugin, which will be possible once the plugin API is released. The plugin API is currently a work in progress, and is being tracked as issue #111.

**Comment by evanw** [comment]
I just tried this out and it seems pretty straightforward. Here's an example plugin:

```js
let path = require('path')
let util = require('util')
let fs = require('fs')

let wasmPlugin = plugin => {
  plugin.setName('wasm-loader')

  plugin.addResolver({ filter: /\.wasm$/ }, args => ({
    path: path.isAbsolute(args.path) ? args.path : path.join(path.dirname(args.importer), args.path),
    namespace: args.namespace === 'wasm-stub' ? 'wasm-binary' : 'wasm-stub',
  }))

  plugin.addLoader({ filter: /.*/, namespace: 'wasm-binary' }, async (args) =>
    ({ contents: await util.promisify(fs.readFile)(args.path), loader: 'binary' }))

  plugin.addLoader({ filter: /.*/, namespace: 'wasm-stub' }, async (args) => ({
    contents: `import wasm from ${JSON.stringify(args.path)}
      export default async (imports) =>
        (await WebAssembly.instantiate(wasm, imports)).instance.exports` }))
}
```

If you generate WebAssembly using `wasm-pack` with this Rust code:

```rust
#[wasm_bindgen]
pub fn add(x: i32, y: i32) -> i32 {
  x + y
}
```

You can use it like this:

```js
import load from './example.wasm'
load().then(({ add }) => {
  console.log(add(1, 2))
})
```

Obviously real-world code would be somewhat more complicated but the current plugin API seems sufficient to enable this functionality.

**Comment by evanw** [comment]
Plugin documentation has been released: https://esbuild.github.io/plugins/. You should be able to do this yourself now. There is even an example WebAssembly plugin as a starting point: https://esbuild.github.io/plugins/#webassembly-plugin.

**Comment by tompark** [comment]
Hi, I was trying to use esbuild to bundle the "hello world" example from the rustwasm tutorials (nearly identical "hello world" code is given in the rustwasm game-of-life, wasm-bindgen, and wasm-pack tutorials), but the plugin that's given at https://esbuild.github.io/plugins/#webassembly-plugin wasn't working for me as-is, and it wasn't clear to me how to address it.

I finally got it working but -- perhaps due to my lack of experience with js and js bundlers -- it took me a few days of banging my head on it. I thought I'd document what I did here because this closed issue is the first thing I found when I was trying to get it working, and it's most likely where someone else having the same problem will find this comment.

Here's the initial problem I was having:

After getting the example code to work with webpack, as assumed in the tutorials, I reconfigured it to run without a bundler, using `wasm-pack build --target web`. This required moving directories around so the http server has access to the bindgen pkg files.

It seemed to make sense to me that that the next step before using esbuild to bundle this version of the code would be to do the Rust build using `wasm-pack build --target bundler`. (I now think that's a mistake, but that's what I did.)

Then I created a file esbuild.config.js containing the example plugin code, and this at the bottom:
``` esbuild.config.js
require('esbuild').build({
   entryPoints: ['index.js'],
   outfile: 'bundle.js',
   bundle: true,
   minify: false,
   plugins: [wasmPlugin],
}).catch(err => {
   process.stderr.write(err.stderr);
   process.exit(1)
})
```

When running esbuild, it would create the output file, but generate warnings:
``` bash
$ node esbuild.config.js 
 > ../pkg/wasm_hello_world_bg.js: warning: No matching export for import "memory"
    11 │     if (cachegetUint8Memory0 === null || cachegetUint8Memory0.buffer !== wasm.memory.buffer) {
       ╵                                                                               ~~~~~~
 > ../pkg/wasm_hello_world_bg.js: warning: No matching export for import "__wbindgen_malloc"
    81 │     var ptr0 = passStringToWasm0(name, wasm.__wbindgen_malloc, wasm.__wbindgen_realloc);
       ╵                                             ~~~~~~~~~~~~~~~~~
 > ../pkg/wasm_hello_world_bg.js: warning: No matching export for import "__wbindgen_realloc"
    81 │     var ptr0 = passStringToWasm0(name, wasm.__wbindgen_malloc, wasm.__wbindgen_realloc);
       ╵                                                                     ~~~~~~~~~~~~~~~~~~
 > ../pkg/wasm_hello_world_bg.js: warning: No matching export for import "greet"
    83 │     wasm.greet(ptr0, len0);
       ╵          ~~~~~
4 warnings
```

When running the resulting bundle.js in a browser, the browser console would say something like this:
``` bash
TypeError: malloc is not a function. (In 'malloc(buf.length)', 'malloc' is undefined)
	passStringToWasm0 — bundle.js:71
	greet — bundle.js:99
```

The output bundle.js file had put null ptrs in the greet call to passStringToWasm0():
``` bundle.js
  var require_wasm_hello_world_bg = __commonJS((exports, module) => {
    __export(exports, {
      __wbg_alert_84709ef345bc4a68: () => __wbg_alert_84709ef345bc4a68,
      greet: () => greet2
    });
[...]
    function greet2(name) {
      var ptr0 = passStringToWasm0(name, void 0, void 0);
      var len0 = WASM_VECTOR_LEN;
      (void 0)(ptr0, len0);
    }
```

That function looked like this before it was bundled:
``` wasm_hello_world_bg.js
export function greet(name) {
    var ptr0 = passStringToWasm0(name, wasm.__wbindgen_malloc, wasm.__wbindgen_realloc);
    var len0 = WASM_VECTOR_LEN;
    wasm.greet(ptr0, len0);
}
```

Note that when running the `wasm-pack build` command, it generates a 'pkg' directory containing the wasm file, named in the form of `<project_name>_bg.wasm`. Also depending on whether the target is 'web' or 'bundler' it will generate one or two js files.

In my case, using the `--target bundler` option, wasm-bindgen was generating a file called `wasm_hello_world_bg.js`. At the top of this file was the import statement that triggered the esbuild plugin:
`import * as wasm from './wasm_hello_world_bg.wasm';`

I had to change that line to this:
`export * as wasm from './wasm_hello_world_bg.wasm';`

After that, esbuild did not issue warnings and its bundled version of greet() looked like the unbundled version inside wasm_hello_world_bg.js.

However, this didn't fix the problem. When running this bundle.js in the browser, the console outputs something like:
``` bash
[Error] ReferenceError: Can't find variable: wasm
	greet2 (bundle.js:116)
	(anonymous function) (bundle.js:144)
	Global Code (bundle.js:145)
```

After tracking what happens in the esbuild WebAssembly plugin during the build.onLoad hook for 'wasm-stub', and I never saw the `WebAssembly.instantiate` call in the plugin actually work. Specifically, the plugin contains a script that does this:
``` esbuild.config.js
import wasm from ${JSON.stringify(args.path)}
export default (imports) =>
   WebAssembly.instantiate(wasm, imports).then(
      result => result.instance.exports)
```
And it's not clear where the `imports` comes from.
I could see that the wasm file, when converted to wat, contained one import statement, so I tried to supply that as an import to the instantiate call, but never got it to work. The instantiate() call would not trigger an exception or promise rejection, but at best it only returned an object that looked like this: `{instance: {}, module: {}}`. 

This is the point where I realized that, above, @evanw said: "an example WebAssembly plugin as **a starting point**"

Doh, I hadn't paid attention to this before, and assumed it would work as-is.

💡

At that point I went back to `wasm-pack build --target web` because that generates code for calling the WebAssembly.instantiate() with a serious `imports` object that looks like this:
``` wasm_hello_world_bg.js
    const imports = {};
    imports.wbg = {};
    imports.wbg.__wbg_alert_84709ef345bc4a68 = function(arg0, arg1) {
        alert(getStringFromWasm0(arg0, arg1));
    };
    imports.wbg.__wbg_new_59cb74e423758ede = function() {
        var ret = new Error();
        return addHeapObject(ret);
    };
    imports.wbg.__wbg_stack_558ba5917b466edd = function(arg0, arg1) {
        var ret = getObject(arg1).stack;
        var ptr0 = passStringToWasm0(ret, wasm.__wbindgen_malloc, wasm.__wbindgen_realloc);
        var len0 = WASM_VECTOR_LEN;
        getInt32Memory0()[arg0 / 4 + 1] = len0;
        getInt32Memory0()[arg0 / 4 + 0] = ptr0;
    };
    imports.wbg.__wbg_error_4bb6c2a97407129a = function(arg0, arg1) {
        try {
            console.error(getStringFromWasm0(arg0, arg1));
        } finally {
            wasm.__wbindgen_free(arg0, arg1);
        }
    };
    imports.wbg.__wbindgen_object_drop_ref = function(arg0) {
        takeObject(arg0);
    };
```

I didn't want to embed that code into the esbuild wasm plugin, so I removed the `build.onload` callback for 'wasm-stub' and used the modified plugin only as a binary file loader:
``` esbuild.config.js
let wasmPlugin = {
  name: 'wasm',
  setup(build) {
    let path = require('path')
    let fs = require('fs')

    // Resolve ".wasm" files to a path with a namespace
    build.onResolve({ filter: /\.wasm$/ }, args => {
      if (args.resolveDir === '') {
        return // Ignore unresolvable paths
      }
      return {
        path: path.isAbsolute(args.path) ? args.path : path.join(args.resolveDir, args.path),
          namespace: 'wasm-binary',
      }
    })

    // Virtual modules in the "wasm-binary" namespace contain the
    // actual bytes of the WebAssembly file. This uses esbuild's
    // built-in "binary" loader instead of manually embedding the
    // binary data inside JavaScript code ourselves.
    build.onLoad({ filter: /.*/, namespace: 'wasm-binary' }, async (args) => ({
      contents: await fs.promises.readFile(args.path),
      loader: 'binary',
    }))
  },
}
```

Then, use esbuild to bundle that bindgen code and call it correctly. Specifically, the `index.js` used to look like this:
``` index.js
import * as wasm from "wasm-hello-world";
wasm.greet("World");
```

But if you change it to this, then the whole thing works in the browser:
``` index.js
import { default as wasmbin } from './pkg/wasm_hello_world_bg.wasm';
import init, {greet} from "wasm-hello-world";

async function run() {
	await init(wasmbin);
	greet("World");
}
run();
```

Note that by doing this, esbuild will base64-encode the wasm file during bundling. This does bloat your bundle.js download (approx 30%) compared to downloading the wasm file separately as a binary from your http server, so if your wasm is very large then you probably don't want to bundle it.

If you'd rather not incur that bloat, then remove the 'import wasmbin' line and replace the above `init(wasmbin)` call with this:
`await init("./pkg/wasm_hello_world_bg.wasm");`

Hope this is helpful to someone.

**Comment by Rizary** [comment]
@tompark I stumbled upon this issue when searching how to package rust wasm using esbuild. Does the plugin run `wasm-pack build --target web` by itself, or should we run it inside `package.json`?

**Comment by tompark** [comment]
@Rizary Sorry for the slow reply, I didn't see a notification until just now.

I was running the `wasm-pack build --target web` command prior to bundling it using `node esbuild.config.js`. (btw, nowhere did I see anyone say, "Run esbuild using this command: `node esbuild.config.js`", which I suppose is obvious to js/node developers, but it took me a little while to realize that, and I'm still not sure if that's the conventionally correct way to do it.)

I suppose you could arrange these in `package.json` as npm scripts, and use nodemon or smtg like that to watch/monitor changes in your code and reload in your browser for testing.

**Comment by Rizary** [comment]
@tompark thank you very much, I'll try to follow your example.

**Comment by DylanSp** [comment]
@tompark Thanks a ton for the working example; I used it to get Rust -> WASM working in an [Elixir Phoenix project](https://github.com/DylanSp/puccinia-basic-poc).

**Comment by logankeenan** [comment]
@tompark Thank you so much for your thorough write up! You saved me a lot of time!

This also works for anyone who is just using the `wasm32-unknown-unknown` compile target and [wasm-bindgen](https://github.com/rustwasm/wasm-bindgen)

Example:

Building wasm
`cargo build --target wasm32-unknown-unknown`

Building with wasm-bindgen. (debug or release)
`wasm-bindgen target/wasm32-unknown-unknown/debug/your-lib-name.wasm --out-dir ./wasm-out`

**Comment by johnnybenson** [comment]
@tompark 🍺

**Comment by chaosprint** [comment]
@tompark thank you

**Comment by akeeee** [comment]
@tompark thank you 🙌🏻
