### ISSUE TITLE
Bug: let followed by a new line fails

### ISSUE THREAD

**Issue by galvez** [evanw/esbuild#409]
Snippet in question:

```
function foo () {
  let
    bar
  bar = 1
  return bar
}
```

Error:

```
Module parse failed: The keyword 'let' is reserved
```

**Comment by evanw** [comment]
Interesting. This behaves like this in esbuild because it's necessary to be able to pass test262 conformance tests like [this one](https://github.com/tc39/test262/blob/4bcc582183f8c24dbd29e2e0e33e57a7c70db460/test/language/statements/if/let-identifier-with-newline.js). But it looks like perhaps these ASI rules should only apply in a single-statement context. I will fix this in the next release.
