### ISSUE TITLE
Plugins regression, modules returned from generated code are not resolved

### ISSUE THREAD

**Issue by zmitry** [evanw/esbuild#416]
My plugin, if I return react import then I get the error that says `/src/assets/icons/location_endpoint_app.svg:2:41: error: Could not resolve "react" (mark it as external to exclude it from the bundle)`
```
	plugin.AddLoader(
		api.LoaderOptions{Filter: `\.svg`, Namespace: "svg"},
		func(args api.LoaderArgs) (res api.LoaderResult, err error) {
			dat, err := os.Open(args.Path)
			if err != nil {
				return res, err
			}

			svg, err := svgparser.Parse(dat, true)
			if err != nil {
				return res, err
			}
			contents := fmt.Sprintf(`
      import {createElement as jsx} from "react";
      export function ReactComponent(props) {
        return <xml %s {...props}>
        %s
        </xml>
      }
      `, attributesToString(svg.Attributes), svgToJsx(svg.Children))
			res.Contents = &contents
			res.Loader = api.LoaderTSX
			return res, nil
		},
	)
```

**Comment by evanw** [comment]
Thanks for flagging this. I changed this recently because I realized that trying to interpret import paths inside a module that isn't in the `file` namespace may not make sense. For example, the path of the importer module may be a URL and it may not make sense to interpret import paths as local to the file system at all.

I have added a new optional return value called `ResolveDir` for loader plugins to provide a directory on the local file system to use when import paths are resolved using the default behavior. If that directory is not provided, the default resolver will only run if the importer module is in the `file` namespace. This `ResolveDir` value is also exposed to resolver plugins for them to make use of.

So in your case you should be able to get this working again by doing one of these things:

* You can just leave the `.svg` paths in the default `file` namespace instead of using a resolver to change them to the `svg` namespace. Then esbuild will automatically know which directory to use for path resolution.

* If you want the file to still be loaded in the `svg` namespace, you should be able to add something like `res.ResolveDir = filepath.Dir(args.Path)` to the above code to tell esbuild how to resolve paths inside that namespace.

**Comment by zmitry** [comment]
Could you point me out to ResolveDir in plugins, I didn't find any reference to it.

**Comment by zmitry** [comment]
![Uploading image.png…]()

**Comment by evanw** [comment]
> Could you point me out to ResolveDir in plugins, I didn't find any reference to it.

Here is the definition in `api.go`:

```go
type LoaderResult struct {
	Errors   []Message
	Warnings []Message

	Contents   *string
	ResolveDir string // <==
	Loader     Loader
}
```
