### ISSUE TITLE
[Questions] support for angular applications

### ISSUE THREAD

**Issue by ayox** [evanw/esbuild#42]
`esbuild` looks promising, I want ask if there is there a support for angular applications, or do you plan to support angular application?

**Comment by evanw** [comment]
I'm not familiar with Angular but it looks like Angular has a [custom compiler](https://angular.io/guide/aot-compiler) that is pretty different than other JavaScript build tools. So I don't think Angular applications will work with esbuild.

I'm only intending for esbuild to target a certain sweet spot of use cases (bundling JavaScript, TypeScript, and maybe CSS). I don't think Angular is mainstream enough to warrant building into the core of esbuild, and since esbuild doesn't have plugins it won't be possible to add Angular support to esbuild.

**Comment by thekip** [comment]
Actually with some manual working it's possible to build Angular with tools such as es-build. Angular has a standlone compiler which can be used to compile angular components to regular typescript files and than you can hook it up with esbuild. 

Despite the fact this is possible it's going to be a really hard way, because angular teams doesn't care too much about cases where angular apps built with tooling outside of angular's ecosystem.

**Comment by sp90** [comment]
@thekip do you have any examples on this setup that I could look into?

**Comment by thekip** [comment]
The main idea is to run angular compiler on your angular project to compile all html/ts files into regular js:

```bash
ngc --build ./tsconfig.app.json --outDir ./ngc
```

`ngc` stands for angular compiler and it is a drop-off replacement for `tsc` command (Typescript Compiler)

And then run any of building tool which can work with ES files, such as esbuild. 

You will probably have a problems with scss files if you use them because ngcc compiler understand only pure css. 
The output still will not be the same to what AngularCLI is produce, because they have few additional steps in pipeline (BuildOptimizer, conditional loading bundles es5/es2015, service workers, index.html production and etc)

PS.
Angular compiler is implented as set of custom typescript transformers using public typescript api. So you can try too hook up this transformers into other tools which use typescript natively. But there are no documentation about angular compiler internals and only on way to find some detail of implementation is digging into angular CLI code.

**Comment by literalpie** [comment]
To build on @thekip's comment, I got pretty far just by doing:
```
    "ngcc": "ngcc",
    "esbuild": "ngc build -p tsconfig.app.json && esbuild ./out-tsc/app/main --bundle --minify --splitting --outdir=out --format=esm",
```
then running `npm run ngcc` once and `npm run esbuild` to build the project. I then had to manually copy the `index.html` file to the folder where the main.js file was output, and add `<script src="main.js" defer></script>` to the index.html

This feels pretty close, but I'm getting the error:
> Error: Angular JIT compilation failed: '@angular/compiler' not loaded! - JIT compilation is discouraged for production use...

I'm probably not going to look into this much more because it still requires running `ngc` so the speed improvements will probably be very minor. I'm just putting this here in case it helps others.

**Comment by gorshkov-leonid** [comment]
Hi, here is a working experiment for a [simple app](https://angular.io/tutorial/toh-pt0)

**package.json**
"@angular-builders/custom-webpack": "~11.1.1"
"esbuild-loader": "~2.11.0"

**angular.json**
_projects.architect.serve.builder_ "@angular-builders/custom-webpack:dev-server"
_projects.architect.build.builder_  "@angular-builders/custom-webpack:browser"
with options
```
"options": {
            "customWebpackConfig": {
              "path": "./custom-webpack.conf.js",
              "replaceDuplicatePlugins": true
            },
...
}
```


**custom-webpack.conf.js**
```
const ESBuildPlugin = require("esbuild-loader/dist/plugin").default;

module.exports = function (config, opts, {target, configuration}) {
    config.module = {
        ...config.module,
        rules: [
            ...config.module.rules.filter(rule => !rule || !rule.use || !rule.use.loader || !rule.use.loader.includes("/babel-loader/")),
            {
                test: /\.ts$/,
                loader: "esbuild-loader",
                options: {
                    loader: "ts",
                    target: "es2018"
                }
            },
            {
                test: /\.js$/,
                loader: "esbuild-loader",
                options: {
                    target: "es2018"
                }
            }
        ]
    }

    var opts = undefined;
    if (target === "serve") {
        opts = {
            options: {
                minify: false
            }
        }
        config.devtool = "none";
    }
    else {
        config.mode = "production";    
    }
    config.plugins = [
        ...config.plugins,
        new ESBuildPlugin(opts)
    ]
    return config
}

```

It seems that 
1. It takes about the same time to build app
2. I am not sure, but there will be a problem with dynamic chunks when tree-shaking is enabled.

**Comment by jpike88** [comment]
"I don't think Angular is mainstream enough"

There are actually more jobs on LinkedIn looking for angular skillsets than react. I fail to see how you don't consider Angular to be squarely in the 'mainstream' category of frameworks, and by some perspectives even consider it the most prominent.

More reading:
https://www.codeinwp.com/blog/angular-vs-vue-vs-react/

**Comment by vzakharov-rxnt** [comment]
I agree, there is lots of Angular in enterprise.
Enterprise has virtually unlimited money, especially when it comes to tooling.
You might get sponsored/promoted by those big companies who need it.

**Comment by jpike88** [comment]
@evanw to @vzakharov-rxnt’s point, it would be extra attractive to the likes of Google as it would support their framework and be written in their language.

**Comment by AnthonyLenglet** [comment]
I've done a bit of digging on my end regarding using esbuild

best I could get was this
`"build:esbuild": "ngc build -p tsconfig.app.json --target es5 && esbuild out-tsc/app/main --outdir=esbuild-dist --splitting --bundle --minify --format=esm",`
this does create a "esbuild-dist" folder with everything properly split into chunks, the only thing left to do is:
- copying the `assets` folder, the favicon and the `index.html` file into the build folder
- modify the `index.html` file to add `<script src="main.js" defer></script>` at the end of the `body`

when launching a server on this folder however, ivy seems to get in the way, with a `missing 'ɵmod' property` error, I've looked at the non-minified build code and it does look like `ɵmod`, `ɵcmp` and other ivy related additions are missing

Looking into the angular-cli source code it looks like this part might be handled by a webpack plugin, so looks like that's the brick wall with this idea sadly, unless someone would be willing to pick up the task of create a esbuild version of the plugin

**Comment by jpike88** [comment]
@evanw pls reopen this issue

**Comment by NateRadebaugh** [comment]
Looks like angular cli is starting to use esbuild internally. See changes related to @angular-devkit/build-angular

https://github.com/angular/angular-cli/blob/master/CHANGELOG.md

**Comment by literalpie** [comment]
To add some more details, 
* [This RFC](https://github.com/angular/angular/issues/43131) outlines some future work that may make Angular more suitable to work with esbuild (and faster in general). 
* [This PR](https://github.com/angular/angular-cli/pull/21535) shows that the Angular CLI is currently using esbuild for style optimizations.

My conclusion is that the lack of Angular support for esbuild is the responsibility of the Angular team, not esbuild. Angular has a pipeline that depends heavily on TypeScript tooling, and until they break that apart, there is nothing esbuild can reasonably do to better support Angular.

**Comment by kyjus25** [comment]
Update on this for anyone wondering, it's on the roadmap!

https://angular.io/guide/roadmap#investigate-modern-bundles

**Comment by fasidOnGit** [comment]
In Angular v15 we have experimental esbuild support in `ng build` and `ng build --watch`.
https://angular.io/guide/roadmap#investigate-modern-bundles

**Comment by kyjus25** [comment]
[AnalogJS](https://analogjs.org/) also has beta support for Vite if anyone would like to consider that as an option as well. Vite, if anyone doesn't know, uses esbuild under the hood
