### ISSUE TITLE
Can esbuild minify better then Google Closure Compiler? 

### ISSUE THREAD

**Issue by slidertom** [evanw/esbuild#425]
Can esbuild minify better then Google Closure Compiler?

**Comment by evanw** [comment]
If better means smaller output than no, currently Google Closure Compiler's "advanced mode" minifier is state of the art (but also means you have to write your code in a special style). Otherwise, if you aren't talking about advanced mode, you are free to do your own size comparisons. I don't think anyone has extensively compared esbuild to Google Closure Compiler yet.

If better means faster minification than overwhelmingly yes, esbuild is much better than Google Closure Compiler. I'm guessing Google Closure Compiler is the slowest minifier out there.

**Comment by slidertom** [comment]
>If better means smaller output 
yes this is exactly what I mean.
I agree Google Closure Compiler probably is the slowest one, but it does a lot other things also and it costs the price.
Speed of minification it not an issue on mine projects as this is separate build/packaging task which is 
never executed by developers.
Thanks for the quick response :)

**Comment by privatenumber** [comment]
I collected benchmarks on Google Closure Compiler here:
https://github.com/privatenumber/minification-benchmarks
