### ISSUE TITLE
Happy to help with issue spam if you're after contributors

### ISSUE THREAD

**Issue by photonstorm** [evanw/esbuild#433]
@evanw just wanted to say that I'd be more than happy to help manage some of the issue spam you're getting here recently. I maintain several massive repos and have done community management for decades, so am personally familiar with how annoying the kind of spam you got over the weekend is! It just wastes your time, which could be better spent elsewhere.

I'm sure I'm not the only one who would be willing to help out, either.

To clarify, I wouldn't get personally involved in any decisions, I'd just help remove / block the obvious spam issues and PRs.

Anyway, the offer is there if you want it.

**Comment by evanw** [comment]
Thanks for the offer! I really appreciate it. I agree the spam is annoying, and I suppose we have Hacktoberfest from @digitalocean to thank for that this month.

However, the actual time to click report+block+delete is not something I mind. That just takes a few seconds. So I'm not looking for help there.

The thing I mind more is the spam being emailed to lots of people. Unfortunately I don't think GitHub has any moderation features around this (e.g. requiring approval from me before issues and PRs are public). I wonder why not. Anyway, I have temporarily activated the interaction limit that prevents people with brand new accounts from interacting with this repo. Let me know if there are other settings I could change to help make this better.

Closing this since this isn't an issue with esbuild, although we can continue the discussion in this thread.
