### ISSUE TITLE
[Feature request] Replace global objects with polyfills

### ISSUE THREAD

**Issue by remorses** [evanw/esbuild#451]
My use case is to replace the `process` global object with a polyfill

You could do that adding an option to replace global objects with modules, this way you can for example replace the `process` global object with a polyfill stored in a local file that has the process polyfill as default export

### Example

Building with a setting like `--inject=proces:process-polyfill.js`

The code below
```js
console.log(`This platform is ${process.platform}`);
```

Would become
```js
import process from './process-polyfill.js'
console.log(`This platform is ${process.platform}`);
```

This feature request is similar to what the `@rollup/plugin-inject` does in rollup

**Comment by evanw** [comment]
I think something like this would be good to add. I got most of the way to implementing what is essentially this proposal, but then it occurred to me that there's a more general form of this that would have the same effect here: injecting a small bit of code into each file.

You could then specify `--inject:"import process from './process-polyfill.js'"` and it would prefix all files with that code. The bundler already has tree shaking that can remove unused imports. This would also address #53 and potentially other use cases as well (e.g. modifying code using a plugin without affecting source maps). So I'm tempted to do that instead of this proposal.

**Comment by remorses** [comment]
some problems that could arise injecting code in every module are
- duplicate import for the same name: what if there was already an `import process from 'process-polyfill'`?
- appending code with relative imports would not work because those imports path are relative to the importer file

**Comment by evanw** [comment]
Yeah I was thinking of doing both of those things. Or more specifically, the injected file would still be a separate file (parsed once and resolved in a specific directory) but esbuild would automatically generate imports of the injected file into each file for all top-level variables not shadowed by that injecting file.

**Comment by evanw** [comment]
The final solution is somewhat different than what I proposed above. You have to explicitly export the local variables you want to expose as globals. There is more information in [the release notes](https://github.com/evanw/esbuild/blob/03a33e6e007467d99989ecf82fad61bd928a71aa/CHANGELOG.md#0717).
