### ISSUE TITLE
Question: how do I override the public path of assets

### ISSUE THREAD

**Issue by Checksum** [evanw/esbuild#459]
Is there a way to set the base path for assets, similar to webpack's `publicPath` setting? (https://webpack.js.org/guides/public-path/). I can't find that option for the CLI and can't seem to find a related issue as well.

**Comment by evanw** [comment]
Can you say more about what you expect to happen? I don't use Webpack myself and the documentation you linked to doesn't tell me anything about what this feature does. What changes about the generated files when this setting is changed?

**Comment by dalcib** [comment]
react-native bundler also has a option to define a different output destination for the assets

```[--assets-dest](https://github.com/react-native-community/cli/blob/master/docs/commands.md#--assets-dest-string)```

**Comment by rtsao** [comment]
The webpack build-time `publicPath` option (and runtime `__webpack_public_path__` variable) is used to determine the path for loading assets and chunks (depending on the [chunk loading method](https://webpack.js.org/configuration/output/#outputchunkloading)).

By default, for web bundles, webpack uses a JSONP method for dynamically loading chunks wherein `<script>` tags are appended to the DOM. The public path is essentially [path prefix](https://github.com/webpack/webpack/blob/e3087eadb38c7525671aa352fb6dd9336668f9df/lib/web/JsonpChunkLoadingRuntimeModule.js#L156). Typically, you would set `publicPath` to something like `/assets/` or `https://cdn.example.com/`

In addition to chunk loading, it also used to determine paths to other assets. For example, if you are using `file-loader` for `.png` files and have set the publicPath to a CDN:

```js
import imgPath from "./my-image.png";

console.log(imgPath);
// https://cdn.example.com/my-image-e3087eadb38c752.png
```

----

Because esbuild currently only supports ESM output when using `--splitting`, I don't think there's a need for a public path option for chunk loading. However, this would be useful for the esbuild `file` loader.

**Comment by Checksum** [comment]
Sorry for the pretty thin description, I really shouldn't create issues on my mobile. @rtsao has explained it well. The `publicPath` is the base URL for all the assets that are generated by a loader. For example:

```js
const style = require("./style.css");
console.log(style);
// style.T5D2JDNG.css
```

If deploying this bundle to a CDN with a relative path, say `https://cdn.example.com/v1/`, the absolute path to the file should be `https://cdn.example.com/v1/style.T5D2JDNG.css`. By default `publicPath` is empty and hence is relative, but explicitly setting a base path is required quite often.

**Comment by jhohlfeld** [comment]
Just for those like me stumbling across this and because the feature request is still open: here's a documented setting exactly like as requested: https://esbuild.github.io/api/#public-path

**Comment by alvaro-junqueira-axa** [comment]
> Just for those like me stumbling across this and because the feature request is still open: here's a documented setting exactly as requested: https://esbuild.github.io/api/#public-path

Did you use that and it's working  @jhohlfeld ?
