### ISSUE TITLE
[Bug] Undefined variable from lexical environment

### ISSUE THREAD

**Issue by maltsev** [evanw/esbuild#46]
I tried to build [ProseMirror basic editor](https://prosemirror.net/examples/basic/) and stumbled upon a bug in `esbuild`. 

So in that example, `prosemirror-model` module is imported, which contains the following code in `dist/index.js`:

```js
    for (var name in schema.marks) loop( name );
  var loop$1 = function ( name ) {
    var rules$1 = schema.nodes[name$1].spec.parseDOM;
    if (rules$1) { rules$1.forEach(function (rule) {
      insert(rule = copy(rule));
      rule.node = name$1;
    }); }
  };

    for (var name$1 in schema.nodes) loop$1();
```

`esbuild` translates it to

```js
      for (var name in schema.marks)
        loop(name);
      var loop$1 = function(name2) {
        var rules$1 = schema.nodes[name$1].spec.parseDOM;
        if (rules$1) {
          rules$1.forEach(function(rule) {
            insert(rule = copy(rule));
            rule.node = name$1;
          });
        }
      };
      for (var name$12 in schema.nodes)
        loop$1();
      return result;
```

which produces the following error:

```
Uncaught ReferenceError: name$1 is not defined at loop$1
```

I've built `esbuild` from the sources from the master branch.

I also simplified this code, so you can reproduce the error more easily. I'll post it in the next message.

By the way, I'm using `esbuild` in production and so far it works perfectly fine. Thanks for such a tool!

**Comment by maltsev** [comment]
So here is more simpler example:

```js
var a = function () {
    var loop$1 = function () {
        console.log(name$1);
    };

    for (var name$1 in {c: 'c', d: 'd'}) loop$1();
};

a();
```

translates to 

```js
var a = function() {
    var loop$1 = function() {
        console.log(name$1);
    };
    for (var name$12 in {
        c: "c",
        d: "d"
    })
        loop$1();
};
a();
```

which produces the same error:

```
Uncaught ReferenceError: name$1 is not defined at loop$1
```

**Comment by evanw** [comment]
Thanks for the report. This is something that I already know about and am working on fixing. It's my top priority. Unfortunately fixing it isn't straightforward because it requires a change to how scopes work.

The problem is caused by variables that are defined in a nested scope and then used in a sibling or parent scope. I have surprisingly not run in to this on all of the code bases I've tested so far. I only discovered it because of the library mentioned in #24.

This came up because I have a somewhat different way of doing scope analysis. I'm trying to keep the number of full-tree passes required to a minimum for speed, so I'm attempting to set up scopes and bind variables in the same pass. That mostly works except for this case.

I've already tried to fix this by doing a bottom-up algorithm instead of the top-down algorithm I'm currently using. It mostly works except that I'm also doing some AST transforms during the same pass that need to know if a given identifier is a specific global or not, which is information that isn't available at that point when using the bottom-up algorithm.

I think it should work without a performance penalty if I move scope construction from the binding pass to the parsing pass. That's what I plan to try next.
