### ISSUE TITLE
support proposal-export-default-from

### ISSUE THREAD

**Issue by AIluffy** [evanw/esbuild#461]
I use a library which has syntax proposal-export-default-from, and esbuild cannot transform this code:

Code:
```js
export default form './Pagination';
```

Error: **Expected ";", but found "'./Pagination'"**

**Comment by evanw** [comment]
The proposal is currently at stage 1, so it's not valid JavaScript syntax yet: https://github.com/tc39/proposal-export-default-from.

I really hope this proposal makes it because it makes so much sense (why didn't they just make `import` and `export` symmetric in the first place?) but I don't want to be stuck in a situation where esbuild ends up implementing a JavaScript syntax proposal that eventually ends up being changed or removed. This proposal would have to reach at least [stage 3](https://tc39.es/process-document/) and be implemented by other environments (e.g. browsers, node, or TypeScript) before it should be included in esbuild.

For now the workaround is this:

```js
export {default} from './Pagination';
```

I'm going to close this issue since this proposal reaching stage 3 is likely a long time away. We can revisit this issue when it comes out.

**Comment by AIluffy** [comment]
maybe this feature can implemented by community，just like what babel do。anyway, thanks for reply.
