### ISSUE TITLE
Externals with function in `module.exports` are not usable

### ISSUE THREAD

**Issue by jellelicht** [evanw/esbuild#477]
I'm trying to use esbuild to target node 10.

Given the following TypeScript in `in.ts`:
```
import * as assert from 'assert';
assert(true);
```

Running: `esbuild --platform=node --outfile=out.js --bundle in.ts`, and subsequently running `node out.js`, gives the following:

```
TypeError: assert is not a function
    at Object.<anonymous> (/tmp/out.js:23:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

I can work around this in my own code by doing e.g. `import { strict as assert } from 'assert';` instead, but would still like to have a usable js file for the instances were I can't change the sources myself.

**Comment by evanw** [comment]
In JavaScript, doing `import * as assert from 'assert'` means `assert` is a [module namespace object](http://www.ecma-international.org/ecma-262/11.0/#sec-module-namespace-exotic-objects), not a function. You get the same result if you do this with node's native module support (requires node 12 maybe?):

```js
// example.mjs
import * as assert from 'assert';
assert(true);
```

This is what happens when you run `node --experimental-modules example.mjs`:

```
file:///example.mjs
assert(true);
^

TypeError: assert is not a function
    at file:///example.mjs
    at ModuleJob.run (internal/modules/esm/module_job.js:146:23)
    at async Loader.import (internal/modules/esm/loader.js:165:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

You are likely encountering this because some other ECMAScript-to-CommonJS transformers have a loose/buggy transform that converts this to `var assert = require('assert')` which happens to work with the code you wrote. But that's not a correct transformation because it doesn't obey the right semantics, so esbuild won't be supporting code written this way.

When a CommonJS module is imported into an ECMAScript module, the value of `module.exports` is available as a `default` import:

```js
import assert from 'assert';
assert(true);
```

The example above should work both in esbuild and with node's native ECMAScript modules.

**Comment by jellelicht** [comment]
Note; I'm talking about TypeScript, and `tsc` does seem to support this (faulty?) transformation.

Some of the libraries that you need to build Node from source (`llparse-builder`, `llhttp` and friends) seem to use this 'pattern'. Are you saying that they are doing it wrong? If so, I can open issues for each of those project :+1:

**Comment by evanw** [comment]
> Are you saying that they are doing it wrong? If so, I can open issues for each of those projects 👍

Sort of. At least, their code is not portable to tools that follow ECMAScript module semantics (including modern versions of node itself). For example, libraries such as `llhttp` would no longer run in node if TypeScript's `module` target is changed from `commonjs` to `es2015` because of this issue. These libraries also wouldn't work with Babel's transforms either as far as I can tell (`@babel/preset-env` + `@babel/preset-typescript` appears to behave like esbuild here).

If those libraries are only intending for other projects to consume their build artifacts, not their source files, then requiring a specific tool to build their code may not be an issue. But if the source code is intended to be consumed by other projects too, there is an argument for following ECMAScript module semantics to maximize code portability.

Right now esbuild takes a "TypeScript is just JavaScript with types" approach to TypeScript compilation and I think that's the correct and forward-looking approach. ECMAScript modules are gaining momentum and I think it wouldn't be a good decision for esbuild to start deviating from these semantics since it's clearly where the JavaScript ecosystem is going in the future.

I'm sorry about all of this. Honestly the whole `default` import situation with ECMAScript and CommonJS modules is kind of a mess. There's an overview of some of the history about it [here](https://itnext.io/great-import-schism-typescript-confusion-around-imports-explained-d512fc6769c2) in case that's helpful.

**Comment by jellelicht** [comment]
Thank you for your patience and the explanations; as I only need to build a handful (~12) of packages that do this, I'll just carry some small patches going forward to do exactly what you proposed.
