### ISSUE TITLE
Is Module Federation (or similar) on the roadmap?

### ISSUE THREAD

**Issue by akatechis** [evanw/esbuild#479]
I've been looking at alternatives to webpack, and I recently looked at Webpack 5's flagship feature, Module Federations, and was impressed, as I have been trying to think of ways to adopt micro-frontends architecture for the company I work for. Given esbuild is meant to be a small, focused, and most importantly FAST bundler, do you intend to add something like this in the future?

Is there a roadmap document somewhere we can see what features are/aren't part of your vision for `esbuild`?

**Comment by evanw** [comment]
> Given esbuild is meant to be a small, focused, and most importantly FAST bundler, do you intend to add something like this in the future?

Module federation is not on my roadmap, mainly for that reason (esbuild being a small, focused bundler) and because it's a brand new feature that hasn't been widely adopted by the community. I'm not sure if the upcoming plugin API (issue #111) could be used to implement module federation or not since I don't know anything about how module federation works, but if so that could be an interesting experiment.

> Is there a roadmap document somewhere we can see what features are/aren't part of your vision for `esbuild`?

I'm working on a real website for esbuild at the moment. This will include a section for the roadmap. Hopefully it'll be up in a week or two.

**Comment by evanw** [comment]
There is now a roadmap here: https://esbuild.github.io/faq/#upcoming-roadmap.
