### ISSUE TITLE
Non-official watch mode wrapper

### ISSUE THREAD

**Issue by henriquehbr** [evanw/esbuild#481]
Hi there Evan!

First, thank you for the great work you've done with esbuild, this tool is simply amazing, in comparison with rollup/webpack

Recently, i've been working on [eswatch](https://github.com/henriquehbr/eswatch), a simple wrapper around esbuild built with chokidar for watching, building and running files instantly, even though the project is just a PoC in early development stage, i tested it with a couple of node-based personal projects (including ones with typescript), and it works really well, even for CLI applications with prompts (like inquirer), as esbuild still don't have an built-in watch mode feature available, do you think that this non-official alternative should be recommended on the documentation?

Unfortunately, i'm not that familiar with esbuild codebase, and i opted to build a wrapper from scratch as for me, it would be faster and easier, but if i could contribute in any way, let me know, this project is really promising

**Comment by heyheyhello** [comment]
I think it's very nice to see personal watchers but it's also a very opinionated topic as some people want generic tools/binaries like watchexec or to roll their own implementation in Node (as you have) since it's only a few lines of code.

It's hard to make something "official" that's not built into the esbuild binary since it will always be leaving out someone's use case. As you've discovered yourself, it's probably better to build your own personal version.

**Comment by David-Else** [comment]
I have used https://github.com/egoist/rollup-plugin-esbuild which seems nice and minimal.

I hope ESBuild gets its own watch soon, would be great to get rid of more dependencies.

**Comment by evanw** [comment]
There is also https://github.com/rsms/estrella, which runs `tsc` for you. I'm not planning on recommending a single non-official alternative in the documentation since there are many different approaches to wrappers. Closing this issue in favor of the existing one about watch mode: #21. FYI the next release will hopefully have an incremental build API that will make watch mode wrappers more ergonomic and efficient, and a way to run esbuild as a local file server which replaces some use cases for watch mode.
