### ISSUE TITLE
[Feature] banner and footer

### ISSUE THREAD

**Issue by wessberg** [evanw/esbuild#482]
# Feature Request

I would like to propose a `banner` and `footer` option, as seen in Rollup and [documented here](https://rollupjs.org/guide/en/#outputbanneroutputfooter).

> A string to prepend/append to the bundle. (...) (Note: banner and footer options will not break sourcemaps).

From what I've been able to gather, and based on my own testing, the new `inject` option doesn't quite allow for this behavior, so I feel like this one is needed.

# Use case

One common use case is for adding a license or another relevant comment in the top of a bundle in a way that doesn't break source maps.

**Comment by evanw** [comment]
Yes, I think a feature like this makes sense. Another issue with `--inject` is that you can't insert partial files. For example, you may want the prefix to be `try {` and the suffix to be `} finally { ... }`, which may be necessary to support certain strange use cases such as hot-module reloading.

However, if I support that then these prefix and suffix strings aren't actually valid JavaScript code, and for example won't be able to be minified. I think that should be fine though since this is a very custom use case and you can always minify them yourself if needed.

**Comment by wessberg** [comment]
Yes, agreed. And to your latter point, I would argue that this is fine since it would make sense that the banner and footer (or prefix and suffix if you prefer these names) are added to the bundle(s) as late in the compilation process as possible, even after minification.

**Comment by Gelio** [comment]
I wanted to make a contribution to this project and pick up a bit of go along the way. Here is my attempt at adding support for those options: https://github.com/evanw/esbuild/pull/531

**Comment by evanw** [comment]
This feature was implemented in #531 by @Gelio.
