### ISSUE TITLE
[Feature] buildSync returns outputFiles[].content as Uint8Array, expected String

### ISSUE THREAD

**Issue by Jarred-Sumner** [evanw/esbuild#496]
If you run `buildSync`, it returns the `outputFiles[].contents` as `Uint8Array`. This is a little unexpected for source code where you don't intend to write to disk, but it makes a lot of sense if you're about to upload the file to a CDN

 It would be slightly easier if either:
- `.toString()` function defined on the prototype of the `outputFiles[].` object.
- Default to returning a String based on the file type (code/plaintext? string. images/other? Uint8Array)

A `.toString()` function or `.toCode()` would be cool, since changing the return type might cause weird bugs in tools and decoding isn't free. And, if it was something like`.toCode()`, it would be natural for that to maybe be pretty printed later on 

Example code:
```js
const result = require("esbuild").buildSync({
    stdin: {
      contents: "module.exports = console.log("HI!!")",
      resolveDir: path.resolve("."),
      sourcefile: "file.ts",
      loader: "ts",
    },
    format: "cjs",
    target: [`node12`],
    sourcemap: "inline",
    bundle: true,
    write: false,
  })

> result.outputFiles[0].contents.constructor.name
'Uint8Array'
```

If anyone searches how to get the outputFiles contents as a string, here's the code:

```js
new TextDecoder("utf-8").decode(result.outputFiles[0].contents)
```

Sidenote: esbuild is really cool. I'm using it in a webpack loader for a build tool. I first tried implementing this webpack loader as a webpack plugin via [`createChildCompiler`](https://webpack.js.org/api/compilation-object/#createchildcompiler) and spent much of the day trying to get it to work. It took about 15 minutes with esbuild and now I wish I just tried esbuild to start with.

**Comment by evanw** [comment]
Yes, this is unfortunate. The reason it works this way is because the [`file` loader](https://esbuild.github.io/content-types/#external-file) can cause some of the output files to contain binary data. That binary data could be corrupted if it was encoded using a JavaScript string, since JavaScript strings use UTF-16 encoding and the binary data may not be valid UTF-8.

One idea for this could be to have a property on each output file called `text` or something that is a string representation of the underlying Uint8Array. It could be a getter that lazily decodes the byte array for performance, and either throws on invalid UTF-8 or replaces such sequences with the U+FFFD replacement character.

**Comment by Jarred-Sumner** [comment]
Yay

**Comment by zandaqo** [comment]
Just a heads up concerning TextEncoder API, it's slow in V8 right now: https://bugs.chromium.org/p/v8/issues/detail?id=4383
I had to go back (for now) to custom encoding in my library because TextEncoder/TextDecoder were roughly 3 times slower for me.
