### ISSUE TITLE
[optimization] [proposal] used exports

### ISSUE THREAD

**Issue by kamil0414** [evanw/esbuild#511]
Determine used exports for each module. Dead code elimination will speed up resolving node modules and reduce bundle size.

**Comment by evanw** [comment]
This is already done for ECMAScript modules (the `esm` output format). It's called "tree shaking" in the documentation instead of "dead code elimination" because that's what other JavaScript bundlers call it. It's always enabled and you can't configure it or turn it off. However, tree shaking is only applied during linking. It does not have any affect on speed of node module resolution.
