### ISSUE TITLE
failed to ignore relative external path

### ISSUE THREAD

**Issue by Shigma** [evanw/esbuild#514]
I'm using esbuild to compile a library with multiple entries (one for main thread, another for worker thread). However both file requires a shared file. 

```
src/
  main.ts
  worker.ts
  shared.ts
  ... and other files
```

I want to get a build result like this:

```
dist/
  main.js
  worker.js
  shared.js
```

So I write up my build script:

```js
build({
  bundle: true,
  entryPoints: ['src/main.ts', 'src/worker.ts', 'src/shared.ts'],
  external: ['src/shared.ts', ...severalLibraries],
  // I also tried ./shared.ts and full path of shared.ts
  outdir: 'dist',
})
```

But it just doesn't work.

**Comment by evanw** [comment]
I assume you're trying to run this with node? The simplest way to do this would just be to bundle the shared file into each entry point, so there would be no shared file in the output.

I'm guessing marking the file as external isn't working for you because the path doesn't match what's used in the source code. For example, you may be marking `./src/shared.ts` as external but your code imports `./shared`. In that case marking `./src/shared` as external instead would work.

However, the external feature won't do what you want. That would be marking your source code as external instead of your compiled code, so the compiled code would try to call the original source code instead of the shared compiled code. The external feature in the API wasn't designed for doing this.

You could potentially do this with a plugin:

```js
require('esbuild').build({
  bundle: true,
  entryPoints: ['src/index.ts', 'src/worker.ts', 'src/shared.ts'],
  outdir: 'dist',
  format: 'cjs',
  plugins: [{
    name: 'example',
    setup(build) {
      // Match an import called "./shared" and mark it as external
      build.onResolve({ filter: /^\.\/shared$/ }, () => ({ external: true }))
    },
  }],
})
```

**Comment by Shigma** [comment]
It works for me. Thanks a lot.

**Comment by darsain** [comment]
I think I've run into the same issue where I have a `src/dynamic/module.ts` file which is in code loaded lazyly (inside a function that is not always called) with `require('../../dynamic/module')` (this path unfortunately resolves to the correct file in both build and source versions), and no matter what I add to `external` option the file is still bundled in,

I've tried the plugin solution from above, but I just get `The entry point "./src/dynamic/module.ts" cannot be marked as external` errors that don't provide a reason, or how to fix it.

Each `src/dynamic/*` file is declared as a separate entry point.

Reason for this setup: I'm creating an electron app and I'm doing this to load big dependencies only when needed to speed up app startup times.
