### ISSUE TITLE
sourcemap support for CSS

### ISSUE THREAD

**Issue by yagebu** [evanw/esbuild#519]
Hi, first of all, thank you very much for `esbuild`! The performance is amazing and I really like that it brings just enough batteries included be a nearly complete bundling tool and that it treats CSS as a first-class citizen :). I wrote a plugin to provide support for importing Svelte components, the plugin API worked quite well for that for me (https://github.com/yagebu/esbuild-plugin-svelte).

The Svelte compiler provides sourcemaps for both JS and CSS, which I included inline in the strings that I handed off to esbuild, [see here](https://github.com/yagebu/esbuild-plugin-svelte/blob/2678243f470b2fe45c0d7e27d8081c10e6d48e02/index.ts#L79). It worked great for JS but seems that those have no effect in the CSS (and from a quick code search in the repo here, it seems there's just no sourcemap functionality for CSS yet. I don't really use CSS preprocessors, so the comments that reference the file names in the generated CSS already help quite a bit, but having proper sourcemaps would be even better :)

**Comment by evanw** [comment]
Thanks for logging this. I'm unfamiliar with this feature because I haven't used it myself. The CSS feature is still very early and I already have at least one rewrite planned for it, so it's a little premature to add CSS source map support yet. I'll make sure to add this once CSS support is further along.
