### ISSUE TITLE
(enhancement) Idea for plugin - #DEFINE pre-parsing - Is there interest / would it be useful?

### ISSUE THREAD

**Issue by rw3iss** [evanw/esbuild#525]
I've been thinking of a potential plugin for something like esbuild, which might be an ideal tool for the use case: adding #DEFINE directive support to javascript (or any input files for that matter, ie. json).

esbuild could act as a pre-parser in order to use #DEFINE's to both implement macros in javascript, and also to eliminate or "branch" entire pieces or features of code. 

For example, a developer could define:

`#DEFINE LEAN_MODE true`

and then somewhere throughout the code:

```
#IFNDEF LEAN_MODE  // (if NOT lean mode)
  ... a bunch of code that is non-performant ...
#ENDIF
```

or macros:

`#DEFINE A_MACRO(INPUT) get_max(...INPUT) { // find max from input }`

I'd have to work out the macro syntax a bit (adding arguments seems challenging), but I think in general this would be pretty useful, and I think would be the job of a pre-parser, such as an esbuild plugin.

I'm wondering if other people would find it useful, or see any issues with it?

**Comment by evanw** [comment]
Yes other people would find this useful, if that answer's your question. Here's one example: https://github.com/evanw/esbuild/issues/163. This person was looking for preprocessor statements to be handled in comments.

> also to eliminate or "branch" entire pieces or features of code

You may already be aware, but this is also possible with normal JavaScript syntax without macros. You can use normal if statements and global variables as flags that are set to `true` or `false` at compile time. See the "define" feature of esbuild for more information: https://esbuild.github.io/api/#define.

I'm going to close this issue because it's not a problem with esbuild.

**Comment by rw3iss** [comment]
Awesome, thanks @evanw .. I didn't know about the compile time constants/if dead-code elimination, that's great and should suit needs well enough. If might be fun to build something via a plugin, and possibly extend the capability with more expressive #defines... but not sure there's such a point aside from the basic necessity to eliminate/include certain code. Only benefit I could see from separating from the standard if syntax is possibly implementing macros and maybe more pre-processor capabilities in general, but for now that's cool - thanks again 👍
