### ISSUE TITLE
No ARM32 support

### ISSUE THREAD

**Issue by GoldenTK** [evanw/esbuild#528]
Hi,
I have a small raspberryPi 4 with `code-server` on it and I decided to use `snowpack` in my new project but when I tried to install `esbuild` I'm getting:
```
Unsupported platform: linux arm LE
```

My linux version:
```
Linux raspberrypi 5.4.75-v8+ #1367 SMP PREEMPT Mon Nov 9 15:11:16 GMT 2020 aarch64 GNU/Linux
```

Could you please add support for ARM64 platform? I think it's crucial to have support for ARM's.

**Comment by rtsao** [comment]
There is already support for ARM64, but it appears installation is failing because `os.arch()` is returning `arm` rather than `arm64` which esbuild expects. Is it possible you are accidentally using the 32-bit Node.js ARM binary? My understanding is that `os.arch()` actually returns the architecture of the Node.js process, not the OS CPU architecture.

Maybe esbuild should use a heuristic like https://github.com/feross/arch to determine the actual CPU architecture.

**Comment by GoldenTK** [comment]
Hmm I just upgraded `raspbian` to 64bit version, maybe that's the case.
