### ISSUE TITLE
Missing String.prototype.replaceAll polyfill

### ISSUE THREAD

**Issue by gunar** [evanw/esbuild#530]
Hi, `String.prototype.replaceAll` was introduced in `es2021` so I'd expect the output for target `es2015` to contain a polyfill for it. Maybe I'm missing something? Thanks in advance.

**Comment by evanw** [comment]
The target level in esbuild only handles syntax-level concerns. You are free to include whatever polyfill you'd like to use.

**Comment by gunar** [comment]
Okay, thank you.

Side question: Is there a way you can recommend me so that the necessary
polyfills get added automatically?

**Comment by evanw** [comment]
I guess that depends on the polyfill. You can insert the polyfill as an import into all files so it's guaranteed to come first with the [inject](https://esbuild.github.io/api/#inject) feature. This is sufficient for almost everything including `replaceAll`.

But if you need to polyfill the functions used by esbuild's automatically-generated run-time code such as `Object.assign`, you'd currently have to use a separate `<script>` tag that comes before your own code. Arguably the run-time code not being polyfilled could be considered a bug in esbuild.

**Comment by gunar** [comment]
I see. And is there a way to automate the usage of the inject feature? I mean, is there a library that can help me identify which polyfills are required based on the code at hand and based on the target ECMAScript (or browser) version?

**Comment by evanw** [comment]
That's kind of a general JavaScript question instead of an esbuild-specific question, so it might be good to ask this question elsewhere. I'm not super knowledgable about this.

Many projects including Babel use [core-js](https://github.com/zloirock/core-js) although I believe the primary author is in jail at the moment, so I'm not sure what the current state of that project is. We used [es5-shim](https://github.com/es-shims/es5-shim) and [es6-shim](https://github.com/paulmillr/es6-shim) at work for a while but we no longer need it (we now require ES2017+).

Sorry I can't help more. Maybe someone else can comment with more context.

**Comment by zloirock** [comment]
> I believe the primary author is in jail at the moment

Nope -)

**Comment by evanw** [comment]
Oh hello! Never mind then. Welcome back :)

**Comment by gunar** [comment]
I just realized what I was asking for is not possible because JavaScript is a dynamic language 🤦

Anyway, thanks @evanw, [the projects you've mentioned](https://github.com/evanw/esbuild/issues/530#issuecomment-727616700) solved my problem. Thank you so much for being so gracious and trying to help me out—you're awesome!
