### ISSUE TITLE
Decorators implementation

### ISSUE THREAD

**Issue by edoardocavazza** [evanw/esbuild#533]
At the moment, the `__decorate` implementation differs from the official one:

```js
export var __decorate = (decorators, target, key, desc) => {
	var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
	if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
	else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
	return c > 3 && r && Object.defineProperty(target, key, r), r;
}
```

Is there any plan to align the runtime helper and the esbuild output? May I help in this?

**Comment by evanw** [comment]
No I don't have plans to do that.

I'm aligning the behavior of the implementation with the official one instead of aligning the code. The code generation in esbuild for decorators is a little different (more compact) so using the literal helper function from the TypeScript library won't work. I'm not calling out to `Reflect.decorate` because that method is no longer part of any specification and will likely never be a part of the web (the actual JavaScript decorator proposal has evolved several times since then).

**Comment by evanw** [comment]
Closing this since I got a 👍 from the author so I consider this question to be answered.
