### ISSUE TITLE
How to use dev server?

### ISSUE THREAD

**Issue by samevision** [evanw/esbuild#557]
Hello,

I wanted to try esbuild to speed up the compiling process. Unfortunately I am not sure about using the dev server.

My esbuild.config.js looks like this:
```
require('esbuild').build({
    entryPoints: ['./src/index.js'],
    bundle: true,
    minify: true,
    outfile: './dist/out.js',
    define: {
        'process.env.NODE_ENV': '"production"'
    }
}).catch(() => process.exit(1))
```

This works fine for bundling. To set up the dev server I use web-dev-server.config.mjs:
```
import { esbuildPlugin } from '@web/dev-server-esbuild'

export default {
  open: false,
  nodeResolve: true,
  watch: true,
  appIndex: './public/index.html',
  debug: false,
  rootDir: './src/',
  plugins: [
    esbuildPlugin({
      target: 'auto'
    })
  ]
}
```

How am I able to use my esbuild.config.js while starting the server?

Best

**Comment by evanw** [comment]
Sorry, I'm not familiar with `@web/dev-server-esbuild`. I'm guessing this is a question for [that project](https://github.com/modernweb-dev/web) instead of this project. I did a Google search and got this documentation: https://modern-web.dev/docs/dev-server/plugins/esbuild/. Is that what you were looking for?

**Comment by samevision** [comment]
Oh, you're right. I assumed that the dev-server is part this project. I already read this article but I wasn't able to make it work. I will ask this question there. Thank you!

**Comment by evanw** [comment]
No worries.
