### ISSUE TITLE
Q: Add file dependencies to loaders

### ISSUE THREAD

**Issue by arcanis** [evanw/esbuild#562]
I'm currently looking into what it'd take to implement a `less` loader. It seems that since Less files can import other files, the loader should have a way to let the core know that if any of the dependencies change (rather than just the file itself), then the loader output should be invalidated. Do you plan to let plugins define this kind of relationship?

Ref, what the `less-loader` from Webpack does:
https://github.com/webpack-contrib/less-loader/blob/master/src/index.js#L58-L66

**Comment by rtsao** [comment]
esbuild doesn't currently include any file watching capability. Instead, with the [current incremental build API](https://esbuild.github.io/api/#incremental), you invoke the `rebuild()` method yourself whenever you wish.

I think the concept of loader `fileDependencies` and `contextDependencies` (in webpack parlance) would only be necessary if esbuild were to be responsible for file watching.

**Comment by arcanis** [comment]
Hm 🤔 in the doc is written:

> Parsed ASTs are stored in memory and re-parsing the AST is avoided if the file contents haven't changed since the last build. This optimization applies to virtual modules created by plugins in addition to file system modules, as long as the virtual module path remains the same.

Doesn't that imply that, if `foo.less` doesn't change, then its transformed AST will stay the same in the incremental cache, even if `bar.less`, that it imports, changes?

**Comment by evanw** [comment]
> Doesn't that imply that, if `foo.less` doesn't change, then its transformed AST will stay the same in the incremental cache, even if `bar.less`, that it imports, changes?

This is describing what esbuild does with the file contents after the loader runs. If the loader returns the exact same string as last time for the file contents, then esbuild doesn't re-parse it since it will be the exact same AST as last time. If the loader generates a different string, then esbuild will throw out the old AST and generate a new one.

The answer to your question depends on who's doing the importing. If the loader does the importing then I imagine changing `bar.less` would change the loaded contents of `foo.less`. If the loader just generates `@import` and esbuild handles the import then the loaded contents of `foo.less` wouldn't change when `bar.less` changes.

**Comment by arcanis** [comment]
I see, thanks for the clarification! Then I think this should work just fine, I'll try this way 👍

**Comment by zaydek** [comment]
@evanw In the case where you have a Sass plugin, esbuild can’t pick up changes in linked SCSS files, right?

So let’s say:

```main.scss
// main.scss
@use "other"
```

```other.scss
// other.scss
.hello {
  content: "foo bar";
}
```

If a plugin looks at `main.scss`, esbuild won’t rebuild when `other.scss` changes because esbuild doesn’t know what dependencies `main.scss` depends on, right? I can see how if esbuild rebuilds for some other reason then this wouldn’t matter.

My concern is that if you add a caching layer in front of a plugin, [like you recommend in the docs](https://esbuild.github.io/plugins/#caching-your-plugin), then even normal rebuilds (triggered for any reason) won’t pick up changes to `other.scss` because `main.scss` is cached based on the source text, therefore its dependencies are opaque.

Now that watch mode is implemented, would it make sense to be able to explicitly communicate linked dependencies to esbuild? It may be overkill but I thought it was worth bringing up now that esbuild supports watch mode / incremental recompilation / serving.

<details>
  <summary>Backstory: I stumbled upon this idea when I was reading the Svelte docs.</summary>

> If a dependencies array is returned, it will be included in the result object. This is used by packages like [rollup-plugin-svelte](https://github.com/sveltejs/rollup-plugin-svelte) to watch additional files for changes, in the case where your <style> tag has an @import (for example).
> https://svelte.dev/docs#svelte_preprocess

Code example next to that snippet:

```js
const svelte = require('svelte/compiler');
const sass = require('node-sass');
const { dirname } = require('path');

const { code, dependencies } = await svelte.preprocess(source, {
	style: async ({ content, attributes, filename }) => {
		// only process <style lang="sass">
		if (attributes.lang !== 'sass') return;

		const { css, stats } = await new Promise((resolve, reject) => sass.render({
			file: filename,
			data: content,
			includePaths: [
				dirname(filename),
			],
		}, (err, result) => {
			if (err) reject(err);
			else resolve(result);
		}));

		return {
			code: css.toString(),
			dependencies: stats.includedFiles
		};
	}
}, {
	filename: 'App.svelte'
});
```

And finally, `stats.includedFiles` described by Sass (from the Sass docs):

> An array of the absolute paths of all Sass files loaded during compilation. If a stylesheet was loaded from an importer that returned the stylesheet’s contents, the raw string of the @use or @import that loaded that stylesheet is included in this array.
> https://sass-lang.com/documentation/js-api#result-stats-includedfiles

</details>

**Comment by zaydek** [comment]
I just noticed you said this in a very recent issue:

> > I was wondering if there's anything better esbuild or the plugin system can do here?
>
> I'm planning for plugins to be able to return a list of files to watch. But the API for this doesn't exist yet, sorry. It will be there at some point.
>
> https://github.com/evanw/esbuild/issues/808#issuecomment-779417895

So this can be ignored.
