### ISSUE TITLE
snowpack-plugin-optimize using esbuild having error on iOS and Safari 12 and below

### ISSUE THREAD

**Issue by khoivan88** [evanw/esbuild#575]
Hi, 

First of all, thank you for a very useful library. I don't use this library directly but using snowpack plugin optimize (https://www.npmjs.com/package/@snowpack/plugin-optimize) that using this as the main engine. 

I have a peculiar problem that when using snowpack plugin optimize and when asked was redirected to your library. In short, when I  use snowpack plugin default option to minify JS, I have JS error on device running iOS or Safari 12 and below. It seems to have issue on or before ternary clause.

Screenshot on iPad 5 iOS 12.4 using Safari
![Screen Shot 2020-12-03 at 8 18 42 PM](https://user-images.githubusercontent.com/33493502/101109387-cae75900-35a4-11eb-986f-dd59f7c63089.png)

By not having minifyJS on, i can confirm the site works well on these devices. I know it is a long shot but it seems that no one has seen this issue (or know of it). I was wondering if you might have any pointer for me. I love to be able to optimize my code yet able to provide for all the users even with older tech as well. 

Here is one of my repo that is using this. I am having the same issue with another more popular website (unfortunately, I don't have that repo public): https://github.com/khoivan88/eluent-translator and the website built from that repo is at: https://eluenttranslator.netlify.app/

Thank you very much!

**Comment by evanw** [comment]
I'm guessing this is due to the introduction of the `?.` or `??` operator. You need to tell esbuild what target environment(s) you want to support if you need to limit the output to older JavaScript syntax, otherwise esbuild defaults to using modern JavaScript syntax. For example, if you wanted to support Safari 12 and up you would use `safari12`. This feature is documented here: https://esbuild.github.io/api/#target.

**Comment by khoivan88** [comment]
Hi, thank you so much for your prompt response, I did try the `esbuild` target to 'es2015', 'es2018', and 'es2020' and even empty 'target', I believe. Sadly, none of them work. However, I have not tried 'safari12' at all, I will give that a try! Thank you very much !!

**Comment by evanw** [comment]
I just tried your repo (https://github.com/khoivan88/eluent-translator). I added this code to `src/scripts/index.js`:

```js
var a;
console.log(a !== null && a !== undefined ? a : b);
```

Building that with `npm run build:snowpack` resulted in `a ?? b`, but that's because the target is set to `es2020`. Setting the target to `es2019` instead resulted in `a != null ? a : b` after the `npm run build:snowpack` command (in `dist/_dist_/index.js`).

**Comment by khoivan88** [comment]
Thank you so much for your test. I did a test based on your suggestion and it works with me adding the target to `["es2020", "safari12"]`. It is perfect . 

I wish i had asked earlier, i have been looking for this seems so simple solution for >2 weeks. 

1 comment and your solve it :D. Thank you so much. You are awesome!
