### ISSUE TITLE
Unable to try/catch an import

### ISSUE THREAD

**Issue by joehoyle** [evanw/esbuild#577]
I am not able to `build` the following code, if `Single.tsx` does not exist: 

```js
async function getTemplates() {
	try {
		const m = await import( './Single.jsx' );
	} catch ( e ) {

	}
}
```

In my case, I want to support both the file `Single.jsx` existing at build time, and not existing. I believe this is valid in the ESM spec, so I'm not sure why I'm not able to use this in the bundle, where I'd expect an exception to be thrown.

Sorry if I'm missing something obvious here!

**Comment by evanw** [comment]
If you don't want to include a file in the bundle, you can use the `external` feature to tell esbuild to not include that file: https://esbuild.github.io/api/#external. For example, in this case you could use `--external:./Single.jsx`.

**Comment by joehoyle** [comment]
So, in my case it's not that I don't want to include it-- I just want to include files based off whether they exist or not!

**Comment by heyheyhello** [comment]
I think this is pretty easy to do with a plugin that scans the filesystem for the existence of some files and for any that aren't found it marks them as external.

There are examples in other issues of how to mark an import as external in a plugin.

Still, esbuild is a bundler and you're asking it to not bundle. I'd double check if you have to do it this way since now the code, every execution, will waste time looking for an import that doesn't exist.

**Comment by evanw** [comment]
The easiest approach is probably to move the string literal into a variable. Currently esbuild doesn't have cross-statement constant folding so this effectively hides the string from esbuild. Then it will let your code through because it is unable to bundle the file. In your case there won't even be a warning because you are specifically using `await import()` inside `try`, so esbuild assumes you can handle the error if the file is missing.

If you don't have the ability to change the code in question, you can still do this with a plugin. Something like this would work:

```js
const externalIfMissingPlugin = {
  name: 'external-if-missing',
  setup(build) {
    const fs = require('fs')
    const path = require('path')
    build.onResolve({ filter: /^\.\/Single.jsx$/ }, args => {
      if (!fs.existsSync(path.join(args.resolveDir, args.path)))
        return { path: args.path, external: true }
    })
  },
}
```

You would use it like this:

```js
require('esbuild').build({
  ...
  plugins: [
    externalIfMissingPlugin,
  ],
  ...
})
```

**Comment by joehoyle** [comment]
That's amazing, thank you so much for the guidance @evanw and @heyheyhello!
