### ISSUE TITLE
Regression: esbuild picks CJS instead of ESM export

### ISSUE THREAD

**Issue by schickling** [evanw/esbuild#584]
First of all: Thanks so much for your incredible work @evanw. `esbuild` is a true game changer.

I recently ran into some problems when upgrading `esbuild` from 0.6 to 0.8 and after some further investigation I was able to isolate. My suspicion is that esbuild in the past correctly picked ESM exports (via `module: ...` in the `package.json`) but stopped supporting this at some point.

I've tried to demonstrate this problem in this short video recording:

https://www.loom.com/share/8af8e6abf60f40d0b8dda755c6131eca

I've created individual reproductions here:

- ✅ works with 0.6.17 https://codesandbox.io/s/esbuild-v0617-repro-esm-cjs-9en6s?file=/packages/app/package.json
- ❌ doesn't work with 0.8.20 https://codesandbox.io/s/esbuild-v0820-repro-esm-cjs-brpt6?file=/packages/app/package.json
- 🤔 workaround for 0.8.20 https://codesandbox.io/s/esbuild-v0820-repro-esm-cjs-workaround-jqr6b?file=/packages/mylib/package.json

(Note if Codesandbox is flakey for you, you can just download the ZIP files and run it locally.)

Please let me know how I can potentially help further pin down the problem.

**Comment by evanw** [comment]
This change was made for compatibility in [version 0.7.0](https://github.com/evanw/esbuild/blob/81b8e1f074a4fc69e15f76003663178715cc2148/CHANGELOG.md#070). Some package authors have unfortunately been treating the `module` field as "code for the browser" which is _not_ what it means. But because of these existing packages, the most compatible thing for esbuild to do (i.e. the most likely to not be broken by default) is to select the `main` field when the platform is `node`. So esbuild takes this approach because it prefers generating larger but working code over smaller but broken code.

If you know your node libraries will work with `module`, you can use the [main fields](https://esbuild.github.io/api/#main-fields) feature to prefer `module` over `main` like this: `--main-fields=module,main`.

**Comment by schickling** [comment]
I see! Thanks for elaborating!

This issue is probably not the right place to ask this but do you have any idea whether this error message is related to `esbuild`. (It only occurs when setting the TS target to `es5` for the `mylib` package.)

Error:
```
/sandbox/packages/app/dist/app.js:66
      return _super !== null && _super.apply(this, arguments) || this;
                                       ^

TypeError: Constructor Map requires 'new'
```

`es5` code generated by `tsc` (❌ doesn't work with `esbuild` 0.7+)
```js
var TransformsMap = /** @class */ (function (_super) {
    __extends(TransformsMap, _super);
    function TransformsMap() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    return TransformsMap;
}(Map));
exports.TransformsMap = TransformsMap;
```

`es6` code generated by `tsc` (✅ works with `esbuild` 0.7+)
```js
export class TransformsMap extends Map {
}
```

**Comment by evanw** [comment]
That problem is unrelated to esbuild. Your code is attempting to extend the built-in `Map` object using something like this:

```js
Map.call(Object.create(Map.prototype))
```

That won't work. Map is a native object with special behavior. Instances of Map have special internal state that can only be initialized by constructing a Map. From [the spec](http://www.ecma-international.org/ecma-262/11.0/#sec-map-constructor):

> The Map constructor ... is not intended to be called as a function and will throw an exception when called in that manner. ... Subclass constructors that intend to inherit the specified Map behaviour must include a `super` call to the Map constructor to create and initialize the subclass instance with the internal state necessary to support the Map.prototype built-in methods.

You can only extend the `Map` object using a real ES6 class.

**Comment by schickling** [comment]
Thanks so much. Pretty subtle pitfall that I fell into here 😅

> This change was made for compatibility in version 0.7.0.

Given this change was made intentionally, I'll close this issue. Hopefully it's still helpful for others who might run into a similar problem in the future! 🙏
