### ISSUE TITLE
Fails to transform typescript types when re-exported

### ISSUE THREAD

**Issue by TomzBench** [evanw/esbuild#585]
I think there is an issue with `esbuild ({ts:true})` not liking certain export syntax. My typescript has

```typescript
// menu.ts
import { Item } from './item';
export { Item as MenuItem }; 
```

But it is transformed to this
```typescript
// menu.ts
import { Item } from './item';
export { Item as MenuItem } from './item`
```

Which causes an error:
`SyntaxError: The requested module './item.ts' does not provide an export named 'Item'`

esbuild seems to have transformed my export in order to properly export it, however it should have been stripped because `Item` is an interface.

**Comment by evanw** [comment]
I don’t know what the `esbuild ({ts:true})` syntax is. That’s not from esbuild’s API so you must be using some other tool that wraps esbuild. 

Regardless, this is probably happening because whatever tool you are using is calling esbuild’s transform API which processes each file independently. That means it doesn’t have access to the contents of other files, so it doesn’t know if something is a type or not. This behavior matches other TypeScript transpilers such as Babel, so it’s not unusual. TypeScript has a flag for this situation called `"isolatedModules": true`. Enable that in your `tsconfig.json` file and this syntax will become an error. You will then have to use the `export type { Item as MenuItem }` instead which doesn’t have this ambiguity. All of this and more is documented here: https://esbuild.github.io/content-types/#typescript.

**Comment by TomzBench** [comment]
@evanw Yes I was using another tool.  And yes changing my tsconfig and export syntax fixed!

Thanks for help - sorry for prematurely declaring issue!
