### ISSUE TITLE
Unable to get mainFields to work without platform:node

### ISSUE THREAD

**Issue by joehoyle** [evanw/esbuild#586]
I'm trying to have esbuilt resolve the `main,module` fields when the platform is not node (I don't want the other defaults that come with `node`).

Given the following `package.json`:

```
{
  "name": "test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "esbuild": "^0.8.21",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  }
}
```

`index.js`:

```
import SSR from "react-dom/server";
```

And running: `yarn esbuild index.js --bundle --main-fields='module,main'` I'd expect `node_modules/react-dom/server.node.js` to be in the bundle, but instead I see `node_modules/react-dom/server.browser.js`.

The same happens why trying to add `--format=cjs`.

Per the docs at https://esbuild.github.io/api/#platform, it looks like `node` should set `format`, `mainFields` and some default `externals`. So, I'm not sure what is stopping me just being able to specify `mainFields` only.

**Comment by evanw** [comment]
This happens because when the platform is `browser`, this behavior is active (copied from the docs you linked to):

> * If a package specifies a map for the `browser` field in its `package.json` file, esbuild will use that map to replace specific files or modules with their browser-friendly versions. For example, a package might contain a substitution of `path` with `path-browserify`.

The `mainFields` setting only determines where the _default_ import comes from, which is what you get if you import just the package without any subpath (so `import 'react-dom'`). It does not affect the case where `browser` is a map that remaps subpaths within the package.

It looks like this behavior actually happens with Webpack too, at least as far as I can tell. If you set `mainFields: ['main']` in your `webpack.config.js` but you don't set `target: 'node'`, Webpack will still interpret the `browser` field remapping and give you `server.browser.js` instead of `server.node.js`. So esbuild's behavior this is consistent with the ecosystem in that respect.

The way to fix that in this case is to set the platform to `node`. Is there a reason that doesn't work for you?

**Comment by joehoyle** [comment]
> The way to fix that in this case is to set the platform to node. Is there a reason that doesn't work for you?

I was trying to avoid the automatic externals handling, and wasn't sure exactly what else might be coming with the `node` option under the hood. In my case, I'm actually running the bundle in V8 directly, not nodejs, so I don't have all the same libraries available.

As it happens though, I was able to use `platform: node` and then use my own esbuild plugin to manually overwrite the resolution of some paths. In this case I was trying to load `react-dom/server`. The browser version of this package doesn't include the `renderToNode` implementation as the `stream` package is required (so it's node-only)`. I was wanting to just have it resolve the `main` field for `react-dom/server` but then provide my own `stream` package to run in V8... I was able to get there with an esbuild plugin though!

Thanks again for the help @evanw, and also in making this quite amazing library!
