### ISSUE TITLE
Bundling a virtual file system

### ISSUE THREAD

**Issue by danvoyce** [evanw/esbuild#594]
I'm wondering if it's possible to achieve the equivalent of  `esbuild ./app --bundle --format=esm` but in the browser using `esbuild-wasm`?

Rather than having the source folder `./app` containing a bunch of files, I would have the equivalent in an array of data containing JavaScript strings that would later be evaluated, e.g.

```
[
    {
        name: 'index.js',
        location: '/',
        code: 'import { setup } from "./setup.js"...';
    },
    {
        name: 'setup.js',
        location: '/',
        code: 'export const setup = () => {};...',
    }
]
```

Thanks in advance for any help!

**Comment by evanw** [comment]
You can already do this my writing your own plugin for esbuild. Documentation is here: https://esbuild.github.io/plugins/. You will have to "bring your own file system" though since there is no file system exposed in the browser. You would need an on-resolve plugin to tell esbuild what absolute file system path is referenced by each import path in every file. The specifics depend on how you want path resolution to work but you could for example use the [resolve](https://github.com/browserify/resolve) package in your implementation to get node-style path resolution. Then you would also need an on-load plugin to give esbuild the contents for a specific file system path.

**Comment by danvoyce** [comment]
I'll be honest I'm no expert with build tools or Node - I'm more at home in the safety of the browser. Keen to give this a go though...

My first query is how to setup the plugin for `esbuild-wasm`? I've got the following so far:

```
const bundlePlugin = {
    name: 'bundle',
    entry: files[0].code,
    setup(build) {
        build.onResolve({ filter: /^http\// }, (args) => {
            console.log('args', args);
        });
    },
  };

buildService
    .build({ plugins: [bundlePlugin] })
    .catch((err) => console.log(err));
```

What should I set as the `entry`? I've currently set this to be the code string of the equivalent entry file, eg. `files[0].code`, but not seeing anything going on.

I guess also I'm struggling a little to understand how `onResolve` will work for this scenario.

Thanks @evanw!

**Comment by evanw** [comment]
From [the documentation](https://esbuild.github.io/plugins/#using-plugins):

> An esbuild plugin is an object with a `name` and a `setup` function.

Plugins don't have an `entry` property. I suppose I should detect and throw an error for unexpected properties so that doing this is an error.

The `service.build({ entryPoints: ['/index.js'] })` call takes a list of entry points. Each entry point is the path (not the contents) of the entry point file.

> I guess also I'm struggling a little to understand how `onResolve` will work for this scenario.

This function is called once for every import in every file. So for example if a file `/a/b/file.js` contains `import "../c/other.js"`, presumably that is supposed to reference the file `/a/c/other.js`. The `onResolve` function would need to return `{ path: "/a/c/other.js" }` so esbuild knows which file the import refers to. It has enough information to do this because when it's called in this situation:

* `args.path` is `"../c/other.js"`
* `args.importer` is `"/a/b/file.js"`
* `args.resolveDir` is `"/a/b"`

One way to do this would be something like this:

```js
let path = require('path')
build.onResolve({ ... }, args => {
  if (path.isAbsolute(args.path))
    return { path: args.path }
  if (path.resolveDir)
    return { path: path.join(path.resolveDir, args.path) }
});
```

If you want to do fancy stuff like `./other` resolving to `./other.js` (implicit file extensions) or `react` resolving to `./node_modules/react/index.js` (node-style package resolution) then you'll need to include more resolution logic such as what the [resolve](https://github.com/browserify/resolve) package provides.

> `build.onResolve({ filter: /^http\// }, (args) => {`

Note that this regular expression won't match `http://` because the regular expression doesn't have a colon. Not sure if this is intentional or not but I thought I'd point it out to save you some debugging in case that was an issue.

**Comment by danvoyce** [comment]
Ah yes my mistake, I was mixing up the params.

So if we don't have an entry point, how do we pass in the code to be bundled?

**Comment by evanw** [comment]
Entry points are central to how bundling works. Bundling means "inline all of this file's dependencies into a single file" and simulates what a real module loader such as node or the browser would do with your code.

I'm guessing you're looking for something like file concatenation instead of bundling? That's not something that esbuild is designed to do, since esbuild is a bundler.

You may be able to do this by creating an entry point file consisting of just `import "..."` statements, one per file, and giving that to esbuild. But each file will have its own scope since that's how imports work, so this may not work for your use case.

Another possibility could be to concatenate the files yourself with string concatenation and then run esbuild on the result to do minification. But that wouldn't work with source maps without extra work on your part to concatenate the source maps too.

**Comment by danvoyce** [comment]
Ahh damn, I thought something wasn't quite adding up.

I've ended up getting my hands dirty and writing my own babel plugin to effectively bundle the separate virtual files. It works pretty well actually. Now just to get the source maps working. 

Thanks for your help!

**Comment by evanw** [comment]
Closing this since it seems resolved.
