### ISSUE TITLE
Transform syntax for newer targets

### ISSUE THREAD

**Issue by TheSpyder** [evanw/esbuild#606]
One of the things I miss coming from rollup+terser is the ability to set compress options to [transform ES5 syntax for modern browsers](https://terser.org/docs/api-reference#compress-options). I use a build tool that outputs ES5 but I target modern browsers, in particular the terser `arrows` and `unsafe_arrows` options are able to reduce the bundle size quite a bit.

I've just finished applying terser manually to the output of esbuild, it saves 18% on the bundle but takes 4 seconds so I'll only do it for production builds. It would be nice to have something like this in my development builds as well.

Perhaps the `target` option could be leveraged to apply inverse transforms?
https://esbuild.github.io/content-types/#javascript

**Comment by evanw** [comment]
Some inverse transformations are already supported in esbuild. For example, esbuild will transform `a !==null && a !== undefined ? a : 1` to `a ?? 1` when minifying if the `??` syntax is supported. I could see adding support for other transforms if they are semantically equivalent. The `arrows` setting in Terser sounds like an appropriate transformation for esbuild to do when minifying.

**Comment by TheSpyder** [comment]
Ah good to know! `arrows` would be a big win imo, replacing all instances of `function` and probably a lot of `return` too.

**Comment by evanw** [comment]
I just did a quick test with `arrows`-like functionality on a large private code base I have access to. It did make the minified size slightly smaller but it made the minified size after gzip slightly bigger. So this transformation is actively unhelpful, at least in this case. This makes sense since the character sequence `(){return` is likely already very common in the gzip dictionary. Given that, I'm thinking that it probably doesn't make sense to add this behavior to esbuild's minifier.

I'm not interested in adding the equivalent of Terser's `unsafe_*` minification options to esbuild. I intend for the minifier in esbuild to be generally safe to run and to not have many options to keep esbuild easy to use. It's more appropriate to use other tools for custom AST transformations like that which can break your code when used incorrectly.

**Comment by evanw** [comment]
I'm going to close this for the reasons above.

**Comment by TheSpyder** [comment]
Sorry, I did mean to reply yesterday - I think that's fine. It's probably better to encourage the tool that's generating ES5 functions to support arrow functions anyway.
