### ISSUE TITLE
[Question] Potentially malicious

### ISSUE THREAD

**Issue by amursky** [evanw/esbuild#62]
**OS:** Windows 10 Enterprise x64
**esbuild:** esbuild-windows-64@0.0.10

https://www.adlice.com/threat/?threat=MalPE.99

![image](https://user-images.githubusercontent.com/33891482/79339198-da5d5780-7f6b-11ea-8d7f-d74f5b82bb21.png)

**Comment by evanw** [comment]
It's definitely not malicious of course (assuming this is the official build from npm). You can always build the executable from source if you're concerned.

Antivirus software often flags things using heuristics that don't actually have anything to do with malicious behavior. I wonder if the fact that this is written in Go triggered this. In my experience, antivirus software is sometimes triggered by non-standard executable layouts.

Anyway if this is getting in the way for you and ignoring this is not an option, another option is to use the [WebAssembly esbuild package](npmjs.com/package/esbuild-wasm). I suspect that will be able to bypass the antivirus scanner. It will be a lot slower of course.

I'm going to close this since I don't think there's anything actionable I can change about esbuild to help fix this.
