### ISSUE TITLE
const is replaced by var

### ISSUE THREAD

**Issue by 2beers** [evanw/esbuild#623]
```
// a.js
export const a = {
    a: "a"
};

// main.js
import {a} from "./a";
const v1 = a;
console.log(v1);


//out.js
// src/a.js
var a = {
  a: "a"
};

// src/main.js
var v1 = a;
console.log(v1);

```

I use the following command
`esbuild src/main.js --bundle --format=esm --target=es2020 --outfile=out.js`

`const v1 = a;` is replaced with `var v1 = a;`

Is there an option to keep const instead of var?

**Comment by remorses** [comment]
This is because in Safari declaration with `const` were mush slower than `var`, is there any reason you want to keep `const`?

**Comment by evanw** [comment]
There are also some other reasons, which are described here: https://github.com/evanw/esbuild/issues/598#issuecomment-744729885.

**Comment by 2beers** [comment]
@remorses Not really. I assume only top level const/let are replaced with var?
I'm testing esbuild to see if I can replace rollup in a production project. 

Maybe an option to enable/disable this behavior.

**Comment by evanw** [comment]
As mentioned above, this behavior is deliberate and is done for at least three reasons. It sounds like you don’t have a reason you need to keep `const` since you said “not really”? If so, I would like to close this issue and just keep the current behavior. I’m trying to keep the number of options that esbuild exposes low to avoid esbuild being unnecessarily complex to configure as a user and to avoid it being unnecessarily complex to develop and test for me. Each option has a cost and I’m not going to throw in more options unless there are strong reasons for them.

**Comment by 2beers** [comment]
Sure. I understand. You can close this thread. I don't mind if it's using var on top level. It just looked weird when I saw it the first time, but I read your comment on the other thread and made more sense.
