### ISSUE TITLE
Feature request: Output some build results

### ISSUE THREAD

**Issue by exalted** [evanw/esbuild#631]
On a successful run `esbuild` CLI will currently output nothing and exit with 0 status code.

This is GREAT actually, however I'd appreciate some output either via `--log-level=info` or a new flag (e.g., `--verbose`).

For the most part I am looking for some output which indicates which files have been bundled (source & destination), how much it took to process each file and overall time spent, etc.

Thanks.

**Comment by evanw** [comment]
Thanks for asking for this. This has been a request in the past from others as well and is something I have also wanted on occasion. I just added a new flag for this: `--summary`. You can see an example of what it looks like in [the release notes](https://github.com/evanw/esbuild/blob/f70234145bfa505e832eaebe997c937de576c459/CHANGELOG.md#unreleased). This feature will go out with the next release.

I chose `--summary` instead of `--verbose` because I'd like to reserve `--verbose` for verbose debugging output if it's necessary in the future. And I didn't include the time to process each file in the summary because that's not something I can measure. Files are processed in parallel instead of sequentially and many intermediate steps are shared between output files.

**Comment by exalted** [comment]
Looks neat @evanw . Thank you! 🙂

**Comment by exalted** [comment]
I personally don't use `--serve`, however I wonder if this kind of output would be useful in that as well (i.e., if https://github.com/evanw/esbuild/commit/f70234145bfa505e832eaebe997c937de576c459 doesn't already cover that as well). :two-cents:

**Comment by saramorillon** [comment]
Hello, is this feature available? I get this error when I try to use it:
![image](https://user-images.githubusercontent.com/4224278/200028827-0916fdb7-fe40-44ce-bd5b-b9bd5582b73c.png)

**Comment by evanw** [comment]
This option was removed. Instead, esbuild now just always prints a summary by default. This has been the case for over a year now. This change happened in [esbuild version 0.9.0](https://github.com/evanw/esbuild/releases/v0.9.0), released in March 2021.

**Comment by saramorillon** [comment]
Hello @evanw , thank you for your answer. I don't see a summary when I use esbuild v0.15.13. Here is my build script:
```
require('esbuild').build({
  entryPoints: ['src/index.ts'],
  bundle: true,
  outdir: 'dist',
  minify: true,
  sourcemap: true,
  watch: true,
})
```
Am I doing something wrong?

**Comment by evanw** [comment]
You are missing `logLevel: "info"`. The [log level](https://esbuild.github.io/api/#log-level) only defaults to `info` for the CLI. It defaults to `warning` when using the JS `build` API, so you'll need to set it to `info` if you want to see info log messages.

**Comment by saramorillon** [comment]
Thanks a lot, it's working now!
