### ISSUE TITLE
Include file from outside of the project root

### ISSUE THREAD

**Issue by henriquehbr** [evanw/esbuild#634]
According to the docs:

> If your build contains multiple entry points in separate directories, the directory structure will be replicated into the output directory starting from the lowest common ancestor directory among all input entry point paths. For example, if there are two entry points src/home/index.ts and src/about/index.ts, the output directory will contain home/index.js and about/index.js. If you want to customize this behavior, you chould change the outbase directory.

**Full context:** I'm refactoring [`svelte-typewriter`](https://github.com/henriquehbr/svelte-typewriter) codebase, it's essentially composed by the library source code on the root directory, and a `example` subdirectory with a demo Svelte project for testing purposes with the following directory structure:

```
.
├── build.js
├── jsconfig.json
├── package.json
├── public
│   ├── favicon.ico
│   └── index.html
├── rollup.config.js
├── src
│   ├── App.svelte
│   ├── components
│   │   ├── TypewriterControls.svelte
│   │   └── TypewriterMode.svelte
│   ├── index.js
│   └── pages
│       ├── Cascade.svelte
│       ├── Default.svelte
│       ├── Loop.svelte
│       └── LoopRandom.svelte
└── yarn.lock
```

I'm building the Svelte component with the following config:

```js
await esbuild.build({
	entryPoints: ['./src/index.js'],
	platform: 'browser',
	bundle: true,
	format: 'esm',
	splitting: true,
	outbase: './',
	outdir: 'public/build',
	plugins: [sveltePlugin()]
})
```

When i try to import `./src/Typewriter.svelte` from `./example/src/components/TypewriterControls.svelte`, esbuild end up including unnecessary files/folders from root directory (like `example`,  and `src`), is there any viable way to import a file from outside of the project folder, and build it with `outdir` without replicating the whole directory structure of the imported file parent directory?

---

**Edit:** i even tried including `outbase` in the config as pointed in the docs, but with no luck, i received the following error:

> `Cannot traverse from directory "../src/helpers" to chunk "chunk.34VXZT2I.js"`

I'm not 100% sure of what could be happening here, but i suspect that it might have something to do with the `*.js` files imported by the Svelte component not being able to properly import their modules

**Comment by evanw** [comment]
There are enough details here that I'm not sure exactly what's going on. For example, some of the files in https://github.com/henriquehbr/svelte-typewriter use paths that start with `@example/` and esbuild doesn't have built-in logic to resolve those. Would it be possible for you to provide a way for me to reproduce this issue, such as a branch in your repo that includes the esbuild script and any other necessary packages?

**Comment by henriquehbr** [comment]
Of course, [this branch](https://github.com/henriquehbr/svelte-typewriter/tree/repro/esbuild) contains the whole project structure for reproducing the bug in question

Just for clarification, both build scripts are called `build.js`, and contains the configuration for building the example Svelte app in `example/src/App.svelte` and the library in `src/Typewriter.svelte`, respectively

I thought about cloning the `Typewriter.svelte` component to the `example` directory every time it is built, but in a Rollup context, this wasn't needed, so i thought it would be cool to see if such behavior could also be achieved with esbuild without doing some hacks

Many thanks for your time and support!

**Comment by evanw** [comment]
Thanks. I can reproduce the issue. It looks like esbuild is expecting all entry points to be inside the `outbase` directory but with this setup, some of the entry points are outside the `outbase` directory. This is because the dynamic `import()` expressions in `src/modes/index.ts` generate additional entry points. I hadn't considered this possibility when I accepted the PR that added `outbase`.

When esbuild generates the output path for a bundled entry point, it computes the relative path from `outbase` to the input entry point file and then joins that relative path to the output directory. If the entry point isn't under the `outbase` directory then that would cause esbuild to try to write the output file outside of the output directory (if the build had succeeded). That's obviously not good.

What are you expecting the output directory to look like in this case? The generated output paths look something like this (if `..` was a valid directory name):

```
public/build/../src
public/build/../src/helpers
public/build/../src/helpers/index.js
public/build/../src/modes
public/build/../src/modes/loopTypewriter.js
public/build/../src/modes/typewriter.js
public/build/chunk.34VXZT2I.js
public/build/chunk.EET7KLGS.js
public/build/chunk.R77EYHP3.css
public/build/chunk.SNO4HFOA.js
public/build/src/index.js
public/build/src/pages
public/build/src/pages/Cascade.js
public/build/src/pages/Default.js
public/build/src/pages/Loop.js
public/build/src/pages/LoopRandom.js
```

I can't just remove the leading `../` from the relative path because that might cause a collision with something else. For example, both `src/index.js` and `../src/index.js` might exist. I suppose I could replace it with `.._/` or something. That appears to be a valid directory name on Unix and Windows. Yeah, I should probably just do that.

**Comment by henriquehbr** [comment]
Sorry for reopening this, as a asnwer to your question, i expected the output directory to be "flattened", for instance, instead of generating `public/build/src/{helpers,modes}`, i was hoping for both helpers and modes to be inserted directly into the root level of `outdir`, like `public/build/{helpers,modes}`, is there any viable way to achieve such behavior?

Rollup has a option that can help explain this concept better, called [preserveModules](https://rollupjs.org/guide/en/#outputpreservemodules), but i'm not 100% sure that it's related or exists in esbuild context
