### ISSUE TITLE
Reference in package-lock is architecture-specific

### ISSUE THREAD

**Issue by StefanoChiodino** [evanw/esbuild#642]
Hello,

I've been struggling to run my build in docker. I've found that the problem seems to be that I'm developing on a mac, and the package-lock referenced `https://registry.npmjs.org/esbuild/-/esbuild-0.8.29.tgz`, but in Linux trying to run that throws `cannot execute binary file: Exec format error`.

I've then added a manual install esbuild in docker and the download location seems to be `https://registry.npmjs.org/esbuild-linux-64/-/esbuild-linux-64-0.8.29.tgz`. So it seems to me I can't rely on npm installing the correct version using the project files.

Is this expected?

Thanks

**Comment by evanw** [comment]
The main `esbuild` package contains an install script that installs the corresponding secondary package for the current OS and architecture. So if you install the `esbuild` package it will also install `esbuild-darwin-64` on macOS and `esbuild-linux-64` on Linux to download the binary executable.

This means the `node_modules` install folder is specific to your current OS and architecture. You can't copy it to another OS and expect it to work. Instead, you would need to delete the `node_modules` folder and re-install the `esbuild` package which would re-run the install script and re-download the correct binary executable. This is expected. I believe this is how other binary npm packages work too such as those that generate `*.node` native modules in their install scripts.

If you install the `esbuild` package, your `package-lock.json` file should only have an entry for `esbuild`. It should not have an entry for `esbuild-darwin-64` or `esbuild-linux-64` because those are installed to a temporary directory and then discarded. They are only used as a mechanism for downloading the binary executable. So I don't think I fully understand your problem. I don't use Docker myself, sorry.

**Comment by StefanoChiodino** [comment]
Hi @evanw , thanks for your reply. I believe what's happened here is that I'm copying over the `node_modules` folder without realising! I'll close this for now, thanks again!
