### ISSUE TITLE
How to debug transform + minify issues?

### ISSUE THREAD

**Issue by AlexGalays** [evanw/esbuild#644]
Hello,

I have a js file generated by svelte that breaks esbuild --minify but I can't get at the file that caused it as the only error I see is "The service was stopped", seemingly for an unrelated file (which I can minify alright with the same options so it's probably another file that fails)

How can I find out which string makes esbuild --minify fail?

**Comment by evanw** [comment]
Sorry this is happening. The first thing to check is that either you or some library you are using is not calling `stop()` on the service yourself. If so, all subsequent attempts to use the service will fail with that error.

If you aren't calling `stop()` yourself, then I'm guessing this probably sounds like an internal error inside the Go part of esbuild. That's unfortunate because these are harder to debug. If you are willing to share your source code, then I'm more than happy to debug this problem and fix it myself. That's probably the fastest way to fix this. Otherwise, here are some tips for debugging a crash in the Go part of esbuild:

If there is a bug that causes Go to panic and abort the process, I believe the panic information including the stack trace should be printed to stderr. It would be useful to know if this is happening because it would help to determine how to find out which string makes esbuild --minify fail.

Another way to debug this could be to build esbuild yourself from the Go code in the repo and then substitute your copy of esbuild into your script. It can be built by cloning the repo, installing Go, and then running `go build ./cmd/esbuild` in the repo. You can then substitute it into your script using `ESBUILD_BINARY_PATH=/path/to/esbuild node your-script.js`. The `ESBUILD_BINARY_PATH` environment variable overrides the executable used by the `esbuild` npm package. From there you could add `fmt.Fprintf(os.Stderr, "debugging information")` to various places in the Go code to figure out at what part the build is being stopped.

**Comment by AlexGalays** [comment]
Thanks a lot for all this information. The good news is: no Go debugging will be required. I hadn't even considered the abstraction on top of `esbuild` was responsible for prematurily calling stop() but It is indeed the case. I will open a bug ticket at `rollup-plugin-esbuild` instead.
