### ISSUE TITLE
esbuild vs rollup-plugin-esbuild

### ISSUE THREAD

**Issue by henriquehbr** [evanw/esbuild#651]
Accordingly to the benchmark, **esbuild** takes **0.37s** to do a production bundle of 10 copies of the three.js library from scratch using default settings, while **rollup + terser** takes 36s (a roughly increase of almost **10000%** in build time)

So far, so good, but what about third party plugins that makes use of esbuild under the hood? would it be interesting enough to add it to the benchmarks? i'm not sure how well `rollup-plugin-esbuild` performs in comparison to a bare-bones esbuild scenario

**Comment by lukeed** [comment]
You would only be gaining performance wrt the minification step. The `rollup-plugin-esbuild` transforms files individually, relying on Rollup to do everything else (aka – parse, follow, link, shake, bundle).

This gain would still be significant; but I don't imagine it'd compare to `esbuild`'s raw 0.37s.

**Comment by henriquehbr** [comment]
Thank you @lukeed, do you think it would be valuable to add this entry to the benchmarks? if is there anything that i can contribute with about this, please, let me know and i will be happy to help

**Comment by lukeed** [comment]
Oh, not up to me at all! :D Just sharing my thoughts.

**Comment by chowey** [comment]
This seems similar to #318.

> I'm not currently planning to do this. There's a lot of different combinations of everything that could be added to the benchmark but I feel like that's visually overwhelming and makes it harder to read.

**Comment by henriquehbr** [comment]
Is there any specific section on the docs about how to reproduce the exact same benchmark environment, in order to do the tests by yourself, but with other tools/frameworks?

I was taking a look on the `package.json` of [`three.js`](https://github.com/mrdoob/three.js), looking for build scripts and studying it's structure, but i'm still not sure if i would be doing it the right way, mainly due to being related to such a massive project, with thousands of files and commits, because of that, i'm afraid of possibly getting unrealistic results

**Comment by evanw** [comment]
> Is there any specific section on the docs about how to reproduce the exact same benchmark environment, in order to do the tests by yourself, but with other tools/frameworks?

This is documented here: https://esbuild.github.io/faq/#benchmark-details. Use `make bench-three` and `make bench-rome` in this repo to reproduce the two benchmarks on the website. If you just want to build the code for the benchmarks but not actually run them, you can use `make bench/three` and `make bench/rome`.

> I was taking a look on the `package.json` of [`three.js`](https://github.com/mrdoob/three.js), looking for build scripts and studying it's structure, but i'm still not sure if i would be doing it the right way, mainly due to being related to such a massive project, with thousands of files and commits, because of that, i'm afraid of possibly getting unrealistic results

I chose the Three.js project because the source is trivial to bundle. There are no dependencies and all files are plain JavaScript with relative paths. You don't even have to deal with the CommonJS format. So it should be very easy to get this working.

For example, to bundle one copy of Three.js instead of 10 copies like the benchmark, you can do this:

```
$ git clone --depth 1 --branch r108 https://github.com/mrdoob/three.js.git three
$ esbuild --bundle three/src/Three.js --outfile=Three.bundle.js
```

The real benchmark is similar but it just copies the Three.js source code 10 times and then bundles an entry point file that re-exports `src/Three.js` from each copy.

**Comment by henriquehbr** [comment]
Many thanks again @evanw! keep up the great job with esbuild :)
