### ISSUE TITLE
Don't drop /*@__PURE__*/ comments

### ISSUE THREAD

**Issue by Djaler** [evanw/esbuild#653]
Related to #221.

These comments should stay in the library build so client bundlers can respect them.

**Comment by evanw** [comment]
This is already the case. These comments are not dropped:

```
$ echo '/*@__PURE__*/fn()' | ./esbuild 
/* @__PURE__ */ fn();
```

**Comment by Djaler** [comment]
Sorry, I forgot to note that they are dropped if minify enabled

**Comment by Djaler** [comment]
```
const { transformSync } = require('esbuild');

console.log(transformSync(
    `
    const foo = /*@__PURE__*/ bar();
    
    export default foo;`,
    { minify: true },
).code);

// produces: 
// const o=bar();export default o;
```

**Comment by evanw** [comment]
It is expected behavior that they are dropped when minification is enabled. Minification is intended to produce production-ready assets to serve to users, and these comments would mean sending users many additional useless bytes. If you are generating code that is intended for another bundler to process, you can disable minification to preserve these comments and then enable minification in the other bundler so that the result is still minified.

**Comment by Djaler** [comment]
Makes sense, thanks
