### ISSUE TITLE
Constant folding in development builds

### ISSUE THREAD

**Issue by Xiot** [evanw/esbuild#657]
I've noticed a case where the constant folding isn't happening where I thought it should.

It works great in tertirary operators, however it doesn't seem to fold with constant `if` conditions.

```
echo "if (process.env.NODE_ENV === 'production') {
  module.exports = require('./cjs/react-dom.production.min.js');
} else {
  module.exports = require('./cjs/react-dom.development.js');
}" | esbuild --define:process.env.NODE_ENV=\"production\"

if (true) {
  module.exports = require("./cjs/react-dom.production.min.js");
} else {
  module.exports = require("./cjs/react-dom.development.js");
}
```

Looking at #371 it appears like that should be folded properly.

If I enable minification, it does do the proper foldinig.
```
echo "if (process.env.NODE_ENV === 'production') {
  module.exports = require('./cjs/react-dom.production.min.js');
} else {
  module.exports = require('./cjs/react-dom.development.js');
}" | esbuild --define:process.env.NODE_ENV=\"production\" --minify

module.exports=require("./cjs/react-dom.production.min.js");
```

**Comment by evanw** [comment]
This is true, but why is this a problem?

**Comment by Xiot** [comment]
For the same reason that you explained in the linked issue.  It throws off static analysis and bundling.
It's not a huge issue for me, as `--minify-syntax` will do the proper folding and I can use that before bundling.

It's just something that I noticed that didn't seem to work the way it "should".

**Comment by heyheyhello** [comment]
I see why you think it should fold, but there's certainly people who wouldn't want it to. Makes it easier to diff code before and after using --define flags in large projects, for instance.

**Comment by Xiot** [comment]
I was going off of what @evanw said in the other thread.
@heyheyhello , do you think this should automatically fold?

```
echo "const value = flag ? 'prod' : 'dev';" | esbuild --define:flag=false
const value = "dev";
```

The reason that I brought it up was the incosistency in folding between tertiary operators and if statements

**Comment by heyheyhello** [comment]
Oh interesting, I didn't know about ternary folding. Personally I don't think it should fold. Thanks for the catch. It would be nice if it was consistent, whichever way it goes.

**Comment by evanw** [comment]
This whole feature is motivated by these few lines of code in React, which makes doing this necessary. When not minifying, esbuild still does enough constant folding to be able to determine that `process.env.NODE_ENV === 'production'` is a constant so it knows which branch is dead. That then tells esbuild that it can ignore the `require()` call inside the dead branch and avoid the overhead of parsing all of React twice, which is a performance win because the React library is a lot of code. So not doing this constant folding would have a performance cost. But esbuild doesn't go further than that because minification is not technically enabled, and some people have requested that esbuild _not_ remove dead code when not minifying. So the current behavior is intentional and is motivated by practical concerns.

**Comment by Xiot** [comment]
Not removing dead code when not minifying makes a lot of sense, and I agree that the its the way to go.
In this case, should the tertiary operator be folded when minification is disabled ?

**Comment by evanw** [comment]
Sure, I can turn off dead code elimination for that specific case. Previously it was only done for expressions but not for statements. With this change it will now be done for all expressions except no longer for conditional expressions.
