### ISSUE TITLE
support to change AST through plugin

### ISSUE THREAD

**Issue by sessionboy** [evanw/esbuild#658]
Hi, i need to change AST through plugin, hope esbuild can support it.

1,  I need to rewrite the path of the bare module to a relative path and I don't need to check it. 

##### before rewrite:
```js
import React, { useState }  from "react";
export default ()=> {
  return <div>hello world!</div>
}
```
##### after rewrite:
```js
import React, { useState }   from "../@modules/react.acsd243.js";
var __default = () => {
  return /* @__PURE__ */ React.createElement("div", null, "hello world!");
};
export {
  __default as default
};
```
The onResolve and onLoad API can't do this.

2，I need to inject specific code, such as hmr code
```js
/** React Refresh: Setup **/
var prevRefreshReg = window.$RefreshReg$;
var prevRefreshSig = window.$RefreshSig$;
window.$RefreshReg$ = (type, id) => {
  window.$RefreshRuntime$.register(type, "/Volumes/work/react-build/src/App.js" + " " + id);
}
window.$RefreshSig$ = window.$RefreshRuntime$.createSignatureFunctionForTransform;


import React, { useState }   from "../@modules/react.acsd243.js";
var __default = () => {
  return /* @__PURE__ */ React.createElement("div", null, "hello world!");
};
export {
  __default as default
};


$RefreshReg$(_c, "App");
/** React Refresh: Connect **/
if (import.meta.hot) {
  window.$RefreshReg$ = prevRefreshReg
  window.$RefreshSig$ = prevRefreshSig
  import.meta.hot.accept(() => {
    window.$RefreshRuntime$.performReactRefresh()
  });
}
```

3,  Expose the parser and lexer API. I need to parse the dependency graph of the module and process it.

Now in order to achieve the above goals, I have to use bundler such as rollup and parser such as babel, which will slow down my build speed and increase complexity. I hope that esbuild can natively support these features to bring the best performance and convenience.

**Comment by evanw** [comment]
Closing this since I am not planning to support an AST API in esbuild. You can read more about this on [esbuild's roadmap](https://esbuild.github.io/faq/#upcoming-roadmap).

That said, `onResolve` is intended for changing import paths. You can use an `onResolve` plugin to intercept `react` and remap it to `../@modules/react.acsd243.js`. And `onLoad` is intended for changing source code before it has been compiled with esbuild. You can use an `onLoad` plugin to insert extra JavaScript into your files. Keep in mind that esbuild doesn't support HMR so `import.meta.hot` would have to exist in your host environment.
