### ISSUE TITLE
"Assignment to itself has no effect"

### ISSUE THREAD

**Issue by arcanis** [evanw/esbuild#666]
My understanding is that third-party packages shouldn't emit warning due to weird syntax (https://github.com/evanw/esbuild/issues/395#issuecomment-697827458), but it doesn't seem to be the case every time. I have the following construct coming from `got` (caused by [this line](https://github.com/sindresorhus/got/blob/master/source/core/utils/url-to-options.ts#L21)):

```ts
url = url;
```

Which generates the following warning:

```
> [...]/got/dist/source/core/utils/url-to-options.js: warning: Assignment of "url" to itself has no effect
    6 │     url = url;
      ╵     ~~~~~~~~~
```

**Comment by arcanis** [comment]
Similarly, I have the following warning:

```
 > [...]/keyv/src/index.js: warning: This call to "require" will not be bundled because the argument is not a string literal (surround with a try/catch to silence this warning)
```

While it could be a valid warning, in my case it's not, this code will never be triggered (it's caused by `got` depending on `cacheable-request`, itself on `keyv`, with `keyv` having some sort adapters of databases 🤷‍♀️). It would be nice to have a way to hide this warning (perhaps in relation to #665).

**Comment by evanw** [comment]
> ```
> > [...]/got/dist/source/core/utils/url-to-options.js: warning: Assignment of "url" to itself has no effect
> ```

I'd like to know what this error message originally looked like before you replaced part of it with `[...]`. I assume the path didn't originally look like that. Is this file in a `node_modules` folder?

> ```
>  > [...]/keyv/src/index.js: warning: This call to "require" will not be bundled because the argument is not a string literal (surround with a try/catch to silence this warning)
> ```

This warning exists to tell you about code that isn't being bundled. The alternative of ignoring this code would mean that the generated bundle is likely to fail at run-time since some of the code is missing. It felt like a good idea to have this warning because other bundlers may actually bundle code like this successfully due to dynamic file system emulation, so people may actually expect it to work. And an extra warning is mostly harmless but a silently failing build can be very annoying and hard to debug.

**Comment by arcanis** [comment]
> I'd like to know what this error message originally looked like before you replaced part of it with `[...]`. I assume the path didn't originally look like that. Is this file in a `node_modules` folder?

Yep. The full path was something like:

```
pnp:/home/arcanis/app/.yarn/cache/got-somehash/node_modules/got/dist/source/[...]
```

> And an extra warning is mostly harmless but a silently failing build can be very annoying and hard to debug.

Fair enough 👍

**Comment by evanw** [comment]
Ah that makes sense. Looks like these warnings are only ignored for files inside `node_modules` if the path does not originate from a plugin. This is because this feature was added before plugins were added. Will fix.
