### ISSUE TITLE
Update Parcel 2 in esbuild benchmarks

### ISSUE THREAD

**Issue by devongovett** [evanw/esbuild#669]
The latest Parcel 2 nightlies are much faster than shown on the esbuild website and in the readme. The three.js benchmark builds in 53s on my machine (~2x faster). It would be great if you could update the data shown in your charts as well. 😄 

<img width="955" alt="image" src="https://user-images.githubusercontent.com/19409/104390909-c18ace00-550c-11eb-99b3-e5a6ce5885ce.png">

**Comment by evanw** [comment]
That's really exciting! I've been following along with your work so I know how much work went into this. Congrats on the improvements. I'll update my benchmarks soon.

**Comment by evanw** [comment]
I just finished re-running the benchmarks. Here's what I got:

**Time:**

| | JS benchmark | TS benchmark |
|---|---|---|
| `2.0.0-nightly.475` | 108.66s | 53.13s |
| `2.0.0-nightly.527` | 56.71s (1.92x faster) | 42.32s (1.26x faster) |

**Size:**

| | JS benchmark | TS benchmark |
|---|---|---|
| `2.0.0-nightly.475` | 5.81mb | 1.68mb |
| `2.0.0-nightly.527` | 5.92mb (2% larger) | 1.68mb (no change) |

So great news that the 2x speedup works out in practice! This puts Parcel 2 in between Webpack 4 and Webpack 5 in terms of performance.

However, it looks like the latest update broke source maps. I'm not completely sure what happened but in my usual test of inserting `throw new Error` into the `BoxGeometry` constructor and then running the [hello world example](https://threejs.org/docs/index.html#manual/en/introduction/Creating-a-scene), it's mapping the location to the wrong file.

I consider working source maps to be a requirement for inclusion in the benchmark. Can you confirm whether or not you can also reproduce the source map issue? And would it be possible to fix source maps in Parcel 2 so that I can update the benchmark with the new times?
