### ISSUE TITLE
sideEffects in package.json doesn't appear to be respected

### ISSUE THREAD

**Issue by Ventajou** [evanw/esbuild#670]
I'm trying to get a html file copied to the output dir by importing it. Here's my setup:

hammer/html/src/index.ts:
```
import './foo.html';
```

hammer/html/package.json:
```
  ...
	"main": "src/index.ts",
	"sideEffects": [
		"./src/foo.html",
		"./src/index.ts"
	],
  ...
```

I'm using the JS API and set the options to use the file loader for html extensions.

When I try to build, I get: 
```
 > hammer/html/src/index.ts: warning: Ignoring this import because "hammer/html/src/foo.html" was marked as having no side effects
    1 │ import './foo.html';
      ╵        ~~~~~~~~~~~~
```

I know the package.json file is read because if I remove the html file from it, I get an extra error:
```
     hammer/html/package.json: note: It was excluded from the "sideEffects" array in the enclosing "package.json" file
    5 │   "sideEffects": [
      ╵   ~~~~~~~~~~~~~
```

I use the API to run esbuild and set the CWD to outside of the package because the tool is aimed at a monorepo. I tried without that and don't see a difference so I don't think that's it.

Also using `"sideEffects": true` doesn't work either...

**Comment by evanw** [comment]
A file is currently marked as side-effect free if either:

* The `sideEffects` field says it is side-effect free (either by being `false` or by omission in the array).
* The loader is one marked as having no visible side effects.

Currently all loaders that export a string as a default value are marked this way, including the `file` loader. The rationale is that even though the generation of a file in the output directory is an externally-visible side effect, the name of that file is an unstable internal implementation detail of esbuild. The only way you are supposed to access the file is by using the file name that is saved in the default export. So if the default export is unused, esbuild assumes that the file is unused. This is helpful for removing unused files from your build.

I'm guessing you are doing this to try to get the file `foo.html` to end up in the output directory. But that won't happen even if that import is preserved because the file will be renamed to something like `foo.LQ3SVOLM.html` due to the way the `file` loader works. If you want the file `foo.html` to end up in the output directory, I would recommend copying it there manually using another script instead.

**Comment by Ventajou** [comment]
That makes a lot of sense, thanks!
