### ISSUE TITLE
How to skip transform javascript code?

### ISSUE THREAD

**Issue by hardfist** [evanw/esbuild#674]
we want to use esbuild as our  build tools(which is super fast), But because our target is not browser and node( an embed Javascript runtime), which transform may break code , so I want to know is there any way to disable transform Javascript code when bundle, thanks。

**Comment by evanw** [comment]
It's not currently possible to set the platform to something other than the browser or node. Can you say more about your use case? Which of esbuild's transforms are breaking your code, and how?

**Comment by hardfist** [comment]
our build tools use two different javascript languages(for different purpose), one of which  supports a subset of es3(JS-A), which most transform tools doesn't support, but we support esm by using rollup  for now(because rollup doesn't do any transform  by default, which meets our needs),and another js language(supports es5+,JS-B) use esbuild as our build tools, so we want also want to  use esbuild instead of rollup to build the JS-A,but the  transform result may break the code。

**Comment by evanw** [comment]
You can now specify `--platform=neutral` to disable esbuild's defaults. There is more information here: https://esbuild.github.io/api/#platform.

**Comment by hardfist** [comment]
> https://esbuild.github.io/api/#platform

It seems that even though I set platform `neutral`, It still do some transform(like transform `let` to `var`)

**Comment by SergeiMinaev** [comment]
Same here. I want to keep **const**s for example. Is there any way to bundle files without transpilation?

**Comment by evanw** [comment]
> I want to keep consts for example.

Why do you want to do this? Is it just for aesthetics? Whenever `const` is transformed to something else, esbuild makes assigning to a `const` symbol a build error so it should not be possible to bundle code that assigns to `const` and have it work at run time (in case that's what you are worried about).

It is intentionally not possible to keep top-level `const` symbols as `const` during bundling because some upcoming bundling features will require removing top-level `const` symbols to allow for lazy initialization of modules. In addition, changing top-level `const` and `let` to `var` improves the performance of your code. The `const` and `let` features introduce additional overhead compared to `var` because of checks for something called the "temporal dead zone." This is especially problematic for bundling because bundling creates a single extremely large top-level scope with lots of variables, and certain JavaScript VMs have a huge performance penalty (e.g. >5 additional seconds of initialization time) in this case if you use `const` and `let` instead of `var`.

**Comment by SergeiMinaev** [comment]
> Is it just for aesthetics? 

Yeah, it looks like this.

> Whenever const is transformed to something else, esbuild makes assigning to a const symbol a build error so it should not be possible to bundle code that assigns to const and have it work at run time (in case that's what you are worried about).

Ok I got it. 

> This is especially problematic for bundling because bundling creates a single extremely large top-level scope with lots of variables, and certain JavaScript VMs have a huge performance penalty (e.g. >5 additional seconds of initialization time) in this case if you use const and let instead of var.

Wow, this is interesting. I should rethink the priorities. Thanks!

**Comment by hardfist** [comment]
my case is very special, our javascript vm implementation does not support `var`,but support `let`, when esbuild transform `let `to `var`, it breaks our code

**Comment by evanw** [comment]
> my case is very special, our javascript vm implementation does not support `var`,but support `let`, when esbuild transform `let `to `var`, it breaks our code

That is interesting. However, I do not intend for esbuild to include logic for handling JavaScript language subsets like this. Various parts of esbuild's internals may produce `var` when bundling even independent of what your code looks like. This is because `var` is an older language feature than `let`, and it is assumed that older language features are safer to use than newer language features.

**Comment by hardfist** [comment]
so  esbuild's tranformer function is not opt-in but bound to it's other functionality?

**Comment by hardfist** [comment]
@evanw , Except `let` | `var` | `const` things, can other transformer features be opt-out ? esbuild plugin is so much elegant than rollup when deal with virtual module, This is the last thing stop I migrate from rollup.

**Comment by therealparmesh** [comment]
We use SWC quite a bit, but we also love the bundling functionality that esbuild provides over Webpack. If we could optionally skip the transform step for esbuild (in lieu of an esbuild SWC plugin), that'd be a perfect setup for us. Is there any chance such a proposed change would be accepted?
