### ISSUE TITLE
Chunking for CommonJS bundles

### ISSUE THREAD

**Issue by jfrconley** [evanw/esbuild#677]
I'm trying to bundle node_modules seperately from the application code of my node project to aid in readability when deployed to a lambda. I have moved all external imports to a file which then re-exports them for the rest of my application. I then bundle this file and my handler as seperate entrypoints. For the handler, I mark the depedency file as external.

*index.ts*
```
import {Dep} from "./dependencies"

Dep.doSomething();
```
*dependencies.ts*
```
export * as Dep from "dep"
```
*Build commands*

```
# app
esbuild --bundle --platform=node index.ts --external:"*/dependencies"
# dependencies
esbuild --bundle --platform=node dependencies.ts
```

This mostly works, but doesn't handle paths like "../dependencies" in the application. Is there some way to rename these paths, or a better way to do this?

**Comment by evanw** [comment]
One option: if you do not specify a `*` in the external path and use `./dependencies` instead, esbuild should consistently refer to the file in the same place regardless of whether or not it was traversed to by `./` or `../`. This happens because `*` patterns are matched before path resolution but other patterns are matched after path resolution.

Another option: you should be able to write an [on-resolve plugin](https://esbuild.github.io/plugins/#resolve-callbacks) to do whatever custom logic you need here. The plugin can return paths with `external: true` and whatever custom text you need.

**Comment by jfrconley** [comment]
Thank you, the external path change worked great!

**Comment by evanw** [comment]
That's great! Closing this issue then since it sounds like it has been resolved.
