### ISSUE TITLE
Incremental build doesn't seem to help SCSS bundle

### ISSUE THREAD

**Issue by buronnie** [evanw/esbuild#679]
I am working on a plugin to support scss integration. As we all know, node-sass or dart sass are slow and therefore become a performance bottleneck of the entire bundle process (bump up the bundle time from 400ms to 5s 🤕 ). I am not sure if there is anything we can do to boost the performance since I already try the async mode of [`sass.render()`](https://sass-lang.com/documentation/js-api#render) with [`Fiber`](https://sass-lang.com/documentation/js-api#fiber) enabled.

I also expect the incremental build can significantly shorten the build time in watch mode, but it seems to only reduce the time from 5s to 4s. I wonder if it's because built scss files are not cached. Thanks for your great work!

**Comment by zaydek** [comment]
Wouldn’t you want your plugin to be responsible for caching, rather than esbuild? AFAIK esbuild incremental recompilation doesn’t have to do with plugins / files outside of esbuild. _I could be wrong._

I have a lot of experience compiling Dart Sass. A few recommendations:

- Try upgrading to 1.32.3 (https://github.com/sass/dart-sass/releases/tag/1.32.3) or later. They recently fixed a bug that lead to +30% speedups for my large code base.
- You can also use the native Dart Sass, distributed from the GitHub release pages. This is like 2-3x faster. So my project went from 10 seconds to 7 seconds by upgrading to 1.32.3, and then went down to 3 seconds when I upgraded to native Dart Sass.

Anyway, am also interested to hear what are the recommendations concerning caching externally compiled assets like Sass. 😇

**Comment by evanw** [comment]
> AFAIK esbuild incremental recompilation doesn’t have to do with plugins / files outside of esbuild. _I could be wrong._

This is correct. See also [this thread](https://github.com/evanw/esbuild/issues/567#issuecomment-735516227).

I'm not familiar with the library you are using but does it compile each file independently? Because if it does, it's trivial for your esbuild plugin to cache the transform. You essentially just [memoize](https://chialunwu.medium.com/wtf-is-memoization-a2979594fb2a) the transform function. That would look something like this:

```js
let examplePlugin = {
  name: 'example',
  setup(build) {
    let fs = require('fs')
    let cache = new Map;

    build.onLoad({ filter: /\.example$/ }, async (args) => {
      let input = await fs.promises.readFile(args.path, 'utf8');
      let value = cache.get(args.path);

      if (!value || value.input !== input) {
        let contents = yourExpensiveTransformFunction(input);
        value = { input, output: { contents } };
        cache.set(args.path, value);
      }

      return value.output;
    })
  }
}
```

This only works if `yourExpensiveTransformFunction` is a pure function (the output only depends on the input) and all of the input is captured in the cache key. If the library you are using does not transform each file independently (e.g. it bundles imports itself) then this approach is incorrect and caching it correctly is more complicated.

**Comment by buronnie** [comment]
Thanks folks for your advice! The sass builder is a pure function so the plugin cache works perfectly in my use-case 👍 .

**Comment by evanw** [comment]
More detailed document about how to do this is now available here: https://esbuild.github.io/plugins/#caching-your-plugin.
