### ISSUE TITLE
Variables storing a curried function don't get DCE when unused

### ISSUE THREAD

**Issue by whaaaley** [evanw/esbuild#691]
```js
const foo = a => b => {
  return [a, b]
}

const bar = foo('bar')
const baz = foo('baz') // should be dce

console.log(
  bar('hello')
)
```

Using the pure annotation is a work around, but it's quite annoying to use and other bundlers including Rollup DCE this just fine.

**Comment by evanw** [comment]
This level of side-effect inference is not something esbuild is designed to do. The general rule is that if code evaluates something, it will be retained. With esbuild, an expression is determined to have side effects or not by just looking at the expression instead of by analyzing all dependencies, which allows this side effect determination to happen in parallel. That way the side effect determinations can be evaluated independently per file instead of having to do a large serial analysis across the whole bundle. It's not impossible to add this to esbuild of course, but it would come at a large increase in complexity and would cause a substantial performance hit as it would serialize a part of the bundler that is currently parallel. So I consider doing these types of optimizations to be out of esbuild's current scope. If you would like to write code like this, you may want to use another bundler.

**Comment by whaaaley** [comment]
Gotcha. I totally understand. It makes sense that it works this way.

Would it be possible to have an annotation in the function declaration rather than before the function call? I don't mind adding _some_ annotations but the real pain of this is that the pure annotation has to be added every time the curried function is stored. I suppose it would still require some type of tracking.

This wouldn't be so bad.
```js
const foo = /* @__PURE__ */ a => b => {
  return [a, b]
}

const bar = foo('bar')
const baz = foo('baz') // should be dce

console.log(
  bar('hello')
)
```

Anyway, just throwing some noodles at the wall. I'll have to make do with the annotations for now because I like the simplicity of esbuild over other bundlers. Thanks for taking the time to reply!
