### ISSUE TITLE
How can I apply it to my development? In webpack, I can use webpack-dev-server. Do I need to install webpack before using esbuild?

### ISSUE THREAD

**Issue by SiroSong** [evanw/esbuild#692]
As the title...

**Comment by zaydek** [comment]
I’ll try my best to help answer this question.

You can use esbuild w/ webpack but you don’t have to. It depends on what you expect. If you are a React developer, etc., then you may want to use esbuild with webpack like you described. In that case, try looking around: https://github.com/search?q=esbuild+webpack. I tried this one before: https://github.com/privatenumber/esbuild-loader.

Other repos may be able to help you better than this one, since this one is more focused on core development. You probably want to follow this repo https://github.com/esbuild/community-plugins in general. I didn’t see any there but probably a good place to check from time to time.

I hope that answers your question. 🙂 If it does, feel free to close this issue.

**Comment by heyheyhello** [comment]
If you're used to a dev server here's a mini one?  https://github.com/evanw/esbuild/issues/621#issuecomment-761952726

**Comment by SiroSong** [comment]
> If you're used to a dev server here's a mini one? [#621 (comment)](https://github.com/evanw/esbuild/issues/621#issuecomment-761952726)

Oh, yes, my fault, I should read more API documentation.
