### ISSUE TITLE
React Example 

### ISSUE THREAD

**Issue by rizkyramadhan** [evanw/esbuild#7]
We need an easy to follow example. 
I would suggest a Create-React-App project built using esbuild as an example, this will onboard most of us to esbuild.

**Comment by immanuelfodor** [comment]
This. When I saw that incredible benchmark in the readme, I just said, wow, we seriously need it for React build. If you make an example app happen, I think we'll consider migrating to your hobby project as a company 😃

**Comment by arangates** [comment]
Please go-create-react-app . It might sound like an order but its humble request.

**Comment by evanw** [comment]
I've never used create-react-app before but from what I understand, it's basically a customized webpack config. It's not possible to use esbuild to replace a webpack config generated with create-react-app because it includes a lot of things that esbuild doesn't implement. For example, it appears to support processing CSS in .css/sass/scss files as well as inlining .bmp/gif/jpg/png files as base64 URLs. It also seems to enable JSX syntax in .js files while esbuild requires you to use the .jsx extension.

I'm not trying to have esbuild replace webpack. If you need the complexity of create-react-app/webpack, then you're not going to be able to use esbuild. I'm only intending for esbuild to be appropriate for a certain sweet spot of use cases. Currently this is just bundling JavaScript/JSX files that use CommonJS/ES6 modules. In the future, it will hopefully also include bundling TypeScript files and maybe CSS files. If I get to implementing all of that, it may be possible to manually port an app that uses create-react-app to esbuild, but it may take significant effort depending on how many custom webpack features it uses.

**Comment by immanuelfodor** [comment]
If you would try to replace webpack, and you succeed to "reimplement" it in Go, you'd get famous, go to conferences, etc. This is a real opportunity here, you're one step ahead of everybody, and it fills a need in the market. But fair enough, it's your project, it seems you have clear vision about what you want to do with it. I just don't get if you have the talent to accomplish this already, why not make it something truly earthshaking. No matter what, I wish you all the luck you can master, great job what you did here, the most amazing build optimization I've seen in some time!

**Comment by arangates** [comment]
@immanuelfodor maybe Google must do that

**Comment by immanuelfodor** [comment]
Sooner or later somebody will definitely implement it. 100x increase in build time is well worth the effort. There was another issue for Svelte use case (#8), so I feel even two forks of this repo could coexist: an `esbuild-react` and an `esbuild-svelte` variant.

**Comment by chowey** [comment]
You guys might be missing the point. Webpack has 10,472 commits and 585 contributors over the past 7 years. Re-writing that in Go from the ground up is not trivial.

The same goes for any JS build tool. You would have to re-write it in Go from the ground up.

I'm already impressed that @evanw is planning Typescript support.

Now, something like transpiling JSX is much simpler. The React guys [explain it well](https://reactjs.org/docs/react-without-jsx.html). JSX converts directly to function calls in a straightforward way.

I think a React example is a good idea. It doesn't have to be Create-React-App. It can just showcase how to run `esbuild` with JSX.

**Comment by immanuelfodor** [comment]
Sounds good, thumbs up for showing us the way! :)

**Comment by evanw** [comment]
Just using React with esbuild should be pretty simple:

* Make sure all JSX syntax is put in .jsx files instead of .js files because esbuild uses the file extension to determine what syntax to parse.

* If you're using TypeScript, run `tsc` first to convert .tsx files into either .jsx or .js files.

* If you're using esbuild to bundling React yourself instead of including it with a `<script>` tag in your HTML, you'll need to pass `'--define:process.env.NODE_ENV="development"'` or `'--define:process.env.NODE_ENV="production"'` to esbuild on the command line (see #12 for details).

If you're using Preact instead of React, you'll also need to pass `--jsx-factory=preact.h --jsx-fragment=preact.Fragment` to esbuild on the command line.

**Comment by evanw** [comment]
For example, if you have a file called `example.jsx` with the following contents:

```js
import * as React from 'react'
import * as ReactDOM from 'react-dom'

ReactDOM.render(
  <h1>Hello, world!</h1>,
  document.getElementById('root')
);
```

Use this for a development build:

```
esbuild example.jsx --bundle '--define:process.env.NODE_ENV="development"' --outfile=out.js
```

Use this for a production build:

```
esbuild example.jsx --bundle '--define:process.env.NODE_ENV="production"' --minify --outfile=out.js
```

**Comment by Frikki** [comment]
How do you go about defining `process.env.NODE_ENV` in a JavaScript build script?

```js
require('esbuild').build({
  entryPoints: ['app.jsx'],
  bundle: true,
  define: {
    ???
  },
  outfile: 'out.js',
}).catch(() => process.exit(1))
```

**Comment by rw3iss** [comment]
FYI, for anyone else wanting to replace webpack for a faster building, you don't really have to. Just use the esbuild-loader package, and it will work. The livereload isn't any faster, but it will still build the JS/TS faster, ie:

           {
                test: /\.(j|t)sx?$/,
                include: [PATHS.src], 
                exclude: [PATHS.modules],
                use: [
                    {
                        loader: 'esbuild-loader',
                        options: {
                            loader: 'tsx', // Or 'ts' if you don't need tsx
                            target: 'esnext'
                        }
                    }
                ]
            },

**Comment by IlmariKu** [comment]
I'm creating a ESbuild-version of `nano-react-app` to this repository

https://github.com/IlmariKu/esbuild-react-app

**Comment by zaydek** [comment]
I’m also messing around with a kind of CRA using esbuild: https://github.com/zaydek/react-ssg. I’m also experimenting with SSG so it’s sort of a CSR / SSG hybrid (SSG for prerendered pages, CRA for everything else).

**Comment by josteph** [comment]
Following @rw3iss suggestion, I was able to make CRA based project run blazing fast with esbuild 👍.
So far there is no problem yet, I will update this comment if I found something.

**Comment by zaydek** [comment]
@josteph Can you share which repo?

**Comment by bard** [comment]
@josteph did you eject or did you use something like craco?

**Comment by josteph** [comment]
@zaydek @bard I had to eject the app due to other circumstances. I only replaced the js loader & terser to esbuild loader though.

**Comment by cliffordfajardo** [comment]
I wanted to share with folks that you may not likely need to eject from `create-react-app` to use features like ESbuild.
I highly recommend folks checkout
- [react-app-rewired](https://github.com/timarney/react-app-rewired#extended-configuration-options) (what im using) OR 
[craco](https://github.com/gsoft-inc/craco)

I was working on a codebase for a few months and its been a PITA maintaining a custom build setup. I like receiving free bug fixes & performance improvements from the upstream `create-react-app` team  and the open source community 💙

**Comment by tangdw** [comment]
> I wanted to share with folks that you may not likely need to eject from to use features like ESbuild.
> I highly recommend folks checkout`create-react-app`
> 
> * [react-app-rewired](https://github.com/timarney/react-app-rewired#extended-configuration-options) (what im using) OR
>   [craco](https://github.com/gsoft-inc/craco)
> 
> I was working on a codebase for a few months and its been a PITA maintaining a custom build setup. I like receiving free bug fixes & performance improvements from the upstream team and the open source community 💙`create-react-app`

https://github.com/pradel/create-react-app-esbuild
