### ISSUE TITLE
Option to build the N-API native extension locally

### ISSUE THREAD

**Issue by ryanprior** [evanw/esbuild#714]
Hi there! I've been maintaining the Guix package for esbuild. For purposes of security, portability and reproducibility we like to remove pre-built binary bits from package sources and replace them with something we can build from source using our own infrastructure.

What do you think about providing an option (or instructions would be fine) to build the N-API native extension locally?

**Comment by evanw** [comment]
Well for reproducibility ideally a good state to be in would be where all bits can be reproducible on all platforms. Unfortunately it doesn't look like that's currently the case. It'd be great to get there though.

If I were you I'd be much more worried about the WebAssembly binary since the N-API stubs are super tiny while the WebAssembly module is huge. Go's WebAssembly interface has a general-purpose API that should be able to access all node APIs including network methods. I just tried building the WebAssembly module on macOS and Linux, both with Go 1.15.5 (the Go version I'm using for releases), but the files are unfortunately different. Any tips for getting these to be the same would be appreciated. I'm not an expert with binary reproducibility.

Anyway the instructions for building the N-API native extensions locally are [here](https://github.com/evanw/esbuild/blob/4417f2f80d3cf031b2968752d6e5baf9c6a7e0ec/Makefile#L70-L88). They aren't super robust because I wasn't intending for them to be rebuilt automatically so these instructions are more just for documentation. Each one was run on that platform (so there was no cross-compilation).

I have experimented with [cross-assembling small executable stubs before](https://github.com/evanw/clink) and I briefly tried using that same technique here, but I couldn't immediately figure out how to get nasm to build dynamic libraries (I didn't try too hard) and I also wasn't confident that the dynamic libraries I produced would be as portable. For example, I think I remember that you're supposed to invoke syscalls via `libSystem.dylib` instead of directly on macOS for compatibility with future macOS versions. So I just went with the simpler approach of manually building them on each platform and checking them in for now. But I'd love to get them building from source in a cross-platform way if there's an easy way to do that without heavy dependencies.

Also an alternative for you could be to just omit these N-API extensions. The resulting build will be slower but it should still work. I'm not sure how you're building esbuild but if you just delete the `.node` files before the build script is run, the [directory scan in the build script](https://github.com/evanw/esbuild/blob/4417f2f80d3cf031b2968752d6e5baf9c6a7e0ec/scripts/esbuild.js#L155-L172) that includes these files will just not include them. This is probably the easiest way to solve your problem.

**Comment by ryanprior** [comment]
I'm interested in building the webassembly binary from source as well. I'm fairly new to wasm, whether via golang or otherwise, so I'm looking for examples of how that's typically done. I'll give this all another read later, thank you for providing the links and pointers!

**Comment by evanw** [comment]
The WebAssembly build happens [here](https://github.com/evanw/esbuild/blob/4417f2f80d3cf031b2968752d6e5baf9c6a7e0ec/scripts/esbuild.js#L42). Most of the complexity is building the various forms of the JavaScript companion code. The actual build command for the WebAssembly is just `GOOS=js GOARCH=wasm go build -o esbuild.wasm ./cmd/esbuild`.

**Comment by Siilwyn** [comment]
:wave: chiming in, hope this fits into this issue, not 100% sure.

I was surprised to find esbuild not working when installing my dependencies with npm and `--ignore-scripts`. Assuming new packages would be pre-building and bundling binaries like described in [this NearForm article](https://www.nearform.com/blog/the-future-of-native-modules-in-node-js/). So I'm curious why instead the binary is fetched during installation.

**Comment by evanw** [comment]
This issue has nothing to do with install scripts, so your question is not related to this issue.

That article you linked says this:

> instead of downloading a prebuild for your platform at installation time, we simply bundle all prebuilds for all platforms inside a ./prebuilds folder in the `node_modules` before it is published to npm.

I am using an install script to download the correct executable instead of sticking all of the executables for all supported platforms into a single package to make the downloaded size smaller. Each executable for a specific platform is ~6-7mb but all of them together is ~82mb (esbuild supports many different platforms). So I'm not going to do this because I don't want each installed copy of esbuild to take up 82mb of disk space.

You probably want to follow issue #789 instead, which is about trying to use npm's `optionalDependencies` feature instead of the install script.

**Comment by Siilwyn** [comment]
Alright thanks for your detailed helpful response! I'll keep an eye on #789.

**Comment by evanw** [comment]
One piece of the reproducible build puzzle was just solved: #1200. Another piece is needing the `-trimpath` flag according to https://github.com/golang/go/issues/16860, which I have also just added. With both of these, builds now appear to be reproducible, at least between my macOS and Linux computers.

**Comment by evanw** [comment]
Another update: I have added automated reproducibility verification for compiled Go and WASM binaries after every release: https://github.com/evanw/esbuild/commit/96c6e35078e12e2a8fea59f19ddb88cc5dbbfeae. This was done back in March but I forgot to update this issue. All major binary artifacts have been reproducible for quite a while (except for these small N-API native extensions, which is why this issue is still open).

**Comment by evanw** [comment]
I just discovered that node has finally fixed their bug: https://github.com/nodejs/node/issues/36616#issuecomment-1338272684. So it's not a problem anymore in node v18.3.0+. I think this means I can finally delete these N-API extensions, and then consider this issue to be fixed.

**Comment by ryanprior** [comment]
Let's go! Fully bootstrapped esbuild in sight.
