### ISSUE TITLE
Warn about ambiguous re-exports in entry points

### ISSUE THREAD

**Issue by threepointone** [evanw/esbuild#716]
I think I found a bug with the way esbuild handles matching exports in a bundle. Consider:

`a.js`
```js
export const x = 123
```
`b.js`
```js
export const x = 456
```
`ab.js`
```js
export * from './a'
export * from './b'
```

Running esbuild like so: `esbuild ab.js --bundle` generates: 
```js
(() => {
})();
```

This should probably be an error?

---
 Let's say we added another file, `script.js`
```js
import {x} from './ab'.
```
Then running esbuild like so: `esbuild script.js --bundle` generates:
```
> src/script.js: error: Ambiguous import "x" has multiple matching exports
    1 │ import { x } from "./ab";
      ╵          ^

1 error
``` 
This seems correct, so it should probably be an error in the previous case too?

**Comment by evanw** [comment]
The reason why this happens is that esbuild tries to match node's semantics. Both esbuild and node let you bundle/evaluate `ab.js` without an error. It _is_ an error if you then import `x` from another file, since then the ambiguous export is actually used. That is why both esbuild and node don't let you bundle/evaluate `script.js`. So esbuild is just being consistent with node in both cases.

Can you say more about your use case? What's the real-world situation where you encountered this problem?

**Comment by threepointone** [comment]
I do not have a real world situation for this, I was only experimenting with esbuild. You're right, even browsers don't throw an error until an import is actually imported out of it and used. Rollup does a warning, but doesn't error, then oddly chooses a.js (123! That seems bad.). 

Could esbuild have a warning in this case of clashing exports? It feels like my compiler should complain when I try this.

**Comment by evanw** [comment]
I'm going to close this since this is valid well-defined behavior and it doesn't seem appropriate to warn about this, especially since the warning would be inconvenient for people that have valid use cases for this behavior.
