### ISSUE TITLE
TypeScript async function parse bug

### ISSUE THREAD

**Issue by koenbok** [evanw/esbuild#72]
The following valid TypeScript code:

```.ts
export class Test {
  f = async <T>(a: T) => {
    return a;
  };
}
```

Will error with:

```
index.ts:10:17: error: Expected ")" but found ":"
  f = async <T>(a: T) => {
```

**Comment by koenbok** [comment]
Regular function syntax works fine:

```.ts
export class Test {
  async f<T>(a: T) {
    return a;
  };
}
```

**Comment by evanw** [comment]
Whoops! I didn't think to test this, and I haven't run across any code that does this yet. Thanks so much for reporting it.

For backwards compatibility, you're allowed to call a function `async` in TypeScript:

```ts
function async<T>() {}
async<number>();
```

This bug happens because my parsing is trying to parse this as the function call `async<T>(a)` instead of the arrow expression `async<T>(a) => { return a; }`. Just pushed a fix.
