### ISSUE TITLE
Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by darioielardi** [evanw/esbuild#73]
Installing and importing [react-dates](https://github.com/airbnb/react-dates) results in this error:
```
Uncaught ReferenceError: global is not defined
```
since react-dates has some dependencies that use `global`, assuming the bundler will replace it with `window` when the compile target is the browser.

**Comment by evanw** [comment]
You should now be able to do `--define:global=window` on the command line. Does that work for you?

**Comment by darioielardi** [comment]
Works perfectly, thank you.

**Comment by datpt11** [comment]
> Works perfectly, thank you.

I am also having similar case in vite js. Can you help me?

**Comment by ballonura** [comment]
What about using an script as configurations? `esbuild.js`?
Iv'e try:
```
const define = {
  global: 'window',
};
```

**Comment by Dalepalmer** [comment]
@ballonura 
This works for me

```
esbuild.build({
...other config,
  define: {
    "global": 'window',
  }
})
```

**Comment by augustosamame** [comment]
> --define:global=window

This solved it in my Rails 7 project. Since Rails does not provide an esbuild.config.js file, you can append it to the build script in package.json:

```
"scripts": {
    "build": "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds --public-path=/assets --define:global=window",
```

worked like a charm

**Comment by aamiriqubal** [comment]
Please use 'esbuild-plugin-polyfill-node' plugin.
https://npm.io/package/esbuild-plugin-polyfill-node
This solved the problem for me, and NO NEED of manually adding and assigning `global = window` in script tag.

**Comment by Arlen22** [comment]
@evanw I know this is a closed issue, but why is this not done automatically with `platform: 'browser'`? I've run into this when trying to use the es-shims repo.

**Comment by evanw** [comment]
That's a good question. I'm not sure I remember exactly why I did this since it's been a while. Thinking about it now, I've seen people try to use `typeof global === 'undefined'` to detect when something is running in the browser. Something like this:

```js
let node =
  typeof global === 'undefined'
    ? require('crypto-browserify')
    : require('crypto')
```

So auto-defining `global` to `window` could subtly break things, and so it isn't always the right thing to do automatically. I'm not saying it's a good reason, but it is a reason.

It could be that it's arguably better to do it automatically if it's the right thing to do in the vast majority of cases and there's an easy way to opt out. That's especially true if other widely-used tools in the space already do this, since then esbuild would be the one that is different.

But if changing this would cause esbuild to be different than other widely-used tools, then it might cause more pain than it's worth as libraries written to work in other tools would no longer work with esbuild. I'm not sure what the state of the ecosystem is on this at the moment.

**Comment by ljharb** [comment]
`typeof global` indeed shouldn't be transpiled, but `global` in general should - that's how it's always worked in the ecosystem, prior to this new wave of bundlers trying to break the "implicit node polyfill" use case.
