### ISSUE TITLE
BigInt polyfill for ES2018

### ISSUE THREAD

**Issue by hazae41** [evanw/esbuild#732]
When compiling ipfs with es2018 target on https://esm.sh, I get the following error

https://esm.sh/ipfs?target=es2018&dev

```
/* esm.sh - error */
throw new Error("[esm.sh] " + "esbuild: Big integer literals are not available in the configured target environment");
export default null;
```

Maybe we could polyfill BigIntegers for ES2018?

**Comment by evanw** [comment]
BigInts are not lowered to older syntax in esbuild because there is no direct translation. The BigInt specification decided to use normal JavaScript operators for BigInts and the JavaScript language does not have user-pluggable operator overloading. Code wanting to use BigInts on older browsers will have to be rewritten to use a library that uses function calls instead of native JavaScript operators. That way the function calls can be substituted with older functionality using a polyfill. Here is a quote from https://github.com/GoogleChromeLabs/jsbi:

> To use BigInts in your code today, you need a library. But there’s a difficulty: the BigInt proposal changes the behavior of operators (like `+`, `>=`, etc.) to work on BigInts. These changes are impossible to polyfill directly; and they are also making it infeasible (in most cases) to transpile BigInt code to fallback code using Babel or similar tools. The reason is that such a transpilation would have to replace every single operator in the program with a call to some function that performs type checks on its inputs, which would incur an unacceptable performance penalty.
>
> The solution is to do it the other way round: write code using a library’s syntax, and [transpile it to native BigInt code](https://github.com/GoogleChromeLabs/babel-plugin-transform-jsbi-to-bigint) when available. JSBI is designed for exactly this purpose: it provides a BigInt “polyfill” implementation that behaves exactly like the upcoming native BigInts, but with a syntax that you can ship on all browsers, today.

I haven't tried the [JSBI](https://github.com/GoogleChromeLabs/jsbi) library myself but the approach sounds solid from their description. And I'm not familiar with IPFS's JavaScript tooling. Do they already have a transpilation strategy for BigInts? Maybe it's worth asking them?

**Comment by evanw** [comment]
I'm going to close this since this is not something I plan on supporting in esbuild itself, for reasons stated above.
