### ISSUE TITLE
Invalid OnResolveArgs.Importer for stdin in >= 0.8.21

### ISSUE THREAD

**Issue by bep** [evanw/esbuild#736]
Before `0.8.21` we got the value `stdin` which is a constant I know how to handle.

After `0.8.21` we get what looks like an absolute filename, but it points to a file that does not exist -- but most importantly I don't know the origin of it to resolve imports relative to it.

https://github.com/gohugoio/hugo/issues/8189

**Comment by evanw** [comment]
I've got some tests that cover various cases with stdin here:

https://github.com/evanw/esbuild/blob/ad97902d6602eb63857ac4c41cb2237d8788f1dc/scripts/plugin-tests.js#L746-L880

There you can see what various combinations of `Stdin` options and the resulting `Importer` are. It looks like if you pass both a `ResolveDir` and a `Sourcefile`, the importer will now be the `Sourcefile` path resolved relative to the `ResolveDir`. The behavior is somewhat arbitrary but I probably did it that way so that it's consistent with how the importer for other files behave. Sorry about the breakage–I don't think I had test coverage for these cases before that change.

It looks like you should be able to get `<stdin>` back by not passing the `Sourcefile` option to `Stdin`. I think that should fix your use case unless you needed the `Sourcefile` for something. Alternatively, you can also avoid using `Stdin` altogether and just provide the contents of the entry point file with a plugin. An example of doing that is here: https://github.com/evanw/esbuild/issues/720#issuecomment-768928333.

Unrelated: While I have your attention, I believe there's also a bug with Hugo's use of esbuild's API that causes Hugo to crash with a null pointer error. Details are [here](https://github.com/gohugoio/hugo/issues/8040#issuecomment-753582279). It seems like an easy fix.

**Comment by bep** [comment]
Thanks; I will have a look at it. The nilpointer is fixed (I'm pretty sure ...)

**Comment by bep** [comment]
Yes, that works, and I guess the current behaviour makes sense. Closing.
