### ISSUE TITLE
Use esbuildService to build multiple bundles

### ISSUE THREAD

**Issue by buronnie** [evanw/esbuild#741]
I am trying to make multiple bundles per dependency, so instead of one big bundled asset, I am expecting to have one bundle for each dependent library.

In the main process, I start the build process:
```
buildPromises.push(esBuildService.build(options))
```
Then in `onResolve` hook, whenever there is external dep to import, we will start a new build (same as above).

The problem is that the main process does not know when all `import` statements are analyzed so i have to set a timeout before i call `const modules = await Promise.all(buildPromises);` to make sure `buildPromises` include all sub-build i made in `onResolve`. The manually set timeout won't fly since the value varies a lot depending on the number of files we need to process. I am wondering if there is a good mechanism to avoid the timeout. Thanks!

**Comment by evanw** [comment]
It sounds to me like you should be using another concurrency primitive instead of `Promise.all`. You want to wait until all build calls have completed, but build calls may spawn other build calls. Something like a queue or a counter might be more appropriate.

I took a few seconds to write some random code that might be a good head start (not tested):

```js
await new Promise(resolve => {
  function done() {
    if (--counter === 0) resolve()
  }
  function startAnotherBuild(...) {
    ++counter
    esbuild.build({
      ...
      if (someCondition) startAnotherBuild(...)
      ...
    }).then(done, done)
  }
  let counter = 0
  startAnotherBuild(...)
})
```

This problem is more of a general JavaScript programming question and doesn't have to do with esbuild specifically, so I'm going to close this issue. There are many asynchronous programming libraries and tutorials available that you may find helpful.
