### ISSUE TITLE
Loader dataurl can't load some patterns

### ISSUE THREAD

**Issue by benjaminbours** [evanw/esbuild#743]
Hi, I'm evaluating your tool for a company, and we are using this javascript library => https://blueprintjs.com.

In our CSS, we import some style sheets from them:

```css
@import '@blueprintjs/core/lib/css/blueprint.css';
@import '@blueprintjs/icons/lib/css/blueprint-icons.css';
@import '@blueprintjs/datetime/lib/css/blueprint-datetime.css';
```
And in their style sheets, they import some file with this syntax:

```css
@font-face{
  font-family:"Icons20";
  font-style:normal;
  font-weight:normal;
  src:url("../../resources/icons/icons-20.eot?#iefix")
```

That leads to compilation error:
![2021-02-03_09-02](https://user-images.githubusercontent.com/8804297/106716283-8c026d80-65fe-11eb-89b9-130f83def989.png)

Remove the part `?#iefix` after the `.eot` solve the issue. Is that an unsupported use case or am I not using the right loader? I did try with the file one and not much luck.

**Comment by evanw** [comment]
I assume the problem is that there is no path with the `.eot?#iefix` extension on the file system. You should be able to solve this with an on-load plugin that remaps the path from your path format to the underlying file system path so esbuild knows which file to load: https://esbuild.github.io/plugins/#resolve-callbacks.

**Comment by benjaminbours** [comment]
Indeed, it solves it, thanks for the help, and for this great tool :)

**Comment by nsainaney** [comment]
@benjaminbours I have the same issue. Can you please post your solution? Thanks!
