### ISSUE TITLE
esbuild.exe was reported as Trojan in windows 

### ISSUE THREAD

**Issue by ycjcl868** [evanw/esbuild#763]
![image](https://user-images.githubusercontent.com/13595509/107140934-62856280-68da-11eb-8f41-c77c09a3fab3.png)

**Comment by evanw** [comment]
Sorry, this is something you are going to have to resolve yourself. This is not esbuild's fault and there's nothing I can do about this myself. Windows antivirus programs are well-known for causing trouble like this with legitimate software like esbuild. Potential workarounds include a) reporting this as a false positive to your antivirus vendor, b) adding an exception rule for esbuild to your antivirus application if possible, and/or c) using the [WebAssembly package](https://www.npmjs.com/package/esbuild-wasm) instead of the [native package](https://www.npmjs.com/package/esbuild) to bypass the antivirus filter.
