### ISSUE TITLE
BigInt not support Math.pow. 

### ISSUE THREAD

**Issue by underfin** [evanw/esbuild#764]
## Input
```
 BigInt(2) ** BigInt(32) - BigInt(1);
```
## Output
```
__pow(BigInt(2), BigInt(32)) - BigInt(1)
```

## Description 

The code will not worked. The broswer will throw  error with `bundle.js:formatted:512 Uncaught TypeError: Cannot convert a BigInt value to a number`.

**Comment by evanw** [comment]
This is deliberately not supported. That's why esbuild's [documentation about JavaScript language features](https://esbuild.github.io/content-types/#javascript) says this:

> BigInt ... Unsupported when `--target` is below `es2020`

The presence of `__pow` means you have set `--target` to `es2016` or lower, which is below `es2020`. This configuration is unsupported because emulating BigInt in JavaScript environments that don't support it natively is a very invasive and expensive transformation. If you need to support those environments, it's better to rewrite your code to use a BigInt emulation library instead. More information is here: https://github.com/evanw/esbuild/issues/732#issuecomment-770519567.
