### ISSUE TITLE
[Bug] Service API + incremental indefinitely freezes

### ISSUE THREAD

**Issue by zaydek** [evanw/esbuild#777]
Hi Evan. I  wanted to use a long-lived esbuild process that incrementally recompiles _different_ source files and I noticed that once I ticked `incremental` to true, esbuild freezes. I made a minimal repro here: https://github.com/zaydek/esbuild-incremental-service-bug and attached a video to help explain (no audio). This is on `0.8.43`. The invocation command is `node esbuild.js`.

Quick related question: If you want to use incremental recompilation for _different_ source files, so build options for `entryPoints` and `outfile` change on every pass, is this the right approach? Using `startService` and `build` together, or am I using the wrong feature?

https://user-images.githubusercontent.com/58870766/107356252-e8402280-6b13-11eb-93e1-cc71fe48dc5d.mov

**Comment by zaydek** [comment]
I’m going to try and answer my related question. I noticed in the docs:

> You may want to use this API if your use case involves calling esbuild's build API repeatedly with the same options
> https://esbuild.github.io/api/#incremental

It sounds like maybe I can’t use an esbuild service + incremental in this way since I’m passing _different options_. Maybe this is the reason esbuild freezes, because this is undefined behavior?

**Comment by evanw** [comment]
What do you mean by "freeze"? Do you mean the process isn't exiting? Incremental builds should keep the process open until you call `result.rebuild.dispose()` since incremental builds mean you can call `result.rebuild()` in the future as many times as you want. The actual build information is inside the external esbuild process so it's not automatically cleaned up when `result.rebuild` is garbage collected by node. You must free it explicitly.

**Comment by zaydek** [comment]
Thank you for the fast response.

> Do you mean the process isn't exiting?

Yes. It sounds like I overlooked how incremental builds work. It sounds like this isn’t a bug at all, I just didn’t understand that incremental builds need to be disposed.

Will close this. Thank you.
