### ISSUE TITLE
[Discussion] Is the plugins option available only for build option ?

### ISSUE THREAD

**Issue by siva-sundar** [evanw/esbuild#779]
I am relatively new to esbuild. Trying to bundle a Ember project. Using it to transform the js files.

Is the plugins option available only for `build` option ?

https://esbuild.github.io/plugins/#using-plugins

**Comment by evanw** [comment]
Yes, that's correct.

**Comment by siva-sundar** [comment]
Thanks for the response. Any plans to bring it for transform/transformSync api ?

From my understanding, shouldn't it be for both the hooks? Correct me if I am wrong.

**Comment by evanw** [comment]
No, I have no plans to do that at the moment. Plugins determine where the bundler looks for import paths and what the contents of imported files look like, which are more relevant to the build API.

Would you mind describing more about your use case? It's hard to understand what you're trying to do.

**Comment by siva-sundar** [comment]
Ember has its own cli tool called [ember-cli](https://github.com/ember-cli/ember-cli/) which uses [broccoli](https://github.com/broccolijs?type=source) for bundling.

It uses [ember-cli-babel](https://github.com/babel/ember-cli-babel) for transpiling(using babel) with presets and some custom plugins. I am trying to replace babel with esbuild for transpiling.

I am looking for custom plugins support for transform api in esbuild.

**Comment by evanw** [comment]
I'm guessing there probably isn't a way to get esbuild to do what you want. The transformation pipeline inside esbuild is deliberately not designed to be extensible the way Babel is. There is no way to access the AST directly in esbuild.

It is possible to use Babel plugins with esbuild. However, the only extensibility point exposed by esbuild's plugin API where you can alter the code is an [on-load callback](https://esbuild.github.io/plugins/#load-callbacks) which must return a string. So the only way to do this is to have your esbuild plugin run Babel on your JavaScript first, convert Babel's AST to a string of JavaScript code, and then return that string to esbuild for further processing. This is slower than just running Babel because you are now running both Babel and esbuild.

The reason why you can't use on-load plugins with the transform API is that it's pointless. The transform API takes the code as a string so if you want to transform the string before esbuild processes it, you can just transform the string yourself first before giving it to esbuild. You don't need the plugin API for that.

**Comment by siva-sundar** [comment]
Thanks of detailed response. Closing this issue.
