### ISSUE TITLE
add the outfile path on onResolveArgs

### ISSUE THREAD

**Issue by dixdiydiz** [evanw/esbuild#794]
i want to return the path property according to the output file path,  i need to know the output path of  importer.
like this:
export interface OnResolveArgs {
  path: string;
  importer: string;
  namespace: string;
  resolveDir: string;
  pluginData: any;
  outputfile: string; // output file path
}

**Comment by evanw** [comment]
That’s not really possible if I understand you correctly. Most files in a bundle do not have a corresponding output path. Bundling takes many files as input and produces one file as output. In addition, an upcoming change to add a content hash to the file name of output files will mean that potentially none of the output file names can be determined at this stage since that would require hashing the generated content of the output file, which doesn’t exist yet (and which depends on running this plugin).

**Comment by dixdiydiz** [comment]
Thanks for your answer.
