### ISSUE TITLE
Compile times get progressively worse in watch mode

### ISSUE THREAD

**Issue by marvinhagemeister** [evanw/esbuild#801]
We just dropped our own chokidar watch setup in favor of esbuild's native watch features and noticed that compile times progressively get worse with each file change.

| Machine | 1st change | 2nd change | 3rd change | 4th change | 5th change | 6. change | 
|---|---|---|---|---|---|---|
| Macbook Air M1 | 665ms | 763ms | 914ms | 914ms | 5s | 1min 9s |
| Dell XPS 13 9380 | 2s | 2s | 23s | 56s | - | - |

During that time all cores on the CPU are running at 100% (screenshot of Macbook Air).

<img width="1679" alt="Screenshot 2021-02-13 at 09 55 41" src="https://user-images.githubusercontent.com/1062408/107846129-a4823d00-6de1-11eb-998d-f1b284b407ae.png">

The issue is reproducable in `0.8.42`, `0.8.43` and `0.8.44`.

Steps to reproduce:

1. Clone this repo `git clone git@github.com:preactjs/preact.git`
2. Go into the cloned directory: `cd preact`
3. Checkout branch: `git checkout esbuild-watch-bug`
4. Run `npm install`
5. Run `npm run test:karma:watch` (fires up our test runner)
6. Open `memo.js` and update the string in the console.log on line 16 with each file save.

The issue occurs with any other file too, for as long the content changes with save.

Haven't had the time yet to create a more isolated reproduction case. Will try to make some time for that later today.

**Comment by evanw** [comment]
> 3. Checkout branch: `git checkout esbuild-watch-bug`

I can't do this part. Does the branch need to be pushed?

**Comment by marvinhagemeister** [comment]
> > 1. Checkout branch: `git checkout esbuild-watch-bug`
> 
> I can't do this part. Does the branch need to be pushed?

I feel stupid, I really forgot to push it :S It's up now.

**Comment by evanw** [comment]
It looks like each time your test setup detects a change it preprocesses around a hundred files and for each file it starts a new instance of esbuild's watch mode. These instances are never stopped so you quickly end up with 1000s of instances of esbuild's watch mode all scanning for changes and rebuilding simultaneously. This will quickly eat your computer alive :)

Here's the documentation about watch mode: https://esbuild.github.io/api/#watch. You are supposed to call `stop()` on the result when you're done, which doesn't appear to be happening in this code:

```js
require('esbuild').build({
  entryPoints: ['app.js'],
  outfile: 'out.js',
  bundle: true,
  watch: true,
}).then(result => {
  // Call "stop" on the result when you're done
  result.stop()
})
```

I don't really understand your setup well enough to know if it's a problem that can be fixed by using esbuild's watch mode more effectively, or if it's just something that esbuild's watch mode isn't designed for. I didn't have the use case of a hundred of watch modes running simultaneously in mind when I designed it, even if the previous hundred are stopped when a change is detected. I was intending for you to only create one of them and use bundling to combine multiple files together.

If you do really need a hundred simultaneous watch modes all going on at the same time, it's probably best to use a different file watching library that gets real file system events from the operating system instead of using the polling approach that esbuild uses.

**Comment by marvinhagemeister** [comment]
Oof, that sounds like pretty bad misusage on my end. The intention was to fire the service up only once and feed it with different entry files to transpile and bundle over time. Thank you so much for taking a look and I apologize for it being something in my code in the end 😅
