### ISSUE TITLE
Best way to handle LESS/SCSS file's dependencies updates in watch mode?

### ISSUE THREAD

**Issue by jsilveira** [evanw/esbuild#808]
As an esbuild fanboy, I have been working to replace my old parcel live development setup with esbuild, by using watch mode and https://github.com/tapio/live-server to mimic a "rudimentary" hot reload behavior. For CSS the project is using LESS, with a .less entry point that includes many other .less files. I'm using an esbuild plugin to successfully parse Less into CSS, but I'm finding a couple of (reasonable) drawbacks and I was wondering if there are better ways to deal with them:

a) When any `.less` file other than the entry point changes, esbuild watch mode misses the change. I suppose this will happen with SCSS and any other plugin where the plugin handles its own file dependencies. I can setup my own file watcher and trigger a manual incremental update, but I was wondering if there's anything better esbuild or the plugin system can do here?

b) LESS parser is kind of slow, and does not take advantage of any of the incremental esbuild magic. Any tips on ways to mitigate this? Any experience with alternative compilers for less or scss with some sort of incremental compilation?

**Comment by evanw** [comment]
> I was wondering if there's anything better esbuild or the plugin system can do here?

I'm planning for plugins to be able to return a list of files to watch. But the API for this doesn't exist yet, sorry. It will be there at some point.

> Any tips on ways to mitigate this? Any experience with alternative compilers for less or scss with some sort of incremental compilation?

I'm not familiar with less but I just took a look. Unfortunately It looks like it isn't designed for having fast incremental builds. Here are some approaches you generally use to speed up this kind of stuff:

* Avoid doing any work at all if none of the files have changed. This involves caching the previous result in memory and reusing it if none of the input files have changed. Doing this correctly is especially tricky for compilers that interact with the file system like less does. I have written up some thoughts about how to do this here: https://esbuild.github.io/plugins/#caching-your-plugin.

    The problem here is that less calls `require.resolve()` directly instead of allowing that to be configured, so I don't think you can easily hook into less and see what file system locations it's checking to know which file locations to use in the cache invalidation check.

* Avoid doing expensive work if you do end up having to build. An easy way of doing this with a compiler is to cache the parsing of the file, but still always run the compiler. So if a given file hasn't changed you can just reuse the previous AST instead of parsing it all over again. This works well in scenarios where you only change one file out of many.

    The problem here is that I think less mutates the AST instead of treating the AST as immutable and doing a shallow clone when the AST needs to be mutated. That means you wouldn't be able to take full advantage of this approach. You could still try using JSON.parse/serialize to clone the AST before loading and saving it in the cache. That still might be faster if the parser is really slow. The other problem is that there doesn't appear to be a good way to hook into the parser like this, although I could be wrong.

* There are many more things that could be done to make less even faster. One example is partially reusing the old AST by scanning forward over the changed file until you reach the first change. All AST nodes before that change can be reused (assuming an immutable AST). Also assuming less has a top-down compilation model, compilation of whole chains of imported files (e.g. propagating variable values) could potentially be cached so editing a root file does not need to re-compile all of the imported files.

    The problem with this is that this would have to be done by the less team itself, since it's a pretty deep change. And I'm guessing this isn't something that is important to them.

Some of this could potentially be hacked around with monkey patching, but you might want to ask the less project maintainers directly about support for incremental builds.

**Comment by jsilveira** [comment]
> I'm planning for plugins to be able to return a list of files to watch. But the API for this doesn't exist yet, sorry. It will be there at some point.

Brilliant, I think it makes a lot of sense in order to prevent each plugin from having to set up it's own fs watcher. Its up to you whether to close this issue or leave it until that feature exists!

> Some of this could potentially be hacked around with monkey patching, but you might want to ask the less project maintainers directly about support for incremental builds.

Lots of good ideas there, I'll see what I can explore with the less project. I'll also check if Sass has the same issues.

> The problem here is that less calls require.resolve() directly instead of allowing that to be configured

Interesting. Just out of curiosity, how to you avoid this in esbuild when parsing js/ts?

Thanks a lot for the quick and thorough response, and also for all the incredible work you are doing with esbuild, it's truly inspiring.

**Comment by evanw** [comment]
> Interesting. Just out of curiosity, how to you avoid this in esbuild when parsing js/ts?

The resolver is written in Go and replicates what require.resolve() does. It uses a custom file system interface that automatically tracks all file system accesses for use with watch mode later. And esbuild also uses immutable ASTs so it can cache parsing across builds.

**Comment by zaydek** [comment]
@jsilveira I’ve implemented caching once in esbuild for the Svelte compiler and it works really well. As you can imagine, the first build will be the slowest, but w/ `incremental: true` in the esbuild options, your rebuilds are almost instant. It’s a memory intense approach so it may not be ideal for long-running tasks because the caching implementation as outlined in the docs has no eviction strategy, but I think most of the time caching gets around the problem that most tooling doesn’t support incremental recompilation.

I’d actually be interested to see some kind of meta plugin that provides caching for any plugin. Probably not something you want to use always since caching is actually slightly slower if you’re not doing rebuilds.

> > I was wondering if there's anything better esbuild or the plugin system can do here?
> 
> I'm planning for plugins to be able to return a list of files to watch. But the API for this doesn't exist yet, sorry. It will be there at some point.

@evanw I’m looking forward to this. I noticed this is one of the cases esbuild doesn’t handle yet. It’s not a dealbreaker but it will help bring feature parity to esbuild (vs. other tooling).

**Comment by zaydek** [comment]
@evanw Hey Evan. I just noticed that manually triggering a rebuild event w/ watch mode + incremental mode enabled does not trigger Sass plugins, for example, to rebuild. I believe this is the same issue @jsilveira mentioned previously.

Other than handling Sass dependencies entirely separately from esbuild, are there currently any APIs / strategies to get esbuild to process `.scss` plugins the same way `.css` imports already work? By that I mean, imported `.css` do rebuild on rebuild events, whereas `.scss` plugins do not.

I’m using a simple handrolled plugins like this:

```js
const scssPlugin = {
  name: "scss",
  setup(build) {
    const path = require("path")
    const sass = require("sass")

    build.onResolve({ filter: /\.scss$/ }, args => ({
      path: args.path,
      namespace: "scss-ns",
    }))

    // NOTE: esbuild does not support sourcemaps for CSS. Tracked by
    // https://github.com/evanw/esbuild/issues/519.
    build.onLoad({ filter: /.*/, namespace: "scss-ns" }, async args => {
      const result = sass.renderSync({ file: path.join("src", args.path) })
      return {
        contents: result.css.toString(),
        loader: "css",
      }
    })
  },
}
```

The fallback I’m thinking of using is to just handle Sass entirely separately from esbuild and to manually fire a server-sent event, but this requires some coordination between ports used, etc.

**Comment by evanw** [comment]
If you are trying to watch a file on the file system you will need to use the `file` namespace for esbuild to watch it. Otherwise the path is considered a virtual path (i.e. not on the file system) and is not watched.

**Comment by zaydek** [comment]
Thank you for the speedy reply! Working on it now.

**Comment by zaydek** [comment]
@evanw OK got it. Makes sense now. Some constructive comments:

For now I am spinning up a second watcher (custom watcher), and will poll myself since virtual files don’t trigger rebuilds. Personally I would love to see virtual path plugins be able to rebuild the same as `file` path plugins. This enables a lot of use-cases I am intent on using, such as rebuilding `.mdx` files, etc. which uses `jsx` for the loader. Example here: https://github.com/zaydek/esbuild-mdx/blob/master/index.js#L25.

It’s not a big deal for `.scss` files or `.mdx` files alone, but if I need to spin up a watcher per extension or for all custom extensions, then I (and anyone else in this situation) will most likely need to a) know which extensions to watch for myself b) roll our own watcher which will almost certainly consume more CPU than your watch implementation. I appreciate how much care you put into your poll implementation.

I think if there was an API, even if it were opt-in, that treated virtual plugins the same as file plugins, that would help a lot. Using the `file` API seems less ergonomic for my use-case, [though I do understand it’s intended use-case](https://github.com/evanw/esbuild/issues/20#issuecomment-802269745). I don’t mind needing to cache my own plugins to make them more performant, I just would rather not have multiple watch implementations is all.

This seems somewhat related to #1014 as well.

**Comment by evanw** [comment]
> > > I was wondering if there's anything better esbuild or the plugin system can do here?
> > 
> > I'm planning for plugins to be able to return a list of files to watch. But the API for this doesn't exist yet, sorry. It will be there at some point.
>
> @evanw I’m looking forward to this. I noticed this is one of the cases esbuild doesn’t handle yet. It’s not a dealbreaker but it will help bring feature parity to esbuild (vs. other tooling).

The latest release now lets plugins return `watchFiles` and `watchDirs` to supply custom file system paths for watching. Documentation is here: https://esbuild.github.io/plugins/#load-results.

**Comment by zaydek** [comment]
Wow. Thanks @evanw! I’ll play with this today and follow-up with notes if I have any. Solid release!

**Comment by jsilveira** [comment]
Awesome news @evanw! It seems to work great. I think I can close this issue now. Thanks
