### ISSUE TITLE
non-*n*x OS exist - please tell folks to use npx, which comes with node =)

### ISSUE THREAD

**Issue by Pomax** [evanw/esbuild#823]
https://esbuild.github.io/getting-started/ says:

>This should have installed esbuild in your local node_modules folder. You can run the esbuild binary to verify that everything is working correctly: `./node_modules/.bin/esbuild --version`

Don't say this. Half the world can't run things this way, so Node added `npx` to the standard offering for a good reason: it works for _everone_. If you can run `npm`, you can run `npx`. So given that everyone has `npx` available, can we change the instructions to this, instead?

>This should have installed esbuild in your local node_modules folder. You can run the esbuild binary to verify that everything is working correctly: `npx esbuild --version`

The same goes for the run example:

> Finally, tell esbuild to bundle the file: `./node_modules/.bin/esbuild app.jsx --bundle --outfile=out.js`

This should really be:

> Finally, tell esbuild to bundle the file: `npx esbuild app.jsx --bundle --outfile=out.js`

No one should be running things from the `node_modules` dir directly in 2021 =)

**Comment by evanw** [comment]
I actually used to recommend `npx` in the docs, but now consider it an anti-pattern. I stopped recommending it for these reasons:

* I realized that it has security problems. It downloads and executes the package with the provided name without prompting so if you make a typo, your computer can be instantly executing malicious code. I know this was changed a few months ago in npm v7 (`npx` now prompts you before installing a package), but many people are still on npm v6. So recommending `npx` at the moment doesn't seem like a good idea to me.

* Not using `npx` is a performance win because `npx` adds extra overhead over just executing the module directly. This doesn't matter for most tools since they are so slow, but this does matter for esbuild since it's so fast.

* People are confused by `npx` and when it's necessary. It's actually not necessary in build scripts since they are already run in a context where `node_modules/.bin` is in the path, but I was seeing people copy `npx` into their build scripts anyway via `"scripts": { "build": "npx esbuild ..." }`. That unnecessarily adds the performance cost of running `npx` to every build without any benefit, since it would work fine without `npx` instead: `"scripts": { "build": "esbuild ..." }`. This is why the [documentation for build scripts](https://esbuild.github.io/getting-started/#build-scripts) uses this specific syntax. It deliberately uses the `esbuild` command instead of `./node_modules/.bin/esbuild` which also works on Windows.

**Comment by Pomax** [comment]
1. that's a perfectly valid reason not to, we've had a lot of fun security issues in npm-land.
2. maybe, but esbuild is going to be part of a build chain, so in that sense the performance impact of `npx` on a manual run (which isn't how esbuild is going to run 99.99% of the time) doesn't feel all that important.
3. absolutely true, though in that case I'd suggest first showing how to use set up the npm script and only then mentioning that for manual testing purposes you can of course also run it yourself, either using `npx` (with a note on why that might be a bad idea right now, that's good information for folks to learn!) or directly from the `node_modules/.bin` dir.

(There is also the option of explaining that if you've set up an npm script lke `"esbuild": "esbuild"` you can then use `npm run esbuild -- [runtime options go here]` as much as you like for manual testing, but that's certainly more work than either `npx` or running from the `.bin` dir)

**Comment by hardfist** [comment]
I use pnpm，which use pnpx other than npx

**Comment by Pomax** [comment]
That's not a tool people will have. If you have a recent version of Node, you already have npx because it comes with node. Having to install a third part tool just to run esbuild would be fairly silly ;)

**Comment by evanw** [comment]
The getting started documentation now uses `npx` in some places: https://esbuild.github.io/getting-started/. Closing.

**Comment by evanw** [comment]
I have an update on this: it looks like the `npx` command is pretty broken in recent versions of npm (version 7.3.0, released 3 months ago according to https://www.npmjs.com/package/npm?activeTab=versions). Paths with spaces are not quoted and are instead interpreted as multiple arguments: #965.

Given this severe bug, I am considering removing `npx` from the getting started documentation again.

**Comment by Pomax** [comment]
yeah that's pretty ridiculous. Is there an corresponding npm/npx bug that can be subscribed to about that?

**Comment by evanw** [comment]
It's fixed in the latest version (7.6.3), just not in that version (7.3.0). I tried to find the corresponding PR and/or commit from their repo but came up blank.

I'm planning on removing `npx` from the documentation again because I don't want the documentation to have to cover all of the various nuances of using `npx`. It's supposed to be a tutorial about using `esbuild`, not about using `npx`.

**Comment by Pomax** [comment]
makes sense. sham though, maybe it'll be the right thing to recommend once v16 in the LTS
