### ISSUE TITLE
Enable external source maps by default?

### ISSUE THREAD

**Issue by Siilwyn** [evanw/esbuild#833]
Just read [this article about source maps declining](https://www.ctrl.blog/entry/deploy-javascript-source-maps.html) in usage and how it helps developers to learn from existing websites. What are your thoughts on enabling them by default, preferably external source maps?

**Comment by evanw** [comment]
I do not think source maps should be enabled by default in esbuild. People reach for esbuild primarily because they want their builds to be fast, and generating source maps is one of the slowest things about doing a production build. Source maps contain your original source code and are often ~3x larger than your minified JavaScript, so they will also bloat the output folder and slow down deploys if you aren't using them. And if only 18% of web sites need this (according to your link), then that further reinforces to me that they shouldn't be enabled by default.

**Comment by heyheyhello** [comment]
Just to clarify, they're not saying only 18% _need_ it, but rather that it's unfortunate how only 18% actually have source maps hosted/available.

Size isn't really a concern since source maps are only downloaded by browsers when you open devtools, so it's very opt-in and doesn't impact any normal production traffic.

I agree that esbuild should be fast and that source maps are slow. It's good that it's off by default.

@Siilwyn it's a really nice dream to make the web inspectable and something people can learn from (even pika/snowpack's old motto was "bring back view-source://") but unfortunately the modern web stack is so over-engineered and bloated that it's very difficult to try to learn from reading deployed code... Projects are likely better off redirecting people to their Git and ARCHITECTURE.MD docs
