### ISSUE TITLE
Can I push a file to plugin output file list?

### ISSUE THREAD

**Issue by ym-project** [evanw/esbuild#837]
Hi!
Does exist an opportunity to push file to output file list via plugin API?
I have a plugin to transform stylus to css files. And I want to generate external sourcemaps.
```js
onLoad({}, () => {
    // ...
    const result = await stylusToCss(stylusContent)
    
    if (result.sourcemap) {
        await fs.writeFile(fileName + '.map', JSON.stringify(result.sourcemap, null, 2))
    }
    
    return {
        contents: result.css,
        loader: 'css',
    }
})
```
I have 2 problems:
1. I don't see external sourcemap in output file list (but let's skip this);
2. When esbuild has an option "write: false" sourcemap will be generated anyway (critical case).

I see 2 solutions for this problem.
1. Get access to esbuild user options to know value of option "write: false/true" (as workaround);
2. Get an opportunity to return an array of files.

What do you think about this?

**Comment by evanw** [comment]
Not yet. But that might not be what you want here. If you were to use the plugin proposed above where you write source maps to the file system outside of esbuild's view like this, the source maps would be broken because they would be referencing offsets in the input file instead of the output file.

There are several things here including:

1. Plugins should be able to access options (tracked by #373)
2. Source map support for CSS (tracked by #519)

I think the real solution for this would be for esbuild to support source maps. Then you could pass the source map along with `/*# sourceMappingURL=data:... */` and esbuild would transform it along with the CSS (and bundle multiple source maps into one when bundling). This is how generating source maps in JavaScript plugins works with esbuild. Unfortunately CSS support in esbuild is still early and CSS source maps aren't working yet. You can follow issue #519 for progress on that front.

**Comment by ym-project** [comment]
Maybe in my case sourcemap support will resolve the problem. But there are situations where developer would like to create additional files for correct file transform.
So if you implement an opportunity to return array of files, it will be awesome.

**Comment by evanw** [comment]
You can now do this using an `onEnd` callback: https://esbuild.github.io/plugins/#end-callbacks. Closing.

**Comment by mbrevda** [comment]
Can you please point to an example of adding files in `onEnd`?
