### ISSUE TITLE
Question: esbuild in Next.JS

### ISSUE THREAD

**Issue by Jared-Dev** [evanw/esbuild#838]
This may not be possible, but has anyone found a method to use esbuild to compile Next apps?

**Comment by DannyFeliz** [comment]
They're investigating 😀
![image](https://user-images.githubusercontent.com/5460365/108388074-a20a5380-71e4-11eb-9976-541bcb5548bf.png)

[Source](https://twitter.com/rauchg/status/1361801714903343108)

**Comment by zaydek** [comment]
@Jared-Dev Next.js uses webpack and you can customize webpack in Next.js, and there are some community plugins for using esbuild in webpack: https://github.com/esbuild/community-plugins.

If that answers your question, I’d recommend closing this to help keep the issues organized. Anyway, best of luck!

**Comment by evanw** [comment]
I’m going to close this since this isn’t an issue with esbuild. It seems more like a question for next.js.

**Comment by harisraharjo** [comment]
here is an example of how to use esbuild in nextjs https://github.com/privatenumber/esbuild-loader-examples/tree/master/examples/next

**Comment by s-kris** [comment]
> here is an example of how to use esbuild in nextjs https://github.com/privatenumber/esbuild-loader-examples/tree/master/examples/next

this is for build and not for dev/hmr.
Build time was reduced to 100s from 180s for my nextjs app.

**Comment by corysimmons** [comment]
>here is an example of how to use esbuild in nextjs https://github.com/privatenumber/esbuild-loader-examples/tree/master/examples/next

**Note:** ☝️ is esbuild-loader (wraps slow Webpack), not esbuild by itself (clean, super fast). It should mostly work (with a few bugs) _now_ for Next, but you just get a ~2x boost. If you're looking for insane ESBuild 100x boost then NextJS would have to stop using Webpack completely and just use ESBuild—which is [going to be an incredibly hard sell](https://github.com/vercel/next.js/search?q=webpack) because they'd need to completely refactor what NextJS is, but if they did it, NextJS would dominate everything for the foreseeable future.

I'm not holding my breath for Next to do this. We'll probably just have to wait a year for some other greenfield tool to get good (like Vite or Snowpack + some Next-like React framework).

**Comment by redbar0n** [comment]
@corysimmons [vite-plugin-ssr](https://github.com/brillout/vite-plugin-ssr) might already be that greenfield tool to potentially replace NextJS..

**Comment by redbar0n** [comment]
actually, [Vitext](https://github.com/Aslemammad/vitext) is the framework built on top of [vite-plugin-ssr](https://github.com/brillout/vite-plugin-ssr) that aims to replace Next. Since [vite-plugin-ssr](https://github.com/brillout/vite-plugin-ssr) is just a small focused core on which frameworks can be built (ref: [creator's tweet](https://twitter.com/brillout/status/1434433974412226560?s=20)).

**Comment by brillout** [comment]
@redbar0n 💯

**Comment by brillout** [comment]
@Aslemammad 😊

**Comment by Aslemammad** [comment]
Thank you, @brillout @redbar0n, for indicating [Vitext](https://github.com/Aslemammad/vitext)!
Yep, Vitext is experimenting with vite-plugin-ssr to replace vitext's core; this is in favour of concentrating more on framework/lib development (React/Preact/Solid/...) instead of handling cases that vite-plugin-ssr handles already!

**Comment by leerob** [comment]
Hello everyone! Lee from Vercel here.

As mentioned above, we are moving Next.js to a new [Rust compiler based on SWC](https://nextjs.org/blog/next-11-1#adopting-rust-based-swc). We are not planning to use esbuild or Vite, although both are great projects.

11.2 will include a beta for this new compiler, which has [much faster](https://twitter.com/timneutkens/status/1443540327101566976) HMR / Fast Refresh and build times.

**Comment by corysimmons** [comment]
Honestly I'm excited and appreciate Vercel working on it.

Imagine having a huge project that is 90% Webpack plugins/config, then someone creates some crazy-fast replacement but it doesn't have most of the plugins projects rely on, so you'd have to make & assume responsibility for maintaining a lot of those.

...a lot of other companies would've just threw their hands up, but it seems like Vercel is trying their best to migrate to these incredible new technologies with big wins first, then slowly/precisely migrating other parts of Next.

**Comment by leerob** [comment]
We plan to introduce the new Rust compiler with no breaking changes. You'll be able to incrementally adopt into it. If you have custom Babel configurations that aren't supported, your application won't break - you will just de-opt and continue using Babel. We feel this will help teams slowly move to a faster dev experience – plus help all new applications start off with the Rust compiler.

Over time, we'll continue moving more and more parts from webpack to the Rust compiler, again with incremental adoption.

**Comment by sergeysova** [comment]
But SWC does not support a plugin system. Projects like [vanilla-extract](https://github.com/seek-oss/vanilla-extract) and [effector](https://github.com/effector/effector/) really depends on it.

**Comment by sergeysova** [comment]
@timneutkens Thank you for the answer.
Babel plugin for effector — https://github.com/effector/effector/blob/master/src/babel/babel-plugin.js

I want to help you port plugins to a new SWC plugin system.
