### ISSUE TITLE
Broken import with unicode path

### ISSUE THREAD

**Issue by Djaler** [evanw/esbuild#841]
Example file
```
import test from "./тест";

export default test
```

When I run esbuild on this file (without any options) I receive this:
```
import test from "./\u0442\u0435\u0441\u0442";
export default test;
```

**Comment by Djaler** [comment]
I found this when using vitejs (https://github.com/vitejs/vite/issues/2083)

**Comment by evanw** [comment]
It looks like escapes in import paths are valid to me, at least according to node:

```sh
$ echo 'export default 123' > тест.mjs
$ echo 'import test from "./\u0442\u0435\u0441\u0442.mjs"; console.log(test)' > example.mjs
$ node example.mjs
123
```

So esbuild is justified in using them. Perhaps this is an issue with Vite instead? Note that I had to add `.mjs` to the import path to get it to work in node.

You can use UTF-8 output instead of ASCII output if you want, although there are caveats: https://esbuild.github.io/api/#charset.

**Comment by Djaler** [comment]
Yeah, it works good with UTF-8 charset defined!

**Comment by evanw** [comment]
Ok. I'm going to close this then. This is a bug in Vite, not in esbuild. I also filed https://github.com/guybedford/es-module-lexer/issues/61 which is the underlying issue in the library Vite is using.

**Comment by Djaler** [comment]
Thanks!
