### ISSUE TITLE
Cannot resolve node libs: path, events

### ISSUE THREAD

**Issue by g-a-v-i-n** [evanw/esbuild#85]
Hi! First, this project is extremely impressive to me. One of the biggest things that breaks my flow when programming these days is the speed of the build tooling. It's very exciting to see a project that addresses this need.

As I was trying this out, I ran into some issues with 3rd party modules which include `path` and `events`:

```
node_modules/replace-ext/index.js:3:19: error: Could not resolve "path"  
var path = require('path');
```
```
node_modules/htmlparser2/lib/Parser.js:20:23: error: Could not resolve "events"
var events_1 = require("events");
```

The 3rd party library in question is `react-markdown`.

I know esbuild isn't quite ready for prime time, but was wondering if you had any pointers with these. Thanks!

Building for browser
Using Typescript + React
Build command: `esbuild src/index.tsx --bundle --outdir=dist`
Node 10.0.0
Mac OS Catalina 10.15.2 (19C57)

**Comment by evanw** [comment]
This happens because esbuild doesn't currently attempt to replicate the full node environment in the browser. It just bundles together the JavaScript you provide to it.

I think it should be possible to shim these particular libraries by installing https://www.npmjs.com/package/path-browserify and https://www.npmjs.com/package/events and then adding this to your project's package.json:

```json
"browser": {
  "path": "path-browserify"
},
```

This tells esbuild to remap the `path` package to the `path-browserify` package. It's the same convention that other bundlers use when targeting the browser.

However, when you try to use the `react-markdown` package, it will still crash at run time because it attempts to call `process.cwd()`. Since esbuild doesn't do anything special about replicating the node environment in the browser, it doesn't do anything to ensure that there's a global called `process` in the browser. You can shim that yourself though by installing https://www.npmjs.com/package/process and then running this code before the `react-markdown` package is required:

```js
window.process = require('process')
```

Does that work for you?

**Comment by evanw** [comment]
FWIW I was able to get the `react-markdown` package to work in the browser after building with esbuild using the flags `--define:process.cwd=String` and `--define:process.env.NODE_ENV='"production"'` as well as the `path-browserify` path substitution mentioned above.

I'm closing this issue as I believe this information is sufficient to address the issue.

**Comment by dstaley** [comment]
@evanw is there a way to provide those package resolutions without modifying package.json? For example, I only want to replace a node-specific package when building my tests, but not my production bundle. If not, I'd be happy to open a PR if you can point me to where esbuild is ingesting the defined resolutions from package.json.

**Comment by evanw** [comment]
The general solution to package substitution is to write a small plugin to rewrite certain import paths: https://esbuild.github.io/plugins/#resolve-callbacks.

**Comment by mhsdesign** [comment]
im trying to bundle jit tailwind css for the browser, but it seems the `browser` alias are only used for imports in my own package, not where i need it. i want to `browserfy` path and co in tailwind and postcss source code...

**Comment by mhsdesign** [comment]
solved it via a custom plugin:

```js
const replaceNodeBuiltIns = () => {
    const replace = {
        'path': require.resolve('path-browserify'),
        'fs': require.resolve('./src/fs.cjs'),
        'util': require.resolve('./src/util.cjs'),
        'url': require.resolve('url/'),
    }
    const filter = RegExp(`^(${Object.keys(replace).join("|")})$`);
    return {
        name: "myReplaces",
        setup(build) {
            build.onResolve({ filter }, arg => ({
                path: replace[arg.path],
            }));
        },
    };
}
```

`plugins: [replaceNodeBuiltIns()]`
