### ISSUE TITLE
Support using onResolve and onLoad on the same import

### ISSUE THREAD

**Issue by martonlederer** [evanw/esbuild#853]
Request: support using `build.onResolve` and `build.onLoad` on the same import, while bundling the returned `path` from `build.onResolve`.

This would be necessary to provide support for PostCSS modules (#20), as we need to provide the bundled CSS module contents (and their classes) using `build.onResolve`, as well as providing a JSON object to map the random-generated CSS module class names with `build.onLoad`.

This usecase would look something like this:

```ts
...
modules: { path: string; json: { [key: string]: string} }[] = [];
build.onResolve({ filter: /.\.(css|sass|scss|less|styl)$/, namespace: "file" }, async (args) => {
   ...
   postcssPlugins.push(require("postcss-modules")({
      getJSON(filepath, json) {
         modules.push({
            path: tmpFilePath, // path to temporary file written by postcss
            json // css-module-class map created by "postcss-modules"
         })
      }
   }))
   ...
   return {
      path: tmpFilePath,
      namespace: isModule ? "postcss-module" : "file"  // here we add the namespace "postcss-module", if the file is a css module, if not, we treat it as a normal file
   };
})

// filter all css-module files and return it's content as a JSON object mapped from module fields
build.onLoad({ filter: /.*/, namespace: "postcss-module" }, (args) => {
   const map = modules.find(({ path }) => path === args.path);
    
   // here we basically return the css module's class mapping
   return {
      contents: JSON.stringify(map?.map ?? {}),
      loader: "json"
   };
});
```
The problem with the example above is that if I provide the namespace `"postcss-module"`, the css code bundled by postcss-modules and postcss will not be bundled into the `bundle.css` file, generated by `esbuild`.

**Comment by evanw** [comment]
I'm not totally sure what you're suggesting here but going off of what I know about PostCSS modules, I'm guessing you're trying to have your plugin both a) return a JSON object to JavaScript and b) include some CSS to go along with that JS. In that case you will need two separate virtual modules for this, one for the JS and one for the CSS. You'll need to arrange it so that an import like this:

```js
import * as styles from "./button.module.css";
```

generates a virtual JavaScript module that looks like this:

```js
import "...a reference to the css that goes with this js...";
module.exports = { button: "...the button class name..." };
```

that then imports a virtual CSS module that looks like this:

```css
.button { ...styles... }
```

This will involve two calls to `onResolve` and two calls to `onLoad`, one pair for the virtual JavaScript module and one pair for the virtual CSS module. If you put the JavaScript in a namespace such as `postcss-module-js` you can have the CSS `onResolve` plugin only look for imports for files in that namespace to pick out the import in the virtual JavaScript file.

Hope that helps.

**Comment by martonlederer** [comment]
Thanks, I'll try that and reflect on it asap

**Comment by martonlederer** [comment]
Thanks @evanw, figured it out with virtual modules
