### ISSUE TITLE
Contribution guidelines for docs

### ISSUE THREAD

**Issue by mesqueeb** [evanw/esbuild#854]
I found  typo in the docs:
<img width="681" alt="image" src="https://user-images.githubusercontent.com/3253920/108577274-ce001300-7363-11eb-83e9-cd602c7f7d62.png">

`tsc -noEmit` should be `tsc --noEmit`

I want to make a PR!
But I cannot find the source code on these docs.

Are there any contribution guidelines for the docs?

**Comment by evanw** [comment]
> `tsc -noEmit` should be `tsc --noEmit`

`tsc -noEmit` and `tsc --noEmit` both mean exactly the same thing. The TypeScript command line parser accepts either one `-` or two `--` equally. You can see the code that does this for yourself if you'd like (from [src/compiler/commandLineParser.ts](https://github.com/microsoft/TypeScript/blob/c3e132da5972c3dafed9c1de1e07414e540fbdd3/src/compiler/commandLineParser.ts#L1315-L1320)):

```ts
if (s.charCodeAt(0) === CharacterCodes.at) {
    parseResponseFile(s.slice(1));
}
else if (s.charCodeAt(0) === CharacterCodes.minus) {
    const inputOptionName = s.slice(s.charCodeAt(1) === CharacterCodes.minus ? 2 : 1);
    const opt = getOptionDeclarationFromName(diagnostics.getOptionsNameMap, inputOptionName, /*allowShort*/ true);
```

Closing this issue since it does not seem like anything is wrong. The source code for the documentation is at https://github.com/esbuild/esbuild.github.io but I'm not interested in a contribution that just changes a command-line argument to a slightly different form.

**Comment by mesqueeb** [comment]
@evanw Thank you very much. I didn't know this. When I checked with `tsc --help` it didn't anywhere say you can substitute `--` for `-`, so that's why I thought it was a typo.

I think seasoned devs might know this but a lot of newer front-end developers who are not good so experienced yet with CLIs in general might not know this.

If it were me I would still replace the docs `-noEmit` for `--noEmit` just to prevent other devs like me coming here, reporting the same thing. :P
