### ISSUE TITLE
Specifying plugins via the CLI

### ISSUE THREAD

**Issue by andreialecu** [evanw/esbuild#884]
`aws-cdk` currently uses `esbuild` to bundle code used for lambdas: https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-nodejs-readme.html

Unfortunately, because of internal implementation details in `aws-cdk`, the esbuild nodejs API cannot be used directly. Ref: https://github.com/aws/aws-cdk/issues/13179#issuecomment-783219945

So they can only use the `CLI` to spawn `esbuild`. 

The problem is that when used in conjunction with Yarn v2 and PnP, this plugin needs to be added: https://github.com/yarnpkg/berry/tree/master/packages/esbuild-plugin-pnp

Currently `esbuild` does not seem to allow specifying plugins via a CLI option, so Yarn PnP cannot work with the aws-cdk esbuild implementation. Ref: https://github.com/aws/aws-cdk/pull/13257#issuecomment-785754369 (there's a workaround possible, but it makes things pretty complicated)

Would it be possible to allow specifying the plugin via the CLI? Or via some configuration file perhaps? (some file like `.esbuildrc` could be an option)

**Comment by evanw** [comment]
Sorry, esbuild's plugin API is intentionally designed to be accessible via JavaScript instead of the CLI. IMO using JavaScript is much more intuitive and ergonomic than a CLI for complex configuration scenarios. I don't really have any plans to change this at the moment.

I'm completely unfamiliar with what AWS CDK is, so my apologies if something I'm saying doesn't make sense. With that caveat in mind, some possible workarounds for you off the top of my head:

* Disable Yarn v2 PnP mode
* Use Yarn v1 instead of Yarn v2
* Use another package manager instead of Yarn
* Use Yarn v2 with PnP but run esbuild yourself in your own build script before the AWS CDK sees your code

Do any of those work for you?

I may in the far future explore a plugin API for binary plugins. If I do that, there's a possibility that they might be enabled for CLI usage. See https://github.com/evanw/esbuild/issues/111#issuecomment-720053290 for more information. But right now I am not planning on taking esbuild's plugin API in this direction.

**Comment by fazouane-marouane** [comment]
A bit of a hack but, does creating an alias to npx solve the issue ? Maybe aliasing npx to "yarn" or "yarn dlx" would do ?

**Comment by andreialecu** [comment]
@evanw in the PnP resolver plugin's case, it just needs to be imported. No other configuration for it is required.

There is a workaround possible, by disabling PnP, but that's not a good solution for bigger monorepos that rely on it.

This is also related: https://github.com/evanw/esbuild/issues/237#issuecomment-725715131

A way to simply allow specifying a plugin, but for the CLI would be great. This is all that is needed:

```ts
import {pnpPlugin} from '@yarnpkg/esbuild-plugin-pnp';

await build({
  plugins: [pnpPlugin()],
  // ...
});
```

I noticed that the possibility of an `esbuildrc` file was discussed before: https://github.com/evanw/esbuild/issues/39

An `.esbuildrc.js` could look like:

```js
module.exports = {
  plugins: ['@yarnpkg/esbuild-plugin-pnp']
}
```

or

```js
import {pnpPlugin} from '@yarnpkg/esbuild-plugin-pnp';
module.exports = {
  plugins: [pnpPlugin]}
```

There are various tools already written that use the `esbuild` CLI, and they're all blocked from supporting PnP due to this omission, unfortunately. :(

**Comment by fregante** [comment]
> IMO using JavaScript is much more intuitive and ergonomic than a CLI for complex configuration scenarios

This kind of makes sense from a "complexity within esbuild" standpoint but unfortunately the API isn't equivalent to the CLI. I just used it successfully and the first thing I notice is that I no longer get a list of outputted files and stats.

I also have to deal with running the file myself, e.g. I have to use ts-node:

```sh
node --loader ts-node/esm esbuild.ts
```

**Comment by fregante** [comment]
Blocked by 

- https://github.com/evanw/esbuild/issues/1492

🤷‍♂️

**Comment by hyrious** [comment]
@fregante You can get output stats with [`logLevel: 'info'`](https://esbuild.github.io/api/#log-level), or try parse the [`metafile`](https://esbuild.github.io/api/#metafile) by yourself ([an example of mine](https://github.com/hyrious/esbuild-repl/blob/fab9c82fe6193cf930a15039de5f540c507aee82/scripts/build.ts#L35)).

---

Talk back to the issue, I have made `--plugin:xxx` in my [esbuild-dev](https://github.com/hyrious/esbuild-dev), which is just a wrapper of esbuild to build & run files like ts-node. An example of using that is I made a [svelte ssr](https://github.com/hyrious/esbuild-repl/blob/fab9c82fe6193cf930a15039de5f540c507aee82/package.json#L4) plugin and with that I can import svelte file right in the node side.

Other solutions like [antfu/esno](https://github.com/antfu/esno) use require.extensions / loaders to not pollute the file system and provide better experience at `__filename` and `import.meta`. I believe this will be a better solution than mine because node loaders are the future. However esbuild plugins won't work in transform mode, I don't know what will they do.

---

One thing I'd like to have is loading plugins from the global scope like rollup. But I haven't got the trick to implement that.

**Comment by shellscape** [comment]
Another vote for specifying plugins via CLI. CDK has us limited to builtin loaders, for which there isn't one for `.graphql` files, and forces us to abandon imports.

**Comment by piotrmoszkowicz** [comment]
It would be awesome to have that +1 to @VanTanev proposal.

**Comment by klarkc** [comment]
+1 for this. When using nix package manager, it only exposes esbuild CLI, to use plugins with esbuild, one need to build a derivation to inject plugins, it just does not worth the added complexity.

**Comment by thefat32** [comment]
+1 for this need this to simplify bundling using CDK aws-lambda-nodejs

**Comment by PatrykMilewski** [comment]
Same issue here with aws-cdk

**Comment by IARI** [comment]
similar issue here (though im building with esbuild manually, so I can workaround by not using the cli tool ....)

**Comment by evanw** [comment]
I'm closing this issue because I'm not planning on doing this. For what it's worth esbuild has since added native support for Yarn PnP, so the concern in the original issue should be resolved by just updating esbuild.

**Comment by shellscape** [comment]
Disappointing, as even Rollup has pulled this off without headache.

**Comment by klarkc** [comment]
FWIW, [vite](https://vitejs.dev/) might be a good replacement for esbuild in this case, given that it support more features without the need for plugins.

**Comment by shellscape** [comment]
guess what vite uses under the hood? 😉

**Comment by VanTanev** [comment]
Hey @evanw, thank you for the amazing work on esbuild!

I wanted to ask, could you reconsider this issue? `aws-cdk` has really put us in a bind, by not allowing a js config for esbuild. The only thing we can configure is cli options.

I know that is of no fault of yours, and you have no obligation to take on the burden of supporting extra features in esbuild.

Still, it would be really helpful for us, and other teams that need to bundle through cdk. Having the option to either specify a config file, or a file with a plugin to be loaded from the cli would be a God sent.

**Comment by evanw** [comment]
This isn’t straightforward on esbuild’s side because the CLI is native code and doesn’t contain a JavaScript interpreter. This feels like something that sounds be fixed on AWS’s side instead. If they want to support JavaScript plugins, they should be using esbuild’s JavaScript API instead of the CLI. Please file an issue with them about it.

**Comment by aslakhellesoy** [comment]
FWIW, I worked around this issue with https://github.com/mrgrain/cdk-esbuild

**Comment by rjmackay** [comment]
This is the relevant CDK issue FYI https://github.com/aws/aws-cdk/issues/18470

**Comment by dy** [comment]
Stumbled here too - sprae needs [CDN version](https://github.com/dy/sprae/issues/24), but first limitation of esbuild - it doesn't have [UMD output format](https://github.com/evanw/esbuild/issues/507).
We can use [esbuild-plugin-umd-wrapper](https://github.com/inqnuam/esbuild-plugin-umd-wrapper) as workaround, but it can be used only via JS API, which forces creating a js entry. We expose all root level js files, so this way it just makes repository not as clean, whereas there could just be `--plugin:umd-wrapper` or `--format:umd`

**Comment by lpicchi** [comment]
@dy please take a look at this merge

https://github.com/aws/aws-cdk/pull/30196

**Comment by dy** [comment]
32k loc... can you be more specific? For now I just made .esbuild.js

**Comment by lpicchi** [comment]
Yes this is the relevant section of the [README ](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-lambda-nodejs/README.md#running-a-custom-build-script-as-part-of-cdk-synthesis)

You can create your own `build.mjs` file and use wathever plugin you need

**Comment by drzraf** [comment]
@evanw : Do you mind specifying what are the technical challenges to overcome to make this a reality (given that it is, for sure, desirable and source of interest to many). Is it about command-line expressiveness limitations only (passing plugins arguments?). If so, this could be probably be overcome passing a plain JSON object to a `--plugins` option.
