### ISSUE TITLE
Custom chunk folder

### ISSUE THREAD

**Issue by claviska** [evanw/esbuild#888]
This is somewhat similar to #553 but specifically for chunks. Currently, they all get dumped in the root, which is a bit messy and confusing.

As a user, I don't really want to configure an output dir/filename for _all_ files. I'm actually very happy with esbuild mimicking my existing directory structure. But those chunk files...In my case, each component has its own entry point and I end up with ~50 chunks in the root. 😆

I'd love to have an option that let's me define a simple path or even a string-based. Rollup does this quite intuitively with `chunkFileNames`:

```js
{
  // ...
  chunkFileNames: '[name]-[hash].js'
}
```

But again, even a`chunkDirectory` option would be amazing. ✨

Aside: thanks for your incredible work on esbuild! 🙌

**Comment by evanw** [comment]
This is actually already in the works. It's one of the features from the upcoming rewrite of the linker, with which I am planning to support this feature as well as code splitting for all formats, top-level await, manual chunk names, custom chunk transform plugins, accurate import order, and probably some other stuff. But that has been taking a while because the combination of all of those features gets really complicated. I could potentially pull out some of these features and land them into master now though.
