### ISSUE TITLE
bug: run-time error when enum is declared

### ISSUE THREAD

**Issue by privatenumber** [evanw/esbuild#890]
Reproduction repo: https://github.com/privatenumber/esbuild-vue-enum-repro

### Description
The following code yields a run-time error:
```js
import { NodeTypes } from '@vue/compiler-core';

console.log(NodeTypes.ELEMENT);
```

`@vue/compiler-core`:
```ts
...

export declare const enum NodeTypes {
	...
```

Error:
```
console.log(import_compiler_core.NodeTypes.ELEMENT);
                                           ^

TypeError: Cannot read property 'ELEMENT' of undefined
```

I believe esbuild ignores the Typescript `declare` syntax, but the run-time error is unexpected. I think the expected behavior here would be for the enum value to be inlined (in this case `1`) and the enum map to be stripped, or for the build to throw an error.

### Reproduction steps
1. Clone https://github.com/privatenumber/esbuild-vue-enum-repro
2. Install dependencies: `npm ci`
3. Produce Typescript and Esbuild builds to compare: `npm run build`
4. Test Typescript dist is working: `node dist-ts`
5. See esbuild dist is not working: `node dist-esbuild`

I wanted to use Vue to demonstrate this is something happening in a popular library but this is a more minimal reproduction of the problem:

#### Src
```ts
declare const enum NodeTypes {
    ELEMENT = 1,
}
console.log(NodeTypes.ELEMENT);
```

#### Dist
```js
// src/index.ts
console.log(NodeTypes.ELEMENT);
```

**Comment by evanw** [comment]
This is happening because esbuild compiles each TypeScript file in isolation. That means there is no way for esbuild to know that `NodeTypes` is a type-only construct given just the contents of that one file. This limitation applies to all other TypeScript-to-JavaScript compilers that operate on a single file including Babel and using TypeScript's `transpileModule` API. Because of this, the TypeScript team has added a flag called [`isolatedModules`](https://www.typescriptlang.org/tsconfig#isolatedModules) that you can add to your `tsconfig.json` file to prevent you from doing things that don't work with this compilation approach. It will make doing what you are trying to do here a compile error, and then you can fix the resulting compile errors. You should enable this setting when using esbuild. There is more documentation about this as well as some additional TypeScript compilation caveats in the esbuild documentation: https://esbuild.github.io/content-types/#typescript.

**Comment by privatenumber** [comment]
Didn't know about those options but just read up on them and makes sense.

I will probably have to copy-paste the enum without the declaration in my code.

Going to close this since this is expected behavior.

Thanks @evanw
