### ISSUE TITLE
[Feature Request]: show warning about undeclared variables

### ISSUE THREAD

**Issue by susiwen8** [evanw/esbuild#896]
During build process, `webpack` and `rollup` throw error when `undeclared variable` exist in code but  `esbuild` doesn't.

Right now `esbuild` throw warning if `process.env.NODE_ENV` existed. It there any plan on warning `undeclared`?

**Comment by evanw** [comment]
This is out of scope of esbuild. This is the job for a linter, not for esbuild. Warnings in esbuild are intended to only trigger if there is a very low probability of a false positive. Warning on every global variable access would be extremely noisy and would be the opposite of that goal. The only reason esbuild warns about `process.env.NODE_ENV` is because React is an extremely popular library that has decided to make it impossible to bundle correctly without defining `process.env.NODE_ENV`. Closing because this is out of scope.
