### ISSUE TITLE
 collect performance timings about plugin cost

### ISSUE THREAD

**Issue by hardfist** [evanw/esbuild#904]
We heavily use esbuild in production with lots of js plugins, sometimes we met performance issues, we want to know  every plugin's cost and esbuild internal cost. something like rollup's [perf](https://rollupjs.org/guide/en/#perf) option might be helpful.

**Comment by zaydek** [comment]
@hardfist Are you caching your plugins? If I’m not mistaken, esbuild doesn’t cache plugins because they cannot be considered ‘pure functions’ (given you can write to disk, etc.). I implemented caching for a plugin I was working on based on the docs: https://esbuild.github.io/plugins/#caching-your-plugin and found that provided the performance gains I expected. First build will be the slowest, of course.

That being said, yeah it would be nice to have some kind of diagnostic to triage plugin performance, given that is likely to be the biggest performance bottleneck. I’m not sure how solvable this is in user land because it may not be a good idea to have users implement performance diagnostics on a per-plugin basis.

Maybe there’s a way to wrap a plugin and then write to `pluginData` so this can be solved in user land and by wrapping only / every plugin you want to measure? Something like: `plugins: [...measurePlugins(myPlugin, ...)]`? Might be a bad idea…

**Comment by evanw** [comment]
It's not easy to automatically collect actionable performance metrics about plugins. Plugins are intentionally async I don't think there's a great way of having the caller follow a promise chain and measure the time spent in all of the promises in the chain. And the time from plugin start to end doesn't necessarily mean too much if there are a lot of plugins running concurrently.

I would recommend just running a profiler instead. That should provide much more actionable information.

**Comment by hardfist** [comment]
@evanw ,it seems esbuild-wasm's plugin does not running concurrently, I do some profile on my application(https://github.com/evanw/esbuild/files/6095377/browser.cpuprofile.zip), It seems that handleRequest's cost is a little too high(the cost is mostly in  the js-to-wasm function, and the cost is much slower on node #922 ),
![image](https://user-images.githubusercontent.com/8898718/110208561-d3607000-7ec2-11eb-9c22-a0a0009688f9.png)
 it seems that can do some perf metrics on esbuild's js side 
https://github.com/evanw/esbuild/blob/899414ec00b92e069060f049084d061b534c634f/lib/common.ts#L632-L658, since it already await esbuild plugin's resolve&load hooks.

**Comment by evanw** [comment]
Closing for the reasons described above. The `js-to-wasm` "function" just means the browser is running esbuild's WebAssembly code. This is not related to running a plugin.
