### ISSUE TITLE
[Feature] Inline identity functions when minifying

### ISSUE THREAD

**Issue by natemoo-re** [evanw/esbuild#907]
Hello there! I know [minification](https://esbuild.github.io/api/#minify) isn't the core focus of `esbuild`, but one very nice feature of `terser` is identity function inlining (see [terser#510](https://github.com/terser/terser/issues/510).) It would be nice if `esbuild` could optimize these functions away as well, as it's a pretty common pattern.

**Input**
```js
const id = x => x;
const repro = [id(1), id(2)];
console.log(repro);
```

**Current output**
```js
const id=o=>o,repro=[id(1),id(2)];console.log(repro);
```

**Desired output**
```js
const repro=[1,2];console.log(repro);
```

**Comment by evanw** [comment]
This isn't super straightforward to fix because doing this correctly would require inserting at least one more full-AST traversal after the scanning phase but before the linking phase. This would slow esbuild down and would work against the goal of having as few passes as possible for speed. So I'm not planning on having esbuild tackle these kinds of optimizations. At least not at the moment.

Another consideration is that the author of Terser is currently exploring a rewrite in Rust which should hopefully alleviate the huge performance impact of running Terser during a build. If that rewrite is successful, it might make less sense for esbuild to do all the work to replicate the advanced optimizations that Terser does if people can just run Terser after running esbuild instead.

Another similar request: #290.

**Comment by natemoo-re** [comment]
That makes total sense, thank you for the quick and thorough response. As the docs mention, esbuild's minification is definitely within range of the alternatives—was just curious if this would be a quick optimization!

Going to close this as it seems out of scope for now.

**Comment by evanw** [comment]
I implemented this for `function` declarations by the way. It was not a quick optimization, and it's a bit of a hack, but it should work now. See #1898 for details.
