### ISSUE TITLE
TypeError: Cannot read property 'ColumnNames' of undefined

### ISSUE THREAD

**Issue by moltar** [evanw/esbuild#909]
I am not sure if the issue is with `esbuild` or the underlying library, but I am running into a peculiar error for which I have a repro here:

https://github.com/moltar/zapatos-issue-10

Transpiling with `tsc` works fine.

Reference issue in the library repo: https://github.com/jawj/zapatos/issues/75

Thank you!

**Comment by evanw** [comment]
The problem happens when `node_modules/zapatos/db.mjs` (an ESM file) imports `node_modules/zapatos/db.js` (a CommonJS file). I think the underlying issue is #532, which is already tracked. Basically there are two conflicting approaches for handling importing a CommonJS file into an ESM file. Some JavaScript tools do this one way and other JavaScript tools do this another way. It's a big mess.

The way node works is that the `default` export is always equal to the value of the CommonJS file's `module.exports` property without any exceptions. Some other JavaScript tools (but not node) support CommonJS files that have been converted from ESM format to CommonJS format. These ones are marked by setting `module.exports.__esModule` to true. For these modules, all properties on `module.exports` behave like named exports as if the file was in ESM format. And if there is no `module.exports.default` property, then there is no export named `default`.

So this should be considered a bug in esbuild in that the behavior isn't matching node. But it's not super straightforward to fix this because a trivial fix would break esbuild's ESM-to-CommonJS transform which esbuild relies on internally. Webpack has an approach where they try to support both of these behaviors and use heuristics to determine which approach to apply when. I assume esbuild will have to do something like that.

**Comment by moltar** [comment]
@evanw thank you for your in-depth explanation! I really appreciate all of the effort and community management you put into this. 🙌🏼 

Shall we close this in favor of #532 then?

**Comment by evanw** [comment]
Sure, sounds good. I greatly appreciate having a real-world example of this problem in practice though. So thank you very much for taking the time to put together a repro.

**Comment by evanw** [comment]
Closing in favor of #532.

**Comment by evanw** [comment]
I believe this should be working now as of version 0.8.55. Please let me know if that's not the case.

**Comment by moltar** [comment]
That does indeed fix the issue! Thank you so much for fixing this so quickly!
