### ISSUE TITLE
[proposal]: Replace esm import paths by their full equivalents

### ISSUE THREAD

**Issue by kamil0414** [evanw/esbuild#911]
Some unscoped npm dependencies have index.js with shortcuts (exports). 
For example:

`// node_modules/lib_example/index.js`
`export {a} from './a';`
`export {b} from './b';`

Its allow to easy import dependency files in appliaction.
But there is a problem with resolving these files by browsers (unbundled version). 
Browser resolve all exports (unused also). 
It has big impact on loading performance.
Imports paths could be replaced by 'full' path, based on index.js file from dep.

before:

`import {a} from 'lib_example'`

after:

`import {a} from 'lib_example/a'`

**Comment by evanw** [comment]
It's not clear to me what you are doing from this description, so it's hard to say what to recommend. But if you are using esbuild as a bundler and want to mark these paths as external instead of including them in the bundle, you could try writing an on-resolve plugin that returns `{ path: 'lib_example', external: true }` for these import paths: https://esbuild.github.io/plugins/#resolve-callbacks.

**Comment by evanw** [comment]
Closing due to lack of a reply.
