### ISSUE TITLE
[Question] Is there a shutdown hook for plugins?

### ISSUE THREAD

**Issue by leheinlein** [evanw/esbuild#912]
Hello! We are looking into whether it would be feasible to use esbuild in our application; I am looking at writing a plugin that would add some additional functionality that we need.

My plan was to open up some resources when the plugin is initialized and close them up when it is shutdown. However, I don't see any shutdown hooks - I only see the `Setup` function on the `Plugin` type, and the `OnResolve` and `OnLoad` hooks.  Is there any hook that I can use to close any resources that were opened, or would they have to be open with each `OnResolve`/`OnLoad` callback?

[For more context, the extra functionality we need is related to some experimental TypeScript features that we are using in just a couple of files; the idea behind the plugin is to start a `tsserver` instance, send those particular files for checking when they are resolved, and then shut down the `tsserver` when `esbuild` is shutdown.]

**Comment by evanw** [comment]
No, there isn't yet. It's a little more complicated than just adding a shutdown callback because of incremental builds. Incremental builds mean that new builds can be started later, and multiple builds can even be running at the same time.

So one option is to expose an API for being able to tell when one or more builds are in progress. Maybe `onBuildBegin` and `onBuildEnd`? Another option is to expose an API for being able to tell when it's no longer possible for an incremental build to happen (e.g. `rebuild.dispose()` was called). Maybe `onDispose`? Do you know which one you are looking for?

**Comment by leheinlein** [comment]
Hmmm... something like `onDispose` sounds like what I was looking for.  Thanks for the response and the info!
