### ISSUE TITLE
Entry file is ignored for re-exported file

### ISSUE THREAD

**Issue by jalal246** [evanw/esbuild#916]
I have `index.ts` as an entry which re-export default function:

```js
export { default } from "./foo";
```

But it's being ignored when running `esbuild ./src/index.ts --bundle` 

However, doing import/export in index works fine:

```js
import foo from "./foo";

export default foo;
 ```

**Comment by evanw** [comment]
When you use `--bundle` without any other flags, the default format is set to `iife` (immediately-invoked function expression). However, no exports object is created if you don't specify `--global-name=` so unused exports are removed as dead code. If you expose the exports by either setting `--global-name=` or by using another format such as `--format=cjs` or `--format=esm`, the exports should come back because they are actually used in that case.

The reason why the code in the second example is not removed is because `export default <expression>` actually creates a separate variable called `default` to capture the initial value of the import `foo`, so it's doing something slightly different. Arguably this variable should be removed if it's not used in this case, so maybe it staying around could be considered a bug.

In any case, the equivalent two-statement version of the original one-statement version is this instead, which does not create another variable and which remains a live binding instead of capturing the initial value:

```js
import foo from "./foo";
export { foo as default };
```

**Comment by jalal246** [comment]
Thanks for the explanation! That's why it worked fine when I tried to export the bundle with `esm` format. I don't know if this case can be detected when running esbuild so maybe throwing a warning can help to avoid exporting an empty function.
