### ISSUE TITLE
suggestion to pin pr with 0.9.0 wip and also link it in docs

### ISSUE THREAD

**Issue by vladmandic** [evanw/esbuild#939]
i've just updated to 0.9.0 and got hit with no less than 5 breaking changes (metafile and banner changes, removal of service, etc.)  
none bad and all are desirable, but took some searching to fix them  

suggestion to pin your pr <https://github.com/evanw/esbuild/pull/924> with 0.9.0 wip notes as top-level issue and also link it in docs

**Comment by heyheyhello** [comment]
It's semver versioning. The 0 means that minor version changes are breaking changes. Evan said that as the first line in the changelog too.

**Comment by vladmandic** [comment]
i understand that and i forced major version update myself (eyes wide open).  
but documentation of changes is not easy to find as the notes in the PR that is most helpful is closed as merged.

**Comment by heyheyhello** [comment]
It's on the front page of https://github.com/evanw/esbuild in all caps as CHANGELOG.md which is a common community practice... I don't mean to argue about it but I think the rollout was done well

**Comment by avindra** [comment]
Been packaging [`esbuild`](https://build.opensuse.org/package/show/devel:languages:javascript/esbuild) since January and here is what I've observed:

All change notes can be found on the release tag on GitHub. E.g., for `0.9.0`:

https://github.com/evanw/esbuild/releases/tag/v0.9.0

Similarly it's reflected in `CHANGELOG.md`:

https://github.com/evanw/esbuild/blob/master/CHANGELOG.md#090

Between these, I can always find what I need.

**Comment by vladmandic** [comment]
ok, i guess i'll close this suggestion.
