### ISSUE TITLE
CI/CD Setup

### ISSUE THREAD

**Issue by itshaydendev** [evanw/esbuild#94]
Just thinking how this could benefit from a CI/CD solution. Like, running all your tests and stuff as part of every push.

Deploying to NPM on every new tag.

That sorta thing. If you wanted, as long as I knew what to run, I could throw together a GitHub Actions config file for you! :)

**Comment by evanw** [comment]
Wow, that'd be great! I've wanted to do this, mainly for running tests on Linux, macOS, and Windows. I already did the hard work of getting the tests running on Windows but I haven't done the GitHub Actions thing yet because I haven't used it before. The commands I'd want to run on all three platforms are:

```
go test ./internal/...
npm ci
node scripts/verify-source-map.js
node scripts/end-to-end-tests.js
node scripts/js-api-tests.js
```

This is essentially just `make test`. I was thinking of not running these core tests with `make` so people don't have to install the make toolchain on Windows to run tests locally. Later on I'll probably move this to a `npm test` script but I figure this would be a good start.

**Comment by itshaydendev** [comment]
Due to npm/cli#558, I'm gonna have to use `npm i` over `npm ci` but the implementation is basically sorted. https://github.com/itshaydendev/esbuild/actions

**Comment by itshaydendev** [comment]
I'll make a PR once this runs
