### ISSUE TITLE
add only rollup speed 

### ISSUE THREAD

**Issue by danny007in** [evanw/esbuild#949]

**Comment by lukeed** [comment]
This has been the rationale (and requirement), yes, however I still think it would make sense to add secondary benchmarks that track _bundling_ speed only. The current benchmarks are _effectively_ esbuild vs terser, since all candidates rely on terser for minification... and terser is not known for its speed to begin with. (Requires its own extra parsing step, maintains separate AST, separate traversal, etc.)

While it's by (good) design that esbuild avoids this problem, I think it'd be worthwhile to add these extra benchmarks to put an end to the doubts/murmurs I've seen circling. I'd suggest a pure-bundle benchmark (no typescript, no `target` translation, and no minify for any candidate) so that we can actually measure the overhead of each _bundler_ itself and not the Babels and/or the Tersers that must typically come with them. I think the results would show that the difference isn't _as_ drastic, but it'd still show how much faster esbuild is in a direct apples-to-apples comparison (even if it's not representative of a complete workflow).

This allows the current benchmark to be called the "comprehensive" or "production" benchmark. Anyone interested in this extra chart can find it in a `/benchmark` directory or on the website. Doesn't need to be highlighted, but it should be there for those doubting/shrugging off the current charts IMO.

**Comment by evanw** [comment]
I'm closing this issue because I'm not planning on doing this. There is a combinatorial explosion of possible feature subsets to benchmark and I don't think esbuild's website is the right place to do that.
