### ISSUE TITLE
Inject script tag into html after bundling (using with React)

### ISSUE THREAD

**Issue by oze4** [evanw/esbuild#96]
I love this project and was looking for the ability to inject built files, as script tags, into my `index.html` file after bundling.  I was not able to find anything online about injecting script tags with `esbuild`, so forgive me if this type of functionality is out of scope.

The functionality I am looking for is comparable to the [`HtmlWebpackPlugin`](https://webpack.js.org/plugins/html-webpack-plugin/), in a `webpack` world...

Regardless, thank you for your amazing work! :)

**Comment by evanw** [comment]
If esbuild does support ways of working with HTML, I've been thinking that the solution would look more like #31 where you give esbuild a HTML file with `<script>` tags already in it and then esbuild would add the linked JavaScript files as entry points, build them, and generate a new HTML file with the `<script>` tag rewritten to point to the generated JavaScript bundle. This is similar to how Parcel works.

The reason is because people using things like `HtmlWebpackPlugin` potentially have a lot of custom requirements, and it wouldn't make sense to add all of that to esbuild as built-in options. There's a whole template system and many configuration options. Using a HTML file as an entry point naturally gives you complete control over exactly what the HTML file looks like and lets esbuild just handle the bundling part.

However, if that doesn't work and something like `HtmlWebpackPlugin` is still desired, it should be very easy for someone else to build it as a wrapper for esbuild or as a post-processing step to call after esbuild is done. That way people can address those custom requirements without that complexity being added to esbuild itself.

**Comment by oze4** [comment]
@evanw thank you very much for your response!  I suppose I was using the webpack plugin as an example, not exactly looking for a 1:1. Using an HTML file as an entry point sounds like a solid idea to me :smile: 

Regardless of this feature, esbuild has made it extremely simple, quick, and easy to bundle/transpile code. Truly an amazing project and it's exactly what I have been searching for. So much easier and straight forward to use than Rollup or Webpack, as far as bundling/transpiling is concerned. 

It also looks like some folks have turned esbuild into an [webpack plugin](https://github.com/sorrycc/esbuild-webpack-plugin) so at the very least I could use esbuild inside webpack along with the HtmlWebpackPlugin for React projects. 

Thanks again for your response!

**Comment by ChildishGiant** [comment]
I'm going to be using ejs to insert the script tags with appropriate integrities etc

**Comment by vikasgarghb** [comment]
@ChildishGiant How did you integrate ejs with esbuild?

**Comment by ChildishGiant** [comment]
My script has a lot extra but basically I wait for esbuild to finish and then run a script that calls ejs

```js
    esbuild.build({
      entryPoints: ['src/main.js'],
      bundle: true,
    }).catch(() => process.exit(1)).then(() => {
      // Generate html
      require('./makeHTML')
    }).catch(() => process.exit(1))
```

makeHTML:

```js
// Compile ejs -> html
ejs.renderFile('./src/src.ejs', replacements, {}, function (err, str) {
  if (err) console.error(err)   
  fs.writeFileSync(path.join(__dirname, `../../public/${out}`), str)
})
```

More reading: https://ejs.co/#docs

**Comment by n19htz** [comment]
> My script has a lot extra but basically I wait for esbuild to finish and then run a script that calls ejs
> 
> ```js
> esbuild.build({
>   entryPoints: ['src/main.js'],
>   bundle: true,
> }).catch(() => process.exit(1)).then(() => {
>   // Generate html
>   require('./makeHTML')
> }).catch(() => process.exit(1))
> ```
> 
> makeHTML:
> 
> ```js
> // Compile ejs -> html
> ejs.renderFile('./src/src.ejs', replacements, {}, function (err, str) {
>   if (err) console.error(err)   
>   fs.writeFileSync(path.join(__dirname, `../../public/${out}`), str)
> })
> ```
> 
> More reading: https://ejs.co/#docs

How to deal with requires inside of ejs files?
for example:
```
<img src="<%= require('../../assets/images/logo.svg')%>" class="main-logo__img"/>
```
