### ISSUE TITLE
compatible problem with pnpm when multiple esbuild version exists

### ISSUE THREAD

**Issue by hardfist** [evanw/esbuild#963]
It seems that pnpm will do some special tricks to bin files, which will cause esbuild fails when multiple esbuild version exisits,(it may be a bug of pnpm https://github.com/pnpm/pnpm/issues/3238), but It's kind of unusual to make js entry files rely on bin files(it's usual that bin file relys on main js entry files), maybe not put the real bin into bin folder could solve the issue.

**Comment by hardfist** [comment]
I think I find the reason, because esbuild modify bin file in post-install script, which violates pnpm's  the hard-link & content-hash strategy, because different version of esbuild's bin's content is same before post-install , so different esbuild shared same hard-link of the same file(content-hash&hard-link strategy), but in post-install the both change their bin file, but because the use the same hard-link ,the last modify will modify the result for both version, which will cause one version get wrong result, I currently change hard-link strategy to copy(mac not support COW currently), but I think esbuild could change the strategy so as to be compatible with pnpm's hard-link strategy.

**Comment by evanw** [comment]
I made a change that I think might fix this: #970. It uses `fs.renameSync` instead of `fs.writeFileSync` which I assume doesn't mutate the hard-linked data. I'm not sure how to write a test for this though. Is it possible for you to verify that the code in that PR works somehow? I usually test this kind of stuff by running `make platform-neutral` to build the package into the `npm/esbuild` directory and then using `npm pack` to generate a `*.tgz` package that I can then `npm install` somewhere else. Not sure if it's possible to do that with pnpm or not as I am very unfamiliar with pnpm.

**Comment by hardfist** [comment]
could you publish an alpha version so I can test it , there's somethings wrong with pnpm's link so it's not easy to test an unpublished version

**Comment by evanw** [comment]
I'm just going to try shipping it normally and see how that goes. You can try it out in the next release.

**Comment by evanw** [comment]
This was published btw. Let me know if it's working for you now or not.
