### ISSUE TITLE
Certain imports are not being bundled

### ISSUE THREAD

**Issue by jayair** [evanw/esbuild#966]
First off, I really love the project! Thank you for all the hard work.

I'm having a weird issue where a specific import is not being bundled. I'm not too familiar with TS so maybe I'm doing something wrong.

I created a repo to reproduce this — https://github.com/jayair/esbuild-util-bundle-issue

I'm running

```bash
$ yarn
$ npx esbuild lib/index.ts --bundle --format=cjs --platform=node --outdir=. --tsconfig=tsconfig.json --metafile=meta.json
```

The `lib/index.ts` just has.

```ts
import {logMessage} from 'util/logger';

export default function main(): void {
  logMessage()
}
```

The resulting metafile does not have the import listed.

But if I rename `util/` to anything else, say `new/` and move the directories. It works fine. What am I doing wrong?

**Comment by hardfist** [comment]
node have an builtin module called util

**Comment by jayair** [comment]
Oh I see. I'm not too familiar with how TS resolves these imports but does it not work because `util` is a built-in? Is this documented somewhere on the TS side?

Feel free to close this if it's not esbuild related.

**Comment by Zuckjet** [comment]
> Oh I see. I'm not too familiar with how TS resolves these imports but does it not work because `util` is a built-in? Is this documented somewhere on the TS side?
> 
> Feel free to close this if it's not esbuild related.

As hardfist pointed "node have an builtin module called util".  If you have a util folder in your project, you can change your import to `import { logMessage } from './util/logger';`. Since the import path starts with a dot, it will be treated as local file not internal.

For typescript's module resolution, you can read this [doc](https://www.typescriptlang.org/docs/handbook/module-resolution.html#node)

**Comment by evanw** [comment]
It looks like maybe path resolution for node's built-in `util` package doesn't actually capture subpaths. So maybe it's possible to get this to work by building a special "node externals" path resolution instead of using esbuild's built-in externals path resolution for these node modules. But yes for now using a relative path will work.

**Comment by jayair** [comment]
Got it. Let me look into how TS does this. Thanks!
