### ISSUE TITLE
Building from source with plugin support?

### ISSUE THREAD

**Issue by retorquere** [evanw/esbuild#969]
[this](https://esbuild.github.io/getting-started/#build-from-source) says local builds don't have plugin support -- I intend to experiment with esbuild to see if my use-case for xpcom plugins can be supported, but I'd need plugin support. Is just more difficult to get plugin support for local builds, or is there a structural reason local builds cannot have plugin support?

**Comment by evanw** [comment]
It's not that local builds don't have plugin support. It's that the native build doesn't (local or not). This is the same for the native build published to npm. The reason is that using plugins requires using the JavaScript or Go APIs instead of the command-line interface.

If you want to use plugins but need to be using a local build of esbuild for some reason (i.e. you're modifying the internals of esbuild itself) you have two options:

* If you only need to modify esbuild's internal Go code and don't need to modify esbuild's internal JavaScript code, then you can actually just build the Go code and tell the `esbuild` npm package to swap it out at run-time by setting the `ESBUILD_BINARY_PATH=...` environment variable before you run your JavaScript build script. In this case you could just install the `esbuild` package that has been published to npm into your project as long as it's the same version as the local esbuild code.

* If you need to modify esbuild's internal JavaScript code, then you can run `make platform-neutral` (or possibly just `node scripts/esbuild.js ./esbuild` if you don't have `make` installed) to generate the npm package, then run `npm pack` in the `npm/esbuild` directory to generate the package file, then run `npm install path/to/pack.tgz` in your project to install the local version of esbuild.

    This is automated in the `installForTests` function so you could also just do this:

    ```js
    const esbuild = require('./your-repos/esbuild/scripts/esbuild.js').installForTests()
    esbuild.build({ ... })
    ```

If you don't need to modify esbuild's internals and just want to use plugins, then I recommend just installing the `esbuild` package from npm and using that instead of trying to use a local build of esbuild.

**Comment by retorquere** [comment]
That's what I have currently, but I'm really keen to get esbuild going for my projects, and I need a different output format for that. I'm tinkering with jscodeshift to do postprocessing on the esm export, but I figured I might also give adding the actual XPCOM module format to esbuild.

**Comment by evanw** [comment]
Closing this as this question has been answered. The instructions for doing this are listed above.
