### ISSUE TITLE
Community

### ISSUE THREAD

**Issue by Aslemammad** [evanw/esbuild#986]
Hello esbuild devs, I hope you are doing well. 👋🏻
As you know, many Open-source communities now have a discord server to have more chat about the development process or even learning the tool. 
I wanted to know, is there any discord server for esbuild? Because I wanted to ask the contributors the best issues/bugs for new contributors to solve and send PR (I'm a new go dev, inspired by this repo, but I do some open source in JS/TS). ♥️

**Comment by evanw** [comment]
Thanks for reaching out. I am not aware of a Discord server for esbuild at the moment. And I'm not looking for contributions for contributions' sake. If you have a specific problem with esbuild or there is some change that you would like to see, it's best to file an issue so we can work through it together.

**Comment by zaydek** [comment]
I’m also interested in some kind of community space in general. That being said, having thought about this, I think GitHub is serving well enough for now. GitHub has a better search / indexing experience (posts are more discoverable) and is public by default (no authentication needed).

Maybe this topic should be revisited post 1.0.

**Comment by Aslemammad** [comment]
Feel free to re-open after v1.0

**Comment by quantuminformation** [comment]
would love a discord

**Comment by WagnerMoreira** [comment]
a discord server would be awesome, I would be one of those guys helping people and answering questions if we had a server

**Comment by zmzlois** [comment]
any updates on this?

**Comment by onzag** [comment]
The problem is that when you are learning and you can't figure what is going on or can't quite grasp some obscure option you need, if you ask via github issue you will be quickly shutdown for asking a lot of questions that you would figure out yourself if you just happened to know where to look, "hint, you didn't know where to look".

So are you going to be comfortable with a gazillion questions from confused beginners, likely repeats since they can't even phrase the question or find this information hence they ask.
