### ISSUE TITLE
warning: "@-ms-viewport" is not a known rule name with AntD

### ISSUE THREAD

**Issue by mikecann** [evanw/esbuild#997]
Im running esbuild 0.9.3 and everything works great (incredible work BTW) but I am getting a warning during build: 

```
 > node_modules/antd/dist/antd.css:56:0: warning: "@-ms-viewport" is not a known rule name
    56 │ @-ms-viewport {
       ╵ ~~~~~~~~~~~~~

1 warning
```

I dont think im doing anything special just importing the CSS as the [ant docs suggest](https://ant.design/docs/react/getting-started).

Not sure if this is related to: https://github.com/evanw/esbuild/issues/955 or not. Is AntD doing something special? If so is there a way of surpressing this warning?

**Comment by evanw** [comment]
It looks like this is an ancient CSS annotation for mobile versions of Internet Explorer. I haven't added support for this because it sounds like [it's an anti-pattern](https://developer.mozilla.org/en-US/docs/Web/CSS/@viewport) that isn't supposed to be used. However, I can add support for this to turn off the warning.

**Comment by mikecann** [comment]
@evanw its up to you mate. AntD is a very popular library tho so I suspect a lot of people are going to run into this at some point. 

Alternatively if you would prefer it, I could bring it up with Ant and see if they can remove it now?
