### ISSUE TITLE
Optimization: could one limit the number of entry points?

### ISSUE THREAD

**Issue by eloff** [evanw/esbuild#998]
I've noticed the linker uses a lot of bitSets (one per chunk/part) and that these involve lots of allocations and indirection as it's implemented a a []byte. Furthermore, this []byte is converted to a string for use as a map key in the linker, so this causes even more allocations.

If it's possible to set a max upper bound on the number of entry points supported (e.g. 64 or 256) one could use an inline array or even a uint64 field. This would avoid allocation for the slice, and the indirection and potential cache miss when accessing it. Additionally because these fields are comparable, the struct itself could be used as a map key, eliminating the need to convert it to a string and those allocations as well.

I think it's not unreasonable to do this given no practical application would have that many entry points, so likely no users would be affected. Do you agree?

With your blessing, I would create a pull request for this change.

**Comment by evanw** [comment]
I considered doing this. The typical pattern is to have a block of fixed-sized memory and then another block of lazily-allocated sparse memory for overflow to avoid needing a limit. But that complicates the dispatch logic. I also didn't optimize this because it didn't show up as a bottleneck.

The impact of these allocations is going to be greatly reduced soon. I am removing the optimization where code splitting happens at the part level. Code splitting will soon happen at the file level instead (this is necessary for correct top-level await semantics). In that case, the impact of these allocations will be even more insignificant.

I think one common use for this many entry points is to transform each file in your code base 1:1 into the output file with bundling off. In that case you could easily end up with a very large number of files, and I don't want the default bit set size to contain many thousands of bits just in case they are needed.

So I'm not interested in a PR for this change.

**Comment by evanw** [comment]
Closing. I'm not planning on doing this for the reasons above.

**Comment by eloff** [comment]
Hi evanw,

Yeah that makes sense, if code splitting happens at the file level, then this doesn't matter anymore.

I'm quite impressed by what you've built here, especially given you've been full-time as a CTO at Figma. Thanks for building it and sharing it with the world. You're clearly one of those mythical 10x developers. I've only bumped into a couple of people in my 20 year career for which I can say that with confidence.

Anyway I hope I don't make you feel uncomfortable, I just want to give recognition where it is due, because open-source is a thankless job at times.
