### ISSUE TITLE
warnings from node_modules code

### ISSUE THREAD

**Issue by alok-runner** [evanw/esbuild#999]
I'm getting this ignored import warning when I have a node module that depends on @material-ui/core. 

```
 > node_modules/@material-ui/pickers/esm/index.js:8:7: warning: Ignoring this import because "node_modules/@material-ui/core/esm/Typography/index.js" was marked as having no side effects
     8 │ import '@material-ui/core/Typography';
       ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   node_modules/@material-ui/core/package.json:51:2: note: "sideEffects" is false in the enclosing "package.json" file
    51 │   "sideEffects": false,
       ╵   ~~~~~~~~~~~~~
```

I've read that warnings from inside node_modules should be silenced automatically, but I still see this warning.

**Comment by evanw** [comment]
This code is very strange. I'm looking at their repo here and trying to figure out how this happened: https://github.com/mui-org/material-ui-pickers. It looks like maybe this is happening because their build process is ignoring the `sideEffects` annotation?

Only some warnings inside `node_modules` are silenced. Warnings related to bundling are not silenced when bundling, since they are really the only way you have of debugging a broken bundle. This has caught real bugs in the past such as https://github.com/tensorflow/tfjs/issues/4248#issuecomment-729168686.

That said, this request seems reasonable and I can try silencing this warning in this case. But I may bring this warning back in the future if someone hits a case where they're getting a broken bundle with esbuild due to an import in a `node_modules` file with an incorrect `sideEffects` annotation. In that case (and in the meantime) you can use `--log-level=error` to silence warnings.

**Comment by alok-runner** [comment]
This makes me want more granular logging controls, and perhaps lower logging level for code we don't control.

**Comment by evanw** [comment]
You can get granular logging controls by using the API with `logLevel: 'silent'` and then filtering the returned `warnings` array.
